(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"CO_Safety_300x250_atlas_P_1", frames: [[0,0,232,87]]},
		{name:"CO_Safety_300x250_atlas_NP_1", frames: [[0,0,300,250]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Buttonshad = function() {
	this.initialize(ss["CO_Safety_300x250_atlas_P_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.safety_img1_300x250 = function() {
	this.initialize(ss["CO_Safety_300x250_atlas_NP_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.HS_logowhite = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ap9EXIAHnRINagKIgCh7IGDgCIAZKDgAFdgfQgVAOgIAYQgGAUAAAZQAAAaAGATQAJAZAVAOQAVAOAgAAQAyAAAeggQADgDgEgCIgZgYQgCgDgEADQgSARgZAAQgfAAgHgZIgDgKQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIBxAAQAEAAAAgEQAAglgGgUQgIgYgVgOQgVgOgfABQgeAAgVANgAgnAvQgVAQAAAdQAAAdASAPQARAOAaAAQAjAAAQgVIABAAIAAANQAAADAEAAIArAAQADAAAAgDIAAh4QAAgjgSgPQgUgRgtABQgqAAgaASQgDACACADIARAeQACADADgDQAQgKAZAAQAWAAAIAEQAIAHAAANIAAAHQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIghAAQgkAAgUAOgAnMBXIgZAdQgCACACADQAiAdAzAAQAoAAAWgSQAVgRABgeQAAgyg/gGIgUgCQgPgCgGgEQgFgDAAgHQAAgOAYgBQAbAAAXAOQAEADACgDIAVgaQADgDgDgDQgegWguAAQgkgBgVARQgUAQAAAaQAAAzA9AHIAVABQAQACAGAEQAFAEAAAHQAAASgdAAQgfAAgagVIgDgBIgDABgACfgkIAACyQAAADAEAAIAuAAQAEAAAAgDIAAhjQAAgnAdgCQAMAAAPAJQADABACgCIAWgmQACgEgDgCQgNgLgUABQgjgBgOAYIAAAAIAAgPQAAgFgEAAIguAAQgEAAAAAFgAieAiIAABsQAAADAEAAIAuAAQAEAAAAgDIAAh2QAAgegRgTQgRgUgeABQghAAgPAUIgBAAIAAhZQAAgDgEAAIguAAQgEAAAAADIAAD/QAAADAEAAIAuAAQAEAAAAgDIAAhsQAAgPAIgKQAIgJAOAAQAdAAAAAig");
	this.shape.setTransform(25.025,83.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAaAAQABABABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_1.setTransform(27.15,92.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeATQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBQAAgGACgIQAHgTAXgBQAZABAGATQACAGAAAIQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_2.setTransform(65.075,85.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AqIk4IUcAvIAII0I03AOgAhWAjQgVAQAAAeQgBAdAUAPQAQAOAbAAQAkAAAPgVIAAANQAAADAEAAIArAAQAEAAAAgDIAAh5QAAgjgSgPQgUgRgsAAQgrAAgcATQgCACACADIARAfQACACADgBQARgMAZAAQAWAAAIAGQAHAGAAAMIAAAHQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIghAAQgjAAgVAOgAkagrQgVAOgIAZQgHATAAAZQAAAXAHAWQAIAaAWAOQAVAOAgAAQAzAAAdggQADgDgDgCIgagYQgCgDgDADQgSAQgZAAQgfAAgIgYQgCgDgBgIQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIBxAAQAFAAAAgEQAAgmgGgTQgJgZgUgOQgWgOgfAAQgeAAgVAOgADcgxIAAAhQAAAEAFAAIALAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAABUQAAAhAOAPQAOAPAgAAIAUAAQAEAAABgEIAAgnQgBgDgEAAIgJAAQgJAAgDgEQgFgFAAgKIAAhSQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAYAAQAEAAABgEIAAghQgBgDgEAAIgYAAQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAgyQAAgEgDAAIguAAQgFAAAAAEIAAAyQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgLAAQgFAAAAADgABth9IAADKQAAAfANAPQAOAOAfAAIAVAAQADAAAAgEIAAgnQAAgDgDAAIgIAAQgRAAAAgSIAAjGQAAgEgEAAIgvAAQgDAAAAAEgAHggBQAIAIAAAQIAABsQAAADADAAIAvAAQAEAAAAgDIAAh3QAAgegRgTQgQgUgfAAQghAAgQAWIAAAAIAAhaQAAgEgEAAIguAAQgFAAAAAEIAAEAQAAADAFAAIAuAAQAEAAAAgDIAAhsQAAgQAIgIQAIgKAOAAQAOAAAHAKgAmpgBQAHAIAAAQIAABsQAAADAFAAIAuAAQAEAAAAgDIAAh3QAAgegRgTQgRgUgfAAQghAAgPAWIAAhaQAAgEgEAAIgvAAQgDAAAAAEIAAEAQAAADADAAIAvAAQAEAAAAgDIAAhsQAAgQAIgIQAHgKAOAAQAOAAAIAKg");
	this.shape_3.setTransform(-21.95,31.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAbAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_4.setTransform(-24.5,39.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeASQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAgGADgIQAHgUAXAAQAYAAAIAUQACAIAAAGQAAABgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-45.05,31.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AJdAwIAcgBQABAJANAAQAPABAAgNIAAgIQgIAFgMAAQgRAAgLgMQgKgLAAgSQAAgSAKgLQALgMARAAQANAAAIAHIAAgFIAaAAIAABRQAAARgLALQgLAKgTAAQgmAAgFgggAJ4AAQAAASAPAAQAHgBAEgEQAEgEAAgIIAAgCQAAgHgEgFQgFgEgGAAQgPAAAAARgALLAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgALbAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAILAeQgLgLAAgTQAAgSALgLQAMgMASAAQASAAAKAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgKAHQgLAHgOAAQgTAAgMgLgAI0gIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgAFOAZQgRgQAAgaQAAgaARgRQAQgQAbAAQAbAAARAQQARARAAAaQAAAagRAQQgRAQgbAAQgbAAgQgQgAFjgpQgIAJAAAPQAAAPAIAJQAIAIAOAAQAOAAAIgIQAJgJAAgPQAAgPgJgJQgIgIgOgBQgOABgIAIgACHAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgACXAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAAJAeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgPAAQgTAAgLgLgAAygIQgBgMgLAAQgKAAgBAMIAXAAIAAAAgAiVASQAAgWAigCIAJAAIAAgEQAAgIgGAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAh6AQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAlOAfQgNgKAAgTIAegBQAAAGAFAEQAFAFAHAAQANgBAAgIQAAgHgTgFQgTgFgIgGQgLgHAAgQQAAgQAKgJQALgMAUAAQAUAAAMALQAMAJABASIgeABQAAgNgOAAQgMAAAAAKQAAAEAEACQADADAMADQATAEAIAHQALAJAAANQAAASgMAKQgMAIgTAAQgVAAgNgKgAoUANIAAgdIgOAAIAAgXIAOAAIABgZIAbAAIAAAZIARAAIAAAXIgRAAIAAAWQAAALALAAIAGgBIAAAYIgNABQggAAAAgcgAqjASQAAgWAigCIAKAAIAAgEQAAgIgHAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAqIAQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAr0AeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgOAAQgTAAgMgLgArLgIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgANWAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAhOIAaAAIAAAFQAGgHAOAAQAOAAAIAIQAJAJAAAPIAAAwgAHGAnIAAhOIAbAAIAAAGQAHgHAOAAIAAAbQgJAAgGAFQgFAEAAAGIAAAlgADlAnIAAg3IgOAAIAAgXIAOAAIAAgFQAAgQAKgKQAKgJAQAAIAJAAIAAAZIgGgBQgFAAgDADQgDADAAAEIAAAGIARAAIAAAXIgRAAIAAA3gAg7AnIAAhOIAbAAIAAAGQAGgHAPAAIAAAbQgKAAgFAFQgFAEAAAGIAAAlgAjAAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAGgGAMAAQAOAAAIAIQAJAJAAAPIAAAwgAmnAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAHgGALAAQAOAAAIAIQAJAJAAAPIAAAwgApJAnIAAh1IAcAAIAAB1gAstAnIAAgsIgmAAIAAAsIgeAAIAAhwIAeAAIAAAqIAmAAIAAgqIAeAAIAABwg");
	this.shape_6.setTransform(0.175,134.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HS_logowhite, new cjs.Rectangle(-88.7,0,177.5,143), null);


(lib.HEAD3type = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANQgGgFAAgIQAAgHAGgGQAEgEAIAAQAIAAAGAEQAFAGAAAHQAAAIgFAFQgGAFgIABQgIgBgEgFg");
	this.shape.setTransform(131,43.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAVAxIgUg1IgUA1IgYAAIgchKIgDgFIgDgBIgFAAIAAgRIA1AAIAAARIgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAAAgBABQgBACABADIAEAJIAFAPIAGAPIAFgPIAFgPIADgJQACgDgCgCQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgEAAIAAgRIAwAAIAAARIgEAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAAAgBABQgBACABADIAEAJIAGAPIAGAPIAGgPIAEgPIADgJQABgEgBgBQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAgBAAIgFAAIAAgRIAoAAIAAARIgGAAIgCABQgCABgBAEIgaBKg");
	this.shape_1.setTransform(120.25,40.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgbAtQgMgGgGgMQgHgMgBgPQABgPAHgLQAGgMAMgGQAMgHAPAAQAQAAAMAHQAMAGAGAMQAHALAAAPQAAAPgHAMQgGAMgMAGQgMAGgQABQgPgBgMgGgAgPgZQgEAIAAAQIAAADQAAAQAEAIQAGAHAJAAQAKAAAGgHQAEgIAAgQIAAgDQAAgQgEgIQgGgHgKAAQgJAAgGAHg");
	this.shape_2.setTransform(106.25,40.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAGAyIAAgRIAGAAIADgBQABgBAAgEIAAgmQgBgJgDgEQgDgEgHAAQgHAAgFAGQgFAHAAANIAAAdQAAAEABABIADABIAGAAIAAARIg1AAIAAgRIAHAAIADgBQABgBAAgEIAAgxIgBgFQgBgBAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAIgHAAIAAgRIATAAIAOgBIAKgCIAAASQAFgJAIgFQAHgEAMAAQAPAAAJAJQAHAKAAATIAAAmQAAAEACABIACABIAHAAIAAARg");
	this.shape_3.setTransform(94.55,40.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgZAtQgMgHgGgLQgHgMAAgPQABgPAGgLQAGgMAMgGQAMgHAOAAQAZABAMANQANAOAAAZIAAAEIhDAAQABAMAHAHQAFAHAMAAQAJAAAGgFQAGgEADgIIAQAKQgCAIgHAGQgFAGgJADQgKADgNABQgQgBgMgGgAASgIQAAgOgDgFQgFgGgIAAQgIAAgEAGQgFAGgBANIAiAAIAAAAg");
	this.shape_4.setTransform(78.25,40.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZBEIAAgSIAGAAIAEgBQABgBAAgEIAAhUIgBgFIgEgBIgHAAIAAgSIAVAAIAMgBIALgBIAABuQAAAEABABIACABIAGAAIAAASg");
	this.shape_5.setTransform(69.85,38.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgGA+QgJgHgEgKIgFAVIgYAAIABgFIAAgKIAAgSIAAhKIgBgGQAAAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgHAAIAAgSIAUAAIAOgBIAKgBIAAA2QAEgJAIgFQAHgFANAAQAMAAAKAGQAJAHAFALQAFALAAAPQAAAPgFANQgFALgKAHQgKAFgNABQgOAAgIgHgAgIgGQgGAGAAAPIAAAEQAAAPAGAHQAFAIAIgBQAJABAGgIQAFgHAAgPIAAgEQAAgPgFgGQgGgHgJAAIgBAAQgIAAgEAHg");
	this.shape_6.setTransform(60.625,38.45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgtAsQgIgHABgLQgBgNAJgIQAJgGAOgEQAPgEAQgCIAAgGQAAgIgEgEQgFgEgIAAIgGAAIgEABIACAEIABAFQgBAHgFAEQgEAEgIABQgJAAgEgFQgEgEgBgIQAAgJAHgGQAFgGALgDQALgDAOAAQAXAAALAIQAMAIgBASIAAAqIABAFQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAIAHAAIAAASIgkAAIgFgHIgCgJQgDAFgFAEQgEAFgHACQgHACgIABQgOgBgIgHgAgNAHQgIAEgBAJQABAGADADQADADAFAAQAKAAAEgGQAGgHAAgKIAAgIQgNACgKAEg");
	this.shape_7.setTransform(49.15,40.175);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgZBEIAAgSIAHAAIADgBQAAgBAAgEIAAhUIAAgFIgDgBIgIAAIAAgSIAUAAIAOgBIAKgBIAABuQAAAEABABIACABIAGAAIAAASg");
	this.shape_8.setTransform(40.35,38.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgaBGIAAgSIAHAAIADAAIABgGIAAgvIgBgHQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAAAAAIgHAAIAAgSIAUAAIANgBIAKgBIAABLIAAAGIADAAIAHAAIAAASgAgMgnQgGgFAAgIQAAgHAGgFQAEgFAIAAQAIAAAGAFQAFAFAAAHQAAAIgFAFQgGAFgIAAQgIAAgEgFg");
	this.shape_9.setTransform(34.35,38.05);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgtAsQgHgHAAgLQAAgNAIgIQAJgGAOgEQAPgEAQgCIAAgGQAAgIgEgEQgEgEgJAAIgGAAIgEABIACAEIAAAFQAAAHgFAEQgEAEgIABQgJAAgEgFQgEgEgBgIQAAgJAHgGQAFgGALgDQALgDAOAAQAYAAAKAIQALAIAAASIAAAqIABAFQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAIAHAAIAAASIgkAAIgFgHIgCgJQgDAFgFAEQgEAFgHACQgHACgIABQgOgBgIgHgAgNAHQgIAEgBAJQABAGADADQADADAGAAQAJAAAEgGQAGgHAAgKIAAgIQgNACgKAEg");
	this.shape_10.setTransform(25.85,40.175);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgLAxIghhKIgDgFIgDgBIgGAAIAAgRIA4AAIAAARIgHAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBACACADIAEALIAGAPIAGAQIAHgSIAHgPIAEgJQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAAAIgIAAIAAgRIAtAAIAAARIgGAAIgEABIgDAFIghBKg");
	this.shape_11.setTransform(14.325,40.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgtAsQgHgHAAgLQAAgNAIgIQAJgGAOgEQAPgEAQgCIAAgGQAAgIgEgEQgEgEgJAAIgGAAIgEABIACAEIAAAFQAAAHgEAEQgGAEgHABQgIAAgFgFQgEgEgBgIQAAgJAHgGQAFgGALgDQALgDAPAAQAXAAAKAIQALAIAAASIAAAqIABAFQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAIAHAAIAAASIgkAAIgFgHIgDgJQgCAFgFAEQgFAFgGACQgHACgIABQgOgBgIgHgAgNAHQgIAEgBAJQABAGADADQADADAGAAQAJAAAEgGQAGgHAAgKIAAgIQgOACgJAEg");
	this.shape_12.setTransform(3,40.175);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgYAxIgRgFIAAgaIAXAAIAAAQIAHABIAIAAQAHAAAEgCQAEgDABgGQgBgGgFgCQgGgDgJgBQgIgCgIgDQgIgDgFgFQgFgGAAgKQAAgQAMgJQALgIAUgBQAMABAKACQAKACAGADIAAAZIgWAAIAAgOIgGgCIgIAAQgGAAgEACQgFADAAAFQAAAEADACQADADAFABIAJACQAJABAIAEQAHADAGAFQAFAGAAALQAAAPgMAJQgLAJgVABQgMgBgLgCg");
	this.shape_13.setTransform(-12.025,40.175);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgLA5QgIgIAAgRIAAgxIgMAAIAAgQIAGgBQAGgBAEgDQADgCACgHIACgQIAVAAIAAAcIASAAIAAASIgTAAIAAAxQAAAHADADQADADAGAAIAFgBIADgBIAAATIgIACIgLAAQgQAAgIgHg");
	this.shape_14.setTransform(-20.275,38.875);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAGAyIAAgRIAGAAIADgBQABgBAAgEIAAgmQgBgJgDgEQgDgEgHAAQgHAAgFAGQgFAHAAANIAAAdQAAAEACABIACABIAGAAIAAARIg1AAIAAgRIAHAAIADgBQABgBAAgEIAAgxIgBgFQgBgBAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAIgHAAIAAgRIATAAIAOgBIAKgCIAAASQAFgJAIgFQAHgEALAAQAQAAAJAJQAHAKABATIAAAmQAAAEABABIACABIAHAAIAAARg");
	this.shape_15.setTransform(-29.55,40.025);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgZAtQgMgHgGgLQgHgMABgPQAAgPAGgLQAGgMAMgGQAMgHAOAAQAZABANANQALAOABAZIAAAEIhDAAQABAMAGAHQAHAHAKAAQAKAAAGgFQAGgEADgIIARAKQgDAIgGAGQgGAGgKADQgJADgMABQgRgBgMgGgAASgIQAAgOgDgFQgEgGgJAAQgIAAgFAGQgEAGgBANIAiAAIAAAAg");
	this.shape_16.setTransform(-41.15,40.175);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAkAyIAAgRIAFAAIAEgBQABgBAAgEIAAgkQgBgKgDgEQgDgFgHAAQgIAAgEAGQgEAHABAMIAAAeQAAAEABABIACABIAHAAIAAARIg0AAIAAgRIAGAAIADgBQAAgBAAgEIAAglQAAgJgDgEQgEgFgGAAQgIAAgEAGQgEAHABAMIAAAeQAAAEABABIACABIAGAAIAAARIg1AAIAAgRIAHAAIACgBQABgBAAgEIAAgxIgBgFQAAgBAAAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgHAAIAAgRIATAAIAOgBIAKgCIAAATQAFgJAHgFQAHgFALAAQANAAAFAFQAIAFACALQAFgKAIgGQAHgFANAAQAQAAAIAJQAJAJAAAUIAAAmQAAAEABABIACABIAHAAIAAARg");
	this.shape_17.setTransform(-55.5,40.025);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgLA5QgIgIAAgRIAAgxIgMAAIAAgQIAGgBQAGgBAEgDQADgCACgHIACgQIAVAAIAAAcIASAAIAAASIgTAAIAAAxQAAAHADADQADADAGAAIAFgBIADgBIAAATIgIACIgLAAQgQAAgIgHg");
	this.shape_18.setTransform(-68.325,38.875);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAGAyIAAgRIAGAAIADgBQAAgBAAgEIAAgmQAAgJgDgEQgDgEgHAAQgIAAgEAGQgFAHABANIAAAdQAAAEABABIACABIAGAAIAAARIg1AAIAAgRIAHAAIADgBQABgBAAgEIAAgxIgBgFQgBgBAAAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgHAAIAAgRIATAAIAOgBIAKgCIAAASQAEgJAJgFQAHgEALAAQAQAAAJAJQAHAKABATIAAAmQAAAEABABIACABIAHAAIAAARg");
	this.shape_19.setTransform(-77.6,40.025);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgaBGIAAgSIAHAAIADAAIABgGIAAgvIgBgHQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAIgGAAIAAgSIAUAAIANgBIAKgBIAABLIAAAGIAEAAIAGAAIAAASgAgNgnQgEgFgBgIQABgHAEgFQAFgFAIAAQAJAAAEAFQAFAFABAHQgBAIgFAFQgEAFgJAAQgIAAgFgFg");
	this.shape_20.setTransform(-86.85,38.05);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgcAtQgLgGgHgMQgGgMgBgPQABgPAGgLQAHgMAMgGQANgHAOAAQARAAAMAHQALAGAHAMQAGALAAAPQAAAPgGAMQgHAMgMAGQgMAGgQABQgQgBgMgGgAgOgZQgFAIAAAQIAAADQAAAQAFAIQAEAHAKAAQALAAAEgHQAFgIABgQIAAgDQgBgQgFgIQgEgHgLAAQgKAAgEAHg");
	this.shape_21.setTransform(-95.5,40.175);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("Ag5BEIAAgSIAGAAIADgBIABgFIAAhTIAAgGQgBAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgHAAIAAgSIAUAAIAOgBIAJgBIAAAUQAFgKAIgFQAHgFAMAAQANAAAKAGQAJAHAFALQAFAMABAPQgBAPgFAMQgGALgJAHQgKAFgNABQgMgBgGgEQgIgGgEgIIAAAbIABAFIADABIAHAAIAAASgAgJgnQgFAHAAAPIAAAEQAAAOAFAHQAGAHAIAAQAKAAAEgHQAGgHAAgOIAAgEQAAgOgGgIQgEgHgKAAQgIABgGAGg");
	this.shape_22.setTransform(-107.4,41.75);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("Ag6BEIAAgSIAIAAIACgBIABgFIAAhTIgBgGQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAAAAAIgIAAIAAgSIATAAIAPgBIAKgBIAAAUQADgKAJgFQAHgFAMAAQAOAAAJAGQAJAHAFALQAFAMAAAPQAAAPgFAMQgFALgKAHQgKAFgNABQgMgBgHgEQgHgGgEgIIAAAbIABAFIACABIAIAAIAAASgAgJgnQgFAHAAAPIAAAEQAAAOAFAHQAGAHAIAAQAJAAAGgHQAFgHAAgOIAAgEQAAgOgFgIQgGgHgJAAQgIABgGAGg");
	this.shape_23.setTransform(-119.7,41.75);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgtAsQgIgHAAgLQAAgNAJgIQAJgGAOgEQAOgEARgCIAAgGQAAgIgEgEQgFgEgIAAIgFAAIgFABIABAEIABAFQAAAHgEAEQgFAEgHABQgKAAgEgFQgFgEABgIQAAgJAFgGQAHgGAKgDQALgDAPAAQAXAAALAIQAKAIAAASIAAAqIABAFQAAAAAAAAQABABAAAAQAAAAABAAQAAAAAAAAIAHAAIAAASIgkAAIgEgHIgDgJQgCAFgFAEQgEAFgHACQgHACgHABQgPgBgIgHgAgMAHQgJAEAAAJQAAAGADADQADADAFAAQAKAAAFgGQAFgHAAgKIAAgIQgOACgIAEg");
	this.shape_24.setTransform(-131.25,40.175);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAGAyIAAgRIAGAAIACgBQABgBAAgEIAAgmQAAgJgDgEQgDgEgHAAQgIAAgEAGQgEAHgBANIAAAdQAAAEABABIADABIAGAAIAAARIg1AAIAAgRIAHAAIACgBQABgBAAgEIAAgxIgBgFQAAgBAAAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgHAAIAAgRIATAAIAOgBIAKgCIAAASQAFgJAIgFQAHgEAMAAQAPAAAIAJQAJAKgBATIAAAmQAAAEABABIADABIAHAAIAAARg");
	this.shape_25.setTransform(-7.9,16.625);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgbAtQgMgGgGgMQgHgMgBgPQABgPAHgLQAGgMAMgGQAMgHAPAAQAQAAAMAHQAMAGAGAMQAHALAAAPQAAAPgHAMQgGAMgMAGQgMAGgQABQgPgBgMgGgAgPgZQgEAIAAAQIAAADQAAAQAEAIQAGAHAJAAQAKAAAGgHQAEgIAAgQIAAgDQAAgQgEgIQgGgHgKAAQgJAAgGAHg");
	this.shape_26.setTransform(-19.75,16.775);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgYAxIgRgFIAAgaIAXAAIAAAQIAHABIAIAAQAHAAAEgCQAEgDABgGQgBgGgFgCQgGgDgJgBQgIgCgIgDQgIgDgFgFQgFgGAAgKQAAgQAMgJQALgIAUgBQAMABAKACQAKACAGADIAAAZIgWAAIAAgOIgGgCIgIAAQgGAAgEACQgFADAAAFQAAAEADACQADADAFABIAJACQAJABAIAEQAHADAGAFQAFAGAAALQAAAPgMAJQgLAJgVABQgMgBgLgCg");
	this.shape_27.setTransform(-29.975,16.775);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AguAyIAAgRIAHAAIADgBQABgBAAgEIAAgxIgBgFQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgHAAIAAgRIAUAAIAOgBIAKgCIAAAWQACgMAHgFQAHgFAJAAQALAAAHAHQAGAHAAANQAAAKgFAHQgGAFgJAAQgHAAgEgDQgEgEgBgGQAAgFADgDQACgEAEgCIgCgBIgEgBQgIAAgEAIQgEAIAAANIAAAbQAAAEABABIACABIAHAAIAAARg");
	this.shape_28.setTransform(-39.475,16.625);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgZAtQgMgHgGgLQgGgMgBgPQABgPAGgLQAHgMALgGQAMgHAPAAQAYABANANQAMAOgBAZIAAAEIhBAAQAAAMAHAHQAGAHALAAQAJAAAGgFQAGgEADgIIAQAKQgCAIgHAGQgFAGgKADQgIADgOABQgQgBgMgGgAATgIQAAgOgFgFQgDgGgJAAQgIAAgFAGQgEAGgBANIAjAAIAAAAg");
	this.shape_29.setTransform(-49.85,16.775);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("Ag6BEIAAgSIAHAAIADgBIABgFIAAhTIgBgGQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgIAAIAAgSIAUAAIAPgBIAJgBIAAAUQAEgKAJgFQAHgFANAAQANAAAJAGQAJAHAFALQAFAMAAAPQAAAPgFAMQgGALgJAHQgKAFgNABQgMgBgHgEQgHgGgEgIIAAAbIABAFIACABIAIAAIAAASgAgIgnQgGAHAAAPIAAAEQAAAOAGAHQAFAHAIAAQAJAAAGgHQAFgHAAgOIAAgEQAAgOgFgIQgGgHgJAAQgIABgFAGg");
	this.shape_30.setTransform(-61.45,18.35);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgaALIAAgVIA1AAIAAAVg");
	this.shape_31.setTransform(-70.6,16.75);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAGAyIAAgRIAGAAIACgBQABgBAAgEIAAgmQAAgJgDgEQgDgEgHAAQgIAAgEAGQgFAHABANIAAAdQAAAEABABIACABIAGAAIAAARIg1AAIAAgRIAHAAIADgBQAAgBAAgEIAAgxIAAgFQgBgBAAAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgHAAIAAgRIATAAIAOgBIAKgCIAAASQAEgJAJgFQAHgEALAAQAQAAAJAJQAHAKABATIAAAmQAAAEABABIACABIAHAAIAAARg");
	this.shape_32.setTransform(-79.75,16.625);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgaBGIAAgSIAHAAIADgBIABgFIAAgvIgBgHQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAIgGAAIAAgSIAUAAIANgBIAKgBIAABLIABAFIADABIAGAAIAAASgAgNgnQgEgFAAgIQAAgHAEgFQAFgFAIAAQAJAAAEAFQAFAFABAHQgBAIgFAFQgEAFgJAAQgIAAgFgFg");
	this.shape_33.setTransform(-89,14.65);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgZAtQgMgHgGgLQgHgMAAgPQABgPAGgLQAGgMAMgGQAMgHAOAAQAZABAMANQANAOAAAZIAAAEIhDAAQABAMAGAHQAGAHALAAQAKAAAGgFQAGgEADgIIARAKQgEAIgFAGQgGAGgJADQgKADgNABQgQgBgMgGgAASgIQAAgOgDgFQgFgGgIAAQgIAAgEAGQgFAGgBANIAiAAIAAAAg");
	this.shape_34.setTransform(-102.1,16.775);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgeBEIAAgRIAIAAIACgBQABgBAAgEIAAg4IgMAAIAAgRIAMAAIAAgFQAAgNAEgHQADgIAIgDQAGgDAMAAIALABIAHACIAAARIgDgBIgEAAQgFAAgDACQgDABgBAFQgBAEAAAIIARAAIAAARIgQAAIAAA4QAAAEABABIADABIAIAAIAAARg");
	this.shape_35.setTransform(-110.675,14.825);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgtAsQgIgHABgLQgBgNAJgIQAJgGAOgEQAPgEAQgCIAAgGQAAgIgEgEQgFgEgIAAIgGAAIgEABIACAEIABAFQgBAHgFAEQgEAEgIABQgJAAgEgFQgEgEgBgIQAAgJAHgGQAFgGALgDQALgDAOAAQAXAAALAIQAMAIgBASIAAAqIABAFQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAIAHAAIAAASIgkAAIgFgHIgCgJQgDAFgFAEQgEAFgHACQgHACgIABQgOgBgIgHgAgNAHQgIAEgBAJQABAGADADQADADAFAAQAKAAAEgGQAGgHAAgKIAAgIQgNACgKAEg");
	this.shape_36.setTransform(-119.6,16.775);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgdBCQgMgDgKgFIAAggIAaAAIAAAUIAMADIAMABQAIAAAGgEQAGgEgBgIQAAgGgDgEQgDgDgGgCIgRgFQgMgDgJgEQgKgFgFgHQgEgHgBgMQABgVAOgMQAOgLAaAAQANAAALACQALADAKAEIAAAgIgaAAIAAgTIgJgCIgKgBQgKAAgGAEQgFAEgBAIQABAGACADQADADAGACQAHADAJACQAMADAKAEQAJAEAGAHQAGAIAAANQAAANgGAKQgGAKgMAFQgNAGgRAAQgOAAgNgDg");
	this.shape_37.setTransform(-131.15,15.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD3type, new cjs.Rectangle(-139,0,289.1,52.8), null);


(lib.HEAD2type = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANQgGgFAAgIQAAgHAGgGQAEgEAIAAQAIAAAGAEQAFAGAAAHQAAAIgFAFQgGAFgIABQgIgBgEgFg");
	this.shape.setTransform(18.25,43.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag5BEIAAgSIAGAAIADgBIABgFIAAhTIAAgGQgBAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgHAAIAAgSIAUAAIAOgBIAJgBIAAAUQAFgKAIgFQAHgFAMAAQANAAAKAGQAJAHAFALQAFAMABAPQgBAPgFAMQgGALgJAHQgKAFgNABQgMgBgGgEQgIgGgEgIIAAAbIABAFIADABIAHAAIAAASgAgJgnQgFAHAAAPIAAAEQAAAOAFAHQAGAHAIAAQAKAAAEgHQAGgHAAgOIAAgEQAAgOgGgIQgEgHgKAAQgIABgGAGg");
	this.shape_1.setTransform(9.6,41.75);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgoApQgIgJAAgTIAAgnQAAgEgBgBIgCgBIgIAAIAAgRIAsAAIAAA9QAAAKADAEQAEADAHAAQAIAAAEgGQAEgGAAgNIAAgeQAAgEgBgBIgDgBIgJAAIAAgRIAuAAIAABIIAAAFQABABAAAAQAAAAABAAQAAABABAAQAAAAAAAAIAIAAIAAARIgUAAIgOABIgKABIAAgQQgFAIgIAFQgHAEgLAAQgQAAgIgJg");
	this.shape_2.setTransform(-2.5,40.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAFBEIAAgSIAGAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAAAAAgBIgBgDIgMgUIgOAMIAAAHQAAAEABABIADABIAGAAIAAASIg1AAIAAgSIAHAAIACgBQACgBAAgEIAAhUIgBgFIgDgBIgIAAIAAgSIAVAAIANgBIAKgBIAABUIAagZQABAAAAAAQAAgBAAAAQABAAAAgBQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAAAAAAAQgBAAgBAAIgJAAIAAgSIA2AAIAAASIgHAAIgFABIgEACIgQAOIAZAnIADAEIADABIAFAAIAAASg");
	this.shape_3.setTransform(-14.55,38.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgiAmQgPgOAAgYQAAgXAPgOQAOgNAYgBQAXAAALAJQAMAJAAAQQAAAKgGAGQgFAFgJAAQgJAAgEgEQgEgEAAgGQAAgHADgEQADgEAHgBQgCgEgEgBQgFgCgHAAQgKAAgHAIQgHAHABAQIAAADQAAAPAFAIQAGAIALAAQAKAAAFgFQAGgEAEgIIARAJQgEAMgLAIQgLAHgTABQgYgBgOgNg");
	this.shape_4.setTransform(-25.65,40.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZAtQgMgHgGgLQgGgMgBgPQABgPAGgLQAHgMALgGQAMgHAPAAQAYABANANQAMAOgBAZIAAAEIhBAAQAAAMAHAHQAGAHALAAQAJAAAGgFQAGgEADgIIAQAKQgCAIgHAGQgFAGgKADQgIADgOABQgQgBgMgGgAATgIQAAgOgFgFQgDgGgJAAQgIAAgFAGQgEAGgBANIAjAAIAAAAg");
	this.shape_5.setTransform(-36.35,40.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAGBEIAAgSIAHAAIACgBQABgBAAgEIAAgmQAAgIgDgFQgEgEgGABQgIgBgFAHQgEAFAAAPIAAAcQAAAEABABIACABIAHAAIAAASIg1AAIAAgSIAHAAIACgBQABgBAAgEIAAhUIgBgFIgCgBIgIAAIAAgSIAUAAIAOgBIAKgBIAAAzQAFgIAIgEQAHgFALAAQAQAAAIAJQAIAJAAATIAAAnQAAAEABABIACABIAHAAIAAASg");
	this.shape_6.setTransform(-47.8,38.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgiAmQgPgOAAgYQAAgXAPgOQAOgNAYgBQAXAAALAJQAMAJAAAQQAAAKgGAGQgFAFgJAAQgJAAgEgEQgEgEAAgGQAAgHADgEQADgEAHgBQgCgEgEgBQgFgCgHAAQgKAAgHAIQgHAHABAQIAAADQAAAPAFAIQAGAIALAAQAKAAAFgFQAGgEAEgIIARAJQgEAMgLAIQgLAHgTABQgYgBgOgNg");
	this.shape_7.setTransform(-58.95,40.175);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgtAsQgIgHAAgLQAAgNAJgIQAJgGAOgEQAPgEAQgCIAAgGQAAgIgEgEQgEgEgJAAIgFAAIgFABIABAEIACAFQgBAHgFAEQgEAEgHABQgKAAgEgFQgFgEABgIQAAgJAFgGQAHgGAKgDQALgDAOAAQAYAAALAIQALAIgBASIAAAqIABAFQAAAAAAAAQABABAAAAQAAAAABAAQAAAAAAAAIAHAAIAAASIgkAAIgEgHIgDgJQgCAFgFAEQgFAFgGACQgHACgHABQgPgBgIgHgAgMAHQgJAEAAAJQAAAGADADQADADAFAAQAKAAAFgGQAFgHAAgKIAAgIQgOACgIAEg");
	this.shape_8.setTransform(-74.45,40.175);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgLA5QgIgIAAgRIAAgxIgMAAIAAgQIAGgBQAGgBAEgDQADgCACgHIACgQIAVAAIAAAcIASAAIAAASIgTAAIAAAxQAAAHADADQADADAGAAIAFgBIADgBIAAATIgIACIgLAAQgQAAgIgHg");
	this.shape_9.setTransform(-88.525,38.875);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgZAtQgMgHgGgLQgHgMAAgPQABgPAGgLQAGgMAMgGQAMgHAOAAQAZABAMANQANAOAAAZIAAAEIhDAAQABAMAGAHQAGAHALAAQAKAAAGgFQAGgEADgIIARAKQgEAIgFAGQgGAGgJADQgKADgNABQgQgBgMgGgAASgIQAAgOgDgFQgFgGgIAAQgIAAgEAGQgFAGgBANIAiAAIAAAAg");
	this.shape_10.setTransform(-97.15,40.175);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AglBLQgMgDgFgEQgGgEABgHQgBgGAHgFQAGgFAMgCQgKgDgFgFQgFgFAAgIQAAgIAFgFQAFgFAIgCQgHgEgEgHQgDgGAAgJQAAgLAGgIQAGgIALgEQALgEAOAAQAIAAAIACQAHABAFADQADgJAFgFQAFgFAHAAQAHAAAFAEQADAEAAAGQAAAGgCADQgEAEgFAAQgEAAgDgCQgDgBgBgDIgDACIgCACQAFAEADAGQACAFAAAHQAAALgGAIQgGAHgKADQgLAEgOAAIgMgBIgKgCIgEACQgBABAAAAQAAAAgBABQAAAAAAABQAAAAAAABQAAADACACQADABAHAAIAOAAIAPAAIAOgBQARABAHAHQAIAIgBANQAAASgOAJQgPAJgdAAQgVAAgMgCgAgfAvQgDADgBAEQAAAFAIADQAHACARAAQARAAAIgEQAJgDAAgGQgBgFgDgCQgDgCgKAAIgkAAQgHACgCADgAgPgsQgEAFAAAJIAAADQAAAJAEAEQAEAEAHAAQAHAAADgEQAEgEABgJIAAgEQAAgIgEgFQgEgEgGAAIgCAAQgHAAgDAEg");
	this.shape_11.setTransform(-108.1,41.425);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcAtQgLgGgHgMQgGgMgBgPQABgPAGgLQAHgMAMgGQAMgHAPAAQAQAAAMAHQAMAGAGAMQAHALAAAPQAAAPgHAMQgGAMgMAGQgMAGgQABQgPgBgNgGgAgPgZQgEAIAAAQIAAADQAAAQAEAIQAGAHAJAAQAKAAAGgHQAEgIAAgQIAAgDQAAgQgEgIQgGgHgKAAQgJAAgGAHg");
	this.shape_12.setTransform(-124.5,40.175);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgLA5QgIgIAAgRIAAgxIgMAAIAAgQIAGgBQAGgBAEgDQADgCACgHIACgQIAVAAIAAAcIASAAIAAASIgTAAIAAAxQAAAHADADQADADAGAAIAFgBIADgBIAAATIgIACIgLAAQgQAAgIgHg");
	this.shape_13.setTransform(-133.775,38.875);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgZAtQgMgHgGgLQgGgMgBgPQABgPAGgLQAHgMALgGQAMgHAOAAQAZABAMANQAMAOAAAZIAAAEIhCAAQABAMAHAHQAFAHAMAAQAJAAAGgFQAGgEADgIIAQAKQgCAIgHAGQgFAGgJADQgKADgNABQgQgBgMgGgAATgIQAAgOgFgFQgEgGgIAAQgIAAgEAGQgFAGgBANIAjAAIAAAAg");
	this.shape_14.setTransform(2.1,16.775);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAkAyIAAgRIAFAAIADgBQABgBAAgEIAAgkQAAgKgDgEQgDgFgHAAQgIAAgEAGQgDAHgBAMIAAAeQAAAEABABIADABIAGAAIAAARIgzAAIAAgRIAFAAIADgBQACgBAAgEIAAglQAAgJgEgEQgEgFgGAAQgIAAgEAGQgEAHAAAMIAAAeQAAAEABABIADABIAGAAIAAARIg1AAIAAgRIAHAAIADgBQABgBAAgEIAAgxIgBgFQgBgBAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAIgHAAIAAgRIATAAIAOgBIAKgCIAAATQAFgJAHgFQAIgFALAAQALAAAHAFQAGAFAEALQAEgKAHgGQAIgFANAAQAPAAAJAJQAIAJAAAUIAAAmQAAAEABABIADABIAHAAIAAARg");
	this.shape_15.setTransform(-12.25,16.625);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgaBGIAAgSIAHAAIADgBIABgFIAAgvIgBgHQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAIgGAAIAAgSIAUAAIANgBIAKgBIAABLIAAAFIAEABIAGAAIAAASgAgMgnQgGgFAAgIQAAgHAGgFQAEgFAIAAQAIAAAGAFQAEAFABAHQgBAIgEAFQgGAFgIAAQgIAAgEgFg");
	this.shape_16.setTransform(-24.5,14.65);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgLA5QgIgIAAgRIAAgxIgMAAIAAgQIAGgBQAGgBAEgDQADgCACgHIACgQIAVAAIAAAcIASAAIAAASIgTAAIAAAxQAAAHADADQADADAGAAIAFgBIADgBIAAATIgIACIgLAAQgQAAgIgHg");
	this.shape_17.setTransform(-31.125,15.475);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgLA5QgIgIAAgRIAAgxIgMAAIAAgQIAGgBQAGgBAEgDQADgCACgHIACgQIAVAAIAAAcIASAAIAAASIgTAAIAAAxQAAAHADADQADADAGAAIAFgBIADgBIAAATIgIACIgLAAQgQAAgIgHg");
	this.shape_18.setTransform(-42.675,15.475);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgtAsQgIgHAAgLQAAgNAJgIQAJgGAOgEQAPgEAQgCIAAgGQAAgIgEgEQgFgEgIAAIgFAAIgFABIACAEIABAFQgBAHgFAEQgFAEgGABQgKAAgEgFQgFgEABgIQAAgJAFgGQAHgGAKgDQALgDAOAAQAXAAALAIQAMAIgBASIAAAqIABAFQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAIAGAAIAAASIgkAAIgEgHIgCgJQgDAFgFAEQgFAFgGACQgHACgHABQgPgBgIgHgAgMAHQgJAEAAAJQAAAGADADQADADAFAAQAKAAAFgGQAFgHAAgKIAAgIQgNACgJAEg");
	this.shape_19.setTransform(-51.4,16.775);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgZAtQgMgHgGgLQgGgMAAgPQAAgPAGgLQAHgMALgGQAMgHAPAAQAYABANANQAMAOgBAZIAAAEIhBAAQAAAMAGAHQAHAHAKAAQAKAAAGgFQAGgEADgIIAQAKQgDAIgGAGQgFAGgKADQgIADgNABQgRgBgMgGgAATgIQgBgOgEgFQgDgGgJAAQgIAAgFAGQgEAGgBANIAjAAIAAAAg");
	this.shape_20.setTransform(-62.55,16.775);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AguAyIAAgRIAHAAIADgBQABgBAAgEIAAgxIgBgFQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgHAAIAAgRIAUAAIAOgBIAKgCIAAAWQACgMAHgFQAHgFAJAAQALAAAHAHQAGAHAAANQAAAKgFAHQgGAFgJAAQgHAAgEgDQgEgEgBgGQAAgFADgDQACgEAEgCIgCgBIgEgBQgIAAgEAIQgEAIAAANIAAAbQAAAEABABIACABIAHAAIAAARg");
	this.shape_21.setTransform(-72.775,16.625);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AglBLQgMgDgFgEQgGgEABgHQgBgGAHgFQAGgFAMgCQgKgDgFgFQgFgFAAgIQAAgIAFgFQAFgFAIgCQgHgEgEgHQgDgGAAgJQAAgLAGgIQAGgIALgEQALgEAOAAQAIAAAIACQAHABAFADQADgJAFgFQAFgFAHAAQAHAAAFAEQADAEAAAGQAAAGgCADQgEAEgFAAQgEAAgDgCQgDgBgBgDIgDACIgCACQAFAEADAGQACAFAAAHQAAALgGAIQgGAHgKADQgLAEgOAAIgMgBIgKgCIgEACQgBABAAAAQAAAAgBABQAAAAAAABQAAAAAAABQAAADACACQADABAHAAIAOAAIAPAAIAOgBQARABAHAHQAIAIgBANQAAASgOAJQgPAJgdAAQgVAAgMgCgAgfAvQgDADgBAEQAAAFAIADQAHACARAAQARAAAIgEQAJgDAAgGQgBgFgDgCQgDgCgKAAIgkAAQgHACgCADgAgPgsQgEAFAAAJIAAADQAAAJAEAEQAEAEAHAAQAHAAADgEQAEgEABgJIAAgEQAAgIgEgFQgEgEgGAAIgCAAQgHAAgDAEg");
	this.shape_22.setTransform(-83.35,18.025);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgtAsQgHgHAAgLQAAgNAIgIQAJgGAOgEQAOgEARgCIAAgGQAAgIgEgEQgEgEgJAAIgGAAIgEABIABAEIABAFQAAAHgEAEQgGAEgHABQgIAAgFgFQgEgEgBgIQAAgJAHgGQAFgGALgDQALgDAPAAQAXAAAKAIQALAIAAASIAAAqIABAFQAAAAAAAAQABABAAAAQAAAAABAAQAAAAAAAAIAIAAIAAASIgkAAIgFgHIgDgJQgCAFgFAEQgFAFgGACQgHACgIABQgOgBgIgHgAgNAHQgIAEgBAJQABAGADADQADADAGAAQAJAAAEgGQAGgHAAgKIAAgIQgOACgJAEg");
	this.shape_23.setTransform(-99.6,16.775);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgYAxIgRgFIAAgaIAXAAIAAAQIAHABIAIAAQAHAAAEgCQAEgDABgGQgBgGgFgCQgGgDgJgBQgIgCgIgDQgIgDgFgFQgFgGAAgKQAAgQAMgJQALgIAUgBQAMABAKACQAKACAGADIAAAZIgWAAIAAgOIgGgCIgIAAQgGAAgEACQgFADAAAFQAAAEADACQADADAFABIAJACQAJABAIAEQAHADAGAFQAFAGAAALQAAAPgMAJQgLAJgVABQgMgBgLgCg");
	this.shape_24.setTransform(-114.625,16.775);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgDAcIgEgMIgFgQQgCgHAAgGIAAgOIAdAAIAAAOQAAAGgCAHIgFAQIgEAMg");
	this.shape_25.setTransform(-121.325,11.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgLA5QgIgIAAgRIAAgxIgMAAIAAgQIAGgBQAGgBAEgDQADgCACgHIACgQIAVAAIAAAcIASAAIAAASIgTAAIAAAxQAAAHADADQADADAGAAIAFgBIADgBIAAATIgIACIgLAAQgQAAgIgHg");
	this.shape_26.setTransform(-127.025,15.475);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgdBDIAAgSIAIAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQABgBAAgDIAAhVIgBgEQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBABIgIAAIAAgSIA7AAIAAASIgIAAQgBgBAAAAQgBAAAAABQgBAAAAAAQAAAAgBABIgBAEIAABVQAAADABABQABABAAAAQAAAAABABQAAAAABAAQAAAAABAAIAIAAIAAASg");
	this.shape_27.setTransform(-133.625,15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2type, new cjs.Rectangle(-139,0,278,52.8), null);


(lib.HEAD1atype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANQgGgFAAgIQAAgHAGgGQAEgEAIAAQAJAAAFAEQAFAGAAAHQAAAIgFAFQgFAFgJABQgIgBgEgFg");
	this.shape.setTransform(69.65,43.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgxA9QgIgGAAgKQAAgJAFgFQAFgFAIAAQAGAAAEADQAFAEABAFQAAAFgCAHQAGgBAEgFQADgGAEgIIAAgBIgihIIgDgFIgEgBIgFAAIAAgSIA3AAIAAASIgGAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABQAAABABAAIARAoIAPgnQACgEgCgCQAAAAAAAAQgBgBAAAAQgBAAAAAAQgBAAAAAAIgIAAIAAgSIAsAAIAAASIgGAAIgDABQgCABgBAEIgeBGQgFAOgGAJQgFAJgHAEQgIAFgMAAQgOgBgHgGg");
	this.shape_1.setTransform(61.4,42.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAHBEIAAgSIAGAAIACgBQABgBAAgEIAAgmQAAgIgDgFQgDgEgIABQgHgBgFAHQgEAFAAAPIAAAcQAAAEABABIADABIAGAAIAAASIg1AAIAAgSIAGAAIADgBQABgBAAgEIAAhUIAAgFIgEgBIgHAAIAAgSIAUAAIAOgBIAKgBIAAAzQAFgIAIgEQAHgFALAAQAQAAAIAJQAIAJAAATIAAAnQAAAEABABIACABIAIAAIAAASg");
	this.shape_2.setTransform(49.65,38.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgLA5QgIgIAAgRIAAgxIgMAAIAAgQIAGgBQAGgBAEgDQADgCACgHIACgQIAVAAIAAAcIASAAIAAASIgTAAIAAAxQAAAHADADQADADAGAAIAFgBIADgBIAAATIgIACIgLAAQgQAAgIgHg");
	this.shape_3.setTransform(39.975,38.875);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgaBEIAAgSIAIAAIACgBQABgBAAgEIAAhUIgBgFIgCgBIgIAAIAAgSIAUAAIAOgBIAKgBIAABuQAAAEAAABIADABIAGAAIAAASg");
	this.shape_4.setTransform(33.7,38.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgtAsQgHgHgBgLQAAgNAJgIQAJgGAOgEQAOgEARgCIAAgGQAAgIgEgEQgFgEgIAAIgFAAIgFABIABAEIABAFQAAAHgEAEQgGAEgHABQgIAAgFgFQgFgEAAgIQABgJAFgGQAHgGAKgDQALgDAPAAQAXAAALAIQAKAIAAASIAAAqIABAFQAAAAAAAAQABABAAAAQAAAAABAAQAAAAAAAAIAIAAIAAASIgkAAIgFgHIgDgJQgCAFgFAEQgFAFgGACQgHACgIABQgOgBgIgHgAgMAHQgJAEAAAJQAAAGADADQADADAGAAQAJAAAFgGQAFgHAAgKIAAgIQgOACgIAEg");
	this.shape_5.setTransform(25.25,40.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgZAtQgMgHgGgLQgHgMABgPQAAgPAGgLQAGgMAMgGQAMgHAOAAQAZABAMANQAMAOABAZIAAAEIhDAAQABAMAGAHQAHAHAKAAQAKAAAGgFQAGgEADgIIARAKQgEAIgFAGQgGAGgKADQgJADgMABQgRgBgMgGgAASgIQAAgOgDgFQgFgGgIAAQgIAAgEAGQgFAGgBANIAiAAIAAAAg");
	this.shape_6.setTransform(14.1,40.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAHBEIAAgSIAFAAIADgBQABgBAAgEIAAgmQAAgIgDgFQgDgEgIABQgHgBgEAHQgFAFAAAPIAAAcQAAAEABABIADABIAFAAIAAASIg1AAIAAgSIAHAAIADgBQABgBAAgEIAAhUIAAgFIgEgBIgIAAIAAgSIAVAAIAOgBIAKgBIAAAzQAFgIAIgEQAHgFALAAQAQAAAIAJQAIAJAAATIAAAnQAAAEABABIADABIAHAAIAAASg");
	this.shape_7.setTransform(2.65,38.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AglA/QgKgHgFgLQgGgNAAgPQABgPAFgLQAFgLAKgHQAKgGANAAQALAAAHAEQAIAFAEAIIAAgZIgBgGIgDgBIgIAAIAAgSIAVAAIAOgBIAKgBIAABuQAAAFABABIACAAIAHAAIAAASIgoAAIAAgHIgBgLQgEAKgIAGQgHAEgNABQgNgBgKgFgAgSgGQgFAGAAAPIAAAEQAAAPAFAHQAGAIAJgBQAIABAFgIQAFgHABgPIAAgEQgBgPgFgGQgFgHgIAAIgBAAQgJAAgFAHg");
	this.shape_8.setTransform(-14.225,38.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAGAyIAAgRIAGAAIACgBQABgBAAgEIAAgmQABgJgEgEQgDgEgHAAQgHAAgFAGQgEAHAAANIAAAdQAAAEAAABIADABIAGAAIAAARIg1AAIAAgRIAHAAIACgBQABgBAAgEIAAgxIgBgFQAAgBAAAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgHAAIAAgRIATAAIAOgBIAKgCIAAASQAFgJAIgFQAHgEALAAQAQAAAIAJQAJAKgBATIAAAmQAAAEABABIADABIAHAAIAAARg");
	this.shape_9.setTransform(-26.45,40.025);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgtAsQgIgHABgLQgBgNAJgIQAJgGAOgEQAPgEAQgCIAAgGQAAgIgEgEQgFgEgIAAIgGAAIgEABIACAEIABAFQgBAHgFAEQgEAEgIABQgJAAgEgFQgEgEgBgIQAAgJAHgGQAFgGALgDQALgDAOAAQAXAAALAIQAMAIgBASIAAAqIABAFQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAIAHAAIAAASIgkAAIgFgHIgCgJQgDAFgFAEQgEAFgHACQgHACgIABQgOgBgIgHgAgNAHQgIAEgBAJQABAGADADQADADAFAAQAKAAAEgGQAGgHAAgKIAAgIQgNACgKAEg");
	this.shape_10.setTransform(-38.15,40.175);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgZAtQgMgHgGgLQgGgMAAgPQAAgPAGgLQAHgMALgGQAMgHAPAAQAYABANANQAMAOgBAZIAAAEIhBAAQAAAMAGAHQAHAHAKAAQAKAAAGgFQAGgEADgIIAQAKQgDAIgGAGQgFAGgKADQgIADgNABQgRgBgMgGgAATgIQgBgOgEgFQgDgGgJAAQgIAAgFAGQgEAGgBANIAjAAIAAAAg");
	this.shape_11.setTransform(-54,40.175);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgeBEIAAgRIAIAAIACgBQABgBAAgEIAAg4IgMAAIAAgRIAMAAIAAgFQAAgNAEgHQADgIAIgDQAGgDAMAAIALABIAHACIAAARIgDgBIgEAAQgFAAgDACQgDABgBAFQgBAEAAAIIARAAIAAARIgQAAIAAA4QAAAEABABIADABIAIAAIAAARg");
	this.shape_12.setTransform(-62.575,38.225);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgtAsQgHgHgBgLQAAgNAJgIQAJgGAOgEQAOgEARgCIAAgGQAAgIgEgEQgFgEgIAAIgFAAIgFABIABAEIABAFQAAAHgEAEQgGAEgHABQgIAAgFgFQgFgEAAgIQABgJAFgGQAHgGAKgDQALgDAPAAQAXAAALAIQAKAIAAASIAAAqIABAFQAAAAAAAAQABABAAAAQAAAAABAAQAAAAAAAAIAHAAIAAASIgkAAIgEgHIgDgJQgCAFgFAEQgFAFgGACQgHACgIABQgOgBgIgHgAgMAHQgJAEAAAJQAAAGADADQADADAGAAQAJAAAFgGQAFgHAAgKIAAgIQgOACgIAEg");
	this.shape_13.setTransform(-71.5,40.175);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgYAxIgRgFIAAgaIAXAAIAAAQIAHABIAIAAQAHAAAEgCQAEgDABgGQgBgGgFgCQgGgDgJgBQgIgCgIgDQgIgDgFgFQgFgGAAgKQAAgQAMgJQALgIAUgBQAMABAKACQAKACAGADIAAAZIgWAAIAAgOIgGgCIgIAAQgGAAgEACQgFADAAAFQAAAEADACQADADAFABIAJACQAJABAIAEQAHADAGAFQAFAGAAALQAAAPgMAJQgLAJgVABQgMgBgLgCg");
	this.shape_14.setTransform(-81.825,40.175);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgZAtQgMgHgGgLQgGgMgBgPQABgPAGgLQAGgMAMgGQAMgHAPAAQAYABAMANQAMAOAAAZIAAAEIhBAAQAAAMAHAHQAFAHAMAAQAJAAAGgFQAGgEADgIIAQAKQgCAIgHAGQgFAGgJADQgKADgNABQgQgBgMgGgAATgIQAAgOgFgFQgDgGgJAAQgIAAgFAGQgEAGgBANIAjAAIAAAAg");
	this.shape_15.setTransform(-96.55,40.175);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgGA+QgJgHgEgKIgFAVIgYAAIABgFIAAgKIAAgSIAAhKIgBgGQAAAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgHAAIAAgSIAUAAIAOgBIAKgBIAAA2QAEgJAIgFQAHgFANAAQAMAAAKAGQAJAHAFALQAFALAAAPQAAAPgFANQgFALgKAHQgKAFgNABQgOAAgIgHgAgIgGQgGAGAAAPIAAAEQAAAPAGAHQAFAIAIgBQAJABAGgIQAFgHAAgPIAAgEQAAgPgFgGQgGgHgJAAIgBAAQgIAAgEAHg");
	this.shape_16.setTransform(-108.175,38.45);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgcAtQgLgGgHgMQgGgMgBgPQABgPAGgLQAHgMAMgGQAMgHAPAAQAQAAAMAHQAMAGAGAMQAHALAAAPQAAAPgHAMQgGAMgMAGQgMAGgQABQgPgBgNgGgAgPgZQgEAIAAAQIAAADQAAAQAEAIQAGAHAJAAQAKAAAGgHQAEgIAAgQIAAgDQAAgQgEgIQgGgHgKAAQgJAAgGAHg");
	this.shape_17.setTransform(-124.5,40.175);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgLA5QgIgIAAgRIAAgxIgMAAIAAgQIAGgBQAGgBAEgDQADgCACgHIACgQIAVAAIAAAcIASAAIAAASIgTAAIAAAxQAAAHADADQADADAGAAIAFgBIADgBIAAATIgIACIgLAAQgQAAgIgHg");
	this.shape_18.setTransform(-133.775,38.875);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgxA9QgIgGABgKQgBgJAFgFQAEgFAJAAQAGAAAFADQADAEABAFQABAFgDAHQAGgBAEgFQAEgGAEgIIAAgBIgjhIIgCgFIgEgBIgFAAIAAgSIA2AAIAAASIgFAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABQAAABABAAIARAoIAQgnQABgEgBgCQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAIgHAAIAAgSIAsAAIAAASIgFAAIgFABQgBABgBAEIgeBGQgFAOgGAJQgFAJgHAEQgIAFgMAAQgOgBgHgGg");
	this.shape_19.setTransform(59.8,18.675);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgaBEIAAgSIAHAAIADgBQACgBAAgEIAAhUIgCgFIgDgBIgHAAIAAgSIAVAAIAMgBIAKgBIAABuQAAAEABABIADABIAGAAIAAASg");
	this.shape_20.setTransform(51.1,14.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgaBGIAAgSIAHAAIADgBIABgFIAAgvIgBgHQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAIgGAAIAAgSIAUAAIANgBIAKgBIAABLIABAFIADABIAGAAIAAASgAgNgnQgEgFAAgIQAAgHAEgFQAFgFAIAAQAJAAAEAFQAFAFABAHQgBAIgFAFQgEAFgJAAQgIAAgFgFg");
	this.shape_21.setTransform(45.1,14.65);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAkAyIAAgRIAGAAIACgBQABgBAAgEIAAgkQABgKgEgEQgDgFgHAAQgIAAgEAGQgDAHgBAMIAAAeQAAAEABABIADABIAGAAIAAARIgzAAIAAgRIAFAAIADgBQABgBAAgEIAAglQAAgJgDgEQgEgFgGAAQgIAAgEAGQgDAHgBAMIAAAeQAAAEABABIADABIAGAAIAAARIg1AAIAAgRIAHAAIACgBQACgBAAgEIAAgxIgCgFQAAgBAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAIgHAAIAAgRIATAAIAOgBIAKgCIAAATQAEgJAIgFQAIgFALAAQALAAAHAFQAHAFADALQAEgKAHgGQAIgFANAAQAPAAAJAJQAIAJABAUIAAAmQgBAEABABIADABIAHAAIAAARg");
	this.shape_22.setTransform(33.1,16.625);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgtAsQgHgHAAgLQAAgNAIgIQAJgGAOgEQAOgEARgCIAAgGQAAgIgEgEQgFgEgIAAIgGAAIgEABIABAEIABAFQAAAHgEAEQgGAEgHABQgIAAgFgFQgFgEAAgIQABgJAFgGQAHgGAKgDQALgDAPAAQAWAAAMAIQAKAIAAASIAAAqIABAFQAAAAAAAAQABABAAAAQAAAAABAAQAAAAAAAAIAIAAIAAASIgkAAIgFgHIgDgJQgCAFgFAEQgFAFgGACQgHACgIABQgOgBgIgHgAgNAHQgIAEgBAJQABAGADADQADADAGAAQAJAAAEgGQAGgHAAgKIAAgIQgOACgJAEg");
	this.shape_23.setTransform(18.4,16.775);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgeBEIAAgRIAIAAIACgBQABgBAAgEIAAg4IgMAAIAAgRIAMAAIAAgFQAAgNAEgHQADgIAIgDQAGgDAMAAIALABIAHACIAAARIgDgBIgEAAQgFAAgDACQgDABgBAFQgBAEAAAIIARAAIAAARIgQAAIAAA4QAAAEABABIADABIAIAAIAAARg");
	this.shape_24.setTransform(9.425,14.825);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AguAyIAAgRIAHAAIADgBQABgBAAgEIAAgxIgBgFQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgHAAIAAgRIAUAAIAOgBIAKgCIAAAWQACgMAHgFQAHgFAJAAQALAAAHAHQAGAHAAANQAAAKgFAHQgGAFgJAAQgHAAgEgDQgEgEgBgGQAAgFADgDQACgEAEgCIgCgBIgEgBQgIAAgEAIQgEAIAAANIAAAbQAAAEABABIACABIAHAAIAAARg");
	this.shape_25.setTransform(-3.575,16.625);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgoApQgIgJAAgTIAAgnQAAgEgBgBIgDgBIgGAAIAAgRIAsAAIAAA9QAAAKADAEQADADAHAAQAHAAAEgGQAFgGAAgNIAAgeQAAgEgBgBIgDgBIgIAAIAAgRIAtAAIAABIIABAFQAAABAAAAQAAAAABAAQAAABABAAQAAAAAAAAIAJAAIAAARIgVAAIgOABIgKABIAAgQQgFAIgIAFQgHAEgLAAQgPAAgJgJg");
	this.shape_26.setTransform(-14.6,16.925);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgcAtQgLgGgHgMQgGgMgBgPQABgPAGgLQAHgMAMgGQANgHAOAAQARAAALAHQAMAGAGAMQAHALAAAPQAAAPgHAMQgGAMgMAGQgMAGgQABQgPgBgNgGgAgOgZQgFAIAAAQIAAADQAAAQAFAIQAEAHAKAAQALAAAEgHQAFgIABgQIAAgDQgBgQgFgIQgEgHgLAAQgKAAgEAHg");
	this.shape_27.setTransform(-26.3,16.775);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgxA9QgHgGgBgKQABgJAEgFQAEgFAJAAQAGAAAEADQAFAEABAFQABAFgDAHQAFgBAFgFQADgGADgIIAAgBIghhIIgEgFIgDgBIgGAAIAAgSIA4AAIAAASIgGAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAgBABQAAAAAAABQAAAAAAABQAAAAAAABQAAABAAAAIARAoIAQgnQABgEgBgCQAAAAAAAAQgBgBAAAAQgBAAAAAAQgBAAAAAAIgIAAIAAgSIAtAAIAAASIgHAAIgDABQgCABgCAEIgdBGQgFAOgGAJQgEAJgJAEQgHAFgMAAQgNgBgIgGg");
	this.shape_28.setTransform(-37.8,18.675);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgLA5QgIgIAAgRIAAgxIgMAAIAAgQIAGgBQAGgBAEgDQADgCACgHIACgQIAVAAIAAAcIASAAIAAASIgTAAIAAAxQAAAHADADQADADAGAAIAFgBIADgBIAAATIgIACIgLAAQgQAAgIgHg");
	this.shape_29.setTransform(-51.775,15.475);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAGAyIAAgRIAGAAIADgBQABgBAAgEIAAgmQgBgJgDgEQgDgEgHAAQgHAAgFAGQgFAHAAANIAAAdQAAAEACABIACABIAGAAIAAARIg1AAIAAgRIAHAAIADgBQABgBAAgEIAAgxIgBgFQgBgBAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAIgHAAIAAgRIATAAIAOgBIAKgCIAAASQAFgJAIgFQAHgEALAAQAQAAAJAJQAHAKABATIAAAmQAAAEABABIACABIAHAAIAAARg");
	this.shape_30.setTransform(-61.05,16.625);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgtAsQgIgHAAgLQAAgNAJgIQAJgGAOgEQAOgEARgCIAAgGQAAgIgEgEQgFgEgIAAIgFAAIgFABIABAEIABAFQAAAHgEAEQgFAEgHABQgKAAgEgFQgFgEABgIQAAgJAFgGQAHgGAKgDQALgDAPAAQAXAAALAIQAKAIAAASIAAAqIABAFQAAAAAAAAQABABAAAAQAAAAABAAQAAAAAAAAIAHAAIAAASIgkAAIgEgHIgDgJQgCAFgFAEQgEAFgHACQgHACgHABQgPgBgIgHgAgMAHQgJAEAAAJQAAAGADADQADADAFAAQAKAAAFgGQAFgHAAgKIAAgIQgOACgIAEg");
	this.shape_31.setTransform(-72.75,16.775);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAVAxIgUg1IgUA1IgYAAIgchKIgDgFIgCgBIgGAAIAAgRIA1AAIAAARIgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAAAgBABQgBACABADIAEAJIAFAPIAGAPIAFgPIAFgPIADgJQABgDgBgCQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgFAAIAAgRIAxAAIAAARIgEAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAAAgBABQgBACABADIAEAJIAGAPIAGAPIAFgPIAFgPIADgJQABgEgBgBQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgGAAIAAgRIAoAAIAAARIgGAAIgCABQgCABgBAEIgaBKg");
	this.shape_32.setTransform(-86.85,16.825);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgoApQgIgJAAgTIAAgnQAAgEgBgBIgDgBIgGAAIAAgRIAsAAIAAA9QAAAKADAEQADADAHAAQAHAAAEgGQAFgGAAgNIAAgeQAAgEgBgBIgDgBIgIAAIAAgRIAtAAIAABIIABAFQAAABAAAAQAAAAABAAQAAABABAAQAAAAAAAAIAJAAIAAARIgVAAIgOABIgKABIAAgQQgFAIgIAFQgHAEgLAAQgPAAgJgJg");
	this.shape_33.setTransform(-105.95,16.925);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgcAtQgLgGgHgMQgGgMgBgPQABgPAGgLQAHgMAMgGQANgHAOAAQARAAALAHQAMAGAGAMQAHALAAAPQAAAPgHAMQgGAMgMAGQgMAGgQABQgPgBgNgGgAgOgZQgFAIAAAQIAAADQAAAQAFAIQAEAHAKAAQALAAAEgHQAFgIABgQIAAgDQgBgQgFgIQgEgHgLAAQgKAAgEAHg");
	this.shape_34.setTransform(-117.65,16.775);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgeBDIAAgSIAKAAQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIABgEIAAggIgjg1IgEgEIgEgBIgGAAIAAgSIA/AAIAAASIgIAAQAAAAgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBADACADIATAfIATghQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgKAAIAAgSIA1AAIAAASIgIAAIgFABIgEAEIghAzIAAAiQAAADABABQABABAAAAQAAAAABABQAAAAABAAQAAAAABAAIAKAAIAAASg");
	this.shape_35.setTransform(-130.075,15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1atype, new cjs.Rectangle(-139,0,278,52.8), null);


(lib.CO_v_white = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgyA1QgXgVAAggQAAgeAWgVQAVgWAeAAQAfAAAWAXQAVAVgBAdQAAAfgVAVQgVAVgfABQgdgBgVgUgAgvgvQgTAUAAAbQAAAcATAUQAUATAbAAQAcAAATgTQATgTABgdQAAgbgTgTQgUgUgcAAQgbAAgUATgAASAuQgCgDgCgKIgCgPQgCgIgFgEQgEgCgJAAIgGAAIAAAqIgRAAIAAhcIAfAAQAPAAAFACQAPAFAAARQAAAQgTAGQAGABADAEQADAEABAJQAEAVADAHgAgOgIIAOAAQATAAAAgNQAAgIgHgDQgDgBgMAAIgLAAg");
	this.shape.setTransform(133.8251,86.6356,0.4949,0.4949);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACmLBQgKgEgNACQgPADgIAAQAAgDgKgCIgOgBQgRABgHgCQAAgDgSACQgjgBAAgBIgUgCIgTgBQgLgCgHAAQAAgBgQABQgRABAAgDIgOgEQgJgDAAAHQgDAAgFgDQgEgDgDAAQAAAFgJgBIgNgDQgNgCgLACQgRACgYgKIgJgEQgEgCgEABQgCAAgIgEQgIgFAAgBIgMABIgMABQgIACgFgBQgDAAgDgEQgEgFgDAAIAAAEQgEAAgEgCQgGgDAAgEQgCAGgBAAQAAgDgIgDQgIgCgFAAIgBABQgBAAAAAAQAAgBAAABQgBAAAAAAQAAAAAAAAQgDABgFgEQgEgDgEABQgEABAAgDIgIgGQgHgFAAAEQgCABgMgFQgNgGAAgCIgTgJQgBABAAAAQgBABAAAAQAAABAAAAQAAAAABAAIgEABIAAAAIgEAAIAEAAQABADgQgGQgCgDgFAAQAAgGgDgCIAAAGIgFgDQgGgDAAADIgIgIIgOgCQAAgCgNgGQgNgGAAgCQgKgEgDgKQgBgDgJgBIgOgCQgTgKgBABQgEgCgCABIABgDQgCAAgQgKQgLgIgDgIIgLgDQgCgCgBgDQgBgBgFAAIgDgHIgCgHQgEgBgCACQgCACgCAAQgBgLgTAAQgPAAAAgBIgNgBIgMgBQgSAFgHgCQAAgBgYgBQgaAAgDgBQAAACgJgCIgNgDQgLAFgDgEQgNgEgCABQAAABgGAAIgHgBIgJgCQgDgCgFAAIgOABQAAABgOgEQgGAAgFgHQgCgBgNABIgMAAQgEABgcgDQgcgDAAgBIgJgDQgGgCgDAAIgXgDQgDgEgbgGQgagHAAgBQgCAAgEgCQgDgDgDABQgOACAAgEQgJgEgPAAQAAgFgKgBQgNgBgBgBQgLgFgFgDQgHgGgQgDIgYgEQgDgDgDABIgHACIgGgDIgHgCQAAgEgJgBQgJgBgCgFIAJgCQgBgEgMgEQgMgFAAACIgSgJQgFAAgIgGIgLgHIgMgEIgNgBIAVAVQAAADAHAGQAHAGABAEQADACAGAHQAGAGAEABQAKADAEAHQADAAAHADIAKAFIAHAEQAHAEAAACQAFAAAHADQAGADAEAAIAEACQABAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAFABAGAGQACAFAWAEQAVAEAAADIAYAKQADAAAGADQAFAEAEAAQACgBATAGIATAFQADAAAIAEQAGAEAEgBQAEgBAJAEQAKAEADAAQAAgBARAEIAVAFQAEAAAJACIANAEQAAABAOACIAQABQAAAFBNAGQADADAjADQAiAEAAABQBPAIAAgBQADgBAkAEQAiAEAAgBQAIgBAAABQgGAAgMAGQgOAGgFABIgMgCQgLgCAAADIgGABQgDABgDgBQAAAGgUABQgTABAAgDQgQACAAgCIgGACQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgLgBQgDgBgDgGQgDAAgCADQgBABgGAAIgNgBQgXgCgDgCIgFgFIgJABIgMgEQgKgDAAADQgGAAgKgCQgCgGgEABIgJAFQgFADgFgCQAAgCgLgCQgKgCgEABQAAACgWgEIgbgFQAAgCgOgBQgPgBgBgEQgHAAgLgDQgMgDgGgBQgCgCgNgBQgNgBAAgCQgGAAgJgCIgOgEIgNgEQgNgEAAgBIgNgCQgKgCAAgBQgFAAgGgCIgLgFIgDgBIgCgBQgLAAAQALQACACAGACQAGACADADIAKADQAAABAFABIAHABQAAACASADQAAADAaAEQAZAFABAHIgKACQAAgDgXgDQgZgDgCgDIgagHQgVgHAAgDIgZgIQgUgIAAgBQgIgCgKgEQgNgGgFgGIgIgFQgJgEAAABQgCAAgHgFQgIgFAAgCQgKAAgPgHQgRgJgCgJQgPgKgGAAIgIgIQgFgFgDgCIgGgIIgJgFQgGgCAAgDQgGgEgHgIQgHgJgDgGQgDgBgEgHQgFgHAAgCQgDAAgDgJQgDgKgEAAQAAgEgDgGQgEgFAAgFQgBAAgFgTIgGgYIgHgkQgHgjAFAAIgFgVQgBAAgBgLIgBgNQgDAAAAgNQgBgOgCAAIgJhUIAAggQAAgcACAAIgCgjQgBggAEAAIgCgxQgCgsAFgDQAAgEAKgaQALgZgBgEQAIAAAHgOQAHgPAGgCQACgBADgFQACgGADgCQAAgFAGgGQAHgGAHgBIgDgEQAAAAAAgBQAAAAAAgBQAAAAABgBQABAAABAAIAEgCQAAAAAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAHgHIAKgHIAFAAIAEgCQALgIgHAAQgCgGAFgEQAFgFAFAAIAIgDIAIgCQAKgFAKgJIAQgRQAGgGADgBIAFgDIACgEQACAAAOgLQAAgCANgFQANgGAAgEQAEAAAJgGQAJgHABgDIAOgJQAHgEAIAAQAAgBAGgDIAFgCIAJABQAGACABgDIAXgEQAOgEAAgJQADgBACgEIADgEQABgCAEgDQAEgCABgDIgBAAQAAgFAHACIAJACIARgCIAIgFIAKgEIAJgFQAHgEACAAIAEgCQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBQAFAAAFgCQAHgCAAgDQgHAAAHgHQAHgGAEgBIANgHQAFAAAGgDQAAgDAHgCQAGgCAAgEQAGAAAAADQADAAAEgCIAHgCIAKACQAGABACgDIAOgGQAJgGAEAAQAAgBALgEQAKgDAEAAQAAgCAHAAQAHAAAAgBQAJAAACgCQACgBAAgHIAFgDIAEgEIAJACIgBAFIAEgCIADgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAfAAAHgDQAEgBAGACIAKACQALgGgFAAQgCgJASgGQATgGAAAFQAMgIAZAAQACgDAJAAQAJABACgEIAXgEQAUgEAAgBIABABIAVgFQAWgFADAAQAVAAAAgEIAIgCQAHgBAAgBIAggHIAvgHQAOAAAggFQAggGAQAAQAAgFBQAAQAAABAGACQAHACAAACQgIAFgXgCIgQABIgRABQgJAAgRADQgSADgJAAQAAgChXATQAAAFArgFIAxgGIAugGIAbgDQARgCAJACQAUgDABAKQASAAAAABIAHABQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAABIgIAAQAAADg1ACQAAABgRADIgUACIgTAAQgSAAAAADIgwAHIgSACIgUACQAAADgMACIgQACQgIgBgPAEQgQAFgHAAIgMACQgMACAAACQgEAAgGAEQgHAEgDAAIgJAAIgJgBQAAADgQACQgPADgBADQgCAKgMADQgOABgIACQAAADgTAHQgHAKgHAEQACAIAiABQAfABAHgEQADgCAagEQAXgDAAgCIAMgCIAMgDQAAgBAGABIAHABQARgEAJAAQAAgBAcgDIAcgFQAfgDAAgBIAVgCIAWgCQAAgCAmgCQAngDAFABIApgDQAkgDAAACQAMgCAYACIAcgBQASgBALACQAAADAJACQAJACAAgCIAQABQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQADgBAKACQALADAAACQgEACgWABIgVAAIgmABQgCADgWAFQgVAFAAACIgQgBQgPgBAAACIgWAAQAAAFgZABIgegBQAAADglABQglACgBAIQARADAXgDIAngGQAAACAkgCQAjgBAAABQAFAAALgDQAEAAAEACQAFADAEAAIAQgBQAJABgEAGQgFAIghACIghACQhWAFAAADIgTACQgTACAAgCQgGgBgJADQgLADgDAAIgRACQgCACgGAAIgKgBQgGABgJAGQgIAGgGABQAAAFgdAEQAAABgHACQgIADAAABIgTADIgKACQgLACgBACQgRAAgMAMQgGABgKAFQgKAGgGABQAAgBgNAFIgPAFQAAgCgFABQgEAAgCACIAEABQgBADgMACIAAgEIgOAFQAKAIgUAEQgWAEAAACIgTAGQgNAFgGABQAAgCgvAQIgRAGQgRAGgCADQgTAAgDAEQgFAAgHAFQgGAEgFgBQgGAAgFAFQgGAGgFAAQgCgDgFACIgIAEIgKAFQgFACgFABQgBABgLADIgNACQAAAFgJACIgOADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABgBAAQgCADgEAAQgEAAgCADQgDAEgDACIgDADQgBABgEAAQgBgCgGgBQgFgCAAAEQgFAAgBAFQgDAHgCABQAAADgJAAQgOAJgCAAQAAACgMACQgLADAAAEIgMAGQgIAFAAADQgFABgFAEQgGAEgEABIgGADQgEACgCAAQgRAJgCAAQgEAEgFAAIgQAMQAAADgIAFQgIAEAAADQgGAEgOACQgBAEgEACQgFACgBABQgFAAgEAIQgEAHgDABQgEABgIAHQgIAFgDAAQAAAFgHAEQgIADgBAFQgSALgLANQgEAAgGAGIgIAKQgGAIgFADQgBADgFACQgFACAAAEQgCAAgHAJQgGAIgDAAIABADQgFAAgFAHIgHAKIgIAIIgHAJQgDAHgLANQgJALgBAJQADAAAGgHQAIgJACgBQAGgKAEAAQAAgDAHgFQAGgFABgCQgCAAAKgJIALgJQAGAAAEgJQAEgJADAAIAGgGQAGgFACAAQACgEAHgEIALgHQAAgCAEgFIAHgFIAVgPQADgHAUgGQABgDAJgEQAIgEAAgCQgBgEAGgCIAIgDIAWgOQAEAAAFgFQAGgEADAAIAhgUQAGgCARgIQATgJAAgDQAHgBACgDQAEAAABgDQACgDACAAQAHgCABgCIAIgEQAFgDAAgBIAGgDIAFgDQAAADAMgFQALgFACgDIAHgCQAFgCAAgBQAHgBAOgJQANgIAIAAQADgEAJgCQAIgCADgDQAEAAAGgEQAFgEAEAAQAFgFAIAAIAIgIIAHAAIAGgBIASgHQAAgBAGgCIAHgBQADgEAKgBIALgCQABgCAHgDQAIgEAAgCIAQgDQAAgCALgDQAJgCAEAAQAAgGANgBQANgBACgCIApgMQAhgJAAgFQAEAAASgFQARgGAAgBQAFAAAJgCQAKgCAAgEQAygGAAgEQALAAAQgFQATgHAHgBQAAgBAYgFIAbgFQAAgBAdgGIAhgHQAIgCANgBQAAgBAFgBIAHgBIATgEQAMgDAHABQAAAIgWAFIgeAFQgQAEAAACQgDAAgHAFQgHAFgFgBQAAAAgBgBQAAAAAAAAQAAAAgBAAQgBAAAAAAQAAACgZAIIgHAFQgEADgEAAQgDAEgGABIgMABIgbAJQgQAFgMACIgEADQgEADAAACQgEAAAFAEQAFADAAgEIAMgBQAKgBAAgCQAfAAgQAFIgHAEIgGAGQgCABgHgCQgEgBgCAGQgJgBgIAEQgKAEgIAAQgFAAgHAEQgGAEgEAAQAAAEAGAAIAGgCIAHgCQAAANgmACQgBADgGABQgDACgEgBQgEAAgDABQgBACgPAFQgFAGgSAAQgLABgBAGQgEgBgFACQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgEgCgBABQAAABgFAEIgIAEQgOAFAAACQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIABACIgGACQgEACgCgBQgBAGgKABIgOgBQAHAFgHADQgFACgGAAQAAgBgIAEIgIAEQgDAGgPAAQAAgDgGACIgEADQgBgDgEAFIgEAIIgGgCQgBAAgBAAQgBAAgBAAQAAAAgBABQAAAAAAABQgFACgIAAQgEAAgMACQgNADAAADQgDAAgEAEQgFAEgDAAIgbAKQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgDADQgEAAgDACQgDACgCAAQAAADgEABQgEACgDAAQgFgBgDAEQgEAFgDAAIgHAEIgFADQAAAGgKACIgOABQAAABgFADIgHADQgDABgHAIQgFAHgGgBQgHgCgJAJQgRAEgBADIgFACQgCABAAAEIgJgBQABABAAAAQABAAgBABQAAAAAAAAQgBABgBAAIgEAAQgBAAgBAAQAAAAAAABQgBAAAAABQAAABABABQAAAGgKAAQgCgCgGADIgJAEQgRAHgIAKQgJABgIAEIgPAJQAAAEgMAGQgMAHgCAFIgJAEQgGACAAAEIgMAFIgGACQgDABgCADIgCADIgEACQgJAHAAACQgDAAgCADQgDAEgCAAQgHABgFAEIgNAPQgHAIgJADQAAAGgOAJQgOAKAAAHQgEACAOALQAPANgBADQgFAAgGAKQgFAKgBAGQgDAAAPANQAPAMAAgEQAGAAAIAHQAIAHABAGQAAAEAKACQAKACACACIAMAJQAGAAALAGQALAFAGAAQAAAHArAAQAMAMAIAAQAAABAIAAQAJABABABIALAAQAGABAFADIAOAJQANAGAFgCIAKgCIALgCQAEADACAAQgCAEADACQACABANgBQAMAAACAEIATABIAIABIAJABQAAgCAPADIASADQADgEAGAAIALAAQABACAHAAQAHAAADADIAEAKQAEAIADgBIACAAIABgCIABgNQABgFAFAAIAKAAIAPACIARAAQAAgCAKADIAMAEQAAgFAKgCQAKgBAAAGIAugFIgBgCQADgCgDgPQgEgPABAAIgEgNQgFgMABAAQABgCgBgFQgBgFgCAAIgBgUQgBgFACgMQABgOACAAIAAgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBABAAQAFAAAAgZQACAAACgIIADgJQAAgFADgGQADgHABgFIAIgfIAIgQQAFgKAAgGQAEgCACgGQADgIADgCQAHgGgBgHQAMgMgBAAIAEgGQADgCACgEQgCgFAEgBQAAgCAFgGQAGgFAAgDQACgBAFgGQAFgHACAAQAAgDAFgDIAIgGQACAAAEgEQADgEAAgCQANgGAPgPIAFgCQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIgRANQgFACgFAIQgFAHgBAFQAGgBADgDIAGgIQAPgGAAgBQAIgCANgKQALgJAKAAIAIgBQADAAADgDQABgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQAAgDAEgBQAAgDAJgHQAIgHAFgCQADgBAFgEIAIABQACgCAFAAQABAAABAAQABgBAAAAQABAAAAgBQAAAAAAgBIAIgGQAHgGAAADQAGACAAgLQAGgBAFgEQACgCAJgCQAAgDACgDQADgDACAAQAAgCAMgGIANgHIACgFQABgCAEgBIAGgCIAGgFIAFgBIAFgCQAEgEAHgDQAIgDADgDQAFgEADACIAEADQADAHgOAHIgSAIQAAACgSAJIgMAJQgIAFgCAFQgEABgIAGQgIAGgGABQAAAIgLACIgMAJQgGAFgCAFQgIACgHAIQgCAAgDADQgDACgEAAQgGABgCAHQgIAEgCAJQgEACgEAFIgIAIIgPAMQgKAHAAAHQgNAGACANIgDAEIgCAGQgFACgBAJQgCAAgEAFIgFAFQgJAKAAgEQgDABgBAHQAAAGgIAAQAAABgEAEIgFAEIgBALIgGAJQgEAGgBAEIgMAKIgEAMIgGAEQgBACABAFQgBAAgEAHIgDAJQgDABgFAIIgHAHQAAATgIADQgGACABAJIAAANQgEAAgBAZQgBAZABAAQABgJAIgNQAKgOABgHQADAAAFgIQAEgGAAgDIALgUQACgBAFgIQAEgHAEAAQAEgPALgCQgCgKAMgGIANgPQABgEAJgIQAIgHAAgFQAFgCAGgIQAFgJAFgCQAAgDALgJQAJgIAFgDQAAgDALgHQAKgGAAgCQAGgEANgNIAPgNQAEAAADgFQADgFAEAAQACgEAHgGQAHgFAEgBQABgDAFgEQAHgEABgCQAIAAALgMQAMgMAGAAIAKgHQAIgFAAgCQADgBABgDQAAAAAAgBQABAAAAAAQABgBABAAQAAAAABAAQAIAAgCgGIAGAAQAAgCARgIQAQgJAEgBQAAgEATgKQARgJAGAAQADgGAJgFQAIgEAHgCQAAgBAJgEQAJgEACAAQACgCAUgJQATgIAAgBIAEgEQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAQABAAABAAIAGgBQAAgCAIgDIAIgCQADgDAIAEQACgJAFAAQAGgGAIAAQAAgCAHgCIAKgDQAFgHAZgGQABgCAGgBQAFgCACgCIAGgCIAHgCQAAgCAGgBQAGgBAAgBIAEADIAdgQQAAgBAMgDQALgCAAgCQAXgGAAgCIAJAAQAHAAADgEQADAAAPgJQABAAABAGQAAgIAVgEIAMgEQAJgDABAAQAQAKgEgHIgCgDQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAugJQACgEAXgEQAWgEAAgBIAIgDQAEgCADAAQAAgDARgBQATgCABgCQADAAADgDQADgDADAAQAAgCALAAQAngIADABQAAgCAvgIQAHABANgDIAVgGQAYgFAGAAQA9gJAGAAQAJgBAVgEQATgEAMAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAKAFQAIADAAgGIAUgCQA+gHAAACQADABAZgFIAigBQAfAAAAgCIBjgBQAAgCAoADQAsAEAEAAIAKAAQADAEAEgCIAIgCQACAHgDgBQgBAAgBAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgFAEgNAAQAAAAAAgBQAAAAgBAAQgBAAAAAAQgBAAgBAAIgFACQgEAAgDgCQgDgCgCAAQgNAHAAgEQgQACgIgCQAAgCgMABQgMACAAABQgLAAgKABQgCAFgGgCIgKgDQAAADgLAAQgKgHgCACIgDADIgFABQgDADgGABQgDAAAAAHQgMAAgCAIQgCAIAMAAQACADAKABQAKABADACQAAgFAHADIAKADQAAgEANACQAIABgDACIgFADQgCACgJAAQgIAAgEgCQAAABgHABQgGABgBAFQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgCADQgKAAgIACQgKADgHAAIgqADQgCAEgLAAIgRAAIgtACQAAABgfAEQggADgFgBQAAAGgzgBQAAABgIADIgJACQgYAAAAADQgFgBgOADIgiACQAAABgVAEIgYADQAAgDgKAHQgLAGAAACIAhAAIAbgEIATACQADAAAFgCQAEgCAFAAIAOgDQANgCAAACQAFABAHgFIAOABQAAAFALgHQAKgBARgDQAAgCAJAAQAGgBAFABQAGACAGgBQAGgCAFACQAAgDARgDQARgEAAAFQArAFAAgDIAJABQAGABAAADQgNAHgDgBQgFgBgKABQgLABAAADQAkgDBBACQANAAAaAEQAYADANAAQAlAAA5AKQArAFAAAFQAFAAAXAFQAZAFAAADIAIAAQAEAAABgEQAJgDAFAAQAFAAAFACQAAABAIACQAIACAAACQATAAAZAOQAPASgBAAQAAAGASAAIgLgKQgIgHAJAAQAGAAAJAFQAJAFAFAAQAqAWAEAAQAAABAPAEQAOADAAADQADAAAHAEQAIADADAAQAAABAoAOIAZAOQASALAAAHQAEAEAFACQAAACAJAIQAKAIAAADQAHAMACAAQAAADAEAGQAEAGAAAEQABAAACAHIACAJQAEAAAFATQAFATADAAIAJAUQAFAMAAAKQACAAAFAbQACAAAGAXIANAyIAHAaQAHAXgDAAQACAGADApQABADgCAFIgCAIQgCAAAAAGIAAAJQgCAAgDAIIgDAJQgDABgFAPIgFAPQgBADgDAAIgDAAIgBAGQgBAAAAAAQgBABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgIAAIAAAEQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgEACgBAGQgCAAgDAGQgDADgCgFQgHABgFAFQgEAAgCAIQgCAIgCABQAAAHgGADQgGADgGgCQABANgJgDQgMgEgCAEIAAAMQgCABgDADIgCADIgEACQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAGQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQgJgCAAABIgKAEQgEAAgCADQgCAAAAAFQgBAFACAAQgBAKgNABQAAgDgIgBIgLgCIgGADQgGACAAADQAAADgMACQgEABgKAFQgKAFAAADQgCAAgNAHQgNAHAAACQgFACgDAHQgCAFgHgCQAAACgDAEQABAAACAEQACADAAACQgGACgLgDQgLgDgFABIABAKQAAAGgFAAQgCgDgEACQgBABAAAAQAAABAAABQgBAAABABQAAAAABAAQADACABADQgEACgFAAIgJAAQgCAAgHgFQgHgEgFAFIgDAGQgBACgEABIgHAEIgFADQgBAFgJAAIgPgBQAAAHgJADQgLADgCADIgDADQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAgBgBQgCgDgDAAQgEgBAAAEQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAIAAAGIgMABQgDAAgGAFQgEADgDgHQgDgBgDAFQgDAEAAAEQgFAAgFADQgFADAAAEIgGgBIgHABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAADQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgEAAIgPADQgFAGgHACIgPACQAAAAgBAAQAAABAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAADABAGQAAAEgNgEIgHAFQgHAEAAADIgJgBQgEABgCAGIgJADQgHABgCgEQgGADgHAFIgMAIQAAAGgRgDQgSgDAAAIIgFgCQgBgBgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBAAgDAFQgDAEgCgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgGAHQgDAFgFgBIgEAAIgFACQAAAAgBABQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgFAFIgJAEQgHADABABIAYAAQAOgBAIgDQADgBAcgFQAYgFAAgDQADgBAFAGQAEAGAEgCIARgFQACgFAZgDQAAgBALgDIALgEIALgCQAJgBgBgDQARgHABAHIAPgGQAKgDAHABQgSALgFABIgpAUQABgGgKACQgIABgEAEIAEADQgEAAgUAIQgUAIAAACIgJABQgIACAAADQgFABgFgBIgJgDQgBAKgHgBQgMgBgCABQAAABgIABQgJAAABAEQgRAJgKABQgWADAAACIgIABQgGgBAAgBQgDgBgEABIgHACQgWAMAAgIQgDAAgEACQgFABgBADQgDgBgIADIgGADQAAABgVAEQgGAAgFAEQgGAEAKABQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIADABQAAgDARAAQAQgBAAgCQAIAAAWgHIAdgEIAkgGIAVgEQATgEAAABQAIAAAMgEIASgHQgBgBAOgFIAQgEIAVgIQAPgHAEAFIgUAKIgRAHQgGABgLAGQgMAFgEABQABADgKACIgNACQgKAGgLACQAAgCgMAIQgCAFgDgFIgDgDQgEABgFADQgFAEgDAAIgKADQgJABAAADQgFAAgGACQgGACgGAAQAAAJgLgMQgCAGgBAAQgDgFgJACIgLADQgFAGgBADQgFAAgEgDQgFgDgEgBQAAAFgGAEIgLAEQgXALgNgLQgMAEgDAAQAAAHgPAAQAAACgMADQgLADgEgBQAAgEgIAAIgMAAQgCAHgBAAIgHgBQAAACgVgBQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAADgJAAQAAgGgEAIIgDAEIgIAEQAAgEgHABIgIACQgCABgQAAQgOAAgBADIgYAAQgFAAgHgDIgMgDQgHAHgIAAIgRgDQAAABgKADQgKACAAABIgPACQgMACgEgEQAAgBgNAAIgRgBQAAAFgHgBIgKgCQAAADgPABIgFAAQgKAAAAgDgACUKCQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAdgDQAZgCABAEQABAAAAAAQABAAAAgBQAAAAABgBQAAAAABgBQACgDADAAIAEAAIADgBQAEgBAGABQAHAAADgBIAOgFQAJgCAHAEQABgGAEADIAFAFQADAAAFgFQADgGAEABIAHACQADAAAFgDQACgBAFAAIAHgCQAFgBABABIABAFQAEAAAEgGIAJgDIASgFIALgBQAHgBAEgDQALgFADAAQgFgBgPAEIgTAGIgfADQgPACgVgBIgWAEQgSACgBgEQgNACgBABQgKADgJgCQgKgDgNACIg1ADQgFABgCgFIgKADQgBgDgFgBQgIgBgCgCQgLAEgEgBQgMgDgagBIgagBQgFAAgJgCIgOgBIgMAAIgKgCIgBACQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgDgCgCABQgBgDgFgBIgHAAQgKgDgYgBIgOgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABIgDABQgLABgIgDIgFgDQgCgCgDABIgNAAQAAgCgFAAIgHAAQgDgBgEAAIgIAAQgEAAgDgCIgGgEIgPgDQgJgBgEgEQgFgEgBAAQgCACgEAAIgKgCQgGgBgEABQgBgEgMgDQgIgCgGAAQgDABgDgDQgCgCgDABQgDAAgGgBIgKgEQACABgSgIQgQgHAEgBQgCgBgHAAQgGABgDgCQgIgEADgCIgQgFQgDgBgPADQgRADgOgBIApAdQARgBALAEIANAFQAIgBAMAGIAMAFQAKAEAAACIAHgCQADgBACADIAGAHQACgBAIgBQAJgBABADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIASAGQADACAFAAIAIABIASAFQAEACAFABIAJABQAQAEAjAEQA8ALA6AFIAbACQARABALACIAhABQADgBALACIAQABIAMgBQAIgBAEACQABAAAAAAQAAAAABAAQAAAAABgBQABAAAAAAIABgBQABAAAAAAQAAABABAAQAAAAAAAAQAAABABAAgAGCH/IgCgHQAAgDAHAAQABABAHgBQAHgBABgCIAPADQALACAAgEQAGgHAHAFIAMAHQAGAAAAgDQgBgEADgCIAHgCQACAAACAEQAIgIAQgBQAJAAAQABQAAgBAFgCIAGgDIARAAQAAgCAPAAQACAGAEAAQAAgGAIgBQAHgCAAACIAJgCIAJgCQAAAAABgBQAAAAABAAQAAgBABAAQABAAABAAQADAAACgDQALgFAIADQACAAATgEIAGACQAAAAABAAQAAgBABAAQAAAAAAgBQABgBAAgBQAAgBAAgBQABgBAAAAQAAAAABAAQABgBAAABQAFACABgBQAAgCAPgDIARgDQABgCAOgFQANgFAEAAQADABAEgEQAEgDADAAQAAgDAQAAQAGABALgHQAGAAALgFQALgGAGAAQACgDANgEQANgFAFAAQABgCAMgEQALgDAAgBIAVgIQADAAAEgCQAEgDAEAAIAKgEIAHgDQAEgCAEgBQABgDAGgBQAGgCACgCQAEAAAIgDQAJgEACgCQAEAAAHgEQAHgEADgEQAFAAAJgFQAIgFAGAAIAYgMQAAgBAVgIQAWgJACgDQAFAAAJgFQAIgGAGAAQAFAAAGgGQAHgHADAAQAEAAAGgGQAHgGADAAQAHAAAKgIQAEgCAHgHQAAgBAGgCQAGgCAAgCQgHAAAGgCQAFgCADAAQAAgEAJgBQAHgBADABQAAgDADgEQADgFAAgFIAQAAQAAgEAEgCIAIgFIANgIQAAgFAMgGQALgGAAgCQAMgCADgDQAGgEADgJQAFgBAQgbQAMgGAGgKIACgEQABgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAQADAAAFgJQAFgKAFAAQADgFAAgJQAFgDgBgEQABAAACgMQACgNACAAQAAgBgCgFIgEgGQAAAHgLAAIgFAGQgEAGACAAQAAADgHAGQgIAFAAACIgFAGIgGAIQgDAAgFAFIgIAFIgFADQgFADABAEIgJADIgHADIADAAIgBAEQADAAgMAKQgDADgIAAQgHABgCACQAFAAgFAHQgFAGgEAAQgJAMgOADQgEAIgOAFIgCACQgBAAgBAAQAAABgBAAQAAABAAAAQAAABAAAAIgKABQgCABAAAHQgbAFAAAGQgPALAAABIgJADQgGACgEAAQAAADgFACQgEACgEAAQgEgGgEAHQgEAHgCABQAAACgKAGIgMAGQgEABgIAGQgJAGAAAEQAAACgMAEIgQACQAAAEgJACQgJABABAEQAAABgaAFQAAAHgOAGQgLAFgKABQAAgFgOAHIgOAGQgDAAgJAEQgIAEAAABQgEAAgHADQgHADgEAAQAAACgJAEQgIADgCgBIgBADIgBADQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgDABgCgCQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAFIgDAAIgCgBQAAADgFABQgGABAAABQgEACgCgBQgDAAgDACQgDADgMAAIgIAGQAAABgKADIgNADQgNAGgDAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAAAABIgYAKQgYAGgGAEQAAADgXAAIgHAEQgEABgBAFQgFACgEgBIAAAFIgPAAQAAAGgGABQgHACAAgCQgDAAgLAFQgJAEgFgBQAAgBgGACIgHACQgDADgIAAIgMgBQgCAEgLAAIgbAJQAAABgFACIgJADQgFADgKAAQgDgDgDACIgFAEIgKgDQAAAHgNABIgTABIgIABQgFACgBADIgMgBQgcALgDgBIgUACQgSADAAACIgPADIgOACIgHACQgFACAAABQgIAAgQACQgVAEgDAEQACgCATAAQAAAEAZAAQADgEALABIAQACQAAgEANACIAOABQACAAADADQADACADAAIAAAAgAn2HeQgCAEgDAAIANAKQAJAGAEAAIADgDQABAAAAgBQAAgBAAAAQgBgBAAAAQgBgBgBAAQgBgDgGgFIgKgFIgDgCIgCACgAAUGwQACAEACAAIAIACQAFABACgEIADgBQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAgBAHgBQAHgCAAgBQAigBAAgFIAGABQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAFgBANADIAJgDQAGgDADAEQACADAFgBQAFAAACgDQACgCAFACIAIACIgEgEIADgGIAKgCQAGAHAAgFIASABQAFgCAHgHQACgBAKABQAJABADgDQAEgEAHAAIALABQACgFALABIAOABQAAgDAHABIAJADQAAABAKgHQAKgBAOACQAAgIAPgBQAAgBAVgEQAVgFADABQABADAMAAQAMAAACgEIACgFQAEgEADAFQACABAEAAIAGAAQAAgIABgCQACgBAIABQABAEAHgDIALgDQAEgBAKAEIAIgEQAAgFANgDIARgCQAHgDAEgGQADgCAHABIALABIgBgFQAEAAABgCQACgDADgBQADgBADABIAHACQAAgCAPgCIASgBIgCgEIADgBQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAJgBAHgEQAJgHAFgCQAXAAADgFQANAAABgCQAGAAgDgGIAKgBIAEgGQABgBAAgBQABgBAAAAQABAAAAAAQAAAAAAAAQADABADgCQADgCADABQAAACAHAAQAHAAAAgCQAHAAAEgDIAJgIQAHgBAEAAQACgEAEABQAGACACAAQAAgBASgGIAUgIQgDgDABgCQACgCAFAAQADADAFgCIAIgDQAAgBAHgBQAHgBAAgDIAGACQAIgFgEAAQgBgDAPgEQAQgEAAgCQAHAAAHgDIAOgIQABgCAIABQAHABAAgEIADgDQABgCAFAAQAEAAAHgDQAAgBAKgDQAKgCADABQgBgFAFgDQAGgEACgDQAPABAAgDIAHABQAEAAABgEIAKgIQAAgDAIgEQAHgFAEAAIALAAQAAABATgLQAAgDAHgFIAIgFQAGAAAIgHQAIgIAFAAQAAADASgNQAIgGAKAAQAUgNAAgCIAWgPQALAAAMgIQADgHAEAAQADgDAJgDQAJgEACgDQAFAAADgGQADgHADAAIAKgHQABgDAEgEIAHgGIAGgCQAFgBABgCQAAgFANgGQAMgHgBgDQAVgZADgBIAHgPQAFgKgHgDQAAgCgHgEQgIgDgBgDQAAgDgEgCIgHgFQgMgLgGgDIgQgHQgNgHAAgDQgGAAgJgFQgKgGgEgBQAAgBgJgFIgKgHQgEgBgIgFQgHgFgEAAQAAgBgSgEQgUgHgDgDIgQgIIgKABQgHABgEgBIgFgCIgHgBQgRgLgDAAQAAABgSgHIgJgDQgDgEgGgCIgKgBQgtgKgGgBQgGgHgWADQgSACgDgEQgDgEgHAAQAAgBgOACQgPACAAgDIgTgBQAAgEgGgBQgHgHgIAEIgNAFQgHAAgKgEIgRgGQAAAFgXgBQgWgBAAgJQABgEgFgBQgEgBgFABQgCADgIgCQgBgBgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAADgJgBQADAHAAAEQAHAAACAeQACAcgCAIQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABABQAAAAAAAAQgBABAAAAIgBAUQgBATgEAAQgBADADADIgIAQIgGANQgFAIAAAGIgGAPQgFAOgHAAIABAFQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIAAAEQgCAAgCAGQgBAGgDAAIAAAEQAAABgBAAQAAAAAAABQAAAAgBABQgBAAAAABIgFAEIgBAHQgDAAgBAFQgBAAgGAIQgHAJgFABQgBADgIADQgIACABAFIgCAFIgCADQAAACgEAEIgGAFQAEAKgSACQgBAGgHAEQgIAGgCADQgFAIgTAJQgCABgDAEIgFAFQgJAAgRAOQgUARgFACIgNAFQgJAEAAAEIgLAHQgGAFgGABQAAgBgFAFQgFAEABAAIgKAFIgKAGQAAABgLADQgMADAAAEQgJAAgRANQgSAMgMAAIgKADQgIAEgBABIgJAHQgFAFgFAAQgeAKgEAAQAAACgJAGQgJAFAAgEQgEAAgHADQgHAEgDADIgLACQgFABgEAFQgFAAgKAGQgJAGgEAAQgDAFgVAAQgCADgDACQgEABgBACIgGABQgEABgCgCIgGgDQgHgBgGADIgKAIQgBAFgNAEQgDAAgIAFQgHAEgEAAQgsANgHAAQAAADgZAHQgaAIgDADQgTACghANQgHADgOAAQAAAGgPAAQAAACgVAGQABgGgiAKQgEAAgGACIgKAEQAAgBgMAEIgPAFQgIAGgMACIgWAFIAFAAIABABIARACQAOACABgDQAcAAASAEQAsgBAAAFQAFABAvgHQAHgDAHAEIANAHQAAgCAQgCIAUgCIAQgBQAEABACADgAqtGZQgHgMAAgBIAHAFIAGAEQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIADgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgGAAIgCgBIgBAAIAAgBQgDgDgDgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgDgBQgjAFAAgEIgJgBIgIgCQAAgEgOACIgQADQgGAJATADQAWADAAABIAVABQARAAAAACIASAAIAAAAgAopGGQgDABAAAFIADAEIAEAFIAHgBQALAAgJgLQgFgEgEAAgAmTFsIAIAOIAFAFIAOACQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAIAOgCQAJgCAEABIBCgLQAAgCAVgDIAYgEQBOgSAHAAQAAgBAXgGQAXgFAEAAQAAgDAWgEQAWgDACgEQAHAAAKgEQALgDAGgBQAGAAALgEIAQgFQACgDAdgHQAagGgBgHQAYgBAAgDQAJgBARgHQAAgBAJgCQAJgCAAgBQADAAADgCQABgBAAAAQABgBAAAAQABAAAAgBQAAAAAAgBIAGgBIAFABQAAgDAQgFQAOgEAFAAQACgDAJgDQAKgCAAgDQAEAAAIgDQAJgDACgDQAGAAALgEQAJgEAFgEQAGgFAPgDQABgCANgEQANgEAAgCIANgGIAOgHIAPgFQAKgEADgEQACAAAJgFQAIgEAAgBQAEAAAIgEQAIgFADgDQAKAAAOgKQAOgKAIgBQACgEAUgJQATgKgBgCQAAgBANgHQAOgHAAgBIAHgGQADgDAFgBQAKACAEgGIAEgIQAEgIAFAAQAAgBAFgEQAGgDAAgCQAFgBAIgHQAIgHAFgBQADAAACgFQACgFADgBIAIgFIALgKQAEgCAFgHQAFgHAEgCQAAgFAOgMIAOgRQACgEAFgIQAGgIACAAQABgGAFgHIAGgMQACAAACgFIACgGIACgHQACgGgBgDQgFAAgJAOQgKAQgEACQAAAGgMAJIgLAKQgGAHgEACQAAAFgHAFIgKAKQgBACgIAFQgHAEAAAEQgDABgDAEQgDAEgFABIgEAFQgEADgCAAIgHADIgIADQAAACgEADQgFAEgBADIgKAGQgHAGgBACQgDAAgJAGQgJAGgCADQgKADgQANQgPAMgMACQgFAGgMAEQgLAEgIAAIgOAOQgFAAgHAGQgHAFgDAAQgCAEgIABQgHABgDADIgHADIgGADQgCAAgEAEIgFADQgCAEgJAAQgJABgDAEQgEACgDAAQgCAEgIABIgNABIgJABQgGAAgDABQgDABgDAHQgDAGgEABQgEAEgFgCQgHgCgDABQAAAEgFACQAAAEgVAJIgbALQgDAAgFADQgFADgDAAQAAACgNACQgEAEgIADQgHACgGAAQAAACgNADQgNADAAADIgNACQgKACgCADQgGAAgCABQgDABgFAFQgHAAgGACIgNADIgWAHQgBACgKACQgKACAAACIgbAHQgFAAgIADQgIADgFAAQgCACgOAEQgNADAAABQgDAAgFADQgFADgDAAQgBACgGABQgFABgCgCQgRAHgCAAQgDADgNADIgMACQgEABgKAEQgIADgEAAQAAACgOAAIgQgCQAAABgJADIgMACQgPAAgMAFQAAAFgLACQgMABAAABIgXAAQgQAAgFAFIgDACIgDADIgJADIgHACQgCADgcAEQgcAFAAACIgFAAIgFAAgAxuEwQAAgCgHgCQgFgCgEAAQAAAGAQAAgAzoD+IgCADIAOALIAKACIALACQAEAHAcAKQAbAKAAgGQgOAAAAgHQgQgCAAgCIgUgKQgCAAgEgIQgEgHgGAAQAAgDgKgBIgKgBIAAAAIgGACgAmhD9QgJAEgBADQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAIADAAQAAACAsgFIA0gGQAAgDAWgEIAcgFQABgDANAAIARAAQAFAAARgGQANgEAIACQAAgCATgDIAWgEQAAgFALACQAMACAAgEIAKAAQAGAAADgEIAJgDQAFgGAQACQAQABACgFQgIAAAHgEQAGgEAEAAIANgBIAEACIAFABIASgEQAAgCgFABIgHABQgDgGAcgHQAXgHAKAAQAAgBALgCQALgBABgCIAHgCIAHAAIADADIAFABQAAgBAAgBQgBgBABAAQAAgBAAAAQABAAABAAQgCgFAEgBIAJgCIAKAGQAKAGADgBIgHgDIgDgKIAGgFQADgBAFACQACABAMgFQALgFAAAEQADABAEgCQAEgCAAgCQAOAAADgFQAAgJAJAAQACgEAKAAIANAAQAFgBADgEQADgEADAAIAVAAIAEgJQADgDAEABIAGADQgBgJAGABIALADQADAAAEgDQAEgEADAAQACgCAJgFQALgFABACQAAgHAUgCQAUgCAAgCQAIAAAFgBIAFgDIAGgDQACgDALgDQAMgDAAAGQAEABAOgEQAGgEABgFQgEAAAEgHIAFgIQAEgCAAgJIANgHQAJgFAGAAQABACAKACIAMACQAAAEAMgGQALgFACgEQgHAAgCgMQAFAAAMgPQASgEAAgCQAMgCAOgGIAWgKQAFgFARgHQAOgGADgHQAGgCANgOQALgMAHAAQACgDAFgDQAFgEACgDQACgCAHgGQAHgFAAgEQACAAAFgIQAFgHAAgCQAEAAAJgXQAKgXgCgFQgCAAAAgMQABgMgEgCIADAAQgBAAgDgHIgHgRIgSgBQAAACgPgEQgPgDAAADQgmAHAAgBQgLABAAgCIgIABQgFABgDgDIgHABIgJABQAAgBAAAAQAAAAgBAAQgBAAAAAAQgBAAgBABIgGABQAAAEgMABQgLABgFgBIgPgBIgDAFQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIgOABQgCAHgNgEIgUgGQgBACgIABQgFABAAAHQgYAAgEABQAAADgUABQgUABAAACIgZABQgLAAgDADIgBABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgQABQAAABgGACIgIABQAAgBgSADQgTACAAACIgMADQgIACgFAAIgJAIQAAAEgJgHQgDAAgBADIgCAFQgBADgEABIgGABQAAAEgMAAQgBACgEABQgEABgDADQgDADgGAAQAAgEgGABIgKACQAAAFgWgCQAAAGgJADQgLADgCACQgCAAgEADIgHAEQgEACgCgBQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgDAAgCgCQgEgCgCAAIgIADIgIACQgDgCgEACIgHADIgEAEQgEAEAAACQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABIgBAEIgEAFIgCAAQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgDABgCgCQgDgCgCABQgFAJgVACIgUAMQgKAEgEgDIAAgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAQAAgBgKAHQAAAHgEABIgIgCQgBgBgHADQgHADgBACQgFAAgDADQgDADABAEIgMACQgNADgEAFQgEAAgBAFIAAAGIgRAJQgEAGgIAAIgMgCQACAMgGACIgMAHQgMAIAAgFQgGgEgBADIAAAEQAAADgKAIQgLAGgEABQAAACgGAEIgKADQAAgGgFAEQgHAFACAAQAAAFgHAIQgGAHgFAEQgCAFgFADIgKAEQgJADgDgEIgIAHQgFAFAGAAIgCAHIgGAJQgFAGgCAAIgKAJQgHAHgCAEQgGAAgCADIgEAJQgEABgEAFIgGAHQACAEgZAYQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIAPgBIAqgFQAAAFARgHIAFAAIADgCQAAAAABAAQABgBAAAAQAAAAABAAQAAAAAAABIAEACQABgFAKgDIAJgEQAGAAAVgEQASgDAEAIQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAgBABAAQACgEACAAQAAgBAFABIAHAAQAAgBAGAAIAJgBQAAABAAAAQAAABABAAQAAAAABAAQABAAABAAQAAgKAqAAQAAgEAKgBIAOgBQAAgHAZgBQAZgCAAADQADgBAEgEQAEgDACAAQAAgCAHACIAIACQAAAHAVgMQAAgCAHgDIAJgCQAFAHAHgBIARgDIAOgBQAHgBAAgGQgEADgEAAQAAgEADgCQAEgCABgCIAOgCIAGgCQAAgFALAAIAPAAQAHAHAGgGQAJgKAEgBQAMAAAAgCQAFAAADAFQACAFgHAAQAAAEAHACQAGADAAgFQgEAAgBgDQAAgEAEAAQAAgCAKAAIAGgEQAFgCAAgDQAHAAAEgDQABgCAEABQAEABACgBQAEgHALAAQACABAHgDIAIgEQAVgLAAAFQALAAgDgBQgIgEgBgCQgHgCAGgCIAJgBIAFAGQACACAEABQAMAAAAgCIAYgLQAFAAAJgEQALgEAFAAQAAgEAMgEQAKgDAFAAQABgCAFgCQAFgCACgCQAQgEACAAQAEABADgDQAFgFADgBIAJgFQAHgDACAEQACADgLANQgEAAgHAGQgIAFgEAAQAAAFgNAGQgOAGgCAEQgCAEgKACQgIABgCAEQgEAAgHAFIgJAHQgcALAAgBIgTAPIgMAEIgLAEQgZAGgGAIQgGgBgGAEQgGADgEAAQAAABgMABQgLABAAAGIgQADQgLACgEAEQgMAGgHABQAAACgJADIgKAEIgEAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgKADQgEAGgJABIABADIgGACIgHACIgJAAQgFgBgEABIgKAGQgKAFAAgBQgIAAgPAFQgPAFgJAAQAAABgWAEQgWAEAAADQgdALAAgEQgEAAgIAFQgHAFgEAAIgQAFQgRAEgBABIgZAFIgkAJQgaAAgCAEIgIACIgIACQAAgDgUAHIgNAEQgIADgHAAQgKADgFAAIgTAAQgFAFgMAAQgNgCgFABQAAABgIACIgLADIgBgBIgIACgAz3D2QAEgHgIgCQAAgBgEgEIgFgFQgDAAgIgFQgHgEgEAAQgBgDgHgGQgHgGgDAAQAAgCgLgIQgLgIgEAAQACAFAGAIQAGAHAFADQANAKgCAAQADAFAGAAQAWATAAgCQACABAFgCQAAAHALAAgApzCuIAGAEQgEABgCADQgDAEADADQAFADgDADIgEAEQATgEAAgBQADgBAFABIAHACIAEgBIADgDIADgBIAKgCQgFgZACAAIgCgJQgCgGABgDIACgOQABgIABgEQADAAgBgIQgBgIgGgBIgMASQAAAFgGAJQgGAJABAEQgGADgCACIgEAJQgCAAgCAEIgDAFQAAAEgIgGQgBABAGAEgAnqBaQgEAAgDAIQgEAKgDABQgDAVgBAAIAAACQgDAAgDAUQgDAUACADQADgBAFgIIADgIQADgHACAAIAFgLQAEgIACAAIADgHQAEgFAAgDQACAAAEgJIAFgLIAIgGQAHgGAAgCQAEAAABgDIABgIQACAAACgDQABgEADAAQAIgJABgEQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIACgFQAIgFAHgLQAEAAAGgJQAFgJAGAAQAegLgOAAQAAgGAFgCIAJgDQAAgGAIgEQAIgEAAgFQAFgBADgEQAEgFADgBQACgDAMgGQALgFAAgEQAKgGAGAAQAAgEAIgFQAIgEAAgDIAGgEIAHgEIAHgFQADAAAIgHQAIgGABABIALgGQAIgFACgDQAHgFABgGQAFAAAGgBQAGgCAJgGQAAAHAMgIIAPgKQACAAAGgEIAHgGQABgBAIgDIAIgDQAhgKAAgDQAFAAAJgEQAIgDAGAAQABgEAFACQAHABACgIIAGgCQACAAAHgEQACgCAOgEQANgDAAgCIAJgDQAGgDAAgDQAQgCAAgBIAJgCQAHgCAAgBQAFAAAKgEQALgFAGgBQAAgBAIgDIALgCQA2gRAEAAQAAgBAOgDIAQgEQATABAAgGQAFAAALgDQAKgDAGAAIAfgIQAAgCAMgBIAOgBQAAgCAMgCQAMgBABgCQAEAAAGgCQAHgDAEAAIAMABQAHgBADgDQAXgCAKgDQAAgEAygEQADgFAeAAQASABARgEQAAgFA4gBIA+gBQAAgCAGABQABAAABAAQABAAAAgBQABAAAAgBQAAAAAAgBIADAAIgBgCQgEAAgEgIQgFgIgDAAQAAgDgHgHQgHgGAAgEQAHgCAJADQALADAAAIQAEABAFAEQAFAEACAEQADACAAAFIADABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAEADQAEgBAEABQAGABAMgBIAUAAIAmACQAhABAAABQAIABAHgBQAAgCAUACIAZADQArACAAACIAzAEQArAFAAAGQAKAAAUAFQAVAEAKAAQAAACAPADQAPACAAACQAHABAKAEQAJADAHABQADABAHADQAGADADAAQAAADAJAAQAKABABACIAcAJQAEAAAIAEQAJAEACADQAOAHAAgDIAEABIACACQAEAAALAGQALAGAAABQAFAAAIAGQAIAFAEAAQAAABAHAFQAHAEACAAQAAABAIADQAIAEABACQADADAKAFQAIAFADAEQAHAAgHgJQgGgKgFAAIgEgEQgEgDAAgCQgIAAgHgKQgEAAgKgJQgLgKAAgDIgLgBQgHgCAAgEIgDgCIgGgBQgIgIgCgBIgOgHQgGgEgHAAQgEgFgKgDQgEgBgBgCQgCgDgCgBQAAgCgSAAQAAgGgLgCIgPgCQgHAAgHgDQgIgEAAgEQgIAAgNgJQgNgKgHAAQAAgBgKgCIgKgBQgZgHAAgCIgPgDQgIgDgEAAQAAgEgdgGQgZgEgKAAQAAgCgOAAQgPgBAAgEIgXgDQAAgDgbgCIgbgDQgZgDgMAAQAAgBgMgBQgMgBgBgBIgbgBQAAADgogCQgBgCgOAAQgNgBAAACQgDABgGgBIgIgBQgRACgIgBIgKADQAAABgKAAIgMgBQAAADgVACQgVABgFgBIgwAEIg5AEQgFAAgYAEQgZAEAAACIgXACIgUADQAAAHgyACQAAADgkAGQgCADgJAAQgJAAgDAEQgFgBgGACIgJABQAAACgOABQgNABAAADIgeAJQgSAFgLAAIgdAKQgeAJgCgBQAAAEgNACQgOACgBAEIgOAEQgIACgFABQAAABgHADIgIACQAAABgKAEIgPADQgCAEgLADQgLADgCAEQgEAAgGADQgHAEgDAAQgVAFgFAHQgFAAgIAGQgJAGgFAAQgDADgHAEQgHAEgEAAQgCADgPAIQgEAAgJAHQgIAHgHgCQgBAEgJAAQgBAEgIADQgNAFgHAGIgPAJIgPAJIgJAIQgEAFgFAAQABgCgKAHQAAAGgYAPQgLAMgKAEQAAABgEADIgGAEQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAABgFAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQgDAEgMAHIgDAEIgEAEQAAADgEAEQgDAEgDAAIgFAHIgHAFQAAACgJAIQgDADgEACQgFABgDADQAAADgEACQAAADgDACIgGAEQgCACAAAEQAAAFgCACIgFADQgDAAgCADQgCAFgBAAQgBACgEAGQgEAFgCABQAAAGgJAGQgKAGAAAGQABAAgFARIABAIQgBAFgDABIgBABIAAAAIgBABgAxpmXQgDABgCACIgCAFQgHAAgCADQgCAAgGADQgFADgCACIgHADIgGADQgGAHgTAGQgCAEgKACQgKABgBADIgHAGQgGAFAAABQgOAAgBAHIgSAOQgEAAgPAKQgJAGgGAHQgCADgFADQgFADgCADQAAAHgIAEQgKAEgBAFQgCABgDAGQgCAEgDABQgBACgGAFQgFAEAAADIgJAJIgIALIgDACQACACAlgbQAmgdAHgBIAHgFQAEgDADAAQAAgBAEgCIADgEQgDgBAAgEIAMgBQAIgCACgCIADgCQAAgBABAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgCAGgDQAFgDACAAQACgDALgFQAJgEACgDQADAAAFgFIAHgHQAMgEABgBQADAAAHgEQAJgEADgBQACgCAHAAQAEABABgFQABgJANAAIAHgIQACgDAFABQAFABABgDQACAAAHgEQAHgFACgBQAAgCARgHQAQgHADABIgBgEQAGgBAHgEQAHgEAFgBIALgFQAHgEACgDQADAAAFgCIAHgDQACgCAFAAIAIABQACgFADgCQAGgHAPgDIAYgDQACgDAIgDQAIgDAEAAQAAgDAIACQACABAEgCIAGgEIAIgEQAEgCADAAQAEgGAOgEIAWgEQAGgBALgDQAOgEAAgDIAHgCIAFgDIAJABQAFgBAAgFQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAABgBIACgDIgGgDIgvAMIgCgBQAAACgLABQgKACAAABQgHAAgLAGQgLAGgGABIAAgDQgFAAgKADQgJADgFAAQgEgBgCADIgFAEQgEAEgCAAIgHgDIgIAEQgIADgBAEIADABQgBADgFAAQgEABACgEQgDAAgHADQgHADgEAAIgFACQgGADgBACIgDAFQgDABgDgBQgCAGgOAFQAAABgFABQgFAAAAABIgLACQgEABgCAHIgDABQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgKAAAAgCQgCAAgDACQgEADgCABIgOAHQgNAIACABIgNAGIgNgCIgDABgAlSlJQgFgDAKgGIALgHQAIgDAAgBQABgBABAAQAAAAABAAQABAAAAAAQAAABABABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQACACgOAJQgJAGgFAAIgEgBg");
	this.shape_1.setTransform(7.7928,27.7457,0.4948,0.4948);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABwDnIAAkXQAAgygageQgbgeguAAQgfAAgdAPQgdAPgkAjIAAFEIhjAAIAAnEIBjAAIAAA8IADAAQAdghAogSQAngSAqAAQBLAAAvAtQAxAxAABZIAAEWg");
	this.shape_2.setTransform(117.997,94.1892,0.4949,0.4949);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjCCoQhLhEAAhnQAAhiBNhCQBNhDBxgBQB2AABNBCQBNBBAABlQAABqhMBCQhMBDh4AAQh1AAhLhEgAh4hvQgvAqAABCQAABGAuAsQAtArBIABQBPgBAugqQAugrAAhIQAAhBgwgrQgxgrhKAAQhGAAguArg");
	this.shape_3.setTransform(90.4194,94.4243,0.4949,0.4949);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiqEwQhCgnAAg8QABgyAegeQAfgfBBgOQgygbAAgeQAAgWAWgRQAWgRAjgIIAAgCQg3gVgdgkQgbgjAAgyQAAhIA8gqQA7gqBkAAIDRAAIAABFIhoAAQAeAbAMAWQALAVAAAdQAAAbgPAeQgNAcgTARQgiAghdAPQgoAGgOAGQgXAJAAARQAAASAnAOQAiAMBQAOQBNAOAlAjQAhAfgBAuQAABEg/AmQg/AmhvAAQhmAAhBgmgAhtCYQggATAAAeQAAAiAkASQAkASBEAAQBBAAAlgRQAlgSAAgfQgBgmg7gUQgsgOg9AAQgyAAggATgAhIjvQgdAYAAAhQABAlAbAXQAcAXAtAAQApAAAcgYQAbgYAAglQAAgggdgYQgdgYgnAAQgpAAgeAZg");
	this.shape_4.setTransform(64.4501,100.1526,0.4949,0.4949);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABoAAQBmAAA5A+QA8BAAAB7IliAAQAYCHCQAAQBVAABbg2IAABXQguAcgsAMQgxAOg9AAQhxgBhEhJgAhPiAQgjAdgKA2ID9AAQgDg0gfgeQgggeg0AAQg4AAgiAdg");
	this.shape_5.setTransform(39.7057,94.4243,0.4949,0.4949);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ai3DnIAAnEIBkAAIAABoIACAAQBHhxBKAAQA6AAA/A1Ig1BNQgXgTgbgNQgagMgSAAQgzAAgjAoQgjApAAA6IAADsg");
	this.shape_6.setTransform(19.9101,94.1892,0.4949,0.4949);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Aj1DJQhahSAAh3QAAh3BchTQBfhVCUAAQCWAABfBVQBbBSAAB4QAAB3haBSQhfBXiYAAQiVAAhfhXgAitiYQhGA8AABcQAABcBGA9QBFA9BoAAQBpAABFg9QBFg8AAhdQAAhchFg8QhFg9hpAAQhoAAhFA9g");
	this.shape_7.setTransform(-9.6965,91.7272,0.4949,0.4949);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABnAAQBnAAA5A+QA8BAAAB7IljAAQAMBCArAjQAqAiBIAAQBUAABdg2IAABXQgwAcgrAMQgwAOg/AAQhvgBhFhJgAhQiAQgjAdgKA2ID+AAQgDg0gfgeQgggeg0AAQg4AAgjAdg");
	this.shape_8.setTransform(-41.7282,94.4243,0.4949,0.4949);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ai4DnIAAnEIBkAAIAABoIADAAQBHhxBKAAQA7AAA9A1Ig1BNQgWgTgbgNQgagMgSAAQgyAAgkAoQgkApAAA6IAADsg");
	this.shape_9.setTransform(-61.1773,94.1892,0.4949,0.4949);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ABFDgQgTgLgHgYQhAAuhHABQg2AAgkgiQgiggAAguQABg7A3gkQAfgUBVgbIBYgcIAAgYQAAgpgWgUQgWgTguAAQhZAAhHBLIAAhiQA7g+BtAAQBQABAxAjQA1AoAABKIAADoQAAAXATAAQARAAAkgYIAAA2QgjAVgTAHQgUAIgWAAQghAAgSgMgAhCAtQgxAbAAAkQABAcAUASQAVASAeAAQAsAAArgmIAAiDQhOAXggATg");
	this.shape_10.setTransform(-84.536,94.4243,0.4949,0.4949);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AjIDAQhRhQAAhnQAAiABhhUQBhhUCUAAQBcAAB7AuIAABXQg6gfg0gOQgzgOg3AAQhqAAhHA9QhHA+AABbQAABeBGA8QBGA7BwAAQBsAABug/IAABXQgzAYgwAMQg6AOhFAAQihAAhfhgg");
	this.shape_11.setTransform(-112.7818,91.9993,0.4949,0.4949);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CO_v_white, new cjs.Rectangle(-126.7,-7.3,264.2,124.39999999999999), null);


(lib.BUTTON = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAqIAlgqIglgpIAaAAIAmApIgmAqgAg2AqIAmgqIgmgpIAbAAIAlApIglAqg");
	this.shape.setTransform(34.925,4.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag5BQIAAicIAeAAIAAAOQAHgIAJgFQAJgEAJAAQALAAAKAEQAJAEAHAHQAGAIAEALQAEALAAAPQAAAOgEAKQgEALgGAIQgHAIgJAEQgKAEgLAAQgJAAgJgFQgJgEgHgJIAAA6gAgQgxQgHAEgEAFIAAAoQAEAFAHAEQAIAEAHAAQAMAAAIgJQAIgIAAgPQAAgPgIgKQgIgJgMAAQgHAAgIAEg");
	this.shape_1.setTransform(19.425,6.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgOBPIAAidIAdAAIAACdg");
	this.shape_2.setTransform(9.85,2.025);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgUA3QgMgDgIgIQgIgIgFgLQgEgLAAgOQAAgMAEgKQAFgLAHgJQAIgIALgFQALgEAMAAQANAAAKAEQALAFAHAIQAIAJAEAMQAEALAAANIAAAGIhUAAQACALAIAIQAIAIAOAAIAIgBIAIgCIAIgEIAHgEIANATQgJAIgMAEQgNAEgNAAQgMAAgLgFgAgKghQgFADgEADIgFAJIgCAIIA3AAIgCgIIgFgJQgDgDgFgDQgGgCgHAAQgGAAgFACg");
	this.shape_3.setTransform(1.025,4.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAXBPIAAhGQAAgLgFgEQgGgFgJAAQgIAAgHAFQgGAEgEAEIAABNIgfAAIAAidIAfAAIAAA6QAFgGAKgGQAKgFANAAQAUAAAIAJQAJAKAAARIAABQg");
	this.shape_4.setTransform(-11.8,2.025);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgaBMQgJgEgIgHQgGgIgEgLQgEgMAAgOQAAgOAEgKQAEgLAGgIQAHgHAKgFQAJgEAKAAQAKAAAJAFQAJAEAHAJIAAg6IAeAAIAACcIgeAAIAAgOQgHAIgJAFQgJAEgKAAQgKAAgJgEgAgSgDQgIAIAAAPQAAAIACAGQADAGADAEQAEAFAFACQAGACAFAAQAHAAAIgDQAHgEAEgGIAAgoQgEgFgHgDQgIgEgHAAQgMAAgIAJg");
	this.shape_5.setTransform(-30.65,2.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAXA6IAAhEQABgMgGgEQgGgFgKAAQgIAAgGAEQgHAFgEAEIAABMIgdAAIAAhxIAdAAIAAAPQAGgGAKgGQAJgFAPgBQASAAAKAKQAIAKABARIAABPg");
	this.shape_6.setTransform(-43.35,4.05);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgOBRIAAhxIAdAAIAABxgAgMgxQgFgGAAgIQAAgHAFgFQAGgFAGAAQAIAAAEAFQAGAFAAAHQAAAIgGAGQgEAEgIAAQgGAAgGgEg");
	this.shape_7.setTransform(-52.55,1.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag3BPIAAidIBvAAIAAAeIhNAAIAAAhIBLAAIAAAdIhLAAIAABBg");
	this.shape_8.setTransform(-61.275,2.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// bkgd
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00A7B5").s().p("Aq0C4IAAluITwAAIB6CtIh6DBg");
	this.shape_9.setTransform(-10.4,3.85);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	// shad
	this.instance = new lib.Buttonshad();
	this.instance.setTransform(-80,-15,0.6438,0.6438);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BUTTON, new cjs.Rectangle(-96.8,-15,166.2,56), null);


(lib.BKGDblue = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#256BA2").s().p("A3ZKVIAA0pMAuzAAAIAAUpg");
	this.shape.setTransform(0,66.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGDblue, new cjs.Rectangle(-149.7,0,299.5,132.2), null);


(lib.BKGD = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF8300").s().p("A96WbMAAAgs1MA71AAAMAAAAs1g");
	this.shape.setTransform(0.0067,125.0449,0.7833,0.8714);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGD, new cjs.Rectangle(-150,0,300,250.1), null);


(lib.HEAD3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD3type();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD3, new cjs.Rectangle(-139,0,289.1,52.8), null);


(lib.HEAD2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD2type();
	this.instance.setTransform(0,36,1,1,0,0,0,0,36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-139,0,278,52.8), null);


(lib.HEAD1a = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1atype();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1a, new cjs.Rectangle(-139,0,278,52.8), null);


// stage content:
(lib.CO_Safety_300x250 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,308];
	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_308 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(308).call(this.frame_308).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,2,0,3).p("A3WzcMAutAAAMAAAAm5MgutAAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(309));

	// HS logo
	this.instance = new lib.HS_logowhite();
	this.instance.setTransform(149.9,217.75,0.31,0.31,0,0,0,0.7,71.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(309));

	// CO logo
	this.instance_1 = new lib.CO_v_white();
	this.instance_1.setTransform(240.2,219.2,0.35,0.35,0,0,0,0.1,55.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(309));

	// CTA
	this.instance_2 = new lib.BUTTON();
	this.instance_2.setTransform(-27.3,216.95,0.76,0.76,0,0,0,-10.4,3.9);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(293).to({_off:false},0).to({x:52.7},15,cjs.Ease.quadOut).wait(1));

	// BKGD-orange
	this.instance_3 = new lib.BKGD();
	this.instance_3.setTransform(150,241.25,1,0.2639,0,0,0,0,216.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(309));

	// HEAD1a
	this.instance_4 = new lib.HEAD1a();
	this.instance_4.setTransform(145.5,146.5,1,1,0,0,0,0,24);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(5).to({_off:false},0).to({alpha:1},10).wait(104).to({alpha:0},8,cjs.Ease.quadInOut).to({_off:true},1).wait(181));

	// HEAD2
	this.instance_5 = new lib.HEAD2();
	this.instance_5.setTransform(145.5,158.5,1,1,0,0,0,0,36);
	this.instance_5.alpha = 0;
	this.instance_5.shadow = new cjs.Shadow("rgba(0,163,181,1)",0,0,0);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(133).to({_off:false},0).to({alpha:1},8).wait(95).to({alpha:0},8).to({_off:true},1).wait(64));

	// HEAD3
	this.instance_6 = new lib.HEAD3();
	this.instance_6.setTransform(145.5,146.5,1,1,0,0,0,0,24);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(250).to({_off:false},0).to({alpha:1},8).wait(51));

	// BKGD-blue
	this.instance_7 = new lib.BKGDblue();
	this.instance_7.setTransform(149.75,183.95,1,1,0,0,0,0,66.1);
	this.instance_7.alpha = 0.6992;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(309));

	// PIC
	this.instance_8 = new lib.safety_img1_300x250();
	this.instance_8.setTransform(0,1);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(309));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(57.1,124.5,243.4,126.5);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 300,
	height: 250,
	fps: 36,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/CO_Safety_300x250_atlas_P_1.png", id:"CO_Safety_300x250_atlas_P_1"},
		{src:"images/CO_Safety_300x250_atlas_NP_1.jpg", id:"CO_Safety_300x250_atlas_NP_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;