(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"CO_MhSubstance_160x600_atlas_P_1", frames: [[0,0,232,87]]},
		{name:"CO_MhSubstance_160x600_atlas_NP_1", frames: [[0,0,320,1200]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Buttonshad = function() {
	this.initialize(ss["CO_MhSubstance_160x600_atlas_P_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.MhSubstance_160x600 = function() {
	this.initialize(ss["CO_MhSubstance_160x600_atlas_NP_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.HS_logowhite = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ap9EXIAHnRINagKIgCh7IGDgCIAZKDgAFdgfQgVAOgIAYQgGAUAAAZQAAAaAGATQAJAZAVAOQAVAOAgAAQAyAAAeggQADgDgEgCIgZgYQgCgDgEADQgSARgZAAQgfAAgHgZIgDgKQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIBxAAQAEAAAAgEQAAglgGgUQgIgYgVgOQgVgOgfABQgeAAgVANgAgnAvQgVAQAAAdQAAAdASAPQARAOAaAAQAjAAAQgVIABAAIAAANQAAADAEAAIArAAQADAAAAgDIAAh4QAAgjgSgPQgUgRgtABQgqAAgaASQgDACACADIARAeQACADADgDQAQgKAZAAQAWAAAIAEQAIAHAAANIAAAHQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIghAAQgkAAgUAOgAnMBXIgZAdQgCACACADQAiAdAzAAQAoAAAWgSQAVgRABgeQAAgyg/gGIgUgCQgPgCgGgEQgFgDAAgHQAAgOAYgBQAbAAAXAOQAEADACgDIAVgaQADgDgDgDQgegWguAAQgkgBgVARQgUAQAAAaQAAAzA9AHIAVABQAQACAGAEQAFAEAAAHQAAASgdAAQgfAAgagVIgDgBIgDABgACfgkIAACyQAAADAEAAIAuAAQAEAAAAgDIAAhjQAAgnAdgCQAMAAAPAJQADABACgCIAWgmQACgEgDgCQgNgLgUABQgjgBgOAYIAAAAIAAgPQAAgFgEAAIguAAQgEAAAAAFgAieAiIAABsQAAADAEAAIAuAAQAEAAAAgDIAAh2QAAgegRgTQgRgUgeABQghAAgPAUIgBAAIAAhZQAAgDgEAAIguAAQgEAAAAADIAAD/QAAADAEAAIAuAAQAEAAAAgDIAAhsQAAgPAIgKQAIgJAOAAQAdAAAAAig");
	this.shape.setTransform(25.025,83.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAaAAQABABABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_1.setTransform(27.15,92.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeATQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBQAAgGACgIQAHgTAXgBQAZABAGATQACAGAAAIQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_2.setTransform(65.075,85.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AqIk4IUcAvIAII0I03AOgAhWAjQgVAQAAAeQgBAdAUAPQAQAOAbAAQAkAAAPgVIAAANQAAADAEAAIArAAQAEAAAAgDIAAh5QAAgjgSgPQgUgRgsAAQgrAAgcATQgCACACADIARAfQACACADgBQARgMAZAAQAWAAAIAGQAHAGAAAMIAAAHQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIghAAQgjAAgVAOgAkagrQgVAOgIAZQgHATAAAZQAAAXAHAWQAIAaAWAOQAVAOAgAAQAzAAAdggQADgDgDgCIgagYQgCgDgDADQgSAQgZAAQgfAAgIgYQgCgDgBgIQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIBxAAQAFAAAAgEQAAgmgGgTQgJgZgUgOQgWgOgfAAQgeAAgVAOgADcgxIAAAhQAAAEAFAAIALAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAABUQAAAhAOAPQAOAPAgAAIAUAAQAEAAABgEIAAgnQgBgDgEAAIgJAAQgJAAgDgEQgFgFAAgKIAAhSQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAYAAQAEAAABgEIAAghQgBgDgEAAIgYAAQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAgyQAAgEgDAAIguAAQgFAAAAAEIAAAyQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgLAAQgFAAAAADgABth9IAADKQAAAfANAPQAOAOAfAAIAVAAQADAAAAgEIAAgnQAAgDgDAAIgIAAQgRAAAAgSIAAjGQAAgEgEAAIgvAAQgDAAAAAEgAHggBQAIAIAAAQIAABsQAAADADAAIAvAAQAEAAAAgDIAAh3QAAgegRgTQgQgUgfAAQghAAgQAWIAAAAIAAhaQAAgEgEAAIguAAQgFAAAAAEIAAEAQAAADAFAAIAuAAQAEAAAAgDIAAhsQAAgQAIgIQAIgKAOAAQAOAAAHAKgAmpgBQAHAIAAAQIAABsQAAADAFAAIAuAAQAEAAAAgDIAAh3QAAgegRgTQgRgUgfAAQghAAgPAWIAAhaQAAgEgEAAIgvAAQgDAAAAAEIAAEAQAAADADAAIAvAAQAEAAAAgDIAAhsQAAgQAIgIQAHgKAOAAQAOAAAIAKg");
	this.shape_3.setTransform(-21.95,31.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAbAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_4.setTransform(-24.5,39.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeASQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAgGADgIQAHgUAXAAQAYAAAIAUQACAIAAAGQAAABgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-45.05,31.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AJdAwIAcgBQABAJANAAQAPABAAgNIAAgIQgIAFgMAAQgRAAgLgMQgKgLAAgSQAAgSAKgLQALgMARAAQANAAAIAHIAAgFIAaAAIAABRQAAARgLALQgLAKgTAAQgmAAgFgggAJ4AAQAAASAPAAQAHgBAEgEQAEgEAAgIIAAgCQAAgHgEgFQgFgEgGAAQgPAAAAARgALLAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgALbAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAILAeQgLgLAAgTQAAgSALgLQAMgMASAAQASAAAKAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgKAHQgLAHgOAAQgTAAgMgLgAI0gIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgAFOAZQgRgQAAgaQAAgaARgRQAQgQAbAAQAbAAARAQQARARAAAaQAAAagRAQQgRAQgbAAQgbAAgQgQgAFjgpQgIAJAAAPQAAAPAIAJQAIAIAOAAQAOAAAIgIQAJgJAAgPQAAgPgJgJQgIgIgOgBQgOABgIAIgACHAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgACXAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAAJAeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgPAAQgTAAgLgLgAAygIQgBgMgLAAQgKAAgBAMIAXAAIAAAAgAiVASQAAgWAigCIAJAAIAAgEQAAgIgGAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAh6AQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAlOAfQgNgKAAgTIAegBQAAAGAFAEQAFAFAHAAQANgBAAgIQAAgHgTgFQgTgFgIgGQgLgHAAgQQAAgQAKgJQALgMAUAAQAUAAAMALQAMAJABASIgeABQAAgNgOAAQgMAAAAAKQAAAEAEACQADADAMADQATAEAIAHQALAJAAANQAAASgMAKQgMAIgTAAQgVAAgNgKgAoUANIAAgdIgOAAIAAgXIAOAAIABgZIAbAAIAAAZIARAAIAAAXIgRAAIAAAWQAAALALAAIAGgBIAAAYIgNABQggAAAAgcgAqjASQAAgWAigCIAKAAIAAgEQAAgIgHAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAqIAQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAr0AeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgOAAQgTAAgMgLgArLgIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgANWAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAhOIAaAAIAAAFQAGgHAOAAQAOAAAIAIQAJAJAAAPIAAAwgAHGAnIAAhOIAbAAIAAAGQAHgHAOAAIAAAbQgJAAgGAFQgFAEAAAGIAAAlgADlAnIAAg3IgOAAIAAgXIAOAAIAAgFQAAgQAKgKQAKgJAQAAIAJAAIAAAZIgGgBQgFAAgDADQgDADAAAEIAAAGIARAAIAAAXIgRAAIAAA3gAg7AnIAAhOIAbAAIAAAGQAGgHAPAAIAAAbQgKAAgFAFQgFAEAAAGIAAAlgAjAAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAGgGAMAAQAOAAAIAIQAJAJAAAPIAAAwgAmnAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAHgGALAAQAOAAAIAIQAJAJAAAPIAAAwgApJAnIAAh1IAcAAIAAB1gAstAnIAAgsIgmAAIAAAsIgeAAIAAhwIAeAAIAAAqIAmAAIAAgqIAeAAIAABwg");
	this.shape_6.setTransform(0.175,134.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HS_logowhite, new cjs.Rectangle(-88.7,0,177.5,143), null);


(lib.HEAD3type = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANQgFgFAAgIQAAgHAFgFQAFgEAHAAQAIAAAFAEQAFAFAAAHQAAAIgFAFQgFAFgIAAQgHAAgFgFg");
	this.shape.setTransform(-51.475,91.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYArQgMgHgFgLQgGgKAAgPQAAgNAGgLQAHgMALgFQALgHAOAAQAWABANANQALANAAAXIAAAEIg/AAQAAALAHAHQAFAGALAAQAJAAAFgEQAGgEADgHIAQAJQgDAHgFAGQgGAGgJADQgJADgMAAQgPAAgMgGgAASgHQgBgNgEgFQgEgGgHAAQgIAAgEAGQgEAFgBANIAhAAIAAAAg");
	this.shape_1.setTransform(-58.85,88.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgjBHQgMgCgEgFQgGgDAAgHQAAgGAHgEQAFgFAMgCQgJgDgGgFQgEgEAAgIQAAgHAEgFQAEgFAJgCQgGgEgEgGQgDgGgBgJQAAgKAHgHQAGgIAJgDQALgFANAAQAIAAAHACQAHACAFADQACgJAFgFQAFgEAHgBQAHABADADQAFADAAAGQAAAGgDADQgDAEgGAAQgDAAgDgCQgDgCgBgCIgCABIgCACQAFAFACAFQACAFAAAHQAAAKgGAIQgGAGgJADQgLAEgNAAIgLgBIgKgCIgEACQAAAAgBABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAABAAAAQABABAAAAQAAABABAAQADABAGAAIAOAAIANAAIANAAQARAAAGAHQAIAIAAAMQAAAQgOAJQgOAJgcAAQgUAAgLgCgAgeAtQgDADABAEQgBAFAIABQAGADAQAAQAQAAAIgEQAIgCAAgHQAAgEgDgCQgDgCgKAAIgjAAQgFACgDADgAgOgpQgEAEAAAJIAAADQAAAIAEAEQADAEAHAAQAGAAAEgEQAEgEAAgJIAAgDQAAgIgEgFQgDgDgHAAQgHgBgDAFg");
	this.shape_2.setTransform(-69.3,89.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgrAqQgHgHAAgLQAAgMAJgHQAIgFANgFQAOgDAPgDIAAgEQABgJgEgEQgEgEgJAAIgFABIgEABIACAEIAAAEQAAAHgFAEQgEAEgHAAQgIAAgFgEQgEgEAAgIQAAgJAGgFQAGgGAJgDQALgCANAAQAWAAALAIQAKAHAAARIAAAoIABAFQAAAAAAAAQABAAAAABQAAAAABAAQAAAAAAAAIAHAAIAAARIgiAAIgEgIIgDgIQgCAFgFAEQgEAEgHADQgGACgHAAQgOAAgIgHgAgLAHQgJAEAAAJQAAAEADAEQADACAFAAQAJABAFgHQAEgGAAgJIAAgHQgMABgIAEg");
	this.shape_3.setTransform(-80.3,88.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgrAwIAAgRIAGAAIADgBQABgBAAgEIAAguIgBgFQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgHAAIAAgRIATAAIANgBIAKgBIAAAUQACgLAGgFQAGgFAJAAQALAAAHAHQAFAHABAMQgBAKgFAGQgFAFgJAAQgGAAgEgDQgEgEAAgGQgBgEADgDQACgEAEgCIgDgBIgDAAQgHAAgFAHQgDAHAAANIAAAZQAAAEABABIACABIAHAAIAAARg");
	this.shape_4.setTransform(-90.35,88.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYArQgMgHgFgLQgGgKAAgPQAAgNAGgLQAHgMAKgFQALgHAOAAQAXABAMANQAMANAAAXIAAAEIg/AAQABALAFAHQAHAGAKAAQAJAAAGgEQAFgEADgHIAQAJQgDAHgGAGQgFAGgJADQgJADgLAAQgRAAgLgGgAARgHQAAgNgDgFQgFgGgIAAQgGAAgFAGQgEAFgBANIAgAAIAAAAg");
	this.shape_5.setTransform(-100.2,88.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgKAvIgghHQgBgDgBgBIgDgBIgGAAIAAgRIA1AAIAAARIgHAAQAAAAgBAAQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABABABQAAAAAAABIAEALIAGANIAGAQIAGgRIAHgOIADgJQAAAAABgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAIgHAAIAAgRIArAAIAAARIgGAAIgDABQgCABgBADIggBHg");
	this.shape_6.setTransform(-110.75,88.375);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgaArQgLgGgGgLQgHgLAAgPQAAgNAHgLQAGgMAMgFQALgHAOAAQAQAAALAHQALAFAGAMQAGALABANQgBAPgGALQgGALgMAGQgLAGgPAAQgPAAgLgGgAgOgXQgEAGAAAQIAAADQAAAQAEAGQAFAIAJgBQAKABAFgIQAEgGAAgQIAAgDQAAgQgEgGQgFgIgKABIAAAAQgJAAgFAHg");
	this.shape_7.setTransform(-121.675,88.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AghAkQgOgNAAgXQAAgWAOgNQAOgMAXgBQAVAAALAIQALAJABAPQAAAKgGAFQgFAFgJAAQgIAAgEgEQgEgDAAgHQgBgFAEgFQAEgEAFgBQgCgDgEgCQgEgBgGAAQgKAAgHAHQgFAIAAAOIAAADQgBAOAGAIQAFAHALAAQAIAAAHgEQAFgEADgIIARAJQgFAMgKAGQgKAIgSAAQgXAAgOgNg");
	this.shape_8.setTransform(-131.95,88.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgPIAGgBQAGgBADgDQAEgCABgHIACgPIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADADAGgBIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_9.setTransform(-51.575,63);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAGAwIAAgRIAFAAIADgBQABgBAAgEIAAgjQAAgJgDgEQgDgEgHAAQgHAAgEAGQgFAGAAAOIAAAaQAAAEABABIADABIAFAAIAAARIgyAAIAAgRIAHAAIACgBIABgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAIgHAAIAAgRIASAAIANgBIAKgBIAAARQAEgJAIgEQAHgFALAAQAPAAAHAJQAIAJAAASIAAAkQAAAEABABIADABIAGAAIAAARg");
	this.shape_10.setTransform(-60.375,64.075);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgYArQgLgHgGgKQgGgMAAgOQAAgNAGgMQAGgKALgHQAMgGAOAAQAXABAMANQALAMAAAXIAAAFIg/AAQAAAMAHAGQAFAGALAAQAJABAFgFQAGgEADgHIAQAJQgDAIgGAFQgFAGgJADQgJADgMAAQgPAAgMgGgAASgHQAAgOgFgEQgEgGgHAAQgIAAgEAGQgFAFAAANIAhAAIAAAAg");
	this.shape_11.setTransform(-71.35,64.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAjAwIAAgRIAFAAIACgBQABgBAAgEIAAghQAAgKgDgEQgDgEgHAAQgHAAgEAGQgDAFAAAMIAAAcQAAAEABABIACABIAGAAIAAARIgwAAIAAgRIAFAAIACgBQABgBAAgEIAAgiQAAgJgDgEQgDgEgHAAQgHAAgEAGQgDAFAAAMIAAAcQAAAEABABIACABIAGAAIAAARIgzAAIAAgRIAHAAIADgBIAAgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgHAAIAAgRIATAAIANgBIAJgBIAAARQAFgIAHgFQAHgFAKAAQAMAAAFAFQAHAFADALQAEgKAHgGQAIgFAMAAQAPAAAIAJQAIAJAAATIAAAjIAAAFIADABIAHAAIAAARg");
	this.shape_12.setTransform(-85.025,64.075);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgPIAGgBQAGgBADgDQAEgCABgHIACgPIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADADAGgBIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_13.setTransform(-97.175,63);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgrAqQgHgHAAgKQAAgNAJgHQAIgFANgFQAOgDAPgCIAAgGQABgIgEgDQgEgFgJAAIgFABIgEABIACAEIAAAEQAAAHgFAEQgEAEgHAAQgIAAgFgEQgEgEAAgIQAAgIAGgGQAGgFAJgDQALgDANAAQAWAAALAHQAKAIAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAAAAAIAHAAIAAAQIgiAAIgEgHIgDgIQgCAGgFADQgEAEgHADQgGACgHAAQgOAAgIgHgAgLAHQgJAEAAAJQAAAEADAEQADACAFAAQAJAAAFgFQAEgGAAgKIAAgIQgMACgIAEg");
	this.shape_14.setTransform(-105.5,64.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgYArQgMgHgFgKQgGgMAAgOQAAgNAGgMQAHgKAKgHQALgGAOAAQAXABAMANQAMAMAAAXIAAAFIg/AAQABAMAFAGQAHAGAKAAQAJABAGgFQAGgEACgHIAQAJQgDAIgGAFQgFAGgJADQgIADgNAAQgPAAgMgGgAARgHQAAgOgDgEQgFgGgIAAQgGAAgFAGQgEAFgBANIAgAAIAAAAg");
	this.shape_15.setTransform(-116.05,64.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgsAwIAAgRIAHAAIACgBQABgBAAgEIAAguIAAgFQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgHAAIAAgRIATAAIAOgBIAJgBIAAAUQACgLAGgFQAGgFAKAAQAKAAAHAHQAGAHAAAMQAAAKgFAGQgGAFgJAAQgGAAgEgDQgEgEgBgGQAAgEADgDQACgEAEgCIgDgBIgCAAQgJAAgEAHQgDAHAAANIAAAZQAAAEABABIABABIAIAAIAAARg");
	this.shape_16.setTransform(-125.75,64.075);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgPIAGgBQAGgBADgDQAEgCABgHIACgPIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADADAGgBIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_17.setTransform(-133.925,63);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgYArQgMgGgFgLQgGgLAAgPQAAgOAGgLQAGgLALgGQAMgGANAAQAYAAALANQAMANAAAXIAAAFIg/AAQAAAMAHAGQAFAHALgBQAJABAFgFQAHgEACgHIAQAJQgDAHgGAGQgFAFgJAEQgJADgMAAQgPAAgMgGgAASgIQAAgNgFgFQgDgFgJAAQgGAAgFAFQgEAGgBAMIAhAAIAAAAg");
	this.shape_18.setTransform(-17.6,40.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgWAuQgKgBgHgDIAAgZIAWAAIAAAPIAGABIAJABQAGAAAEgCQAEgEAAgEQAAgHgFgCIgOgEQgIgBgHgDQgIgDgFgEQgEgHgBgKQABgOAKgIQALgJATAAQAMABAJACIAPAEIAAAYIgVAAIAAgNIgGgCIgHgBQgGAAgEADQgEADAAAEQAAAFADABQACACAFABIAJADIAQAEQAHADAFAFQAFAGAAAKQAAAPgLAJQgLAIgUAAQgMAAgJgDg");
	this.shape_19.setTransform(-27.075,40.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgmAnQgHgJAAgSIAAglQAAAAAAgBQAAgBAAAAQgBgBAAAAQAAgBAAAAIgDgBIgHAAIAAgRIAqAAIAAA7QAAAIAEAEQADAEAGAAQAHAAAEgGQAEgGAAgMIAAgdQAAAAAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAIgCgBIgIAAIAAgRIArAAIAABFIAAAFQABAAAAABQAAAAABAAQAAAAAAAAQABAAAAAAIAIAAIAAARIgUAAIgNAAIgKACIAAgQQgEAIgIAEQgGAEgLAAIgBABQgOAAgIgJg");
	this.shape_20.setTransform(-37.225,40.2513);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgYArQgMgGgFgLQgGgLAAgPQAAgOAGgLQAHgLALgGQALgGAOAAQAWAAANANQALANAAAXIAAAFIg/AAQAAAMAHAGQAFAHALgBQAJABAFgFQAGgEADgHIAQAJQgDAHgFAGQgGAFgJAEQgJADgMAAQgPAAgMgGgAASgIQgBgNgEgFQgEgFgHAAQgIAAgEAFQgEAGgBAMIAhAAIAAAAg");
	this.shape_21.setTransform(-52.55,40.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AghAkQgOgMAAgYQAAgWAOgNQAOgMAXgBQAVAAALAJQALAIABAPQgBAJgFAHQgFAEgJABQgHgBgFgEQgEgDAAgGQgBgHAEgDQAEgFAFgBQgCgDgEgBQgEgCgGAAQgKAAgHAHQgFAHAAAPIAAACQgBAQAGAHQAFAHALAAQAIAAAHgEQAFgEADgIIARAJQgFALgKAIQgKAHgSAAQgXAAgOgNg");
	this.shape_22.setTransform(-62.55,40.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAGAwIAAgRIAFAAIADgBQABgBAAgEIAAgjQAAgJgDgEQgDgEgHAAQgHAAgEAGQgFAGAAAOIAAAaQAAAEABABIADABIAFAAIAAARIgyAAIAAgRIAHAAIACgBIABgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAIgHAAIAAgRIASAAIANgBIAKgBIAAARQAEgJAIgEQAHgFALAAQAPAAAHAJQAIAJAAASIAAAkQAAAEABABIADABIAGAAIAAARg");
	this.shape_23.setTransform(-73.325,39.975);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgrAqQgHgGAAgLQABgNAHgGQAJgGAOgFQANgDAPgCIAAgGQABgIgEgDQgFgEgIgBIgFABIgEABIABAEIABAFQAAAGgFAEQgEAEgHAAQgIAAgFgEQgEgEAAgIQAAgIAFgGQAGgFAKgDQALgDAOAAQAWAAAKAHQAKAIAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAAAAAIAHAAIAAAQIgiAAIgEgHIgDgHQgCAEgGAFQgDAEgHACQgGACgHAAQgOAAgIgHgAgLAHQgJAEAAAIQAAAGADACQADADAFAAQAJAAAFgFQAEgHAAgJIAAgIQgMACgIAEg");
	this.shape_24.setTransform(-84.45,40.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADACAGAAIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_25.setTransform(-93.325,38.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgWAuQgKgBgHgDIAAgZIAWAAIAAAPIAGABIAJABQAGAAAEgCQAEgEAAgEQAAgHgFgCIgOgEQgIgBgHgDQgIgDgFgEQgEgHgBgKQABgOAKgIQALgJATAAQAMABAJACIAPAEIAAAYIgVAAIAAgNIgGgCIgHgBQgGAAgEADQgEADAAAEQAAAFADABQACACAFABIAJADIAQAEQAHADAFAFQAFAGAAAKQAAAPgLAJQgLAIgUAAQgMAAgJgDg");
	this.shape_26.setTransform(-100.775,40.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgGA7QgIgGgFgLIgEAVIgXAAIABgFIAAgKIAAgRIAAhGIgBgFQAAgBAAAAQAAAAgBAAQAAgBAAAAQgBAAAAAAIgIAAIAAgQIATAAIAOgBIAJgBIAAAzQAFgJAHgFQAHgFALAAQAMAAAKAHQAIAGAFAKQAFAKABAPQgBAPgFALQgFALgJAGQgJAGgNAAQgNAAgIgGgAgIgGQgFAGgBAPIAAADQABAOAFAHQAFAHAHAAQAJAAAGgHQAEgHAAgOIAAgDQAAgPgEgGQgGgHgJABIgBAAQgGAAgFAGg");
	this.shape_27.setTransform(-111.05,38.475);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgmAnQgHgJAAgSIAAglQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBAAAAIgDgBIgHAAIAAgRIAqAAIAAA7QAAAIAEAEQADAEAGAAQAHAAAEgGQAEgGAAgMIAAgdQAAAAAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAIgCgBIgIAAIAAgRIArAAIAABFIAAAFQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAAAIAIAAIAAARIgUAAIgNAAIgKACIAAgQQgEAIgIAEQgGAEgLAAIgBABQgOAAgIgJg");
	this.shape_28.setTransform(-122.525,40.2513);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgWAuQgKgBgHgDIAAgZIAWAAIAAAPIAGABIAJABQAGAAAEgCQAEgEAAgEQAAgHgFgCIgOgEQgIgBgHgDQgIgDgFgEQgEgHgBgKQABgOAKgIQALgJATAAQAMABAJACIAPAEIAAAYIgVAAIAAgNIgGgCIgHgBQgGAAgEADQgEADAAAEQAAAFADABQACACAFABIAJADIAQAEQAHADAFAFQAFAGAAAKQAAAPgLAJQgLAIgUAAQgMAAgJgDg");
	this.shape_29.setTransform(-132.625,40.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgYArQgMgHgFgLQgGgLAAgOQAAgNAGgMQAHgKAKgGQALgHAOAAQAXAAAMANQAMAOAAAWIAAAFIg/AAQABAMAFAGQAHAHAKAAQAJAAAGgFQAGgEACgHIAQAJQgDAHgGAGQgFAFgJAEQgIADgNAAQgPAAgMgGgAARgIQAAgMgDgGQgFgFgIAAQgGAAgFAFQgEAGgBAMIAgAAIAAAAg");
	this.shape_30.setTransform(-5.8,16);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgYArQgLgHgGgLQgGgLAAgOQAAgNAGgMQAGgKALgGQAMgHAOAAQAXAAAMANQALAOAAAWIAAAFIg/AAQAAAMAHAGQAFAHALAAQAJAAAFgFQAGgEADgHIAQAJQgDAHgGAGQgFAFgJAEQgJADgMAAQgPAAgMgGgAASgIQAAgMgFgGQgEgFgHAAQgIAAgEAFQgFAGAAAMIAhAAIAAAAg");
	this.shape_31.setTransform(-16,16);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgsAwIAAgRIAHAAIACgBQABgBAAgEIAAguIAAgFQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAgRIATAAIAOgBIAJgBIAAAUQACgLAHgFQAGgFAIAAQAMAAAFAHQAHAHAAAMQAAAKgGAGQgFAFgJAAQgGAAgEgDQgEgEgBgGQABgEACgDQACgEAEgCIgCgBIgEAAQgHAAgFAHQgDAHAAANIAAAZQAAAEABABIABABIAIAAIAAARg");
	this.shape_32.setTransform(-25.7,15.875);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgdBBIAAgRIAIAAIACgBQABAAAAgFIAAg0IgLAAIAAgQIALAAIAAgFQAAgMAEgHQADgIAHgCQAGgEAMAAIAKACIAHACIAAAQIgEgBIgDAAIgIABQgDACgBAEQgBAEABAIIAPAAIAAAQIgPAAIAAA0QAAAFABAAIACABIAJAAIAAARg");
	this.shape_33.setTransform(-33.5,14.15);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgWAuQgKgCgHgCIAAgZIAWAAIAAAPIAGABIAJABQAGAAAEgCQAEgDAAgFQAAgGgFgDIgOgEQgIgBgHgDQgIgDgFgFQgEgFgBgLQABgOAKgIQALgJATAAQAMAAAJACIAPAGIAAAXIgVAAIAAgNIgGgCIgHAAQgGAAgEACQgEADAAAFQAAADADACQACACAFACIAJACIAQAEQAHADAFAFQAFAFAAALQAAAPgLAJQgLAIgUAAQgMAAgJgDg");
	this.shape_34.setTransform(-45.625,16);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgrAwIAAgRIAGAAIADgBQAAgBAAgEIAAguIAAgFQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAgRIATAAIANgBIAKgBIAAAUQACgLAHgFQAGgFAIAAQAMAAAFAHQAHAHAAAMQAAAKgGAGQgFAFgJAAQgGAAgEgDQgEgEgBgGQABgEACgDQACgEAEgCIgCgBIgEAAQgHAAgFAHQgDAHAAANIAAAZQAAAEABABIACABIAHAAIAAARg");
	this.shape_35.setTransform(-54.6,15.875);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgYArQgLgHgGgLQgGgLAAgOQAAgNAGgMQAHgKALgGQAKgHAPAAQAXAAALANQAMAOAAAWIAAAFIg/AAQABAMAFAGQAHAHAKAAQAJAAAGgFQAFgEADgHIAQAJQgDAHgFAGQgGAFgJAEQgIADgMAAQgQAAgMgGgAARgIQAAgMgDgGQgEgFgIAAQgIAAgEAFQgFAGAAAMIAgAAIAAAAg");
	this.shape_36.setTransform(-64.45,16);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgcBBIAAgRIAHAAIADgBQABAAAAgFIAAg0IgNAAIAAgQIANAAIAAgFQAAgMACgHQAEgIAHgCQAGgEALAAIALACIAGACIAAAQIgCgBIgEAAIgIABQgDACgBAEQgBAEAAAIIARAAIAAAQIgQAAIAAA0QAAAFABAAIADABIAIAAIAAARg");
	this.shape_37.setTransform(-72.6,14.15);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgcBBIAAgRIAHAAIADgBQABAAAAgFIAAg0IgNAAIAAgQIANAAIAAgFQAAgMACgHQAEgIAHgCQAGgEALAAIALACIAGACIAAAQIgCgBIgEAAIgIABQgDACgBAEQgBAEAAAIIARAAIAAAQIgQAAIAAA0QAAAFABAAIADABIAIAAIAAARg");
	this.shape_38.setTransform(-78.9,14.15);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgaArQgLgGgGgLQgHgLAAgPQAAgNAHgMQAGgKAMgGQALgHAOAAQAQAAALAHQALAGAGAKQAGAMABANQgBAPgGALQgGALgMAGQgLAGgPAAQgPAAgLgGgAgOgXQgEAGAAAQIAAACQAAARAEAGQAFAIAJAAQAKAAAFgIQAEgGAAgRIAAgCQAAgQgEgGQgFgIgKABIAAAAQgJAAgFAHg");
	this.shape_39.setTransform(-87.525,16);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("Ag2A/IAAgQIAIAAQAAAAABgBQAAAAABAAQAAAAAAAAQABgBAAAAQABgBAAgEIAAhPIgBgFIgDgBIgIAAIAAgRIA7AAQAaAAAMAJQANAKAAATQgBAUgLAIQgNAJgbAAIgNAAIAAAbIABAFQAAAAAAABQAAAAABAAQAAAAABAAQAAABABAAIAIAAIAAAQgAgJgCIALAAQALAAAFgFQAFgFgBgMQABgLgFgFQgFgFgLAAIgLAAg");
	this.shape_40.setTransform(-103.3,14.3488);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAMA/IAAgRIAHAAQABAAAAAAQABAAAAAAQAAAAABAAQAAgBAAAAQABgBAAgEIAAghIgsAAIAAAhIAAAFQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAAAIAIAAIAAARIg5AAIAAgRIAJAAQAAAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQABgBAAgEIAAhQIgBgEIgCgBIgJAAIAAgRIA5AAIAAARIgIAAIgDABIAAAEIAAAgIAsAAIAAggIgBgEQAAgBAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAIgHAAIAAgRIA4AAIAAARIgIAAIgDABIgBAEIAABQQAAAEABABQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAAAIAIAAIAAARg");
	this.shape_41.setTransform(-116.2,14.35);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgiA6QgPgIgHgPQgIgPAAgUQAAgTAIgOQAJgPAOgIQAPgIATgBQAUABAPAIQAOAIAHAOQAIAPAAATQAAAUgJAPQgHAPgPAIQgPAIgTAAQgUAAgOgIgAgWgjQgIAKABAWIAAAIQgBAWAIAJQAIAKAOAAQAQAAAHgKQAIgJAAgWIAAgIQAAgWgIgKQgIgKgPAAQgOAAgIAKg");
	this.shape_42.setTransform(-130.1,14.325);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD3type, new cjs.Rectangle(-139,0,150,100.4), null);


(lib.HEAD2type = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANQgFgFAAgIQAAgHAFgFQAFgEAHAAQAIAAAFAEQAFAFAAAHQAAAIgFAFQgFAFgIAAQgHAAgFgFg");
	this.shape.setTransform(-8.675,91.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgjA7QgKgGgFgLQgFgLAAgPQAAgOAGgKQAFgLAJgGQAJgHAMAAQAMAAAGAFQAHAEAEAIIAAgYIgBgFQAAgBAAAAQgBAAAAAAQAAgBgBAAQAAAAgBAAIgHAAIAAgQIATAAIAOgBIAJgBIAABoQAAAEABABIADABIAGAAIAAARIgmAAIAAgGIgBgLQgEAJgHAFQgHAFgMAAQgNAAgJgGgAgRgGQgFAGAAAPIAAADQAAAOAFAHQAFAHAJAAQAIAAAFgHQAFgHAAgOIAAgDQAAgPgFgGQgFgHgIABIgBAAQgIAAgFAGg");
	this.shape_1.setTransform(-16.775,86.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgYArQgMgHgFgLQgGgKAAgPQAAgNAGgLQAHgMAKgFQALgHAOAAQAXABAMANQAMANAAAXIAAAEIg/AAQABALAFAHQAHAGAKAAQAJAAAGgEQAFgEADgHIAQAJQgDAHgGAGQgFAGgJADQgJADgLAAQgRAAgLgGgAARgHQAAgNgDgFQgFgGgIAAQgGAAgFAGQgEAFgBANIAgAAIAAAAg");
	this.shape_2.setTransform(-27.75,88.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgYArQgMgHgFgLQgGgKAAgPQAAgNAGgLQAGgMALgFQAMgHANAAQAYABAMANQALANAAAXIAAAEIg/AAQAAALAHAHQAFAGALAAQAJAAAFgEQAHgEACgHIAQAJQgDAHgGAGQgFAGgJADQgJADgMAAQgQAAgLgGgAASgHQAAgNgFgFQgDgGgJAAQgHAAgEAGQgEAFgBANIAhAAIAAAAg");
	this.shape_3.setTransform(-37.95,88.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAGAwIAAgRIAFAAIADgBQABgBAAgEIAAgjQAAgJgDgEQgDgEgHAAQgHAAgEAGQgFAGAAAOIAAAaQAAAEABABIADABIAFAAIAAARIgyAAIAAgRIAHAAIACgBIABgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAIgHAAIAAgRIASAAIANgBIAKgBIAAARQAEgJAIgEQAHgFALAAQAPAAAHAJQAIAJAAASIAAAkQAAAEABABIADABIAGAAIAAARg");
	this.shape_4.setTransform(-48.775,88.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgmAnQgHgJAAgSIAAglQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBAAAAIgDgBIgHAAIAAgRIAqAAIAAA7QAAAIAEAEQADAEAGAAQAHAAAEgGQAEgGAAgMIAAgdQAAAAAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAIgCgBIgIAAIAAgRIArAAIAABFIAAAFQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAAAIAIAAIAAARIgUAAIgNAAIgKACIAAgQQgEAIgIAEQgGAEgLAAIgBABQgOAAgIgJg");
	this.shape_5.setTransform(-64.925,88.4513);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgaArQgLgGgGgLQgHgLAAgPQAAgNAHgLQAGgMAMgFQALgHAOAAQAQAAALAHQALAFAGAMQAGALABANQgBAPgGALQgGALgMAGQgLAGgPAAQgPAAgLgGgAgOgXQgEAGAAAQIAAADQAAAQAEAGQAFAIAJgBQAKABAFgIQAEgGAAgQIAAgDQAAgQgEgGQgFgIgKABIAAAAQgJAAgFAHg");
	this.shape_6.setTransform(-76.025,88.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgvA6QgHgFAAgLQAAgIAEgFQAFgEAIAAQAGAAAEADQAEADABAFQABAFgDAGQAFgBAEgFQAEgEADgJIAAgBIghhEIgCgFIgDgBIgGAAIAAgQIA0AAIAAAQIgFAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAIAAAEIAQAmIAPglQABgDgBgCQAAgBgBAAQAAAAAAAAQgBgBgBAAQAAAAgBAAIgGAAIAAgQIAqAAIAAAQIgGAAIgEABIgDAFIgcBDQgFANgFAIQgFAJgHAEQgHAEgLAAQgNAAgIgGg");
	this.shape_7.setTransform(-86.925,90.125);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgYArQgLgHgGgLQgGgKAAgPQAAgNAGgLQAHgMALgFQAKgHAOAAQAXABAMANQAMANAAAXIAAAEIg/AAQABALAFAHQAHAGAKAAQAJAAAGgEQAFgEADgHIAQAJQgDAHgFAGQgGAGgJADQgIADgMAAQgRAAgLgGgAARgHQAAgNgDgFQgFgGgIAAQgGAAgFAGQgFAFAAANIAgAAIAAAAg");
	this.shape_8.setTransform(-101.9,88.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgrAwIAAgRIAGAAIADgBQABgBAAgEIAAguIgBgFQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgHAAIAAgRIATAAIANgBIAKgBIAAAUQACgLAGgFQAHgFAJAAQAKAAAHAHQAFAHABAMQgBAKgEAGQgGAFgJAAQgGAAgEgDQgEgEAAgGQAAgEACgDQACgEAEgCIgDgBIgDAAQgIAAgEAHQgDAHAAANIAAAZQAAAEABABIACABIAHAAIAAARg");
	this.shape_9.setTransform(-111.6,88.175);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgqAqQgIgHAAgLQAAgMAJgHQAIgFANgFQAOgDAPgDIAAgEQABgJgFgEQgEgEgHAAIgGABIgEABIACAEIAAAEQAAAHgFAEQgEAEgHAAQgIAAgEgEQgFgEAAgIQAAgJAGgFQAGgGAJgDQALgCANAAQAXAAAKAIQAKAHAAARIAAAoIABAFQAAAAAAAAQABAAAAABQAAAAABAAQAAAAAAAAIAHAAIAAARIgiAAIgEgIIgDgIQgCAFgFAEQgEAEgHADQgGACgHAAQgOAAgHgHgAgMAHQgIAEAAAJQAAAEADAEQADACAFAAQAJABAFgHQAEgGAAgJIAAgHQgMABgJAEg");
	this.shape_10.setTransform(-121.6,88.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AghAkQgOgNAAgXQAAgWAOgNQAOgMAXgBQAVAAALAIQALAJABAPQAAAKgGAFQgFAFgJAAQgIAAgEgEQgEgDAAgHQgBgFAEgFQAEgEAFgBQgCgDgEgCQgEgBgGAAQgKAAgHAHQgFAIAAAOIAAADQgBAOAGAIQAFAHALAAQAIAAAHgEQAFgEADgIIARAJQgFAMgKAGQgKAIgSAAQgXAAgOgNg");
	this.shape_11.setTransform(-131.95,88.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgYArQgMgHgFgKQgGgMAAgOQAAgNAGgMQAHgKAKgHQALgGAOAAQAXABAMANQAMAMAAAXIAAAFIg/AAQABAMAFAGQAHAGAKAAQAJABAGgFQAGgEACgHIAQAJQgDAIgGAFQgFAGgJADQgIADgNAAQgPAAgMgGgAARgHQAAgOgDgEQgFgGgIAAQgGAAgFAGQgEAFgBANIAgAAIAAAAg");
	this.shape_12.setTransform(-59.8,64.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAGBAIAAgQIAGAAIADgBIAAgGIAAgjQABgJgEgDQgDgFgHABQgGAAgFAGQgEAFAAAOIAAAaIAAAGIAEABIAFAAIAAAQIgzAAIAAgQIAHAAIADgBQABgCAAgEIAAhPQAAgEgBgBQgBAAAAgBQAAAAAAAAQgBAAAAAAQgBgBAAAAIgHAAIAAgQIATAAIANgBIAKgBIAAAyQAFgJAHgFQAHgDALAAQAOgBAIAKQAHAIAAARIAAAlQAAAEABACIADABIAGAAIAAAQg");
	this.shape_13.setTransform(-70.7,62.45);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgPIAGgBQAGgBADgDQAEgCABgHIACgPIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADADAGgBIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_14.setTransform(-79.875,63);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgPIAGgBQAGgBADgDQAEgCABgHIACgPIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADADAGgBIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_15.setTransform(-90.875,63);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgYArQgMgHgFgKQgGgMAAgOQAAgNAGgMQAGgKALgHQAMgGANAAQAYABALANQAMAMAAAXIAAAFIg/AAQAAAMAHAGQAFAGALAAQAJABAFgFQAHgEACgHIAQAJQgDAIgGAFQgFAGgJADQgJADgMAAQgPAAgMgGgAASgHQAAgOgFgEQgDgGgJAAQgGAAgFAGQgEAFgBANIAhAAIAAAAg");
	this.shape_16.setTransform(-99.05,64.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgjBHQgMgCgFgFQgEgDgBgHQABgGAFgFQAHgEALgCQgJgCgGgGQgEgFAAgHQAAgHAEgFQAFgFAIgCQgHgEgDgGQgEgGAAgJQABgKAFgIQAGgGALgEQAKgFANAAQAIAAAHACQAHABAGADQABgIAFgFQAFgEAIgBQAFABAFADQADAEAAAFQAAAGgCADQgDADgGABQgEgBgCgBQgDgCgBgDIgCACIgCADQAEAEACAFQADAGAAAGQAAAKgFAHQgHAHgKADQgKAEgNAAIgLAAIgKgDIgEACQAAAAgBABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAABAAAAQABABAAAAQAAABABAAQADACAGAAIANAAIAPgBIAMAAQAQAAAIAHQAHAIAAAMQAAARgPAIQgOAJgcAAQgSAAgMgCgAgeAtQgCADgBAEQAAAFAIACQAGACAQAAQAQAAAIgDQAIgEAAgFQAAgFgDgCQgDgCgKAAIgjAAQgFACgDADgAgPgpQgDAEAAAJIAAADQAAAIADAEQAEAEAHAAQAHAAADgEQAEgEAAgJIAAgDQAAgIgDgFQgEgEgHAAQgHABgEAEg");
	this.shape_17.setTransform(-109.5,65.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgaArQgLgGgGgLQgHgLAAgPQAAgNAHgMQAGgKAMgHQALgGAOAAQAQAAALAGQALAHAGAKQAGAMABANQgBAPgGALQgGALgMAGQgLAGgPAAQgPAAgLgGgAgOgYQgEAHAAARIAAABQAAAQAEAIQAFAGAJAAQAKAAAFgGQAEgIAAgQIAAgBQAAgRgEgHQgFgGgKAAIAAAAQgJAAgFAGg");
	this.shape_18.setTransform(-125.125,64.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgPIAGgBQAGgBADgDQAEgCABgHIACgPIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADADAGgBIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_19.setTransform(-133.925,63);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgYArQgMgGgFgLQgGgLAAgPQAAgOAGgLQAGgLALgGQAMgGANAAQAYAAAMANQALANAAAXIAAAFIg/AAQAAAMAHAGQAFAHALgBQAJABAFgFQAHgEACgHIAQAJQgDAHgGAGQgFAFgJAEQgJADgMAAQgQAAgLgGgAASgIQAAgNgFgFQgDgFgJAAQgHAAgEAFQgEAGgBAMIAhAAIAAAAg");
	this.shape_20.setTransform(-76.2,40.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAjAwIAAgRIAFAAIACgBQABgBAAgEIAAghQAAgKgDgEQgDgEgHAAQgHAAgEAGQgDAFAAAMIAAAcQAAAEABABIACABIAGAAIAAARIgwAAIAAgRIAFAAIACgBQABgBAAgEIAAgiQAAgJgDgEQgDgEgHAAQgHAAgEAGQgDAFAAAMIAAAcQAAAEABABIACABIAGAAIAAARIgzAAIAAgRIAHAAIADgBIAAgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgHAAIAAgRIATAAIANgBIAJgBIAAARQAFgIAHgFQAHgFAKAAQAMAAAFAFQAHAFADALQAEgKAHgGQAIgFAMAAQAPAAAIAJQAIAJAAATIAAAjIAAAFIADABIAHAAIAAARg");
	this.shape_21.setTransform(-89.875,39.975);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgZBCIAAgQIAHAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAgtIgBgGQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgGAAIAAgRIATAAIAMgBIAKgBIAABHQAAABAAABQAAAAAAABQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAHAAIAAAQgAgMglQgFgFAAgHQAAgHAFgEQAFgFAHgBQAIABAFAFQAEAEABAHQgBAHgEAFQgFAEgIABQgHgBgFgEg");
	this.shape_22.setTransform(-101.475,38.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADACAGAAIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_23.setTransform(-107.775,38.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgWAuQgKgBgHgDIAAgZIAWAAIAAAPIAGABIAJABQAGAAAEgCQAEgEAAgEQAAgHgFgCIgOgEQgIgBgHgDQgIgDgFgEQgEgHgBgKQABgOAKgIQALgJATAAQAMABAJACIAPAEIAAAYIgVAAIAAgNIgGgCIgHgBQgGAAgEADQgEADAAAEQAAAFADABQACACAFABIAJADIAQAEQAHADAFAFQAFAGAAAKQAAAPgLAJQgLAIgUAAQgMAAgJgDg");
	this.shape_24.setTransform(-119.725,40.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADACAGAAIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_25.setTransform(-127.525,38.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgbA/IAAgQIAIAAQAAAAAAgBQABAAAAAAQABAAAAAAQAAgBABAAQAAgBAAgEIAAhQIAAgEIgDgBIgIAAIAAgRIA3AAIAAARIgIAAIgCABIgBAEIAABQQAAAEABABQAAAAAAABQAAAAABAAQAAAAABAAQAAABAAAAIAIAAIAAAQg");
	this.shape_26.setTransform(-133.8,38.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2type, new cjs.Rectangle(-139,0,150,100.4), null);


(lib.HEAD1btype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANQgFgFAAgIQAAgHAFgFQAFgEAHAAQAIAAAFAEQAFAFAAAHQAAAIgFAFQgFAFgIAAQgHAAgFgFg");
	this.shape.setTransform(-64.475,91.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgLA2QgHgIAAgQIAAgvIgMAAIAAgOIAGgBQAGgBADgDQAEgDABgGIACgPIAUAAIAAAbIARAAIAAAQIgRAAIAAAvQAAAHACADQADACAGAAIAEAAIAEgBIAAASIgIABIgKABQgQAAgIgHg");
	this.shape_1.setTransform(-70.175,87.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrAwIAAgRIAGAAIADgBQABgBAAgEIAAguIgBgFQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgHAAIAAgRIATAAIANgBIAKgBIAAAUQACgLAGgFQAHgFAJAAQAKAAAHAHQAFAHABAMQgBAKgEAGQgGAFgJAAQgGAAgEgDQgEgEAAgGQAAgEACgDQACgEAEgCIgDgBIgDAAQgIAAgEAHQgDAHAAANIAAAZQAAAEABABIACABIAHAAIAAARg");
	this.shape_2.setTransform(-77.85,88.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaArQgLgGgGgLQgHgLAAgPQAAgNAHgLQAGgMAMgFQALgHAOAAQAQAAALAHQALAFAGAMQAGALABANQgBAPgGALQgGALgMAGQgLAGgPAAQgPAAgLgGgAgOgXQgEAGAAAQIAAADQAAAQAEAGQAFAIAJgBQAKABAFgIQAEgGAAgQIAAgDQAAgQgEgGQgFgIgKABIAAAAQgJAAgFAHg");
	this.shape_3.setTransform(-87.975,88.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag3BAIAAgQIAHAAIACgCQABAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAhQQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQAAAAAAAAQgBAAAAAAQgBgBAAAAIgHAAIAAgQIASAAIAOgBIAKgCIAAAUQAEgKAHgEQAHgGALAAQANAAAJAHQAJAFAFALQAEALAAAPQAAAOgFALQgFALgJAGQgJAGgNAAQgLAAgGgEQgIgGgDgIIAAAaIABAEIACACIAIAAIAAAQgAgIglQgFAHAAAOIAAAEQAAANAFAHQAFAGAIABQAIgBAFgGQAGgHAAgNIAAgEQAAgOgGgHQgFgGgIAAQgIAAgFAGg");
	this.shape_4.setTransform(-99.3,89.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag3BAIAAgQIAHAAIACgCQABAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAhQQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQAAAAAAAAQgBAAAAAAQgBgBAAAAIgHAAIAAgQIASAAIAOgBIAKgCIAAAUQAEgKAHgEQAHgGALAAQANAAAJAHQAJAFAFALQAEALAAAPQAAAOgFALQgFALgJAGQgJAGgNAAQgLAAgGgEQgIgGgDgIIAAAaIABAEIACACIAIAAIAAAQgAgIglQgFAHAAAOIAAAEQAAANAFAHQAFAGAIABQAIgBAFgGQAGgHAAgNIAAgEQAAgOgGgHQgFgGgIAAQgIAAgFAGg");
	this.shape_5.setTransform(-111,89.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgmAnQgHgJAAgSIAAglQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBAAAAIgDgBIgHAAIAAgRIAqAAIAAA7QAAAIAEAEQADAEAGAAQAHAAAEgGQAEgGAAgMIAAgdQAAAAAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAIgCgBIgIAAIAAgRIArAAIAABFIAAAFQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAAAIAIAAIAAARIgUAAIgNAAIgKACIAAgQQgEAIgIAEQgGAEgLAAIgBABQgOAAgIgJg");
	this.shape_6.setTransform(-122.525,88.4513);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgWAvQgKgDgHgDIAAgXIAWAAIAAAOIAGABIAJABQAGAAAEgDQAEgCAAgGQAAgFgFgDIgOgEQgIgBgHgDQgIgDgFgFQgEgGgBgJQABgPAKgJQALgHATgBQAMABAJABIAPAGIAAAYIgVAAIAAgPIgGgBIgHAAQgGgBgEADQgEADAAAEQAAAFADACQACACAFAAIAJADIAQAEQAHADAFAFQAFAGAAAKQAAAPgLAIQgLAJgUAAQgMAAgJgCg");
	this.shape_7.setTransform(-132.625,88.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgvA6QgHgFAAgLQAAgIAEgFQAFgEAIAAQAGAAAEADQAEADABAFQABAFgDAGQAFgBAEgFQAEgEADgJIAAgBIghhEIgCgFIgDgBIgGAAIAAgQIA0AAIAAAQIgFAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAABAAAAIAAAEIAQAmIAPglQABgDgBgCQAAgBgBAAQAAAAAAAAQgBgBgBAAQAAAAgBAAIgGAAIAAgQIAqAAIAAAQIgGAAIgEABIgDAFIgcBDQgFANgFAIQgFAJgHAEQgHAEgLAAQgNAAgIgGg");
	this.shape_8.setTransform(-57.675,66.025);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgrAwIAAgRIAGAAIADgBQAAgBAAgEIAAguIAAgFQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAgRIATAAIANgBIAKgBIAAAUQACgLAHgFQAGgFAIAAQAMAAAFAHQAHAHAAAMQAAAKgGAGQgFAFgJAAQgGAAgEgDQgEgEgBgGQABgEACgDQACgEAEgCIgCgBIgEAAQgHAAgFAHQgDAHAAANIAAAZQAAAEABABIACABIAHAAIAAARg");
	this.shape_9.setTransform(-67.65,64.075);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgYArQgLgHgGgKQgGgMAAgOQAAgNAGgMQAHgKALgHQAKgGAPAAQAXABALANQAMAMAAAXIAAAFIg/AAQABAMAFAGQAHAGAKAAQAJABAGgFQAFgEADgHIAQAJQgDAIgFAFQgGAGgJADQgIADgMAAQgQAAgMgGgAARgHQAAgOgDgEQgEgGgIAAQgIAAgEAGQgFAFAAANIAgAAIAAAAg");
	this.shape_10.setTransform(-77.5,64.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgKAvIgghHQgBgDgCgBIgCgBIgHAAIAAgRIA2AAIAAARIgHAAQAAAAgBAAQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABABABQAAAAAAABIAEALIAGANIAGAQIAHgRIAGgOIADgJQAAAAABgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAIgHAAIAAgRIArAAIAAARIgFAAIgFABQgBABgBADIggBHg");
	this.shape_11.setTransform(-88.05,64.275);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgaArQgLgGgGgLQgHgLAAgPQAAgNAHgMQAGgKAMgHQALgGAOAAQAQAAALAGQALAHAGAKQAGAMABANQgBAPgGALQgGALgMAGQgLAGgPAAQgPAAgLgGgAgOgYQgEAHAAARIAAABQAAAQAEAIQAFAGAJAAQAKAAAFgGQAEgIAAgQIAAgBQAAgRgEgHQgFgGgKAAIAAAAQgJAAgFAGg");
	this.shape_12.setTransform(-98.975,64.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AghAkQgOgMAAgYQAAgWAOgNQANgNAYAAQAVAAALAIQALAJABAPQgBAJgFAHQgFAEgJAAQgHAAgFgEQgEgDAAgGQAAgHADgDQAEgEAFgCQgCgDgEgCQgEgBgGAAQgLAAgFAHQgHAHABAPIAAADQAAAOAFAIQAFAHALAAQAJAAAFgEQAGgEADgIIARAJQgFAMgKAGQgKAIgSAAQgYAAgNgNg");
	this.shape_13.setTransform(-109.25,64.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgYArQgMgHgFgKQgGgMAAgOQAAgNAGgMQAGgKALgHQAMgGANAAQAYABAMANQALAMAAAXIAAAFIg/AAQAAAMAHAGQAFAGALAAQAJABAFgFQAHgEACgHIAQAJQgDAIgGAFQgFAGgJADQgJADgMAAQgQAAgLgGgAASgHQAAgOgFgEQgDgGgJAAQgHAAgEAGQgEAFgBANIAhAAIAAAAg");
	this.shape_14.setTransform(-119.4,64.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAkA/QgIAAgFgEQgFgEgCgIQgDgHgBgJQAAgHgBgFQgCgFgEgCQgDgDgGAAIgLAAIAAAfIABAFQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAIAAIAAAQIg5AAIAAgQIAJAAQAAAAABgBQAAAAAAAAQABAAAAAAQAAgBABAAIABgFIAAhPIgBgFQgBAAAAgBQAAAAgBAAQAAAAAAAAQgBAAAAAAIgJAAIAAgRIBDAAQAWAAAMAIQALAJAAASQAAAMgHAIQgHAHgNACQAMAEAGAIQAFAJABANQAAAGACACQACADAEAAIAEAAIAAAQgAgPgEIALAAQALAAAFgFQAGgFAAgLQAAgLgFgEQgFgFgKAAIgNAAg");
	this.shape_15.setTransform(-130.675,62.5486);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1btype, new cjs.Rectangle(-139,0,150,100.4), null);


(lib.HEAD1atype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANQgFgFAAgIQAAgHAFgEQAFgGAHAAQAIAAAFAGQAFAEAAAHQAAAIgFAFQgFAEgIABQgHgBgFgEg");
	this.shape.setTransform(-45.875,43.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADACAGAAIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_1.setTransform(-51.575,38.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAGAwIAAgRIAFAAIADgBQABgBAAgEIAAgjQAAgJgDgEQgDgEgHAAQgHAAgEAGQgFAGAAAOIAAAaQAAAEABABIADABIAFAAIAAARIgyAAIAAgRIAHAAIACgBIABgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAIgHAAIAAgRIASAAIANgBIAKgBIAAARQAEgJAIgEQAHgFALAAQAPAAAHAJQAIAJAAASIAAAkQAAAEABABIADABIAGAAIAAARg");
	this.shape_2.setTransform(-60.375,39.975);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgYArQgLgGgGgLQgGgLAAgPQAAgOAGgLQAGgLALgGQAMgGAOAAQAXAAAMANQALANAAAXIAAAFIg/AAQAAAMAHAGQAFAHALgBQAJABAFgFQAGgEADgHIAQAJQgDAHgGAGQgFAFgJAEQgJADgMAAQgPAAgMgGgAASgIQAAgNgFgFQgEgFgHAAQgIAAgEAFQgFAGAAAMIAhAAIAAAAg");
	this.shape_3.setTransform(-71.35,40.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAjAwIAAgRIAFAAIACgBQABgBAAgEIAAghQAAgKgDgEQgDgEgHAAQgHAAgEAGQgDAFAAAMIAAAcQAAAEABABIACABIAGAAIAAARIgwAAIAAgRIAFAAIACgBQABgBAAgEIAAgiQAAgJgDgEQgDgEgHAAQgHAAgEAGQgDAFAAAMIAAAcQAAAEABABIACABIAGAAIAAARIgzAAIAAgRIAHAAIADgBIAAgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgHAAIAAgRIATAAIANgBIAJgBIAAARQAFgIAHgFQAHgFAKAAQAMAAAFAFQAHAFADALQAEgKAHgGQAIgFAMAAQAPAAAIAJQAIAJAAATIAAAjIAAAFIADABIAHAAIAAARg");
	this.shape_4.setTransform(-85.025,39.975);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADACAGAAIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_5.setTransform(-97.175,38.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgrAqQgHgGAAgLQAAgNAJgGQAIgGANgFQAOgDAPgCIAAgGQABgIgEgDQgEgEgJgBIgFABIgEABIACAEIAAAFQAAAGgFAEQgEAEgHAAQgIAAgFgEQgEgEAAgIQAAgIAGgGQAGgFAJgDQALgDANAAQAWAAALAHQAKAIAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAAAAAIAHAAIAAAQIgiAAIgEgHIgDgHQgCAEgFAFQgEAEgHACQgGACgHAAQgOAAgIgHgAgLAHQgJAEAAAIQAAAGADACQADADAFAAQAJAAAFgFQAEgHAAgJIAAgIQgMACgIAEg");
	this.shape_6.setTransform(-105.5,40.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgYArQgMgGgFgLQgGgLAAgPQAAgOAGgLQAHgLAKgGQALgGAOAAQAXAAAMANQAMANAAAXIAAAFIg/AAQABAMAFAGQAHAHAKgBQAJABAGgFQAGgEACgHIAQAJQgDAHgGAGQgFAFgJAEQgIADgNAAQgPAAgMgGgAARgIQAAgNgDgFQgFgFgIAAQgGAAgFAFQgEAGgBAMIAgAAIAAAAg");
	this.shape_7.setTransform(-116.05,40.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgsAwIAAgRIAHAAIACgBQABgBAAgEIAAguIAAgFQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgHAAIAAgRIATAAIAOgBIAJgBIAAAUQACgLAGgFQAGgFAKAAQAKAAAHAHQAGAHAAAMQAAAKgFAGQgGAFgJAAQgGAAgEgDQgEgEgBgGQAAgEADgDQACgEAEgCIgDgBIgCAAQgJAAgEAHQgDAHAAANIAAAZQAAAEABABIABABIAIAAIAAARg");
	this.shape_8.setTransform(-125.75,39.975);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADACAGAAIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_9.setTransform(-133.925,38.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgYArQgLgHgGgLQgGgLAAgOQAAgNAGgMQAHgKALgGQALgHAOAAQAWAAANANQALAOAAAWIAAAFIg/AAQAAAMAGAGQAHAHAKAAQAJAAAFgFQAGgEADgHIAQAJQgDAHgFAGQgGAFgJAEQgIADgMAAQgQAAgMgGgAARgIQAAgMgEgGQgEgFgHAAQgIAAgEAFQgFAGAAAMIAgAAIAAAAg");
	this.shape_10.setTransform(-15.3,16);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgWAuQgKgCgHgCIAAgZIAWAAIAAAPIAGABIAJABQAGAAAEgCQAEgDAAgFQAAgGgFgDIgOgEQgIgBgHgDQgIgDgFgFQgEgFgBgLQABgOAKgIQALgJATAAQAMAAAJACIAPAGIAAAXIgVAAIAAgNIgGgCIgHAAQgGAAgEACQgEADAAAFQAAADADACQACACAFACIAJACIAQAEQAHADAFAFQAFAFAAALQAAAPgLAJQgLAIgUAAQgMAAgJgDg");
	this.shape_11.setTransform(-24.775,16);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgmAnQgHgJAAgSIAAglQAAAAAAgBQAAgBAAAAQgBgBAAAAQAAgBAAAAIgDgBIgHAAIAAgRIAqAAIAAA7QAAAIAEAEQADAEAGAAQAHAAAEgGQAEgGAAgMIAAgdQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBgBAAIgCgBIgIAAIAAgRIArAAIAABFIAAAFQAAAAABABQAAAAABAAQAAAAAAAAQABAAAAAAIAIAAIAAARIgUAAIgNAAIgKACIAAgQQgEAIgIAEQgGAEgLAAIgBABQgOAAgIgJg");
	this.shape_12.setTransform(-34.925,16.1513);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgYArQgMgHgFgLQgGgLAAgOQAAgNAGgMQAHgKAKgGQALgHAOAAQAXAAAMANQAMAOAAAWIAAAFIg/AAQABAMAFAGQAHAHAKAAQAJAAAGgFQAFgEADgHIAQAJQgDAHgGAGQgFAFgJAEQgJADgLAAQgRAAgLgGgAARgIQAAgMgDgGQgFgFgIAAQgGAAgFAFQgEAGgBAMIAgAAIAAAAg");
	this.shape_13.setTransform(-50.25,16);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AghAkQgNgMAAgYQAAgWANgNQANgNAYAAQAVAAALAJQALAIAAAPQABAKgGAFQgFAFgJABQgHgBgFgEQgEgDgBgHQAAgFAEgFQADgDAHgCQgDgDgEgBQgEgCgGAAQgKAAgHAHQgFAIgBAOIAAACQAAAPAGAIQAFAHALAAQAJAAAFgEQAGgEADgIIAQAJQgEALgJAIQgLAHgSAAQgYAAgNgNg");
	this.shape_14.setTransform(-60.25,16);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAGAwIAAgRIAFAAIADgBQABgBAAgEIAAgjQAAgJgDgEQgDgEgHAAQgHAAgEAGQgFAGAAAOIAAAaQAAAEABABIADABIAFAAIAAARIgyAAIAAgRIAHAAIACgBIABgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAIgHAAIAAgRIASAAIANgBIAKgBIAAARQAEgJAIgEQAHgFALAAQAPAAAHAJQAIAJAAASIAAAkQAAAEABABIADABIAGAAIAAARg");
	this.shape_15.setTransform(-71.025,15.875);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgqAqQgIgGAAgMQAAgMAIgGQAJgHANgDQAOgEAQgDIAAgFQAAgIgFgEQgDgDgIAAIgGAAIgEABIABAEIABAFQAAAGgEAEQgFAEgHAAQgIAAgEgEQgFgEAAgIQAAgJAFgFQAGgGALgDQAKgCANAAQAWAAALAIQAKAHAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAIAGAAIAAAQIgiAAIgFgGIgCgIQgDAEgFAFQgDAEgGACQgHACgIAAQgNAAgHgHgAgMAHQgIAEAAAIQAAAGADACQADAEAGAAQAIgBAEgGQAGgFAAgLIAAgHQgNACgJAEg");
	this.shape_16.setTransform(-82.15,16);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADADAGAAIAEgBIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_17.setTransform(-91.025,14.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgWAuQgKgCgHgCIAAgZIAWAAIAAAPIAGABIAJABQAGAAAEgCQAEgDAAgFQAAgGgFgDIgOgEQgIgBgHgDQgIgDgFgFQgEgFgBgLQABgOAKgIQALgJATAAQAMAAAJACIAPAGIAAAXIgVAAIAAgNIgGgCIgHAAQgGAAgEACQgEADAAAFQAAADADACQACACAFACIAJACIAQAEQAHADAFAFQAFAFAAALQAAAPgLAJQgLAIgUAAQgMAAgJgDg");
	this.shape_18.setTransform(-98.475,16);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgGA7QgJgGgEgLIgFAVIgWAAIABgFIAAgKIAAgRIAAhGIgBgFQAAgBAAAAQAAAAgBAAQAAgBAAAAQgBAAAAAAIgHAAIAAgQIASAAIAOgBIAKgBIAAAzQADgJAJgFQAGgFALAAQANAAAIAHQAKAGAFAKQAEAKAAAPQAAAPgFALQgFALgJAGQgKAGgMAAQgNAAgIgGgAgIgGQgGAGABAPIAAADQgBAOAGAHQAFAHAIAAQAIAAAFgHQAGgHAAgOIAAgDQAAgPgGgGQgFgHgIABIgCAAQgGAAgFAGg");
	this.shape_19.setTransform(-108.75,14.375);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgmAnQgHgJAAgSIAAglQAAAAAAgBQAAgBAAAAQgBgBAAAAQAAgBAAAAIgDgBIgHAAIAAgRIAqAAIAAA7QAAAIAEAEQADAEAGAAQAHAAAEgGQAEgGAAgMIAAgdQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBgBAAIgCgBIgIAAIAAgRIArAAIAABFIAAAFQABAAAAABQAAAAABAAQAAAAAAAAQABAAAAAAIAIAAIAAARIgUAAIgNAAIgKACIAAgQQgEAIgIAEQgGAEgLAAIgBABQgOAAgIgJg");
	this.shape_20.setTransform(-120.225,16.1513);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgbA/QgMgDgJgEIAAgfIAZAAIAAATQAEACAGABIAMABQAIAAAFgEQAFgEABgHQAAgGgEgDQgDgEgGgCIgPgEQgMgDgJgEQgIgFgFgGQgFgHAAgMQAAgTAOgLQANgLAYgBQANAAALADQAKACAJAEIAAAfIgZAAIAAgTIgIgBIgJgBQgKAAgFAEQgGAEAAAHQAAAGADADQADADAGACIAPAEQALACAJAFQAJAEAGAGQAFAHABANQAAAMgGAKQgGAJgMAGQgLAFgRAAQgNAAgMgDg");
	this.shape_21.setTransform(-131.425,14.325);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1atype, new cjs.Rectangle(-139,0,151,76.3), null);


(lib.CO_v_white = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgyA1QgXgVAAggQAAgeAWgVQAVgWAeAAQAfAAAWAXQAVAVgBAdQAAAfgVAVQgVAVgfABQgdgBgVgUgAgvgvQgTAUAAAbQAAAcATAUQAUATAbAAQAcAAATgTQATgTABgdQAAgbgTgTQgUgUgcAAQgbAAgUATgAASAuQgCgDgCgKIgCgPQgCgIgFgEQgEgCgJAAIgGAAIAAAqIgRAAIAAhcIAfAAQAPAAAFACQAPAFAAARQAAAQgTAGQAGABADAEQADAEABAJQAEAVADAHgAgOgIIAOAAQATAAAAgNQAAgIgHgDQgDgBgMAAIgLAAg");
	this.shape.setTransform(133.8251,86.6356,0.4949,0.4949);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACmLBQgKgEgNACQgPADgIAAQAAgDgKgCIgOgBQgRABgHgCQAAgDgSACQgjgBAAgBIgUgCIgTgBQgLgCgHAAQAAgBgQABQgRABAAgDIgOgEQgJgDAAAHQgDAAgFgDQgEgDgDAAQAAAFgJgBIgNgDQgNgCgLACQgRACgYgKIgJgEQgEgCgEABQgCAAgIgEQgIgFAAgBIgMABIgMABQgIACgFgBQgDAAgDgEQgEgFgDAAIAAAEQgEAAgEgCQgGgDAAgEQgCAGgBAAQAAgDgIgDQgIgCgFAAIgBABQgBAAAAAAQAAgBAAABQgBAAAAAAQAAAAAAAAQgDABgFgEQgEgDgEABQgEABAAgDIgIgGQgHgFAAAEQgCABgMgFQgNgGAAgCIgTgJQgBABAAAAQgBABAAAAQAAABAAAAQAAAAABAAIgEABIAAAAIgEAAIAEAAQABADgQgGQgCgDgFAAQAAgGgDgCIAAAGIgFgDQgGgDAAADIgIgIIgOgCQAAgCgNgGQgNgGAAgCQgKgEgDgKQgBgDgJgBIgOgCQgTgKgBABQgEgCgCABIABgDQgCAAgQgKQgLgIgDgIIgLgDQgCgCgBgDQgBgBgFAAIgDgHIgCgHQgEgBgCACQgCACgCAAQgBgLgTAAQgPAAAAgBIgNgBIgMgBQgSAFgHgCQAAgBgYgBQgaAAgDgBQAAACgJgCIgNgDQgLAFgDgEQgNgEgCABQAAABgGAAIgHgBIgJgCQgDgCgFAAIgOABQAAABgOgEQgGAAgFgHQgCgBgNABIgMAAQgEABgcgDQgcgDAAgBIgJgDQgGgCgDAAIgXgDQgDgEgbgGQgagHAAgBQgCAAgEgCQgDgDgDABQgOACAAgEQgJgEgPAAQAAgFgKgBQgNgBgBgBQgLgFgFgDQgHgGgQgDIgYgEQgDgDgDABIgHACIgGgDIgHgCQAAgEgJgBQgJgBgCgFIAJgCQgBgEgMgEQgMgFAAACIgSgJQgFAAgIgGIgLgHIgMgEIgNgBIAVAVQAAADAHAGQAHAGABAEQADACAGAHQAGAGAEABQAKADAEAHQADAAAHADIAKAFIAHAEQAHAEAAACQAFAAAHADQAGADAEAAIAEACQABAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAFABAGAGQACAFAWAEQAVAEAAADIAYAKQADAAAGADQAFAEAEAAQACgBATAGIATAFQADAAAIAEQAGAEAEgBQAEgBAJAEQAKAEADAAQAAgBARAEIAVAFQAEAAAJACIANAEQAAABAOACIAQABQAAAFBNAGQADADAjADQAiAEAAABQBPAIAAgBQADgBAkAEQAiAEAAgBQAIgBAAABQgGAAgMAGQgOAGgFABIgMgCQgLgCAAADIgGABQgDABgDgBQAAAGgUABQgTABAAgDQgQACAAgCIgGACQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgLgBQgDgBgDgGQgDAAgCADQgBABgGAAIgNgBQgXgCgDgCIgFgFIgJABIgMgEQgKgDAAADQgGAAgKgCQgCgGgEABIgJAFQgFADgFgCQAAgCgLgCQgKgCgEABQAAACgWgEIgbgFQAAgCgOgBQgPgBgBgEQgHAAgLgDQgMgDgGgBQgCgCgNgBQgNgBAAgCQgGAAgJgCIgOgEIgNgEQgNgEAAgBIgNgCQgKgCAAgBQgFAAgGgCIgLgFIgDgBIgCgBQgLAAAQALQACACAGACQAGACADADIAKADQAAABAFABIAHABQAAACASADQAAADAaAEQAZAFABAHIgKACQAAgDgXgDQgZgDgCgDIgagHQgVgHAAgDIgZgIQgUgIAAgBQgIgCgKgEQgNgGgFgGIgIgFQgJgEAAABQgCAAgHgFQgIgFAAgCQgKAAgPgHQgRgJgCgJQgPgKgGAAIgIgIQgFgFgDgCIgGgIIgJgFQgGgCAAgDQgGgEgHgIQgHgJgDgGQgDgBgEgHQgFgHAAgCQgDAAgDgJQgDgKgEAAQAAgEgDgGQgEgFAAgFQgBAAgFgTIgGgYIgHgkQgHgjAFAAIgFgVQgBAAgBgLIgBgNQgDAAAAgNQgBgOgCAAIgJhUIAAggQAAgcACAAIgCgjQgBggAEAAIgCgxQgCgsAFgDQAAgEAKgaQALgZgBgEQAIAAAHgOQAHgPAGgCQACgBADgFQACgGADgCQAAgFAGgGQAHgGAHgBIgDgEQAAAAAAgBQAAAAAAgBQAAAAABgBQABAAABAAIAEgCQAAAAAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAHgHIAKgHIAFAAIAEgCQALgIgHAAQgCgGAFgEQAFgFAFAAIAIgDIAIgCQAKgFAKgJIAQgRQAGgGADgBIAFgDIACgEQACAAAOgLQAAgCANgFQANgGAAgEQAEAAAJgGQAJgHABgDIAOgJQAHgEAIAAQAAgBAGgDIAFgCIAJABQAGACABgDIAXgEQAOgEAAgJQADgBACgEIADgEQABgCAEgDQAEgCABgDIgBAAQAAgFAHACIAJACIARgCIAIgFIAKgEIAJgFQAHgEACAAIAEgCQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBQAFAAAFgCQAHgCAAgDQgHAAAHgHQAHgGAEgBIANgHQAFAAAGgDQAAgDAHgCQAGgCAAgEQAGAAAAADQADAAAEgCIAHgCIAKACQAGABACgDIAOgGQAJgGAEAAQAAgBALgEQAKgDAEAAQAAgCAHAAQAHAAAAgBQAJAAACgCQACgBAAgHIAFgDIAEgEIAJACIgBAFIAEgCIADgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAfAAAHgDQAEgBAGACIAKACQALgGgFAAQgCgJASgGQATgGAAAFQAMgIAZAAQACgDAJAAQAJABACgEIAXgEQAUgEAAgBIABABIAVgFQAWgFADAAQAVAAAAgEIAIgCQAHgBAAgBIAggHIAvgHQAOAAAggFQAggGAQAAQAAgFBQAAQAAABAGACQAHACAAACQgIAFgXgCIgQABIgRABQgJAAgRADQgSADgJAAQAAgChXATQAAAFArgFIAxgGIAugGIAbgDQARgCAJACQAUgDABAKQASAAAAABIAHABQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAABIgIAAQAAADg1ACQAAABgRADIgUACIgTAAQgSAAAAADIgwAHIgSACIgUACQAAADgMACIgQACQgIgBgPAEQgQAFgHAAIgMACQgMACAAACQgEAAgGAEQgHAEgDAAIgJAAIgJgBQAAADgQACQgPADgBADQgCAKgMADQgOABgIACQAAADgTAHQgHAKgHAEQACAIAiABQAfABAHgEQADgCAagEQAXgDAAgCIAMgCIAMgDQAAgBAGABIAHABQARgEAJAAQAAgBAcgDIAcgFQAfgDAAgBIAVgCIAWgCQAAgCAmgCQAngDAFABIApgDQAkgDAAACQAMgCAYACIAcgBQASgBALACQAAADAJACQAJACAAgCIAQABQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQADgBAKACQALADAAACQgEACgWABIgVAAIgmABQgCADgWAFQgVAFAAACIgQgBQgPgBAAACIgWAAQAAAFgZABIgegBQAAADglABQglACgBAIQARADAXgDIAngGQAAACAkgCQAjgBAAABQAFAAALgDQAEAAAEACQAFADAEAAIAQgBQAJABgEAGQgFAIghACIghACQhWAFAAADIgTACQgTACAAgCQgGgBgJADQgLADgDAAIgRACQgCACgGAAIgKgBQgGABgJAGQgIAGgGABQAAAFgdAEQAAABgHACQgIADAAABIgTADIgKACQgLACgBACQgRAAgMAMQgGABgKAFQgKAGgGABQAAgBgNAFIgPAFQAAgCgFABQgEAAgCACIAEABQgBADgMACIAAgEIgOAFQAKAIgUAEQgWAEAAACIgTAGQgNAFgGABQAAgCgvAQIgRAGQgRAGgCADQgTAAgDAEQgFAAgHAFQgGAEgFgBQgGAAgFAFQgGAGgFAAQgCgDgFACIgIAEIgKAFQgFACgFABQgBABgLADIgNACQAAAFgJACIgOADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABgBAAQgCADgEAAQgEAAgCADQgDAEgDACIgDADQgBABgEAAQgBgCgGgBQgFgCAAAEQgFAAgBAFQgDAHgCABQAAADgJAAQgOAJgCAAQAAACgMACQgLADAAAEIgMAGQgIAFAAADQgFABgFAEQgGAEgEABIgGADQgEACgCAAQgRAJgCAAQgEAEgFAAIgQAMQAAADgIAFQgIAEAAADQgGAEgOACQgBAEgEACQgFACgBABQgFAAgEAIQgEAHgDABQgEABgIAHQgIAFgDAAQAAAFgHAEQgIADgBAFQgSALgLANQgEAAgGAGIgIAKQgGAIgFADQgBADgFACQgFACAAAEQgCAAgHAJQgGAIgDAAIABADQgFAAgFAHIgHAKIgIAIIgHAJQgDAHgLANQgJALgBAJQADAAAGgHQAIgJACgBQAGgKAEAAQAAgDAHgFQAGgFABgCQgCAAAKgJIALgJQAGAAAEgJQAEgJADAAIAGgGQAGgFACAAQACgEAHgEIALgHQAAgCAEgFIAHgFIAVgPQADgHAUgGQABgDAJgEQAIgEAAgCQgBgEAGgCIAIgDIAWgOQAEAAAFgFQAGgEADAAIAhgUQAGgCARgIQATgJAAgDQAHgBACgDQAEAAABgDQACgDACAAQAHgCABgCIAIgEQAFgDAAgBIAGgDIAFgDQAAADAMgFQALgFACgDIAHgCQAFgCAAgBQAHgBAOgJQANgIAIAAQADgEAJgCQAIgCADgDQAEAAAGgEQAFgEAEAAQAFgFAIAAIAIgIIAHAAIAGgBIASgHQAAgBAGgCIAHgBQADgEAKgBIALgCQABgCAHgDQAIgEAAgCIAQgDQAAgCALgDQAJgCAEAAQAAgGANgBQANgBACgCIApgMQAhgJAAgFQAEAAASgFQARgGAAgBQAFAAAJgCQAKgCAAgEQAygGAAgEQALAAAQgFQATgHAHgBQAAgBAYgFIAbgFQAAgBAdgGIAhgHQAIgCANgBQAAgBAFgBIAHgBIATgEQAMgDAHABQAAAIgWAFIgeAFQgQAEAAACQgDAAgHAFQgHAFgFgBQAAAAgBgBQAAAAAAAAQAAAAgBAAQgBAAAAAAQAAACgZAIIgHAFQgEADgEAAQgDAEgGABIgMABIgbAJQgQAFgMACIgEADQgEADAAACQgEAAAFAEQAFADAAgEIAMgBQAKgBAAgCQAfAAgQAFIgHAEIgGAGQgCABgHgCQgEgBgCAGQgJgBgIAEQgKAEgIAAQgFAAgHAEQgGAEgEAAQAAAEAGAAIAGgCIAHgCQAAANgmACQgBADgGABQgDACgEgBQgEAAgDABQgBACgPAFQgFAGgSAAQgLABgBAGQgEgBgFACQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgEgCgBABQAAABgFAEIgIAEQgOAFAAACQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIABACIgGACQgEACgCgBQgBAGgKABIgOgBQAHAFgHADQgFACgGAAQAAgBgIAEIgIAEQgDAGgPAAQAAgDgGACIgEADQgBgDgEAFIgEAIIgGgCQgBAAgBAAQgBAAgBAAQAAAAgBABQAAAAAAABQgFACgIAAQgEAAgMACQgNADAAADQgDAAgEAEQgFAEgDAAIgbAKQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgDADQgEAAgDACQgDACgCAAQAAADgEABQgEACgDAAQgFgBgDAEQgEAFgDAAIgHAEIgFADQAAAGgKACIgOABQAAABgFADIgHADQgDABgHAIQgFAHgGgBQgHgCgJAJQgRAEgBADIgFACQgCABAAAEIgJgBQABABAAAAQABAAgBABQAAAAAAAAQgBABgBAAIgEAAQgBAAgBAAQAAAAAAABQgBAAAAABQAAABABABQAAAGgKAAQgCgCgGADIgJAEQgRAHgIAKQgJABgIAEIgPAJQAAAEgMAGQgMAHgCAFIgJAEQgGACAAAEIgMAFIgGACQgDABgCADIgCADIgEACQgJAHAAACQgDAAgCADQgDAEgCAAQgHABgFAEIgNAPQgHAIgJADQAAAGgOAJQgOAKAAAHQgEACAOALQAPANgBADQgFAAgGAKQgFAKgBAGQgDAAAPANQAPAMAAgEQAGAAAIAHQAIAHABAGQAAAEAKACQAKACACACIAMAJQAGAAALAGQALAFAGAAQAAAHArAAQAMAMAIAAQAAABAIAAQAJABABABIALAAQAGABAFADIAOAJQANAGAFgCIAKgCIALgCQAEADACAAQgCAEADACQACABANgBQAMAAACAEIATABIAIABIAJABQAAgCAPADIASADQADgEAGAAIALAAQABACAHAAQAHAAADADIAEAKQAEAIADgBIACAAIABgCIABgNQABgFAFAAIAKAAIAPACIARAAQAAgCAKADIAMAEQAAgFAKgCQAKgBAAAGIAugFIgBgCQADgCgDgPQgEgPABAAIgEgNQgFgMABAAQABgCgBgFQgBgFgCAAIgBgUQgBgFACgMQABgOACAAIAAgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBABAAQAFAAAAgZQACAAACgIIADgJQAAgFADgGQADgHABgFIAIgfIAIgQQAFgKAAgGQAEgCACgGQADgIADgCQAHgGgBgHQAMgMgBAAIAEgGQADgCACgEQgCgFAEgBQAAgCAFgGQAGgFAAgDQACgBAFgGQAFgHACAAQAAgDAFgDIAIgGQACAAAEgEQADgEAAgCQANgGAPgPIAFgCQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIgRANQgFACgFAIQgFAHgBAFQAGgBADgDIAGgIQAPgGAAgBQAIgCANgKQALgJAKAAIAIgBQADAAADgDQABgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQAAgDAEgBQAAgDAJgHQAIgHAFgCQADgBAFgEIAIABQACgCAFAAQABAAABAAQABgBAAAAQABAAAAgBQAAAAAAgBIAIgGQAHgGAAADQAGACAAgLQAGgBAFgEQACgCAJgCQAAgDACgDQADgDACAAQAAgCAMgGIANgHIACgFQABgCAEgBIAGgCIAGgFIAFgBIAFgCQAEgEAHgDQAIgDADgDQAFgEADACIAEADQADAHgOAHIgSAIQAAACgSAJIgMAJQgIAFgCAFQgEABgIAGQgIAGgGABQAAAIgLACIgMAJQgGAFgCAFQgIACgHAIQgCAAgDADQgDACgEAAQgGABgCAHQgIAEgCAJQgEACgEAFIgIAIIgPAMQgKAHAAAHQgNAGACANIgDAEIgCAGQgFACgBAJQgCAAgEAFIgFAFQgJAKAAgEQgDABgBAHQAAAGgIAAQAAABgEAEIgFAEIgBALIgGAJQgEAGgBAEIgMAKIgEAMIgGAEQgBACABAFQgBAAgEAHIgDAJQgDABgFAIIgHAHQAAATgIADQgGACABAJIAAANQgEAAgBAZQgBAZABAAQABgJAIgNQAKgOABgHQADAAAFgIQAEgGAAgDIALgUQACgBAFgIQAEgHAEAAQAEgPALgCQgCgKAMgGIANgPQABgEAJgIQAIgHAAgFQAFgCAGgIQAFgJAFgCQAAgDALgJQAJgIAFgDQAAgDALgHQAKgGAAgCQAGgEANgNIAPgNQAEAAADgFQADgFAEAAQACgEAHgGQAHgFAEgBQABgDAFgEQAHgEABgCQAIAAALgMQAMgMAGAAIAKgHQAIgFAAgCQADgBABgDQAAAAAAgBQABAAAAAAQABgBABAAQAAAAABAAQAIAAgCgGIAGAAQAAgCARgIQAQgJAEgBQAAgEATgKQARgJAGAAQADgGAJgFQAIgEAHgCQAAgBAJgEQAJgEACAAQACgCAUgJQATgIAAgBIAEgEQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAQABAAABAAIAGgBQAAgCAIgDIAIgCQADgDAIAEQACgJAFAAQAGgGAIAAQAAgCAHgCIAKgDQAFgHAZgGQABgCAGgBQAFgCACgCIAGgCIAHgCQAAgCAGgBQAGgBAAgBIAEADIAdgQQAAgBAMgDQALgCAAgCQAXgGAAgCIAJAAQAHAAADgEQADAAAPgJQABAAABAGQAAgIAVgEIAMgEQAJgDABAAQAQAKgEgHIgCgDQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAugJQACgEAXgEQAWgEAAgBIAIgDQAEgCADAAQAAgDARgBQATgCABgCQADAAADgDQADgDADAAQAAgCALAAQAngIADABQAAgCAvgIQAHABANgDIAVgGQAYgFAGAAQA9gJAGAAQAJgBAVgEQATgEAMAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAKAFQAIADAAgGIAUgCQA+gHAAACQADABAZgFIAigBQAfAAAAgCIBjgBQAAgCAoADQAsAEAEAAIAKAAQADAEAEgCIAIgCQACAHgDgBQgBAAgBAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgFAEgNAAQAAAAAAgBQAAAAgBAAQgBAAAAAAQgBAAgBAAIgFACQgEAAgDgCQgDgCgCAAQgNAHAAgEQgQACgIgCQAAgCgMABQgMACAAABQgLAAgKABQgCAFgGgCIgKgDQAAADgLAAQgKgHgCACIgDADIgFABQgDADgGABQgDAAAAAHQgMAAgCAIQgCAIAMAAQACADAKABQAKABADACQAAgFAHADIAKADQAAgEANACQAIABgDACIgFADQgCACgJAAQgIAAgEgCQAAABgHABQgGABgBAFQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgCADQgKAAgIACQgKADgHAAIgqADQgCAEgLAAIgRAAIgtACQAAABgfAEQggADgFgBQAAAGgzgBQAAABgIADIgJACQgYAAAAADQgFgBgOADIgiACQAAABgVAEIgYADQAAgDgKAHQgLAGAAACIAhAAIAbgEIATACQADAAAFgCQAEgCAFAAIAOgDQANgCAAACQAFABAHgFIAOABQAAAFALgHQAKgBARgDQAAgCAJAAQAGgBAFABQAGACAGgBQAGgCAFACQAAgDARgDQARgEAAAFQArAFAAgDIAJABQAGABAAADQgNAHgDgBQgFgBgKABQgLABAAADQAkgDBBACQANAAAaAEQAYADANAAQAlAAA5AKQArAFAAAFQAFAAAXAFQAZAFAAADIAIAAQAEAAABgEQAJgDAFAAQAFAAAFACQAAABAIACQAIACAAACQATAAAZAOQAPASgBAAQAAAGASAAIgLgKQgIgHAJAAQAGAAAJAFQAJAFAFAAQAqAWAEAAQAAABAPAEQAOADAAADQADAAAHAEQAIADADAAQAAABAoAOIAZAOQASALAAAHQAEAEAFACQAAACAJAIQAKAIAAADQAHAMACAAQAAADAEAGQAEAGAAAEQABAAACAHIACAJQAEAAAFATQAFATADAAIAJAUQAFAMAAAKQACAAAFAbQACAAAGAXIANAyIAHAaQAHAXgDAAQACAGADApQABADgCAFIgCAIQgCAAAAAGIAAAJQgCAAgDAIIgDAJQgDABgFAPIgFAPQgBADgDAAIgDAAIgBAGQgBAAAAAAQgBABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgIAAIAAAEQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgEACgBAGQgCAAgDAGQgDADgCgFQgHABgFAFQgEAAgCAIQgCAIgCABQAAAHgGADQgGADgGgCQABANgJgDQgMgEgCAEIAAAMQgCABgDADIgCADIgEACQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAGQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQgJgCAAABIgKAEQgEAAgCADQgCAAAAAFQgBAFACAAQgBAKgNABQAAgDgIgBIgLgCIgGADQgGACAAADQAAADgMACQgEABgKAFQgKAFAAADQgCAAgNAHQgNAHAAACQgFACgDAHQgCAFgHgCQAAACgDAEQABAAACAEQACADAAACQgGACgLgDQgLgDgFABIABAKQAAAGgFAAQgCgDgEACQgBABAAAAQAAABAAABQgBAAABABQAAAAABAAQADACABADQgEACgFAAIgJAAQgCAAgHgFQgHgEgFAFIgDAGQgBACgEABIgHAEIgFADQgBAFgJAAIgPgBQAAAHgJADQgLADgCADIgDADQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAgBgBQgCgDgDAAQgEgBAAAEQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAIAAAGIgMABQgDAAgGAFQgEADgDgHQgDgBgDAFQgDAEAAAEQgFAAgFADQgFADAAAEIgGgBIgHABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAADQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgEAAIgPADQgFAGgHACIgPACQAAAAgBAAQAAABAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAADABAGQAAAEgNgEIgHAFQgHAEAAADIgJgBQgEABgCAGIgJADQgHABgCgEQgGADgHAFIgMAIQAAAGgRgDQgSgDAAAIIgFgCQgBgBgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBAAgDAFQgDAEgCgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgGAHQgDAFgFgBIgEAAIgFACQAAAAgBABQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgFAFIgJAEQgHADABABIAYAAQAOgBAIgDQADgBAcgFQAYgFAAgDQADgBAFAGQAEAGAEgCIARgFQACgFAZgDQAAgBALgDIALgEIALgCQAJgBgBgDQARgHABAHIAPgGQAKgDAHABQgSALgFABIgpAUQABgGgKACQgIABgEAEIAEADQgEAAgUAIQgUAIAAACIgJABQgIACAAADQgFABgFgBIgJgDQgBAKgHgBQgMgBgCABQAAABgIABQgJAAABAEQgRAJgKABQgWADAAACIgIABQgGgBAAgBQgDgBgEABIgHACQgWAMAAgIQgDAAgEACQgFABgBADQgDgBgIADIgGADQAAABgVAEQgGAAgFAEQgGAEAKABQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIADABQAAgDARAAQAQgBAAgCQAIAAAWgHIAdgEIAkgGIAVgEQATgEAAABQAIAAAMgEIASgHQgBgBAOgFIAQgEIAVgIQAPgHAEAFIgUAKIgRAHQgGABgLAGQgMAFgEABQABADgKACIgNACQgKAGgLACQAAgCgMAIQgCAFgDgFIgDgDQgEABgFADQgFAEgDAAIgKADQgJABAAADQgFAAgGACQgGACgGAAQAAAJgLgMQgCAGgBAAQgDgFgJACIgLADQgFAGgBADQgFAAgEgDQgFgDgEgBQAAAFgGAEIgLAEQgXALgNgLQgMAEgDAAQAAAHgPAAQAAACgMADQgLADgEgBQAAgEgIAAIgMAAQgCAHgBAAIgHgBQAAACgVgBQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAADgJAAQAAgGgEAIIgDAEIgIAEQAAgEgHABIgIACQgCABgQAAQgOAAgBADIgYAAQgFAAgHgDIgMgDQgHAHgIAAIgRgDQAAABgKADQgKACAAABIgPACQgMACgEgEQAAgBgNAAIgRgBQAAAFgHgBIgKgCQAAADgPABIgFAAQgKAAAAgDgACUKCQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAdgDQAZgCABAEQABAAAAAAQABAAAAgBQAAAAABgBQAAAAABgBQACgDADAAIAEAAIADgBQAEgBAGABQAHAAADgBIAOgFQAJgCAHAEQABgGAEADIAFAFQADAAAFgFQADgGAEABIAHACQADAAAFgDQACgBAFAAIAHgCQAFgBABABIABAFQAEAAAEgGIAJgDIASgFIALgBQAHgBAEgDQALgFADAAQgFgBgPAEIgTAGIgfADQgPACgVgBIgWAEQgSACgBgEQgNACgBABQgKADgJgCQgKgDgNACIg1ADQgFABgCgFIgKADQgBgDgFgBQgIgBgCgCQgLAEgEgBQgMgDgagBIgagBQgFAAgJgCIgOgBIgMAAIgKgCIgBACQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgDgCgCABQgBgDgFgBIgHAAQgKgDgYgBIgOgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABIgDABQgLABgIgDIgFgDQgCgCgDABIgNAAQAAgCgFAAIgHAAQgDgBgEAAIgIAAQgEAAgDgCIgGgEIgPgDQgJgBgEgEQgFgEgBAAQgCACgEAAIgKgCQgGgBgEABQgBgEgMgDQgIgCgGAAQgDABgDgDQgCgCgDABQgDAAgGgBIgKgEQACABgSgIQgQgHAEgBQgCgBgHAAQgGABgDgCQgIgEADgCIgQgFQgDgBgPADQgRADgOgBIApAdQARgBALAEIANAFQAIgBAMAGIAMAFQAKAEAAACIAHgCQADgBACADIAGAHQACgBAIgBQAJgBABADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIASAGQADACAFAAIAIABIASAFQAEACAFABIAJABQAQAEAjAEQA8ALA6AFIAbACQARABALACIAhABQADgBALACIAQABIAMgBQAIgBAEACQABAAAAAAQAAAAABAAQAAAAABgBQABAAAAAAIABgBQABAAAAAAQAAABABAAQAAAAAAAAQAAABABAAgAGCH/IgCgHQAAgDAHAAQABABAHgBQAHgBABgCIAPADQALACAAgEQAGgHAHAFIAMAHQAGAAAAgDQgBgEADgCIAHgCQACAAACAEQAIgIAQgBQAJAAAQABQAAgBAFgCIAGgDIARAAQAAgCAPAAQACAGAEAAQAAgGAIgBQAHgCAAACIAJgCIAJgCQAAAAABgBQAAAAABAAQAAgBABAAQABAAABAAQADAAACgDQALgFAIADQACAAATgEIAGACQAAAAABAAQAAgBABAAQAAAAAAgBQABgBAAgBQAAgBAAgBQABgBAAAAQAAAAABAAQABgBAAABQAFACABgBQAAgCAPgDIARgDQABgCAOgFQANgFAEAAQADABAEgEQAEgDADAAQAAgDAQAAQAGABALgHQAGAAALgFQALgGAGAAQACgDANgEQANgFAFAAQABgCAMgEQALgDAAgBIAVgIQADAAAEgCQAEgDAEAAIAKgEIAHgDQAEgCAEgBQABgDAGgBQAGgCACgCQAEAAAIgDQAJgEACgCQAEAAAHgEQAHgEADgEQAFAAAJgFQAIgFAGAAIAYgMQAAgBAVgIQAWgJACgDQAFAAAJgFQAIgGAGAAQAFAAAGgGQAHgHADAAQAEAAAGgGQAHgGADAAQAHAAAKgIQAEgCAHgHQAAgBAGgCQAGgCAAgCQgHAAAGgCQAFgCADAAQAAgEAJgBQAHgBADABQAAgDADgEQADgFAAgFIAQAAQAAgEAEgCIAIgFIANgIQAAgFAMgGQALgGAAgCQAMgCADgDQAGgEADgJQAFgBAQgbQAMgGAGgKIACgEQABgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAQADAAAFgJQAFgKAFAAQADgFAAgJQAFgDgBgEQABAAACgMQACgNACAAQAAgBgCgFIgEgGQAAAHgLAAIgFAGQgEAGACAAQAAADgHAGQgIAFAAACIgFAGIgGAIQgDAAgFAFIgIAFIgFADQgFADABAEIgJADIgHADIADAAIgBAEQADAAgMAKQgDADgIAAQgHABgCACQAFAAgFAHQgFAGgEAAQgJAMgOADQgEAIgOAFIgCACQgBAAgBAAQAAABgBAAQAAABAAAAQAAABAAAAIgKABQgCABAAAHQgbAFAAAGQgPALAAABIgJADQgGACgEAAQAAADgFACQgEACgEAAQgEgGgEAHQgEAHgCABQAAACgKAGIgMAGQgEABgIAGQgJAGAAAEQAAACgMAEIgQACQAAAEgJACQgJABABAEQAAABgaAFQAAAHgOAGQgLAFgKABQAAgFgOAHIgOAGQgDAAgJAEQgIAEAAABQgEAAgHADQgHADgEAAQAAACgJAEQgIADgCgBIgBADIgBADQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgDABgCgCQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAFIgDAAIgCgBQAAADgFABQgGABAAABQgEACgCgBQgDAAgDACQgDADgMAAIgIAGQAAABgKADIgNADQgNAGgDAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAAAABIgYAKQgYAGgGAEQAAADgXAAIgHAEQgEABgBAFQgFACgEgBIAAAFIgPAAQAAAGgGABQgHACAAgCQgDAAgLAFQgJAEgFgBQAAgBgGACIgHACQgDADgIAAIgMgBQgCAEgLAAIgbAJQAAABgFACIgJADQgFADgKAAQgDgDgDACIgFAEIgKgDQAAAHgNABIgTABIgIABQgFACgBADIgMgBQgcALgDgBIgUACQgSADAAACIgPADIgOACIgHACQgFACAAABQgIAAgQACQgVAEgDAEQACgCATAAQAAAEAZAAQADgEALABIAQACQAAgEANACIAOABQACAAADADQADACADAAIAAAAgAn2HeQgCAEgDAAIANAKQAJAGAEAAIADgDQABAAAAgBQAAgBAAAAQgBgBAAAAQgBgBgBAAQgBgDgGgFIgKgFIgDgCIgCACgAAUGwQACAEACAAIAIACQAFABACgEIADgBQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAgBAHgBQAHgCAAgBQAigBAAgFIAGABQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAFgBANADIAJgDQAGgDADAEQACADAFgBQAFAAACgDQACgCAFACIAIACIgEgEIADgGIAKgCQAGAHAAgFIASABQAFgCAHgHQACgBAKABQAJABADgDQAEgEAHAAIALABQACgFALABIAOABQAAgDAHABIAJADQAAABAKgHQAKgBAOACQAAgIAPgBQAAgBAVgEQAVgFADABQABADAMAAQAMAAACgEIACgFQAEgEADAFQACABAEAAIAGAAQAAgIABgCQACgBAIABQABAEAHgDIALgDQAEgBAKAEIAIgEQAAgFANgDIARgCQAHgDAEgGQADgCAHABIALABIgBgFQAEAAABgCQACgDADgBQADgBADABIAHACQAAgCAPgCIASgBIgCgEIADgBQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAJgBAHgEQAJgHAFgCQAXAAADgFQANAAABgCQAGAAgDgGIAKgBIAEgGQABgBAAgBQABgBAAAAQABAAAAAAQAAAAAAAAQADABADgCQADgCADABQAAACAHAAQAHAAAAgCQAHAAAEgDIAJgIQAHgBAEAAQACgEAEABQAGACACAAQAAgBASgGIAUgIQgDgDABgCQACgCAFAAQADADAFgCIAIgDQAAgBAHgBQAHgBAAgDIAGACQAIgFgEAAQgBgDAPgEQAQgEAAgCQAHAAAHgDIAOgIQABgCAIABQAHABAAgEIADgDQABgCAFAAQAEAAAHgDQAAgBAKgDQAKgCADABQgBgFAFgDQAGgEACgDQAPABAAgDIAHABQAEAAABgEIAKgIQAAgDAIgEQAHgFAEAAIALAAQAAABATgLQAAgDAHgFIAIgFQAGAAAIgHQAIgIAFAAQAAADASgNQAIgGAKAAQAUgNAAgCIAWgPQALAAAMgIQADgHAEAAQADgDAJgDQAJgEACgDQAFAAADgGQADgHADAAIAKgHQABgDAEgEIAHgGIAGgCQAFgBABgCQAAgFANgGQAMgHgBgDQAVgZADgBIAHgPQAFgKgHgDQAAgCgHgEQgIgDgBgDQAAgDgEgCIgHgFQgMgLgGgDIgQgHQgNgHAAgDQgGAAgJgFQgKgGgEgBQAAgBgJgFIgKgHQgEgBgIgFQgHgFgEAAQAAgBgSgEQgUgHgDgDIgQgIIgKABQgHABgEgBIgFgCIgHgBQgRgLgDAAQAAABgSgHIgJgDQgDgEgGgCIgKgBQgtgKgGgBQgGgHgWADQgSACgDgEQgDgEgHAAQAAgBgOACQgPACAAgDIgTgBQAAgEgGgBQgHgHgIAEIgNAFQgHAAgKgEIgRgGQAAAFgXgBQgWgBAAgJQABgEgFgBQgEgBgFABQgCADgIgCQgBgBgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAADgJgBQADAHAAAEQAHAAACAeQACAcgCAIQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABABQAAAAAAAAQgBABAAAAIgBAUQgBATgEAAQgBADADADIgIAQIgGANQgFAIAAAGIgGAPQgFAOgHAAIABAFQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIAAAEQgCAAgCAGQgBAGgDAAIAAAEQAAABgBAAQAAAAAAABQAAAAgBABQgBAAAAABIgFAEIgBAHQgDAAgBAFQgBAAgGAIQgHAJgFABQgBADgIADQgIACABAFIgCAFIgCADQAAACgEAEIgGAFQAEAKgSACQgBAGgHAEQgIAGgCADQgFAIgTAJQgCABgDAEIgFAFQgJAAgRAOQgUARgFACIgNAFQgJAEAAAEIgLAHQgGAFgGABQAAgBgFAFQgFAEABAAIgKAFIgKAGQAAABgLADQgMADAAAEQgJAAgRANQgSAMgMAAIgKADQgIAEgBABIgJAHQgFAFgFAAQgeAKgEAAQAAACgJAGQgJAFAAgEQgEAAgHADQgHAEgDADIgLACQgFABgEAFQgFAAgKAGQgJAGgEAAQgDAFgVAAQgCADgDACQgEABgBACIgGABQgEABgCgCIgGgDQgHgBgGADIgKAIQgBAFgNAEQgDAAgIAFQgHAEgEAAQgsANgHAAQAAADgZAHQgaAIgDADQgTACghANQgHADgOAAQAAAGgPAAQAAACgVAGQABgGgiAKQgEAAgGACIgKAEQAAgBgMAEIgPAFQgIAGgMACIgWAFIAFAAIABABIARACQAOACABgDQAcAAASAEQAsgBAAAFQAFABAvgHQAHgDAHAEIANAHQAAgCAQgCIAUgCIAQgBQAEABACADgAqtGZQgHgMAAgBIAHAFIAGAEQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIADgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgGAAIgCgBIgBAAIAAgBQgDgDgDgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgDgBQgjAFAAgEIgJgBIgIgCQAAgEgOACIgQADQgGAJATADQAWADAAABIAVABQARAAAAACIASAAIAAAAgAopGGQgDABAAAFIADAEIAEAFIAHgBQALAAgJgLQgFgEgEAAgAmTFsIAIAOIAFAFIAOACQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAIAOgCQAJgCAEABIBCgLQAAgCAVgDIAYgEQBOgSAHAAQAAgBAXgGQAXgFAEAAQAAgDAWgEQAWgDACgEQAHAAAKgEQALgDAGgBQAGAAALgEIAQgFQACgDAdgHQAagGgBgHQAYgBAAgDQAJgBARgHQAAgBAJgCQAJgCAAgBQADAAADgCQABgBAAAAQABgBAAAAQABAAAAgBQAAAAAAgBIAGgBIAFABQAAgDAQgFQAOgEAFAAQACgDAJgDQAKgCAAgDQAEAAAIgDQAJgDACgDQAGAAALgEQAJgEAFgEQAGgFAPgDQABgCANgEQANgEAAgCIANgGIAOgHIAPgFQAKgEADgEQACAAAJgFQAIgEAAgBQAEAAAIgEQAIgFADgDQAKAAAOgKQAOgKAIgBQACgEAUgJQATgKgBgCQAAgBANgHQAOgHAAgBIAHgGQADgDAFgBQAKACAEgGIAEgIQAEgIAFAAQAAgBAFgEQAGgDAAgCQAFgBAIgHQAIgHAFgBQADAAACgFQACgFADgBIAIgFIALgKQAEgCAFgHQAFgHAEgCQAAgFAOgMIAOgRQACgEAFgIQAGgIACAAQABgGAFgHIAGgMQACAAACgFIACgGIACgHQACgGgBgDQgFAAgJAOQgKAQgEACQAAAGgMAJIgLAKQgGAHgEACQAAAFgHAFIgKAKQgBACgIAFQgHAEAAAEQgDABgDAEQgDAEgFABIgEAFQgEADgCAAIgHADIgIADQAAACgEADQgFAEgBADIgKAGQgHAGgBACQgDAAgJAGQgJAGgCADQgKADgQANQgPAMgMACQgFAGgMAEQgLAEgIAAIgOAOQgFAAgHAGQgHAFgDAAQgCAEgIABQgHABgDADIgHADIgGADQgCAAgEAEIgFADQgCAEgJAAQgJABgDAEQgEACgDAAQgCAEgIABIgNABIgJABQgGAAgDABQgDABgDAHQgDAGgEABQgEAEgFgCQgHgCgDABQAAAEgFACQAAAEgVAJIgbALQgDAAgFADQgFADgDAAQAAACgNACQgEAEgIADQgHACgGAAQAAACgNADQgNADAAADIgNACQgKACgCADQgGAAgCABQgDABgFAFQgHAAgGACIgNADIgWAHQgBACgKACQgKACAAACIgbAHQgFAAgIADQgIADgFAAQgCACgOAEQgNADAAABQgDAAgFADQgFADgDAAQgBACgGABQgFABgCgCQgRAHgCAAQgDADgNADIgMACQgEABgKAEQgIADgEAAQAAACgOAAIgQgCQAAABgJADIgMACQgPAAgMAFQAAAFgLACQgMABAAABIgXAAQgQAAgFAFIgDACIgDADIgJADIgHACQgCADgcAEQgcAFAAACIgFAAIgFAAgAxuEwQAAgCgHgCQgFgCgEAAQAAAGAQAAgAzoD+IgCADIAOALIAKACIALACQAEAHAcAKQAbAKAAgGQgOAAAAgHQgQgCAAgCIgUgKQgCAAgEgIQgEgHgGAAQAAgDgKgBIgKgBIAAAAIgGACgAmhD9QgJAEgBADQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAIADAAQAAACAsgFIA0gGQAAgDAWgEIAcgFQABgDANAAIARAAQAFAAARgGQANgEAIACQAAgCATgDIAWgEQAAgFALACQAMACAAgEIAKAAQAGAAADgEIAJgDQAFgGAQACQAQABACgFQgIAAAHgEQAGgEAEAAIANgBIAEACIAFABIASgEQAAgCgFABIgHABQgDgGAcgHQAXgHAKAAQAAgBALgCQALgBABgCIAHgCIAHAAIADADIAFABQAAgBAAgBQgBgBABAAQAAgBAAAAQABAAABAAQgCgFAEgBIAJgCIAKAGQAKAGADgBIgHgDIgDgKIAGgFQADgBAFACQACABAMgFQALgFAAAEQADABAEgCQAEgCAAgCQAOAAADgFQAAgJAJAAQACgEAKAAIANAAQAFgBADgEQADgEADAAIAVAAIAEgJQADgDAEABIAGADQgBgJAGABIALADQADAAAEgDQAEgEADAAQACgCAJgFQALgFABACQAAgHAUgCQAUgCAAgCQAIAAAFgBIAFgDIAGgDQACgDALgDQAMgDAAAGQAEABAOgEQAGgEABgFQgEAAAEgHIAFgIQAEgCAAgJIANgHQAJgFAGAAQABACAKACIAMACQAAAEAMgGQALgFACgEQgHAAgCgMQAFAAAMgPQASgEAAgCQAMgCAOgGIAWgKQAFgFARgHQAOgGADgHQAGgCANgOQALgMAHAAQACgDAFgDQAFgEACgDQACgCAHgGQAHgFAAgEQACAAAFgIQAFgHAAgCQAEAAAJgXQAKgXgCgFQgCAAAAgMQABgMgEgCIADAAQgBAAgDgHIgHgRIgSgBQAAACgPgEQgPgDAAADQgmAHAAgBQgLABAAgCIgIABQgFABgDgDIgHABIgJABQAAgBAAAAQAAAAgBAAQgBAAAAAAQgBAAgBABIgGABQAAAEgMABQgLABgFgBIgPgBIgDAFQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIgOABQgCAHgNgEIgUgGQgBACgIABQgFABAAAHQgYAAgEABQAAADgUABQgUABAAACIgZABQgLAAgDADIgBABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgQABQAAABgGACIgIABQAAgBgSADQgTACAAACIgMADQgIACgFAAIgJAIQAAAEgJgHQgDAAgBADIgCAFQgBADgEABIgGABQAAAEgMAAQgBACgEABQgEABgDADQgDADgGAAQAAgEgGABIgKACQAAAFgWgCQAAAGgJADQgLADgCACQgCAAgEADIgHAEQgEACgCgBQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgDAAgCgCQgEgCgCAAIgIADIgIACQgDgCgEACIgHADIgEAEQgEAEAAACQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABIgBAEIgEAFIgCAAQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgDABgCgCQgDgCgCABQgFAJgVACIgUAMQgKAEgEgDIAAgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAQAAgBgKAHQAAAHgEABIgIgCQgBgBgHADQgHADgBACQgFAAgDADQgDADABAEIgMACQgNADgEAFQgEAAgBAFIAAAGIgRAJQgEAGgIAAIgMgCQACAMgGACIgMAHQgMAIAAgFQgGgEgBADIAAAEQAAADgKAIQgLAGgEABQAAACgGAEIgKADQAAgGgFAEQgHAFACAAQAAAFgHAIQgGAHgFAEQgCAFgFADIgKAEQgJADgDgEIgIAHQgFAFAGAAIgCAHIgGAJQgFAGgCAAIgKAJQgHAHgCAEQgGAAgCADIgEAJQgEABgEAFIgGAHQACAEgZAYQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIAPgBIAqgFQAAAFARgHIAFAAIADgCQAAAAABAAQABgBAAAAQAAAAABAAQAAAAAAABIAEACQABgFAKgDIAJgEQAGAAAVgEQASgDAEAIQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAgBABAAQACgEACAAQAAgBAFABIAHAAQAAgBAGAAIAJgBQAAABAAAAQAAABABAAQAAAAABAAQABAAABAAQAAgKAqAAQAAgEAKgBIAOgBQAAgHAZgBQAZgCAAADQADgBAEgEQAEgDACAAQAAgCAHACIAIACQAAAHAVgMQAAgCAHgDIAJgCQAFAHAHgBIARgDIAOgBQAHgBAAgGQgEADgEAAQAAgEADgCQAEgCABgCIAOgCIAGgCQAAgFALAAIAPAAQAHAHAGgGQAJgKAEgBQAMAAAAgCQAFAAADAFQACAFgHAAQAAAEAHACQAGADAAgFQgEAAgBgDQAAgEAEAAQAAgCAKAAIAGgEQAFgCAAgDQAHAAAEgDQABgCAEABQAEABACgBQAEgHALAAQACABAHgDIAIgEQAVgLAAAFQALAAgDgBQgIgEgBgCQgHgCAGgCIAJgBIAFAGQACACAEABQAMAAAAgCIAYgLQAFAAAJgEQALgEAFAAQAAgEAMgEQAKgDAFAAQABgCAFgCQAFgCACgCQAQgEACAAQAEABADgDQAFgFADgBIAJgFQAHgDACAEQACADgLANQgEAAgHAGQgIAFgEAAQAAAFgNAGQgOAGgCAEQgCAEgKACQgIABgCAEQgEAAgHAFIgJAHQgcALAAgBIgTAPIgMAEIgLAEQgZAGgGAIQgGgBgGAEQgGADgEAAQAAABgMABQgLABAAAGIgQADQgLACgEAEQgMAGgHABQAAACgJADIgKAEIgEAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgKADQgEAGgJABIABADIgGACIgHACIgJAAQgFgBgEABIgKAGQgKAFAAgBQgIAAgPAFQgPAFgJAAQAAABgWAEQgWAEAAADQgdALAAgEQgEAAgIAFQgHAFgEAAIgQAFQgRAEgBABIgZAFIgkAJQgaAAgCAEIgIACIgIACQAAgDgUAHIgNAEQgIADgHAAQgKADgFAAIgTAAQgFAFgMAAQgNgCgFABQAAABgIACIgLADIgBgBIgIACgAz3D2QAEgHgIgCQAAgBgEgEIgFgFQgDAAgIgFQgHgEgEAAQgBgDgHgGQgHgGgDAAQAAgCgLgIQgLgIgEAAQACAFAGAIQAGAHAFADQANAKgCAAQADAFAGAAQAWATAAgCQACABAFgCQAAAHALAAgApzCuIAGAEQgEABgCADQgDAEADADQAFADgDADIgEAEQATgEAAgBQADgBAFABIAHACIAEgBIADgDIADgBIAKgCQgFgZACAAIgCgJQgCgGABgDIACgOQABgIABgEQADAAgBgIQgBgIgGgBIgMASQAAAFgGAJQgGAJABAEQgGADgCACIgEAJQgCAAgCAEIgDAFQAAAEgIgGQgBABAGAEgAnqBaQgEAAgDAIQgEAKgDABQgDAVgBAAIAAACQgDAAgDAUQgDAUACADQADgBAFgIIADgIQADgHACAAIAFgLQAEgIACAAIADgHQAEgFAAgDQACAAAEgJIAFgLIAIgGQAHgGAAgCQAEAAABgDIABgIQACAAACgDQABgEADAAQAIgJABgEQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIACgFQAIgFAHgLQAEAAAGgJQAFgJAGAAQAegLgOAAQAAgGAFgCIAJgDQAAgGAIgEQAIgEAAgFQAFgBADgEQAEgFADgBQACgDAMgGQALgFAAgEQAKgGAGAAQAAgEAIgFQAIgEAAgDIAGgEIAHgEIAHgFQADAAAIgHQAIgGABABIALgGQAIgFACgDQAHgFABgGQAFAAAGgBQAGgCAJgGQAAAHAMgIIAPgKQACAAAGgEIAHgGQABgBAIgDIAIgDQAhgKAAgDQAFAAAJgEQAIgDAGAAQABgEAFACQAHABACgIIAGgCQACAAAHgEQACgCAOgEQANgDAAgCIAJgDQAGgDAAgDQAQgCAAgBIAJgCQAHgCAAgBQAFAAAKgEQALgFAGgBQAAgBAIgDIALgCQA2gRAEAAQAAgBAOgDIAQgEQATABAAgGQAFAAALgDQAKgDAGAAIAfgIQAAgCAMgBIAOgBQAAgCAMgCQAMgBABgCQAEAAAGgCQAHgDAEAAIAMABQAHgBADgDQAXgCAKgDQAAgEAygEQADgFAeAAQASABARgEQAAgFA4gBIA+gBQAAgCAGABQABAAABAAQABAAAAgBQABAAAAgBQAAAAAAgBIADAAIgBgCQgEAAgEgIQgFgIgDAAQAAgDgHgHQgHgGAAgEQAHgCAJADQALADAAAIQAEABAFAEQAFAEACAEQADACAAAFIADABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAEADQAEgBAEABQAGABAMgBIAUAAIAmACQAhABAAABQAIABAHgBQAAgCAUACIAZADQArACAAACIAzAEQArAFAAAGQAKAAAUAFQAVAEAKAAQAAACAPADQAPACAAACQAHABAKAEQAJADAHABQADABAHADQAGADADAAQAAADAJAAQAKABABACIAcAJQAEAAAIAEQAJAEACADQAOAHAAgDIAEABIACACQAEAAALAGQALAGAAABQAFAAAIAGQAIAFAEAAQAAABAHAFQAHAEACAAQAAABAIADQAIAEABACQADADAKAFQAIAFADAEQAHAAgHgJQgGgKgFAAIgEgEQgEgDAAgCQgIAAgHgKQgEAAgKgJQgLgKAAgDIgLgBQgHgCAAgEIgDgCIgGgBQgIgIgCgBIgOgHQgGgEgHAAQgEgFgKgDQgEgBgBgCQgCgDgCgBQAAgCgSAAQAAgGgLgCIgPgCQgHAAgHgDQgIgEAAgEQgIAAgNgJQgNgKgHAAQAAgBgKgCIgKgBQgZgHAAgCIgPgDQgIgDgEAAQAAgEgdgGQgZgEgKAAQAAgCgOAAQgPgBAAgEIgXgDQAAgDgbgCIgbgDQgZgDgMAAQAAgBgMgBQgMgBgBgBIgbgBQAAADgogCQgBgCgOAAQgNgBAAACQgDABgGgBIgIgBQgRACgIgBIgKADQAAABgKAAIgMgBQAAADgVACQgVABgFgBIgwAEIg5AEQgFAAgYAEQgZAEAAACIgXACIgUADQAAAHgyACQAAADgkAGQgCADgJAAQgJAAgDAEQgFgBgGACIgJABQAAACgOABQgNABAAADIgeAJQgSAFgLAAIgdAKQgeAJgCgBQAAAEgNACQgOACgBAEIgOAEQgIACgFABQAAABgHADIgIACQAAABgKAEIgPADQgCAEgLADQgLADgCAEQgEAAgGADQgHAEgDAAQgVAFgFAHQgFAAgIAGQgJAGgFAAQgDADgHAEQgHAEgEAAQgCADgPAIQgEAAgJAHQgIAHgHgCQgBAEgJAAQgBAEgIADQgNAFgHAGIgPAJIgPAJIgJAIQgEAFgFAAQABgCgKAHQAAAGgYAPQgLAMgKAEQAAABgEADIgGAEQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAABgFAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQgDAEgMAHIgDAEIgEAEQAAADgEAEQgDAEgDAAIgFAHIgHAFQAAACgJAIQgDADgEACQgFABgDADQAAADgEACQAAADgDACIgGAEQgCACAAAEQAAAFgCACIgFADQgDAAgCADQgCAFgBAAQgBACgEAGQgEAFgCABQAAAGgJAGQgKAGAAAGQABAAgFARIABAIQgBAFgDABIgBABIAAAAIgBABgAxpmXQgDABgCACIgCAFQgHAAgCADQgCAAgGADQgFADgCACIgHADIgGADQgGAHgTAGQgCAEgKACQgKABgBADIgHAGQgGAFAAABQgOAAgBAHIgSAOQgEAAgPAKQgJAGgGAHQgCADgFADQgFADgCADQAAAHgIAEQgKAEgBAFQgCABgDAGQgCAEgDABQgBACgGAFQgFAEAAADIgJAJIgIALIgDACQACACAlgbQAmgdAHgBIAHgFQAEgDADAAQAAgBAEgCIADgEQgDgBAAgEIAMgBQAIgCACgCIADgCQAAgBABAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgCAGgDQAFgDACAAQACgDALgFQAJgEACgDQADAAAFgFIAHgHQAMgEABgBQADAAAHgEQAJgEADgBQACgCAHAAQAEABABgFQABgJANAAIAHgIQACgDAFABQAFABABgDQACAAAHgEQAHgFACgBQAAgCARgHQAQgHADABIgBgEQAGgBAHgEQAHgEAFgBIALgFQAHgEACgDQADAAAFgCIAHgDQACgCAFAAIAIABQACgFADgCQAGgHAPgDIAYgDQACgDAIgDQAIgDAEAAQAAgDAIACQACABAEgCIAGgEIAIgEQAEgCADAAQAEgGAOgEIAWgEQAGgBALgDQAOgEAAgDIAHgCIAFgDIAJABQAFgBAAgFQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAABgBIACgDIgGgDIgvAMIgCgBQAAACgLABQgKACAAABQgHAAgLAGQgLAGgGABIAAgDQgFAAgKADQgJADgFAAQgEgBgCADIgFAEQgEAEgCAAIgHgDIgIAEQgIADgBAEIADABQgBADgFAAQgEABACgEQgDAAgHADQgHADgEAAIgFACQgGADgBACIgDAFQgDABgDgBQgCAGgOAFQAAABgFABQgFAAAAABIgLACQgEABgCAHIgDABQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgKAAAAgCQgCAAgDACQgEADgCABIgOAHQgNAIACABIgNAGIgNgCIgDABgAlSlJQgFgDAKgGIALgHQAIgDAAgBQABgBABAAQAAAAABAAQABAAAAAAQAAABABABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQACACgOAJQgJAGgFAAIgEgBg");
	this.shape_1.setTransform(7.7928,27.7457,0.4948,0.4948);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABwDnIAAkXQAAgygageQgbgeguAAQgfAAgdAPQgdAPgkAjIAAFEIhjAAIAAnEIBjAAIAAA8IADAAQAdghAogSQAngSAqAAQBLAAAvAtQAxAxAABZIAAEWg");
	this.shape_2.setTransform(117.997,94.1892,0.4949,0.4949);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjCCoQhLhEAAhnQAAhiBNhCQBNhDBxgBQB2AABNBCQBNBBAABlQAABqhMBCQhMBDh4AAQh1AAhLhEgAh4hvQgvAqAABCQAABGAuAsQAtArBIABQBPgBAugqQAugrAAhIQAAhBgwgrQgxgrhKAAQhGAAguArg");
	this.shape_3.setTransform(90.4194,94.4243,0.4949,0.4949);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiqEwQhCgnAAg8QABgyAegeQAfgfBBgOQgygbAAgeQAAgWAWgRQAWgRAjgIIAAgCQg3gVgdgkQgbgjAAgyQAAhIA8gqQA7gqBkAAIDRAAIAABFIhoAAQAeAbAMAWQALAVAAAdQAAAbgPAeQgNAcgTARQgiAghdAPQgoAGgOAGQgXAJAAARQAAASAnAOQAiAMBQAOQBNAOAlAjQAhAfgBAuQAABEg/AmQg/AmhvAAQhmAAhBgmgAhtCYQggATAAAeQAAAiAkASQAkASBEAAQBBAAAlgRQAlgSAAgfQgBgmg7gUQgsgOg9AAQgyAAggATgAhIjvQgdAYAAAhQABAlAbAXQAcAXAtAAQApAAAcgYQAbgYAAglQAAgggdgYQgdgYgnAAQgpAAgeAZg");
	this.shape_4.setTransform(64.4501,100.1526,0.4949,0.4949);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABoAAQBmAAA5A+QA8BAAAB7IliAAQAYCHCQAAQBVAABbg2IAABXQguAcgsAMQgxAOg9AAQhxgBhEhJgAhPiAQgjAdgKA2ID9AAQgDg0gfgeQgggeg0AAQg4AAgiAdg");
	this.shape_5.setTransform(39.7057,94.4243,0.4949,0.4949);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ai3DnIAAnEIBkAAIAABoIACAAQBHhxBKAAQA6AAA/A1Ig1BNQgXgTgbgNQgagMgSAAQgzAAgjAoQgjApAAA6IAADsg");
	this.shape_6.setTransform(19.9101,94.1892,0.4949,0.4949);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Aj1DJQhahSAAh3QAAh3BchTQBfhVCUAAQCWAABfBVQBbBSAAB4QAAB3haBSQhfBXiYAAQiVAAhfhXgAitiYQhGA8AABcQAABcBGA9QBFA9BoAAQBpAABFg9QBFg8AAhdQAAhchFg8QhFg9hpAAQhoAAhFA9g");
	this.shape_7.setTransform(-9.6965,91.7272,0.4949,0.4949);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABnAAQBnAAA5A+QA8BAAAB7IljAAQAMBCArAjQAqAiBIAAQBUAABdg2IAABXQgwAcgrAMQgwAOg/AAQhvgBhFhJgAhQiAQgjAdgKA2ID+AAQgDg0gfgeQgggeg0AAQg4AAgjAdg");
	this.shape_8.setTransform(-41.7282,94.4243,0.4949,0.4949);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ai4DnIAAnEIBkAAIAABoIADAAQBHhxBKAAQA7AAA9A1Ig1BNQgWgTgbgNQgagMgSAAQgyAAgkAoQgkApAAA6IAADsg");
	this.shape_9.setTransform(-61.1773,94.1892,0.4949,0.4949);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ABFDgQgTgLgHgYQhAAuhHABQg2AAgkgiQgiggAAguQABg7A3gkQAfgUBVgbIBYgcIAAgYQAAgpgWgUQgWgTguAAQhZAAhHBLIAAhiQA7g+BtAAQBQABAxAjQA1AoAABKIAADoQAAAXATAAQARAAAkgYIAAA2QgjAVgTAHQgUAIgWAAQghAAgSgMgAhCAtQgxAbAAAkQABAcAUASQAVASAeAAQAsAAArgmIAAiDQhOAXggATg");
	this.shape_10.setTransform(-84.536,94.4243,0.4949,0.4949);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AjIDAQhRhQAAhnQAAiABhhUQBhhUCUAAQBcAAB7AuIAABXQg6gfg0gOQgzgOg3AAQhqAAhHA9QhHA+AABbQAABeBGA8QBGA7BwAAQBsAABug/IAABXQgzAYgwAMQg6AOhFAAQihAAhfhgg");
	this.shape_11.setTransform(-112.7818,91.9993,0.4949,0.4949);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CO_v_white, new cjs.Rectangle(-126.7,-7.3,264.2,124.39999999999999), null);


(lib.BUTTON = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAqIAlgqIglgpIAaAAIAmApIgmAqgAg2AqIAmgqIgmgpIAbAAIAlApIglAqg");
	this.shape.setTransform(71.925,4.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag5BQIAAicIAeAAIAAAOQAHgIAJgFQAJgEAJAAQALAAAKAEQAJAEAHAHQAGAIAEALQAEALAAAPQAAAOgEAKQgEALgGAIQgHAIgJAEQgKAEgLAAQgJAAgJgFQgJgEgHgJIAAA6gAgQgxQgHAEgEAFIAAAoQAEAFAHAEQAIAEAHAAQAMAAAIgJQAIgIAAgPQAAgPgIgKQgIgJgMAAQgHAAgIAEg");
	this.shape_1.setTransform(56.425,6.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgOBPIAAidIAdAAIAACdg");
	this.shape_2.setTransform(46.85,2.025);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgUA3QgMgDgIgIQgIgIgFgLQgEgLAAgOQAAgMAEgKQAFgLAHgJQAIgIALgFQALgEAMAAQANAAAKAEQALAFAHAIQAIAJAEAMQAEALAAANIAAAGIhUAAQACALAIAIQAIAIAOAAIAIgBIAIgCIAIgEIAHgEIANATQgJAIgMAEQgNAEgNAAQgMAAgLgFgAgKghQgFADgEADIgFAJIgCAIIA3AAIgCgIIgFgJQgDgDgFgDQgGgCgHAAQgGAAgFACg");
	this.shape_3.setTransform(37.975,4.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAXBPIAAhGQAAgLgFgEQgGgFgJAAQgJAAgGAFQgHAEgDAEIAABNIgeAAIAAidIAeAAIAAA6QAFgGAKgGQAJgFAOAAQAUAAAIAJQAJAKAAARIAABQg");
	this.shape_4.setTransform(25.2,2.025);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgbBMQgIgEgHgHQgHgIgEgLQgEgMAAgOQAAgOAEgKQADgLAIgIQAGgHAJgFQAKgEALAAQAJAAAJAFQAJAEAHAJIAAg6IAeAAIAACcIgeAAIAAgOQgHAIgJAFQgJAEgJAAQgLAAgKgEgAgSgDQgIAIAAAPQAAAIACAGQACAGAEAEQAEAFAFACQAFACAGAAQAHAAAIgDQAHgEAEgGIAAgoQgEgFgHgDQgIgEgHAAQgMAAgIAJg");
	this.shape_5.setTransform(6.3,2.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAXA6IAAhEQAAgMgFgEQgGgFgJAAQgIAAgHAEQgHAFgDAEIAABMIgfAAIAAhxIAfAAIAAAPQAFgGAKgGQAJgFAOgBQAUAAAIAKQAJAKAAARIAABPg");
	this.shape_6.setTransform(-6.4,4.05);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgOBRIAAhxIAdAAIAABxgAgMgxQgFgGAAgIQAAgHAFgFQAGgFAGAAQAIAAAEAFQAGAFAAAHQAAAIgGAGQgEAEgIAAQgGAAgGgEg");
	this.shape_7.setTransform(-15.55,1.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag3BPIAAidIBvAAIAAAeIhNAAIAAAhIBLAAIAAAdIhLAAIAABBg");
	this.shape_8.setTransform(-24.275,2.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// bkgd
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00A7B5").s().p("AxYC4IAAluMAg4AAAIB6CtIh6DBg");
	this.shape_9.setTransform(-3.65,3.85);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	// shad copy
	this.instance = new lib.Buttonshad();
	this.instance.setTransform(-21.65,-15,0.6438,0.6438,0,0,180);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shad
	this.instance_1 = new lib.Buttonshad();
	this.instance_1.setTransform(-30,-15,0.6438,0.6438);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BUTTON, new cjs.Rectangle(-171,-15,300,56), null);


(lib.BKGDblue = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#256BA2").s().p("A3ZKVIAA0pMAuzAAAIAAUpg");
	this.shape.setTransform(0,66.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGDblue, new cjs.Rectangle(-149.7,0,299.5,132.2), null);


(lib.BKGD = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF8300").s().p("A96WbMAAAgs1MA71AAAMAAAAs1g");
	this.shape.setTransform(0.0067,125.0449,0.7833,0.8714);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGD, new cjs.Rectangle(-150,0,300,250.1), null);


(lib.HEAD3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD3type();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD3, new cjs.Rectangle(-139,0,150,100.4), null);


(lib.HEAD2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD2type();
	this.instance.setTransform(0,26,1,1,0,0,0,0,36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-139,-10,150,100.4), null);


(lib.HEAD1b = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1btype();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1b, new cjs.Rectangle(-139,0,150,100.4), null);


(lib.HEAD1a = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1atype();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1a, new cjs.Rectangle(-139,0,151,76.3), null);


// stage content:
(lib.CO_MhSubstance_160x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,289];
	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_289 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(289).call(this.frame_289).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,2,0,3).p("EgMaguyIY1AAMAAABdlI41AAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(290));

	// HS logo
	this.instance = new lib.HS_logowhite();
	this.instance.setTransform(80.2,557.75,0.31,0.31,0,0,0,0.7,71.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(290));

	// CO logo
	this.instance_1 = new lib.CO_v_white();
	this.instance_1.setTransform(79.2,500.2,0.35,0.35,0,0,0,0.1,55.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(290));

	// CTA
	this.instance_2 = new lib.BUTTON();
	this.instance_2.setTransform(-27.3,446.95,0.76,0.76,0,0,0,-10.4,3.9);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(274).to({_off:false},0).to({x:52.7},15,cjs.Ease.quadOut).wait(1));

	// BKGD-orange
	this.instance_3 = new lib.BKGD();
	this.instance_3.setTransform(79.7,575.2,0.5317,0.7337,0,0,0,0,217);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(290));

	// HEAD1a
	this.instance_4 = new lib.HEAD1a();
	this.instance_4.setTransform(145.5,319.65,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(119).to({alpha:0},8,cjs.Ease.quadInOut).to({_off:true},1).wait(162));

	// HEAD1b
	this.instance_5 = new lib.HEAD1b();
	this.instance_5.setTransform(145.5,327.65,1,1,0,0,0,0,24);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(43).to({_off:false},0).to({alpha:1},6).wait(70).to({alpha:0},8,cjs.Ease.quadInOut).to({_off:true},1).wait(162));

	// HEAD2
	this.instance_6 = new lib.HEAD2();
	this.instance_6.setTransform(145.5,331.65,1,1,0,0,0,0,36);
	this.instance_6.alpha = 0;
	this.instance_6.shadow = new cjs.Shadow("rgba(0,163,181,1)",0,0,0);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(133).to({_off:false},0).to({alpha:1},8).wait(60).to({alpha:0},8).to({_off:true},1).wait(80));

	// HEAD3
	this.instance_7 = new lib.HEAD3();
	this.instance_7.setTransform(145.5,322.65,1,1,0,0,0,0,24);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(210).to({_off:false},0).to({alpha:1},8).wait(72));

	// BKGD-blue
	this.instance_8 = new lib.BKGDblue();
	this.instance_8.setTransform(80,352.1,0.5342,1,0,0,0,0,66.1);
	this.instance_8.alpha = 0.6992;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(290));

	// PIC
	this.instance_9 = new lib.MhSubstance_160x600();
	this.instance_9.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(290));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-69.3,299.5,237.8,301);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 160,
	height: 600,
	fps: 36,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/CO_MhSubstance_160x600_atlas_P_1.png", id:"CO_MhSubstance_160x600_atlas_P_1"},
		{src:"images/CO_MhSubstance_160x600_atlas_NP_1.jpg", id:"CO_MhSubstance_160x600_atlas_NP_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;