(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"JCC_SchoolisBack_300x600_atlas_P_1", frames: [[0,0,232,87]]},
		{name:"JCC_SchoolisBack_300x600_atlas_NP_1", frames: [[0,0,600,1200],[0,1202,300,600]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib._300x6002x = function() {
	this.initialize(ss["JCC_SchoolisBack_300x600_atlas_NP_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.Buttonshad = function() {
	this.initialize(ss["JCC_SchoolisBack_300x600_atlas_P_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.sch_img_300x600 = function() {
	this.initialize(ss["JCC_SchoolisBack_300x600_atlas_NP_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.JCClogo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#40474F").s().p("AgRAdIABgIIAEABQAFgBABgDIACgFIgRgqIAKAAIALAfIAMgfIALAAIgVAxQgCAJgMABg");
	this.shape.setTransform(56.05,24.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#40474F").s().p("AgEAdIAAg5IAJAAIAAA5g");
	this.shape_1.setTransform(52.775,22.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#40474F").s().p("AgDAfIAAgqIAIAAIAAAqgAgFgYQAAgFAFgBQAGABAAAFQAAAGgGAAQgFAAAAgGg");
	this.shape_2.setTransform(50.625,22.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#40474F").s().p("AAVAWIAAgbQAAgIgHAAQgGAAgEAGIAAAdIgIAAIAAgbQAAgIgHAAQgGAAgEAGIAAAdIgJAAIAAgqIAJAAIAAAGQAFgHAJAAQAIAAADAIQAFgIAJAAQANAAAAANIAAAeg");
	this.shape_3.setTransform(45.925,23.375);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#40474F").s().p("AgNATQgFgEAAgHQAAgHAFgCQAEgEAGAAQAIAAAFAFIAAgFQAAgIgKAAQgHAAgFAFIgEgGQAHgHAKAAQASAAAAAPIAAAbIgJAAIAAgEQgFAFgIAAQgGAAgEgDgAgIAIQgBAIAJAAQAGAAAEgEIAAgHQgEgEgGAAQgJAAABAHg");
	this.shape_4.setTransform(39.75,23.425);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#40474F").s().p("AgTAdIAAg5IAnAAIAAAJIgdAAIAAAPIAcAAIAAAIIgcAAIAAAZg");
	this.shape_5.setTransform(35.375,22.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#40474F").s().p("AAKAWIAAgaQAAgJgJAAQgGAAgDAGIAAAdIgKAAIAAgqIAKAAIAAAGQAFgHAIAAQAOAAAAAOIAAAdg");
	this.shape_6.setTransform(27.95,23.375);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#40474F").s().p("AgPAQQgGgHAAgJQAAgJAGgGQAGgGAJAAQAKAAAGAGQAGAGAAAJQAAAJgGAHQgGAGgKAAQgJAAgGgGgAgIgJQgDAEgBAFQAAAOAMAAQANAAAAgOQAAgFgDgEQgEgEgGAAQgFAAgDAEg");
	this.shape_7.setTransform(23.15,23.425);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#40474F").s().p("AgRAYIADgGQAGAFAIAAQALAAAAgMIAAgFQgEAHgIAAQgIAAgGgFQgFgHAAgIQAAgLAFgGQAGgFAIAAQAIAAAEAGIAAgFIAKAAIAAAnQAAATgVAAQgLABgGgHgAgKgHQAAAMALAAQAHAAADgFIAAgQQgDgFgHgBQgLAAAAAPg");
	this.shape_8.setTransform(18.15,24.25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#40474F").s().p("AgOAQQgGgGAAgKQAAgIAGgHQAGgGAIAAQAKAAAGAGQAFAHAAAJIAAACIgfAAQAAAFAEADQAEAEAEAAQAIAAAEgFIAEAGQgGAGgLAAQgJAAgGgGgAgLgCIAXAAQAAgFgDgDQgDgEgGAAQgKAAgBAMg");
	this.shape_9.setTransform(13.275,23.425);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#40474F").s().p("AgKAWIAAgqIAJAAIAAAGQAFgHAHAAIAAAJIgCAAQgIAAgCAGIAAAcg");
	this.shape_10.setTransform(9.5,23.375);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#40474F").s().p("AgVAWQgIgJAAgNQAAgMAIgJQAJgIAMAAQANAAAIAIQAJAJAAAMQAAANgJAJQgIAIgNAAQgMAAgJgIgAgNgOQgGAGABAIQgBAJAGAGQAFAGAIAAQAJAAAFgGQAGgGgBgJQABgIgGgGQgFgGgJAAQgIAAgFAGg");
	this.shape_11.setTransform(4.55,22.625);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#40474F").s().p("AgOAQQgGgGAAgKQAAgIAGgHQAGgGAIAAQAKAAAGAGQAFAHAAAJIAAACIgfAAQAAAFAEADQAEAEAEAAQAIAAAEgFIAEAGQgGAGgLAAQgJAAgGgGgAgLgCIAXAAQAAgFgDgDQgDgEgGAAQgKAAgBAMg");
	this.shape_12.setTransform(-1.275,23.425);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#40474F").s().p("AgLAWIAAgqIAKAAIAAAGQAEgHAJAAIAAAJIgDAAQgIAAgCAGIAAAcg");
	this.shape_13.setTransform(-5.025,23.375);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#40474F").s().p("AgNATQgFgEAAgHQAAgNAPAAQAIAAAFAFIAAgFQAAgIgKAAQgHAAgFAFIgEgGQAHgHAKAAQASAAAAAPIAAAbIgJAAIAAgEQgGAFgHAAQgGAAgEgDgAgJAIQAAAIAJAAQAGAAAEgEIAAgHQgEgEgGAAQgJAAAAAHg");
	this.shape_14.setTransform(-9.225,23.425);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#40474F").s().p("AgRAWQgJgJAAgNQAAgMAJgJQAIgIAMAAQAQAAAIANIgJAEQgFgIgKAAQgIAAgFAGQgGAGAAAIQAAAJAGAGQAFAGAIAAQAKAAAFgIIAJAEQgIANgQAAQgMAAgIgIg");
	this.shape_15.setTransform(-14.375,22.625);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#40474F").s().p("AgOAQQgGgGgBgKQAAgIAHgHQAGgGAJAAQAJAAAFAGQAHAHgBAJIAAACIggAAQABAFAEADQAEAEAEAAQAHAAAFgFIAFAGQgHAGgLAAQgIAAgHgGgAgLgCIAYAAQgCgMgKAAQgLAAgBAMg");
	this.shape_16.setTransform(-22.2,23.425);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#40474F").s().p("AAKAdIAAgaQAAgIgJAAQgFAAgEAFIAAAdIgKAAIAAg5IAKAAIAAAWQAFgHAIAAQAOAAAAANIAAAdg");
	this.shape_17.setTransform(-26.95,22.625);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#40474F").s().p("AgFARIAAgYIgIAAIAAgIIAIAAIAAgLIAIAAIAAALIAJAAIAAAIIgJAAIAAAWQAAAEAEAAQABAAAAAAQABAAAAAAQABAAAAAAQABgBAAAAIADAHQgEACgGABQgKAAABgLg");
	this.shape_18.setTransform(-30.85,22.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#40474F").s().p("AgGAeIAAgiIgHAAIAAgIIAHAAIAAgCQAAgPANAAQAFAAACACIgCAHIgEgBQgFAAgBAHIAAACIAJAAIAAAIIgJAAIAAAig");
	this.shape_19.setTransform(-35.75,22.575);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#40474F").s().p("AgPAQQgGgHAAgJQAAgJAGgGQAGgGAJAAQAKAAAGAGQAGAGAAAJQAAAJgGAHQgGAGgKAAQgJAAgGgGgAgIgJQgDAEAAAFQAAAGADAEQADAEAFAAQAMAAAAgOQAAgFgDgEQgDgEgGAAQgFAAgDAEg");
	this.shape_20.setTransform(-39.775,23.425);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#40474F").s().p("AgFARIAAgYIgHAAIAAgIIAHAAIAAgLIAIAAIAAALIAJAAIAAAIIgJAAIAAAWQAAAEAEAAQABAAAAAAQABAAAAAAQABAAAAAAQABgBAAAAIACAHQgCACgGABQgKAAAAgLg");
	this.shape_21.setTransform(-45.975,22.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#40474F").s().p("AgLAWIAAgqIAJAAIAAAGQAGgHAIAAIAAAJIgEAAQgHAAgDAGIAAAcg");
	this.shape_22.setTransform(-48.85,23.375);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#40474F").s().p("AgNATQgFgEAAgHQAAgHAFgCQAEgEAGAAQAIAAAEAFIAAgFQABgIgKAAQgHAAgFAFIgEgGQAHgHAKAAQASAAAAAPIAAAbIgKAAIAAgEQgEAFgIAAQgGAAgEgDgAgJAIQAAAIAJAAQAHAAACgEIAAgHQgCgEgHAAQgJAAAAAHg");
	this.shape_23.setTransform(-52.75,23.425);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#40474F").s().p("AgWAdIAAg5IAZAAQAJAAAGAFQAEAFAAAIQAAAIgEAEQgGAFgJAAIgPAAIAAAWgAgMgBIANAAQALAAgBgJQABgJgLAAIgNAAg");
	this.shape_24.setTransform(-57.1,22.625);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#40474F").s().p("AAIAKIgBgRIgGARIgCAAIgFgRIgBARIgDAAIACgTIADAAIAFAQIAAAAIAFgQIAEAAIACATg");
	this.shape_25.setTransform(68.25,3.275);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#40474F").s().p("AAAAKIAAgRIgHAAIAAgCIAPAAIAAACIgHAAIAAARg");
	this.shape_26.setTransform(66.225,3.275);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#40474F").s().p("AgLAaIAAgjIgMAAIAAgRIAMAAIAAgTIASAAIAAATIAOAAIAAARIgOAAIAAAeQAAAIAGAAQAEAAACgCIAFAOQgGAEgKAAQgTABAAgUg");
	this.shape_27.setTransform(63.25,6.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#40474F").s().p("AgVAaQgLgKAAgQQAAgPALgLQALgKAPAAQATAAAJANIgNALQgFgIgJAAQgIAAgFAGQgGAGAAAIQAAAJAGAGQAFAFAIAAQAIAAAGgHIANALQgKANgSAAQgPAAgLgLg");
	this.shape_28.setTransform(57.3,7.675);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#40474F").s().p("AgYAbQgLgLAAgQQAAgPAKgKQALgLAPAAQAPAAAKALQAKAKAAARIAAAEIgzAAQABAHAFAEQAGAFAHAAQALAAAIgHIAIAMQgLAKgSAAQgPAAgLgKgAgLgQQgEAEAAAGIAhAAQAAgGgEgEQgFgFgIAAQgHAAgFAFg");
	this.shape_29.setTransform(50.025,7.675);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#40474F").s().p("AAPAkIAAgpQAAgOgOAAQgIAAgHAJIAAAuIgSAAIAAhFIASAAIAAAJQAKgLAOAAQAXAAAAAWIAAAxg");
	this.shape_30.setTransform(42.55,7.575);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#40474F").s().p("AAOAkIAAgpQABgOgNAAQgJAAgGAJIAAAuIgTAAIAAhFIATAAIAAAJQAJgLAOAAQAXAAAAAWIAAAxg");
	this.shape_31.setTransform(34.85,7.575);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#40474F").s().p("AgaAaQgKgLAAgPQAAgPAKgKQAKgLAQAAQARAAAKALQAKAKAAAPQAAAPgKALQgKALgRAAQgQAAgKgLgAgMgOQgFAGAAAIQAAAIAFAGQAFAGAHAAQAIAAAFgGQAFgGAAgIQAAgIgFgGQgFgGgIAAQgHAAgFAGg");
	this.shape_32.setTransform(27.225,7.675);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#40474F").s().p("AgeAkQgPgOAAgWQAAgVAPgOQAOgOAVAAQAbAAAOAYIgSAIQgHgOgQAAQgMAAgIAJQgJAJAAANQAAAOAJAJQAIAJAMAAQAQAAAHgOIASAIQgOAYgbAAQgVAAgOgOg");
	this.shape_33.setTransform(18.825,6.325);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#40474F").s().p("AgYAbQgLgLAAgQQAAgPAKgKQALgLAOAAQAQAAAKALQAKALAAAQIAAAEIg0AAQADAQARAAQALAAAHgHIAIAMQgLAKgRAAQgQAAgKgKgAgQgGIAiAAQgBgGgDgEQgFgFgJAAQgOAAgCAPg");
	this.shape_34.setTransform(7.925,7.675);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#40474F").s().p("AgTAkIAAhFIASAAIAAAJQAIgLAOAAIAAASIgGAAQgEAAgFACQgGACgBAEIAAAtg");
	this.shape_35.setTransform(2.25,7.575);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#40474F").s().p("AgYAfQgIgHAAgLQAAgLAIgFQAHgFAKAAQAOAAAHAIIAAgJQAAgMgOAAQgMAAgJAIIgHgMQANgLARAAQAfAAAAAbIAAAsIgTAAIAAgHQgIAJgNAAQgKAAgHgGgAgNAOQAAAEAEADQAEADAFAAQAKAAAEgGIAAgJQgEgGgKAAQgNAAAAALg");
	this.shape_36.setTransform(-4.575,7.675);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#40474F").s().p("AgeAkQgPgOAAgWQAAgVAPgOQAOgOAVAAQAbAAAOAYIgSAIQgHgOgQAAQgMAAgIAJQgJAJAAANQAAAOAJAJQAIAJAMAAQAQAAAHgOIASAIQgOAYgbAAQgVAAgOgOg");
	this.shape_37.setTransform(-12.875,6.325);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#40474F").s().p("AAOAkIAAgpQABgOgNAAQgJAAgHAJIAAAuIgSAAIAAhFIASAAIAAAJQAKgLAOAAQAXAAAAAWIAAAxg");
	this.shape_38.setTransform(-24,7.575);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#40474F").s().p("AgaAaQgKgLAAgPQAAgPAKgKQAKgLAQAAQARAAAKALQAKAKAAAPQAAAPgKALQgKALgRAAQgQAAgKgLgAgNgOQgEAGAAAIQAAAIAEAGQAFAGAIAAQAIAAAFgGQAFgGAAgIQAAgIgFgGQgFgGgIAAQgIAAgFAGg");
	this.shape_39.setTransform(-31.775,7.675);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#40474F").s().p("AgeAaIAIgNQAKAJANAAQAMAAAAgHQAAgFgNgDQgNgCgFgDQgJgFAAgLQAAgJAHgGQAIgHAMAAQAQAAAMAKIgHAMQgHgIgOAAQgKAAAAAHQAAAFAMACQAOADAFADQAKAFAAALQAAAKgIAGQgIAHgPAAQgSAAgMgLg");
	this.shape_40.setTransform(-38.9,7.675);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#40474F").s().p("AALAwIgRgbIgJAJIAAASIgSAAIAAhfIASAAIAAA5IAagfIAXAAIgcAfIAcAmg");
	this.shape_41.setTransform(-45.425,6.325);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#40474F").s().p("AgVAaQgKgKAAgQQAAgPAKgLQALgKAPAAQATAAAIANIgMALQgFgIgJAAQgIAAgFAGQgFAGAAAIQAAAJAFAGQAFAFAIAAQAJAAAFgHIAMALQgJANgSAAQgPAAgLgLg");
	this.shape_42.setTransform(-52.775,7.675);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#40474F").s().p("AgYAfQgIgHAAgLQAAgLAIgFQAHgFAKAAQAOAAAHAIIAAgJQAAgMgOAAQgNAAgIAIIgHgMQANgLARAAQAeAAAAAbIAAAsIgSAAIAAgHQgIAJgNAAQgJAAgIgGgAgNAOQAAAEAEADQAEADAFAAQAJAAAFgGIAAgJQgFgGgJAAQgNAAAAALg");
	this.shape_43.setTransform(-59.9,7.675);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#40474F").s().p("AgdAoIAJgQQAHAHAIAAQAOAAAAgQIAAg/IAVAAIAABAQAAAQgJAJQgKAIgOAAQgRAAgJgJg");
	this.shape_44.setTransform(-66.875,6.425);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#08594C").s().p("AncgNQD9gdDhAAQDdAAD7AdQD1AcAfAbQifgXi8gMQjBgLjNAAQmkAAlOAvQAYgbD5gdg");
	this.shape_45.setTransform(0,-6.075);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#08594C").s().p("AhsBBIADgLIASgMIgOAAIAJgdIAOgJIgKAAIAPgwIAUBDIgPABIARAKIAUgOIgRAAIAMglIARgLIgNAAIATg+IANAqIgKgCIAMAKIAKAkIgTABIAZAOIAKAjIgVgEIAZAUIABACIAEgLIARgLIgOAAIAKgdIANgKIgKABIAPgwIAVBDIgQAAIATAMIARA4g");
	this.shape_46.setTransform(58.9,-12.875);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#08594C").s().p("Ag/AzIAYgTIgTAFIAJggIAXgMIgSgBIAJghIALgIIgJABIAMgmIASA4IgMAAIAPAKIAKAhIgPAAIATANIACAHIACgGIASgLIgPAAIATg8IAOAsIgKgBIAMAIIgBABIAIAZIgMAAIAPAKIAJAYIiVAUg");
	this.shape_47.setTransform(-63.275,-12.15);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#08594C").s().p("Ag1AfIAIgGIgIABIAFgRIAIgFIgGAAIAJgaIALAlIgJAAIALAHIABACIAKgGIgKAAIAGgUIAKgHIgIAAIALgjIAHAYIgFgBIAGAFIAGAUIgKAAIANAJIAEALIADgBIAAAAIAKgHIgIAAIAEgQIAHgFIgGAAIAHgbIAOAjIgJACIAMAFIAIAcIh1AHg");
	this.shape_48.setTransform(-40.525,-10.275);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#7B4C18").s().p("AkWgZIAYgEIAJgrIEQgFIAPAJIA7gBIANgKIBAgBIAMAyIAsAAIB4BUIgygBIhKhAIhpAAIAIgGQAMgIAWgDIgJgfIgoABIgMAKIhFABIgOgKIj0AFIgHAXQAsAAAuALQAWAFAOAFIiiADIgYAiQgYAlgDAKIgmAFQAMgZA/hRg");
	this.shape_49.setTransform(-20.35,-13.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.JCClogo, new cjs.Rectangle(-74.9,-22,149.9,49.3), null);


(lib.HEAD2type = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgRASQgIgHAAgLQAAgKAIgHQAGgHALAAQALAAAHAHQAIAHAAAKQAAALgIAHQgHAHgLAAQgLAAgGgHg");
	this.shape.setTransform(112,56.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAcBCIgbhIIgbBIIghAAIglhkQgCgFgCgCQAAAAgBAAQAAAAAAgBQgBAAgBAAQAAAAgBAAIgHAAIAAgXIBIAAIAAAXIgHAAQgEAAgBADQgBABABAFIAEAMIAIAVIAHATIAHgTIAIgVIAEgMQABgFgBgBQgCgDgDAAIgGAAIAAgXIBDAAIAAAXIgGAAQgEAAgCADQgBABACAFIAEAMIAIAVIAJAUIAHgUIAHgUIAEgNQABgFgCgCQAAAAAAgBQgBAAAAAAQgBgBgBAAQAAAAgBAAIgIAAIAAgXIA2AAIAAAXIgHAAQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAgBAAIgDAHIgjBkg");
	this.shape_1.setTransform(97.475,52.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AglA9QgQgJgJgQQgJgPAAgVQAAgUAJgQQAJgPARgJQAQgJAVAAQAVAAAQAJQAQAJAJAPQAJAQAAAUQAAAVgJAPQgJAQgQAJQgRAIgVABQgVgBgQgIgAgUgiQgGAKAAAXIAAADQAAAWAGAKQAHAKANAAQAOAAAHgKQAHgKgBgWIAAgDQABgXgHgKQgHgKgOAAQgNAAgHAKg");
	this.shape_2.setTransform(78.525,52.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAIBEIAAgYIAIAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAAAQACgCAAgFIAAgzQAAgNgFgFQgEgGgKABQgKgBgGAJQgGAJAAASIAAAnQAAAFABACQABAAAAAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAIAAAYIhIAAIAAgYIAJAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgJAAIAAgYIAaAAIATgBQAIgBAFgBIAAAYQAHgNALgGQAKgGAPAAQAVAAALANQALAMAAAaIAAA0QAAAFACACQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_3.setTransform(62.775,51.975);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgQBNQgLgLABgXIAAhDIgQAAIAAgVIAIgBQAIgBAFgEQAEgEACgIIACgXIAeAAIAAAnIAYAAIAAAXIgZAAIAABDQAAAKAEAEQAEADAIAAIAHAAIAEgCIAAAZIgLADIgPABQgWAAgLgKg");
	this.shape_4.setTransform(43.2,50.425);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgkBfIAAgYIAKAAQAAAAABAAQABAAAAAAQABgBAAAAQAAgBABAAIABgGIAAhBQAAgGgBgCQgCgDgDABIgJAAIAAgYIAbAAIASgBIANgCIAABmQAAAEACACQAAAAAAABQABAAAAABQABAAAAAAQABAAAAAAIAKAAIAAAYgAgRg1QgHgHAAgKQAAgKAHgGQAGgIALABQALgBAHAIQAHAGAAAKQAAAKgHAHQgHAHgLAAQgLAAgGgHg");
	this.shape_5.setTransform(34.725,49.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AghBCQgNgDgJgEIAAgjIAeAAIAAAVIAJACIAMABQAJAAAGgEQAFgEABgHQgBgIgHgEQgIgDgLgCQgMgCgLgFQgKgEgHgHQgGgIgBgOQAAgVAPgMQAQgMAbAAQARAAAOAEQANADAHAEIAAAiIgdAAIAAgUIgIgCIgLgBQgJAAgFAEQgGAEAAAGQAAAGAEADQADADAHABIANADQAMACAKAFQAKAEAIAHQAGAIABAPQgBAVgPAMQgPAMgdABQgRgBgOgDg");
	this.shape_6.setTransform(24.45,52.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgkBfIAAgYIAKAAQAAAAABAAQABAAAAAAQABgBAAAAQAAgBABAAIABgGIAAhBQAAgGgBgCQgCgDgDABIgJAAIAAgYIAbAAIASgBIANgCIAABmQAAAEACACQAAAAAAABQABAAAAABQABAAAAAAQABAAAAAAIAKAAIAAAYgAgRg1QgHgHAAgKQAAgKAHgGQAGgIALABQALgBAHAIQAHAGAAAKQAAAKgHAHQgHAHgLAAQgLAAgGgHg");
	this.shape_7.setTransform(14.125,49.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgPBCIgthkQgCgFgCgCQAAAAgBAAQAAAAAAgBQgBAAgBAAQAAAAgBAAIgIAAIAAgXIBMAAIAAAXIgKAAQgDAAgCADQgBABABAFIAGAPIAJAUIAIAWIAKgYIAJgUIAFgNQABgDgBgDQgCgDgEAAIgKAAIAAgXIA9AAIAAAXIgIAAQgDAAgDABQgCADgCAEIgsBkg");
	this.shape_8.setTransform(2.325,52.25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgzBUQgNgIgHgRQgHgPAAgVQAAgVAHgOQAHgQANgJQANgJASAAQAQAAAJAHQALAFAFAMIAAgjIgBgHQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgLAAIAAgZIAcAAIATAAIANgCIAACWQAAAEACACQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAJAAIAAAXIg1AAIgBgJIgBgOQgFAMgLAIQgKAGgSABQgSAAgNgJgAgZgJQgHAKAAAUIAAAEQAAAVAHAKQAIAKAMAAQALAAAHgKQAIgKAAgVIAAgEQAAgUgIgKQgHgJgLAAIgBAAQgMAAgHAJg");
	this.shape_9.setTransform(-20.125,49.85);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgjBbIAAgXIAKAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBAAAAQABgCAAgEIAAhzIgBgHQAAAAAAAAQgBgBAAAAQgBAAAAAAQgBAAAAAAIgKAAIAAgZIAbAAIASAAIANgCIAACWQAAAEABACQABAAAAABQABAAAAAAQABAAAAAAQAAABABAAIAJAAIAAAXg");
	this.shape_10.setTransform(-32.65,49.65);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgkBfIAAgYIAKAAQAAAAABAAQAAAAABAAQABgBAAAAQAAgBABAAIABgGIAAhBQAAgGgBgCQgCgDgDABIgJAAIAAgYIAbAAIASgBQAIgBAFgBIAABmQAAAEACACQAAAAAAABQABAAAAABQABAAAAAAQABAAAAAAIAKAAIAAAYgAgRg1QgHgHAAgKQAAgKAHgGQAGgIALABQALgBAHAIQAHAGAAAKQAAAKgHAHQgHAHgLAAQgLAAgGgHg");
	this.shape_11.setTransform(-40.725,49.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAJBbIAAgXIAHAAQABAAABgBQAAAAABAAQAAAAAAAAQABgBAAAAQABgCAAgEIAAg0QAAgMgEgGQgEgFgKAAQgKAAgHAJQgFAIgBASIAAAoQAAAEACACQAAAAABABQAAAAAAAAQABAAAAAAQABABABAAIAIAAIAAAXIhIAAIAAgXIAJAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQACgCAAgEIAAhzIgBgHQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAIgKAAIAAgZIAbAAIATAAIANgCIAABGQAHgMAKgFQALgHAPAAQAVAAALANQALAMAAAZIAAA2QAAAEABACQAAAAABABQAAAAABAAQAAAAABAAQAAABABAAIAKAAIAAAXg");
	this.shape_12.setTransform(-53,49.65);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgvAzQgTgSAAghQAAggATgSQATgTAiAAQAdAAAQAMQAQAMAAAVQAAAOgHAIQgHAIgNAAQgLAAgGgGQgGgFAAgJQAAgJAEgGQAFgFAJgCQgDgFgGgCQgGgCgJAAQgPAAgJAKQgIALAAAVIAAAEQAAAVAIAKQAIALAPAAQAMAAAIgGQAIgGAFgLIAXAMQgGAQgOALQgPAKgZABQgigBgTgSg");
	this.shape_13.setTransform(-68.125,52.175);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgjAOIAAgbIBHAAIAAAbg");
	this.shape_14.setTransform(-79.475,52.15);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgjBbIAAgXIAJAAQABAAABgBQAAAAABAAQAAAAABAAQAAgBAAAAQACgCAAgEIAAhzIgCgHQAAAAAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAIgJAAIAAgZIAbAAIARAAIAOgCIAACWQAAAEACACQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAIAAIAAAXg");
	this.shape_15.setTransform(-87.8,49.65);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgjBbIAAgXIAJAAQABAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQAAgCAAgEIAAhzIAAgHQgBAAAAAAQAAgBgBAAQAAAAgBAAQgBAAgBAAIgKAAIAAgZIAbAAIASAAIAOgCIAACWQAAAEABACQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAIAAIAAAXg");
	this.shape_16.setTransform(-95.95,49.65);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgjA8QgQgIgIgQQgIgQAAgUQAAgUAJgQQAIgPAQgJQAQgJAUAAQAhAAAQATQARATAAAhIAAAGIhZAAQAAARAJAJQAIAJAPAAQAOAAAHgGQAIgGAEgKIAXANQgEAKgJAIQgHAIgNAFQgMAEgRABQgXgBgRgJgAAZgMQAAgSgFgHQgHgIgKAAQgLAAgHAIQgGAIgBARIAvAAIAAAAg");
	this.shape_17.setTransform(-107.2,52.175);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAcBCIgbhIIgbBIIghAAIglhkQgCgFgCgCQAAAAgBAAQAAAAAAgBQgBAAgBAAQAAAAgBAAIgHAAIAAgXIBIAAIAAAXIgHAAQgEAAgBADQgBABABAFIAEAMIAIAVIAHATIAHgTIAIgVIAEgMQABgFgBgBQgCgDgDAAIgGAAIAAgXIBDAAIAAAXIgGAAQgEAAgCADQgBABACAFIAEAMIAIAVIAJAUIAHgUIAHgUIAEgNQABgFgCgCQAAAAAAgBQgBAAAAAAQgBgBgBAAQAAAAgBAAIgIAAIAAgXIA2AAIAAAXIgHAAQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAgBAAIgDAHIgjBkg");
	this.shape_18.setTransform(-125.725,52.25);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag8A7QgLgJAAgQQAAgRAMgKQAMgJATgFQAUgFAWgEIAAgHQAAgMgGgFQgGgFgLAAIgIAAIgGABQACADAAADIABAHQAAAJgGAGQgHAFgKAAQgLAAgHgFQgGgGAAgLQAAgNAIgHQAIgIAPgEQAOgEAUAAQAgAAAOALQAPAKAAAZIAAA5IABAGQAAABAAAAQABABAAAAQABAAAAAAQABAAAAAAIAJAAIAAAYIgwAAIgGgKQgCgFgCgHQgDAIgHAFQgGAGgJADQgJADgLABQgTgBgKgKgAgRAKQgLAFgBAMQAAAIAFAEQAEAEAHAAQANAAAHgIQAHgJAAgPIAAgJQgTACgMAGg");
	this.shape_19.setTransform(-6.625,21.9239);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgjA8QgQgIgIgQQgIgQAAgUQAAgUAIgQQAJgPAQgJQAQgJAUAAQAhAAARATQAQATAAAhIAAAGIhaAAQABARAIAJQAJAJAPAAQANAAAIgGQAIgGAEgKIAXANQgEAKgJAIQgIAIgLAFQgNAEgRABQgYgBgQgJgAAZgMQgBgSgFgHQgFgIgMAAQgLAAgGAIQgGAIgBARIAvAAIAAAAg");
	this.shape_20.setTransform(-27.95,21.925);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgjBbIAAgXIAJAAQABAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQABgBAAgFIAAhyIgBgIQgBAAAAAAQAAgBgBAAQAAAAgBAAQgBAAgBAAIgKAAIAAgZIAbAAIASAAIAOgCIAACWQAAAFABABQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAIAAIAAAXg");
	this.shape_21.setTransform(-39.35,19.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("Ag2A3QgLgMAAgaIAAg0QAAgFgBgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAAAAAIgKAAIAAgYIA7AAIAABUQAAAMAFAFQAEAGAJgBQALAAAFgIQAHgIgBgRIAAgpQAAgFgBgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgMAAIAAgYIA+AAIAABiIABAHQAAABABAAQAAAAAAABQABAAAAAAQABAAAAAAIAMAAIAAAYIgcAAIgUABIgNACIAAgXQgGAMgLAGQgKAGgPAAQgVAAgLgNg");
	this.shape_22.setTransform(-51.55,22.125);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgzBUQgNgJgHgPQgHgQAAgVQAAgVAHgOQAHgQANgJQANgJASAAQAQAAAJAHQALAFAFAMIAAgiIgBgIQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgLAAIAAgZIAcAAIATAAIANgCIAACWQAAAFACABQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAJAAIAAAXIg1AAIgBgJIgBgOQgFAMgLAIQgKAGgSABQgSAAgNgJgAgZgJQgHAKAAAUIAAAEQAAAVAHAKQAIAKAMAAQALAAAHgKQAIgKAAgVIAAgEQAAgUgIgKQgHgKgLABIgBAAQgMAAgHAJg");
	this.shape_23.setTransform(-67.925,19.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgjA8QgQgIgIgQQgIgQAAgUQAAgUAJgQQAIgPAQgJQAQgJAUAAQAhAAARATQAQATAAAhIAAAGIhZAAQAAARAJAJQAIAJAPAAQAOAAAHgGQAIgGAEgKIAXANQgEAKgJAIQgHAIgNAFQgMAEgRABQgYgBgQgJgAAZgMQAAgSgGgHQgFgIgMAAQgKAAgHAIQgGAIgBARIAvAAIAAAAg");
	this.shape_24.setTransform(-83.55,21.925);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAIBbIAAgXIAIAAQABAAABgBQAAAAABAAQAAAAAAAAQABgBAAAAQABgBABgFIAAg0QgBgLgEgGQgEgGgKAAQgLAAgFAJQgHAHAAATIAAAoQABAFABABQAAAAABABQAAAAAAAAQABAAAAAAQABABABAAIAIAAIAAAXIhIAAIAAgXIAJAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQACgBAAgFIAAhyIgBgIQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgKAAIAAgZIAbAAIATAAIANgCIAABGQAHgMAKgFQAKgHAQAAQAVAAALANQALAMAAAZIAAA2QAAAFABABQAAAAABABQAAAAABAAQAAAAABAAQAAABABAAIAJAAIAAAXg");
	this.shape_25.setTransform(-99,19.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgvAzQgTgSAAghQAAggATgSQATgTAiAAQAdAAAQAMQAQAMAAAVQAAAOgHAIQgHAIgNAAQgLAAgGgGQgGgFAAgJQAAgJAEgGQAFgFAJgCQgDgFgGgCQgGgCgJAAQgPAAgJAKQgIALAAAVIAAAEQAAAVAIAKQAIALAPAAQAMAAAIgGQAIgGAFgLIAXAMQgGAQgOALQgPAKgZABQgigBgTgSg");
	this.shape_26.setTransform(-114.125,21.925);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgnBZQgRgDgNgIIAAgrIAkAAIAAAcIAPADIAQABQALABAIgGQAIgFABgLQgBgIgEgFQgEgEgKgDIgWgGQgRgEgMgHQgMgGgHgJQgGgLgBgQQABgcASgQQAUgQAiAAQATAAAOAEQAPADANAGIAAAsIgkAAIAAgbIgLgCIgNgBQgOAAgIAGQgHAFgBALQAAAHAFAEQAEAFAIADIAVAFQAQAEANAGQANAGAIAJQAJALAAARQAAATgJANQgIAOgRAGQgQAIgXAAQgUAAgRgEg");
	this.shape_27.setTransform(-129.1,19.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2type, new cjs.Rectangle(-139,0,278,68.5), null);


(lib.HEAD1btype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSASQgHgHAAgLQAAgKAHgHQAHgHALAAQALAAAHAHQAIAHAAAKQAAALgIAHQgHAHgLAAQgLAAgHgHg");
	this.shape.setTransform(-9.4,56.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhCBTQgLgIAAgPQAAgLAGgHQAHgHALAAQAJAAAFAFQAGAEABAHQABAIgEAJQAIgCAGgHQAFgHAEgMIAAgBIguhiIgEgGQAAgBgBAAQAAAAgBAAQAAgBgBAAQgBAAAAAAIgIAAIAAgXIBKAAIAAAXIgHAAQgEAAgBADQgBADABADIAYA2IAVg1QACgFgCgCQgCgDgEAAIgIAAIAAgXIA7AAIAAAXIgJAAQgDAAgCACIgEAGIgoBgQgHASgHAMQgHAMgLAGQgKAGgQAAQgSAAgKgIg");
	this.shape_1.setTransform(-20.525,54.725);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgzBUQgNgIgHgRQgHgPAAgVQAAgVAHgOQAHgQANgJQANgJASAAQAQAAAJAHQALAFAFAMIAAgjIgBgHQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAIgLAAIAAgZIAcAAIATAAIANgCIAACWQAAAEACACQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAJAAIAAAXIg1AAIgBgJIgBgOQgFAMgLAIQgKAGgSABQgSAAgNgJgAgZgJQgHAKAAAUIAAAEQAAAVAHAKQAIAKAMAAQALAAAHgKQAIgKAAgVIAAgEQAAgUgIgKQgHgJgLAAIgBAAQgMAAgHAJg");
	this.shape_2.setTransform(-36.375,49.85);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag8A7QgLgJAAgQQAAgRAMgKQAMgJATgFQAUgFAWgEIAAgHQAAgMgGgFQgGgFgLAAIgIAAIgGABQACADAAADIABAHQAAAJgGAGQgHAFgKAAQgLAAgHgFQgGgGAAgLQAAgNAIgHQAIgIAPgEQAOgEAUAAQAgAAAOALQAPAKAAAZIAAA5IABAGQAAABAAAAQABABAAAAQABAAAAAAQABAAAAAAIAJAAIAAAYIgwAAIgGgKQgCgFgCgHQgDAIgHAFQgGAGgJADQgJADgLABQgTgBgKgKgAgRAKQgLAFgBAMQAAAIAFAEQAEAEAHAAQANAAAHgIQAHgJAAgPIAAgJQgTACgMAGg");
	this.shape_3.setTransform(-52.175,52.1739);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgjA8QgQgIgIgQQgIgQAAgUQAAgUAJgQQAIgPAQgJQAQgJAUAAQAhAAAQATQARATAAAhIAAAGIhZAAQAAARAJAJQAIAJAPAAQAOAAAHgGQAIgGAEgKIAXANQgEAKgJAIQgHAIgNAFQgMAEgRABQgXgBgRgJgAAZgMQAAgSgFgHQgHgIgKAAQgLAAgHAIQgGAIgBARIAvAAIAAAAg");
	this.shape_4.setTransform(-67.15,52.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag+BEIAAgYIAJAAQABAAAAAAQABAAABAAQAAAAAAgBQABAAAAAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgKAAIAAgYIAbAAIATgBIAOgCIAAAdQADgQAJgHQAJgHANAAQAPAAAJAKQAJAKAAAQQAAAPgIAIQgHAIgNAAQgJAAgGgFQgFgFgBgJQAAgFAEgFQADgFAFgDIgDgCIgFAAQgLAAgGAKQgFAKAAATIAAAkQAAAFABACQABAAAAAAQAAABABAAQAAAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_5.setTransform(-80.975,51.975);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgjA8QgQgIgIgQQgIgQAAgUQAAgUAIgQQAJgPAQgJQAQgJAUAAQAhAAARATQAQATAAAhIAAAGIhaAAQABARAIAJQAJAJAPAAQANAAAIgGQAIgGAEgKIAXANQgEAKgJAIQgIAIgLAFQgNAEgRABQgYgBgQgJgAAZgMQgBgSgFgHQgFgIgMAAQgLAAgGAIQgGAIgBARIAvAAIAAAAg");
	this.shape_6.setTransform(-101.3,52.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag+BEIAAgYIAJAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgKAAIAAgYIAbAAIATgBQAJgBAFgBIAAAdQADgQAJgHQAJgHANAAQAPAAAJAKQAJAKAAAQQAAAPgIAIQgHAIgNAAQgJAAgGgFQgFgFgBgJQAAgFAEgFQADgFAFgDIgDgCIgFAAQgLAAgGAKQgFAKAAATIAAAkQAAAFABACQABAAAAAAQABABAAAAQAAAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_7.setTransform(-115.125,51.975);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag8A7QgLgJAAgQQAAgRAMgKQAMgJATgFQAUgFAWgEIAAgHQAAgMgGgFQgGgFgLAAIgIAAIgGABQACADAAADIABAHQAAAJgGAGQgHAFgKAAQgLAAgHgFQgGgGAAgLQAAgNAIgHQAIgIAPgEQAOgEAUAAQAgAAAOALQAPAKAAAZIAAA5IABAGQAAABAAAAQABABAAAAQABAAAAAAQABAAAAAAIAJAAIAAAYIgwAAIgGgKQgCgFgCgHQgDAIgHAFQgGAGgJADQgJADgLABQgTgBgKgKgAgRAKQgLAFgBAMQAAAIAFAEQAEAEAHAAQANAAAHgIQAHgJAAgPIAAgJQgTACgMAGg");
	this.shape_8.setTransform(-129.275,52.1739);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AggBCQgOgDgKgEIAAgjIAfAAIAAAVIAJACIAMABQAKAAAFgEQAFgEABgHQgBgIgHgEQgIgDgMgCQgLgCgKgFQgLgEgHgHQgGgIgBgOQAAgVAQgMQAPgMAbAAQARAAAOAEQANADAHAEIAAAiIgdAAIAAgUIgIgCIgLgBQgJAAgGAEQgFAEAAAGQAAAGAEADQADADAHABIANADQAMACAKAFQAKAEAIAHQAGAIABAPQAAAVgQAMQgPAMgdABQgQgBgOgDg");
	this.shape_9.setTransform(115.9,21.925);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgzBUQgNgJgHgPQgHgQAAgVQAAgVAHgOQAHgQANgJQANgJASAAQAQAAAJAHQALAFAFAMIAAgiIgBgIQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAIgLAAIAAgZIAcAAIATAAIANgCIAACWQAAAFACABQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAJAAIAAAXIg1AAIgBgJIgBgOQgFAMgLAIQgKAGgSABQgSAAgNgJgAgZgJQgHAKAAAUIAAAEQAAAVAHAKQAIAKAMAAQALAAAHgKQAIgKAAgVIAAgEQAAgUgIgKQgHgKgLABIgBAAQgMAAgHAJg");
	this.shape_10.setTransform(101.425,19.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgkBfIAAgYIAKAAQAAAAABAAQABAAAAgBQABAAAAAAQAAgBABAAIABgGIAAhAQAAgHgBgCQgCgCgDAAIgJAAIAAgYIAbAAIASgBQAIgBAFgBIAABmQAAAEACACQAAAAAAABQABAAAAAAQABABAAAAQABAAAAAAIAKAAIAAAYgAgRg1QgHgGAAgLQAAgKAHgHQAGgGALAAQALAAAHAGQAHAHAAAKQAAALgHAGQgHAGgLABQgLgBgGgGg");
	this.shape_11.setTransform(88.975,19.05);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAHBbIAAgXIAHAAQABgBABAAQAAAAAAAAQABgBAAAAQAAAAAAgBIgBgEIgQgcIgTASIAAAJQABAFABABQAAAAABABQAAAAAAAAQABAAAAAAQABABABAAIAIAAIAAAXIhIAAIAAgXIAJAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQACgBAAgFIAAhyIgBgIQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgKAAIAAgZIAbAAIATAAIANgCIAAByIAkghQABgBAAAAQAAgBAAAAQABgBAAAAQAAgBgBgBQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAgBAAIgMAAIAAgXIBJAAIAAAXIgKAAQgEAAgDABIgFAEIgWASIAiA3QACADACABIAEACIAGAAIAAAXg");
	this.shape_12.setTransform(76.85,19.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag+BEIAAgYIAJAAQABAAAAAAQABAAABAAQAAAAAAgBQABAAAAAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgKAAIAAgYIAbAAIATgBIAOgCIAAAdQADgQAJgHQAJgHANAAQAPAAAJAKQAJAKAAAQQAAAPgIAIQgHAIgNAAQgJAAgGgFQgFgFgBgJQAAgFAEgFQADgFAFgDIgDgCIgFAAQgLAAgGAKQgFAKAAATIAAAkQAAAFABACQABAAAAAAQAAABABAAQAAAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_13.setTransform(55.825,21.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ag2A3QgLgMAAgaIAAg0QAAgFgBgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgKAAIAAgYIA8AAIAABUQAAAMAEAFQAFAGAKgBQAJAAAHgIQAFgIAAgRIAAgpQABgFgCgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgMAAIAAgYIA+AAIAABiIABAHQAAABABAAQAAAAAAABQABAAAAAAQABAAABAAIALAAIAAAYIgcAAIgTABIgOACIAAgXQgGAMgLAGQgKAGgPAAQgVAAgLgNg");
	this.shape_14.setTransform(40.9,22.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AglA9QgQgJgJgQQgJgPAAgVQAAgUAJgQQAJgPARgJQAQgJAVAAQAVAAAQAJQAQAJAJAPQAJAQAAAUQAAAVgJAPQgJAQgQAJQgRAIgVABQgVgBgQgIgAgUgiQgGAKAAAXIAAADQAAAWAGAKQAHAKANAAQAOAAAHgKQAHgKgBgWIAAgDQABgXgHgKQgHgKgOAAQgNAAgHAKg");
	this.shape_15.setTransform(25.075,21.925);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhCBTQgLgIAAgPQAAgLAGgHQAHgHALAAQAJAAAFAFQAGAEABAHQABAIgEAJQAIgCAGgHQAFgHAEgMIAAgBIguhiIgEgGQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgIAAIAAgXIBKAAIAAAXIgHAAQgEAAgBADQgBADABADIAYA2IAVg1QACgFgCgCQgCgDgEAAIgIAAIAAgXIA7AAIAAAXIgJAAQgDAAgCACIgEAGIgoBgQgHASgHAMQgHAMgLAGQgKAGgQAAQgSAAgKgIg");
	this.shape_16.setTransform(9.575,24.475);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgjA8QgQgIgIgQQgIgQAAgUQAAgUAIgQQAKgPAPgJQAQgJAUAAQAhAAARATQAQATAAAhIAAAGIhZAAQAAARAJAJQAIAJAPAAQAOAAAHgGQAIgGAEgKIAXANQgEAKgJAIQgHAIgMAFQgNAEgRABQgYgBgQgJgAAZgMQAAgSgGgHQgFgIgMAAQgLAAgGAIQgGAIgBARIAvAAIAAAAg");
	this.shape_17.setTransform(-11.65,21.925);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag+BEIAAgYIAJAAQABAAAAAAQABAAABAAQAAAAAAgBQABAAAAAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgKAAIAAgYIAbAAIATgBQAJgBAFgBIAAAdQADgQAJgHQAJgHANAAQAPAAAJAKQAJAKAAAQQAAAPgIAIQgHAIgNAAQgJAAgGgFQgFgFgBgJQAAgFAEgFQADgFAFgDIgDgCIgFAAQgLAAgGAKQgFAKAAATIAAAkQAAAFABACQABAAAAAAQAAABABAAQAAAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_18.setTransform(-25.475,21.725);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag2A3QgLgMAAgaIAAg0QAAgFgBgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAAAAAIgKAAIAAgYIA7AAIAABUQAAAMAFAFQAEAGAJgBQALAAAFgIQAHgIAAgRIAAgpQgBgFgBgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgMAAIAAgYIA+AAIAABiIABAHQAAABABAAQAAAAAAABQABAAAAAAQABAAAAAAIAMAAIAAAYIgdAAIgTABIgMACIAAgXQgHAMgLAGQgKAGgPAAQgVAAgLgNg");
	this.shape_19.setTransform(-40.4,22.125);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AghBCQgNgDgJgEIAAgjIAeAAIAAAVIAJACIAMABQAJAAAGgEQAFgEABgHQgBgIgHgEQgIgDgLgCQgMgCgLgFQgKgEgHgHQgGgIgBgOQAAgVAPgMQAQgMAbAAQARAAAOAEQANADAHAEIAAAiIgdAAIAAgUIgIgCIgLgBQgJAAgFAEQgGAEAAAGQAAAGAEADQADADAHABIANADQAMACAKAFQAKAEAIAHQAGAIABAPQgBAVgPAMQgPAMgdABQgRgBgOgDg");
	this.shape_20.setTransform(-54.75,21.925);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgiA8QgRgIgIgQQgIgQAAgUQAAgUAIgQQAKgPAPgJQAQgJAUAAQAhAAAQATQARATAAAhIAAAGIhaAAQABARAIAJQAJAJAPAAQANAAAIgGQAIgGAEgKIAXANQgFAKgHAIQgJAIgMAFQgMAEgRABQgXgBgQgJgAAZgMQgBgSgEgHQgHgIgKAAQgLAAgHAIQgGAIgBARIAvAAIAAAAg");
	this.shape_21.setTransform(-74.6,21.925);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAHBbIAAgXIAHAAQABgBABAAQAAAAABAAQAAgBAAAAQAAAAABgBIgCgEIgQgcIgTASIAAAJQAAAFACABQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIAJAAIAAAXIhIAAIAAgXIAJAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQACgBAAgFIAAhyIgBgIQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAIgKAAIAAgZIAbAAIATAAIANgCIAAByIAkghQAAgBABAAQAAgBAAAAQABgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBAAQgBgBAAAAQgBAAgBAAIgMAAIAAgXIBJAAIAAAXIgKAAQgEAAgDABIgFAEIgWASIAiA3QACADACABIAEACIAGAAIAAAXg");
	this.shape_22.setTransform(-89.9,19.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("Ag8A7QgLgJAAgQQAAgRAMgKQAMgJATgFQAUgFAWgEIAAgHQAAgMgGgFQgGgFgLAAIgIAAIgGABQACADAAADIABAHQAAAJgGAGQgHAFgKAAQgLAAgHgFQgGgGAAgLQAAgNAIgHQAIgIAPgEQAOgEAUAAQAgAAAOALQAPAKAAAZIAAA5IABAGQAAABAAAAQABABAAAAQABAAAAAAQABAAAAAAIAJAAIAAAYIgwAAIgGgKQgCgFgCgHQgDAIgHAFQgGAGgJADQgJADgLABQgTgBgKgKgAgRAKQgLAFgBAMQAAAIAFAEQAEAEAHAAQANAAAHgIQAHgJAAgPIAAgJQgTACgMAGg");
	this.shape_23.setTransform(-105.425,21.9239);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAjBaIAAgYIALAAQABAAABAAQAAAAABAAQAAgBABAAQAAAAABgBQABgCAAgFIAAhyIgxCTIgbAAIgsiRIAABwIABAHQAAABABAAQAAAAABABQAAAAABAAQABAAAAAAIANAAIAAAYIhBAAIAAgYIAOAAQAAAAABAAQABAAAAAAQABgBAAAAQABAAAAgBQABgCAAgFIAAhxQAAgFgBgCQAAgBgBAAQAAAAgBAAQAAgBgBAAQgBAAAAAAIgOAAIAAgYIBVAAIAeBmIAihmIBSAAIAAAYIgMAAQgBAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBABQgBACAAAFIAABxQAAAFABACQABABAAAAQABAAAAABQABAAAAAAQABAAABAAIAMAAIAAAYg");
	this.shape_24.setTransform(-125.05,19.525);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1btype, new cjs.Rectangle(-139,0,278,68.5), null);


(lib.HEAD1atype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSASQgGgHgBgLQABgKAGgHQAHgHALAAQAMAAAGAHQAIAHAAAKQAAALgIAHQgGAHgMAAQgLAAgHgHg");
	this.shape.setTransform(-44.85,56.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAHBbIAAgXIAHAAQABgBABAAQAAAAABAAQAAgBAAAAQAAAAABgBIgCgEIgQgcIgTASIAAAJQAAAEACACQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIAJAAIAAAXIhIAAIAAgXIAJAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQACgCAAgEIAAhzIgBgHQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAIgKAAIAAgZIAbAAIATAAIANgCIAAByIAkghQAAAAABgBQAAgBAAAAQABgBAAAAQAAgBAAAAQgBgBAAgBQAAAAgBAAQgBgBAAAAQgBAAgBAAIgMAAIAAgXIBJAAIAAAXIgKAAQgEAAgDABIgFAEIgWASIAiA2QACAEACABIAEACIAGAAIAAAXg");
	this.shape_1.setTransform(-56.15,49.65);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgvAzQgTgSAAghQAAggATgSQATgTAiAAQAdAAAQAMQAQAMAAAVQAAAOgHAIQgHAIgNAAQgLAAgGgGQgGgFAAgJQAAgJAEgGQAFgFAJgCQgDgFgGgCQgGgCgJAAQgPAAgJAKQgIALAAAVIAAAEQAAAVAIAKQAIALAPAAQAMAAAIgGQAIgGAFgLIAXAMQgGAQgOALQgPAKgZABQgigBgTgSg");
	this.shape_2.setTransform(-71.175,52.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag8A7QgLgJAAgQQAAgRAMgKQAMgJATgFQAUgFAWgEIAAgHQAAgMgGgFQgGgFgLAAIgIAAIgGABQACADAAADIABAHQAAAJgGAGQgHAFgKAAQgLAAgHgFQgGgGAAgLQAAgNAIgHQAIgIAPgEQAOgEAUAAQAgAAAOALQAPAKAAAZIAAA5IABAGQAAABAAAAQABABAAAAQABAAAAAAQABAAAAAAIAJAAIAAAYIgwAAIgGgKQgCgFgCgHQgDAIgHAFQgGAGgJADQgJADgLABQgTgBgKgKgAgRAKQgLAFgBAMQAAAIAFAEQAEAEAHAAQANAAAHgIQAHgJAAgPIAAgJQgTACgMAGg");
	this.shape_3.setTransform(-85.775,52.1739);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgJBUQgNgJgEgPIgHAdIggAAIAAgGIABgOIAAgZIAAhlIgBgHQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAIgKAAIAAgZIAbAAIATAAIANgCIAABJQAGgMALgIQAKgHAQAAQASAAANAJQAMAIAHARQAHAOAAAVQAAAVgHAPQgIARgMAIQgOAJgSAAQgTAAgLgJgAgMgJQgIAJAAAVIAAAEQAAAVAIAKQAHAKALAAQANAAAHgKQAIgKgBgVIAAgEQABgUgIgKQgHgJgNAAIgBAAQgKAAgHAJg");
	this.shape_4.setTransform(-101.95,49.85);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AggBCQgOgDgKgEIAAgjIAfAAIAAAVIAJACIAMABQAKAAAFgEQAFgEABgHQgBgIgHgEQgIgDgMgCQgLgCgKgFQgLgEgHgHQgGgIgBgOQAAgVAQgMQAPgMAbAAQARAAAOAEQANADAHAEIAAAiIgdAAIAAgUIgIgCIgLgBQgJAAgGAEQgFAEAAAGQAAAGAEADQADADAHABIANADQAMACAKAFQAKAEAIAHQAGAIABAPQAAAVgQAMQgPAMgdABQgQgBgOgDg");
	this.shape_5.setTransform(-122.6,52.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgkBfIAAgYIAKAAQAAAAABAAQABAAAAAAQAAgBABAAQAAgBABAAIABgGIAAhBQAAgGgBgCQgCgDgDABIgJAAIAAgYIAbAAIASgBIANgCIAABmQAAAEACACQAAAAAAABQABAAAAABQABAAAAAAQABAAAAAAIAKAAIAAAYgAgRg1QgHgHAAgKQAAgKAHgGQAGgIALABQALgBAHAIQAHAGAAAKQAAAKgHAHQgHAHgLAAQgLAAgGgHg");
	this.shape_6.setTransform(-132.925,49.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgjBbIAAgXIAJAAQABAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQABgBAAgFIAAhyIgBgIQgBAAAAAAQAAgBgBAAQAAAAgBAAQgBAAgBAAIgKAAIAAgZIAbAAIASAAIAOgCIAACWQAAAFABABQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAIAAIAAAXg");
	this.shape_7.setTransform(69.55,19.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AglA9QgQgJgJgQQgJgPAAgVQAAgUAJgQQAJgPARgJQAQgJAVAAQAVAAAQAJQAQAJAJAPQAJAQAAAUQAAAVgJAPQgJAQgQAJQgRAIgVABQgVgBgQgIgAgUgiQgGAKAAAXIAAADQAAAWAGAKQAHAKANAAQAOAAAHgKQAHgKgBgWIAAgDQABgXgHgKQgHgKgOAAQgNAAgHAKg");
	this.shape_8.setTransform(57.875,21.925);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AglA9QgQgJgJgQQgJgPAAgVQAAgUAJgQQAJgPARgJQAQgJAVAAQAVAAAQAJQAQAJAJAPQAJAQAAAUQAAAVgJAPQgJAQgQAJQgRAIgVABQgVgBgQgIgAgUgiQgGAKAAAXIAAADQAAAWAGAKQAHAKANAAQAOAAAHgKQAHgKgBgWIAAgDQABgXgHgKQgHgKgOAAQgNAAgHAKg");
	this.shape_9.setTransform(42.575,21.925);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAJBbIAAgXIAIAAQAAAAABgBQAAAAABAAQAAAAAAAAQABgBAAAAQACgBgBgFIAAg0QAAgLgEgGQgFgGgJAAQgKAAgHAJQgFAHgBATIAAAoQAAAFACABQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIAJAAIAAAXIhIAAIAAgXIAJAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQACgBAAgFIAAhyIgBgIQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAIgKAAIAAgZIAbAAIATAAIANgCIAABGQAHgMAKgFQALgHAPAAQAVAAALANQALAMAAAZIAAA2QAAAFABABQAAAAABABQAAAAABAAQAAAAABAAQAAABABAAIAKAAIAAAXg");
	this.shape_10.setTransform(26.75,19.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgvAzQgTgSAAghQAAggATgSQATgTAiAAQAdAAAQAMQAQAMAAAVQAAAOgHAIQgHAIgNAAQgLAAgGgGQgGgFAAgJQAAgJAEgGQAFgFAJgCQgDgFgGgCQgGgCgJAAQgPAAgJAKQgIALAAAVIAAAEQAAAVAIAKQAIALAPAAQAMAAAIgGQAIgGAFgLIAXAMQgGAQgOALQgPAKgZABQgigBgTgSg");
	this.shape_11.setTransform(11.625,21.925);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AghBCQgOgDgIgEIAAgjIAeAAIAAAVIAJACIAMABQAJAAAGgEQAFgEABgHQgBgIgHgEQgIgDgLgCQgMgCgLgFQgKgEgHgHQgHgIAAgOQAAgVAPgMQAQgMAbAAQARAAAOAEQANADAIAEIAAAiIgeAAIAAgUIgIgCIgLgBQgJAAgFAEQgGAEAAAGQAAAGAEADQADADAHABIANADQALACALAFQAKAEAIAHQAGAIABAPQgBAVgPAMQgQAMgcABQgRgBgOgDg");
	this.shape_12.setTransform(-1.75,21.925);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAIBEIAAgYIAIAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAAAQACgCAAgFIAAgzQAAgNgFgFQgEgGgKABQgKgBgGAJQgGAJAAASIAAAnQAAAFABACQABAAAAAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAIAAAYIhIAAIAAgYIAJAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgJAAIAAgYIAaAAIATgBQAIgBAFgBIAAAYQAHgNALgGQAKgGAPAAQAVAAALANQALAMAAAaIAAA0QAAAFACACQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_13.setTransform(-22.475,21.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AglA9QgQgJgJgQQgJgPAAgVQAAgUAJgQQAJgPARgJQAQgJAVAAQAVAAAQAJQAQAJAJAPQAJAQAAAUQAAAVgJAPQgJAQgQAJQgRAIgVABQgVgBgQgIgAgUgiQgGAKAAAXIAAADQAAAWAGAKQAHAKANAAQAOAAAHgKQAHgKgBgWIAAgDQABgXgHgKQgHgKgOAAQgNAAgHAKg");
	this.shape_14.setTransform(-38.525,21.925);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AghBCQgOgDgIgEIAAgjIAeAAIAAAVIAJACIAMABQAKAAAFgEQAFgEABgHQAAgIgIgEQgIgDgLgCQgMgCgLgFQgKgEgHgHQgHgIAAgOQAAgVAPgMQAQgMAbAAQARAAANAEQAOADAIAEIAAAiIgfAAIAAgUIgIgCIgKgBQgJAAgFAEQgGAEAAAGQAAAGADADQAEADAGABIAOADQALACALAFQALAEAGAHQAIAIAAAPQAAAVgQAMQgQAMgcABQgQgBgPgDg");
	this.shape_15.setTransform(-52.35,21.925);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag+BEIAAgYIAJAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgKAAIAAgYIAbAAIATgBQAJgBAFgBIAAAdQADgQAJgHQAJgHANAAQAPAAAJAKQAJAKAAAQQAAAPgIAIQgHAIgNAAQgJAAgGgFQgFgFgBgJQAAgFAEgFQADgFAFgDIgDgCIgFAAQgLAAgGAKQgFAKAAATIAAAkQAAAFABACQABAAAAAAQABABAAAAQAAAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_16.setTransform(-65.175,21.725);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgjA8QgQgIgIgQQgIgQAAgUQAAgUAIgQQAKgPAPgJQAQgJAUAAQAhAAARATQAQATAAAhIAAAGIhZAAQAAARAJAJQAIAJAPAAQAOAAAHgGQAIgGAEgKIAXANQgEAKgJAIQgHAIgMAFQgNAEgRABQgYgBgQgJgAAZgMQAAgSgGgHQgFgIgMAAQgLAAgGAIQgGAIgBARIAvAAIAAAAg");
	this.shape_17.setTransform(-79.15,21.925);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhOBbIAAgYIAJAAQABAAAAAAQABAAAAAAQABAAAAAAQAAgBABAAQABgCAAgFIAAhwQAAgGgBgBQAAgBAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAIgKAAIAAgYIAbAAIATgBIANgCIAAAcQAGgOALgIQAKgHARAAQARAAANAJQAMAIAHAQQAHAQAAAUQAAAVgHAPQgHAQgOAIQgNAJgRAAQgQAAgKgHQgKgGgFgNIAAAlQAAAFABACQAAAAABABQAAAAABAAQAAAAABAAQAAAAABAAIAKAAIAAAYgAAaALQAHgJAAgUIAAgFQAAgUgHgJQgHgKgMAAQgMAAgHAKQgHAJAAAUIAAAFQAAAUAHAJQAHAJAMAAQAMAAAHgJg");
	this.shape_18.setTransform(-94.875,24.05);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgjAOIAAgbIBHAAIAAAbg");
	this.shape_19.setTransform(-107.225,21.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAIBEIAAgYIAIAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAAAQACgCAAgFIAAgzQAAgNgFgFQgEgGgKABQgKgBgGAJQgGAJAAASIAAAnQAAAFABACQABAAAAAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAIAAAYIhIAAIAAgYIAJAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgJAAIAAgYIAaAAIATgBIANgCIAAAYQAHgNALgGQAKgGAPAAQAVAAALANQALAMAAAaIAAA0QAAAFACACQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_20.setTransform(-119.525,21.725);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgoBaIAAgYIAMAAQADAAABgCIABgHIAAhxIgBgHQgBgCgDAAIgMAAIAAgYIBQAAIAAAYIgLAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBAAAAABQgCACAAAFIAABxQAAAFACACQAAABABAAQAAAAABABQAAAAABAAQABAAAAAAIALAAIAAAYg");
	this.shape_21.setTransform(-132.45,19.525);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1atype, new cjs.Rectangle(-139,0,278,68.5), null);


(lib.BUTTON = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAqIAlgqIglgpIAaAAIAmApIgmAqgAg2AqIAmgqIgmgpIAbAAIAlApIglAqg");
	this.shape.setTransform(30.575,6.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUA4QgMgFgIgIQgIgHgFgMQgEgLAAgNQAAgLAEgLQAFgMAHgHQAIgIALgGQALgEAMAAQANAAAKAEQALAFAHAJQAIAHAEANQAEALAAANIAAAGIhUAAQACALAIAIQAIAIAOAAIAIgBIAIgCIAIgDIAHgGIANAUQgJAIgMAEQgNAEgNAAQgMAAgLgEgAgKghQgFACgEAEIgFAIIgCAJIA3AAIgCgJIgFgIQgDgDgFgCQgGgDgHAAQgGAAgFACg");
	this.shape_1.setTransform(15.125,6.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AggA6IAAhwIAeAAIAAAPQAFgHAKgGQAJgFALgBIAAAeIgIgBIgIABIgIADIgHAEQgDACgBADIAABKg");
	this.shape_2.setTransform(5.475,6.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaA6QgHgDgGgEQgFgFgEgHQgEgHAAgKQAAgKAEgHQAEgGAFgEQAGgFAHgCQAHgCAHAAQALAAAJADQAKAEAFAHIAAgPQAAgJgHgGQgHgEgKgBQgTAAgPAOIgLgUQALgJANgFQANgEAMAAQAKAAAJACQAJACAGAGQAIAFAEAHQAEAJAAAMIAABJIgeAAIAAgMQgGAHgJAEQgJAEgLAAQgHAAgHgCgAgQAKQgFAEgBAJQABAIAFAEQAHAEAJABQAGgBAGgCQAHgCAEgFIAAgPQgEgEgHgDQgGgCgGAAQgJAAgHAEg");
	this.shape_3.setTransform(-5.45,6.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgQA4QgLgFgIgIQgIgIgEgLQgFgLAAgNQAAgMAFgLQAEgLAIgIQAIgIALgFQAMgEAMAAQARAAALAGQALAGAGAJIgUASQgIgMgQAAQgMAAgJAJQgJAJAAAOQAAAPAJAJQAJAJAMAAQAIAAAGgDQAGgDAEgGIAUASQgGAIgLAGQgLAHgRAAQgMAAgMgEg");
	this.shape_4.setTransform(-16.625,6.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgKBCQgIgIAAgPIAAg7IgTAAIAAgaIATAAIAAgfIAdAAIAAAfIAXAAIAAAaIgXAAIAAAzQAAAFADAEQACADAFAAIAGgBIAFgCIAGAXQgDADgGACQgHACgJAAQgPAAgIgIg");
	this.shape_5.setTransform(-31.375,4.775);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgUA4QgMgFgIgIQgIgHgFgMQgEgLAAgNQAAgLAEgLQAFgMAHgHQAIgIALgGQALgEAMAAQANAAAKAEQALAFAHAJQAIAHAEANQAEALAAANIAAAGIhUAAQACALAIAIQAIAIAOAAIAIgBIAIgCIAIgDIAHgGIANAUQgJAIgMAEQgNAEgNAAQgMAAgLgEgAgKghQgFACgEAEIgFAIIgCAJIA3AAIgCgJIgFgIQgDgDgFgCQgGgDgHAAQgGAAgFACg");
	this.shape_6.setTransform(-41.225,6.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgXBMQgPgGgLgKQgMgLgHgPQgGgPgBgTQABgSAGgPQAHgPAMgLQALgKAPgGQAPgGAQAAQANAAAKADQAKADAIAFQAIAFAGAGIALAOIgcAPQgFgIgKgHQgJgGgOAAQgJAAgJAEQgKAEgGAHQgGAHgEAJQgEAKAAAKQAAALAEAKQAEAJAGAHQAGAHAKAEQAJAEAJAAQALAAAJgEQAJgEAFgEIAAgTIgpAAIAAgdIBLAAIAAA8QgNAOgQAIQgRAIgWAAQgQAAgPgGg");
	this.shape_7.setTransform(-55.8,4.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// bkgd
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#97D700").s().p("Aq0C4IAAluITwAAIB6CtIh6DBg");
	this.shape_8.setTransform(-10.4,4.9325,1,1.1643);

	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(1));

	// shad
	this.instance = new lib.Buttonshad();
	this.instance.setTransform(-80,-17,0.6438,0.7496);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BUTTON, new cjs.Rectangle(-96.8,-17,166.2,65.2), null);


(lib.BKGDblue = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#79863C").s().p("A3ZKVIAA0pMAuzAAAIAAUpg");
	this.shape.setTransform(0,66.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGDblue, new cjs.Rectangle(-149.7,0,299.5,132.2), null);


(lib.HEAD2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD2type();
	this.instance.setTransform(6,50,1,1,0,0,0,0,36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-133,14,278,68.5), null);


(lib.HEAD1b = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1btype();
	this.instance.setTransform(0,25,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1b, new cjs.Rectangle(-139,1,278,68.5), null);


(lib.HEAD1a = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1atype();
	this.instance.setTransform(0,23,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1a, new cjs.Rectangle(-139,-1,278,68.5), null);


// stage content:
(lib.JCC_SchoolisBack_300x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,338];
	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_338 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(338).call(this.frame_338).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,2,0,3).p("EgXWguyMAutAAAMAAABdlMgutAAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(339));

	// JCC logo
	this.instance = new lib.JCClogo();
	this.instance.setTransform(205,558.2,1,1,0,0,0,0,2.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(339));

	// CTA
	this.instance_1 = new lib.BUTTON();
	this.instance_1.setTransform(-27.3,556.95,0.76,0.76,0,0,0,-10.4,3.9);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(323).to({_off:false},0).to({x:52.7},15,cjs.Ease.quadOut).wait(1));

	// BKGD-orange (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgXbAu4IAAtcMAu3AAAIAANcg");
	mask.setTransform(150.0038,299.9917);

	// bkgd
	this.instance_2 = new lib._300x6002x();
	this.instance_2.setTransform(-1,1,0.5,0.5);

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(339));

	// HEAD1a
	this.instance_3 = new lib.HEAD1a();
	this.instance_3.setTransform(145.5,450.55,1,1,0,0,0,0,24);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(4).to({_off:false},0).to({alpha:1},6).wait(91).to({alpha:0},7).to({_off:true},1).wait(230));

	// HEAD1b
	this.instance_4 = new lib.HEAD1b();
	this.instance_4.setTransform(145.5,447.95,1,1,0,0,0,0,24);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(113).to({_off:false},0).to({alpha:1},7).wait(124).to({alpha:0},6).to({_off:true},1).wait(88));

	// HEAD2
	this.instance_5 = new lib.HEAD2();
	this.instance_5.setTransform(139.5,446.95,1,1,0,0,0,0,36);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(256).to({_off:false},0).wait(83));

	// BKGD-blue
	this.instance_6 = new lib.BKGDblue();
	this.instance_6.setTransform(149.75,406,1,0.8169);
	this.instance_6.alpha = 0.8516;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(339));

	// img
	this.instance_7 = new lib.sch_img_300x600();

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(339));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(57.1,299.5,243.4,301);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 300,
	height: 600,
	fps: 36,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/JCC_SchoolisBack_300x600_atlas_P_1.png", id:"JCC_SchoolisBack_300x600_atlas_P_1"},
		{src:"images/JCC_SchoolisBack_300x600_atlas_NP_1.jpg", id:"JCC_SchoolisBack_300x600_atlas_NP_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;