(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"CO_KidsProcedures_160x600_atlas_P_1", frames: [[0,0,232,87]]},
		{name:"CO_KidsProcedures_160x600_atlas_NP_1", frames: [[0,0,320,1200]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Buttonshad = function() {
	this.initialize(ss["CO_KidsProcedures_160x600_atlas_P_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.sch_img_160x6002x = function() {
	this.initialize(ss["CO_KidsProcedures_160x600_atlas_NP_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.HS_logowhite = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ap9EXIAHnRINagKIgCh7IGDgCIAZKDgAFdgfQgVAOgIAYQgGAUAAAZQAAAaAGATQAJAZAVAOQAVAOAgAAQAyAAAeggQADgDgEgCIgZgYQgCgDgEADQgSARgZAAQgfAAgHgZIgDgKQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIBxAAQAEAAAAgEQAAglgGgUQgIgYgVgOQgVgOgfABQgeAAgVANgAgnAvQgVAQAAAdQAAAdASAPQARAOAaAAQAjAAAQgVIABAAIAAANQAAADAEAAIArAAQADAAAAgDIAAh4QAAgjgSgPQgUgRgtABQgqAAgaASQgDACACADIARAeQACADADgDQAQgKAZAAQAWAAAIAEQAIAHAAANIAAAHQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIghAAQgkAAgUAOgAnMBXIgZAdQgCACACADQAiAdAzAAQAoAAAWgSQAVgRABgeQAAgyg/gGIgUgCQgPgCgGgEQgFgDAAgHQAAgOAYgBQAbAAAXAOQAEADACgDIAVgaQADgDgDgDQgegWguAAQgkgBgVARQgUAQAAAaQAAAzA9AHIAVABQAQACAGAEQAFAEAAAHQAAASgdAAQgfAAgagVIgDgBIgDABgACfgkIAACyQAAADAEAAIAuAAQAEAAAAgDIAAhjQAAgnAdgCQAMAAAPAJQADABACgCIAWgmQACgEgDgCQgNgLgUABQgjgBgOAYIAAAAIAAgPQAAgFgEAAIguAAQgEAAAAAFgAieAiIAABsQAAADAEAAIAuAAQAEAAAAgDIAAh2QAAgegRgTQgRgUgeABQghAAgPAUIgBAAIAAhZQAAgDgEAAIguAAQgEAAAAADIAAD/QAAADAEAAIAuAAQAEAAAAgDIAAhsQAAgPAIgKQAIgJAOAAQAdAAAAAig");
	this.shape.setTransform(25.025,83.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAaAAQABABABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_1.setTransform(27.15,92.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeATQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBQAAgGACgIQAHgTAXgBQAZABAGATQACAGAAAIQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_2.setTransform(65.075,85.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AqIk4IUcAvIAII0I03AOgAhWAjQgVAQAAAeQgBAdAUAPQAQAOAbAAQAkAAAPgVIAAANQAAADAEAAIArAAQAEAAAAgDIAAh5QAAgjgSgPQgUgRgsAAQgrAAgcATQgCACACADIARAfQACACADgBQARgMAZAAQAWAAAIAGQAHAGAAAMIAAAHQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIghAAQgjAAgVAOgAkagrQgVAOgIAZQgHATAAAZQAAAXAHAWQAIAaAWAOQAVAOAgAAQAzAAAdggQADgDgDgCIgagYQgCgDgDADQgSAQgZAAQgfAAgIgYQgCgDgBgIQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIBxAAQAFAAAAgEQAAgmgGgTQgJgZgUgOQgWgOgfAAQgeAAgVAOgADcgxIAAAhQAAAEAFAAIALAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAABUQAAAhAOAPQAOAPAgAAIAUAAQAEAAABgEIAAgnQgBgDgEAAIgJAAQgJAAgDgEQgFgFAAgKIAAhSQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAYAAQAEAAABgEIAAghQgBgDgEAAIgYAAQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAgyQAAgEgDAAIguAAQgFAAAAAEIAAAyQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgLAAQgFAAAAADgABth9IAADKQAAAfANAPQAOAOAfAAIAVAAQADAAAAgEIAAgnQAAgDgDAAIgIAAQgRAAAAgSIAAjGQAAgEgEAAIgvAAQgDAAAAAEgAHggBQAIAIAAAQIAABsQAAADADAAIAvAAQAEAAAAgDIAAh3QAAgegRgTQgQgUgfAAQghAAgQAWIAAAAIAAhaQAAgEgEAAIguAAQgFAAAAAEIAAEAQAAADAFAAIAuAAQAEAAAAgDIAAhsQAAgQAIgIQAIgKAOAAQAOAAAHAKgAmpgBQAHAIAAAQIAABsQAAADAFAAIAuAAQAEAAAAgDIAAh3QAAgegRgTQgRgUgfAAQghAAgPAWIAAhaQAAgEgEAAIgvAAQgDAAAAAEIAAEAQAAADADAAIAvAAQAEAAAAgDIAAhsQAAgQAIgIQAHgKAOAAQAOAAAIAKg");
	this.shape_3.setTransform(-21.95,31.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAbAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_4.setTransform(-24.5,39.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeASQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAgGADgIQAHgUAXAAQAYAAAIAUQACAIAAAGQAAABgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-45.05,31.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AJdAwIAcgBQABAJANAAQAPABAAgNIAAgIQgIAFgMAAQgRAAgLgMQgKgLAAgSQAAgSAKgLQALgMARAAQANAAAIAHIAAgFIAaAAIAABRQAAARgLALQgLAKgTAAQgmAAgFgggAJ4AAQAAASAPAAQAHgBAEgEQAEgEAAgIIAAgCQAAgHgEgFQgFgEgGAAQgPAAAAARgALLAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgALbAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAILAeQgLgLAAgTQAAgSALgLQAMgMASAAQASAAAKAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgKAHQgLAHgOAAQgTAAgMgLgAI0gIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgAFOAZQgRgQAAgaQAAgaARgRQAQgQAbAAQAbAAARAQQARARAAAaQAAAagRAQQgRAQgbAAQgbAAgQgQgAFjgpQgIAJAAAPQAAAPAIAJQAIAIAOAAQAOAAAIgIQAJgJAAgPQAAgPgJgJQgIgIgOgBQgOABgIAIgACHAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgACXAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAAJAeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgPAAQgTAAgLgLgAAygIQgBgMgLAAQgKAAgBAMIAXAAIAAAAgAiVASQAAgWAigCIAJAAIAAgEQAAgIgGAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAh6AQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAlOAfQgNgKAAgTIAegBQAAAGAFAEQAFAFAHAAQANgBAAgIQAAgHgTgFQgTgFgIgGQgLgHAAgQQAAgQAKgJQALgMAUAAQAUAAAMALQAMAJABASIgeABQAAgNgOAAQgMAAAAAKQAAAEAEACQADADAMADQATAEAIAHQALAJAAANQAAASgMAKQgMAIgTAAQgVAAgNgKgAoUANIAAgdIgOAAIAAgXIAOAAIABgZIAbAAIAAAZIARAAIAAAXIgRAAIAAAWQAAALALAAIAGgBIAAAYIgNABQggAAAAgcgAqjASQAAgWAigCIAKAAIAAgEQAAgIgHAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAqIAQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAr0AeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgOAAQgTAAgMgLgArLgIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgANWAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAhOIAaAAIAAAFQAGgHAOAAQAOAAAIAIQAJAJAAAPIAAAwgAHGAnIAAhOIAbAAIAAAGQAHgHAOAAIAAAbQgJAAgGAFQgFAEAAAGIAAAlgADlAnIAAg3IgOAAIAAgXIAOAAIAAgFQAAgQAKgKQAKgJAQAAIAJAAIAAAZIgGgBQgFAAgDADQgDADAAAEIAAAGIARAAIAAAXIgRAAIAAA3gAg7AnIAAhOIAbAAIAAAGQAGgHAPAAIAAAbQgKAAgFAFQgFAEAAAGIAAAlgAjAAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAGgGAMAAQAOAAAIAIQAJAJAAAPIAAAwgAmnAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAHgGALAAQAOAAAIAIQAJAJAAAPIAAAwgApJAnIAAh1IAcAAIAAB1gAstAnIAAgsIgmAAIAAAsIgeAAIAAhwIAeAAIAAAqIAmAAIAAgqIAeAAIAABwg");
	this.shape_6.setTransform(0.175,134.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HS_logowhite, new cjs.Rectangle(-88.7,0,177.5,143), null);


(lib.HEAD2type = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOAPQgGgGAAgJQAAgIAGgGQAGgFAIAAQAJAAAGAFQAGAGAAAIQAAAJgGAGQgGAFgJAAQgIAAgGgFg");
	this.shape.setTransform(-41.2,73.675);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAWA2IgVg6IgXA6IgaAAIgehSIgDgFIgEgBIgFAAIAAgUIA6AAIAAAUIgGAAQAAAAgBAAQgBAAAAAAQgBABAAAAQAAAAAAABQgBACABADIADAKIAGARIAGAQIAGgQIAGgRIADgKQABgDgBgCQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAIgGAAIAAgUIA3AAIAAAUIgFAAQgBAAgBAAQAAAAgBAAQAAABgBAAQAAAAgBABQgBACABADIAFAKIAGARIAHAQIAFgQIAGgRIADgKQACgDgCgCQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAAAIgGAAIAAgUIArAAIAAAUIgGAAIgDABIgDAFIgdBSg");
	this.shape_1.setTransform(-53,70.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeAyQgNgHgHgNQgIgNAAgRQAAgQAIgNQAHgMAOgHQANgIAQAAQASAAANAHQANAIAIAMQAGANAAAQQAAARgGANQgIANgNAHQgNAHgSAAQgRAAgNgHgAgQgbQgFAIAAASIAAADQAAASAFAIQAGAIAKAAQAMAAAFgIQAGgIgBgSIAAgDQABgSgGgIQgFgIgMAAQgKAAgGAIg");
	this.shape_2.setTransform(-68.45,70.025);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAGA3IAAgTIAHAAQAAAAABAAQAAAAAAAAQABAAAAgBQAAAAABAAQABgBAAgFIAAgpQAAgKgEgFQgDgEgIAAQgIAAgFAHQgFAHAAAPIAAAfQAAAFABABQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAIAGAAIAAATIg6AAIAAgTIAHAAQABAAAAAAQABAAAAAAQAAAAABgBQAAAAAAAAQABgBAAgFIAAg2QABgEgBgBQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgHAAIAAgTIAVAAIAPgBIALgCIAAAUQAGgKAJgFQAHgFANAAQARAAAJAKQAJAKAAAVIAAAqQAAAFABABQAAAAABAAQAAABAAAAQABAAAAAAQABAAAAAAIAIAAIAAATg");
	this.shape_3.setTransform(-81.275,69.875);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNA+QgIgIABgTIAAg2IgPAAIAAgSIAIAAQAGgBAEgEQAEgDACgHIACgSIAYAAIAAAfIATAAIAAAUIgVAAIAAA2QABAIADADQADADAHAAIAEAAIAFgBIAAAUIgJACIgMABQgTAAgJgJg");
	this.shape_4.setTransform(-97.25,68.625);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgdBNIAAgUIAIAAIADgBIABgFIAAg0QAAgFgBgCQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgHAAIAAgUIAWAAIAOAAIALgCIAABTIABAFIADABIAIAAIAAAUgAgOgrQgGgGAAgIQAAgIAGgFQAFgGAJAAQAJAAAGAGQAFAFAAAIQAAAIgFAGQgGAGgJgBQgJABgFgGg");
	this.shape_5.setTransform(-104.125,67.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgbA2IgSgGIAAgcIAZAAIAAARIAHABIAKABQAHAAAFgDQAEgDAAgGQAAgHgGgCQgGgDgKgCQgJgCgJgDQgIgDgFgGQgGgHAAgLQAAgRANgKQAMgJAXgBQANABAKACQAMADAFADIAAAcIgXAAIAAgQIgHgCIgIgBQgIAAgFADQgEADAAAGQAAAEADADIAIADIALADQAJABAJAEQAJADAFAGQAGAHAAALQAAASgNAKQgNAKgXAAQgNAAgMgDg");
	this.shape_6.setTransform(-112.5,70.025);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgdBNIAAgUIAIAAIADgBIABgFIAAg0QAAgFgBgCQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgHAAIAAgUIAWAAIAOAAIALgCIAABTIABAFIADABIAIAAIAAAUgAgOgrQgGgGAAgIQAAgIAGgFQAFgGAJAAQAJAAAGAGQAFAFAAAIQAAAIgFAGQgGAGgJgBQgJABgFgGg");
	this.shape_7.setTransform(-120.925,67.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgMA2IglhSIgDgFIgDgBIgHAAIAAgUIA+AAIAAAUIgIAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAABQgBACABADIAFANIAHAQIAHASIAHgUIAIgRIAEgKQABgDgBgCQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgIAAIAAgUIAyAAIAAAUIgHAAQgDAAgCACQgCABgBADIgkBSg");
	this.shape_8.setTransform(-130.575,70.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgpBFQgLgHgFgNQgHgNAAgRQAAgRAHgMQAFgMALgIQALgHAOAAQANAAAIAFQAIAFAEAJIAAgcIgBgGQAAAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgIAAIAAgTIAWAAIAPgBIALgCIAAB6QAAAEABABQABABAAAAQAAAAABAAQAAAAABAAQAAAAABAAIAHAAIAAAUIgrAAIgBgHIgBgNQgFALgJAGQgIAGgOAAQgOAAgLgHgAgUgGQgFAHgBAQIAAAEQABARAFAIQAGAIALAAQAJAAAFgIQAGgIAAgRIAAgEQAAgQgGgHQgFgJgJABIgCAAQgJAAgGAIg");
	this.shape_9.setTransform(-24.4,42.225);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgcBKIAAgTIAHAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAQABgBAAgFIAAhcQAAgEgBgCQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAgBAAIgIAAIAAgTIAXAAIAOgBIALgBIAAB5QAAAFABABQAAAAABAAQAAABAAAAQABAAAAAAQABAAAAAAIAHAAIAAATg");
	this.shape_10.setTransform(-34.55,42.075);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgdBNIAAgUIAIAAIADgBIABgFIAAg0QAAgFgBgCQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgHAAIAAgTIAWAAIAOgBIALgCIAABTIABAFIADABIAIAAIAAAUgAgOgrQgGgFAAgJQAAgIAGgGQAFgFAJAAQAJAAAGAFQAFAGAAAIQAAAJgFAFQgGAGgJAAQgJAAgFgGg");
	this.shape_11.setTransform(-41.125,41.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAHBKIAAgTIAHAAQAAAAAAAAQABAAAAAAQAAAAABgBQAAAAAAAAQABgBAAgFIAAgqQABgJgEgEQgEgFgHAAQgJAAgFAHQgFAHAAAPIAAAfQAAAFABABQABAAAAAAQAAABAAAAQABAAAAAAQABAAAAAAIAHAAIAAATIg7AAIAAgTIAIAAQAAAAABAAQAAAAABAAQAAAAAAgBQABAAAAAAQABgBAAgFIAAhcIgBgGQAAgBAAAAQgBAAAAAAQgBgBAAAAQgBAAAAAAIgIAAIAAgTIAWAAIAPgBIALgBIAAA5QAGgKAIgEQAIgFANAAQARAAAJAKQAJAKAAAUIAAArQAAAFABABQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAIAHAAIAAATg");
	this.shape_12.setTransform(-51.175,42.075);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgnAqQgPgPAAgbQABgaAPgPQAQgOAagBQAZAAAMAKQANAKABARQAAALgGAHQgGAGgLAAQgJAAgEgFQgGgEAAgHQAAgHAEgFQAEgFAHgBQgCgEgFgCQgEgBgIAAQgNAAgGAIQgHAIAAASIAAADQAAARAGAIQAHAJAMAAQAKAAAGgFQAHgFADgJIAUAKQgFAOgLAIQgMAJgWAAQgbAAgQgPg");
	this.shape_13.setTransform(-63.45,44.125);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgdAMIAAgXIA6AAIAAAXg");
	this.shape_14.setTransform(-72.7,44.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgcBKIAAgTIAHAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAQABgBAAgFIAAhcQAAgEgBgCQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAgBAAIgIAAIAAgTIAXAAIAOgBIALgBIAAB5QAAAFABABQAAAAABAAQAAABAAAAQABAAAAAAQABAAAAAAIAHAAIAAATg");
	this.shape_15.setTransform(-79.45,42.075);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgcBKIAAgTIAHAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAAAAAQABgBAAgFIAAhcQABgEgBgCQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAgBAAIgIAAIAAgTIAXAAIAOgBIALgBIAAB5QAAAFABABQAAAAABAAQAAABAAAAQABAAAAAAQAAAAABAAIAHAAIAAATg");
	this.shape_16.setTransform(-86.05,42.075);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgcAxQgNgHgHgNQgHgMABgRQAAgQAGgNQAIgMANgIQANgHAQAAQAbABANAPQAOAPAAAbIAAAFIhJAAQABANAGAIQAHAHAMAAQALAAAHgFQAGgFADgIIATALQgEAIgGAHQgHAGgKAEQgKAEgOAAQgTAAgNgIgAAUgJQAAgPgEgGQgEgGgKAAQgIAAgGAGQgFAHAAAOIAlAAIAAAAg");
	this.shape_17.setTransform(-95.2,44.125);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAWA3IgVg8IgXA8IgaAAIgehTIgDgFIgEgBIgFAAIAAgTIA6AAIAAATIgGAAQAAAAgBAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBACABADIADAKIAGARIAGAQIAGgQIAGgRIADgKQABgDgBgCQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAIgGAAIAAgTIA3AAIAAATIgFAAQgBAAgBAAQAAAAgBAAQgBABAAAAQAAAAgBABQgBACABADIAFAKIAGARIAHAQIAGgQIAFgQIAEgKQAAgFgBgBQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAIgFAAIAAgTIArAAIAAATIgGAAIgDABIgDAFIgdBTg");
	this.shape_18.setTransform(-110.25,44.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgxAxQgIgIgBgNQABgOAJgIQAJgHARgEQAPgEATgDIAAgGQgBgKgFgEQgEgFgKAAIgFABIgGABIACAEIABAGQAAAIgFAEQgGAFgIAAQgJAAgFgFQgGgFAAgJQABgKAGgGQAHgHAMgDQAMgDAPAAQAaAAAMAJQAMAIAAAUIAAAvIABAFQAAAAAAAAQAAABABAAQAAAAABAAQAAAAAAAAIAIAAIAAAUIgoAAIgEgIIgDgKQgDAGgFAFQgGAEgHADQgHADgJAAQgPAAgJgIgAgNAIQgKAFAAAJQAAAHADADQAEADAGAAQAKAAAGgHQAFgHABgMIAAgIQgQACgJAFg");
	this.shape_19.setTransform(-130.7,44.125);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgcAxQgNgHgHgNQgGgMAAgRQgBgQAIgNQAGgMAOgIQANgHAPAAQAbABAOAPQANAPAAAbIAAAFIhIAAQABANAGAIQAHAHAMAAQALAAAHgFQAGgFADgIIASALQgDAIgGAHQgHAGgKAEQgKAEgOAAQgTAAgNgIgAAUgJQAAgPgEgGQgFgGgJAAQgJAAgFAGQgFAHAAAOIAlAAIAAAAg");
	this.shape_20.setTransform(-48.2,18.225);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgcBKIAAgTIAIAAQAAAAAAAAQABAAAAAAQABAAAAgBQAAAAAAAAQABgBAAgFIAAhcQABgEgBgCQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgJAAIAAgTIAWAAIAPgBIALgBIAAB5QAAAFABABQAAAAABAAQAAABAAAAQABAAAAAAQAAAAABAAIAHAAIAAATg");
	this.shape_21.setTransform(-57.45,16.175);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgsAtQgJgJABgWIAAgqQAAgEgCgCIgDgBIgIAAIAAgTIAxAAIAABEQAAAKADAEQAEAFAHgBQAJAAAFgGQAEgHAAgOIAAghIgBgGIgDgBIgJAAIAAgTIAxAAIAABQIACAFQAAABAAAAQAAAAABABQAAAAABAAQAAAAABAAIAJAAIAAATIgXAAIgPABIgMACIAAgTQgEAKgJAFQgJAEgLAAQgSAAgJgKg");
	this.shape_22.setTransform(-67.4,18.375);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgpBFQgKgHgHgNQgFgNAAgRQAAgRAFgMQAHgMAKgIQALgHAOAAQANAAAHAFQAJAFAEAJIAAgcIAAgGQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgJAAIAAgTIAXAAIAPgBIAMgCIAAB6QAAAEABABQAAABAAAAQAAAAABAAQAAAAABAAQAAAAAAAAIAIAAIAAAUIgsAAIgBgHIAAgNQgEALgKAGQgHAGgPAAQgPAAgKgHgAgUgGQgFAHAAAQIAAAEQAAARAFAIQAGAIAKAAQAKAAAFgIQAGgIAAgRIAAgEQAAgQgGgHQgFgJgKABIgBAAQgJAAgGAIg");
	this.shape_23.setTransform(-80.8,16.325);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgcAxQgNgHgHgNQgHgMAAgRQABgQAGgNQAHgMANgIQAOgHAQAAQAbABANAPQAOAPAAAbIAAAFIhJAAQAAANAHAIQAHAHAMAAQALAAAHgFQAGgFADgIIATALQgEAIgGAHQgHAGgKAEQgKAEgOAAQgTAAgNgIgAAVgJQgBgPgEgGQgEgGgKAAQgIAAgGAGQgFAHAAAOIAmAAIAAAAg");
	this.shape_24.setTransform(-93.5,18.225);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAHBKIAAgTIAHAAQAAAAAAAAQABAAAAAAQAAAAABgBQAAAAAAAAQABgBAAgFIAAgqQABgJgEgEQgEgFgHAAQgJAAgFAHQgFAHAAAPIAAAfQAAAFABABQAAAAABAAQAAABABAAQAAAAAAAAQABAAAAAAIAHAAIAAATIg7AAIAAgTIAIAAQAAAAABAAQAAAAABAAQAAAAAAgBQABAAAAAAQABgBAAgFIAAhcIgBgGQAAgBAAAAQgBAAAAAAQgBgBAAAAQgBAAAAAAIgIAAIAAgTIAWAAIAPgBIALgBIAAA5QAGgKAIgEQAIgFANAAQARAAAJAKQAJAKAAAUIAAArQAAAFABABQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAIAHAAIAAATg");
	this.shape_25.setTransform(-106.125,16.175);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgmAqQgQgPAAgbQAAgaAQgPQAPgOAbgBQAZAAANAKQANAKAAARQgBALgFAHQgGAGgKAAQgKAAgFgFQgEgEgBgHQABgHAEgFQADgFAHgBQgDgEgEgCQgFgBgHAAQgMAAgHAIQgHAIAAASIAAADQAAARAHAIQAGAJAMAAQAKAAAHgFQAGgFAEgJIATAKQgFAOgMAIQgMAJgVAAQgbAAgPgPg");
	this.shape_26.setTransform(-118.4,18.225);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AggBJQgOgDgKgGIAAgjIAdAAIAAAWIAMADIAOABQAJAAAGgFQAGgEAAgIQABgHgEgEQgEgEgHgCIgTgFQgNgDgJgGQgLgEgFgIQgGgIABgOQAAgXAPgMQAQgNAcAAQAOAAAMACQANADALAFIAAAjIgdAAIAAgVIgKgCIgLAAQgLgBgHAFQgFAEgBAJQAAAGAEAEQACADAIACIARAGQAMADAMAEQAKAFAHAHQAGAJAAAOQAAAPgGALQgHALgOAGQgNAGgTAAQgQAAgOgDg");
	this.shape_27.setTransform(-130.55,16.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2type, new cjs.Rectangle(-139,0,278,83.7), null);


(lib.HEAD1dtype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLALQgEgEAAgHQAAgGAEgEQAFgFAGAAQAIAAAEAFQAEAEAAAGQAAAHgEAEQgEAEgIABQgGgBgFgEg");
	this.shape.setTransform(-60.125,13.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUAqIgPgFIAAgVIAUAAIAAAMIAFABIAHABQAGAAAEgCQADgCABgGQAAgEgGgCIgLgEIgOgEQgHgDgEgEQgFgEABgKQgBgNAKgHQAKgIARAAQAKAAAJADQAIABAFADIAAAVIgTAAIAAgMIgFgBIgGgBQgGAAgDACQgEACAAAFQAAAEADABQACACADABIAJACIAOAEQAGADAEADQAFAGABAJQgBANgJAIQgLAHgRABQgLAAgIgCg");
	this.shape_1.setTransform(-66.05,10.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgJAwQgHgGAAgPIAAgqIgKAAIAAgNIAFgBQAFgBADgCQADgCABgGIACgOIASAAIAAAYIAPAAIAAAPIgQAAIAAAqQABAGACACQACADAFAAIAFgBIADAAIAAAPIgIACIgJAAIgCABQgMAAgGgHg");
	this.shape_2.setTransform(-73.05,9.4018);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXAmQgKgFgFgKQgGgKAAgNQAAgMAGgKQAFgKAKgFQALgFAMgBQAOABAKAFQAKAFAFAKQAGAKAAAMQAAANgGAKQgFAKgKAFQgKAGgOAAQgNAAgKgGgAgMgVQgEAHAAANIAAACQAAAOAEAHQAEAGAIAAQAJAAAEgGQAEgHAAgOIAAgCQAAgNgEgHQgEgGgJAAQgIAAgEAGg");
	this.shape_3.setTransform(-80.6,10.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAFA5IAAgPIAFAAIACgBIABgEIAAggQAAgHgCgEQgDgDgGAAQgGAAgEAFQgEAFAAAMIAAAYIABAEIADABIAEAAIAAAPIgtAAIAAgPIAGAAIACgBIABgEIAAhHIgBgFIgCgBIgHAAIAAgPIASAAIAMAAIAIgBIAAAsQAEgIAHgDQAGgEAJAAQAOAAAHAIQAGAIAAAPIAAAhIACAEIACABIAFAAIAAAPg");
	this.shape_4.setTransform(-90.6,8.925);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgUAqIgPgFIAAgVIATAAIAAAMIAGABIAIABQAFAAAEgCQADgCAAgGQAAgEgEgCIgNgEIgNgEQgHgDgEgEQgEgEgBgKQAAgNAKgHQAJgIASAAQAKAAAIADQAJABAFADIAAAVIgTAAIAAgMIgFgBIgGgBQgGAAgEACQgDACAAAFQAAAEACABQACACAEABIAJACIAOAEQAGADAFADQAEAGAAAJQAAANgKAIQgKAHgRABQgKAAgJgCg");
	this.shape_5.setTransform(-99.65,10.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AghAjQgHgIAAgQIAAghIgBgEIgCgBIgHAAIAAgPIAmAAIAAA1QAAAIADADQADADAFAAQAHAAADgFQAEgGAAgKIAAgaIgBgEIgCgBIgIAAIAAgPIAnAAIAAA+IABAEIACABIAHAAIAAAPIgSAAIgMABIgIABIAAgOQgEAHgHAEQgGAEgJAAQgOAAgGgIg");
	this.shape_6.setTransform(-112.775,10.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgWA5IAAgPIAHAAIACgBIAAgEIAAhHQABgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAgBIgCgBIgHAAIAAgPIARAAIALAAIAJgBIAABdIAAAEIADABIAFAAIAAAPg");
	this.shape_7.setTransform(-120.5,8.925);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgtA5IAAgQIAHAAIADAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBIAAhHIgBgFIgDAAIgHAAIAAgQIBbAAIAAAfIgQAAIgCgJQgBgFgDgBIgIAAIgVAAIAAAkIAOAAIAEgBQABgCAAgDIAAgFIAOAAIAAAlIgOAAIAAgFQAAgDgBgCQAAgBgBAAQAAAAgBgBQAAAAgBAAQgBAAAAAAIgOAAIAAAaIABAFIADAAIAHAAIAAAQg");
	this.shape_8.setTransform(-128.125,9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1dtype, new cjs.Rectangle(-135,-4,278,25.6), null);


(lib.HEAD1ctype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLALQgEgEAAgHQAAgGAEgEQAFgFAGAAQAIAAAEAFQAEAEAAAGQAAAHgEAEQgEAEgIABQgGgBgFgEg");
	this.shape.setTransform(-8.475,13.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgWAmQgKgGgEgJQgGgKAAgNQAAgMAGgKQAFgKAKgFQAKgFANgBQAUAAAKAMQALAMAAAUIAAAEIg4AAQABALAFAGQAFAFAJAAQAJAAAEgDQAFgFADgGIAOAJQgCAGgFAFQgGAFgHADQgIADgLAAQgOgBgLgFgAAQgHQgBgLgDgFQgDgFgHABQgHgBgEAFQgEAFgBALIAeAAIAAAAg");
	this.shape_1.setTransform(-15.1,10.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAFArIAAgPIAFAAIACgBIABgEIAAggQAAgIgDgDQgCgEgHAAQgGAAgEAGQgDAFAAAMIAAAYIABAEIACABIAFAAIAAAPIgtAAIAAgPIAGAAIACgBIABgEIAAgqIgBgEIgCgBIgGAAIAAgPIAQAAIAMgBIAIgBIAAAPQAEgIAHgEQAGgEAKAAQANAAAHAIQAHAIAAARIAAAgIABAEIACABIAGAAIAAAPg");
	this.shape_2.setTransform(-24.775,10.375);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgWA8IAAgQIAGAAIACAAIABgEIAAgoQABgEgCgCQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAgBAAAAIgGAAIAAgOIARAAIALgBIAIgCIAABBIABAEIADAAIAFAAIAAAQgAgLghQgEgEAAgHQAAgGAEgEQAFgFAGABQAIgBADAFQAFAEAAAGQAAAHgFAEQgDAEgIABQgGgBgFgEg");
	this.shape_3.setTransform(-32.65,8.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeAgQgLgLAAgVQAAgUAMgLQAMgMAVAAQASABAKAGQALAIgBANQABAKgFAEQgFAEgIABQgHAAgEgEQgDgDAAgGQAAgFACgEQADgDAGgBQgCgDgEgCQgDgBgGAAQgJAAgFAHQgGAGAAAOIAAABQAAAOAGAGQAEAHAJAAQAIAAAFgDQAGgFACgGIAPAHQgEAKgJAHQgJAGgQABQgVAAgNgMg");
	this.shape_4.setTransform(-39.6,10.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeAgQgLgLAAgVQAAgUAMgLQAMgMAVAAQASABAKAGQAKAIAAANQABAKgFAEQgEAEgJABQgGAAgFgEQgDgDAAgGQAAgFACgEQADgDAGgBQgCgDgEgCQgDgBgGAAQgJAAgFAHQgGAGAAAOIAAABQAAAOAGAGQAFAHAIAAQAIAAAFgDQAGgFACgGIAPAHQgEAKgJAHQgJAGgQABQgWAAgMgMg");
	this.shape_5.setTransform(-48.5,10.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgmAlQgGgGgBgJQABgLAHgGQAIgGAMgDIAagGIAAgEQAAgHgEgEQgEgDgGAAIgFAAIgEABIACADIAAAFQAAAGgEADQgEAEgHAAQgHAAgEgEQgDgEAAgGQAAgIAEgFQAGgFAJgCQAJgDAMAAQAUAAAJAGQAJAIAAAPIAAAkIABAEIACAAIAFAAIAAAQIgeAAIgDgHIgDgHQgCAEgEAEQgEAEgFACQgGACgHAAQgMAAgHgHgAgKAGQgIAEAAAHQAAAFADADQADACAEAAQAIAAAFgFQAEgFAAgJIAAgHQgMACgHADg");
	this.shape_6.setTransform(-57.7,10.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgLA5IgkhcIgCgFIgEAAIgHAAIAAgQIA2AAIAAAQIgGAAQgBAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABIAWA6IAVg6QABgBAAAAQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIgIAAIAAgQIAtAAIAAAQIgIAAIgEAAIgDAFIgkBcg");
	this.shape_7.setTransform(-68.725,9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag4A5IAAgQIAHAAIADAAQAAgBABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAhHIgBgFIgDAAIgHAAIAAgQIA2AAQAdAAAPAPQAPAOAAAcQAAAbgPAOQgQAPgeAAgAgPApIANAAQAKAAAGgDQAGgFADgIQACgIAAgNIAAgHQAAgNgCgIQgDgIgGgFQgGgDgJAAIgOAAg");
	this.shape_8.setTransform(-85.125,9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgYA5IAAgQIAHAAIADAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAhHIAAgFIgDAAIgHAAIAAgQIAxAAIAAAQIgGAAIgDAAIgBAFIAABHQAAABAAABQAAAAAAABQAAAAABABQAAAAAAABIADAAIAGAAIAAAQg");
	this.shape_9.setTransform(-93.95,9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgLA5IgkhcIgCgFIgEAAIgHAAIAAgQIA2AAIAAAQIgGAAQgBAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABIAWA6IAVg6QAAgBABAAQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAAAgBAAQAAAAgBAAQgBAAAAAAIgIAAIAAgQIAtAAIAAAQIgIAAIgEAAIgDAFIgkBcg");
	this.shape_10.setTransform(-102.975,9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgfAzQgMgGgHgOQgHgNAAgSQAAgQAHgOQAIgNANgHQANgIARAAQASAAANAIQANAHAGANQAHANAAARQAAASgHANQgHAOgOAGQgNAIgRAAQgSAAgNgIgAAVAgQAHgJAAgTIAAgHQAAgTgHgJQgHgJgOAAQgMAAgHAJQgHAJAAATIAAAHQAAATAHAJQAGAKANgBQAOABAHgKg");
	this.shape_11.setTransform(-115.475,9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgaA0QgNgHgGgNQgHgNAAgTQAAgQAGgOQAHgNAMgHQAMgIAPAAQALAAAIAEQAIAFAEAJIAFgQIAQAAIAAAsIgXAAQgCgOgGgGQgHgHgKAAQgMAAgGAJQgHAJAAATIAAAFQAAATAHAJQAHAKAMAAQAMgBAHgGQAHgHABgNIAVADQgBAMgFAJQgGAJgKAGQgLAFgQABQgRAAgNgHg");
	this.shape_12.setTransform(-127.35,9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1ctype, new cjs.Rectangle(-135,-4,278,25.6), null);


(lib.HEAD1btype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLALQgEgEAAgHQAAgGAEgEQAFgFAGAAQAIAAAEAFQAEAEAAAGQAAAHgEAEQgEAEgIABQgGgBgFgEg");
	this.shape.setTransform(-41.775,13.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUAqIgPgFIAAgVIAUAAIAAAMIAFABIAHABQAGAAAEgCQAEgCAAgGQgBgEgFgCIgLgEIgOgEQgHgDgEgEQgFgEAAgKQAAgNAKgHQAKgIARAAQAKAAAJADQAIABAFADIAAAVIgTAAIAAgMIgFgBIgGgBQgGAAgDACQgEACAAAFQAAAEADABQACACADABIAJACIAOAEQAGADAEADQAFAGABAJQgBANgKAIQgJAHgSABQgLAAgIgCg");
	this.shape_1.setTransform(-47.7,10.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgfA/QgLgCgEgDQgFgEABgFQgBgGAGgEQAFgEALgCQgJgCgFgFQgEgEAAgHQAAgGAEgFQAFgEAHgCQgHgDgCgGQgEgFAAgIQAAgJAGgHQAFgGAKgEQAJgDAMgBQAGAAAGACIAMAEQACgIAEgEQAEgEAHAAQAGAAADADQADADAAAFQAAAFgCADQgDADgFAAIgGgBIgDgEIgBACIgDACQAFADABAFQACAFAAAGQAAAJgEAGQgGAHgJACQgJADgLAAIgKAAIgJgCIgEACIgBADQAAAAAAABQAAABABAAQAAABAAAAQABAAAAABQACABAGAAIAMAAIAMAAIAMgBQAPABAGAGQAHAHgBALQAAAPgNAHQgMAIgZAAQgRAAgKgCgAgbAoQgCADAAADQAAAFAGABQAGACAOAAQAOAAAHgDQAIgCAAgGQAAgEgDgCQgDgBgIAAIgfAAQgFABgDADgAgNglQgDAEAAAHIAAAEQAAAHADADQADAEAHAAQAFAAAEgEQADgDAAgIIAAgDQAAgHgDgEQgDgEgGAAQgHAAgDAEg");
	this.shape_2.setTransform(-56.45,11.575);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAFArIAAgPIAFAAIACgBIABgEIAAggQAAgIgDgDQgCgEgHAAQgGAAgEAGQgDAFAAAMIAAAYIABAEIACABIAFAAIAAAPIgtAAIAAgPIAGAAIACgBIABgEIAAgqIgBgEIgCgBIgGAAIAAgPIAQAAIAMgBIAIgBIAAAPQAEgIAHgEQAGgEAKAAQANAAAHAIQAHAIAAARIAAAgIABAEIACABIAGAAIAAAPg");
	this.shape_3.setTransform(-66.725,10.375);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgWA8IAAgQIAGAAIACAAIABgEIAAgoQABgEgCgCQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAgBAAAAIgGAAIAAgOIARAAIALgBIAIgCIAABBIABAEIADAAIAFAAIAAAQgAgLghQgEgEAAgHQAAgGAEgEQAFgFAGABQAIgBAEAFQAEAEAAAGQAAAHgEAEQgEAEgIABQgGgBgFgEg");
	this.shape_4.setTransform(-74.6,8.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAFArIAAgPIAFAAIACgBIABgEIAAggQAAgIgDgDQgCgEgHAAQgGAAgEAGQgDAFAAAMIAAAYIABAEIACABIAFAAIAAAPIgtAAIAAgPIAGAAIACgBIABgEIAAgqIgBgEIgCgBIgGAAIAAgPIAQAAIAMgBIAIgBIAAAPQAEgIAHgEQAGgEAKAAQANAAAHAIQAHAIAAARIAAAgIABAEIACABIAGAAIAAAPg");
	this.shape_5.setTransform(-82.275,10.375);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgWAmQgKgGgFgJQgFgKAAgNQAAgMAFgKQAGgKAKgFQAKgFANgBQAUAAAKAMQALAMAAAUIAAAEIg4AAQABALAFAGQAFAFAJAAQAJAAAFgDQAEgFADgGIAOAJQgCAGgGAFQgFAFgHADQgIADgLAAQgOgBgLgFgAAQgHQgBgLgDgFQgDgFgHABQgHgBgEAFQgEAFgBALIAeAAIAAAAg");
	this.shape_6.setTransform(-92.15,10.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgWAmQgJgGgFgJQgGgKAAgNQAAgMAGgKQAFgKAKgFQAKgFAMgBQAVAAALAMQAKAMAAAUIAAAEIg4AAQAAALAGAGQAFAFAJAAQAJAAAEgDQAFgFADgGIAOAJQgDAGgEAFQgGAFgHADQgIADgLAAQgOgBgLgFgAAQgHQAAgLgEgFQgDgFgIABQgGgBgEAFQgEAFgBALIAeAAIAAAAg");
	this.shape_7.setTransform(-101.3,10.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgnArIAAgPIAGAAIADgBIAAgEIAAgqQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAIgDgBIgGAAIAAgPIARAAIAMgBIAIgBIAAASQACgKAGgEQAGgFAIAAQAJABAGAGQAFAGAAAKQAAAJgEAGQgFAEgIAAQgGAAgDgDQgEgDAAgFQAAgEACgDQACgDADgCIgCgBIgDAAQgHAAgEAGQgCAHAAALIAAAXIAAAEIACABIAGAAIAAAPg");
	this.shape_8.setTransform(-109.975,10.375);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgeAgQgLgLgBgVQABgUAMgLQAMgMAVAAQATABAJAGQAKAIAAANQABAKgFAEQgEAEgJABQgGAAgFgEQgDgDAAgGQAAgFACgEQADgDAGgBQgCgDgDgCQgEgBgGAAQgJAAgFAHQgGAGAAAOIAAABQAAAOAGAGQAFAHAIAAQAIAAAFgDQAGgFACgGIAPAHQgEAKgJAHQgJAGgQABQgWAAgMgMg");
	this.shape_9.setTransform(-118.6,10.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgYA5QgKgDgJgFIAAgaIAWAAIAAARIAKACIALAAQAGABAFgEQAFgDAAgHQAAgFgDgDQgCgDgHgCIgNgDQgKgDgIgEQgHgEgFgFQgEgHAAgLQAAgRAMgKQAMgKAVAAQAMAAAJACQAKACAHAEIAAAcIgVAAIAAgRIgIgBIgJgBQgIAAgFADQgEAEAAAGQgBAFADADQACADAGACIANADQAKACAIAEQAJAEAEAGQAFAGABALQgBALgFAJQgEAJgLAEQgLAFgOAAQgNAAgKgCg");
	this.shape_10.setTransform(-128.05,9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1btype, new cjs.Rectangle(-135,-4,278,25.6), null);


(lib.HEAD1atype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLALQgEgEAAgHQAAgGAEgEQAFgFAGAAQAIAAAEAFQAEAEAAAGQAAAHgEAEQgEAEgIABQgGgBgFgEg");
	this.shape.setTransform(-11.525,13.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUAqIgPgFIAAgVIAUAAIAAAMIAFABIAHABQAGAAAEgCQADgCABgGQAAgEgGgCIgLgEIgOgEQgHgDgEgEQgFgEABgKQgBgNAKgHQAKgIARAAQAKAAAJADQAIABAFADIAAAVIgTAAIAAgMIgFgBIgGgBQgGAAgDACQgEACAAAFQAAAEADABQACACADABIAJACIAOAEQAGADAEADQAFAGABAJQgBANgJAIQgLAHgRABQgLAAgIgCg");
	this.shape_1.setTransform(-17.45,10.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAFArIAAgPIAFAAIACgBIABgEIAAggQAAgIgDgDQgCgEgHAAQgGAAgEAGQgDAFAAAMIAAAYIABAEIACABIAFAAIAAAPIgtAAIAAgPIAGAAIACgBIABgEIAAgqIgBgEIgCgBIgGAAIAAgPIAQAAIAMgBIAIgBIAAAPQAEgIAHgEQAGgEAKAAQANAAAHAIQAHAIAAARIAAAgIABAEIACABIAGAAIAAAPg");
	this.shape_2.setTransform(-26.525,10.375);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXAmQgKgFgGgKQgFgKAAgNQAAgMAFgKQAGgKAKgFQALgFANgBQANABAKAFQAKAFAFAKQAGAKABAMQgBANgGAKQgFAKgLAFQgJAGgOAAQgNAAgKgGgAgMgVQgEAHAAANIAAACQAAAOAEAHQAEAGAIAAQAJAAAEgGQAEgHAAgOIAAgCQAAgNgEgHQgEgGgJAAQgHAAgFAGg");
	this.shape_3.setTransform(-36.6,10.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgWA8IAAgQIAGAAIACAAIABgEIAAgoQABgEgCgCQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAgBAAAAIgGAAIAAgOIARAAIALgBIAIgCIAABBIABAEIADAAIAFAAIAAAQgAgLghQgEgEAAgHQAAgGAEgEQAFgFAGABQAIgBAEAFQAEAEAAAGQAAAHgEAEQgEAEgIABQgGgBgFgEg");
	this.shape_4.setTransform(-44,8.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgKAwQgGgGAAgPIAAgqIgLAAIAAgNIAGgBQAFgBADgCQAEgCAAgGIACgOIASAAIAAAYIAPAAIAAAPIgPAAIAAAqQAAAGACACQADADAEAAIAEgBIADAAIAAAPIgGACIgJAAIgDABQgMAAgHgHg");
	this.shape_5.setTransform(-49.6,9.4018);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgmAlQgGgGAAgJQAAgLAHgGQAIgGAMgDIAagGIAAgEQAAgHgEgEQgEgDgGAAIgFAAIgEABIABADIABAFQAAAGgEADQgEAEgGAAQgHAAgFgEQgDgEAAgGQAAgIAEgFQAFgFAJgCQAKgDAMAAQAUAAAJAGQAJAIAAAPIAAAkIABAEIACAAIAGAAIAAAQIgfAAIgDgHIgDgHQgCAEgEAEQgDAEgGACQgGACgHAAQgMAAgHgHgAgKAGQgIAEABAHQAAAFACADQADACAFAAQAHAAAEgFQAFgFAAgJIAAgHQgMACgHADg");
	this.shape_6.setTransform(-57.05,10.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgmAqIAAgOIAug3IgQAAIgIABQgCACgBADIgBAKIgPAAIAAgdIBJAAIAAANIgtA3IARAAQAFAAADgCQADgBAAgEIACgJIAQAAIgBAeg");
	this.shape_7.setTransform(-66.2,10.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgWA8IAAgQIAGAAIADAAIAAgEIAAgoQAAgEAAgCQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIgFAAIAAgOIARAAIALgBIAIgCIAABBIABAEIACAAIAGAAIAAAQgAgLghQgDgEgBgHQABgGADgEQAFgFAGABQAHgBAFAFQAEAEAAAGQAAAHgEAEQgFAEgHABQgGgBgFgEg");
	this.shape_8.setTransform(-73,8.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAFArIAAgPIAFAAIACgBIABgEIAAggQAAgIgDgDQgCgEgHAAQgGAAgEAGQgDAFAAAMIAAAYIABAEIACABIAFAAIAAAPIgtAAIAAgPIAGAAIACgBIABgEIAAgqIgBgEIgCgBIgGAAIAAgPIAQAAIAMgBIAIgBIAAAPQAEgIAHgEQAGgEAKAAQANAAAHAIQAHAIAAARIAAAgIABAEIACABIAGAAIAAAPg");
	this.shape_9.setTransform(-80.675,10.375);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AghAjQgHgIAAgQIAAghIgBgEIgCgBIgHAAIAAgPIAmAAIAAA1QAAAIADADQADADAFAAQAHAAADgFQAEgGAAgKIAAgaIgBgEIgCgBIgIAAIAAgPIAnAAIAAA+IABAEIACABIAHAAIAAAPIgSAAIgMABIgIABIAAgOQgEAHgHAEQgGAEgJAAQgOAAgGgIg");
	this.shape_10.setTransform(-91.125,10.625);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAfArIAAgPIAEAAIADgBIABgEIAAgeQAAgJgDgDQgDgEgGAAQgHAAgDAFQgDAFAAAKIAAAaIABAEIACABIAFAAIAAAPIgrAAIAAgPIAFAAIACgBIABgEIAAgfQAAgIgDgEQgDgDgGAAQgGAAgEAFQgDAFAAAKIAAAaIABAEIACABIAFAAIAAAPIgtAAIAAgPIAGAAIACgBIABgEIAAgqIAAgEIgDgBIgGAAIAAgPIAQAAIAMgBIAJgBIAAAPQADgHAHgEQAGgFAKAAQAKAAAFAFQAGAEACAJQAEgIAGgFQAHgFALAAQANAAAHAIQAIAIAAARIAAAgIAAAEIADABIAGAAIAAAPg");
	this.shape_11.setTransform(-103.925,10.375);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAfArIAAgPIAEAAIADgBIABgEIAAgeQAAgJgDgDQgDgEgGAAQgHAAgDAFQgDAFAAAKIAAAaIABAEIACABIAFAAIAAAPIgrAAIAAgPIAFAAIACgBIABgEIAAgfQAAgIgDgEQgDgDgGAAQgGAAgEAFQgDAFAAAKIAAAaIABAEIACABIAFAAIAAAPIgtAAIAAgPIAGAAIACgBIABgEIAAgqIAAgEIgDgBIgGAAIAAgPIAQAAIAMgBIAJgBIAAAPQADgHAHgEQAGgFAKAAQAKAAAFAFQAGAEACAJQAEgIAGgFQAHgFALAAQANAAAHAIQAIAIAAARIAAAgIAAAEIADABIAGAAIAAAPg");
	this.shape_12.setTransform(-119.425,10.375);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgYA5IAAgQIAGAAIAEAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAgBIAAhHIgBgFIgEAAIgGAAIAAgQIAxAAIAAAQIgHAAIgCAAIgBAFIAABHQAAABAAABQAAAAAAABQAAAAABABQAAAAAAABIACAAIAHAAIAAAQg");
	this.shape_13.setTransform(-130.15,9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1atype, new cjs.Rectangle(-135,-4,278,25.6), null);


(lib.CO_v_white = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgyA1QgXgVAAggQAAgeAWgVQAVgWAeAAQAfAAAWAXQAVAVgBAdQAAAfgVAVQgVAVgfABQgdgBgVgUgAgvgvQgTAUAAAbQAAAcATAUQAUATAbAAQAcAAATgTQATgTABgdQAAgbgTgTQgUgUgcAAQgbAAgUATgAASAuQgCgDgCgKIgCgPQgCgIgFgEQgEgCgJAAIgGAAIAAAqIgRAAIAAhcIAfAAQAPAAAFACQAPAFAAARQAAAQgTAGQAGABADAEQADAEABAJQAEAVADAHgAgOgIIAOAAQATAAAAgNQAAgIgHgDQgDgBgMAAIgLAAg");
	this.shape.setTransform(133.8251,86.6356,0.4949,0.4949);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACmLBQgKgEgNACQgPADgIAAQAAgDgKgCIgOgBQgRABgHgCQAAgDgSACQgjgBAAgBIgUgCIgTgBQgLgCgHAAQAAgBgQABQgRABAAgDIgOgEQgJgDAAAHQgDAAgFgDQgEgDgDAAQAAAFgJgBIgNgDQgNgCgLACQgRACgYgKIgJgEQgEgCgEABQgCAAgIgEQgIgFAAgBIgMABIgMABQgIACgFgBQgDAAgDgEQgEgFgDAAIAAAEQgEAAgEgCQgGgDAAgEQgCAGgBAAQAAgDgIgDQgIgCgFAAIgBABQgBAAAAAAQAAgBAAABQgBAAAAAAQAAAAAAAAQgDABgFgEQgEgDgEABQgEABAAgDIgIgGQgHgFAAAEQgCABgMgFQgNgGAAgCIgTgJQgBABAAAAQgBABAAAAQAAABAAAAQAAAAABAAIgEABIAAAAIgEAAIAEAAQABADgQgGQgCgDgFAAQAAgGgDgCIAAAGIgFgDQgGgDAAADIgIgIIgOgCQAAgCgNgGQgNgGAAgCQgKgEgDgKQgBgDgJgBIgOgCQgTgKgBABQgEgCgCABIABgDQgCAAgQgKQgLgIgDgIIgLgDQgCgCgBgDQgBgBgFAAIgDgHIgCgHQgEgBgCACQgCACgCAAQgBgLgTAAQgPAAAAgBIgNgBIgMgBQgSAFgHgCQAAgBgYgBQgaAAgDgBQAAACgJgCIgNgDQgLAFgDgEQgNgEgCABQAAABgGAAIgHgBIgJgCQgDgCgFAAIgOABQAAABgOgEQgGAAgFgHQgCgBgNABIgMAAQgEABgcgDQgcgDAAgBIgJgDQgGgCgDAAIgXgDQgDgEgbgGQgagHAAgBQgCAAgEgCQgDgDgDABQgOACAAgEQgJgEgPAAQAAgFgKgBQgNgBgBgBQgLgFgFgDQgHgGgQgDIgYgEQgDgDgDABIgHACIgGgDIgHgCQAAgEgJgBQgJgBgCgFIAJgCQgBgEgMgEQgMgFAAACIgSgJQgFAAgIgGIgLgHIgMgEIgNgBIAVAVQAAADAHAGQAHAGABAEQADACAGAHQAGAGAEABQAKADAEAHQADAAAHADIAKAFIAHAEQAHAEAAACQAFAAAHADQAGADAEAAIAEACQABAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAFABAGAGQACAFAWAEQAVAEAAADIAYAKQADAAAGADQAFAEAEAAQACgBATAGIATAFQADAAAIAEQAGAEAEgBQAEgBAJAEQAKAEADAAQAAgBARAEIAVAFQAEAAAJACIANAEQAAABAOACIAQABQAAAFBNAGQADADAjADQAiAEAAABQBPAIAAgBQADgBAkAEQAiAEAAgBQAIgBAAABQgGAAgMAGQgOAGgFABIgMgCQgLgCAAADIgGABQgDABgDgBQAAAGgUABQgTABAAgDQgQACAAgCIgGACQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgLgBQgDgBgDgGQgDAAgCADQgBABgGAAIgNgBQgXgCgDgCIgFgFIgJABIgMgEQgKgDAAADQgGAAgKgCQgCgGgEABIgJAFQgFADgFgCQAAgCgLgCQgKgCgEABQAAACgWgEIgbgFQAAgCgOgBQgPgBgBgEQgHAAgLgDQgMgDgGgBQgCgCgNgBQgNgBAAgCQgGAAgJgCIgOgEIgNgEQgNgEAAgBIgNgCQgKgCAAgBQgFAAgGgCIgLgFIgDgBIgCgBQgLAAAQALQACACAGACQAGACADADIAKADQAAABAFABIAHABQAAACASADQAAADAaAEQAZAFABAHIgKACQAAgDgXgDQgZgDgCgDIgagHQgVgHAAgDIgZgIQgUgIAAgBQgIgCgKgEQgNgGgFgGIgIgFQgJgEAAABQgCAAgHgFQgIgFAAgCQgKAAgPgHQgRgJgCgJQgPgKgGAAIgIgIQgFgFgDgCIgGgIIgJgFQgGgCAAgDQgGgEgHgIQgHgJgDgGQgDgBgEgHQgFgHAAgCQgDAAgDgJQgDgKgEAAQAAgEgDgGQgEgFAAgFQgBAAgFgTIgGgYIgHgkQgHgjAFAAIgFgVQgBAAgBgLIgBgNQgDAAAAgNQgBgOgCAAIgJhUIAAggQAAgcACAAIgCgjQgBggAEAAIgCgxQgCgsAFgDQAAgEAKgaQALgZgBgEQAIAAAHgOQAHgPAGgCQACgBADgFQACgGADgCQAAgFAGgGQAHgGAHgBIgDgEQAAAAAAgBQAAAAAAgBQAAAAABgBQABAAABAAIAEgCQAAAAAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAHgHIAKgHIAFAAIAEgCQALgIgHAAQgCgGAFgEQAFgFAFAAIAIgDIAIgCQAKgFAKgJIAQgRQAGgGADgBIAFgDIACgEQACAAAOgLQAAgCANgFQANgGAAgEQAEAAAJgGQAJgHABgDIAOgJQAHgEAIAAQAAgBAGgDIAFgCIAJABQAGACABgDIAXgEQAOgEAAgJQADgBACgEIADgEQABgCAEgDQAEgCABgDIgBAAQAAgFAHACIAJACIARgCIAIgFIAKgEIAJgFQAHgEACAAIAEgCQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBQAFAAAFgCQAHgCAAgDQgHAAAHgHQAHgGAEgBIANgHQAFAAAGgDQAAgDAHgCQAGgCAAgEQAGAAAAADQADAAAEgCIAHgCIAKACQAGABACgDIAOgGQAJgGAEAAQAAgBALgEQAKgDAEAAQAAgCAHAAQAHAAAAgBQAJAAACgCQACgBAAgHIAFgDIAEgEIAJACIgBAFIAEgCIADgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAfAAAHgDQAEgBAGACIAKACQALgGgFAAQgCgJASgGQATgGAAAFQAMgIAZAAQACgDAJAAQAJABACgEIAXgEQAUgEAAgBIABABIAVgFQAWgFADAAQAVAAAAgEIAIgCQAHgBAAgBIAggHIAvgHQAOAAAggFQAggGAQAAQAAgFBQAAQAAABAGACQAHACAAACQgIAFgXgCIgQABIgRABQgJAAgRADQgSADgJAAQAAgChXATQAAAFArgFIAxgGIAugGIAbgDQARgCAJACQAUgDABAKQASAAAAABIAHABQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAABIgIAAQAAADg1ACQAAABgRADIgUACIgTAAQgSAAAAADIgwAHIgSACIgUACQAAADgMACIgQACQgIgBgPAEQgQAFgHAAIgMACQgMACAAACQgEAAgGAEQgHAEgDAAIgJAAIgJgBQAAADgQACQgPADgBADQgCAKgMADQgOABgIACQAAADgTAHQgHAKgHAEQACAIAiABQAfABAHgEQADgCAagEQAXgDAAgCIAMgCIAMgDQAAgBAGABIAHABQARgEAJAAQAAgBAcgDIAcgFQAfgDAAgBIAVgCIAWgCQAAgCAmgCQAngDAFABIApgDQAkgDAAACQAMgCAYACIAcgBQASgBALACQAAADAJACQAJACAAgCIAQABQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQADgBAKACQALADAAACQgEACgWABIgVAAIgmABQgCADgWAFQgVAFAAACIgQgBQgPgBAAACIgWAAQAAAFgZABIgegBQAAADglABQglACgBAIQARADAXgDIAngGQAAACAkgCQAjgBAAABQAFAAALgDQAEAAAEACQAFADAEAAIAQgBQAJABgEAGQgFAIghACIghACQhWAFAAADIgTACQgTACAAgCQgGgBgJADQgLADgDAAIgRACQgCACgGAAIgKgBQgGABgJAGQgIAGgGABQAAAFgdAEQAAABgHACQgIADAAABIgTADIgKACQgLACgBACQgRAAgMAMQgGABgKAFQgKAGgGABQAAgBgNAFIgPAFQAAgCgFABQgEAAgCACIAEABQgBADgMACIAAgEIgOAFQAKAIgUAEQgWAEAAACIgTAGQgNAFgGABQAAgCgvAQIgRAGQgRAGgCADQgTAAgDAEQgFAAgHAFQgGAEgFgBQgGAAgFAFQgGAGgFAAQgCgDgFACIgIAEIgKAFQgFACgFABQgBABgLADIgNACQAAAFgJACIgOADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABgBAAQgCADgEAAQgEAAgCADQgDAEgDACIgDADQgBABgEAAQgBgCgGgBQgFgCAAAEQgFAAgBAFQgDAHgCABQAAADgJAAQgOAJgCAAQAAACgMACQgLADAAAEIgMAGQgIAFAAADQgFABgFAEQgGAEgEABIgGADQgEACgCAAQgRAJgCAAQgEAEgFAAIgQAMQAAADgIAFQgIAEAAADQgGAEgOACQgBAEgEACQgFACgBABQgFAAgEAIQgEAHgDABQgEABgIAHQgIAFgDAAQAAAFgHAEQgIADgBAFQgSALgLANQgEAAgGAGIgIAKQgGAIgFADQgBADgFACQgFACAAAEQgCAAgHAJQgGAIgDAAIABADQgFAAgFAHIgHAKIgIAIIgHAJQgDAHgLANQgJALgBAJQADAAAGgHQAIgJACgBQAGgKAEAAQAAgDAHgFQAGgFABgCQgCAAAKgJIALgJQAGAAAEgJQAEgJADAAIAGgGQAGgFACAAQACgEAHgEIALgHQAAgCAEgFIAHgFIAVgPQADgHAUgGQABgDAJgEQAIgEAAgCQgBgEAGgCIAIgDIAWgOQAEAAAFgFQAGgEADAAIAhgUQAGgCARgIQATgJAAgDQAHgBACgDQAEAAABgDQACgDACAAQAHgCABgCIAIgEQAFgDAAgBIAGgDIAFgDQAAADAMgFQALgFACgDIAHgCQAFgCAAgBQAHgBAOgJQANgIAIAAQADgEAJgCQAIgCADgDQAEAAAGgEQAFgEAEAAQAFgFAIAAIAIgIIAHAAIAGgBIASgHQAAgBAGgCIAHgBQADgEAKgBIALgCQABgCAHgDQAIgEAAgCIAQgDQAAgCALgDQAJgCAEAAQAAgGANgBQANgBACgCIApgMQAhgJAAgFQAEAAASgFQARgGAAgBQAFAAAJgCQAKgCAAgEQAygGAAgEQALAAAQgFQATgHAHgBQAAgBAYgFIAbgFQAAgBAdgGIAhgHQAIgCANgBQAAgBAFgBIAHgBIATgEQAMgDAHABQAAAIgWAFIgeAFQgQAEAAACQgDAAgHAFQgHAFgFgBQAAAAgBgBQAAAAAAAAQAAAAgBAAQgBAAAAAAQAAACgZAIIgHAFQgEADgEAAQgDAEgGABIgMABIgbAJQgQAFgMACIgEADQgEADAAACQgEAAAFAEQAFADAAgEIAMgBQAKgBAAgCQAfAAgQAFIgHAEIgGAGQgCABgHgCQgEgBgCAGQgJgBgIAEQgKAEgIAAQgFAAgHAEQgGAEgEAAQAAAEAGAAIAGgCIAHgCQAAANgmACQgBADgGABQgDACgEgBQgEAAgDABQgBACgPAFQgFAGgSAAQgLABgBAGQgEgBgFACQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgEgCgBABQAAABgFAEIgIAEQgOAFAAACQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIABACIgGACQgEACgCgBQgBAGgKABIgOgBQAHAFgHADQgFACgGAAQAAgBgIAEIgIAEQgDAGgPAAQAAgDgGACIgEADQgBgDgEAFIgEAIIgGgCQgBAAgBAAQgBAAgBAAQAAAAgBABQAAAAAAABQgFACgIAAQgEAAgMACQgNADAAADQgDAAgEAEQgFAEgDAAIgbAKQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgDADQgEAAgDACQgDACgCAAQAAADgEABQgEACgDAAQgFgBgDAEQgEAFgDAAIgHAEIgFADQAAAGgKACIgOABQAAABgFADIgHADQgDABgHAIQgFAHgGgBQgHgCgJAJQgRAEgBADIgFACQgCABAAAEIgJgBQABABAAAAQABAAgBABQAAAAAAAAQgBABgBAAIgEAAQgBAAgBAAQAAAAAAABQgBAAAAABQAAABABABQAAAGgKAAQgCgCgGADIgJAEQgRAHgIAKQgJABgIAEIgPAJQAAAEgMAGQgMAHgCAFIgJAEQgGACAAAEIgMAFIgGACQgDABgCADIgCADIgEACQgJAHAAACQgDAAgCADQgDAEgCAAQgHABgFAEIgNAPQgHAIgJADQAAAGgOAJQgOAKAAAHQgEACAOALQAPANgBADQgFAAgGAKQgFAKgBAGQgDAAAPANQAPAMAAgEQAGAAAIAHQAIAHABAGQAAAEAKACQAKACACACIAMAJQAGAAALAGQALAFAGAAQAAAHArAAQAMAMAIAAQAAABAIAAQAJABABABIALAAQAGABAFADIAOAJQANAGAFgCIAKgCIALgCQAEADACAAQgCAEADACQACABANgBQAMAAACAEIATABIAIABIAJABQAAgCAPADIASADQADgEAGAAIALAAQABACAHAAQAHAAADADIAEAKQAEAIADgBIACAAIABgCIABgNQABgFAFAAIAKAAIAPACIARAAQAAgCAKADIAMAEQAAgFAKgCQAKgBAAAGIAugFIgBgCQADgCgDgPQgEgPABAAIgEgNQgFgMABAAQABgCgBgFQgBgFgCAAIgBgUQgBgFACgMQABgOACAAIAAgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBABAAQAFAAAAgZQACAAACgIIADgJQAAgFADgGQADgHABgFIAIgfIAIgQQAFgKAAgGQAEgCACgGQADgIADgCQAHgGgBgHQAMgMgBAAIAEgGQADgCACgEQgCgFAEgBQAAgCAFgGQAGgFAAgDQACgBAFgGQAFgHACAAQAAgDAFgDIAIgGQACAAAEgEQADgEAAgCQANgGAPgPIAFgCQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIgRANQgFACgFAIQgFAHgBAFQAGgBADgDIAGgIQAPgGAAgBQAIgCANgKQALgJAKAAIAIgBQADAAADgDQABgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQAAgDAEgBQAAgDAJgHQAIgHAFgCQADgBAFgEIAIABQACgCAFAAQABAAABAAQABgBAAAAQABAAAAgBQAAAAAAgBIAIgGQAHgGAAADQAGACAAgLQAGgBAFgEQACgCAJgCQAAgDACgDQADgDACAAQAAgCAMgGIANgHIACgFQABgCAEgBIAGgCIAGgFIAFgBIAFgCQAEgEAHgDQAIgDADgDQAFgEADACIAEADQADAHgOAHIgSAIQAAACgSAJIgMAJQgIAFgCAFQgEABgIAGQgIAGgGABQAAAIgLACIgMAJQgGAFgCAFQgIACgHAIQgCAAgDADQgDACgEAAQgGABgCAHQgIAEgCAJQgEACgEAFIgIAIIgPAMQgKAHAAAHQgNAGACANIgDAEIgCAGQgFACgBAJQgCAAgEAFIgFAFQgJAKAAgEQgDABgBAHQAAAGgIAAQAAABgEAEIgFAEIgBALIgGAJQgEAGgBAEIgMAKIgEAMIgGAEQgBACABAFQgBAAgEAHIgDAJQgDABgFAIIgHAHQAAATgIADQgGACABAJIAAANQgEAAgBAZQgBAZABAAQABgJAIgNQAKgOABgHQADAAAFgIQAEgGAAgDIALgUQACgBAFgIQAEgHAEAAQAEgPALgCQgCgKAMgGIANgPQABgEAJgIQAIgHAAgFQAFgCAGgIQAFgJAFgCQAAgDALgJQAJgIAFgDQAAgDALgHQAKgGAAgCQAGgEANgNIAPgNQAEAAADgFQADgFAEAAQACgEAHgGQAHgFAEgBQABgDAFgEQAHgEABgCQAIAAALgMQAMgMAGAAIAKgHQAIgFAAgCQADgBABgDQAAAAAAgBQABAAAAAAQABgBABAAQAAAAABAAQAIAAgCgGIAGAAQAAgCARgIQAQgJAEgBQAAgEATgKQARgJAGAAQADgGAJgFQAIgEAHgCQAAgBAJgEQAJgEACAAQACgCAUgJQATgIAAgBIAEgEQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAQABAAABAAIAGgBQAAgCAIgDIAIgCQADgDAIAEQACgJAFAAQAGgGAIAAQAAgCAHgCIAKgDQAFgHAZgGQABgCAGgBQAFgCACgCIAGgCIAHgCQAAgCAGgBQAGgBAAgBIAEADIAdgQQAAgBAMgDQALgCAAgCQAXgGAAgCIAJAAQAHAAADgEQADAAAPgJQABAAABAGQAAgIAVgEIAMgEQAJgDABAAQAQAKgEgHIgCgDQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAugJQACgEAXgEQAWgEAAgBIAIgDQAEgCADAAQAAgDARgBQATgCABgCQADAAADgDQADgDADAAQAAgCALAAQAngIADABQAAgCAvgIQAHABANgDIAVgGQAYgFAGAAQA9gJAGAAQAJgBAVgEQATgEAMAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAKAFQAIADAAgGIAUgCQA+gHAAACQADABAZgFIAigBQAfAAAAgCIBjgBQAAgCAoADQAsAEAEAAIAKAAQADAEAEgCIAIgCQACAHgDgBQgBAAgBAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgFAEgNAAQAAAAAAgBQAAAAgBAAQgBAAAAAAQgBAAgBAAIgFACQgEAAgDgCQgDgCgCAAQgNAHAAgEQgQACgIgCQAAgCgMABQgMACAAABQgLAAgKABQgCAFgGgCIgKgDQAAADgLAAQgKgHgCACIgDADIgFABQgDADgGABQgDAAAAAHQgMAAgCAIQgCAIAMAAQACADAKABQAKABADACQAAgFAHADIAKADQAAgEANACQAIABgDACIgFADQgCACgJAAQgIAAgEgCQAAABgHABQgGABgBAFQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgCADQgKAAgIACQgKADgHAAIgqADQgCAEgLAAIgRAAIgtACQAAABgfAEQggADgFgBQAAAGgzgBQAAABgIADIgJACQgYAAAAADQgFgBgOADIgiACQAAABgVAEIgYADQAAgDgKAHQgLAGAAACIAhAAIAbgEIATACQADAAAFgCQAEgCAFAAIAOgDQANgCAAACQAFABAHgFIAOABQAAAFALgHQAKgBARgDQAAgCAJAAQAGgBAFABQAGACAGgBQAGgCAFACQAAgDARgDQARgEAAAFQArAFAAgDIAJABQAGABAAADQgNAHgDgBQgFgBgKABQgLABAAADQAkgDBBACQANAAAaAEQAYADANAAQAlAAA5AKQArAFAAAFQAFAAAXAFQAZAFAAADIAIAAQAEAAABgEQAJgDAFAAQAFAAAFACQAAABAIACQAIACAAACQATAAAZAOQAPASgBAAQAAAGASAAIgLgKQgIgHAJAAQAGAAAJAFQAJAFAFAAQAqAWAEAAQAAABAPAEQAOADAAADQADAAAHAEQAIADADAAQAAABAoAOIAZAOQASALAAAHQAEAEAFACQAAACAJAIQAKAIAAADQAHAMACAAQAAADAEAGQAEAGAAAEQABAAACAHIACAJQAEAAAFATQAFATADAAIAJAUQAFAMAAAKQACAAAFAbQACAAAGAXIANAyIAHAaQAHAXgDAAQACAGADApQABADgCAFIgCAIQgCAAAAAGIAAAJQgCAAgDAIIgDAJQgDABgFAPIgFAPQgBADgDAAIgDAAIgBAGQgBAAAAAAQgBABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgIAAIAAAEQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgEACgBAGQgCAAgDAGQgDADgCgFQgHABgFAFQgEAAgCAIQgCAIgCABQAAAHgGADQgGADgGgCQABANgJgDQgMgEgCAEIAAAMQgCABgDADIgCADIgEACQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAGQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQgJgCAAABIgKAEQgEAAgCADQgCAAAAAFQgBAFACAAQgBAKgNABQAAgDgIgBIgLgCIgGADQgGACAAADQAAADgMACQgEABgKAFQgKAFAAADQgCAAgNAHQgNAHAAACQgFACgDAHQgCAFgHgCQAAACgDAEQABAAACAEQACADAAACQgGACgLgDQgLgDgFABIABAKQAAAGgFAAQgCgDgEACQgBABAAAAQAAABAAABQgBAAABABQAAAAABAAQADACABADQgEACgFAAIgJAAQgCAAgHgFQgHgEgFAFIgDAGQgBACgEABIgHAEIgFADQgBAFgJAAIgPgBQAAAHgJADQgLADgCADIgDADQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAgBgBQgCgDgDAAQgEgBAAAEQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAIAAAGIgMABQgDAAgGAFQgEADgDgHQgDgBgDAFQgDAEAAAEQgFAAgFADQgFADAAAEIgGgBIgHABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAADQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgEAAIgPADQgFAGgHACIgPACQAAAAgBAAQAAABAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAADABAGQAAAEgNgEIgHAFQgHAEAAADIgJgBQgEABgCAGIgJADQgHABgCgEQgGADgHAFIgMAIQAAAGgRgDQgSgDAAAIIgFgCQgBgBgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBAAgDAFQgDAEgCgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgGAHQgDAFgFgBIgEAAIgFACQAAAAgBABQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgFAFIgJAEQgHADABABIAYAAQAOgBAIgDQADgBAcgFQAYgFAAgDQADgBAFAGQAEAGAEgCIARgFQACgFAZgDQAAgBALgDIALgEIALgCQAJgBgBgDQARgHABAHIAPgGQAKgDAHABQgSALgFABIgpAUQABgGgKACQgIABgEAEIAEADQgEAAgUAIQgUAIAAACIgJABQgIACAAADQgFABgFgBIgJgDQgBAKgHgBQgMgBgCABQAAABgIABQgJAAABAEQgRAJgKABQgWADAAACIgIABQgGgBAAgBQgDgBgEABIgHACQgWAMAAgIQgDAAgEACQgFABgBADQgDgBgIADIgGADQAAABgVAEQgGAAgFAEQgGAEAKABQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIADABQAAgDARAAQAQgBAAgCQAIAAAWgHIAdgEIAkgGIAVgEQATgEAAABQAIAAAMgEIASgHQgBgBAOgFIAQgEIAVgIQAPgHAEAFIgUAKIgRAHQgGABgLAGQgMAFgEABQABADgKACIgNACQgKAGgLACQAAgCgMAIQgCAFgDgFIgDgDQgEABgFADQgFAEgDAAIgKADQgJABAAADQgFAAgGACQgGACgGAAQAAAJgLgMQgCAGgBAAQgDgFgJACIgLADQgFAGgBADQgFAAgEgDQgFgDgEgBQAAAFgGAEIgLAEQgXALgNgLQgMAEgDAAQAAAHgPAAQAAACgMADQgLADgEgBQAAgEgIAAIgMAAQgCAHgBAAIgHgBQAAACgVgBQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAADgJAAQAAgGgEAIIgDAEIgIAEQAAgEgHABIgIACQgCABgQAAQgOAAgBADIgYAAQgFAAgHgDIgMgDQgHAHgIAAIgRgDQAAABgKADQgKACAAABIgPACQgMACgEgEQAAgBgNAAIgRgBQAAAFgHgBIgKgCQAAADgPABIgFAAQgKAAAAgDgACUKCQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAdgDQAZgCABAEQABAAAAAAQABAAAAgBQAAAAABgBQAAAAABgBQACgDADAAIAEAAIADgBQAEgBAGABQAHAAADgBIAOgFQAJgCAHAEQABgGAEADIAFAFQADAAAFgFQADgGAEABIAHACQADAAAFgDQACgBAFAAIAHgCQAFgBABABIABAFQAEAAAEgGIAJgDIASgFIALgBQAHgBAEgDQALgFADAAQgFgBgPAEIgTAGIgfADQgPACgVgBIgWAEQgSACgBgEQgNACgBABQgKADgJgCQgKgDgNACIg1ADQgFABgCgFIgKADQgBgDgFgBQgIgBgCgCQgLAEgEgBQgMgDgagBIgagBQgFAAgJgCIgOgBIgMAAIgKgCIgBACQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgDgCgCABQgBgDgFgBIgHAAQgKgDgYgBIgOgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABIgDABQgLABgIgDIgFgDQgCgCgDABIgNAAQAAgCgFAAIgHAAQgDgBgEAAIgIAAQgEAAgDgCIgGgEIgPgDQgJgBgEgEQgFgEgBAAQgCACgEAAIgKgCQgGgBgEABQgBgEgMgDQgIgCgGAAQgDABgDgDQgCgCgDABQgDAAgGgBIgKgEQACABgSgIQgQgHAEgBQgCgBgHAAQgGABgDgCQgIgEADgCIgQgFQgDgBgPADQgRADgOgBIApAdQARgBALAEIANAFQAIgBAMAGIAMAFQAKAEAAACIAHgCQADgBACADIAGAHQACgBAIgBQAJgBABADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIASAGQADACAFAAIAIABIASAFQAEACAFABIAJABQAQAEAjAEQA8ALA6AFIAbACQARABALACIAhABQADgBALACIAQABIAMgBQAIgBAEACQABAAAAAAQAAAAABAAQAAAAABgBQABAAAAAAIABgBQABAAAAAAQAAABABAAQAAAAAAAAQAAABABAAgAGCH/IgCgHQAAgDAHAAQABABAHgBQAHgBABgCIAPADQALACAAgEQAGgHAHAFIAMAHQAGAAAAgDQgBgEADgCIAHgCQACAAACAEQAIgIAQgBQAJAAAQABQAAgBAFgCIAGgDIARAAQAAgCAPAAQACAGAEAAQAAgGAIgBQAHgCAAACIAJgCIAJgCQAAAAABgBQAAAAABAAQAAgBABAAQABAAABAAQADAAACgDQALgFAIADQACAAATgEIAGACQAAAAABAAQAAgBABAAQAAAAAAgBQABgBAAgBQAAgBAAgBQABgBAAAAQAAAAABAAQABgBAAABQAFACABgBQAAgCAPgDIARgDQABgCAOgFQANgFAEAAQADABAEgEQAEgDADAAQAAgDAQAAQAGABALgHQAGAAALgFQALgGAGAAQACgDANgEQANgFAFAAQABgCAMgEQALgDAAgBIAVgIQADAAAEgCQAEgDAEAAIAKgEIAHgDQAEgCAEgBQABgDAGgBQAGgCACgCQAEAAAIgDQAJgEACgCQAEAAAHgEQAHgEADgEQAFAAAJgFQAIgFAGAAIAYgMQAAgBAVgIQAWgJACgDQAFAAAJgFQAIgGAGAAQAFAAAGgGQAHgHADAAQAEAAAGgGQAHgGADAAQAHAAAKgIQAEgCAHgHQAAgBAGgCQAGgCAAgCQgHAAAGgCQAFgCADAAQAAgEAJgBQAHgBADABQAAgDADgEQADgFAAgFIAQAAQAAgEAEgCIAIgFIANgIQAAgFAMgGQALgGAAgCQAMgCADgDQAGgEADgJQAFgBAQgbQAMgGAGgKIACgEQABgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAQADAAAFgJQAFgKAFAAQADgFAAgJQAFgDgBgEQABAAACgMQACgNACAAQAAgBgCgFIgEgGQAAAHgLAAIgFAGQgEAGACAAQAAADgHAGQgIAFAAACIgFAGIgGAIQgDAAgFAFIgIAFIgFADQgFADABAEIgJADIgHADIADAAIgBAEQADAAgMAKQgDADgIAAQgHABgCACQAFAAgFAHQgFAGgEAAQgJAMgOADQgEAIgOAFIgCACQgBAAgBAAQAAABgBAAQAAABAAAAQAAABAAAAIgKABQgCABAAAHQgbAFAAAGQgPALAAABIgJADQgGACgEAAQAAADgFACQgEACgEAAQgEgGgEAHQgEAHgCABQAAACgKAGIgMAGQgEABgIAGQgJAGAAAEQAAACgMAEIgQACQAAAEgJACQgJABABAEQAAABgaAFQAAAHgOAGQgLAFgKABQAAgFgOAHIgOAGQgDAAgJAEQgIAEAAABQgEAAgHADQgHADgEAAQAAACgJAEQgIADgCgBIgBADIgBADQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgDABgCgCQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAFIgDAAIgCgBQAAADgFABQgGABAAABQgEACgCgBQgDAAgDACQgDADgMAAIgIAGQAAABgKADIgNADQgNAGgDAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAAAABIgYAKQgYAGgGAEQAAADgXAAIgHAEQgEABgBAFQgFACgEgBIAAAFIgPAAQAAAGgGABQgHACAAgCQgDAAgLAFQgJAEgFgBQAAgBgGACIgHACQgDADgIAAIgMgBQgCAEgLAAIgbAJQAAABgFACIgJADQgFADgKAAQgDgDgDACIgFAEIgKgDQAAAHgNABIgTABIgIABQgFACgBADIgMgBQgcALgDgBIgUACQgSADAAACIgPADIgOACIgHACQgFACAAABQgIAAgQACQgVAEgDAEQACgCATAAQAAAEAZAAQADgEALABIAQACQAAgEANACIAOABQACAAADADQADACADAAIAAAAgAn2HeQgCAEgDAAIANAKQAJAGAEAAIADgDQABAAAAgBQAAgBAAAAQgBgBAAAAQgBgBgBAAQgBgDgGgFIgKgFIgDgCIgCACgAAUGwQACAEACAAIAIACQAFABACgEIADgBQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAgBAHgBQAHgCAAgBQAigBAAgFIAGABQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAFgBANADIAJgDQAGgDADAEQACADAFgBQAFAAACgDQACgCAFACIAIACIgEgEIADgGIAKgCQAGAHAAgFIASABQAFgCAHgHQACgBAKABQAJABADgDQAEgEAHAAIALABQACgFALABIAOABQAAgDAHABIAJADQAAABAKgHQAKgBAOACQAAgIAPgBQAAgBAVgEQAVgFADABQABADAMAAQAMAAACgEIACgFQAEgEADAFQACABAEAAIAGAAQAAgIABgCQACgBAIABQABAEAHgDIALgDQAEgBAKAEIAIgEQAAgFANgDIARgCQAHgDAEgGQADgCAHABIALABIgBgFQAEAAABgCQACgDADgBQADgBADABIAHACQAAgCAPgCIASgBIgCgEIADgBQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAJgBAHgEQAJgHAFgCQAXAAADgFQANAAABgCQAGAAgDgGIAKgBIAEgGQABgBAAgBQABgBAAAAQABAAAAAAQAAAAAAAAQADABADgCQADgCADABQAAACAHAAQAHAAAAgCQAHAAAEgDIAJgIQAHgBAEAAQACgEAEABQAGACACAAQAAgBASgGIAUgIQgDgDABgCQACgCAFAAQADADAFgCIAIgDQAAgBAHgBQAHgBAAgDIAGACQAIgFgEAAQgBgDAPgEQAQgEAAgCQAHAAAHgDIAOgIQABgCAIABQAHABAAgEIADgDQABgCAFAAQAEAAAHgDQAAgBAKgDQAKgCADABQgBgFAFgDQAGgEACgDQAPABAAgDIAHABQAEAAABgEIAKgIQAAgDAIgEQAHgFAEAAIALAAQAAABATgLQAAgDAHgFIAIgFQAGAAAIgHQAIgIAFAAQAAADASgNQAIgGAKAAQAUgNAAgCIAWgPQALAAAMgIQADgHAEAAQADgDAJgDQAJgEACgDQAFAAADgGQADgHADAAIAKgHQABgDAEgEIAHgGIAGgCQAFgBABgCQAAgFANgGQAMgHgBgDQAVgZADgBIAHgPQAFgKgHgDQAAgCgHgEQgIgDgBgDQAAgDgEgCIgHgFQgMgLgGgDIgQgHQgNgHAAgDQgGAAgJgFQgKgGgEgBQAAgBgJgFIgKgHQgEgBgIgFQgHgFgEAAQAAgBgSgEQgUgHgDgDIgQgIIgKABQgHABgEgBIgFgCIgHgBQgRgLgDAAQAAABgSgHIgJgDQgDgEgGgCIgKgBQgtgKgGgBQgGgHgWADQgSACgDgEQgDgEgHAAQAAgBgOACQgPACAAgDIgTgBQAAgEgGgBQgHgHgIAEIgNAFQgHAAgKgEIgRgGQAAAFgXgBQgWgBAAgJQABgEgFgBQgEgBgFABQgCADgIgCQgBgBgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAADgJgBQADAHAAAEQAHAAACAeQACAcgCAIQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABABQAAAAAAAAQgBABAAAAIgBAUQgBATgEAAQgBADADADIgIAQIgGANQgFAIAAAGIgGAPQgFAOgHAAIABAFQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIAAAEQgCAAgCAGQgBAGgDAAIAAAEQAAABgBAAQAAAAAAABQAAAAgBABQgBAAAAABIgFAEIgBAHQgDAAgBAFQgBAAgGAIQgHAJgFABQgBADgIADQgIACABAFIgCAFIgCADQAAACgEAEIgGAFQAEAKgSACQgBAGgHAEQgIAGgCADQgFAIgTAJQgCABgDAEIgFAFQgJAAgRAOQgUARgFACIgNAFQgJAEAAAEIgLAHQgGAFgGABQAAgBgFAFQgFAEABAAIgKAFIgKAGQAAABgLADQgMADAAAEQgJAAgRANQgSAMgMAAIgKADQgIAEgBABIgJAHQgFAFgFAAQgeAKgEAAQAAACgJAGQgJAFAAgEQgEAAgHADQgHAEgDADIgLACQgFABgEAFQgFAAgKAGQgJAGgEAAQgDAFgVAAQgCADgDACQgEABgBACIgGABQgEABgCgCIgGgDQgHgBgGADIgKAIQgBAFgNAEQgDAAgIAFQgHAEgEAAQgsANgHAAQAAADgZAHQgaAIgDADQgTACghANQgHADgOAAQAAAGgPAAQAAACgVAGQABgGgiAKQgEAAgGACIgKAEQAAgBgMAEIgPAFQgIAGgMACIgWAFIAFAAIABABIARACQAOACABgDQAcAAASAEQAsgBAAAFQAFABAvgHQAHgDAHAEIANAHQAAgCAQgCIAUgCIAQgBQAEABACADgAqtGZQgHgMAAgBIAHAFIAGAEQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIADgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgGAAIgCgBIgBAAIAAgBQgDgDgDgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgDgBQgjAFAAgEIgJgBIgIgCQAAgEgOACIgQADQgGAJATADQAWADAAABIAVABQARAAAAACIASAAIAAAAgAopGGQgDABAAAFIADAEIAEAFIAHgBQALAAgJgLQgFgEgEAAgAmTFsIAIAOIAFAFIAOACQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAIAOgCQAJgCAEABIBCgLQAAgCAVgDIAYgEQBOgSAHAAQAAgBAXgGQAXgFAEAAQAAgDAWgEQAWgDACgEQAHAAAKgEQALgDAGgBQAGAAALgEIAQgFQACgDAdgHQAagGgBgHQAYgBAAgDQAJgBARgHQAAgBAJgCQAJgCAAgBQADAAADgCQABgBAAAAQABgBAAAAQABAAAAgBQAAAAAAgBIAGgBIAFABQAAgDAQgFQAOgEAFAAQACgDAJgDQAKgCAAgDQAEAAAIgDQAJgDACgDQAGAAALgEQAJgEAFgEQAGgFAPgDQABgCANgEQANgEAAgCIANgGIAOgHIAPgFQAKgEADgEQACAAAJgFQAIgEAAgBQAEAAAIgEQAIgFADgDQAKAAAOgKQAOgKAIgBQACgEAUgJQATgKgBgCQAAgBANgHQAOgHAAgBIAHgGQADgDAFgBQAKACAEgGIAEgIQAEgIAFAAQAAgBAFgEQAGgDAAgCQAFgBAIgHQAIgHAFgBQADAAACgFQACgFADgBIAIgFIALgKQAEgCAFgHQAFgHAEgCQAAgFAOgMIAOgRQACgEAFgIQAGgIACAAQABgGAFgHIAGgMQACAAACgFIACgGIACgHQACgGgBgDQgFAAgJAOQgKAQgEACQAAAGgMAJIgLAKQgGAHgEACQAAAFgHAFIgKAKQgBACgIAFQgHAEAAAEQgDABgDAEQgDAEgFABIgEAFQgEADgCAAIgHADIgIADQAAACgEADQgFAEgBADIgKAGQgHAGgBACQgDAAgJAGQgJAGgCADQgKADgQANQgPAMgMACQgFAGgMAEQgLAEgIAAIgOAOQgFAAgHAGQgHAFgDAAQgCAEgIABQgHABgDADIgHADIgGADQgCAAgEAEIgFADQgCAEgJAAQgJABgDAEQgEACgDAAQgCAEgIABIgNABIgJABQgGAAgDABQgDABgDAHQgDAGgEABQgEAEgFgCQgHgCgDABQAAAEgFACQAAAEgVAJIgbALQgDAAgFADQgFADgDAAQAAACgNACQgEAEgIADQgHACgGAAQAAACgNADQgNADAAADIgNACQgKACgCADQgGAAgCABQgDABgFAFQgHAAgGACIgNADIgWAHQgBACgKACQgKACAAACIgbAHQgFAAgIADQgIADgFAAQgCACgOAEQgNADAAABQgDAAgFADQgFADgDAAQgBACgGABQgFABgCgCQgRAHgCAAQgDADgNADIgMACQgEABgKAEQgIADgEAAQAAACgOAAIgQgCQAAABgJADIgMACQgPAAgMAFQAAAFgLACQgMABAAABIgXAAQgQAAgFAFIgDACIgDADIgJADIgHACQgCADgcAEQgcAFAAACIgFAAIgFAAgAxuEwQAAgCgHgCQgFgCgEAAQAAAGAQAAgAzoD+IgCADIAOALIAKACIALACQAEAHAcAKQAbAKAAgGQgOAAAAgHQgQgCAAgCIgUgKQgCAAgEgIQgEgHgGAAQAAgDgKgBIgKgBIAAAAIgGACgAmhD9QgJAEgBADQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAIADAAQAAACAsgFIA0gGQAAgDAWgEIAcgFQABgDANAAIARAAQAFAAARgGQANgEAIACQAAgCATgDIAWgEQAAgFALACQAMACAAgEIAKAAQAGAAADgEIAJgDQAFgGAQACQAQABACgFQgIAAAHgEQAGgEAEAAIANgBIAEACIAFABIASgEQAAgCgFABIgHABQgDgGAcgHQAXgHAKAAQAAgBALgCQALgBABgCIAHgCIAHAAIADADIAFABQAAgBAAgBQgBgBABAAQAAgBAAAAQABAAABAAQgCgFAEgBIAJgCIAKAGQAKAGADgBIgHgDIgDgKIAGgFQADgBAFACQACABAMgFQALgFAAAEQADABAEgCQAEgCAAgCQAOAAADgFQAAgJAJAAQACgEAKAAIANAAQAFgBADgEQADgEADAAIAVAAIAEgJQADgDAEABIAGADQgBgJAGABIALADQADAAAEgDQAEgEADAAQACgCAJgFQALgFABACQAAgHAUgCQAUgCAAgCQAIAAAFgBIAFgDIAGgDQACgDALgDQAMgDAAAGQAEABAOgEQAGgEABgFQgEAAAEgHIAFgIQAEgCAAgJIANgHQAJgFAGAAQABACAKACIAMACQAAAEAMgGQALgFACgEQgHAAgCgMQAFAAAMgPQASgEAAgCQAMgCAOgGIAWgKQAFgFARgHQAOgGADgHQAGgCANgOQALgMAHAAQACgDAFgDQAFgEACgDQACgCAHgGQAHgFAAgEQACAAAFgIQAFgHAAgCQAEAAAJgXQAKgXgCgFQgCAAAAgMQABgMgEgCIADAAQgBAAgDgHIgHgRIgSgBQAAACgPgEQgPgDAAADQgmAHAAgBQgLABAAgCIgIABQgFABgDgDIgHABIgJABQAAgBAAAAQAAAAgBAAQgBAAAAAAQgBAAgBABIgGABQAAAEgMABQgLABgFgBIgPgBIgDAFQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIgOABQgCAHgNgEIgUgGQgBACgIABQgFABAAAHQgYAAgEABQAAADgUABQgUABAAACIgZABQgLAAgDADIgBABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgQABQAAABgGACIgIABQAAgBgSADQgTACAAACIgMADQgIACgFAAIgJAIQAAAEgJgHQgDAAgBADIgCAFQgBADgEABIgGABQAAAEgMAAQgBACgEABQgEABgDADQgDADgGAAQAAgEgGABIgKACQAAAFgWgCQAAAGgJADQgLADgCACQgCAAgEADIgHAEQgEACgCgBQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgDAAgCgCQgEgCgCAAIgIADIgIACQgDgCgEACIgHADIgEAEQgEAEAAACQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABIgBAEIgEAFIgCAAQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgDABgCgCQgDgCgCABQgFAJgVACIgUAMQgKAEgEgDIAAgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAQAAgBgKAHQAAAHgEABIgIgCQgBgBgHADQgHADgBACQgFAAgDADQgDADABAEIgMACQgNADgEAFQgEAAgBAFIAAAGIgRAJQgEAGgIAAIgMgCQACAMgGACIgMAHQgMAIAAgFQgGgEgBADIAAAEQAAADgKAIQgLAGgEABQAAACgGAEIgKADQAAgGgFAEQgHAFACAAQAAAFgHAIQgGAHgFAEQgCAFgFADIgKAEQgJADgDgEIgIAHQgFAFAGAAIgCAHIgGAJQgFAGgCAAIgKAJQgHAHgCAEQgGAAgCADIgEAJQgEABgEAFIgGAHQACAEgZAYQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIAPgBIAqgFQAAAFARgHIAFAAIADgCQAAAAABAAQABgBAAAAQAAAAABAAQAAAAAAABIAEACQABgFAKgDIAJgEQAGAAAVgEQASgDAEAIQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAgBABAAQACgEACAAQAAgBAFABIAHAAQAAgBAGAAIAJgBQAAABAAAAQAAABABAAQAAAAABAAQABAAABAAQAAgKAqAAQAAgEAKgBIAOgBQAAgHAZgBQAZgCAAADQADgBAEgEQAEgDACAAQAAgCAHACIAIACQAAAHAVgMQAAgCAHgDIAJgCQAFAHAHgBIARgDIAOgBQAHgBAAgGQgEADgEAAQAAgEADgCQAEgCABgCIAOgCIAGgCQAAgFALAAIAPAAQAHAHAGgGQAJgKAEgBQAMAAAAgCQAFAAADAFQACAFgHAAQAAAEAHACQAGADAAgFQgEAAgBgDQAAgEAEAAQAAgCAKAAIAGgEQAFgCAAgDQAHAAAEgDQABgCAEABQAEABACgBQAEgHALAAQACABAHgDIAIgEQAVgLAAAFQALAAgDgBQgIgEgBgCQgHgCAGgCIAJgBIAFAGQACACAEABQAMAAAAgCIAYgLQAFAAAJgEQALgEAFAAQAAgEAMgEQAKgDAFAAQABgCAFgCQAFgCACgCQAQgEACAAQAEABADgDQAFgFADgBIAJgFQAHgDACAEQACADgLANQgEAAgHAGQgIAFgEAAQAAAFgNAGQgOAGgCAEQgCAEgKACQgIABgCAEQgEAAgHAFIgJAHQgcALAAgBIgTAPIgMAEIgLAEQgZAGgGAIQgGgBgGAEQgGADgEAAQAAABgMABQgLABAAAGIgQADQgLACgEAEQgMAGgHABQAAACgJADIgKAEIgEAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgKADQgEAGgJABIABADIgGACIgHACIgJAAQgFgBgEABIgKAGQgKAFAAgBQgIAAgPAFQgPAFgJAAQAAABgWAEQgWAEAAADQgdALAAgEQgEAAgIAFQgHAFgEAAIgQAFQgRAEgBABIgZAFIgkAJQgaAAgCAEIgIACIgIACQAAgDgUAHIgNAEQgIADgHAAQgKADgFAAIgTAAQgFAFgMAAQgNgCgFABQAAABgIACIgLADIgBgBIgIACgAz3D2QAEgHgIgCQAAgBgEgEIgFgFQgDAAgIgFQgHgEgEAAQgBgDgHgGQgHgGgDAAQAAgCgLgIQgLgIgEAAQACAFAGAIQAGAHAFADQANAKgCAAQADAFAGAAQAWATAAgCQACABAFgCQAAAHALAAgApzCuIAGAEQgEABgCADQgDAEADADQAFADgDADIgEAEQATgEAAgBQADgBAFABIAHACIAEgBIADgDIADgBIAKgCQgFgZACAAIgCgJQgCgGABgDIACgOQABgIABgEQADAAgBgIQgBgIgGgBIgMASQAAAFgGAJQgGAJABAEQgGADgCACIgEAJQgCAAgCAEIgDAFQAAAEgIgGQgBABAGAEgAnqBaQgEAAgDAIQgEAKgDABQgDAVgBAAIAAACQgDAAgDAUQgDAUACADQADgBAFgIIADgIQADgHACAAIAFgLQAEgIACAAIADgHQAEgFAAgDQACAAAEgJIAFgLIAIgGQAHgGAAgCQAEAAABgDIABgIQACAAACgDQABgEADAAQAIgJABgEQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIACgFQAIgFAHgLQAEAAAGgJQAFgJAGAAQAegLgOAAQAAgGAFgCIAJgDQAAgGAIgEQAIgEAAgFQAFgBADgEQAEgFADgBQACgDAMgGQALgFAAgEQAKgGAGAAQAAgEAIgFQAIgEAAgDIAGgEIAHgEIAHgFQADAAAIgHQAIgGABABIALgGQAIgFACgDQAHgFABgGQAFAAAGgBQAGgCAJgGQAAAHAMgIIAPgKQACAAAGgEIAHgGQABgBAIgDIAIgDQAhgKAAgDQAFAAAJgEQAIgDAGAAQABgEAFACQAHABACgIIAGgCQACAAAHgEQACgCAOgEQANgDAAgCIAJgDQAGgDAAgDQAQgCAAgBIAJgCQAHgCAAgBQAFAAAKgEQALgFAGgBQAAgBAIgDIALgCQA2gRAEAAQAAgBAOgDIAQgEQATABAAgGQAFAAALgDQAKgDAGAAIAfgIQAAgCAMgBIAOgBQAAgCAMgCQAMgBABgCQAEAAAGgCQAHgDAEAAIAMABQAHgBADgDQAXgCAKgDQAAgEAygEQADgFAeAAQASABARgEQAAgFA4gBIA+gBQAAgCAGABQABAAABAAQABAAAAgBQABAAAAgBQAAAAAAgBIADAAIgBgCQgEAAgEgIQgFgIgDAAQAAgDgHgHQgHgGAAgEQAHgCAJADQALADAAAIQAEABAFAEQAFAEACAEQADACAAAFIADABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAEADQAEgBAEABQAGABAMgBIAUAAIAmACQAhABAAABQAIABAHgBQAAgCAUACIAZADQArACAAACIAzAEQArAFAAAGQAKAAAUAFQAVAEAKAAQAAACAPADQAPACAAACQAHABAKAEQAJADAHABQADABAHADQAGADADAAQAAADAJAAQAKABABACIAcAJQAEAAAIAEQAJAEACADQAOAHAAgDIAEABIACACQAEAAALAGQALAGAAABQAFAAAIAGQAIAFAEAAQAAABAHAFQAHAEACAAQAAABAIADQAIAEABACQADADAKAFQAIAFADAEQAHAAgHgJQgGgKgFAAIgEgEQgEgDAAgCQgIAAgHgKQgEAAgKgJQgLgKAAgDIgLgBQgHgCAAgEIgDgCIgGgBQgIgIgCgBIgOgHQgGgEgHAAQgEgFgKgDQgEgBgBgCQgCgDgCgBQAAgCgSAAQAAgGgLgCIgPgCQgHAAgHgDQgIgEAAgEQgIAAgNgJQgNgKgHAAQAAgBgKgCIgKgBQgZgHAAgCIgPgDQgIgDgEAAQAAgEgdgGQgZgEgKAAQAAgCgOAAQgPgBAAgEIgXgDQAAgDgbgCIgbgDQgZgDgMAAQAAgBgMgBQgMgBgBgBIgbgBQAAADgogCQgBgCgOAAQgNgBAAACQgDABgGgBIgIgBQgRACgIgBIgKADQAAABgKAAIgMgBQAAADgVACQgVABgFgBIgwAEIg5AEQgFAAgYAEQgZAEAAACIgXACIgUADQAAAHgyACQAAADgkAGQgCADgJAAQgJAAgDAEQgFgBgGACIgJABQAAACgOABQgNABAAADIgeAJQgSAFgLAAIgdAKQgeAJgCgBQAAAEgNACQgOACgBAEIgOAEQgIACgFABQAAABgHADIgIACQAAABgKAEIgPADQgCAEgLADQgLADgCAEQgEAAgGADQgHAEgDAAQgVAFgFAHQgFAAgIAGQgJAGgFAAQgDADgHAEQgHAEgEAAQgCADgPAIQgEAAgJAHQgIAHgHgCQgBAEgJAAQgBAEgIADQgNAFgHAGIgPAJIgPAJIgJAIQgEAFgFAAQABgCgKAHQAAAGgYAPQgLAMgKAEQAAABgEADIgGAEQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAABgFAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQgDAEgMAHIgDAEIgEAEQAAADgEAEQgDAEgDAAIgFAHIgHAFQAAACgJAIQgDADgEACQgFABgDADQAAADgEACQAAADgDACIgGAEQgCACAAAEQAAAFgCACIgFADQgDAAgCADQgCAFgBAAQgBACgEAGQgEAFgCABQAAAGgJAGQgKAGAAAGQABAAgFARIABAIQgBAFgDABIgBABIAAAAIgBABgAxpmXQgDABgCACIgCAFQgHAAgCADQgCAAgGADQgFADgCACIgHADIgGADQgGAHgTAGQgCAEgKACQgKABgBADIgHAGQgGAFAAABQgOAAgBAHIgSAOQgEAAgPAKQgJAGgGAHQgCADgFADQgFADgCADQAAAHgIAEQgKAEgBAFQgCABgDAGQgCAEgDABQgBACgGAFQgFAEAAADIgJAJIgIALIgDACQACACAlgbQAmgdAHgBIAHgFQAEgDADAAQAAgBAEgCIADgEQgDgBAAgEIAMgBQAIgCACgCIADgCQAAgBABAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgCAGgDQAFgDACAAQACgDALgFQAJgEACgDQADAAAFgFIAHgHQAMgEABgBQADAAAHgEQAJgEADgBQACgCAHAAQAEABABgFQABgJANAAIAHgIQACgDAFABQAFABABgDQACAAAHgEQAHgFACgBQAAgCARgHQAQgHADABIgBgEQAGgBAHgEQAHgEAFgBIALgFQAHgEACgDQADAAAFgCIAHgDQACgCAFAAIAIABQACgFADgCQAGgHAPgDIAYgDQACgDAIgDQAIgDAEAAQAAgDAIACQACABAEgCIAGgEIAIgEQAEgCADAAQAEgGAOgEIAWgEQAGgBALgDQAOgEAAgDIAHgCIAFgDIAJABQAFgBAAgFQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAABgBIACgDIgGgDIgvAMIgCgBQAAACgLABQgKACAAABQgHAAgLAGQgLAGgGABIAAgDQgFAAgKADQgJADgFAAQgEgBgCADIgFAEQgEAEgCAAIgHgDIgIAEQgIADgBAEIADABQgBADgFAAQgEABACgEQgDAAgHADQgHADgEAAIgFACQgGADgBACIgDAFQgDABgDgBQgCAGgOAFQAAABgFABQgFAAAAABIgLACQgEABgCAHIgDABQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgKAAAAgCQgCAAgDACQgEADgCABIgOAHQgNAIACABIgNAGIgNgCIgDABgAlSlJQgFgDAKgGIALgHQAIgDAAgBQABgBABAAQAAAAABAAQABAAAAAAQAAABABABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQACACgOAJQgJAGgFAAIgEgBg");
	this.shape_1.setTransform(7.7928,27.7457,0.4948,0.4948);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABwDnIAAkXQAAgygageQgbgeguAAQgfAAgdAPQgdAPgkAjIAAFEIhjAAIAAnEIBjAAIAAA8IADAAQAdghAogSQAngSAqAAQBLAAAvAtQAxAxAABZIAAEWg");
	this.shape_2.setTransform(117.997,94.1892,0.4949,0.4949);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjCCoQhLhEAAhnQAAhiBNhCQBNhDBxgBQB2AABNBCQBNBBAABlQAABqhMBCQhMBDh4AAQh1AAhLhEgAh4hvQgvAqAABCQAABGAuAsQAtArBIABQBPgBAugqQAugrAAhIQAAhBgwgrQgxgrhKAAQhGAAguArg");
	this.shape_3.setTransform(90.4194,94.4243,0.4949,0.4949);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiqEwQhCgnAAg8QABgyAegeQAfgfBBgOQgygbAAgeQAAgWAWgRQAWgRAjgIIAAgCQg3gVgdgkQgbgjAAgyQAAhIA8gqQA7gqBkAAIDRAAIAABFIhoAAQAeAbAMAWQALAVAAAdQAAAbgPAeQgNAcgTARQgiAghdAPQgoAGgOAGQgXAJAAARQAAASAnAOQAiAMBQAOQBNAOAlAjQAhAfgBAuQAABEg/AmQg/AmhvAAQhmAAhBgmgAhtCYQggATAAAeQAAAiAkASQAkASBEAAQBBAAAlgRQAlgSAAgfQgBgmg7gUQgsgOg9AAQgyAAggATgAhIjvQgdAYAAAhQABAlAbAXQAcAXAtAAQApAAAcgYQAbgYAAglQAAgggdgYQgdgYgnAAQgpAAgeAZg");
	this.shape_4.setTransform(64.4501,100.1526,0.4949,0.4949);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABoAAQBmAAA5A+QA8BAAAB7IliAAQAYCHCQAAQBVAABbg2IAABXQguAcgsAMQgxAOg9AAQhxgBhEhJgAhPiAQgjAdgKA2ID9AAQgDg0gfgeQgggeg0AAQg4AAgiAdg");
	this.shape_5.setTransform(39.7057,94.4243,0.4949,0.4949);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ai3DnIAAnEIBkAAIAABoIACAAQBHhxBKAAQA6AAA/A1Ig1BNQgXgTgbgNQgagMgSAAQgzAAgjAoQgjApAAA6IAADsg");
	this.shape_6.setTransform(19.9101,94.1892,0.4949,0.4949);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Aj1DJQhahSAAh3QAAh3BchTQBfhVCUAAQCWAABfBVQBbBSAAB4QAAB3haBSQhfBXiYAAQiVAAhfhXgAitiYQhGA8AABcQAABcBGA9QBFA9BoAAQBpAABFg9QBFg8AAhdQAAhchFg8QhFg9hpAAQhoAAhFA9g");
	this.shape_7.setTransform(-9.6965,91.7272,0.4949,0.4949);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABnAAQBnAAA5A+QA8BAAAB7IljAAQAMBCArAjQAqAiBIAAQBUAABdg2IAABXQgwAcgrAMQgwAOg/AAQhvgBhFhJgAhQiAQgjAdgKA2ID+AAQgDg0gfgeQgggeg0AAQg4AAgjAdg");
	this.shape_8.setTransform(-41.7282,94.4243,0.4949,0.4949);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ai4DnIAAnEIBkAAIAABoIADAAQBHhxBKAAQA7AAA9A1Ig1BNQgWgTgbgNQgagMgSAAQgyAAgkAoQgkApAAA6IAADsg");
	this.shape_9.setTransform(-61.1773,94.1892,0.4949,0.4949);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ABFDgQgTgLgHgYQhAAuhHABQg2AAgkgiQgiggAAguQABg7A3gkQAfgUBVgbIBYgcIAAgYQAAgpgWgUQgWgTguAAQhZAAhHBLIAAhiQA7g+BtAAQBQABAxAjQA1AoAABKIAADoQAAAXATAAQARAAAkgYIAAA2QgjAVgTAHQgUAIgWAAQghAAgSgMgAhCAtQgxAbAAAkQABAcAUASQAVASAeAAQAsAAArgmIAAiDQhOAXggATg");
	this.shape_10.setTransform(-84.536,94.4243,0.4949,0.4949);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AjIDAQhRhQAAhnQAAiABhhUQBhhUCUAAQBcAAB7AuIAABXQg6gfg0gOQgzgOg3AAQhqAAhHA9QhHA+AABbQAABeBGA8QBGA7BwAAQBsAABug/IAABXQgzAYgwAMQg6AOhFAAQihAAhfhgg");
	this.shape_11.setTransform(-112.7818,91.9993,0.4949,0.4949);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CO_v_white, new cjs.Rectangle(-126.7,-7.3,264.2,124.39999999999999), null);


(lib.BUTTON = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAqIAlgqIglgpIAaAAIAmApIgmAqgAg2AqIAmgqIgmgpIAbAAIAlApIglAqg");
	this.shape.setTransform(30.575,6.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUA4QgMgFgIgIQgIgHgFgMQgEgLAAgNQAAgLAEgLQAFgMAHgHQAIgIALgGQALgEAMAAQANAAAKAEQALAFAHAJQAIAHAEANQAEALAAANIAAAGIhUAAQACALAIAIQAIAIAOAAIAIgBIAIgCIAIgDIAHgGIANAUQgJAIgMAEQgNAEgNAAQgMAAgLgEgAgKghQgFACgEAEIgFAIIgCAJIA3AAIgCgJIgFgIQgDgDgFgCQgGgDgHAAQgGAAgFACg");
	this.shape_1.setTransform(15.125,6.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AggA6IAAhwIAeAAIAAAPQAFgHAKgGQAJgFALgBIAAAeIgIgBIgIABIgIADIgHAEQgDACgBADIAABKg");
	this.shape_2.setTransform(5.475,6.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaA6QgHgDgGgEQgFgFgEgHQgEgHAAgKQAAgKAEgHQAEgGAFgEQAGgFAHgCQAHgCAHAAQALAAAJADQAKAEAFAHIAAgPQAAgJgHgGQgHgEgKgBQgTAAgPAOIgLgUQALgJANgFQANgEAMAAQAKAAAJACQAJACAGAGQAIAFAEAHQAEAJAAAMIAABJIgeAAIAAgMQgGAHgJAEQgJAEgLAAQgHAAgHgCgAgQAKQgFAEgBAJQABAIAFAEQAHAEAJABQAGgBAGgCQAHgCAEgFIAAgPQgEgEgHgDQgGgCgGAAQgJAAgHAEg");
	this.shape_3.setTransform(-5.45,6.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgQA4QgLgFgIgIQgIgIgEgLQgFgLAAgNQAAgMAFgLQAEgLAIgIQAIgIALgFQAMgEAMAAQARAAALAGQALAGAGAJIgUASQgIgMgQAAQgMAAgJAJQgJAJAAAOQAAAPAJAJQAJAJAMAAQAIAAAGgDQAGgDAEgGIAUASQgGAIgLAGQgLAHgRAAQgMAAgMgEg");
	this.shape_4.setTransform(-16.625,6.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgKBCQgIgIAAgPIAAg7IgTAAIAAgaIATAAIAAgfIAdAAIAAAfIAXAAIAAAaIgXAAIAAAzQAAAFADAEQACADAFAAIAGgBIAFgCIAGAXQgDADgGACQgHACgJAAQgPAAgIgIg");
	this.shape_5.setTransform(-31.375,4.775);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgUA4QgMgFgIgIQgIgHgFgMQgEgLAAgNQAAgLAEgLQAFgMAHgHQAIgIALgGQALgEAMAAQANAAAKAEQALAFAHAJQAIAHAEANQAEALAAANIAAAGIhUAAQACALAIAIQAIAIAOAAIAIgBIAIgCIAIgDIAHgGIANAUQgJAIgMAEQgNAEgNAAQgMAAgLgEgAgKghQgFACgEAEIgFAIIgCAJIA3AAIgCgJIgFgIQgDgDgFgCQgGgDgHAAQgGAAgFACg");
	this.shape_6.setTransform(-41.225,6.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgXBMQgPgGgLgKQgMgLgHgPQgGgPgBgTQABgSAGgPQAHgPAMgLQALgKAPgGQAPgGAQAAQANAAAKADQAKADAIAFQAIAFAGAGIALAOIgcAPQgFgIgKgHQgJgGgOAAQgJAAgJAEQgKAEgGAHQgGAHgEAJQgEAKAAAKQAAALAEAKQAEAJAGAHQAGAHAKAEQAJAEAJAAQALAAAJgEQAJgEAFgEIAAgTIgpAAIAAgdIBLAAIAAA8QgNAOgQAIQgRAIgWAAQgQAAgPgGg");
	this.shape_7.setTransform(-55.8,4.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// bkgd
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#00A7B5").s().p("Aq0C4IAAluITwAAIB6CtIh6DBg");
	this.shape_8.setTransform(-10.4,5.9758,1,1.0587);

	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(1));

	// shad
	this.instance = new lib.Buttonshad();
	this.instance.setTransform(-80,-14,0.6438,0.6815);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BUTTON, new cjs.Rectangle(-96.8,-14,166.2,59.3), null);


(lib.BKGDblue = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#256BA2").s().p("A3ZKVIAA0pMAuzAAAIAAUpg");
	this.shape.setTransform(0,66.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGDblue, new cjs.Rectangle(-149.7,0,299.5,132.2), null);


(lib.BKGD = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF8300").s().p("A96WbMAAAgs1MA71AAAMAAAAs1g");
	this.shape.setTransform(0.0067,125.0449,0.7833,0.8714);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGD, new cjs.Rectangle(-150,0,300,250.1), null);


(lib.HEAD2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD2type();
	this.instance.setTransform(0,38,1,1,0,0,0,0,36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-139,2,278,83.7), null);


(lib.HEAD1d = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1dtype();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1d, new cjs.Rectangle(-135,-4,278,25.6), null);


(lib.HEAD1c = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1ctype();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1c, new cjs.Rectangle(-135,-4,278,25.6), null);


(lib.HEAD1b = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1btype();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1b, new cjs.Rectangle(-135,-4,278,25.6), null);


(lib.HEAD1a = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1atype();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1a, new cjs.Rectangle(-135,-4,278,25.6), null);


// stage content:
(lib.CO_KidsProcedures_160x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,374];
	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_374 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(374).call(this.frame_374).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,2,0,3).p("EgMaguyIY1AAMAAABdlI41AAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(375));

	// HS logo
	this.instance = new lib.HS_logowhite();
	this.instance.setTransform(80.2,557.75,0.31,0.31,0,0,0,0.7,71.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(375));

	// CO logo
	this.instance_1 = new lib.CO_v_white();
	this.instance_1.setTransform(79.2,500.2,0.35,0.35,0,0,0,0.1,55.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(375));

	// HEAD1a
	this.instance_2 = new lib.HEAD1a();
	this.instance_2.setTransform(13.25,305.75,1,1,0,0,0,-135,-4);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:296.15,alpha:1},8).wait(253).to({alpha:0},9).to({_off:true},1).wait(104));

	// HEAD1b
	this.instance_3 = new lib.HEAD1b();
	this.instance_3.setTransform(13.25,332.1,1,1,0,0,0,-135,-4);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(70).to({_off:false},0).to({y:322.5,alpha:1},8).wait(188).to({alpha:0},9).to({_off:true},1).wait(99));

	// HEAD1c
	this.instance_4 = new lib.HEAD1c();
	this.instance_4.setTransform(13.25,360.05,1,1,0,0,0,-135,-4);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(140).to({_off:false},0).to({y:350.45,alpha:1},8).wait(124).to({alpha:0},9).to({_off:true},1).wait(93));

	// HEAD1d
	this.instance_5 = new lib.HEAD1d();
	this.instance_5.setTransform(13.25,387.35,1,1,0,0,0,-135,-4);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(210).to({_off:false},0).to({y:377.75,alpha:1},8).wait(58).to({alpha:0},9).to({_off:true},1).wait(89));

	// HEAD2
	this.instance_6 = new lib.HEAD2();
	this.instance_6.setTransform(153.05,346.75,1,1,0,0,0,0,27.4);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(295).to({_off:false},0).to({y:337.15,alpha:1},8).wait(72));

	// CTA
	this.instance_7 = new lib.BUTTON();
	this.instance_7.setTransform(-27.3,446.95,0.76,0.76,0,0,0,-10.4,3.9);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(359).to({_off:false},0).to({x:52.7},15,cjs.Ease.quadOut).wait(1));

	// BKGD-orange
	this.instance_8 = new lib.BKGD();
	this.instance_8.setTransform(79.7,575.2,0.5317,0.7337,0,0,0,0,217);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(375));

	// BKGD-blue
	this.instance_9 = new lib.BKGDblue();
	this.instance_9.setTransform(80,352.1,0.5342,1,0,0,0,0,66.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(375));

	// PIC
	this.instance_10 = new lib.sch_img_160x6002x();
	this.instance_10.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(375));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-13,299.5,305.1,301);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 160,
	height: 600,
	fps: 36,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/CO_KidsProcedures_160x600_atlas_P_1.png", id:"CO_KidsProcedures_160x600_atlas_P_1"},
		{src:"images/CO_KidsProcedures_160x600_atlas_NP_1.jpg", id:"CO_KidsProcedures_160x600_atlas_NP_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;