(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"CO_SchoolisBack_728x90_atlas_P_1", frames: [[0,0,232,87]]},
		{name:"CO_SchoolisBack_728x90_atlas_NP_1", frames: [[0,0,728,90]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Buttonshad = function() {
	this.initialize(ss["CO_SchoolisBack_728x90_atlas_P_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.sch_img_728x902x = function() {
	this.initialize(ss["CO_SchoolisBack_728x90_atlas_NP_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.HS_logowhite = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ap9EXIAHnRINagKIgCh7IGDgCIAZKDgAFdgfQgVAOgIAYQgGAUAAAZQAAAaAGATQAJAZAVAOQAVAOAgAAQAyAAAeggQADgDgEgCIgZgYQgCgDgEADQgSARgZAAQgfAAgHgZIgDgKQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIBxAAQAEAAAAgEQAAglgGgUQgIgYgVgOQgVgOgfABQgeAAgVANgAgnAvQgVAQAAAdQAAAdASAPQARAOAaAAQAjAAAQgVIABAAIAAANQAAADAEAAIArAAQADAAAAgDIAAh4QAAgjgSgPQgUgRgtABQgqAAgaASQgDACACADIARAeQACADADgDQAQgKAZAAQAWAAAIAEQAIAHAAANIAAAHQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIghAAQgkAAgUAOgAnMBXIgZAdQgCACACADQAiAdAzAAQAoAAAWgSQAVgRABgeQAAgyg/gGIgUgCQgPgCgGgEQgFgDAAgHQAAgOAYgBQAbAAAXAOQAEADACgDIAVgaQADgDgDgDQgegWguAAQgkgBgVARQgUAQAAAaQAAAzA9AHIAVABQAQACAGAEQAFAEAAAHQAAASgdAAQgfAAgagVIgDgBIgDABgACfgkIAACyQAAADAEAAIAuAAQAEAAAAgDIAAhjQAAgnAdgCQAMAAAPAJQADABACgCIAWgmQACgEgDgCQgNgLgUABQgjgBgOAYIAAAAIAAgPQAAgFgEAAIguAAQgEAAAAAFgAieAiIAABsQAAADAEAAIAuAAQAEAAAAgDIAAh2QAAgegRgTQgRgUgeABQghAAgPAUIgBAAIAAhZQAAgDgEAAIguAAQgEAAAAADIAAD/QAAADAEAAIAuAAQAEAAAAgDIAAhsQAAgPAIgKQAIgJAOAAQAdAAAAAig");
	this.shape.setTransform(25.025,83.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAaAAQABABABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_1.setTransform(27.15,92.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeATQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBQAAgGACgIQAHgTAXgBQAZABAGATQACAGAAAIQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_2.setTransform(65.075,85.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AqIk4IUcAvIAII0I03AOgAhWAjQgVAQAAAeQgBAdAUAPQAQAOAbAAQAkAAAPgVIAAANQAAADAEAAIArAAQAEAAAAgDIAAh5QAAgjgSgPQgUgRgsAAQgrAAgcATQgCACACADIARAfQACACADgBQARgMAZAAQAWAAAIAGQAHAGAAAMIAAAHQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIghAAQgjAAgVAOgAkagrQgVAOgIAZQgHATAAAZQAAAXAHAWQAIAaAWAOQAVAOAgAAQAzAAAdggQADgDgDgCIgagYQgCgDgDADQgSAQgZAAQgfAAgIgYQgCgDgBgIQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIBxAAQAFAAAAgEQAAgmgGgTQgJgZgUgOQgWgOgfAAQgeAAgVAOgADcgxIAAAhQAAAEAFAAIALAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAABUQAAAhAOAPQAOAPAgAAIAUAAQAEAAABgEIAAgnQgBgDgEAAIgJAAQgJAAgDgEQgFgFAAgKIAAhSQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAYAAQAEAAABgEIAAghQgBgDgEAAIgYAAQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAgyQAAgEgDAAIguAAQgFAAAAAEIAAAyQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgLAAQgFAAAAADgABth9IAADKQAAAfANAPQAOAOAfAAIAVAAQADAAAAgEIAAgnQAAgDgDAAIgIAAQgRAAAAgSIAAjGQAAgEgEAAIgvAAQgDAAAAAEgAHggBQAIAIAAAQIAABsQAAADADAAIAvAAQAEAAAAgDIAAh3QAAgegRgTQgQgUgfAAQghAAgQAWIAAAAIAAhaQAAgEgEAAIguAAQgFAAAAAEIAAEAQAAADAFAAIAuAAQAEAAAAgDIAAhsQAAgQAIgIQAIgKAOAAQAOAAAHAKgAmpgBQAHAIAAAQIAABsQAAADAFAAIAuAAQAEAAAAgDIAAh3QAAgegRgTQgRgUgfAAQghAAgPAWIAAhaQAAgEgEAAIgvAAQgDAAAAAEIAAEAQAAADADAAIAvAAQAEAAAAgDIAAhsQAAgQAIgIQAHgKAOAAQAOAAAIAKg");
	this.shape_3.setTransform(-21.95,31.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAbAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_4.setTransform(-24.5,39.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeASQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAgGADgIQAHgUAXAAQAYAAAIAUQACAIAAAGQAAABgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-45.05,31.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AJdAwIAcgBQABAJANAAQAPABAAgNIAAgIQgIAFgMAAQgRAAgLgMQgKgLAAgSQAAgSAKgLQALgMARAAQANAAAIAHIAAgFIAaAAIAABRQAAARgLALQgLAKgTAAQgmAAgFgggAJ4AAQAAASAPAAQAHgBAEgEQAEgEAAgIIAAgCQAAgHgEgFQgFgEgGAAQgPAAAAARgALLAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgALbAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAILAeQgLgLAAgTQAAgSALgLQAMgMASAAQASAAAKAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgKAHQgLAHgOAAQgTAAgMgLgAI0gIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgAFOAZQgRgQAAgaQAAgaARgRQAQgQAbAAQAbAAARAQQARARAAAaQAAAagRAQQgRAQgbAAQgbAAgQgQgAFjgpQgIAJAAAPQAAAPAIAJQAIAIAOAAQAOAAAIgIQAJgJAAgPQAAgPgJgJQgIgIgOgBQgOABgIAIgACHAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgACXAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAAJAeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgPAAQgTAAgLgLgAAygIQgBgMgLAAQgKAAgBAMIAXAAIAAAAgAiVASQAAgWAigCIAJAAIAAgEQAAgIgGAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAh6AQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAlOAfQgNgKAAgTIAegBQAAAGAFAEQAFAFAHAAQANgBAAgIQAAgHgTgFQgTgFgIgGQgLgHAAgQQAAgQAKgJQALgMAUAAQAUAAAMALQAMAJABASIgeABQAAgNgOAAQgMAAAAAKQAAAEAEACQADADAMADQATAEAIAHQALAJAAANQAAASgMAKQgMAIgTAAQgVAAgNgKgAoUANIAAgdIgOAAIAAgXIAOAAIABgZIAbAAIAAAZIARAAIAAAXIgRAAIAAAWQAAALALAAIAGgBIAAAYIgNABQggAAAAgcgAqjASQAAgWAigCIAKAAIAAgEQAAgIgHAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAqIAQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAr0AeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgOAAQgTAAgMgLgArLgIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgANWAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAhOIAaAAIAAAFQAGgHAOAAQAOAAAIAIQAJAJAAAPIAAAwgAHGAnIAAhOIAbAAIAAAGQAHgHAOAAIAAAbQgJAAgGAFQgFAEAAAGIAAAlgADlAnIAAg3IgOAAIAAgXIAOAAIAAgFQAAgQAKgKQAKgJAQAAIAJAAIAAAZIgGgBQgFAAgDADQgDADAAAEIAAAGIARAAIAAAXIgRAAIAAA3gAg7AnIAAhOIAbAAIAAAGQAGgHAPAAIAAAbQgKAAgFAFQgFAEAAAGIAAAlgAjAAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAGgGAMAAQAOAAAIAIQAJAJAAAPIAAAwgAmnAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAHgGALAAQAOAAAIAIQAJAJAAAPIAAAwgApJAnIAAh1IAcAAIAAB1gAstAnIAAgsIgmAAIAAAsIgeAAIAAhwIAeAAIAAAqIAmAAIAAgqIAeAAIAABwg");
	this.shape_6.setTransform(0.175,134.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HS_logowhite, new cjs.Rectangle(-88.7,0,177.5,143), null);


(lib.HEAD2type = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOAPQgHgFAAgKQAAgJAHgFQAFgGAJgBQAKABAGAGQAGAFAAAJQAAAKgGAFQgGAGgKAAQgJAAgFgGg");
	this.shape.setTransform(75.05,46);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAYA5IgYg+IgWA+IgcAAIgghWQgBgEgBgBQgBgBAAAAQgBAAAAAAQgBgBAAAAQgBAAgBAAIgFAAIAAgUIA8AAIAAAUIgFAAQgBAAAAAAQgBABgBAAQAAAAgBAAQAAABgBAAQAAACABAEIAEAKIAFASIAHARIAGgRIAGgSIAEgKQABgEgBgCQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgFAAIAAgUIA4AAIAAAUIgFAAQgBAAAAAAQgBABAAAAQgBAAAAAAQgBABAAAAQgBACABAEIAEAKIAHASIAHARIAGgRIAFgRIAEgLQABgEgBgCQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgGAAIAAgUIAtAAIAAAUIgGAAIgDABIgEAGIgeBWg");
	this.shape_1.setTransform(62.7,42.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgfAzQgOgGgHgOQgIgNAAgSQAAgRAIgNQAHgNAOgIQAOgHASAAQASAAAOAHQANAIAIANQAHANAAARQAAASgHANQgIAOgOAGQgOAIgSAAQgSAAgNgIgAASAeQAGgJAAgTIAAgDQAAgUgGgIQgGgIgMAAQgLAAgFAIQgGAIAAAUIAAADQAAATAGAJQAFAIALAAQAMAAAGgIg");
	this.shape_2.setTransform(46.575,42.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAHA6IAAgUIAGAAQABAAAAAAQABAAAAgBQABAAAAAAQAAAAABgBQABgBAAgEIAAgsQgBgKgDgFQgEgFgIAAQgJAAgFAIQgFAHAAAQIAAAhQAAAEABABQAAABABAAQAAAAAAAAQABABAAAAQABAAAAAAIAHAAIAAAUIg9AAIAAgUIAHAAQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAgBQABgBAAgEIAAg5IgBgGQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAIgHAAIAAgUIAWAAIAQgBIAMgCIAAAUQAFgKAJgGQAJgFANAAQASAAAJALQAJALABAWIAAAsQgBAEABABQABABAAAAQABAAAAAAQABABAAAAQABAAAAAAIAIAAIAAAUg");
	this.shape_3.setTransform(33.15,42.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNBBQgJgJAAgTIAAg5IgOAAIAAgSIAHgBQAHgBAEgDQAEgDACgIIACgTIAZAAIAAAhIAUAAIAAAUIgVAAIAAA5QAAAIADADQAEADAGAAIAGAAIAEgBIAAAVIgKACIgMABQgTAAgJgJg");
	this.shape_4.setTransform(16.425,40.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeBQIAAgTIAIAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBAAAAIABgGIAAg2IgBgIQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgHAAIAAgUIAWAAIAQgBIALgDIAABXIABAGQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIAIAAIAAATgAgPgtQgFgGgBgJQABgIAFgFQAGgHAJAAQAKAAAFAHQAGAFAAAIQAAAJgGAGQgFAFgKABQgJgBgGgFg");
	this.shape_5.setTransform(9.225,39.75);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgcA4QgLgCgIgEIAAgdIAaAAIAAASIAIABIAKABQAHAAAFgDQAFgEAAgGQAAgHgGgDQgHgDgKgCQgKgCgJgDQgJgDgFgHQgGgGAAgNQAAgRANgKQANgKAXAAQAOAAAMACQALAEAHADIAAAcIgaAAIAAgRIgHgBIgIgBQgIAAgFADQgFADAAAGQAAAFAEACQADADAFABIAMADQAJABAJAEQAJAEAGAGQAGAHAAAMQAAASgNALQgNAKgYAAQgPAAgMgDg");
	this.shape_6.setTransform(0.475,42.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgeBQIAAgTIAIAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBAAAAIABgGIAAg2IgBgIQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgHAAIAAgUIAWAAIAQgBIALgDIAABXIABAGQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIAIAAIAAATgAgPgtQgFgGgBgJQABgIAFgFQAGgHAJAAQAKAAAFAHQAGAFAAAIQAAAJgGAGQgFAFgKABQgJgBgGgFg");
	this.shape_7.setTransform(-8.325,39.75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgNA5IgmhWQgCgEgBgBQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgHAAIAAgUIBBAAIAAAUIgIAAQgBAAgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQgBACACAEIAEANIAIARIAHASIAIgUIAIgRIAEgLQABgDgBgCQgBgDgEAAIgIAAIAAgUIA0AAIAAAUIgHAAQgDAAgCACIgEAFIglBWg");
	this.shape_8.setTransform(-18.375,42.275);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgrBHQgLgHgGgNQgGgOgBgSQABgRAGgNQAHgNALgHQALgIAPAAQANAAAIAFQAIAFAFAKIAAgdIgBgGQAAgBAAAAQgBAAAAAAQAAgBgBAAQAAAAgBAAIgJAAIAAgUIAYAAIAQgBIALgBIAAB/QAAAEABABQAAABABAAQAAAAABAAQAAABABAAQAAAAAAAAIAHAAIAAAUIgtAAIgBgIIgBgMQgEALgJAGQgJAGgOAAQgPAAgMgIgAgVgHQgFAHgBASIAAAEQABARAFAIQAGAJALAAQAJAAAHgJQAGgIAAgRIAAgEQAAgSgGgHQgHgJgJABIgBAAQgKAAgGAIg");
	this.shape_9.setTransform(-37.6,40.225);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgdBNIAAgTIAHAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBABAAQABgBAAgFIAAhhIgBgFQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAIgIAAIAAgUIAXAAIAQgBIALgBIAAB+QAAAFABABQAAAAABABQAAAAAAAAQABAAAAAAQAAABABAAIAHAAIAAATg");
	this.shape_10.setTransform(-48.2,40.05);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgeBQIAAgTIAIAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBAAAAIABgGIAAg2IgBgIQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAIgHAAIAAgUIAWAAIAQgBIALgDIAABXIABAGQABAAAAABQAAAAABAAQAAAAAAAAQABABAAAAIAIAAIAAATgAgPgtQgFgGgBgJQABgIAFgFQAGgHAJAAQAKAAAFAHQAGAFAAAIQAAAJgGAGQgFAFgKABQgJgBgGgFg");
	this.shape_11.setTransform(-55.075,39.75);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAHBNIAAgTIAHAAQABAAAAgBQABAAAAAAQAAAAABAAQAAgBAAAAQABgBAAgFIAAgsQAAgJgDgFQgEgEgIAAQgJAAgFAHQgFAHAAAPIAAAhQAAAFABABQAAAAAAABQABAAAAAAQAAAAABAAQAAABABAAIAHAAIAAATIg+AAIAAgTIAIAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBABAAQABgBAAgFIAAhhIgBgFQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgIAAIAAgUIAXAAIAQgBIAMgBIAAA8QAFgLAJgFQAJgFANAAQASAAAJAKQAJALAAAVIAAAtQAAAFABABIADACIAIAAIAAATg");
	this.shape_12.setTransform(-65.575,40.05);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgoArQgQgPgBgcQABgbAQgPQARgQAcAAQAZAAAOAKQANAKAAASQAAAMgGAHQgGAGgLAAQgJAAgGgFQgEgEgBgIQAAgIAFgEQAEgFAGgBQgCgEgFgDQgFgBgHAAQgOAAgGAIQgIAKAAARIAAADQAAATAHAIQAHAJANAAQAKAAAHgEQAHgFAEgLIATALQgEAOgNAJQgMAJgWAAQgdAAgQgQg");
	this.shape_13.setTransform(-78.45,42.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgeAMIAAgXIA9AAIAAAXg");
	this.shape_14.setTransform(-88.1,42.15);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgdBNIAAgTIAIAAQAAAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQACgBAAgFIAAhhIgBgFQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAAAIgJAAIAAgUIAXAAIAPgBIAMgBIAAB+QAAAFABABQAAAAABABQAAAAAAAAQABAAAAAAQAAABABAAIAHAAIAAATg");
	this.shape_15.setTransform(-95.15,40.05);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgeBNIAAgTIAIAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQACgBAAgFIAAhhIgBgFQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAIgIAAIAAgUIAXAAIAQgBIALgBIAAB+QAAAFABABQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIAHAAIAAATg");
	this.shape_16.setTransform(-102.05,40.05);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgdAzQgOgHgHgNQgHgNAAgSQAAgRAHgNQAIgNANgIQAOgHARAAQAcAAAOAQQAOAQAAAcIAAAFIhMAAQAAAOAIAIQAHAIANgBQALAAAGgEQAHgGAEgJIATAMQgEAJgGAGQgHAIgLADQgKAEgPAAQgTAAgOgIgAAVgKQAAgPgFgGQgEgHgKAAQgJAAgFAHQgGAGgBAPIAoAAIAAAAg");
	this.shape_17.setTransform(-111.625,42.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAYA5IgYg+IgWA+IgcAAIgghWQgBgEgCgBQAAgBAAAAQgBAAAAAAQgBgBAAAAQgBAAgBAAIgFAAIAAgUIA8AAIAAAUIgFAAQgBAAAAAAQgBABgBAAQAAAAgBAAQAAABgBAAQgBACACAEIADAKIAGASIAHARIAGgRIAGgSIAEgKQABgEgBgCQAAAAgBgBQAAAAAAAAQgBAAgBgBQAAAAgBAAIgFAAIAAgUIA4AAIAAAUIgFAAQgBAAAAAAQgBABAAAAQgBAAAAAAQgBABAAAAQgCACACAEIAEAKIAHASIAHARIAGgRIAFgRIAEgLQABgEgBgCQAAAAgBgBQAAAAAAAAQgBAAgBgBQAAAAgBAAIgGAAIAAgUIAtAAIAAAUIgFAAIgFABIgDAGIgdBWg");
	this.shape_18.setTransform(-127.4,42.275);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag0AyQgIgHgBgNQAAgQALgIQAJgIARgDQAQgFAUgDIAAgHQAAgJgFgFQgFgEgKgBIgGABIgGABIACAFIABAGQAAAIgFAEQgGAFgJAAQgKAAgFgFQgFgEAAgKQAAgKAHgIQAHgGAMgEQAMgDARABQAbgBAMAJQANAKAAAUIAAAxIABAFQAAABAAAAQAAAAABAAQAAABABAAQAAAAAAAAIAIAAIAAAUIgoAAIgGgIIgDgKQgDAGgFAFQgGAEgIAEQgHACgJAAQgQAAgKgJgAgOAIQgKAFgBAKQAAAHAEADQAEAEAGAAQALgBAGgGQAFgIABgMIAAgIQgQACgKAEg");
	this.shape_19.setTransform(-25.85,19);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgdAzQgOgHgHgOQgHgNAAgRQAAgRAHgOQAIgMANgIQAOgHARAAQAcAAAOAQQAOAPAAAdIAAAFIhMAAQAAAOAIAIQAHAIANAAQALgBAGgFQAHgFAEgIIATALQgEAIgGAIQgHAGgLAEQgKAEgPAAQgTAAgOgIgAAVgKQAAgPgFgHQgEgGgKAAQgJAAgFAGQgGAIgBAOIAoAAIAAAAg");
	this.shape_20.setTransform(-44.075,19);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgdBNIAAgUIAIAAQAAAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQACgBAAgFIAAhhIgBgFQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAAAIgJAAIAAgUIAXAAIAPgBIAMgCIAAB/QAAAFABABQAAAAABABQAAAAAAAAQABAAAAAAQAAAAABAAIAHAAIAAAUg");
	this.shape_21.setTransform(-53.75,16.85);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AguAvQgJgKAAgWIAAgtQAAgEgCgCIgDgBIgIAAIAAgUIAzAAIAABHQAAALAEAEQAEAFAHAAQAKAAAEgIQAFgHAAgOIAAgjIgBgGIgDgBIgKAAIAAgUIA0AAIAABTIABAGQAAABABAAQAAAAAAABQABAAAAAAQABAAAAAAIAJAAIAAAUIgXAAIgQABIgMACIAAgUQgFALgKAEQgIAGgMAAQgTAAgJgLg");
	this.shape_22.setTransform(-64.15,19.175);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgrBHQgLgHgGgNQgHgOABgSQAAgRAGgNQAHgNAKgHQALgIAPAAQAOAAAIAFQAIAFAFAKIAAgdIgBgGQAAgBAAAAQgBAAAAAAQAAgBgBAAQAAAAgBAAIgJAAIAAgUIAXAAIAQgBIAMgBIAAB/QAAAEABABQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIAHAAIAAAUIgtAAIgBgIIgCgMQgEALgJAGQgIAGgQAAQgOAAgMgIgAgUgHQgHAHAAASIAAAEQAAARAHAIQAFAJAMAAQAIAAAHgJQAGgIAAgRIAAgEQAAgSgGgHQgHgJgIABIgCAAQgKAAgFAIg");
	this.shape_23.setTransform(-78.15,17.025);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgdAzQgOgHgHgOQgHgNAAgRQAAgRAHgOQAIgMANgIQAOgHARAAQAcAAAOAQQAOAPAAAdIAAAFIhMAAQAAAOAIAIQAHAIANAAQALgBAGgFQAHgFAEgIIATALQgEAIgGAIQgHAGgLAEQgKAEgPAAQgTAAgOgIgAAVgKQAAgPgFgHQgEgGgKAAQgJAAgFAGQgGAIgBAOIAoAAIAAAAg");
	this.shape_24.setTransform(-91.425,19);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAHBNIAAgUIAHAAQABAAAAAAQABAAAAAAQAAAAABAAQAAgBAAAAQABgBAAgFIAAgsQAAgJgDgFQgEgEgIgBQgJAAgFAIQgFAGAAARIAAAgQAAAFABABQAAAAAAABQABAAAAAAQAAAAABAAQAAAAABAAIAHAAIAAAUIg+AAIAAgUIAIAAQABAAAAAAQABAAAAAAQABAAAAAAQAAgBABAAQABgBAAgFIAAhhIgBgFQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgIAAIAAgUIAXAAIAQgBIAMgCIAAA9QAFgLAJgFQAJgFANAAQASAAAJALQAJAKAAAVIAAAtQAAAFABABIADABIAIAAIAAAUg");
	this.shape_25.setTransform(-104.625,16.85);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgoArQgQgPAAgcQAAgbAQgPQARgQAcAAQAZgBAOALQANAKAAASQABAMgHAHQgGAGgLAAQgJAAgGgFQgEgFgBgHQAAgHAEgFQAFgFAGgCQgCgDgFgDQgFgBgIAAQgNAAgGAIQgIAKAAARIAAAEQAAARAHAKQAHAIANAAQAKAAAHgFQAHgEADgLIAUAMQgEAOgNAIQgMAJgWAAQgdAAgQgQg");
	this.shape_26.setTransform(-117.5,19);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AghBMQgOgDgMgGIAAglIAfAAIAAAXQAGADAGAAIAPABQAJAAAHgEQAGgFABgJQAAgHgEgEQgEgEgIgCIgTgFQgOgEgKgFQgLgGgFgHQgGgJAAgOQAAgYAQgNQARgOAdAAQAQAAAMADQANADALAFIAAAlIgeAAIAAgWIgKgCIgMgBQgLAAgHAFQgHAEAAAJQAAAHAEADQADAEAIADIASAFQANADALAFQALAFAHAHQAHAJAAAPQAAAQgHALQgHAMgOAGQgOAGgUABQgRgBgOgDg");
	this.shape_27.setTransform(-130.275,16.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2type, new cjs.Rectangle(-139,0,278,56.4), null);


(lib.HEAD1btype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANQgFgFAAgIQAAgHAFgEQAFgGAHAAQAIAAAFAGQAFAEAAAHQAAAIgFAFQgFAEgIABQgHgBgFgEg");
	this.shape.setTransform(139.875,43.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgvA6QgHgFAAgLQAAgIAEgFQAFgEAIAAQAGAAAEADQAEADABAFQABAFgDAGQAFgBAEgFQAEgEADgJIAAgBIghhEIgCgFIgDgBIgGAAIAAgQIA0AAIAAAQIgFAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAABAAAAIAAAEIAQAmIAPglQABgDgBgCQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgGAAIAAgQIAqAAIAAAQIgGAAIgEABIgDAFIgcBDQgFANgFAIQgFAJgHAEQgHAEgLAAQgNAAgIgGg");
	this.shape_1.setTransform(132.075,41.925);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgjA7QgKgGgFgLQgFgLAAgPQAAgOAGgKQAFgLAJgGQAJgHAMAAQAMAAAGAFQAHAEAEAIIAAgYIgBgFQAAgBAAAAQgBAAAAAAQAAgBgBAAQAAAAgBAAIgHAAIAAgQIATAAIAOgBIAJgBIAABoQAAAEABABIADABIAGAAIAAARIgmAAIAAgGIgBgLQgEAJgHAFQgHAFgMAAQgNAAgJgGgAgRgGQgFAGAAAPIAAADQAAAOAFAHQAFAHAJAAQAIAAAFgHQAFgHAAgOIAAgDQAAgPgFgGQgFgHgIABIgBAAQgIAAgFAGg");
	this.shape_2.setTransform(120.875,38.475);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgrAqQgHgGAAgLQABgNAHgGQAJgGAOgFQANgDAPgCIAAgGQABgIgEgDQgFgEgIgBIgFABIgEABIABAEIABAFQAAAGgEAEQgFAEgHAAQgIAAgFgEQgEgEAAgIQAAgIAFgGQAHgFAJgDQALgDAOAAQAVAAALAHQAKAIAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAIAGAAIAAAQIgiAAIgFgHIgCgHQgDAEgFAFQgDAEgGACQgHACgIAAQgNAAgIgHgAgLAHQgJAEAAAIQAAAGADACQADADAGAAQAIAAAEgFQAGgHgBgJIAAgIQgMACgIAEg");
	this.shape_3.setTransform(109.75,40.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgYArQgLgGgGgLQgGgLAAgPQAAgOAGgLQAGgLALgGQAMgGAOAAQAXAAAMANQALANAAAXIAAAFIg/AAQAAAMAHAGQAFAHALgBQAJABAFgFQAGgEADgHIAQAJQgDAHgGAGQgFAFgJAEQgJADgMAAQgPAAgMgGgAASgIQAAgNgFgFQgEgFgHAAQgIAAgEAFQgFAGAAAMIAhAAIAAAAg");
	this.shape_4.setTransform(99.2,40.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgsAwIAAgRIAHAAIACgBQABgBAAgEIAAguIAAgFQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAgRIATAAIAOgBIAJgBIAAAUQACgLAHgFQAGgFAIAAQAMAAAFAHQAHAHAAAMQAAAKgGAGQgFAFgJAAQgGAAgEgDQgEgEgBgGQABgEACgDQACgEAEgCIgCgBIgEAAQgHAAgFAHQgDAHAAANIAAAZQAAAEABABIABABIAIAAIAAARg");
	this.shape_5.setTransform(89.5,39.975);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgYArQgLgGgGgLQgGgLAAgPQAAgOAGgLQAHgLALgGQALgGAOAAQAWAAANANQALANAAAXIAAAFIg/AAQAAAMAGAGQAHAHAKgBQAJABAGgFQAFgEADgHIAQAJQgDAHgFAGQgGAFgJAEQgIADgMAAQgQAAgMgGgAARgIQAAgNgEgFQgEgFgHAAQgIAAgEAFQgFAGAAAMIAgAAIAAAAg");
	this.shape_6.setTransform(75.15,40.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgrAwIAAgRIAGAAIADgBQABgBAAgEIAAguIgBgFQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAgRIATAAIANgBIAKgBIAAAUQACgLAGgFQAGgFAJAAQAMAAAFAHQAGAHABAMQgBAKgFAGQgFAFgJAAQgGAAgEgDQgEgEAAgGQgBgEADgDQACgEAEgCIgCgBIgEAAQgHAAgFAHQgDAHAAANIAAAZQAAAEABABIACABIAHAAIAAARg");
	this.shape_7.setTransform(65.45,39.975);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgqAqQgIgGAAgLQAAgNAJgGQAIgGANgFQAOgDAQgCIAAgGQAAgIgFgDQgEgEgHgBIgGABIgEABIACAEIAAAFQAAAGgFAEQgEAEgHAAQgIAAgEgEQgFgEAAgIQAAgIAGgGQAFgFALgDQAKgDANAAQAXAAAKAHQAKAIAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAIAGAAIAAAQIgiAAIgEgHIgDgHQgDAEgEAFQgEAEgGACQgHACgIAAQgNAAgHgHgAgMAHQgIAEAAAIQAAAGADACQADADAGAAQAIAAAEgFQAFgHABgJIAAgIQgNACgJAEg");
	this.shape_8.setTransform(55.45,40.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgWAuQgKgBgHgDIAAgZIAWAAIAAAPIAGABIAJABQAGAAAEgCQAEgEAAgEQAAgHgFgCIgOgEQgIgBgHgDQgIgDgFgEQgEgHgBgKQABgOAKgIQALgJATAAQAMABAJACIAPAEIAAAYIgVAAIAAgNIgGgCIgHgBQgGAAgEADQgEADAAAEQAAAFADABQACACAFABIAJADIAQAEQAHADAFAFQAFAGAAAKQAAAPgLAJQgLAIgUAAQgMAAgJgDg");
	this.shape_9.setTransform(41.125,40.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgjA7QgKgGgFgLQgFgLAAgPQAAgOAGgKQAFgLAJgGQAJgHAMAAQAMAAAGAFQAHAEAEAIIAAgYIgBgFQAAgBAAAAQgBAAAAAAQAAgBgBAAQAAAAgBAAIgHAAIAAgQIATAAIAOgBIAJgBIAABoQAAAEABABIADABIAGAAIAAARIgmAAIAAgGIgBgLQgEAJgHAFQgHAFgMAAQgNAAgJgGgAgRgGQgFAGAAAPIAAADQAAAOAFAHQAFAHAJAAQAIAAAFgHQAFgHAAgOIAAgDQAAgPgFgGQgFgHgIABIgBAAQgIAAgFAGg");
	this.shape_10.setTransform(30.925,38.475);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgZBCIAAgQIAHAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAgtIgBgGQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgGAAIAAgRIATAAIAMgBIAKgBIAABHQAAABAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAHAAIAAAQgAgMglQgFgFAAgHQAAgHAFgEQAFgFAHgBQAIABAFAFQAEAEABAHQgBAHgEAFQgFAEgIABQgHgBgFgEg");
	this.shape_11.setTransform(22.175,38.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAFBAIAAgQIAGAAIABgCIAAgDIgMgUIgNANIAAAFIABAGIADABIAFAAIAAAQIgzAAIAAgQIAHAAIADgBQABgBAAgFIAAhPQAAgEgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAAAgBAAIgHAAIAAgRIAUAAIANgBIAJgBIAABQIAZgXQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAgBAAIgIAAIAAgRIAyAAIAAARIgGAAIgFABIgDADIgQAMIAYAmIACAEIADABIAFAAIAAAQg");
	this.shape_12.setTransform(13.6,38.35);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgsAwIAAgRIAHAAIACgBQABgBAAgEIAAguIAAgFQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAgRIATAAIAOgBIAJgBIAAAUQACgLAHgFQAFgFAKAAQAKAAAGAHQAHAHAAAMQAAAKgFAGQgGAFgJAAQgGAAgEgDQgEgEgBgGQAAgEADgDQACgEAEgCIgDgBIgCAAQgJAAgEAHQgDAHAAANIAAAZQAAAEABABIABABIAIAAIAAARg");
	this.shape_13.setTransform(-1.2,39.975);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgmAnQgHgJAAgSIAAglQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBAAAAIgDgBIgHAAIAAgRIAqAAIAAA7QAAAIAEAEQADAEAGAAQAHAAAEgGQAEgGAAgMIAAgdQAAAAAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAIgCgBIgIAAIAAgRIArAAIAABFIAAAFQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAAAIAIAAIAAARIgUAAIgNAAIgKACIAAgQQgEAIgIAEQgGAEgLAAIgBABQgOAAgIgJg");
	this.shape_14.setTransform(-11.725,40.2513);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgaArQgLgGgGgLQgHgLAAgPQAAgOAHgLQAGgLAMgGQALgGAOAAQAQAAALAGQALAGAGALQAGALABAOQgBAPgGALQgGALgMAGQgLAGgPAAQgPAAgLgGgAgOgYQgEAIAAAQIAAABQAAAQAEAIQAFAGAJABQAKgBAFgGQAEgIAAgQIAAgBQAAgQgEgIQgFgGgKAAIAAAAQgJAAgFAGg");
	this.shape_15.setTransform(-22.825,40.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgvA6QgHgFAAgLQAAgIAEgFQAFgEAIAAQAGAAAEADQAEADABAFQABAFgDAGQAFgBAEgFQAEgEADgJIAAgBIghhEIgCgFIgDgBIgGAAIAAgQIA0AAIAAAQIgFAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAIAQAmIAPglQABgDgBgCQAAgBgBAAQAAAAAAAAQgBgBgBAAQAAAAgBAAIgGAAIAAgQIAqAAIAAAQIgGAAIgEABIgDAFIgcBDQgFANgFAIQgFAJgHAEQgHAEgLAAQgNAAgIgGg");
	this.shape_16.setTransform(-33.725,41.925);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgYArQgLgGgGgLQgGgLAAgPQAAgOAGgLQAHgLALgGQAKgGAPAAQAXAAALANQAMANAAAXIAAAFIg/AAQABAMAFAGQAHAHAKgBQAJABAGgFQAFgEADgHIAQAJQgDAHgFAGQgGAFgJAEQgIADgMAAQgQAAgMgGgAARgIQAAgNgDgFQgEgFgIAAQgIAAgEAFQgFAGAAAMIAgAAIAAAAg");
	this.shape_17.setTransform(-48.7,40.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgrAwIAAgRIAGAAIADgBQABgBAAgEIAAguIgBgFQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgHAAIAAgRIATAAIANgBIAKgBIAAAUQACgLAGgFQAGgFAJAAQALAAAHAHQAFAHABAMQgBAKgFAGQgFAFgJAAQgGAAgEgDQgEgEAAgGQgBgEADgDQACgEAEgCIgDgBIgDAAQgHAAgFAHQgDAHAAANIAAAZQAAAEABABIACABIAHAAIAAARg");
	this.shape_18.setTransform(-58.4,39.975);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgmAnQgHgJAAgSIAAglQAAAAAAgBQAAgBAAAAQgBgBAAAAQAAgBAAAAIgDgBIgHAAIAAgRIAqAAIAAA7QAAAIAEAEQADAEAGAAQAHAAAEgGQAEgGAAgMIAAgdQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBgBAAIgCgBIgIAAIAAgRIArAAIAABFIAAAFQABAAAAABQAAAAABAAQAAAAAAAAQABAAAAAAIAIAAIAAARIgUAAIgNAAIgKACIAAgQQgEAIgIAEQgGAEgLAAIgBABQgOAAgIgJg");
	this.shape_19.setTransform(-68.925,40.2513);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgWAuQgKgBgHgDIAAgZIAWAAIAAAPIAGABIAJABQAGAAAEgCQAEgEAAgEQAAgHgFgCIgOgEQgIgBgHgDQgIgDgFgEQgEgHgBgKQABgOAKgIQALgJATAAQAMABAJACIAPAEIAAAYIgVAAIAAgNIgGgCIgHgBQgGAAgEADQgEADAAAEQAAAFADABQACACAFABIAJADIAQAEQAHADAFAFQAFAGAAAKQAAAPgLAJQgLAIgUAAQgMAAgJgDg");
	this.shape_20.setTransform(-79.025,40.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgYArQgMgGgFgLQgGgLAAgPQAAgOAGgLQAHgLAKgGQALgGAOAAQAXAAAMANQAMANAAAXIAAAFIg/AAQABAMAFAGQAHAHAKgBQAJABAGgFQAFgEADgHIAQAJQgDAHgGAGQgFAFgJAEQgJADgLAAQgRAAgLgGgAARgIQAAgNgDgFQgFgFgIAAQgGAAgFAFQgEAGgBAMIAgAAIAAAAg");
	this.shape_21.setTransform(-93,40.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAFBAIAAgQIAFAAIACgCIgBgDIgLgUIgMANIAAAFIAAAGIADABIAGAAIAAAQIg0AAIAAgQIAIAAIACgBQABgBAAgFIAAhPQAAgEgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAAAAAAAIgIAAIAAgRIATAAIAOgBIAKgBIAABQIAYgXQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAgBAAIgJAAIAAgRIAzAAIAAARIgHAAIgEABIgEADIgPAMIAXAmIAEAEIADABIAEAAIAAAQg");
	this.shape_22.setTransform(-103.8,38.35);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgqAqQgIgGAAgLQAAgNAJgGQAIgGANgFQAOgDAQgCIAAgGQAAgIgFgDQgEgEgHgBIgGABIgEABIACAEIAAAFQAAAGgFAEQgEAEgHAAQgIAAgEgEQgFgEAAgIQAAgIAGgGQAFgFALgDQAKgDANAAQAXAAAKAHQAKAIAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAAAAAIAHAAIAAAQIgiAAIgEgHIgDgHQgDAEgEAFQgEAEgGACQgHACgIAAQgNAAgHgHgAgMAHQgIAEAAAIQAAAGADACQADADAFAAQAJAAAEgFQAFgHABgJIAAgIQgNACgJAEg");
	this.shape_23.setTransform(-114.75,40.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAYA/IAAgQIAIAAQABAAABgBQAAAAABAAQAAAAAAAAQABgBAAAAIABgFIAAhQIgiBnIgTAAIgghmIAABPQAAAEABABQABAAAAABQAAAAABAAQAAAAABAAQAAABABAAIAJAAIAAAQIguAAIAAgQIAJAAQAAAAABgBQAAAAABAAQAAAAAAAAQABgBAAAAQABgBAAgEIAAhQIgBgEIgDgBIgJAAIAAgRIA7AAIAVBHIAYhHIA6AAIAAARIgJAAIgDABIgBAEIAABQQAAAEABABQAAAAABABQAAAAAAAAQABAAAAAAQAAABABAAIAJAAIAAAQg");
	this.shape_24.setTransform(-128.6,38.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1btype, new cjs.Rectangle(-139,0,334.1,52.2), null);


(lib.HEAD1atype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOAQQgHgHAAgJQAAgIAHgHQAFgFAJgBQAKABAGAFQAGAHAAAIQAAAJgGAHQgGAFgKAAQgJAAgFgFg");
	this.shape.setTransform(126.45,22.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAGBNIAAgUIAHAAQAAAAAAAAQABAAAAAAQAAgBABAAQAAAAAAAAIgBgEIgOgYIgQAPIAAAHQAAAFACABQAAAAAAABQAAAAABAAQAAAAABAAQAAAAABAAIAHAAIAAAUIg+AAIAAgUIAIAAQAAAAABAAQAAAAABAAQAAAAABAAQAAgBAAAAQABgBAAgFIAAhhIgBgFQAAgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgIAAIAAgUIAXAAIAQgBIALgCIAABhIAfgbQAAgBAAAAQAAgBAAgBQABAAAAgBQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAAAgBAAQAAgBgBAAIgKAAIAAgTIA9AAIAAATIgIAAIgFABIgFAEIgTAPIAdAvIAEADIADABIAGAAIAAAUg");
	this.shape_1.setTransform(116.8,16.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgoArQgQgPAAgcQAAgbAQgPQAQgQAdAAQAZgBAOALQANAKAAASQABAMgHAHQgGAGgLAAQgJAAgGgFQgEgFgBgHQAAgHAEgFQAEgFAHgCQgCgDgFgDQgFgBgIAAQgNAAgGAIQgIAKAAARIAAAEQAAARAHAKQAHAIAMAAQALAAAHgFQAHgEADgLIAUAMQgEAOgNAIQgMAJgWAAQgdAAgQgQg");
	this.shape_2.setTransform(104,19);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgzAyQgKgHABgNQgBgQALgIQAKgIAQgDQARgFASgDIAAgHQABgJgFgFQgFgEgKgBIgHABIgFABIADAFIAAAGQAAAIgGAEQgFAFgIAAQgLAAgEgFQgGgEAAgKQAAgKAHgIQAGgGANgEQANgDAQABQAbgBANAJQAMAKgBAUIAAAxIABAFQABABAAAAQAAAAABAAQAAABABAAQAAAAABAAIAIAAIAAAUIgqAAIgFgIIgDgKQgDAGgGAFQgEAEgIAEQgIACgJAAQgQAAgJgJgAgOAIQgKAFAAAKQAAAHADADQAEAEAGAAQALgBAFgGQAHgIgBgMIAAgIQgPACgKAEg");
	this.shape_3.setTransform(91.55,19);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgHBHQgLgHgEgNIgGAZIgbAAIABgGIAAgMIAAgUIAAhWIgBgGQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgJAAIAAgUIAXAAIAQgBIAMgBIAAA+QAFgLAJgGQAIgGAOAAQAPAAALAIQALAHAFANQAGANAAARQAAASgGAOQgGANgLAHQgLAIgQAAQgQAAgJgIgAgKgHQgGAHAAASIAAAEQAAARAGAIQAGAJAKAAQAKAAAHgJQAGgIAAgRIAAgEQAAgSgGgHQgHgJgKABIgBAAQgJAAgGAIg");
	this.shape_4.setTransform(77.725,17.025);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgcA4QgLgDgIgDIAAgdIAaAAIAAASIAIABIAKAAQAHAAAFgCQAFgDAAgHQAAgHgGgDQgHgDgKgCQgKgCgJgDQgJgDgFgHQgGgGAAgNQAAgRANgKQANgKAXAAQAOAAAMACQALAEAHACIAAAdIgaAAIAAgRIgHgBIgIgBQgIAAgFADQgFAEAAAFQAAAFAEACQADADAFACIAMACQAJACAJAEQAJADAGAGQAGAHAAAMQAAATgNAKQgNAKgYAAQgPAAgMgDg");
	this.shape_5.setTransform(60.125,19);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgeBQIAAgUIAIAAQAAAAABAAQAAAAABAAQAAAAABAAQAAgBAAAAIABgGIAAg3IgBgHQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAIgHAAIAAgTIAWAAIAQgBIALgCIAABWIABAGQABAAAAABQAAAAABAAQAAAAAAAAQABAAAAAAIAIAAIAAAUgAgPgtQgFgGgBgIQABgJAFgGQAGgFAJgBQAKABAFAFQAGAGAAAJQAAAIgGAGQgFAFgKABQgJgBgGgFg");
	this.shape_6.setTransform(51.325,16.55);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgeBNIAAgUIAIAAQABAAAAAAQABAAAAAAQABAAAAAAQAAgBABAAQABgBAAgFIAAhhIgBgFQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAIgIAAIAAgUIAXAAIAQgBIALgCIAAB/QAAAFABABQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAAAIAHAAIAAAUg");
	this.shape_7.setTransform(38.9,16.85);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgfAzQgOgGgHgOQgIgNAAgSQAAgRAIgOQAHgMAOgIQAOgHASAAQASAAAOAHQANAIAIAMQAHAOAAARQAAASgHANQgIAOgOAGQgOAIgSAAQgSAAgNgIgAASAeQAGgJAAgTIAAgDQAAgUgGgIQgGgIgMAAQgLAAgFAIQgGAIAAAUIAAADQAAATAGAJQAFAIALAAQAMAAAGgIg");
	this.shape_8.setTransform(28.975,19);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgfAzQgOgGgHgOQgIgNAAgSQAAgRAIgOQAHgMAOgIQAOgHASAAQASAAAOAHQANAIAIAMQAHAOAAARQAAASgHANQgIAOgOAGQgOAIgSAAQgSAAgNgIgAASAeQAGgJAAgTIAAgDQAAgUgGgIQgGgIgMAAQgLAAgFAIQgGAIAAAUIAAADQAAATAGAJQAFAIALAAQAMAAAGgIg");
	this.shape_9.setTransform(15.975,19);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAHBNIAAgUIAHAAQABAAAAAAQABAAAAAAQAAAAABAAQAAgBAAAAQABgBAAgFIAAgsQAAgJgDgFQgEgEgIgBQgJAAgFAIQgFAGAAARIAAAgQAAAFABABQAAAAAAABQABAAAAAAQAAAAABAAQAAAAABAAIAHAAIAAAUIg+AAIAAgUIAIAAQABAAAAAAQABAAAAAAQABAAAAAAQAAgBABAAQABgBAAgFIAAhhIgBgFQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgIAAIAAgUIAXAAIAQgBIAMgCIAAA9QAFgLAJgFQAJgFANAAQASAAAJALQAJAKAAAVIAAAtQAAAFABABIADABIAIAAIAAAUg");
	this.shape_10.setTransform(2.475,16.85);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgoArQgQgPAAgcQAAgbAQgPQARgQAcAAQAZgBAOALQANAKAAASQABAMgHAHQgGAGgLAAQgJAAgGgFQgEgFgBgHQAAgHAEgFQAFgFAGgCQgCgDgFgDQgFgBgIAAQgNAAgGAIQgIAKAAARIAAAEQAAARAHAKQAHAIANAAQAKAAAHgFQAHgEADgLIAUAMQgEAOgNAIQgMAJgWAAQgdAAgQgQg");
	this.shape_11.setTransform(-10.4,19);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcA4QgLgDgIgDIAAgdIAaAAIAAASIAIABIAKAAQAHAAAFgCQAFgDAAgHQAAgHgGgDQgHgDgKgCQgKgCgJgDQgJgDgFgHQgGgGAAgNQAAgRANgKQANgKAXAAQAOAAAMACQALAEAHACIAAAdIgaAAIAAgRIgHgBIgIgBQgIAAgFADQgFAEAAAFQAAAFAEACQADADAFACIAMACQAJACAJAEQAJADAGAGQAGAHAAAMQAAATgNAKQgNAKgYAAQgPAAgMgDg");
	this.shape_12.setTransform(-21.775,19);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAGA6IAAgUIAHAAQABAAAAAAQABAAAAgBQABAAAAAAQAAAAAAgBQACgBAAgEIAAgsQAAgKgEgFQgEgFgIAAQgJAAgFAIQgFAHAAAQIAAAhQAAAEABABQAAABABAAQAAAAAAAAQABABAAAAQABAAAAAAIAHAAIAAAUIg9AAIAAgUIAIAAQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAgBQABgBAAgEIAAg5IgBgGQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgIAAIAAgUIAWAAIAQgBIAMgCIAAAUQAFgKAJgGQAIgFAOAAQASAAAJALQAKALAAAWIAAAsQAAAEABABQAAABAAAAQABAAAAAAQABABAAAAQABAAAAAAIAIAAIAAAUg");
	this.shape_13.setTransform(-39.5,18.825);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgfAzQgOgGgHgOQgIgNAAgSQAAgRAIgOQAHgMAOgIQAOgHASAAQASAAAOAHQANAIAIAMQAHAOAAARQAAASgHANQgIAOgOAGQgOAIgSAAQgSAAgNgIgAASAeQAGgJAAgTIAAgDQAAgUgGgIQgGgIgMAAQgLAAgFAIQgGAIAAAUIAAADQAAATAGAJQAFAIALAAQAMAAAGgIg");
	this.shape_14.setTransform(-53.175,19);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgcA4QgLgDgIgDIAAgdIAaAAIAAASIAIABIAKAAQAHAAAFgCQAFgDAAgHQAAgHgGgDQgHgDgKgCQgKgCgJgDQgJgDgFgHQgGgGAAgNQAAgRANgKQANgKAXAAQAOAAAMACQALAEAHACIAAAdIgaAAIAAgRIgHgBIgIgBQgIAAgFADQgFAEAAAFQAAAFAEACQADADAFACIAMACQAJACAJAEQAJADAGAGQAGAHAAAMQAAATgNAKQgNAKgYAAQgPAAgMgDg");
	this.shape_15.setTransform(-64.925,19);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag1A6IAAgUIAIAAQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAgBQABgBAAgEIAAg5IgBgGQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgIAAIAAgUIAXAAIAQgBIALgCIAAAYQADgNAIgGQAIgGAKAAQAOAAAHAJQAHAIAAAOQAAANgGAHQgGAGgLAAQgIAAgFgEQgFgFAAgHQAAgFADgEQADgEAEgCIgDgCIgDAAQgKAAgFAJQgEAIAAAQIAAAfQAAAEABABQAAABAAAAQABAAAAAAQAAABAAAAQAAAAABAAIAJAAIAAAUg");
	this.shape_16.setTransform(-75.825,18.825);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgdAzQgOgHgHgOQgHgNAAgRQAAgRAHgOQAIgMANgIQAOgHARAAQAcAAAOAQQAOAPAAAdIAAAFIhMAAQAAAOAIAIQAHAIANAAQALgBAGgFQAHgFAEgIIATALQgEAIgGAIQgHAGgLAEQgKAEgPAAQgTAAgOgIgAAVgKQAAgPgFgHQgEgGgKAAQgJAAgFAGQgGAIgBAOIAoAAIAAAAg");
	this.shape_17.setTransform(-87.725,19);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhDBNIAAgUIAIAAQABAAAAAAQABAAAAAAQABAAAAAAQAAgBABAAQABgBAAgFIAAhgQAAgEgBgBQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgIAAIAAgUIAXAAIAQgBIALgCIAAAYQAFgMAJgGQAJgGAOAAQAPAAALAHQAKAIAGAMQAGAOAAASQAAARgGANQgGAOgLAGQgMAIgPAAQgNAAgIgFQgJgGgEgKIAAAeQAAAFABABQAAAAAAABQABAAAAAAQAAAAABAAQAAAAABAAIAIAAIAAAUgAgKgsQgGAIAAARIAAAEQAAAQAGAJQAGAHAJABQALgBAGgHQAGgJAAgQIAAgEQAAgRgGgIQgGgIgLAAQgJAAgGAIg");
	this.shape_18.setTransform(-101.075,20.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgeAMIAAgXIA9AAIAAAXg");
	this.shape_19.setTransform(-111.6,18.95);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAHA6IAAgUIAGAAQABAAAAAAQABAAAAgBQABAAAAAAQAAAAABgBQABgBAAgEIAAgsQgBgKgDgFQgEgFgIAAQgJAAgFAIQgFAHAAAQIAAAhQAAAEABABQAAABABAAQAAAAAAAAQABABAAAAQABAAAAAAIAHAAIAAAUIg9AAIAAgUIAHAAQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAgBQABgBAAgEIAAg5IgBgGQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAIgHAAIAAgUIAWAAIAQgBIAMgCIAAAUQAFgKAJgGQAJgFANAAQASAAAJALQAJALAAAWIAAAsQAAAEABABQABABAAAAQABAAAAAAQABABAAAAQABAAAAAAIAIAAIAAAUg");
	this.shape_20.setTransform(-122.1,18.825);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgiBMIAAgUIAKAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAQABgCAAgFIAAhgQAAgEgBgCQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgKAAIAAgUIBFAAIAAAUIgKAAQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAIgBAGIAABgQAAAFABACQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAIAKAAIAAAUg");
	this.shape_21.setTransform(-133.125,16.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1atype, new cjs.Rectangle(-139,0,278,33.2), null);


(lib.CO_v_white = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgyA1QgXgVAAggQAAgeAWgVQAVgWAeAAQAfAAAWAXQAVAVgBAdQAAAfgVAVQgVAVgfABQgdgBgVgUgAgvgvQgTAUAAAbQAAAcATAUQAUATAbAAQAcAAATgTQATgTABgdQAAgbgTgTQgUgUgcAAQgbAAgUATgAASAuQgCgDgCgKIgCgPQgCgIgFgEQgEgCgJAAIgGAAIAAAqIgRAAIAAhcIAfAAQAPAAAFACQAPAFAAARQAAAQgTAGQAGABADAEQADAEABAJQAEAVADAHgAgOgIIAOAAQATAAAAgNQAAgIgHgDQgDgBgMAAIgLAAg");
	this.shape.setTransform(133.8251,86.6356,0.4949,0.4949);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACmLBQgKgEgNACQgPADgIAAQAAgDgKgCIgOgBQgRABgHgCQAAgDgSACQgjgBAAgBIgUgCIgTgBQgLgCgHAAQAAgBgQABQgRABAAgDIgOgEQgJgDAAAHQgDAAgFgDQgEgDgDAAQAAAFgJgBIgNgDQgNgCgLACQgRACgYgKIgJgEQgEgCgEABQgCAAgIgEQgIgFAAgBIgMABIgMABQgIACgFgBQgDAAgDgEQgEgFgDAAIAAAEQgEAAgEgCQgGgDAAgEQgCAGgBAAQAAgDgIgDQgIgCgFAAIgBABQgBAAAAAAQAAgBAAABQgBAAAAAAQAAAAAAAAQgDABgFgEQgEgDgEABQgEABAAgDIgIgGQgHgFAAAEQgCABgMgFQgNgGAAgCIgTgJQgBABAAAAQgBABAAAAQAAABAAAAQAAAAABAAIgEABIAAAAIgEAAIAEAAQABADgQgGQgCgDgFAAQAAgGgDgCIAAAGIgFgDQgGgDAAADIgIgIIgOgCQAAgCgNgGQgNgGAAgCQgKgEgDgKQgBgDgJgBIgOgCQgTgKgBABQgEgCgCABIABgDQgCAAgQgKQgLgIgDgIIgLgDQgCgCgBgDQgBgBgFAAIgDgHIgCgHQgEgBgCACQgCACgCAAQgBgLgTAAQgPAAAAgBIgNgBIgMgBQgSAFgHgCQAAgBgYgBQgaAAgDgBQAAACgJgCIgNgDQgLAFgDgEQgNgEgCABQAAABgGAAIgHgBIgJgCQgDgCgFAAIgOABQAAABgOgEQgGAAgFgHQgCgBgNABIgMAAQgEABgcgDQgcgDAAgBIgJgDQgGgCgDAAIgXgDQgDgEgbgGQgagHAAgBQgCAAgEgCQgDgDgDABQgOACAAgEQgJgEgPAAQAAgFgKgBQgNgBgBgBQgLgFgFgDQgHgGgQgDIgYgEQgDgDgDABIgHACIgGgDIgHgCQAAgEgJgBQgJgBgCgFIAJgCQgBgEgMgEQgMgFAAACIgSgJQgFAAgIgGIgLgHIgMgEIgNgBIAVAVQAAADAHAGQAHAGABAEQADACAGAHQAGAGAEABQAKADAEAHQADAAAHADIAKAFIAHAEQAHAEAAACQAFAAAHADQAGADAEAAIAEACQABAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAFABAGAGQACAFAWAEQAVAEAAADIAYAKQADAAAGADQAFAEAEAAQACgBATAGIATAFQADAAAIAEQAGAEAEgBQAEgBAJAEQAKAEADAAQAAgBARAEIAVAFQAEAAAJACIANAEQAAABAOACIAQABQAAAFBNAGQADADAjADQAiAEAAABQBPAIAAgBQADgBAkAEQAiAEAAgBQAIgBAAABQgGAAgMAGQgOAGgFABIgMgCQgLgCAAADIgGABQgDABgDgBQAAAGgUABQgTABAAgDQgQACAAgCIgGACQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgLgBQgDgBgDgGQgDAAgCADQgBABgGAAIgNgBQgXgCgDgCIgFgFIgJABIgMgEQgKgDAAADQgGAAgKgCQgCgGgEABIgJAFQgFADgFgCQAAgCgLgCQgKgCgEABQAAACgWgEIgbgFQAAgCgOgBQgPgBgBgEQgHAAgLgDQgMgDgGgBQgCgCgNgBQgNgBAAgCQgGAAgJgCIgOgEIgNgEQgNgEAAgBIgNgCQgKgCAAgBQgFAAgGgCIgLgFIgDgBIgCgBQgLAAAQALQACACAGACQAGACADADIAKADQAAABAFABIAHABQAAACASADQAAADAaAEQAZAFABAHIgKACQAAgDgXgDQgZgDgCgDIgagHQgVgHAAgDIgZgIQgUgIAAgBQgIgCgKgEQgNgGgFgGIgIgFQgJgEAAABQgCAAgHgFQgIgFAAgCQgKAAgPgHQgRgJgCgJQgPgKgGAAIgIgIQgFgFgDgCIgGgIIgJgFQgGgCAAgDQgGgEgHgIQgHgJgDgGQgDgBgEgHQgFgHAAgCQgDAAgDgJQgDgKgEAAQAAgEgDgGQgEgFAAgFQgBAAgFgTIgGgYIgHgkQgHgjAFAAIgFgVQgBAAgBgLIgBgNQgDAAAAgNQgBgOgCAAIgJhUIAAggQAAgcACAAIgCgjQgBggAEAAIgCgxQgCgsAFgDQAAgEAKgaQALgZgBgEQAIAAAHgOQAHgPAGgCQACgBADgFQACgGADgCQAAgFAGgGQAHgGAHgBIgDgEQAAAAAAgBQAAAAAAgBQAAAAABgBQABAAABAAIAEgCQAAAAAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAHgHIAKgHIAFAAIAEgCQALgIgHAAQgCgGAFgEQAFgFAFAAIAIgDIAIgCQAKgFAKgJIAQgRQAGgGADgBIAFgDIACgEQACAAAOgLQAAgCANgFQANgGAAgEQAEAAAJgGQAJgHABgDIAOgJQAHgEAIAAQAAgBAGgDIAFgCIAJABQAGACABgDIAXgEQAOgEAAgJQADgBACgEIADgEQABgCAEgDQAEgCABgDIgBAAQAAgFAHACIAJACIARgCIAIgFIAKgEIAJgFQAHgEACAAIAEgCQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBQAFAAAFgCQAHgCAAgDQgHAAAHgHQAHgGAEgBIANgHQAFAAAGgDQAAgDAHgCQAGgCAAgEQAGAAAAADQADAAAEgCIAHgCIAKACQAGABACgDIAOgGQAJgGAEAAQAAgBALgEQAKgDAEAAQAAgCAHAAQAHAAAAgBQAJAAACgCQACgBAAgHIAFgDIAEgEIAJACIgBAFIAEgCIADgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAfAAAHgDQAEgBAGACIAKACQALgGgFAAQgCgJASgGQATgGAAAFQAMgIAZAAQACgDAJAAQAJABACgEIAXgEQAUgEAAgBIABABIAVgFQAWgFADAAQAVAAAAgEIAIgCQAHgBAAgBIAggHIAvgHQAOAAAggFQAggGAQAAQAAgFBQAAQAAABAGACQAHACAAACQgIAFgXgCIgQABIgRABQgJAAgRADQgSADgJAAQAAgChXATQAAAFArgFIAxgGIAugGIAbgDQARgCAJACQAUgDABAKQASAAAAABIAHABQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAABIgIAAQAAADg1ACQAAABgRADIgUACIgTAAQgSAAAAADIgwAHIgSACIgUACQAAADgMACIgQACQgIgBgPAEQgQAFgHAAIgMACQgMACAAACQgEAAgGAEQgHAEgDAAIgJAAIgJgBQAAADgQACQgPADgBADQgCAKgMADQgOABgIACQAAADgTAHQgHAKgHAEQACAIAiABQAfABAHgEQADgCAagEQAXgDAAgCIAMgCIAMgDQAAgBAGABIAHABQARgEAJAAQAAgBAcgDIAcgFQAfgDAAgBIAVgCIAWgCQAAgCAmgCQAngDAFABIApgDQAkgDAAACQAMgCAYACIAcgBQASgBALACQAAADAJACQAJACAAgCIAQABQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQADgBAKACQALADAAACQgEACgWABIgVAAIgmABQgCADgWAFQgVAFAAACIgQgBQgPgBAAACIgWAAQAAAFgZABIgegBQAAADglABQglACgBAIQARADAXgDIAngGQAAACAkgCQAjgBAAABQAFAAALgDQAEAAAEACQAFADAEAAIAQgBQAJABgEAGQgFAIghACIghACQhWAFAAADIgTACQgTACAAgCQgGgBgJADQgLADgDAAIgRACQgCACgGAAIgKgBQgGABgJAGQgIAGgGABQAAAFgdAEQAAABgHACQgIADAAABIgTADIgKACQgLACgBACQgRAAgMAMQgGABgKAFQgKAGgGABQAAgBgNAFIgPAFQAAgCgFABQgEAAgCACIAEABQgBADgMACIAAgEIgOAFQAKAIgUAEQgWAEAAACIgTAGQgNAFgGABQAAgCgvAQIgRAGQgRAGgCADQgTAAgDAEQgFAAgHAFQgGAEgFgBQgGAAgFAFQgGAGgFAAQgCgDgFACIgIAEIgKAFQgFACgFABQgBABgLADIgNACQAAAFgJACIgOADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABgBAAQgCADgEAAQgEAAgCADQgDAEgDACIgDADQgBABgEAAQgBgCgGgBQgFgCAAAEQgFAAgBAFQgDAHgCABQAAADgJAAQgOAJgCAAQAAACgMACQgLADAAAEIgMAGQgIAFAAADQgFABgFAEQgGAEgEABIgGADQgEACgCAAQgRAJgCAAQgEAEgFAAIgQAMQAAADgIAFQgIAEAAADQgGAEgOACQgBAEgEACQgFACgBABQgFAAgEAIQgEAHgDABQgEABgIAHQgIAFgDAAQAAAFgHAEQgIADgBAFQgSALgLANQgEAAgGAGIgIAKQgGAIgFADQgBADgFACQgFACAAAEQgCAAgHAJQgGAIgDAAIABADQgFAAgFAHIgHAKIgIAIIgHAJQgDAHgLANQgJALgBAJQADAAAGgHQAIgJACgBQAGgKAEAAQAAgDAHgFQAGgFABgCQgCAAAKgJIALgJQAGAAAEgJQAEgJADAAIAGgGQAGgFACAAQACgEAHgEIALgHQAAgCAEgFIAHgFIAVgPQADgHAUgGQABgDAJgEQAIgEAAgCQgBgEAGgCIAIgDIAWgOQAEAAAFgFQAGgEADAAIAhgUQAGgCARgIQATgJAAgDQAHgBACgDQAEAAABgDQACgDACAAQAHgCABgCIAIgEQAFgDAAgBIAGgDIAFgDQAAADAMgFQALgFACgDIAHgCQAFgCAAgBQAHgBAOgJQANgIAIAAQADgEAJgCQAIgCADgDQAEAAAGgEQAFgEAEAAQAFgFAIAAIAIgIIAHAAIAGgBIASgHQAAgBAGgCIAHgBQADgEAKgBIALgCQABgCAHgDQAIgEAAgCIAQgDQAAgCALgDQAJgCAEAAQAAgGANgBQANgBACgCIApgMQAhgJAAgFQAEAAASgFQARgGAAgBQAFAAAJgCQAKgCAAgEQAygGAAgEQALAAAQgFQATgHAHgBQAAgBAYgFIAbgFQAAgBAdgGIAhgHQAIgCANgBQAAgBAFgBIAHgBIATgEQAMgDAHABQAAAIgWAFIgeAFQgQAEAAACQgDAAgHAFQgHAFgFgBQAAAAgBgBQAAAAAAAAQAAAAgBAAQgBAAAAAAQAAACgZAIIgHAFQgEADgEAAQgDAEgGABIgMABIgbAJQgQAFgMACIgEADQgEADAAACQgEAAAFAEQAFADAAgEIAMgBQAKgBAAgCQAfAAgQAFIgHAEIgGAGQgCABgHgCQgEgBgCAGQgJgBgIAEQgKAEgIAAQgFAAgHAEQgGAEgEAAQAAAEAGAAIAGgCIAHgCQAAANgmACQgBADgGABQgDACgEgBQgEAAgDABQgBACgPAFQgFAGgSAAQgLABgBAGQgEgBgFACQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgEgCgBABQAAABgFAEIgIAEQgOAFAAACQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIABACIgGACQgEACgCgBQgBAGgKABIgOgBQAHAFgHADQgFACgGAAQAAgBgIAEIgIAEQgDAGgPAAQAAgDgGACIgEADQgBgDgEAFIgEAIIgGgCQgBAAgBAAQgBAAgBAAQAAAAgBABQAAAAAAABQgFACgIAAQgEAAgMACQgNADAAADQgDAAgEAEQgFAEgDAAIgbAKQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgDADQgEAAgDACQgDACgCAAQAAADgEABQgEACgDAAQgFgBgDAEQgEAFgDAAIgHAEIgFADQAAAGgKACIgOABQAAABgFADIgHADQgDABgHAIQgFAHgGgBQgHgCgJAJQgRAEgBADIgFACQgCABAAAEIgJgBQABABAAAAQABAAgBABQAAAAAAAAQgBABgBAAIgEAAQgBAAgBAAQAAAAAAABQgBAAAAABQAAABABABQAAAGgKAAQgCgCgGADIgJAEQgRAHgIAKQgJABgIAEIgPAJQAAAEgMAGQgMAHgCAFIgJAEQgGACAAAEIgMAFIgGACQgDABgCADIgCADIgEACQgJAHAAACQgDAAgCADQgDAEgCAAQgHABgFAEIgNAPQgHAIgJADQAAAGgOAJQgOAKAAAHQgEACAOALQAPANgBADQgFAAgGAKQgFAKgBAGQgDAAAPANQAPAMAAgEQAGAAAIAHQAIAHABAGQAAAEAKACQAKACACACIAMAJQAGAAALAGQALAFAGAAQAAAHArAAQAMAMAIAAQAAABAIAAQAJABABABIALAAQAGABAFADIAOAJQANAGAFgCIAKgCIALgCQAEADACAAQgCAEADACQACABANgBQAMAAACAEIATABIAIABIAJABQAAgCAPADIASADQADgEAGAAIALAAQABACAHAAQAHAAADADIAEAKQAEAIADgBIACAAIABgCIABgNQABgFAFAAIAKAAIAPACIARAAQAAgCAKADIAMAEQAAgFAKgCQAKgBAAAGIAugFIgBgCQADgCgDgPQgEgPABAAIgEgNQgFgMABAAQABgCgBgFQgBgFgCAAIgBgUQgBgFACgMQABgOACAAIAAgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBABAAQAFAAAAgZQACAAACgIIADgJQAAgFADgGQADgHABgFIAIgfIAIgQQAFgKAAgGQAEgCACgGQADgIADgCQAHgGgBgHQAMgMgBAAIAEgGQADgCACgEQgCgFAEgBQAAgCAFgGQAGgFAAgDQACgBAFgGQAFgHACAAQAAgDAFgDIAIgGQACAAAEgEQADgEAAgCQANgGAPgPIAFgCQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIgRANQgFACgFAIQgFAHgBAFQAGgBADgDIAGgIQAPgGAAgBQAIgCANgKQALgJAKAAIAIgBQADAAADgDQABgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQAAgDAEgBQAAgDAJgHQAIgHAFgCQADgBAFgEIAIABQACgCAFAAQABAAABAAQABgBAAAAQABAAAAgBQAAAAAAgBIAIgGQAHgGAAADQAGACAAgLQAGgBAFgEQACgCAJgCQAAgDACgDQADgDACAAQAAgCAMgGIANgHIACgFQABgCAEgBIAGgCIAGgFIAFgBIAFgCQAEgEAHgDQAIgDADgDQAFgEADACIAEADQADAHgOAHIgSAIQAAACgSAJIgMAJQgIAFgCAFQgEABgIAGQgIAGgGABQAAAIgLACIgMAJQgGAFgCAFQgIACgHAIQgCAAgDADQgDACgEAAQgGABgCAHQgIAEgCAJQgEACgEAFIgIAIIgPAMQgKAHAAAHQgNAGACANIgDAEIgCAGQgFACgBAJQgCAAgEAFIgFAFQgJAKAAgEQgDABgBAHQAAAGgIAAQAAABgEAEIgFAEIgBALIgGAJQgEAGgBAEIgMAKIgEAMIgGAEQgBACABAFQgBAAgEAHIgDAJQgDABgFAIIgHAHQAAATgIADQgGACABAJIAAANQgEAAgBAZQgBAZABAAQABgJAIgNQAKgOABgHQADAAAFgIQAEgGAAgDIALgUQACgBAFgIQAEgHAEAAQAEgPALgCQgCgKAMgGIANgPQABgEAJgIQAIgHAAgFQAFgCAGgIQAFgJAFgCQAAgDALgJQAJgIAFgDQAAgDALgHQAKgGAAgCQAGgEANgNIAPgNQAEAAADgFQADgFAEAAQACgEAHgGQAHgFAEgBQABgDAFgEQAHgEABgCQAIAAALgMQAMgMAGAAIAKgHQAIgFAAgCQADgBABgDQAAAAAAgBQABAAAAAAQABgBABAAQAAAAABAAQAIAAgCgGIAGAAQAAgCARgIQAQgJAEgBQAAgEATgKQARgJAGAAQADgGAJgFQAIgEAHgCQAAgBAJgEQAJgEACAAQACgCAUgJQATgIAAgBIAEgEQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAQABAAABAAIAGgBQAAgCAIgDIAIgCQADgDAIAEQACgJAFAAQAGgGAIAAQAAgCAHgCIAKgDQAFgHAZgGQABgCAGgBQAFgCACgCIAGgCIAHgCQAAgCAGgBQAGgBAAgBIAEADIAdgQQAAgBAMgDQALgCAAgCQAXgGAAgCIAJAAQAHAAADgEQADAAAPgJQABAAABAGQAAgIAVgEIAMgEQAJgDABAAQAQAKgEgHIgCgDQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAugJQACgEAXgEQAWgEAAgBIAIgDQAEgCADAAQAAgDARgBQATgCABgCQADAAADgDQADgDADAAQAAgCALAAQAngIADABQAAgCAvgIQAHABANgDIAVgGQAYgFAGAAQA9gJAGAAQAJgBAVgEQATgEAMAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAKAFQAIADAAgGIAUgCQA+gHAAACQADABAZgFIAigBQAfAAAAgCIBjgBQAAgCAoADQAsAEAEAAIAKAAQADAEAEgCIAIgCQACAHgDgBQgBAAgBAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgFAEgNAAQAAAAAAgBQAAAAgBAAQgBAAAAAAQgBAAgBAAIgFACQgEAAgDgCQgDgCgCAAQgNAHAAgEQgQACgIgCQAAgCgMABQgMACAAABQgLAAgKABQgCAFgGgCIgKgDQAAADgLAAQgKgHgCACIgDADIgFABQgDADgGABQgDAAAAAHQgMAAgCAIQgCAIAMAAQACADAKABQAKABADACQAAgFAHADIAKADQAAgEANACQAIABgDACIgFADQgCACgJAAQgIAAgEgCQAAABgHABQgGABgBAFQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgCADQgKAAgIACQgKADgHAAIgqADQgCAEgLAAIgRAAIgtACQAAABgfAEQggADgFgBQAAAGgzgBQAAABgIADIgJACQgYAAAAADQgFgBgOADIgiACQAAABgVAEIgYADQAAgDgKAHQgLAGAAACIAhAAIAbgEIATACQADAAAFgCQAEgCAFAAIAOgDQANgCAAACQAFABAHgFIAOABQAAAFALgHQAKgBARgDQAAgCAJAAQAGgBAFABQAGACAGgBQAGgCAFACQAAgDARgDQARgEAAAFQArAFAAgDIAJABQAGABAAADQgNAHgDgBQgFgBgKABQgLABAAADQAkgDBBACQANAAAaAEQAYADANAAQAlAAA5AKQArAFAAAFQAFAAAXAFQAZAFAAADIAIAAQAEAAABgEQAJgDAFAAQAFAAAFACQAAABAIACQAIACAAACQATAAAZAOQAPASgBAAQAAAGASAAIgLgKQgIgHAJAAQAGAAAJAFQAJAFAFAAQAqAWAEAAQAAABAPAEQAOADAAADQADAAAHAEQAIADADAAQAAABAoAOIAZAOQASALAAAHQAEAEAFACQAAACAJAIQAKAIAAADQAHAMACAAQAAADAEAGQAEAGAAAEQABAAACAHIACAJQAEAAAFATQAFATADAAIAJAUQAFAMAAAKQACAAAFAbQACAAAGAXIANAyIAHAaQAHAXgDAAQACAGADApQABADgCAFIgCAIQgCAAAAAGIAAAJQgCAAgDAIIgDAJQgDABgFAPIgFAPQgBADgDAAIgDAAIgBAGQgBAAAAAAQgBABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgIAAIAAAEQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgEACgBAGQgCAAgDAGQgDADgCgFQgHABgFAFQgEAAgCAIQgCAIgCABQAAAHgGADQgGADgGgCQABANgJgDQgMgEgCAEIAAAMQgCABgDADIgCADIgEACQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAGQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQgJgCAAABIgKAEQgEAAgCADQgCAAAAAFQgBAFACAAQgBAKgNABQAAgDgIgBIgLgCIgGADQgGACAAADQAAADgMACQgEABgKAFQgKAFAAADQgCAAgNAHQgNAHAAACQgFACgDAHQgCAFgHgCQAAACgDAEQABAAACAEQACADAAACQgGACgLgDQgLgDgFABIABAKQAAAGgFAAQgCgDgEACQgBABAAAAQAAABAAABQgBAAABABQAAAAABAAQADACABADQgEACgFAAIgJAAQgCAAgHgFQgHgEgFAFIgDAGQgBACgEABIgHAEIgFADQgBAFgJAAIgPgBQAAAHgJADQgLADgCADIgDADQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAgBgBQgCgDgDAAQgEgBAAAEQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAIAAAGIgMABQgDAAgGAFQgEADgDgHQgDgBgDAFQgDAEAAAEQgFAAgFADQgFADAAAEIgGgBIgHABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAADQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgEAAIgPADQgFAGgHACIgPACQAAAAgBAAQAAABAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAADABAGQAAAEgNgEIgHAFQgHAEAAADIgJgBQgEABgCAGIgJADQgHABgCgEQgGADgHAFIgMAIQAAAGgRgDQgSgDAAAIIgFgCQgBgBgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBAAgDAFQgDAEgCgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgGAHQgDAFgFgBIgEAAIgFACQAAAAgBABQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgFAFIgJAEQgHADABABIAYAAQAOgBAIgDQADgBAcgFQAYgFAAgDQADgBAFAGQAEAGAEgCIARgFQACgFAZgDQAAgBALgDIALgEIALgCQAJgBgBgDQARgHABAHIAPgGQAKgDAHABQgSALgFABIgpAUQABgGgKACQgIABgEAEIAEADQgEAAgUAIQgUAIAAACIgJABQgIACAAADQgFABgFgBIgJgDQgBAKgHgBQgMgBgCABQAAABgIABQgJAAABAEQgRAJgKABQgWADAAACIgIABQgGgBAAgBQgDgBgEABIgHACQgWAMAAgIQgDAAgEACQgFABgBADQgDgBgIADIgGADQAAABgVAEQgGAAgFAEQgGAEAKABQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIADABQAAgDARAAQAQgBAAgCQAIAAAWgHIAdgEIAkgGIAVgEQATgEAAABQAIAAAMgEIASgHQgBgBAOgFIAQgEIAVgIQAPgHAEAFIgUAKIgRAHQgGABgLAGQgMAFgEABQABADgKACIgNACQgKAGgLACQAAgCgMAIQgCAFgDgFIgDgDQgEABgFADQgFAEgDAAIgKADQgJABAAADQgFAAgGACQgGACgGAAQAAAJgLgMQgCAGgBAAQgDgFgJACIgLADQgFAGgBADQgFAAgEgDQgFgDgEgBQAAAFgGAEIgLAEQgXALgNgLQgMAEgDAAQAAAHgPAAQAAACgMADQgLADgEgBQAAgEgIAAIgMAAQgCAHgBAAIgHgBQAAACgVgBQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAADgJAAQAAgGgEAIIgDAEIgIAEQAAgEgHABIgIACQgCABgQAAQgOAAgBADIgYAAQgFAAgHgDIgMgDQgHAHgIAAIgRgDQAAABgKADQgKACAAABIgPACQgMACgEgEQAAgBgNAAIgRgBQAAAFgHgBIgKgCQAAADgPABIgFAAQgKAAAAgDgACUKCQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAdgDQAZgCABAEQABAAAAAAQABAAAAgBQAAAAABgBQAAAAABgBQACgDADAAIAEAAIADgBQAEgBAGABQAHAAADgBIAOgFQAJgCAHAEQABgGAEADIAFAFQADAAAFgFQADgGAEABIAHACQADAAAFgDQACgBAFAAIAHgCQAFgBABABIABAFQAEAAAEgGIAJgDIASgFIALgBQAHgBAEgDQALgFADAAQgFgBgPAEIgTAGIgfADQgPACgVgBIgWAEQgSACgBgEQgNACgBABQgKADgJgCQgKgDgNACIg1ADQgFABgCgFIgKADQgBgDgFgBQgIgBgCgCQgLAEgEgBQgMgDgagBIgagBQgFAAgJgCIgOgBIgMAAIgKgCIgBACQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgDgCgCABQgBgDgFgBIgHAAQgKgDgYgBIgOgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABIgDABQgLABgIgDIgFgDQgCgCgDABIgNAAQAAgCgFAAIgHAAQgDgBgEAAIgIAAQgEAAgDgCIgGgEIgPgDQgJgBgEgEQgFgEgBAAQgCACgEAAIgKgCQgGgBgEABQgBgEgMgDQgIgCgGAAQgDABgDgDQgCgCgDABQgDAAgGgBIgKgEQACABgSgIQgQgHAEgBQgCgBgHAAQgGABgDgCQgIgEADgCIgQgFQgDgBgPADQgRADgOgBIApAdQARgBALAEIANAFQAIgBAMAGIAMAFQAKAEAAACIAHgCQADgBACADIAGAHQACgBAIgBQAJgBABADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIASAGQADACAFAAIAIABIASAFQAEACAFABIAJABQAQAEAjAEQA8ALA6AFIAbACQARABALACIAhABQADgBALACIAQABIAMgBQAIgBAEACQABAAAAAAQAAAAABAAQAAAAABgBQABAAAAAAIABgBQABAAAAAAQAAABABAAQAAAAAAAAQAAABABAAgAGCH/IgCgHQAAgDAHAAQABABAHgBQAHgBABgCIAPADQALACAAgEQAGgHAHAFIAMAHQAGAAAAgDQgBgEADgCIAHgCQACAAACAEQAIgIAQgBQAJAAAQABQAAgBAFgCIAGgDIARAAQAAgCAPAAQACAGAEAAQAAgGAIgBQAHgCAAACIAJgCIAJgCQAAAAABgBQAAAAABAAQAAgBABAAQABAAABAAQADAAACgDQALgFAIADQACAAATgEIAGACQAAAAABAAQAAgBABAAQAAAAAAgBQABgBAAgBQAAgBAAgBQABgBAAAAQAAAAABAAQABgBAAABQAFACABgBQAAgCAPgDIARgDQABgCAOgFQANgFAEAAQADABAEgEQAEgDADAAQAAgDAQAAQAGABALgHQAGAAALgFQALgGAGAAQACgDANgEQANgFAFAAQABgCAMgEQALgDAAgBIAVgIQADAAAEgCQAEgDAEAAIAKgEIAHgDQAEgCAEgBQABgDAGgBQAGgCACgCQAEAAAIgDQAJgEACgCQAEAAAHgEQAHgEADgEQAFAAAJgFQAIgFAGAAIAYgMQAAgBAVgIQAWgJACgDQAFAAAJgFQAIgGAGAAQAFAAAGgGQAHgHADAAQAEAAAGgGQAHgGADAAQAHAAAKgIQAEgCAHgHQAAgBAGgCQAGgCAAgCQgHAAAGgCQAFgCADAAQAAgEAJgBQAHgBADABQAAgDADgEQADgFAAgFIAQAAQAAgEAEgCIAIgFIANgIQAAgFAMgGQALgGAAgCQAMgCADgDQAGgEADgJQAFgBAQgbQAMgGAGgKIACgEQABgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAQADAAAFgJQAFgKAFAAQADgFAAgJQAFgDgBgEQABAAACgMQACgNACAAQAAgBgCgFIgEgGQAAAHgLAAIgFAGQgEAGACAAQAAADgHAGQgIAFAAACIgFAGIgGAIQgDAAgFAFIgIAFIgFADQgFADABAEIgJADIgHADIADAAIgBAEQADAAgMAKQgDADgIAAQgHABgCACQAFAAgFAHQgFAGgEAAQgJAMgOADQgEAIgOAFIgCACQgBAAgBAAQAAABgBAAQAAABAAAAQAAABAAAAIgKABQgCABAAAHQgbAFAAAGQgPALAAABIgJADQgGACgEAAQAAADgFACQgEACgEAAQgEgGgEAHQgEAHgCABQAAACgKAGIgMAGQgEABgIAGQgJAGAAAEQAAACgMAEIgQACQAAAEgJACQgJABABAEQAAABgaAFQAAAHgOAGQgLAFgKABQAAgFgOAHIgOAGQgDAAgJAEQgIAEAAABQgEAAgHADQgHADgEAAQAAACgJAEQgIADgCgBIgBADIgBADQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgDABgCgCQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAFIgDAAIgCgBQAAADgFABQgGABAAABQgEACgCgBQgDAAgDACQgDADgMAAIgIAGQAAABgKADIgNADQgNAGgDAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAAAABIgYAKQgYAGgGAEQAAADgXAAIgHAEQgEABgBAFQgFACgEgBIAAAFIgPAAQAAAGgGABQgHACAAgCQgDAAgLAFQgJAEgFgBQAAgBgGACIgHACQgDADgIAAIgMgBQgCAEgLAAIgbAJQAAABgFACIgJADQgFADgKAAQgDgDgDACIgFAEIgKgDQAAAHgNABIgTABIgIABQgFACgBADIgMgBQgcALgDgBIgUACQgSADAAACIgPADIgOACIgHACQgFACAAABQgIAAgQACQgVAEgDAEQACgCATAAQAAAEAZAAQADgEALABIAQACQAAgEANACIAOABQACAAADADQADACADAAIAAAAgAn2HeQgCAEgDAAIANAKQAJAGAEAAIADgDQABAAAAgBQAAgBAAAAQgBgBAAAAQgBgBgBAAQgBgDgGgFIgKgFIgDgCIgCACgAAUGwQACAEACAAIAIACQAFABACgEIADgBQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAgBAHgBQAHgCAAgBQAigBAAgFIAGABQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAFgBANADIAJgDQAGgDADAEQACADAFgBQAFAAACgDQACgCAFACIAIACIgEgEIADgGIAKgCQAGAHAAgFIASABQAFgCAHgHQACgBAKABQAJABADgDQAEgEAHAAIALABQACgFALABIAOABQAAgDAHABIAJADQAAABAKgHQAKgBAOACQAAgIAPgBQAAgBAVgEQAVgFADABQABADAMAAQAMAAACgEIACgFQAEgEADAFQACABAEAAIAGAAQAAgIABgCQACgBAIABQABAEAHgDIALgDQAEgBAKAEIAIgEQAAgFANgDIARgCQAHgDAEgGQADgCAHABIALABIgBgFQAEAAABgCQACgDADgBQADgBADABIAHACQAAgCAPgCIASgBIgCgEIADgBQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAJgBAHgEQAJgHAFgCQAXAAADgFQANAAABgCQAGAAgDgGIAKgBIAEgGQABgBAAgBQABgBAAAAQABAAAAAAQAAAAAAAAQADABADgCQADgCADABQAAACAHAAQAHAAAAgCQAHAAAEgDIAJgIQAHgBAEAAQACgEAEABQAGACACAAQAAgBASgGIAUgIQgDgDABgCQACgCAFAAQADADAFgCIAIgDQAAgBAHgBQAHgBAAgDIAGACQAIgFgEAAQgBgDAPgEQAQgEAAgCQAHAAAHgDIAOgIQABgCAIABQAHABAAgEIADgDQABgCAFAAQAEAAAHgDQAAgBAKgDQAKgCADABQgBgFAFgDQAGgEACgDQAPABAAgDIAHABQAEAAABgEIAKgIQAAgDAIgEQAHgFAEAAIALAAQAAABATgLQAAgDAHgFIAIgFQAGAAAIgHQAIgIAFAAQAAADASgNQAIgGAKAAQAUgNAAgCIAWgPQALAAAMgIQADgHAEAAQADgDAJgDQAJgEACgDQAFAAADgGQADgHADAAIAKgHQABgDAEgEIAHgGIAGgCQAFgBABgCQAAgFANgGQAMgHgBgDQAVgZADgBIAHgPQAFgKgHgDQAAgCgHgEQgIgDgBgDQAAgDgEgCIgHgFQgMgLgGgDIgQgHQgNgHAAgDQgGAAgJgFQgKgGgEgBQAAgBgJgFIgKgHQgEgBgIgFQgHgFgEAAQAAgBgSgEQgUgHgDgDIgQgIIgKABQgHABgEgBIgFgCIgHgBQgRgLgDAAQAAABgSgHIgJgDQgDgEgGgCIgKgBQgtgKgGgBQgGgHgWADQgSACgDgEQgDgEgHAAQAAgBgOACQgPACAAgDIgTgBQAAgEgGgBQgHgHgIAEIgNAFQgHAAgKgEIgRgGQAAAFgXgBQgWgBAAgJQABgEgFgBQgEgBgFABQgCADgIgCQgBgBgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAADgJgBQADAHAAAEQAHAAACAeQACAcgCAIQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABABQAAAAAAAAQgBABAAAAIgBAUQgBATgEAAQgBADADADIgIAQIgGANQgFAIAAAGIgGAPQgFAOgHAAIABAFQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIAAAEQgCAAgCAGQgBAGgDAAIAAAEQAAABgBAAQAAAAAAABQAAAAgBABQgBAAAAABIgFAEIgBAHQgDAAgBAFQgBAAgGAIQgHAJgFABQgBADgIADQgIACABAFIgCAFIgCADQAAACgEAEIgGAFQAEAKgSACQgBAGgHAEQgIAGgCADQgFAIgTAJQgCABgDAEIgFAFQgJAAgRAOQgUARgFACIgNAFQgJAEAAAEIgLAHQgGAFgGABQAAgBgFAFQgFAEABAAIgKAFIgKAGQAAABgLADQgMADAAAEQgJAAgRANQgSAMgMAAIgKADQgIAEgBABIgJAHQgFAFgFAAQgeAKgEAAQAAACgJAGQgJAFAAgEQgEAAgHADQgHAEgDADIgLACQgFABgEAFQgFAAgKAGQgJAGgEAAQgDAFgVAAQgCADgDACQgEABgBACIgGABQgEABgCgCIgGgDQgHgBgGADIgKAIQgBAFgNAEQgDAAgIAFQgHAEgEAAQgsANgHAAQAAADgZAHQgaAIgDADQgTACghANQgHADgOAAQAAAGgPAAQAAACgVAGQABgGgiAKQgEAAgGACIgKAEQAAgBgMAEIgPAFQgIAGgMACIgWAFIAFAAIABABIARACQAOACABgDQAcAAASAEQAsgBAAAFQAFABAvgHQAHgDAHAEIANAHQAAgCAQgCIAUgCIAQgBQAEABACADgAqtGZQgHgMAAgBIAHAFIAGAEQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIADgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgGAAIgCgBIgBAAIAAgBQgDgDgDgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgDgBQgjAFAAgEIgJgBIgIgCQAAgEgOACIgQADQgGAJATADQAWADAAABIAVABQARAAAAACIASAAIAAAAgAopGGQgDABAAAFIADAEIAEAFIAHgBQALAAgJgLQgFgEgEAAgAmTFsIAIAOIAFAFIAOACQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAIAOgCQAJgCAEABIBCgLQAAgCAVgDIAYgEQBOgSAHAAQAAgBAXgGQAXgFAEAAQAAgDAWgEQAWgDACgEQAHAAAKgEQALgDAGgBQAGAAALgEIAQgFQACgDAdgHQAagGgBgHQAYgBAAgDQAJgBARgHQAAgBAJgCQAJgCAAgBQADAAADgCQABgBAAAAQABgBAAAAQABAAAAgBQAAAAAAgBIAGgBIAFABQAAgDAQgFQAOgEAFAAQACgDAJgDQAKgCAAgDQAEAAAIgDQAJgDACgDQAGAAALgEQAJgEAFgEQAGgFAPgDQABgCANgEQANgEAAgCIANgGIAOgHIAPgFQAKgEADgEQACAAAJgFQAIgEAAgBQAEAAAIgEQAIgFADgDQAKAAAOgKQAOgKAIgBQACgEAUgJQATgKgBgCQAAgBANgHQAOgHAAgBIAHgGQADgDAFgBQAKACAEgGIAEgIQAEgIAFAAQAAgBAFgEQAGgDAAgCQAFgBAIgHQAIgHAFgBQADAAACgFQACgFADgBIAIgFIALgKQAEgCAFgHQAFgHAEgCQAAgFAOgMIAOgRQACgEAFgIQAGgIACAAQABgGAFgHIAGgMQACAAACgFIACgGIACgHQACgGgBgDQgFAAgJAOQgKAQgEACQAAAGgMAJIgLAKQgGAHgEACQAAAFgHAFIgKAKQgBACgIAFQgHAEAAAEQgDABgDAEQgDAEgFABIgEAFQgEADgCAAIgHADIgIADQAAACgEADQgFAEgBADIgKAGQgHAGgBACQgDAAgJAGQgJAGgCADQgKADgQANQgPAMgMACQgFAGgMAEQgLAEgIAAIgOAOQgFAAgHAGQgHAFgDAAQgCAEgIABQgHABgDADIgHADIgGADQgCAAgEAEIgFADQgCAEgJAAQgJABgDAEQgEACgDAAQgCAEgIABIgNABIgJABQgGAAgDABQgDABgDAHQgDAGgEABQgEAEgFgCQgHgCgDABQAAAEgFACQAAAEgVAJIgbALQgDAAgFADQgFADgDAAQAAACgNACQgEAEgIADQgHACgGAAQAAACgNADQgNADAAADIgNACQgKACgCADQgGAAgCABQgDABgFAFQgHAAgGACIgNADIgWAHQgBACgKACQgKACAAACIgbAHQgFAAgIADQgIADgFAAQgCACgOAEQgNADAAABQgDAAgFADQgFADgDAAQgBACgGABQgFABgCgCQgRAHgCAAQgDADgNADIgMACQgEABgKAEQgIADgEAAQAAACgOAAIgQgCQAAABgJADIgMACQgPAAgMAFQAAAFgLACQgMABAAABIgXAAQgQAAgFAFIgDACIgDADIgJADIgHACQgCADgcAEQgcAFAAACIgFAAIgFAAgAxuEwQAAgCgHgCQgFgCgEAAQAAAGAQAAgAzoD+IgCADIAOALIAKACIALACQAEAHAcAKQAbAKAAgGQgOAAAAgHQgQgCAAgCIgUgKQgCAAgEgIQgEgHgGAAQAAgDgKgBIgKgBIAAAAIgGACgAmhD9QgJAEgBADQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAIADAAQAAACAsgFIA0gGQAAgDAWgEIAcgFQABgDANAAIARAAQAFAAARgGQANgEAIACQAAgCATgDIAWgEQAAgFALACQAMACAAgEIAKAAQAGAAADgEIAJgDQAFgGAQACQAQABACgFQgIAAAHgEQAGgEAEAAIANgBIAEACIAFABIASgEQAAgCgFABIgHABQgDgGAcgHQAXgHAKAAQAAgBALgCQALgBABgCIAHgCIAHAAIADADIAFABQAAgBAAgBQgBgBABAAQAAgBAAAAQABAAABAAQgCgFAEgBIAJgCIAKAGQAKAGADgBIgHgDIgDgKIAGgFQADgBAFACQACABAMgFQALgFAAAEQADABAEgCQAEgCAAgCQAOAAADgFQAAgJAJAAQACgEAKAAIANAAQAFgBADgEQADgEADAAIAVAAIAEgJQADgDAEABIAGADQgBgJAGABIALADQADAAAEgDQAEgEADAAQACgCAJgFQALgFABACQAAgHAUgCQAUgCAAgCQAIAAAFgBIAFgDIAGgDQACgDALgDQAMgDAAAGQAEABAOgEQAGgEABgFQgEAAAEgHIAFgIQAEgCAAgJIANgHQAJgFAGAAQABACAKACIAMACQAAAEAMgGQALgFACgEQgHAAgCgMQAFAAAMgPQASgEAAgCQAMgCAOgGIAWgKQAFgFARgHQAOgGADgHQAGgCANgOQALgMAHAAQACgDAFgDQAFgEACgDQACgCAHgGQAHgFAAgEQACAAAFgIQAFgHAAgCQAEAAAJgXQAKgXgCgFQgCAAAAgMQABgMgEgCIADAAQgBAAgDgHIgHgRIgSgBQAAACgPgEQgPgDAAADQgmAHAAgBQgLABAAgCIgIABQgFABgDgDIgHABIgJABQAAgBAAAAQAAAAgBAAQgBAAAAAAQgBAAgBABIgGABQAAAEgMABQgLABgFgBIgPgBIgDAFQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIgOABQgCAHgNgEIgUgGQgBACgIABQgFABAAAHQgYAAgEABQAAADgUABQgUABAAACIgZABQgLAAgDADIgBABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgQABQAAABgGACIgIABQAAgBgSADQgTACAAACIgMADQgIACgFAAIgJAIQAAAEgJgHQgDAAgBADIgCAFQgBADgEABIgGABQAAAEgMAAQgBACgEABQgEABgDADQgDADgGAAQAAgEgGABIgKACQAAAFgWgCQAAAGgJADQgLADgCACQgCAAgEADIgHAEQgEACgCgBQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgDAAgCgCQgEgCgCAAIgIADIgIACQgDgCgEACIgHADIgEAEQgEAEAAACQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABIgBAEIgEAFIgCAAQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgDABgCgCQgDgCgCABQgFAJgVACIgUAMQgKAEgEgDIAAgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAQAAgBgKAHQAAAHgEABIgIgCQgBgBgHADQgHADgBACQgFAAgDADQgDADABAEIgMACQgNADgEAFQgEAAgBAFIAAAGIgRAJQgEAGgIAAIgMgCQACAMgGACIgMAHQgMAIAAgFQgGgEgBADIAAAEQAAADgKAIQgLAGgEABQAAACgGAEIgKADQAAgGgFAEQgHAFACAAQAAAFgHAIQgGAHgFAEQgCAFgFADIgKAEQgJADgDgEIgIAHQgFAFAGAAIgCAHIgGAJQgFAGgCAAIgKAJQgHAHgCAEQgGAAgCADIgEAJQgEABgEAFIgGAHQACAEgZAYQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIAPgBIAqgFQAAAFARgHIAFAAIADgCQAAAAABAAQABgBAAAAQAAAAABAAQAAAAAAABIAEACQABgFAKgDIAJgEQAGAAAVgEQASgDAEAIQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAgBABAAQACgEACAAQAAgBAFABIAHAAQAAgBAGAAIAJgBQAAABAAAAQAAABABAAQAAAAABAAQABAAABAAQAAgKAqAAQAAgEAKgBIAOgBQAAgHAZgBQAZgCAAADQADgBAEgEQAEgDACAAQAAgCAHACIAIACQAAAHAVgMQAAgCAHgDIAJgCQAFAHAHgBIARgDIAOgBQAHgBAAgGQgEADgEAAQAAgEADgCQAEgCABgCIAOgCIAGgCQAAgFALAAIAPAAQAHAHAGgGQAJgKAEgBQAMAAAAgCQAFAAADAFQACAFgHAAQAAAEAHACQAGADAAgFQgEAAgBgDQAAgEAEAAQAAgCAKAAIAGgEQAFgCAAgDQAHAAAEgDQABgCAEABQAEABACgBQAEgHALAAQACABAHgDIAIgEQAVgLAAAFQALAAgDgBQgIgEgBgCQgHgCAGgCIAJgBIAFAGQACACAEABQAMAAAAgCIAYgLQAFAAAJgEQALgEAFAAQAAgEAMgEQAKgDAFAAQABgCAFgCQAFgCACgCQAQgEACAAQAEABADgDQAFgFADgBIAJgFQAHgDACAEQACADgLANQgEAAgHAGQgIAFgEAAQAAAFgNAGQgOAGgCAEQgCAEgKACQgIABgCAEQgEAAgHAFIgJAHQgcALAAgBIgTAPIgMAEIgLAEQgZAGgGAIQgGgBgGAEQgGADgEAAQAAABgMABQgLABAAAGIgQADQgLACgEAEQgMAGgHABQAAACgJADIgKAEIgEAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgKADQgEAGgJABIABADIgGACIgHACIgJAAQgFgBgEABIgKAGQgKAFAAgBQgIAAgPAFQgPAFgJAAQAAABgWAEQgWAEAAADQgdALAAgEQgEAAgIAFQgHAFgEAAIgQAFQgRAEgBABIgZAFIgkAJQgaAAgCAEIgIACIgIACQAAgDgUAHIgNAEQgIADgHAAQgKADgFAAIgTAAQgFAFgMAAQgNgCgFABQAAABgIACIgLADIgBgBIgIACgAz3D2QAEgHgIgCQAAgBgEgEIgFgFQgDAAgIgFQgHgEgEAAQgBgDgHgGQgHgGgDAAQAAgCgLgIQgLgIgEAAQACAFAGAIQAGAHAFADQANAKgCAAQADAFAGAAQAWATAAgCQACABAFgCQAAAHALAAgApzCuIAGAEQgEABgCADQgDAEADADQAFADgDADIgEAEQATgEAAgBQADgBAFABIAHACIAEgBIADgDIADgBIAKgCQgFgZACAAIgCgJQgCgGABgDIACgOQABgIABgEQADAAgBgIQgBgIgGgBIgMASQAAAFgGAJQgGAJABAEQgGADgCACIgEAJQgCAAgCAEIgDAFQAAAEgIgGQgBABAGAEgAnqBaQgEAAgDAIQgEAKgDABQgDAVgBAAIAAACQgDAAgDAUQgDAUACADQADgBAFgIIADgIQADgHACAAIAFgLQAEgIACAAIADgHQAEgFAAgDQACAAAEgJIAFgLIAIgGQAHgGAAgCQAEAAABgDIABgIQACAAACgDQABgEADAAQAIgJABgEQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIACgFQAIgFAHgLQAEAAAGgJQAFgJAGAAQAegLgOAAQAAgGAFgCIAJgDQAAgGAIgEQAIgEAAgFQAFgBADgEQAEgFADgBQACgDAMgGQALgFAAgEQAKgGAGAAQAAgEAIgFQAIgEAAgDIAGgEIAHgEIAHgFQADAAAIgHQAIgGABABIALgGQAIgFACgDQAHgFABgGQAFAAAGgBQAGgCAJgGQAAAHAMgIIAPgKQACAAAGgEIAHgGQABgBAIgDIAIgDQAhgKAAgDQAFAAAJgEQAIgDAGAAQABgEAFACQAHABACgIIAGgCQACAAAHgEQACgCAOgEQANgDAAgCIAJgDQAGgDAAgDQAQgCAAgBIAJgCQAHgCAAgBQAFAAAKgEQALgFAGgBQAAgBAIgDIALgCQA2gRAEAAQAAgBAOgDIAQgEQATABAAgGQAFAAALgDQAKgDAGAAIAfgIQAAgCAMgBIAOgBQAAgCAMgCQAMgBABgCQAEAAAGgCQAHgDAEAAIAMABQAHgBADgDQAXgCAKgDQAAgEAygEQADgFAeAAQASABARgEQAAgFA4gBIA+gBQAAgCAGABQABAAABAAQABAAAAgBQABAAAAgBQAAAAAAgBIADAAIgBgCQgEAAgEgIQgFgIgDAAQAAgDgHgHQgHgGAAgEQAHgCAJADQALADAAAIQAEABAFAEQAFAEACAEQADACAAAFIADABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAEADQAEgBAEABQAGABAMgBIAUAAIAmACQAhABAAABQAIABAHgBQAAgCAUACIAZADQArACAAACIAzAEQArAFAAAGQAKAAAUAFQAVAEAKAAQAAACAPADQAPACAAACQAHABAKAEQAJADAHABQADABAHADQAGADADAAQAAADAJAAQAKABABACIAcAJQAEAAAIAEQAJAEACADQAOAHAAgDIAEABIACACQAEAAALAGQALAGAAABQAFAAAIAGQAIAFAEAAQAAABAHAFQAHAEACAAQAAABAIADQAIAEABACQADADAKAFQAIAFADAEQAHAAgHgJQgGgKgFAAIgEgEQgEgDAAgCQgIAAgHgKQgEAAgKgJQgLgKAAgDIgLgBQgHgCAAgEIgDgCIgGgBQgIgIgCgBIgOgHQgGgEgHAAQgEgFgKgDQgEgBgBgCQgCgDgCgBQAAgCgSAAQAAgGgLgCIgPgCQgHAAgHgDQgIgEAAgEQgIAAgNgJQgNgKgHAAQAAgBgKgCIgKgBQgZgHAAgCIgPgDQgIgDgEAAQAAgEgdgGQgZgEgKAAQAAgCgOAAQgPgBAAgEIgXgDQAAgDgbgCIgbgDQgZgDgMAAQAAgBgMgBQgMgBgBgBIgbgBQAAADgogCQgBgCgOAAQgNgBAAACQgDABgGgBIgIgBQgRACgIgBIgKADQAAABgKAAIgMgBQAAADgVACQgVABgFgBIgwAEIg5AEQgFAAgYAEQgZAEAAACIgXACIgUADQAAAHgyACQAAADgkAGQgCADgJAAQgJAAgDAEQgFgBgGACIgJABQAAACgOABQgNABAAADIgeAJQgSAFgLAAIgdAKQgeAJgCgBQAAAEgNACQgOACgBAEIgOAEQgIACgFABQAAABgHADIgIACQAAABgKAEIgPADQgCAEgLADQgLADgCAEQgEAAgGADQgHAEgDAAQgVAFgFAHQgFAAgIAGQgJAGgFAAQgDADgHAEQgHAEgEAAQgCADgPAIQgEAAgJAHQgIAHgHgCQgBAEgJAAQgBAEgIADQgNAFgHAGIgPAJIgPAJIgJAIQgEAFgFAAQABgCgKAHQAAAGgYAPQgLAMgKAEQAAABgEADIgGAEQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAABgFAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQgDAEgMAHIgDAEIgEAEQAAADgEAEQgDAEgDAAIgFAHIgHAFQAAACgJAIQgDADgEACQgFABgDADQAAADgEACQAAADgDACIgGAEQgCACAAAEQAAAFgCACIgFADQgDAAgCADQgCAFgBAAQgBACgEAGQgEAFgCABQAAAGgJAGQgKAGAAAGQABAAgFARIABAIQgBAFgDABIgBABIAAAAIgBABgAxpmXQgDABgCACIgCAFQgHAAgCADQgCAAgGADQgFADgCACIgHADIgGADQgGAHgTAGQgCAEgKACQgKABgBADIgHAGQgGAFAAABQgOAAgBAHIgSAOQgEAAgPAKQgJAGgGAHQgCADgFADQgFADgCADQAAAHgIAEQgKAEgBAFQgCABgDAGQgCAEgDABQgBACgGAFQgFAEAAADIgJAJIgIALIgDACQACACAlgbQAmgdAHgBIAHgFQAEgDADAAQAAgBAEgCIADgEQgDgBAAgEIAMgBQAIgCACgCIADgCQAAgBABAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgCAGgDQAFgDACAAQACgDALgFQAJgEACgDQADAAAFgFIAHgHQAMgEABgBQADAAAHgEQAJgEADgBQACgCAHAAQAEABABgFQABgJANAAIAHgIQACgDAFABQAFABABgDQACAAAHgEQAHgFACgBQAAgCARgHQAQgHADABIgBgEQAGgBAHgEQAHgEAFgBIALgFQAHgEACgDQADAAAFgCIAHgDQACgCAFAAIAIABQACgFADgCQAGgHAPgDIAYgDQACgDAIgDQAIgDAEAAQAAgDAIACQACABAEgCIAGgEIAIgEQAEgCADAAQAEgGAOgEIAWgEQAGgBALgDQAOgEAAgDIAHgCIAFgDIAJABQAFgBAAgFQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAABgBIACgDIgGgDIgvAMIgCgBQAAACgLABQgKACAAABQgHAAgLAGQgLAGgGABIAAgDQgFAAgKADQgJADgFAAQgEgBgCADIgFAEQgEAEgCAAIgHgDIgIAEQgIADgBAEIADABQgBADgFAAQgEABACgEQgDAAgHADQgHADgEAAIgFACQgGADgBACIgDAFQgDABgDgBQgCAGgOAFQAAABgFABQgFAAAAABIgLACQgEABgCAHIgDABQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgKAAAAgCQgCAAgDACQgEADgCABIgOAHQgNAIACABIgNAGIgNgCIgDABgAlSlJQgFgDAKgGIALgHQAIgDAAgBQABgBABAAQAAAAABAAQABAAAAAAQAAABABABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQACACgOAJQgJAGgFAAIgEgBg");
	this.shape_1.setTransform(7.7928,27.7457,0.4948,0.4948);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABwDnIAAkXQAAgygageQgbgeguAAQgfAAgdAPQgdAPgkAjIAAFEIhjAAIAAnEIBjAAIAAA8IADAAQAdghAogSQAngSAqAAQBLAAAvAtQAxAxAABZIAAEWg");
	this.shape_2.setTransform(117.997,94.1892,0.4949,0.4949);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjCCoQhLhEAAhnQAAhiBNhCQBNhDBxgBQB2AABNBCQBNBBAABlQAABqhMBCQhMBDh4AAQh1AAhLhEgAh4hvQgvAqAABCQAABGAuAsQAtArBIABQBPgBAugqQAugrAAhIQAAhBgwgrQgxgrhKAAQhGAAguArg");
	this.shape_3.setTransform(90.4194,94.4243,0.4949,0.4949);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiqEwQhCgnAAg8QABgyAegeQAfgfBBgOQgygbAAgeQAAgWAWgRQAWgRAjgIIAAgCQg3gVgdgkQgbgjAAgyQAAhIA8gqQA7gqBkAAIDRAAIAABFIhoAAQAeAbAMAWQALAVAAAdQAAAbgPAeQgNAcgTARQgiAghdAPQgoAGgOAGQgXAJAAARQAAASAnAOQAiAMBQAOQBNAOAlAjQAhAfgBAuQAABEg/AmQg/AmhvAAQhmAAhBgmgAhtCYQggATAAAeQAAAiAkASQAkASBEAAQBBAAAlgRQAlgSAAgfQgBgmg7gUQgsgOg9AAQgyAAggATgAhIjvQgdAYAAAhQABAlAbAXQAcAXAtAAQApAAAcgYQAbgYAAglQAAgggdgYQgdgYgnAAQgpAAgeAZg");
	this.shape_4.setTransform(64.4501,100.1526,0.4949,0.4949);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABoAAQBmAAA5A+QA8BAAAB7IliAAQAYCHCQAAQBVAABbg2IAABXQguAcgsAMQgxAOg9AAQhxgBhEhJgAhPiAQgjAdgKA2ID9AAQgDg0gfgeQgggeg0AAQg4AAgiAdg");
	this.shape_5.setTransform(39.7057,94.4243,0.4949,0.4949);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ai3DnIAAnEIBkAAIAABoIACAAQBHhxBKAAQA6AAA/A1Ig1BNQgXgTgbgNQgagMgSAAQgzAAgjAoQgjApAAA6IAADsg");
	this.shape_6.setTransform(19.9101,94.1892,0.4949,0.4949);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Aj1DJQhahSAAh3QAAh3BchTQBfhVCUAAQCWAABfBVQBbBSAAB4QAAB3haBSQhfBXiYAAQiVAAhfhXgAitiYQhGA8AABcQAABcBGA9QBFA9BoAAQBpAABFg9QBFg8AAhdQAAhchFg8QhFg9hpAAQhoAAhFA9g");
	this.shape_7.setTransform(-9.6965,91.7272,0.4949,0.4949);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABnAAQBnAAA5A+QA8BAAAB7IljAAQAMBCArAjQAqAiBIAAQBUAABdg2IAABXQgwAcgrAMQgwAOg/AAQhvgBhFhJgAhQiAQgjAdgKA2ID+AAQgDg0gfgeQgggeg0AAQg4AAgjAdg");
	this.shape_8.setTransform(-41.7282,94.4243,0.4949,0.4949);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ai4DnIAAnEIBkAAIAABoIADAAQBHhxBKAAQA7AAA9A1Ig1BNQgWgTgbgNQgagMgSAAQgyAAgkAoQgkApAAA6IAADsg");
	this.shape_9.setTransform(-61.1773,94.1892,0.4949,0.4949);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ABFDgQgTgLgHgYQhAAuhHABQg2AAgkgiQgiggAAguQABg7A3gkQAfgUBVgbIBYgcIAAgYQAAgpgWgUQgWgTguAAQhZAAhHBLIAAhiQA7g+BtAAQBQABAxAjQA1AoAABKIAADoQAAAXATAAQARAAAkgYIAAA2QgjAVgTAHQgUAIgWAAQghAAgSgMgAhCAtQgxAbAAAkQABAcAUASQAVASAeAAQAsAAArgmIAAiDQhOAXggATg");
	this.shape_10.setTransform(-84.536,94.4243,0.4949,0.4949);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AjIDAQhRhQAAhnQAAiABhhUQBhhUCUAAQBcAAB7AuIAABXQg6gfg0gOQgzgOg3AAQhqAAhHA9QhHA+AABbQAABeBGA8QBGA7BwAAQBsAABug/IAABXQgzAYgwAMQg6AOhFAAQihAAhfhgg");
	this.shape_11.setTransform(-112.7818,91.9993,0.4949,0.4949);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CO_v_white, new cjs.Rectangle(-126.7,-7.3,264.2,124.39999999999999), null);


(lib.BUTTON = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAqIAlgqIglgpIAaAAIAmApIgmAqgAg2AqIAmgqIgmgpIAbAAIAlApIglAqg");
	this.shape.setTransform(30.575,6.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUA4QgMgFgIgIQgIgHgFgMQgEgLAAgNQAAgLAEgLQAFgMAHgHQAIgIALgGQALgEAMAAQANAAAKAEQALAFAHAJQAIAHAEANQAEALAAANIAAAGIhUAAQACALAIAIQAIAIAOAAIAIgBIAIgCIAIgDIAHgGIANAUQgJAIgMAEQgNAEgNAAQgMAAgLgEgAgKghQgFACgEAEIgFAIIgCAJIA3AAIgCgJIgFgIQgDgDgFgCQgGgDgHAAQgGAAgFACg");
	this.shape_1.setTransform(15.125,6.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AggA6IAAhwIAeAAIAAAPQAFgHAKgGQAJgFALgBIAAAeIgIgBIgIABIgIADIgHAEQgDACgBADIAABKg");
	this.shape_2.setTransform(5.475,6.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaA6QgHgDgGgEQgFgFgEgHQgEgHAAgKQAAgKAEgHQAEgGAFgEQAGgFAHgCQAHgCAHAAQALAAAJADQAKAEAFAHIAAgPQAAgJgHgGQgHgEgKgBQgTAAgPAOIgLgUQALgJANgFQANgEAMAAQAKAAAJACQAJACAGAGQAIAFAEAHQAEAJAAAMIAABJIgeAAIAAgMQgGAHgJAEQgJAEgLAAQgHAAgHgCgAgQAKQgFAEgBAJQABAIAFAEQAHAEAJABQAGgBAGgCQAHgCAEgFIAAgPQgEgEgHgDQgGgCgGAAQgJAAgHAEg");
	this.shape_3.setTransform(-5.45,6.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgQA4QgLgFgIgIQgIgIgEgLQgFgLAAgNQAAgMAFgLQAEgLAIgIQAIgIALgFQAMgEAMAAQARAAALAGQALAGAGAJIgUASQgIgMgQAAQgMAAgJAJQgJAJAAAOQAAAPAJAJQAJAJAMAAQAIAAAGgDQAGgDAEgGIAUASQgGAIgLAGQgLAHgRAAQgMAAgMgEg");
	this.shape_4.setTransform(-16.625,6.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgKBCQgIgIAAgPIAAg7IgTAAIAAgaIATAAIAAgfIAdAAIAAAfIAXAAIAAAaIgXAAIAAAzQAAAFADAEQACADAFAAIAGgBIAFgCIAGAXQgDADgGACQgHACgJAAQgPAAgIgIg");
	this.shape_5.setTransform(-31.375,4.775);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgUA4QgMgFgIgIQgIgHgFgMQgEgLAAgNQAAgLAEgLQAFgMAHgHQAIgIALgGQALgEAMAAQANAAAKAEQALAFAHAJQAIAHAEANQAEALAAANIAAAGIhUAAQACALAIAIQAIAIAOAAIAIgBIAIgCIAIgDIAHgGIANAUQgJAIgMAEQgNAEgNAAQgMAAgLgEgAgKghQgFACgEAEIgFAIIgCAJIA3AAIgCgJIgFgIQgDgDgFgCQgGgDgHAAQgGAAgFACg");
	this.shape_6.setTransform(-41.225,6.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgXBMQgPgGgLgKQgMgLgHgPQgGgPgBgTQABgSAGgPQAHgPAMgLQALgKAPgGQAPgGAQAAQANAAAKADQAKADAIAFQAIAFAGAGIALAOIgcAPQgFgIgKgHQgJgGgOAAQgJAAgJAEQgKAEgGAHQgGAHgEAJQgEAKAAAKQAAALAEAKQAEAJAGAHQAGAHAKAEQAJAEAJAAQALAAAJgEQAJgEAFgEIAAgTIgpAAIAAgdIBLAAIAAA8QgNAOgQAIQgRAIgWAAQgQAAgPgGg");
	this.shape_7.setTransform(-55.8,4.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// bkgd
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#00A7B5").s().p("Aq0C4IAAluITwAAIB6CtIh6DBg");
	this.shape_8.setTransform(-10.4,5.9758,1,1.0587);

	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(1));

	// bkgd copy
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00A7B5").s().p("Aq0C4IAAluITwAAIB6CtIh6DBg");
	this.shape_9.setTransform(-127.15,5.9758,1,1.0587);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	// shad
	this.instance = new lib.Buttonshad();
	this.instance.setTransform(-80,-14,0.6438,0.6815);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shad copy
	this.instance_1 = new lib.Buttonshad();
	this.instance_1.setTransform(-207,-14,0.6438,0.6815);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BUTTON, new cjs.Rectangle(-207,-14,276.4,59.3), null);


(lib.BKGD = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF8300").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape.setTransform(0,125.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGD, new cjs.Rectangle(-150,0,300,250.1), null);


(lib.HEAD2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD2type();
	this.instance.setTransform(0,35,1,1,0,0,0,0,36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-139,-1,278,56.4), null);


(lib.HEAD1b = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1btype();
	this.instance.setTransform(0,21,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1b, new cjs.Rectangle(-139,-3,334.1,52.2), null);


(lib.HEAD1a = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1atype();
	this.instance.setTransform(0,23,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1a, new cjs.Rectangle(-139,-1,278,33.2), null);


// stage content:
(lib.CO_SchoolisBack_728x90 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,308];
	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_308 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(308).call(this.frame_308).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,2,0,3).p("Eg4ygG8MBxlAAAIAAN5MhxlAAAg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(309));

	// HS logo
	this.instance = new lib.HS_logowhite();
	this.instance.setTransform(536.9,47.05,0.3378,0.3376,0,0,0,0.6,71.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(309));

	// CO logo
	this.instance_1 = new lib.CO_v_white();
	this.instance_1.setTransform(638.2,46.85,0.3786,0.3785,0,0,0,0.1,55.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(309));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A+kHCIAAuDMBXaAAAIAAODg");
	mask.setTransform(363.7571,44.9957);

	// CTA
	this.instance_2 = new lib.BUTTON();
	this.instance_2.setTransform(62.7,73.1,0.76,0.76,0,0,0,-10.4,3.9);
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(288).to({_off:false},0).to({x:228.7},20).wait(1));

	// HEAD1a
	this.instance_3 = new lib.HEAD1a();
	this.instance_3.setTransform(324,54,1,1,0,0,0,0,24);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(3).to({_off:false},0).wait(65).to({y:41},7).wait(140).to({alpha:0},8).to({_off:true},1).wait(85));

	// HEAD1b
	this.instance_4 = new lib.HEAD1b();
	this.instance_4.setTransform(324,47,1,1,0,0,0,0,24);
	this.instance_4.alpha = 0.6992;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(75).to({_off:false},0).to({alpha:1},7).wait(133).to({alpha:0},8).to({_off:true},1).wait(85));

	// HEAD2
	this.instance_5 = new lib.HEAD2();
	this.instance_5.setTransform(324,53,1,1,0,0,0,0,36);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(234).to({_off:false},0).wait(49).to({y:40.2},7).wait(19));

	// BKGD-orange
	this.instance_6 = new lib.BKGD();
	this.instance_6.setTransform(766.3,45.5,1.9923,0.3599,0,0,0,150.3,125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("ANGG9I6LAAIAAt5IaLAA");
	this.shape_1.setTransform(84.25,45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.instance_6}]}).wait(309));

	// PIC
	this.instance_7 = new lib.sch_img_728x902x();
	this.instance_7.setTransform(0,0,1,1.0007);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(309));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(363.5,44.5,402.20000000000005,46);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 728,
	height: 90,
	fps: 36,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/CO_SchoolisBack_728x90_atlas_P_1.png", id:"CO_SchoolisBack_728x90_atlas_P_1"},
		{src:"images/CO_SchoolisBack_728x90_atlas_NP_1.jpg", id:"CO_SchoolisBack_728x90_atlas_NP_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;