(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"CO_KidsProcedures_728x90_atlas_P_1", frames: [[0,0,232,87]]},
		{name:"CO_KidsProcedures_728x90_atlas_NP_1", frames: [[0,0,728,90]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Buttonshad = function() {
	this.initialize(ss["CO_KidsProcedures_728x90_atlas_P_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.kp_img_728x90 = function() {
	this.initialize(ss["CO_KidsProcedures_728x90_atlas_NP_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.HS_logowhite = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ap9EXIAHnRINagKIgCh7IGDgCIAZKDgAFdgfQgVAOgIAYQgGAUAAAZQAAAaAGATQAJAZAVAOQAVAOAgAAQAyAAAeggQADgDgEgCIgZgYQgCgDgEADQgSARgZAAQgfAAgHgZIgDgKQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIBxAAQAEAAAAgEQAAglgGgUQgIgYgVgOQgVgOgfABQgeAAgVANgAgnAvQgVAQAAAdQAAAdASAPQARAOAaAAQAjAAAQgVIABAAIAAANQAAADAEAAIArAAQADAAAAgDIAAh4QAAgjgSgPQgUgRgtABQgqAAgaASQgDACACADIARAeQACADADgDQAQgKAZAAQAWAAAIAEQAIAHAAANIAAAHQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIghAAQgkAAgUAOgAnMBXIgZAdQgCACACADQAiAdAzAAQAoAAAWgSQAVgRABgeQAAgyg/gGIgUgCQgPgCgGgEQgFgDAAgHQAAgOAYgBQAbAAAXAOQAEADACgDIAVgaQADgDgDgDQgegWguAAQgkgBgVARQgUAQAAAaQAAAzA9AHIAVABQAQACAGAEQAFAEAAAHQAAASgdAAQgfAAgagVIgDgBIgDABgACfgkIAACyQAAADAEAAIAuAAQAEAAAAgDIAAhjQAAgnAdgCQAMAAAPAJQADABACgCIAWgmQACgEgDgCQgNgLgUABQgjgBgOAYIAAAAIAAgPQAAgFgEAAIguAAQgEAAAAAFgAieAiIAABsQAAADAEAAIAuAAQAEAAAAgDIAAh2QAAgegRgTQgRgUgeABQghAAgPAUIgBAAIAAhZQAAgDgEAAIguAAQgEAAAAADIAAD/QAAADAEAAIAuAAQAEAAAAgDIAAhsQAAgPAIgKQAIgJAOAAQAdAAAAAig");
	this.shape.setTransform(25.025,83.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAaAAQABABABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_1.setTransform(27.15,92.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeATQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBQAAgGACgIQAHgTAXgBQAZABAGATQACAGAAAIQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_2.setTransform(65.075,85.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AqIk4IUcAvIAII0I03AOgAhWAjQgVAQAAAeQgBAdAUAPQAQAOAbAAQAkAAAPgVIAAANQAAADAEAAIArAAQAEAAAAgDIAAh5QAAgjgSgPQgUgRgsAAQgrAAgcATQgCACACADIARAfQACACADgBQARgMAZAAQAWAAAIAGQAHAGAAAMIAAAHQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIghAAQgjAAgVAOgAkagrQgVAOgIAZQgHATAAAZQAAAXAHAWQAIAaAWAOQAVAOAgAAQAzAAAdggQADgDgDgCIgagYQgCgDgDADQgSAQgZAAQgfAAgIgYQgCgDgBgIQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIBxAAQAFAAAAgEQAAgmgGgTQgJgZgUgOQgWgOgfAAQgeAAgVAOgADcgxIAAAhQAAAEAFAAIALAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAABUQAAAhAOAPQAOAPAgAAIAUAAQAEAAABgEIAAgnQgBgDgEAAIgJAAQgJAAgDgEQgFgFAAgKIAAhSQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAYAAQAEAAABgEIAAghQgBgDgEAAIgYAAQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAgyQAAgEgDAAIguAAQgFAAAAAEIAAAyQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgLAAQgFAAAAADgABth9IAADKQAAAfANAPQAOAOAfAAIAVAAQADAAAAgEIAAgnQAAgDgDAAIgIAAQgRAAAAgSIAAjGQAAgEgEAAIgvAAQgDAAAAAEgAHggBQAIAIAAAQIAABsQAAADADAAIAvAAQAEAAAAgDIAAh3QAAgegRgTQgQgUgfAAQghAAgQAWIAAAAIAAhaQAAgEgEAAIguAAQgFAAAAAEIAAEAQAAADAFAAIAuAAQAEAAAAgDIAAhsQAAgQAIgIQAIgKAOAAQAOAAAHAKgAmpgBQAHAIAAAQIAABsQAAADAFAAIAuAAQAEAAAAgDIAAh3QAAgegRgTQgRgUgfAAQghAAgPAWIAAhaQAAgEgEAAIgvAAQgDAAAAAEIAAEAQAAADADAAIAvAAQAEAAAAgDIAAhsQAAgQAIgIQAHgKAOAAQAOAAAIAKg");
	this.shape_3.setTransform(-21.95,31.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAbAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_4.setTransform(-24.5,39.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeASQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAgGADgIQAHgUAXAAQAYAAAIAUQACAIAAAGQAAABgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-45.05,31.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AJdAwIAcgBQABAJANAAQAPABAAgNIAAgIQgIAFgMAAQgRAAgLgMQgKgLAAgSQAAgSAKgLQALgMARAAQANAAAIAHIAAgFIAaAAIAABRQAAARgLALQgLAKgTAAQgmAAgFgggAJ4AAQAAASAPAAQAHgBAEgEQAEgEAAgIIAAgCQAAgHgEgFQgFgEgGAAQgPAAAAARgALLAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgALbAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAILAeQgLgLAAgTQAAgSALgLQAMgMASAAQASAAAKAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgKAHQgLAHgOAAQgTAAgMgLgAI0gIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgAFOAZQgRgQAAgaQAAgaARgRQAQgQAbAAQAbAAARAQQARARAAAaQAAAagRAQQgRAQgbAAQgbAAgQgQgAFjgpQgIAJAAAPQAAAPAIAJQAIAIAOAAQAOAAAIgIQAJgJAAgPQAAgPgJgJQgIgIgOgBQgOABgIAIgACHAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgACXAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAAJAeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgPAAQgTAAgLgLgAAygIQgBgMgLAAQgKAAgBAMIAXAAIAAAAgAiVASQAAgWAigCIAJAAIAAgEQAAgIgGAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAh6AQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAlOAfQgNgKAAgTIAegBQAAAGAFAEQAFAFAHAAQANgBAAgIQAAgHgTgFQgTgFgIgGQgLgHAAgQQAAgQAKgJQALgMAUAAQAUAAAMALQAMAJABASIgeABQAAgNgOAAQgMAAAAAKQAAAEAEACQADADAMADQATAEAIAHQALAJAAANQAAASgMAKQgMAIgTAAQgVAAgNgKgAoUANIAAgdIgOAAIAAgXIAOAAIABgZIAbAAIAAAZIARAAIAAAXIgRAAIAAAWQAAALALAAIAGgBIAAAYIgNABQggAAAAgcgAqjASQAAgWAigCIAKAAIAAgEQAAgIgHAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAqIAQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAr0AeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgOAAQgTAAgMgLgArLgIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgANWAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAhOIAaAAIAAAFQAGgHAOAAQAOAAAIAIQAJAJAAAPIAAAwgAHGAnIAAhOIAbAAIAAAGQAHgHAOAAIAAAbQgJAAgGAFQgFAEAAAGIAAAlgADlAnIAAg3IgOAAIAAgXIAOAAIAAgFQAAgQAKgKQAKgJAQAAIAJAAIAAAZIgGgBQgFAAgDADQgDADAAAEIAAAGIARAAIAAAXIgRAAIAAA3gAg7AnIAAhOIAbAAIAAAGQAGgHAPAAIAAAbQgKAAgFAFQgFAEAAAGIAAAlgAjAAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAGgGAMAAQAOAAAIAIQAJAJAAAPIAAAwgAmnAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAHgGALAAQAOAAAIAIQAJAJAAAPIAAAwgApJAnIAAh1IAcAAIAAB1gAstAnIAAgsIgmAAIAAAsIgeAAIAAhwIAeAAIAAAqIAmAAIAAgqIAeAAIAABwg");
	this.shape_6.setTransform(0.175,134.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HS_logowhite, new cjs.Rectangle(-88.7,0,177.5,143), null);


(lib.HEAD2type = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNANQgFgFAAgIQAAgIAFgFQAFgEAIAAQAIAAAGAEQAFAFAAAIQAAAIgFAFQgGAFgIABQgIgBgFgFg");
	this.shape.setTransform(47.35,41.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAUAxIgUg1IgTA1IgZAAIgbhKIgCgFIgDgBIgFAAIAAgRIA0AAIAAARIgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAAAAAABQgBACABADIACAJIAGAPIAFAPIAGgPIAGgPIACgJQABgDgBgCQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgFAAIAAgRIAyAAIAAARIgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAAAAAABQgBACABADIADAJIAGAPIAGAPIAFgPIAGgPIACgJQABgEgBgBQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgFAAIAAgRIAmAAIAAARIgEAAIgEABQgBABgBAEIgbBKg");
	this.shape_1.setTransform(36.6,38.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgcAtQgLgGgHgMQgGgMAAgPQAAgPAGgLQAHgMAMgGQAMgHAQAAQAQAAAMAHQALAGAHAMQAGALABAPQgBAPgGAMQgHAMgMAGQgMAGgQABQgQgBgMgGgAgOgZQgFAIAAAQIAAADQAAAQAFAIQAEAHAKAAQALAAAEgHQAGgIAAgQIAAgDQAAgQgGgIQgEgHgLAAQgKAAgEAHg");
	this.shape_2.setTransform(22.6,38.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAGAyIAAgRIAGAAIACgBQABgBAAgEIAAgmQABgJgEgEQgDgEgHAAQgHAAgFAGQgEAHAAANIAAAdQAAAEAAABIADABIAGAAIAAARIg1AAIAAgRIAHAAIACgBQABgBAAgEIAAgxIgBgFQAAgBAAAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgHAAIAAgRIATAAIAOgBIAKgCIAAASQAFgJAIgFQAHgEALAAQAQAAAIAJQAJAKAAATIAAAmQgBAEABABIADABIAHAAIAAARg");
	this.shape_3.setTransform(10.9,38.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgLA5QgIgIAAgRIAAgxIgMAAIAAgQIAGgBQAGgBAEgDQADgCACgHIACgQIAVAAIAAAcIASAAIAAASIgTAAIAAAxQAAAHADADQADADAGAAIAFgBIADgBIAAATIgIACIgLAAQgQAAgIgHg");
	this.shape_4.setTransform(-3.625,36.875);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgaBGIAAgRIAHAAIADgBIABgGIAAgvIgBgHQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAIgGAAIAAgSIAUAAIANAAIAKgCIAABLIAAAGIAEABIAGAAIAAARgAgNgnQgEgFgBgIQABgHAEgFQAFgFAIAAQAJAAAEAFQAFAFABAHQgBAIgFAFQgEAFgJAAQgIAAgFgFg");
	this.shape_5.setTransform(-9.9,36.05);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgYAxIgRgFIAAgaIAXAAIAAAQIAHABIAIAAQAHAAAEgCQAEgDABgGQgBgGgFgCQgGgDgJgBQgIgCgIgDQgIgDgFgFQgFgGAAgKQAAgQAMgJQALgIAUgBQAMABAKACQAKACAGADIAAAZIgWAAIAAgOIgGgCIgIAAQgGAAgEACQgFADAAAFQAAAEADACQADADAFABIAJACQAJABAIAEQAHADAGAFQAFAGAAALQAAAPgMAJQgLAJgVABQgMgBgLgCg");
	this.shape_6.setTransform(-17.475,38.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgaBGIAAgRIAHAAIADgBIABgGIAAgvIgBgHQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAAAAAIgHAAIAAgSIAUAAIANAAIAKgCIAABLIAAAGIADABIAHAAIAAARgAgMgnQgGgFAAgIQAAgHAGgFQAEgFAIAAQAIAAAGAFQAFAFAAAHQAAAIgFAFQgGAFgIAAQgIAAgEgFg");
	this.shape_7.setTransform(-25.15,36.05);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgLAxIghhKIgDgFIgDgBIgGAAIAAgRIA4AAIAAARIgHAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBACACADIAEALIAGAPIAGAQIAHgSIAHgPIAEgJQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBAAAAAAIgIAAIAAgRIAtAAIAAARIgGAAIgEABIgDAFIghBKg");
	this.shape_8.setTransform(-33.925,38.225);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AglA+QgKgGgFgMQgGgLAAgQQABgPAFgLQAFgMAKgGQAKgHANABQALgBAHAFQAIAEAEAJIAAgZIgBgGIgDgBIgIAAIAAgSIAVAAIAOgBIAKgBIAABuQAAAFABABIACABIAHAAIAAARIgoAAIAAgHIgBgKQgEAJgIAGQgHAFgNAAQgNAAgKgHgAgSgGQgFAHAAAOIAAAEQAAAPAFAHQAGAIAJAAQAIAAAFgIQAFgHABgPIAAgEQgBgOgFgHQgFgHgIAAIgBAAQgJAAgFAHg");
	this.shape_9.setTransform(-50.575,36.45);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgaBDIAAgRIAIAAIACgBQABgBAAgEIAAhUIgBgFIgCgBIgIAAIAAgSIAUAAIAOgBIAJgCIAABvQAAAEABABIADABIAGAAIAAARg");
	this.shape_10.setTransform(-59.8,36.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgaBGIAAgRIAHAAIADgBIABgGIAAgvIgBgHQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAIgGAAIAAgSIAUAAIANAAIAKgCIAABLIAAAGIAEABIAGAAIAAARgAgMgnQgFgFgBgIQABgHAFgFQAEgFAIAAQAJAAAFAFQAEAFABAHQgBAIgEAFQgFAFgJAAQgIAAgEgFg");
	this.shape_11.setTransform(-65.8,36.05);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAGBDIAAgRIAHAAIACgBQABgBAAgEIAAgmQAAgJgDgEQgEgEgGABQgIgBgFAHQgEAFAAAPIAAAcQAAAEABABIACABIAHAAIAAARIg1AAIAAgRIAHAAIACgBQABgBAAgEIAAhUIAAgFIgDgBIgIAAIAAgSIAUAAIAOgBIAKgCIAAA0QAFgJAIgDQAHgFALAAQAQAAAIAJQAIAKAAARIAAAoQAAAEABABIACABIAIAAIAAARg");
	this.shape_12.setTransform(-74.9,36.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgjAmQgOgOAAgYQAAgXAOgOQAPgNAZgBQAWAAALAJQAMAJAAAQQAAAKgGAGQgFAFgJAAQgJAAgEgEQgFgEABgGQgBgHAEgEQADgEAHgBQgCgEgEgBQgFgCgHAAQgLAAgGAIQgHAHABAQIAAADQAAAPAFAIQAHAIAKAAQAJAAAHgFQAFgEAEgIIARAJQgEAMgLAIQgLAHgSABQgagBgOgNg");
	this.shape_13.setTransform(-86.05,38.175);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgaALIAAgVIA1AAIAAAVg");
	this.shape_14.setTransform(-94.45,38.15);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgZBDIAAgRIAHAAIADgBQAAgBAAgEIAAhUIAAgFIgDgBIgIAAIAAgSIAUAAIAOgBIAKgCIAABvQAAAEABABIACABIAGAAIAAARg");
	this.shape_15.setTransform(-100.6,36.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgaBDIAAgRIAIAAIACgBQABgBAAgEIAAhUIgBgFIgCgBIgIAAIAAgSIAUAAIAOgBIAJgCIAABvQAAAEABABIADABIAGAAIAAARg");
	this.shape_16.setTransform(-106.6,36.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgZAtQgMgHgGgLQgHgMABgPQAAgPAGgLQAGgMAMgGQAMgHAOAAQAZABANANQALAOABAZIAAAEIhDAAQABAMAGAHQAHAHAKAAQAKAAAGgFQAGgEADgIIARAKQgDAIgGAGQgGAGgKADQgJADgMABQgRgBgMgGgAASgIQAAgOgDgFQgEgGgJAAQgIAAgFAGQgEAGgBANIAiAAIAAAAg");
	this.shape_17.setTransform(-114.95,38.175);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAUAxIgUg1IgTA1IgZAAIgbhKIgCgFIgEgBIgEAAIAAgRIA0AAIAAARIgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAAAAAABQgBACABADIACAJIAGAPIAFAPIAGgPIAGgPIADgJQAAgDAAgCQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgFAAIAAgRIAyAAIAAARIgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAAAAAABQgBACABADIADAJIAGAPIAGAPIAFgPIAGgPIADgJQAAgEgBgBQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAgBAAIgEAAIAAgRIAmAAIAAARIgEAAIgEABQgBABgBAEIgbBKg");
	this.shape_18.setTransform(-128.65,38.225);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgtAsQgHgHgBgLQAAgNAJgIQAJgGAOgEQAOgEARgCIAAgGQAAgIgEgEQgFgEgIAAIgFAAIgFABIABAEIABAFQAAAHgEAEQgGAEgHABQgIAAgFgFQgFgEAAgIQABgJAFgGQAHgGAKgDQALgDAPAAQAXAAALAIQAKAIAAASIAAAqIABAFQAAAAAAAAQABABAAAAQAAAAABAAQAAAAAAAAIAHAAIAAASIgkAAIgEgHIgDgJQgCAFgFAEQgFAFgGACQgHACgIABQgOgBgIgHgAgMAHQgJAEAAAJQAAAGADADQADADAGAAQAJAAAFgGQAFgHAAgKIAAgIQgOACgIAEg");
	this.shape_19.setTransform(-40.45,16.775);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgZAtQgMgHgGgLQgHgMAAgPQABgPAGgLQAGgMAMgGQAMgHAOAAQAZABAMANQANAOAAAZIAAAEIhDAAQABAMAHAHQAFAHAMAAQAJAAAGgFQAGgEADgIIAQAKQgCAIgHAGQgFAGgJADQgKADgNABQgQgBgMgGgAASgIQAAgOgDgFQgFgGgIAAQgIAAgEAGQgFAGgBANIAiAAIAAAAg");
	this.shape_20.setTransform(-56.3,16.775);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgZBEIAAgSIAGAAIAEgBQABgBAAgEIAAhUIgBgFIgEgBIgHAAIAAgSIAVAAIAMgBIALgBIAABuQAAAEABABIACABIAGAAIAAASg");
	this.shape_21.setTransform(-64.7,14.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgoApQgIgJAAgTIAAgnQAAgEgBgBIgCgBIgIAAIAAgRIAtAAIAAA9QAAAKACAEQAEADAHAAQAHAAAFgGQAEgGAAgNIAAgeQAAgEgBgBIgDgBIgIAAIAAgRIAtAAIAABIIAAAFQABABAAAAQAAAAABAAQAAABABAAQAAAAAAAAIAIAAIAAARIgUAAIgOABIgKABIAAgQQgFAIgIAFQgHAEgLAAQgQAAgIgJg");
	this.shape_22.setTransform(-73.7,16.925);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AglA/QgKgHgFgLQgGgNAAgPQABgPAFgLQAFgLAKgHQAKgGANAAQALAAAHAEQAIAFAEAIIAAgZIgBgGIgDgBIgIAAIAAgSIAVAAIAOgBIAKgBIAABuQAAAFABAAIACABIAHAAIAAASIgoAAIAAgHIgBgLQgEAKgIAGQgHAEgNABQgNgBgKgFgAgSgGQgFAGAAAPIAAAEQAAAPAFAHQAGAIAJgBQAIABAFgIQAFgHABgPIAAgEQgBgPgFgGQgFgHgIAAIgBAAQgJAAgFAHg");
	this.shape_23.setTransform(-85.875,15.05);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgZAtQgMgHgGgLQgGgMgBgPQABgPAGgLQAGgMAMgGQAMgHAPAAQAYABAMANQAMAOAAAZIAAAEIhBAAQAAAMAHAHQAFAHAMAAQAJAAAGgFQAGgEADgIIAQAKQgCAIgHAGQgFAGgJADQgKADgNABQgQgBgMgGgAATgIQAAgOgFgFQgDgGgJAAQgIAAgFAGQgEAGgBANIAjAAIAAAAg");
	this.shape_24.setTransform(-97.45,16.775);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAGBEIAAgSIAHAAIACgBQABgBAAgEIAAgmQAAgIgDgFQgEgEgGABQgIgBgFAHQgEAFAAAPIAAAcQAAAEABABIACABIAHAAIAAASIg2AAIAAgSIAIAAIACgBQABgBAAgEIAAhUIgBgFIgCgBIgIAAIAAgSIAUAAIAOgBIAKgBIAAAzQAFgIAIgEQAHgFALAAQAQAAAIAJQAIAJAAATIAAAnQAAAEABABIACABIAHAAIAAASg");
	this.shape_25.setTransform(-108.9,14.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgiAmQgOgOgBgYQABgXAOgOQAOgNAYgBQAWAAAMAJQAMAJAAAQQAAAKgFAGQgGAFgJAAQgJAAgEgEQgEgEgBgGQABgHADgEQAEgEAGgBQgCgEgEgBQgFgCgGAAQgMAAgGAIQgGAHAAAQIAAADQAAAPAFAIQAHAIAKAAQAKAAAFgFQAGgEAEgIIARAJQgEAMgLAIQgKAHgUABQgYgBgOgNg");
	this.shape_26.setTransform(-120.05,16.775);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgdBCQgMgDgKgFIAAggIAaAAIAAAUIAMADIAMABQAIAAAGgEQAGgEgBgIQAAgGgDgEQgDgDgGgCIgRgFQgMgDgJgEQgKgFgFgHQgEgHgBgMQABgVAOgMQAOgLAaAAQANAAALACQALADAKAEIAAAgIgaAAIAAgTIgJgCIgKgBQgKAAgGAEQgFAEgBAIQABAGACADQADADAGACQAHADAJACQAMADAKAEQAJAEAGAHQAGAIAAANQAAANgGAKQgGAKgMAFQgNAGgRAAQgOAAgNgDg");
	this.shape_27.setTransform(-131.15,15.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2type, new cjs.Rectangle(-139,0,278,50.8), null);


(lib.HEAD1dtype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgTAUQgIgHAAgNQAAgLAIgIQAHgHAMgBQANABAIAHQAHAIAAALQAAANgHAHQgIAIgNAAQgMAAgHgIg");
	this.shape.setTransform(-4.2,25.075);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgkBKQgPgEgLgFIAAgmIAjAAIAAAXIAKACIANABQAKAAAGgEQAHgEAAgIQAAgJgJgEQgIgEgOgDQgMgCgMgEQgMgFgHgIQgIgJAAgQQAAgXARgNQARgNAfAAQASAAAPAEQAPADAIAEIAAAmIghAAIAAgWIgJgCIgLgBQgKAAgHAEQgGAEAAAIQAAAGAEADQAEADAHACIAQAEQAMACAMAFQAMAEAHAIQAIAJAAARQAAAXgRAOQgRANggAAQgSAAgQgDg");
	this.shape_1.setTransform(-14.725,20.125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSBVQgLgLAAgbIAAhJIgSAAIAAgYIAJgBQAJgCAFgEQAGgFABgIIADgZIAhAAIAAAqIAbAAIAAAbIgcAAIAABJQAAAMAEAEQAFAEAIAAIAIgBIAFgBIAAAbQgFACgHABQgIABgIAAQgaABgMgMg");
	this.shape_2.setTransform(-27.025,18.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgpBEQgSgKgKgRQgKgSAAgXQAAgWAKgSQAKgRASgKQASgJAYAAQAYAAASAJQARAKAKARQAKASAAAWQAAAXgKASQgKARgSAKQgSAJgYAAQgYAAgRgJgAAXAmQAIgLgBgZIAAgDQABgagIgLQgHgLgQAAQgOAAgIALQgHALAAAaIAAADQAAAZAHALQAHAMAPgBQAQABAHgMg");
	this.shape_3.setTransform(-40.425,20.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAJBlIAAgaIAJAAQABAAAAAAQABAAABAAQAAgBAAAAQABAAAAgBQACgBAAgGIAAg5QAAgNgFgGQgFgHgLAAQgLAAgHAKQgHAJAAAVIAAArQAAAGABABQABABAAAAQABAAAAABQABAAAAAAQABAAABAAIAJAAIAAAaIhRAAIAAgaIALAAQAAAAABAAQABAAAAAAQABgBAAAAQABAAAAgBQACgBAAgGIAAh/QAAgFgCgDQAAAAAAgBQgBAAAAAAQgBAAgBgBQAAAAgBAAIgLAAIAAgaIAeAAIAVgBIAPgCIAABOQAHgNAMgHQALgGARAAQAYAAAMANQAMAOAAAcIAAA7QAAAGACABQAAABABAAQAAAAAAABQABAAABAAQAAAAABAAIAKAAIAAAag");
	this.shape_4.setTransform(-58.025,17.325);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgkBKQgPgEgLgFIAAgmIAjAAIAAAXIAKACIANABQAKAAAGgEQAHgEAAgIQAAgJgJgEQgIgEgOgDQgMgCgMgEQgMgFgHgIQgIgJAAgQQAAgXARgNQARgNAfAAQASAAAPAEQAPADAIAEIAAAmIghAAIAAgWIgJgCIgLgBQgKAAgHAEQgGAEAAAIQAAAGAEADQAEADAHACIAQAEQAMACAMAFQAMAEAHAIQAIAJAAARQAAAXgRAOQgRANggAAQgSAAgQgDg");
	this.shape_5.setTransform(-74.075,20.125);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag8A+QgMgNAAgdIAAg7QAAgFgBgCQgBgBAAAAQAAAAgBAAQgBgBAAAAQgBAAAAAAIgLAAIAAgaIBCAAIAABdQAAAOAFAGQAFAFAKAAQAMAAAGgJQAHgJAAgTIAAguQAAgFgCgCQAAgBgBAAQAAAAAAAAQgBgBgBAAQAAAAgBAAIgNAAIAAgaIBEAAIAABtQAAAGACACQAAAAAAABQABAAAAAAQABABAAAAQABAAABAAIALAAIAAAaIgeAAIgVABIgPADIAAgaQgHANgMAHQgLAGgRAAIgBAAQgXAAgMgNg");
	this.shape_6.setTransform(-97.275,20.3259);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgnBlIAAgaIALAAQAAAAABAAQABAAAAAAQABgBAAAAQAAAAABgBQABgBAAgGIAAh/QABgFgCgDQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAAAAAIgMAAIAAgaIAfAAIAUgBIAPgCIAACmQAAAGABABQABABAAAAQABAAAAABQAAAAABAAQABAAAAAAIAKAAIAAAag");
	this.shape_7.setTransform(-110.925,17.325);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhRBjIAAgaIANAAQAEABABgDQACgCAAgFIAAh+QAAgHgCgCQgBgBgEAAIgNAAIAAgaICjAAIAAA1IgcAAIgEgRQgDgHgEgCQgFgBgKAAIglAAIAABAIAYAAQAGAAACgCQACgDAAgFIAAgKIAZAAIAABCIgZAAIAAgJQAAgGgCgDQgCgCgGAAIgYAAIAAAuQAAAFABACQACADADgBIAOAAIAAAag");
	this.shape_8.setTransform(-124.425,17.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1dtype, new cjs.Rectangle(-135,-4,278,42.1), null);


(lib.HEAD1ctype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgUAUQgIgHAAgNQAAgLAIgIQAIgHAMgBQANABAIAHQAIAIgBALQABANgIAHQgIAIgNAAQgMAAgIgIg");
	this.shape.setTransform(86.65,25.075);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgnBDQgSgJgJgSQgJgRAAgXQAAgWAKgSQAJgRASgKQARgJAXAAQAkAAATAVQATAUAAAlIAAAHIhkAAQABATAJAKQAJAKARAAQAPAAAJgHQAIgHAFgLIAZAPQgFALgJAJQgIAJgOAFQgOAFgTAAQgaAAgSgKgAAcgNQgBgUgGgIQgGgJgNAAQgMAAgHAJQgHAJgBATIA1AAIAAAAg");
	this.shape_1.setTransform(75.025,20.125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAJBLIAAgaIAJAAQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBQACgBAAgGIAAg5QAAgOgEgGQgFgGgMAAQgLAAgGAKQgIAJAAAVIAAArQABAGABABQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIAJAAIAAAaIhQAAIAAgaIAKAAQABAAABAAQAAAAABAAQAAgBABAAQAAAAABgBQABgBAAgGIAAhKIgBgIQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAgBAAIgKAAIAAgaIAdAAIAVgBIAPgDIAAAbQAHgOAMgHQAMgGARAAQAYAAAMAOQALAOABAcIAAA6QgBAGACABQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIALAAIAAAag");
	this.shape_2.setTransform(57.9,19.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgoBpIAAgaIALAAQAAAAABgBQABAAAAAAQABAAAAAAQABgBAAAAIABgHIAAhIQABgHgCgDQgBgCgEAAIgKAAIAAgbIAeAAIAUgBIAPgCIAAByQAAAFABACQABAAAAABQAAAAABAAQAAAAABAAQABABAAAAIALAAIAAAagAgTg7QgIgIAAgLQAAgLAIgIQAHgHAMAAQANAAAHAHQAIAIAAALQAAALgIAIQgHAHgNAAQgMAAgHgHg");
	this.shape_3.setTransform(44.075,16.95);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag1A5QgVgUAAglQAAgkAWgUQAVgUAlAAQAhAAASANQARANABAYQAAAPgIAJQgIAIgPABQgMgBgHgGQgGgGgBgKQAAgJAGgHQAFgGAJgCQgDgFgGgCQgHgDgKAAQgRAAgJALQgKAMAAAXIAAAFQAAAXAJAMQAJALARAAQAOAAAJgGQAJgGAEgNIAbAOQgHASgQAMQgQALgdAAQgmAAgVgUg");
	this.shape_4.setTransform(31.825,20.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag1A5QgVgUAAglQAAgkAWgUQAVgUAlAAQAhAAASANQARANABAYQAAAPgIAJQgIAIgPABQgMgBgHgGQgGgGgBgKQAAgJAGgHQAFgGAJgCQgDgFgGgCQgHgDgKAAQgRAAgJALQgKAMAAAXIAAAFQAAAXAJAMQAJALARAAQAOAAAJgGQAJgGAEgNIAbAOQgHASgQAMQgQALgdAAQgmAAgVgUg");
	this.shape_5.setTransform(16.125,20.125);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhDBCQgMgKgBgSQABgTANgLQANgKAWgFQAVgGAZgEIAAgIQAAgNgGgGQgHgGgNAAIgIAAIgHABIADAHIABAHQAAALgIAGQgHAGgLAAQgMAAgHgGQgIgGAAgNQAAgOAJgIQAKgJAQgEQAQgEAVAAQAkgBAQAMQAQAMAAAbIAABAIABAHQAAAAABABQAAAAAAAAQABABABAAQAAAAABAAIAKAAIAAAaIg1AAIgHgKIgFgNQgDAHgHAHQgHAGgKAEQgLADgMAAQgUAAgMgLgAgTALQgNAGAAAOQAAAIAEAFQAGAEAIAAQAOAAAHgJQAIgKAAgQIAAgLQgVADgNAGg");
	this.shape_6.setTransform(-0.1,20.124);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgTBkIhBijQgBgFgDgDQgCgCgEAAIgMAAIAAgaIBfAAIAAAaIgLAAQgFAAgCACQgBACACAGIAnBmIAmhmQABgGgBgCQgCgCgEAAIgPAAIAAgaIBPAAIAAAaIgNAAQgFAAgDACQgCADgCAFIhBCjg");
	this.shape_7.setTransform(-19.625,17.525);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhjBjIAAgaIANAAQADABACgDQABgCAAgGIAAh9QAAgHgBgCQgCgBgDAAIgNAAIAAgaIBfAAQA1AAAaAZQAaAZgBAwQAAAxgaAZQgbAag2gBgAgcBJIAYAAQASAAALgHQAKgHAFgOQAEgPAAgXIAAgNQAAgXgEgOQgEgQgLgGQgKgIgSABIgZAAg");
	this.shape_8.setTransform(-48.6245,17.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgsBjIAAgaIANAAQADABABgDQACgCAAgGIAAh9QAAgHgCgCQgBgBgDAAIgNAAIAAgaIBZAAIAAAaIgMAAQgEAAgCABIgBAJIAAB9IABAIQACADAEgBIAMAAIAAAag");
	this.shape_9.setTransform(-64.1,17.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgTBkIhBijQgBgFgDgDQgCgCgEAAIgMAAIAAgaIBfAAIAAAaIgLAAQgFAAgCACQgBACACAGIAnBmIAmhmQABgGgBgCQgCgCgEAAIgPAAIAAgaIBPAAIAAAaIgNAAQgFAAgDACQgCADgCAFIhBCjg");
	this.shape_10.setTransform(-80.075,17.525);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag2BbQgXgNgMgXQgNgXAAggQAAgeANgXQANgYAYgNQAXgMAfgBQAfABAXAMQAXANAMAXQAMAYAAAeQAAAggNAXQgNAXgXANQgXANgfAAQggAAgWgNgAgjg4QgMAQAAAjIAAAMQAAAjAMAPQAMAQAXAAQAZAAAMgQQAMgPAAgjIAAgMQAAgjgMgQQgMgQgYAAQgXAAgNAQg");
	this.shape_11.setTransform(-102.125,17.475);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AguBcQgXgMgMgXQgMgXABgiQgBgeAMgXQAMgYAVgNQAVgMAbgBQAUAAAOAIQAOAIAHAQIAIgbIAdAAIAABMIgqAAQgDgZgLgLQgKgMgSAAQgXAAgMARQgLAQAAAhIAAAJQAAAiAMAQQAMAQAXAAQAVAAAMgLQANgLACgYIAlAFQgCAVgKAQQgJARgTAKQgTAKgdAAQgeAAgWgMg");
	this.shape_12.setTransform(-123.05,17.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1ctype, new cjs.Rectangle(-135,-4,278,42.1), null);


(lib.HEAD1btype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgUAUQgHgHgBgNQABgLAHgIQAIgHAMgBQANABAIAHQAIAIAAALQAAANgIAHQgIAIgNAAQgMAAgIgIg");
	this.shape.setTransform(27.8,25.075);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgkBKQgPgEgLgFIAAgmIAjAAIAAAXIAKACIANABQAKAAAGgEQAHgEAAgIQAAgJgJgEQgIgEgOgDQgMgCgMgEQgMgFgHgIQgIgJAAgQQAAgXARgNQARgNAfAAQASAAAPAEQAPADAIAEIAAAmIghAAIAAgWIgJgCIgLgBQgKAAgHAEQgGAEAAAIQAAAGAEADQAEADAHACIAQAEQAMACAMAFQAMAEAHAIQAIAJAAARQAAAXgRAOQgRANggAAQgSAAgQgDg");
	this.shape_1.setTransform(17.275,20.125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag4BwQgSgDgIgHQgIgGAAgJQAAgLAJgHQAKgHASgEQgPgDgIgJQgHgHAAgMQAAgMAHgHQAHgIANgEQgLgGgFgKQgGgKAAgNQAAgQAKgMQAJgLAQgGQAQgHAWAAQAMAAALADQALACAJAEQADgMAIgJQAHgHAMAAQAKAAAGAGQAGAGABAIQgBAKgEAEQgFAGgJAAQgFAAgEgCQgFgCgCgFIgDADIgDADQAHAGAEAJQADAIAAAKQAAARgJALQgJALgQAFQgQAGgVAAIgSAAIgPgEQgFABgCACQgCACAAADQAAAGAEACQAEACAKgBIAVAAIAXAAIAUAAQAZAAAMAMQALALAAAUQAAAagWANQgWAOgtAAQgeAAgSgDgAgwBHQgEAFAAAFQgBAJALACQALADAZABQAaAAANgFQAMgFAAgJQABgIgGgDQgFgCgOAAIg4AAQgJACgEAFgAgYhBQgGAGAAAOIAAAFQAAANAGAFQAGAHALAAQALAAAFgHQAGgGAAgNIAAgFQAAgOgFgGQgGgGgKAAIgCAAQgLAAgFAHg");
	this.shape_2.setTransform(1.9735,22);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAIBLIAAgaIAJAAQABAAABAAQABAAAAAAQABgBAAAAQAAAAABgBQABgBAAgGIAAg5QAAgOgEgGQgGgGgKAAQgMAAgGAKQgIAJABAVIAAArQgBAGACABQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIAJAAIAAAaIhQAAIAAgaIALAAQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBQACgBAAgGIAAhKIgBgIQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAAAAAIgLAAIAAgaIAdAAIAVgBIAPgDIAAAbQAHgOAMgHQALgGASAAQAYAAALAOQANAOAAAcIAAA6QAAAGABABQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIALAAIAAAag");
	this.shape_3.setTransform(-16.2,19.925);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgoBpIAAgaIALAAQABAAAAgBQABAAAAAAQABAAAAAAQABgBAAAAIABgHIAAhIQABgHgCgDQgBgCgEAAIgKAAIAAgbIAeAAIAUgBIAPgCIAAByQAAAFABACQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAIALAAIAAAagAgTg7QgIgIAAgLQAAgLAIgIQAHgHAMAAQANAAAHAHQAIAIAAALQAAALgIAIQgHAHgNAAQgMAAgHgHg");
	this.shape_4.setTransform(-30.025,16.95);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAIBLIAAgaIAJAAQABAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBQACgBAAgGIAAg5QAAgOgFgGQgEgGgMAAQgLAAgHAKQgGAJgBAVIAAArQAAAGACABQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIAJAAIAAAaIhQAAIAAgaIAKAAQABAAABAAQAAAAABAAQAAgBABAAQAAAAABgBQABgBAAgGIAAhKIgBgIQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAgBAAIgKAAIAAgaIAdAAIAVgBIAPgDIAAAbQAHgOANgHQAKgGASAAQAYAAAMAOQAMAOgBAcIAAA6QABAGABABQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIALAAIAAAag");
	this.shape_5.setTransform(-43.6,19.925);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgnBDQgSgJgJgSQgJgRAAgXQAAgWAKgSQAJgRASgKQARgJAXAAQAkAAATAVQATAUAAAlIAAAHIhkAAQABATAJAKQAJAKARAAQAPAAAJgHQAIgHAFgLIAZAPQgFALgJAJQgIAJgOAFQgOAFgTAAQgaAAgSgKgAAcgNQgBgUgGgIQgGgJgNAAQgMAAgHAJQgHAJgBATIA1AAIAAAAg");
	this.shape_6.setTransform(-60.925,20.125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgnBDQgSgJgJgSQgJgRAAgXQAAgWAKgSQAJgRASgKQARgJAXAAQAkAAATAVQATAUAAAlIAAAHIhkAAQABATAJAKQAJAKARAAQAPAAAJgHQAIgHAFgLIAZAPQgFALgJAJQgIAJgOAFQgOAFgTAAQgaAAgSgKgAAcgNQgBgUgGgIQgGgJgNAAQgMAAgHAJQgHAJgBATIA1AAIAAAAg");
	this.shape_7.setTransform(-77.025,20.125);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhFBLIAAgaIAKAAQABAAABAAQAAAAABAAQAAgBABAAQAAAAABgBQABgBAAgGIAAhKQAAgGgBgCQgBAAAAgBQAAAAgBAAQAAAAgBgBQgBAAgBAAIgLAAIAAgaIAeAAIAVgBIAPgDIAAAgQAEgRAKgIQAKgHAOAAQASAAAJALQAKAKAAATQAAAQgIAJQgJAJgOAAQgKAAgGgFQgHgGAAgKQAAgGAEgGQADgFAGgDIgEgCIgFgBQgMAAgHAMQgFALgBAVIAAAoQAAAGACABQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAIAMAAIAAAag");
	this.shape_8.setTransform(-92.375,19.925);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag1A5QgVgUAAglQAAgkAWgUQAVgUAlAAQAhAAASANQARANABAYQAAAPgIAJQgIAIgPABQgMgBgHgGQgGgGgBgKQAAgJAGgHQAFgGAJgCQgDgFgGgCQgHgDgKAAQgRAAgJALQgKAMAAAXIAAAFQAAAXAJAMQAJALARAAQAOAAAJgGQAJgGAEgNIAbAOQgHASgQAMQgQALgdAAQgmAAgVgUg");
	this.shape_9.setTransform(-107.575,20.125);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgrBjQgTgEgPgHIAAgxIAoAAIAAAfQAHADAJABQAJABAKAAQANAAAIgGQAJgGAAgMQAAgJgFgFQgFgFgKgDIgZgHQgSgFgOgHQgNgHgIgKQgHgMgBgSQABgfAVgRQAVgRAngBQAUAAARAEQAQAEAOAGIAAAxIgnAAIAAgeIgNgCIgPgBQgPAAgJAGQgIAGgBAMQAAAIAFAFQAEAFAKADQAKADAOAEQARAEAPAGQAOAGAJALQAJAMABATQAAAUgKAPQgJAPgSAJQgSAIgbAAQgWAAgSgFg");
	this.shape_10.setTransform(-124.225,17.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1btype, new cjs.Rectangle(-135,-4,278,42.1), null);


(lib.HEAD1atype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgTAUQgIgHAAgNQAAgLAIgIQAHgHAMgBQANABAIAHQAHAIABALQgBANgHAHQgIAIgNAAQgMAAgHgIg");
	this.shape.setTransform(81.3,25.075);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgkBKQgPgEgLgFIAAgmIAjAAIAAAXIAKACIANABQAKAAAGgEQAHgEAAgIQAAgJgJgEQgIgEgOgDQgMgCgMgEQgMgFgHgIQgIgJAAgQQAAgXARgNQARgNAfAAQASAAAPAEQAPADAIAEIAAAmIghAAIAAgWIgJgCIgLgBQgKAAgHAEQgGAEAAAIQAAAGAEADQAEADAHACIAQAEQAMACAMAFQAMAEAHAIQAIAJAAARQAAAXgRAOQgRANggAAQgSAAgQgDg");
	this.shape_1.setTransform(70.775,20.125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAIBLIAAgaIAJAAQABAAABAAQABAAAAAAQABgBAAAAQAAAAABgBQABgBAAgGIAAg5QAAgOgFgGQgFgGgKAAQgMAAgGAKQgIAJABAVIAAArQgBAGACABQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIAJAAIAAAaIhQAAIAAgaIALAAQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBQACgBAAgGIAAhKIgBgIQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAAAAAIgLAAIAAgaIAdAAIAVgBIAPgDIAAAbQAHgOANgHQAKgGASAAQAXAAAMAOQAMAOAAAcIAAA6QAAAGACABQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIALAAIAAAag");
	this.shape_2.setTransform(54.8,19.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgpBEQgSgKgKgRQgKgSAAgXQAAgWAKgSQAKgRASgKQASgJAYAAQAYAAASAJQARAKAKARQAKASAAAWQAAAXgKASQgKARgSAKQgSAJgYAAQgYAAgRgJgAAXAmQAIgLgBgZIAAgDQABgagIgLQgHgLgQAAQgOAAgIALQgHALAAAaIAAADQAAAZAHALQAHAMAPgBQAQABAHgMg");
	this.shape_3.setTransform(36.975,20.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgoBpIAAgaIALAAQABAAAAgBQABAAAAAAQABAAAAAAQABgBAAAAIABgHIAAhIQABgHgCgDQgBgCgEAAIgKAAIAAgbIAeAAIAUgBIAPgCIAAByQAAAFABACQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAIALAAIAAAagAgTg7QgIgIAAgLQAAgLAIgIQAHgHAMAAQANAAAHAHQAIAIAAALQAAALgIAIQgHAHgNAAQgMAAgHgHg");
	this.shape_4.setTransform(23.975,16.95);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgSBVQgLgLAAgbIAAhJIgSAAIAAgYIAJgBQAJgCAFgEQAGgFABgIIADgZIAhAAIAAAqIAbAAIAAAbIgcAAIAABJQAAAMAEAEQAFAEAIAAIAIgBIAFgBIAAAbQgFACgHABQgIABgIAAQgaABgMgMg");
	this.shape_5.setTransform(14.075,18.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhEBCQgLgKgBgSQABgTANgLQANgKAVgFQAXgGAZgEIAAgIQgBgNgGgGQgHgGgMAAIgJAAIgHABIADAHIAAAHQAAALgGAGQgIAGgLAAQgMAAgIgGQgGgGAAgNQAAgOAJgIQAIgJAQgEQARgEAVAAQAkgBAQAMQAQAMAAAbIAABAIABAHQAAAAABABQAAAAAAAAQABABABAAQAAAAABAAIALAAIAAAaIg2AAIgHgKIgEgNQgEAHgHAHQgHAGgKAEQgKADgNAAQgUAAgNgLgAgSALQgOAGgBAOQABAIAFAFQAEAEAJAAQAOAAAHgJQAIgKABgQIAAgLQgWADgMAGg");
	this.shape_6.setTransform(0.95,20.124);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhEBJIAAgXIBRhjIgbAAQgJAAgFADQgEACgBAHIgEAQIgaAAIABgzICCAAIAAAXIhRBjIAfAAQAJAAAFgDQAEgCACgHIADgRIAbAAIgBA0g");
	this.shape_7.setTransform(-15.2,20.125);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgoBpIAAgaIALAAQAAAAABgBQABAAAAAAQABAAAAAAQABgBAAAAIABgHIAAhIQABgHgCgDQgBgCgEAAIgKAAIAAgbIAeAAIAUgBIAPgCIAAByQAAAFABACQABAAAAABQABAAAAAAQAAAAABAAQABABAAAAIALAAIAAAagAgTg7QgIgIAAgLQAAgLAIgIQAHgHAMAAQANAAAHAHQAIAIAAALQAAALgIAIQgHAHgNAAQgMAAgHgHg");
	this.shape_8.setTransform(-27.125,16.95);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAIBLIAAgaIAJAAQABAAABAAQAAAAABAAQABgBAAAAQAAAAABgBQABgBAAgGIAAg5QAAgOgFgGQgFgGgKAAQgMAAgHAKQgGAJAAAVIAAArQAAAGABABQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIAJAAIAAAaIhQAAIAAgaIALAAQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBQACgBAAgGIAAhKIgBgIQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAAAAAIgLAAIAAgaIAdAAIAVgBIAPgDIAAAbQAHgOANgHQAKgGASAAQAXAAAMAOQAMAOAAAcIAAA6QAAAGACABQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIALAAIAAAag");
	this.shape_9.setTransform(-40.7,19.925);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag8A+QgMgNAAgdIAAg7QAAgFgBgCQgBgBAAAAQAAAAgBAAQAAgBgBAAQgBAAAAAAIgLAAIAAgaIBCAAIAABdQAAAOAFAGQAFAFAKAAQAMAAAGgJQAHgJAAgTIAAguQAAgFgCgCQAAgBgBAAQAAAAAAAAQgBgBgBAAQAAAAgBAAIgNAAIAAgaIBEAAIAABtQAAAGACACQAAAAAAABQABAAAAAAQABABAAAAQABAAABAAIALAAIAAAaIgeAAIgVABIgPADIAAgaQgHANgMAHQgLAGgRAAIgBAAQgXAAgMgNg");
	this.shape_10.setTransform(-59.175,20.3259);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AA3BLIAAgaIAIAAQAAAAABAAQAAAAABAAQAAgBABAAQAAAAABgBQABgBAAgGIAAg2QAAgOgFgHQgEgHgLAAQgMAAgGAJQgFAJAAASIAAAuQAAAGABABQABABAAAAQAAAAABABQAAAAABAAQABAAAAAAIAKAAIAAAaIhNAAIAAgaIAIAAQAAAAABAAQABAAAAAAQAAgBABAAQAAAAABgBQABgBAAgGIAAg4QAAgNgFgHQgFgGgKAAQgMAAgGAJQgFAJAAASIAAAuQAAAGABABQABABAAAAQAAAAABABQAAAAABAAQABAAAAAAIAJAAIAAAaIhQAAIAAgaIALAAQAAAAABAAQABAAAAAAQABgBAAAAQAAAAABgBQABgBAAgGIAAhKQAAgGgBgCQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAAAAAIgLAAIAAgaIAdAAIAVgBIAPgDIAAAcQAHgOALgHQALgHARAAQASAAAKAHQAKAIAEAQQAGgPAMgIQAMgIATAAQAYAAAMAOQANANAAAfIAAA4QAAAGABABQABABAAAAQAAAAABABQAAAAABAAQABAAAAAAIALAAIAAAag");
	this.shape_11.setTransform(-81.775,19.925);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AA3BLIAAgaIAIAAQAAAAABAAQAAAAABAAQABgBAAAAQAAAAABgBQABgBAAgGIAAg2QAAgOgFgHQgEgHgLAAQgMAAgGAJQgFAJAAASIAAAuQAAAGABABQABABAAAAQAAAAABABQAAAAABAAQAAAAABAAIAKAAIAAAaIhNAAIAAgaIAIAAQAAAAABAAQAAAAABAAQAAgBABAAQAAAAABgBQABgBAAgGIAAg4QAAgNgFgHQgFgGgKAAQgMAAgGAJQgFAJAAASIAAAuQAAAGABABQABABAAAAQAAAAABABQABAAAAAAQABAAAAAAIAJAAIAAAaIhQAAIAAgaIALAAQAAAAABAAQABAAAAAAQABgBAAAAQAAAAABgBQABgBAAgGIAAhKIgBgIQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgLAAIAAgaIAdAAIAVgBIAPgDIAAAcQAHgOALgHQALgHARAAQASAAAKAHQAKAIAEAQQAGgPAMgIQAMgIATAAQAYAAAMAOQANANAAAfIAAA4QAAAGABABQABABAAAAQAAAAABABQAAAAABAAQABAAAAAAIALAAIAAAag");
	this.shape_12.setTransform(-109.125,19.925);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgsBjIAAgaIAMAAQAEABACgDQABgCAAgGIAAh9QAAgHgBgCQgCgBgEAAIgMAAIAAgaIBZAAIAAAaIgNAAQgDAAgBABIgBAJIAAB9IABAIQABADADgBIANAAIAAAag");
	this.shape_13.setTransform(-127.95,17.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1atype, new cjs.Rectangle(-135,-4,278,42.1), null);


(lib.CO_v_white = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgyA1QgXgVAAggQAAgeAWgVQAVgWAeAAQAfAAAWAXQAVAVgBAdQAAAfgVAVQgVAVgfABQgdgBgVgUgAgvgvQgTAUAAAbQAAAcATAUQAUATAbAAQAcAAATgTQATgTABgdQAAgbgTgTQgUgUgcAAQgbAAgUATgAASAuQgCgDgCgKIgCgPQgCgIgFgEQgEgCgJAAIgGAAIAAAqIgRAAIAAhcIAfAAQAPAAAFACQAPAFAAARQAAAQgTAGQAGABADAEQADAEABAJQAEAVADAHgAgOgIIAOAAQATAAAAgNQAAgIgHgDQgDgBgMAAIgLAAg");
	this.shape.setTransform(133.8251,86.6356,0.4949,0.4949);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACmLBQgKgEgNACQgPADgIAAQAAgDgKgCIgOgBQgRABgHgCQAAgDgSACQgjgBAAgBIgUgCIgTgBQgLgCgHAAQAAgBgQABQgRABAAgDIgOgEQgJgDAAAHQgDAAgFgDQgEgDgDAAQAAAFgJgBIgNgDQgNgCgLACQgRACgYgKIgJgEQgEgCgEABQgCAAgIgEQgIgFAAgBIgMABIgMABQgIACgFgBQgDAAgDgEQgEgFgDAAIAAAEQgEAAgEgCQgGgDAAgEQgCAGgBAAQAAgDgIgDQgIgCgFAAIgBABQgBAAAAAAQAAgBAAABQgBAAAAAAQAAAAAAAAQgDABgFgEQgEgDgEABQgEABAAgDIgIgGQgHgFAAAEQgCABgMgFQgNgGAAgCIgTgJQgBABAAAAQgBABAAAAQAAABAAAAQAAAAABAAIgEABIAAAAIgEAAIAEAAQABADgQgGQgCgDgFAAQAAgGgDgCIAAAGIgFgDQgGgDAAADIgIgIIgOgCQAAgCgNgGQgNgGAAgCQgKgEgDgKQgBgDgJgBIgOgCQgTgKgBABQgEgCgCABIABgDQgCAAgQgKQgLgIgDgIIgLgDQgCgCgBgDQgBgBgFAAIgDgHIgCgHQgEgBgCACQgCACgCAAQgBgLgTAAQgPAAAAgBIgNgBIgMgBQgSAFgHgCQAAgBgYgBQgaAAgDgBQAAACgJgCIgNgDQgLAFgDgEQgNgEgCABQAAABgGAAIgHgBIgJgCQgDgCgFAAIgOABQAAABgOgEQgGAAgFgHQgCgBgNABIgMAAQgEABgcgDQgcgDAAgBIgJgDQgGgCgDAAIgXgDQgDgEgbgGQgagHAAgBQgCAAgEgCQgDgDgDABQgOACAAgEQgJgEgPAAQAAgFgKgBQgNgBgBgBQgLgFgFgDQgHgGgQgDIgYgEQgDgDgDABIgHACIgGgDIgHgCQAAgEgJgBQgJgBgCgFIAJgCQgBgEgMgEQgMgFAAACIgSgJQgFAAgIgGIgLgHIgMgEIgNgBIAVAVQAAADAHAGQAHAGABAEQADACAGAHQAGAGAEABQAKADAEAHQADAAAHADIAKAFIAHAEQAHAEAAACQAFAAAHADQAGADAEAAIAEACQABAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAFABAGAGQACAFAWAEQAVAEAAADIAYAKQADAAAGADQAFAEAEAAQACgBATAGIATAFQADAAAIAEQAGAEAEgBQAEgBAJAEQAKAEADAAQAAgBARAEIAVAFQAEAAAJACIANAEQAAABAOACIAQABQAAAFBNAGQADADAjADQAiAEAAABQBPAIAAgBQADgBAkAEQAiAEAAgBQAIgBAAABQgGAAgMAGQgOAGgFABIgMgCQgLgCAAADIgGABQgDABgDgBQAAAGgUABQgTABAAgDQgQACAAgCIgGACQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgLgBQgDgBgDgGQgDAAgCADQgBABgGAAIgNgBQgXgCgDgCIgFgFIgJABIgMgEQgKgDAAADQgGAAgKgCQgCgGgEABIgJAFQgFADgFgCQAAgCgLgCQgKgCgEABQAAACgWgEIgbgFQAAgCgOgBQgPgBgBgEQgHAAgLgDQgMgDgGgBQgCgCgNgBQgNgBAAgCQgGAAgJgCIgOgEIgNgEQgNgEAAgBIgNgCQgKgCAAgBQgFAAgGgCIgLgFIgDgBIgCgBQgLAAAQALQACACAGACQAGACADADIAKADQAAABAFABIAHABQAAACASADQAAADAaAEQAZAFABAHIgKACQAAgDgXgDQgZgDgCgDIgagHQgVgHAAgDIgZgIQgUgIAAgBQgIgCgKgEQgNgGgFgGIgIgFQgJgEAAABQgCAAgHgFQgIgFAAgCQgKAAgPgHQgRgJgCgJQgPgKgGAAIgIgIQgFgFgDgCIgGgIIgJgFQgGgCAAgDQgGgEgHgIQgHgJgDgGQgDgBgEgHQgFgHAAgCQgDAAgDgJQgDgKgEAAQAAgEgDgGQgEgFAAgFQgBAAgFgTIgGgYIgHgkQgHgjAFAAIgFgVQgBAAgBgLIgBgNQgDAAAAgNQgBgOgCAAIgJhUIAAggQAAgcACAAIgCgjQgBggAEAAIgCgxQgCgsAFgDQAAgEAKgaQALgZgBgEQAIAAAHgOQAHgPAGgCQACgBADgFQACgGADgCQAAgFAGgGQAHgGAHgBIgDgEQAAAAAAgBQAAAAAAgBQAAAAABgBQABAAABAAIAEgCQAAAAAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAHgHIAKgHIAFAAIAEgCQALgIgHAAQgCgGAFgEQAFgFAFAAIAIgDIAIgCQAKgFAKgJIAQgRQAGgGADgBIAFgDIACgEQACAAAOgLQAAgCANgFQANgGAAgEQAEAAAJgGQAJgHABgDIAOgJQAHgEAIAAQAAgBAGgDIAFgCIAJABQAGACABgDIAXgEQAOgEAAgJQADgBACgEIADgEQABgCAEgDQAEgCABgDIgBAAQAAgFAHACIAJACIARgCIAIgFIAKgEIAJgFQAHgEACAAIAEgCQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBQAFAAAFgCQAHgCAAgDQgHAAAHgHQAHgGAEgBIANgHQAFAAAGgDQAAgDAHgCQAGgCAAgEQAGAAAAADQADAAAEgCIAHgCIAKACQAGABACgDIAOgGQAJgGAEAAQAAgBALgEQAKgDAEAAQAAgCAHAAQAHAAAAgBQAJAAACgCQACgBAAgHIAFgDIAEgEIAJACIgBAFIAEgCIADgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAfAAAHgDQAEgBAGACIAKACQALgGgFAAQgCgJASgGQATgGAAAFQAMgIAZAAQACgDAJAAQAJABACgEIAXgEQAUgEAAgBIABABIAVgFQAWgFADAAQAVAAAAgEIAIgCQAHgBAAgBIAggHIAvgHQAOAAAggFQAggGAQAAQAAgFBQAAQAAABAGACQAHACAAACQgIAFgXgCIgQABIgRABQgJAAgRADQgSADgJAAQAAgChXATQAAAFArgFIAxgGIAugGIAbgDQARgCAJACQAUgDABAKQASAAAAABIAHABQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAABIgIAAQAAADg1ACQAAABgRADIgUACIgTAAQgSAAAAADIgwAHIgSACIgUACQAAADgMACIgQACQgIgBgPAEQgQAFgHAAIgMACQgMACAAACQgEAAgGAEQgHAEgDAAIgJAAIgJgBQAAADgQACQgPADgBADQgCAKgMADQgOABgIACQAAADgTAHQgHAKgHAEQACAIAiABQAfABAHgEQADgCAagEQAXgDAAgCIAMgCIAMgDQAAgBAGABIAHABQARgEAJAAQAAgBAcgDIAcgFQAfgDAAgBIAVgCIAWgCQAAgCAmgCQAngDAFABIApgDQAkgDAAACQAMgCAYACIAcgBQASgBALACQAAADAJACQAJACAAgCIAQABQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQADgBAKACQALADAAACQgEACgWABIgVAAIgmABQgCADgWAFQgVAFAAACIgQgBQgPgBAAACIgWAAQAAAFgZABIgegBQAAADglABQglACgBAIQARADAXgDIAngGQAAACAkgCQAjgBAAABQAFAAALgDQAEAAAEACQAFADAEAAIAQgBQAJABgEAGQgFAIghACIghACQhWAFAAADIgTACQgTACAAgCQgGgBgJADQgLADgDAAIgRACQgCACgGAAIgKgBQgGABgJAGQgIAGgGABQAAAFgdAEQAAABgHACQgIADAAABIgTADIgKACQgLACgBACQgRAAgMAMQgGABgKAFQgKAGgGABQAAgBgNAFIgPAFQAAgCgFABQgEAAgCACIAEABQgBADgMACIAAgEIgOAFQAKAIgUAEQgWAEAAACIgTAGQgNAFgGABQAAgCgvAQIgRAGQgRAGgCADQgTAAgDAEQgFAAgHAFQgGAEgFgBQgGAAgFAFQgGAGgFAAQgCgDgFACIgIAEIgKAFQgFACgFABQgBABgLADIgNACQAAAFgJACIgOADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABgBAAQgCADgEAAQgEAAgCADQgDAEgDACIgDADQgBABgEAAQgBgCgGgBQgFgCAAAEQgFAAgBAFQgDAHgCABQAAADgJAAQgOAJgCAAQAAACgMACQgLADAAAEIgMAGQgIAFAAADQgFABgFAEQgGAEgEABIgGADQgEACgCAAQgRAJgCAAQgEAEgFAAIgQAMQAAADgIAFQgIAEAAADQgGAEgOACQgBAEgEACQgFACgBABQgFAAgEAIQgEAHgDABQgEABgIAHQgIAFgDAAQAAAFgHAEQgIADgBAFQgSALgLANQgEAAgGAGIgIAKQgGAIgFADQgBADgFACQgFACAAAEQgCAAgHAJQgGAIgDAAIABADQgFAAgFAHIgHAKIgIAIIgHAJQgDAHgLANQgJALgBAJQADAAAGgHQAIgJACgBQAGgKAEAAQAAgDAHgFQAGgFABgCQgCAAAKgJIALgJQAGAAAEgJQAEgJADAAIAGgGQAGgFACAAQACgEAHgEIALgHQAAgCAEgFIAHgFIAVgPQADgHAUgGQABgDAJgEQAIgEAAgCQgBgEAGgCIAIgDIAWgOQAEAAAFgFQAGgEADAAIAhgUQAGgCARgIQATgJAAgDQAHgBACgDQAEAAABgDQACgDACAAQAHgCABgCIAIgEQAFgDAAgBIAGgDIAFgDQAAADAMgFQALgFACgDIAHgCQAFgCAAgBQAHgBAOgJQANgIAIAAQADgEAJgCQAIgCADgDQAEAAAGgEQAFgEAEAAQAFgFAIAAIAIgIIAHAAIAGgBIASgHQAAgBAGgCIAHgBQADgEAKgBIALgCQABgCAHgDQAIgEAAgCIAQgDQAAgCALgDQAJgCAEAAQAAgGANgBQANgBACgCIApgMQAhgJAAgFQAEAAASgFQARgGAAgBQAFAAAJgCQAKgCAAgEQAygGAAgEQALAAAQgFQATgHAHgBQAAgBAYgFIAbgFQAAgBAdgGIAhgHQAIgCANgBQAAgBAFgBIAHgBIATgEQAMgDAHABQAAAIgWAFIgeAFQgQAEAAACQgDAAgHAFQgHAFgFgBQAAAAgBgBQAAAAAAAAQAAAAgBAAQgBAAAAAAQAAACgZAIIgHAFQgEADgEAAQgDAEgGABIgMABIgbAJQgQAFgMACIgEADQgEADAAACQgEAAAFAEQAFADAAgEIAMgBQAKgBAAgCQAfAAgQAFIgHAEIgGAGQgCABgHgCQgEgBgCAGQgJgBgIAEQgKAEgIAAQgFAAgHAEQgGAEgEAAQAAAEAGAAIAGgCIAHgCQAAANgmACQgBADgGABQgDACgEgBQgEAAgDABQgBACgPAFQgFAGgSAAQgLABgBAGQgEgBgFACQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgEgCgBABQAAABgFAEIgIAEQgOAFAAACQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIABACIgGACQgEACgCgBQgBAGgKABIgOgBQAHAFgHADQgFACgGAAQAAgBgIAEIgIAEQgDAGgPAAQAAgDgGACIgEADQgBgDgEAFIgEAIIgGgCQgBAAgBAAQgBAAgBAAQAAAAgBABQAAAAAAABQgFACgIAAQgEAAgMACQgNADAAADQgDAAgEAEQgFAEgDAAIgbAKQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgDADQgEAAgDACQgDACgCAAQAAADgEABQgEACgDAAQgFgBgDAEQgEAFgDAAIgHAEIgFADQAAAGgKACIgOABQAAABgFADIgHADQgDABgHAIQgFAHgGgBQgHgCgJAJQgRAEgBADIgFACQgCABAAAEIgJgBQABABAAAAQABAAgBABQAAAAAAAAQgBABgBAAIgEAAQgBAAgBAAQAAAAAAABQgBAAAAABQAAABABABQAAAGgKAAQgCgCgGADIgJAEQgRAHgIAKQgJABgIAEIgPAJQAAAEgMAGQgMAHgCAFIgJAEQgGACAAAEIgMAFIgGACQgDABgCADIgCADIgEACQgJAHAAACQgDAAgCADQgDAEgCAAQgHABgFAEIgNAPQgHAIgJADQAAAGgOAJQgOAKAAAHQgEACAOALQAPANgBADQgFAAgGAKQgFAKgBAGQgDAAAPANQAPAMAAgEQAGAAAIAHQAIAHABAGQAAAEAKACQAKACACACIAMAJQAGAAALAGQALAFAGAAQAAAHArAAQAMAMAIAAQAAABAIAAQAJABABABIALAAQAGABAFADIAOAJQANAGAFgCIAKgCIALgCQAEADACAAQgCAEADACQACABANgBQAMAAACAEIATABIAIABIAJABQAAgCAPADIASADQADgEAGAAIALAAQABACAHAAQAHAAADADIAEAKQAEAIADgBIACAAIABgCIABgNQABgFAFAAIAKAAIAPACIARAAQAAgCAKADIAMAEQAAgFAKgCQAKgBAAAGIAugFIgBgCQADgCgDgPQgEgPABAAIgEgNQgFgMABAAQABgCgBgFQgBgFgCAAIgBgUQgBgFACgMQABgOACAAIAAgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBABAAQAFAAAAgZQACAAACgIIADgJQAAgFADgGQADgHABgFIAIgfIAIgQQAFgKAAgGQAEgCACgGQADgIADgCQAHgGgBgHQAMgMgBAAIAEgGQADgCACgEQgCgFAEgBQAAgCAFgGQAGgFAAgDQACgBAFgGQAFgHACAAQAAgDAFgDIAIgGQACAAAEgEQADgEAAgCQANgGAPgPIAFgCQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIgRANQgFACgFAIQgFAHgBAFQAGgBADgDIAGgIQAPgGAAgBQAIgCANgKQALgJAKAAIAIgBQADAAADgDQABgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQAAgDAEgBQAAgDAJgHQAIgHAFgCQADgBAFgEIAIABQACgCAFAAQABAAABAAQABgBAAAAQABAAAAgBQAAAAAAgBIAIgGQAHgGAAADQAGACAAgLQAGgBAFgEQACgCAJgCQAAgDACgDQADgDACAAQAAgCAMgGIANgHIACgFQABgCAEgBIAGgCIAGgFIAFgBIAFgCQAEgEAHgDQAIgDADgDQAFgEADACIAEADQADAHgOAHIgSAIQAAACgSAJIgMAJQgIAFgCAFQgEABgIAGQgIAGgGABQAAAIgLACIgMAJQgGAFgCAFQgIACgHAIQgCAAgDADQgDACgEAAQgGABgCAHQgIAEgCAJQgEACgEAFIgIAIIgPAMQgKAHAAAHQgNAGACANIgDAEIgCAGQgFACgBAJQgCAAgEAFIgFAFQgJAKAAgEQgDABgBAHQAAAGgIAAQAAABgEAEIgFAEIgBALIgGAJQgEAGgBAEIgMAKIgEAMIgGAEQgBACABAFQgBAAgEAHIgDAJQgDABgFAIIgHAHQAAATgIADQgGACABAJIAAANQgEAAgBAZQgBAZABAAQABgJAIgNQAKgOABgHQADAAAFgIQAEgGAAgDIALgUQACgBAFgIQAEgHAEAAQAEgPALgCQgCgKAMgGIANgPQABgEAJgIQAIgHAAgFQAFgCAGgIQAFgJAFgCQAAgDALgJQAJgIAFgDQAAgDALgHQAKgGAAgCQAGgEANgNIAPgNQAEAAADgFQADgFAEAAQACgEAHgGQAHgFAEgBQABgDAFgEQAHgEABgCQAIAAALgMQAMgMAGAAIAKgHQAIgFAAgCQADgBABgDQAAAAAAgBQABAAAAAAQABgBABAAQAAAAABAAQAIAAgCgGIAGAAQAAgCARgIQAQgJAEgBQAAgEATgKQARgJAGAAQADgGAJgFQAIgEAHgCQAAgBAJgEQAJgEACAAQACgCAUgJQATgIAAgBIAEgEQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAQABAAABAAIAGgBQAAgCAIgDIAIgCQADgDAIAEQACgJAFAAQAGgGAIAAQAAgCAHgCIAKgDQAFgHAZgGQABgCAGgBQAFgCACgCIAGgCIAHgCQAAgCAGgBQAGgBAAgBIAEADIAdgQQAAgBAMgDQALgCAAgCQAXgGAAgCIAJAAQAHAAADgEQADAAAPgJQABAAABAGQAAgIAVgEIAMgEQAJgDABAAQAQAKgEgHIgCgDQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAugJQACgEAXgEQAWgEAAgBIAIgDQAEgCADAAQAAgDARgBQATgCABgCQADAAADgDQADgDADAAQAAgCALAAQAngIADABQAAgCAvgIQAHABANgDIAVgGQAYgFAGAAQA9gJAGAAQAJgBAVgEQATgEAMAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAKAFQAIADAAgGIAUgCQA+gHAAACQADABAZgFIAigBQAfAAAAgCIBjgBQAAgCAoADQAsAEAEAAIAKAAQADAEAEgCIAIgCQACAHgDgBQgBAAgBAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgFAEgNAAQAAAAAAgBQAAAAgBAAQgBAAAAAAQgBAAgBAAIgFACQgEAAgDgCQgDgCgCAAQgNAHAAgEQgQACgIgCQAAgCgMABQgMACAAABQgLAAgKABQgCAFgGgCIgKgDQAAADgLAAQgKgHgCACIgDADIgFABQgDADgGABQgDAAAAAHQgMAAgCAIQgCAIAMAAQACADAKABQAKABADACQAAgFAHADIAKADQAAgEANACQAIABgDACIgFADQgCACgJAAQgIAAgEgCQAAABgHABQgGABgBAFQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgCADQgKAAgIACQgKADgHAAIgqADQgCAEgLAAIgRAAIgtACQAAABgfAEQggADgFgBQAAAGgzgBQAAABgIADIgJACQgYAAAAADQgFgBgOADIgiACQAAABgVAEIgYADQAAgDgKAHQgLAGAAACIAhAAIAbgEIATACQADAAAFgCQAEgCAFAAIAOgDQANgCAAACQAFABAHgFIAOABQAAAFALgHQAKgBARgDQAAgCAJAAQAGgBAFABQAGACAGgBQAGgCAFACQAAgDARgDQARgEAAAFQArAFAAgDIAJABQAGABAAADQgNAHgDgBQgFgBgKABQgLABAAADQAkgDBBACQANAAAaAEQAYADANAAQAlAAA5AKQArAFAAAFQAFAAAXAFQAZAFAAADIAIAAQAEAAABgEQAJgDAFAAQAFAAAFACQAAABAIACQAIACAAACQATAAAZAOQAPASgBAAQAAAGASAAIgLgKQgIgHAJAAQAGAAAJAFQAJAFAFAAQAqAWAEAAQAAABAPAEQAOADAAADQADAAAHAEQAIADADAAQAAABAoAOIAZAOQASALAAAHQAEAEAFACQAAACAJAIQAKAIAAADQAHAMACAAQAAADAEAGQAEAGAAAEQABAAACAHIACAJQAEAAAFATQAFATADAAIAJAUQAFAMAAAKQACAAAFAbQACAAAGAXIANAyIAHAaQAHAXgDAAQACAGADApQABADgCAFIgCAIQgCAAAAAGIAAAJQgCAAgDAIIgDAJQgDABgFAPIgFAPQgBADgDAAIgDAAIgBAGQgBAAAAAAQgBABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgIAAIAAAEQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgEACgBAGQgCAAgDAGQgDADgCgFQgHABgFAFQgEAAgCAIQgCAIgCABQAAAHgGADQgGADgGgCQABANgJgDQgMgEgCAEIAAAMQgCABgDADIgCADIgEACQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAGQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQgJgCAAABIgKAEQgEAAgCADQgCAAAAAFQgBAFACAAQgBAKgNABQAAgDgIgBIgLgCIgGADQgGACAAADQAAADgMACQgEABgKAFQgKAFAAADQgCAAgNAHQgNAHAAACQgFACgDAHQgCAFgHgCQAAACgDAEQABAAACAEQACADAAACQgGACgLgDQgLgDgFABIABAKQAAAGgFAAQgCgDgEACQgBABAAAAQAAABAAABQgBAAABABQAAAAABAAQADACABADQgEACgFAAIgJAAQgCAAgHgFQgHgEgFAFIgDAGQgBACgEABIgHAEIgFADQgBAFgJAAIgPgBQAAAHgJADQgLADgCADIgDADQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAgBgBQgCgDgDAAQgEgBAAAEQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAIAAAGIgMABQgDAAgGAFQgEADgDgHQgDgBgDAFQgDAEAAAEQgFAAgFADQgFADAAAEIgGgBIgHABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAADQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgEAAIgPADQgFAGgHACIgPACQAAAAgBAAQAAABAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAADABAGQAAAEgNgEIgHAFQgHAEAAADIgJgBQgEABgCAGIgJADQgHABgCgEQgGADgHAFIgMAIQAAAGgRgDQgSgDAAAIIgFgCQgBgBgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBAAgDAFQgDAEgCgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgGAHQgDAFgFgBIgEAAIgFACQAAAAgBABQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgFAFIgJAEQgHADABABIAYAAQAOgBAIgDQADgBAcgFQAYgFAAgDQADgBAFAGQAEAGAEgCIARgFQACgFAZgDQAAgBALgDIALgEIALgCQAJgBgBgDQARgHABAHIAPgGQAKgDAHABQgSALgFABIgpAUQABgGgKACQgIABgEAEIAEADQgEAAgUAIQgUAIAAACIgJABQgIACAAADQgFABgFgBIgJgDQgBAKgHgBQgMgBgCABQAAABgIABQgJAAABAEQgRAJgKABQgWADAAACIgIABQgGgBAAgBQgDgBgEABIgHACQgWAMAAgIQgDAAgEACQgFABgBADQgDgBgIADIgGADQAAABgVAEQgGAAgFAEQgGAEAKABQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIADABQAAgDARAAQAQgBAAgCQAIAAAWgHIAdgEIAkgGIAVgEQATgEAAABQAIAAAMgEIASgHQgBgBAOgFIAQgEIAVgIQAPgHAEAFIgUAKIgRAHQgGABgLAGQgMAFgEABQABADgKACIgNACQgKAGgLACQAAgCgMAIQgCAFgDgFIgDgDQgEABgFADQgFAEgDAAIgKADQgJABAAADQgFAAgGACQgGACgGAAQAAAJgLgMQgCAGgBAAQgDgFgJACIgLADQgFAGgBADQgFAAgEgDQgFgDgEgBQAAAFgGAEIgLAEQgXALgNgLQgMAEgDAAQAAAHgPAAQAAACgMADQgLADgEgBQAAgEgIAAIgMAAQgCAHgBAAIgHgBQAAACgVgBQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAADgJAAQAAgGgEAIIgDAEIgIAEQAAgEgHABIgIACQgCABgQAAQgOAAgBADIgYAAQgFAAgHgDIgMgDQgHAHgIAAIgRgDQAAABgKADQgKACAAABIgPACQgMACgEgEQAAgBgNAAIgRgBQAAAFgHgBIgKgCQAAADgPABIgFAAQgKAAAAgDgACUKCQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAdgDQAZgCABAEQABAAAAAAQABAAAAgBQAAAAABgBQAAAAABgBQACgDADAAIAEAAIADgBQAEgBAGABQAHAAADgBIAOgFQAJgCAHAEQABgGAEADIAFAFQADAAAFgFQADgGAEABIAHACQADAAAFgDQACgBAFAAIAHgCQAFgBABABIABAFQAEAAAEgGIAJgDIASgFIALgBQAHgBAEgDQALgFADAAQgFgBgPAEIgTAGIgfADQgPACgVgBIgWAEQgSACgBgEQgNACgBABQgKADgJgCQgKgDgNACIg1ADQgFABgCgFIgKADQgBgDgFgBQgIgBgCgCQgLAEgEgBQgMgDgagBIgagBQgFAAgJgCIgOgBIgMAAIgKgCIgBACQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgDgCgCABQgBgDgFgBIgHAAQgKgDgYgBIgOgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABIgDABQgLABgIgDIgFgDQgCgCgDABIgNAAQAAgCgFAAIgHAAQgDgBgEAAIgIAAQgEAAgDgCIgGgEIgPgDQgJgBgEgEQgFgEgBAAQgCACgEAAIgKgCQgGgBgEABQgBgEgMgDQgIgCgGAAQgDABgDgDQgCgCgDABQgDAAgGgBIgKgEQACABgSgIQgQgHAEgBQgCgBgHAAQgGABgDgCQgIgEADgCIgQgFQgDgBgPADQgRADgOgBIApAdQARgBALAEIANAFQAIgBAMAGIAMAFQAKAEAAACIAHgCQADgBACADIAGAHQACgBAIgBQAJgBABADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIASAGQADACAFAAIAIABIASAFQAEACAFABIAJABQAQAEAjAEQA8ALA6AFIAbACQARABALACIAhABQADgBALACIAQABIAMgBQAIgBAEACQABAAAAAAQAAAAABAAQAAAAABgBQABAAAAAAIABgBQABAAAAAAQAAABABAAQAAAAAAAAQAAABABAAgAGCH/IgCgHQAAgDAHAAQABABAHgBQAHgBABgCIAPADQALACAAgEQAGgHAHAFIAMAHQAGAAAAgDQgBgEADgCIAHgCQACAAACAEQAIgIAQgBQAJAAAQABQAAgBAFgCIAGgDIARAAQAAgCAPAAQACAGAEAAQAAgGAIgBQAHgCAAACIAJgCIAJgCQAAAAABgBQAAAAABAAQAAgBABAAQABAAABAAQADAAACgDQALgFAIADQACAAATgEIAGACQAAAAABAAQAAgBABAAQAAAAAAgBQABgBAAgBQAAgBAAgBQABgBAAAAQAAAAABAAQABgBAAABQAFACABgBQAAgCAPgDIARgDQABgCAOgFQANgFAEAAQADABAEgEQAEgDADAAQAAgDAQAAQAGABALgHQAGAAALgFQALgGAGAAQACgDANgEQANgFAFAAQABgCAMgEQALgDAAgBIAVgIQADAAAEgCQAEgDAEAAIAKgEIAHgDQAEgCAEgBQABgDAGgBQAGgCACgCQAEAAAIgDQAJgEACgCQAEAAAHgEQAHgEADgEQAFAAAJgFQAIgFAGAAIAYgMQAAgBAVgIQAWgJACgDQAFAAAJgFQAIgGAGAAQAFAAAGgGQAHgHADAAQAEAAAGgGQAHgGADAAQAHAAAKgIQAEgCAHgHQAAgBAGgCQAGgCAAgCQgHAAAGgCQAFgCADAAQAAgEAJgBQAHgBADABQAAgDADgEQADgFAAgFIAQAAQAAgEAEgCIAIgFIANgIQAAgFAMgGQALgGAAgCQAMgCADgDQAGgEADgJQAFgBAQgbQAMgGAGgKIACgEQABgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAQADAAAFgJQAFgKAFAAQADgFAAgJQAFgDgBgEQABAAACgMQACgNACAAQAAgBgCgFIgEgGQAAAHgLAAIgFAGQgEAGACAAQAAADgHAGQgIAFAAACIgFAGIgGAIQgDAAgFAFIgIAFIgFADQgFADABAEIgJADIgHADIADAAIgBAEQADAAgMAKQgDADgIAAQgHABgCACQAFAAgFAHQgFAGgEAAQgJAMgOADQgEAIgOAFIgCACQgBAAgBAAQAAABgBAAQAAABAAAAQAAABAAAAIgKABQgCABAAAHQgbAFAAAGQgPALAAABIgJADQgGACgEAAQAAADgFACQgEACgEAAQgEgGgEAHQgEAHgCABQAAACgKAGIgMAGQgEABgIAGQgJAGAAAEQAAACgMAEIgQACQAAAEgJACQgJABABAEQAAABgaAFQAAAHgOAGQgLAFgKABQAAgFgOAHIgOAGQgDAAgJAEQgIAEAAABQgEAAgHADQgHADgEAAQAAACgJAEQgIADgCgBIgBADIgBADQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgDABgCgCQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAFIgDAAIgCgBQAAADgFABQgGABAAABQgEACgCgBQgDAAgDACQgDADgMAAIgIAGQAAABgKADIgNADQgNAGgDAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAAAABIgYAKQgYAGgGAEQAAADgXAAIgHAEQgEABgBAFQgFACgEgBIAAAFIgPAAQAAAGgGABQgHACAAgCQgDAAgLAFQgJAEgFgBQAAgBgGACIgHACQgDADgIAAIgMgBQgCAEgLAAIgbAJQAAABgFACIgJADQgFADgKAAQgDgDgDACIgFAEIgKgDQAAAHgNABIgTABIgIABQgFACgBADIgMgBQgcALgDgBIgUACQgSADAAACIgPADIgOACIgHACQgFACAAABQgIAAgQACQgVAEgDAEQACgCATAAQAAAEAZAAQADgEALABIAQACQAAgEANACIAOABQACAAADADQADACADAAIAAAAgAn2HeQgCAEgDAAIANAKQAJAGAEAAIADgDQABAAAAgBQAAgBAAAAQgBgBAAAAQgBgBgBAAQgBgDgGgFIgKgFIgDgCIgCACgAAUGwQACAEACAAIAIACQAFABACgEIADgBQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAgBAHgBQAHgCAAgBQAigBAAgFIAGABQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAFgBANADIAJgDQAGgDADAEQACADAFgBQAFAAACgDQACgCAFACIAIACIgEgEIADgGIAKgCQAGAHAAgFIASABQAFgCAHgHQACgBAKABQAJABADgDQAEgEAHAAIALABQACgFALABIAOABQAAgDAHABIAJADQAAABAKgHQAKgBAOACQAAgIAPgBQAAgBAVgEQAVgFADABQABADAMAAQAMAAACgEIACgFQAEgEADAFQACABAEAAIAGAAQAAgIABgCQACgBAIABQABAEAHgDIALgDQAEgBAKAEIAIgEQAAgFANgDIARgCQAHgDAEgGQADgCAHABIALABIgBgFQAEAAABgCQACgDADgBQADgBADABIAHACQAAgCAPgCIASgBIgCgEIADgBQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAJgBAHgEQAJgHAFgCQAXAAADgFQANAAABgCQAGAAgDgGIAKgBIAEgGQABgBAAgBQABgBAAAAQABAAAAAAQAAAAAAAAQADABADgCQADgCADABQAAACAHAAQAHAAAAgCQAHAAAEgDIAJgIQAHgBAEAAQACgEAEABQAGACACAAQAAgBASgGIAUgIQgDgDABgCQACgCAFAAQADADAFgCIAIgDQAAgBAHgBQAHgBAAgDIAGACQAIgFgEAAQgBgDAPgEQAQgEAAgCQAHAAAHgDIAOgIQABgCAIABQAHABAAgEIADgDQABgCAFAAQAEAAAHgDQAAgBAKgDQAKgCADABQgBgFAFgDQAGgEACgDQAPABAAgDIAHABQAEAAABgEIAKgIQAAgDAIgEQAHgFAEAAIALAAQAAABATgLQAAgDAHgFIAIgFQAGAAAIgHQAIgIAFAAQAAADASgNQAIgGAKAAQAUgNAAgCIAWgPQALAAAMgIQADgHAEAAQADgDAJgDQAJgEACgDQAFAAADgGQADgHADAAIAKgHQABgDAEgEIAHgGIAGgCQAFgBABgCQAAgFANgGQAMgHgBgDQAVgZADgBIAHgPQAFgKgHgDQAAgCgHgEQgIgDgBgDQAAgDgEgCIgHgFQgMgLgGgDIgQgHQgNgHAAgDQgGAAgJgFQgKgGgEgBQAAgBgJgFIgKgHQgEgBgIgFQgHgFgEAAQAAgBgSgEQgUgHgDgDIgQgIIgKABQgHABgEgBIgFgCIgHgBQgRgLgDAAQAAABgSgHIgJgDQgDgEgGgCIgKgBQgtgKgGgBQgGgHgWADQgSACgDgEQgDgEgHAAQAAgBgOACQgPACAAgDIgTgBQAAgEgGgBQgHgHgIAEIgNAFQgHAAgKgEIgRgGQAAAFgXgBQgWgBAAgJQABgEgFgBQgEgBgFABQgCADgIgCQgBgBgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAADgJgBQADAHAAAEQAHAAACAeQACAcgCAIQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABABQAAAAAAAAQgBABAAAAIgBAUQgBATgEAAQgBADADADIgIAQIgGANQgFAIAAAGIgGAPQgFAOgHAAIABAFQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIAAAEQgCAAgCAGQgBAGgDAAIAAAEQAAABgBAAQAAAAAAABQAAAAgBABQgBAAAAABIgFAEIgBAHQgDAAgBAFQgBAAgGAIQgHAJgFABQgBADgIADQgIACABAFIgCAFIgCADQAAACgEAEIgGAFQAEAKgSACQgBAGgHAEQgIAGgCADQgFAIgTAJQgCABgDAEIgFAFQgJAAgRAOQgUARgFACIgNAFQgJAEAAAEIgLAHQgGAFgGABQAAgBgFAFQgFAEABAAIgKAFIgKAGQAAABgLADQgMADAAAEQgJAAgRANQgSAMgMAAIgKADQgIAEgBABIgJAHQgFAFgFAAQgeAKgEAAQAAACgJAGQgJAFAAgEQgEAAgHADQgHAEgDADIgLACQgFABgEAFQgFAAgKAGQgJAGgEAAQgDAFgVAAQgCADgDACQgEABgBACIgGABQgEABgCgCIgGgDQgHgBgGADIgKAIQgBAFgNAEQgDAAgIAFQgHAEgEAAQgsANgHAAQAAADgZAHQgaAIgDADQgTACghANQgHADgOAAQAAAGgPAAQAAACgVAGQABgGgiAKQgEAAgGACIgKAEQAAgBgMAEIgPAFQgIAGgMACIgWAFIAFAAIABABIARACQAOACABgDQAcAAASAEQAsgBAAAFQAFABAvgHQAHgDAHAEIANAHQAAgCAQgCIAUgCIAQgBQAEABACADgAqtGZQgHgMAAgBIAHAFIAGAEQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIADgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgGAAIgCgBIgBAAIAAgBQgDgDgDgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgDgBQgjAFAAgEIgJgBIgIgCQAAgEgOACIgQADQgGAJATADQAWADAAABIAVABQARAAAAACIASAAIAAAAgAopGGQgDABAAAFIADAEIAEAFIAHgBQALAAgJgLQgFgEgEAAgAmTFsIAIAOIAFAFIAOACQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAIAOgCQAJgCAEABIBCgLQAAgCAVgDIAYgEQBOgSAHAAQAAgBAXgGQAXgFAEAAQAAgDAWgEQAWgDACgEQAHAAAKgEQALgDAGgBQAGAAALgEIAQgFQACgDAdgHQAagGgBgHQAYgBAAgDQAJgBARgHQAAgBAJgCQAJgCAAgBQADAAADgCQABgBAAAAQABgBAAAAQABAAAAgBQAAAAAAgBIAGgBIAFABQAAgDAQgFQAOgEAFAAQACgDAJgDQAKgCAAgDQAEAAAIgDQAJgDACgDQAGAAALgEQAJgEAFgEQAGgFAPgDQABgCANgEQANgEAAgCIANgGIAOgHIAPgFQAKgEADgEQACAAAJgFQAIgEAAgBQAEAAAIgEQAIgFADgDQAKAAAOgKQAOgKAIgBQACgEAUgJQATgKgBgCQAAgBANgHQAOgHAAgBIAHgGQADgDAFgBQAKACAEgGIAEgIQAEgIAFAAQAAgBAFgEQAGgDAAgCQAFgBAIgHQAIgHAFgBQADAAACgFQACgFADgBIAIgFIALgKQAEgCAFgHQAFgHAEgCQAAgFAOgMIAOgRQACgEAFgIQAGgIACAAQABgGAFgHIAGgMQACAAACgFIACgGIACgHQACgGgBgDQgFAAgJAOQgKAQgEACQAAAGgMAJIgLAKQgGAHgEACQAAAFgHAFIgKAKQgBACgIAFQgHAEAAAEQgDABgDAEQgDAEgFABIgEAFQgEADgCAAIgHADIgIADQAAACgEADQgFAEgBADIgKAGQgHAGgBACQgDAAgJAGQgJAGgCADQgKADgQANQgPAMgMACQgFAGgMAEQgLAEgIAAIgOAOQgFAAgHAGQgHAFgDAAQgCAEgIABQgHABgDADIgHADIgGADQgCAAgEAEIgFADQgCAEgJAAQgJABgDAEQgEACgDAAQgCAEgIABIgNABIgJABQgGAAgDABQgDABgDAHQgDAGgEABQgEAEgFgCQgHgCgDABQAAAEgFACQAAAEgVAJIgbALQgDAAgFADQgFADgDAAQAAACgNACQgEAEgIADQgHACgGAAQAAACgNADQgNADAAADIgNACQgKACgCADQgGAAgCABQgDABgFAFQgHAAgGACIgNADIgWAHQgBACgKACQgKACAAACIgbAHQgFAAgIADQgIADgFAAQgCACgOAEQgNADAAABQgDAAgFADQgFADgDAAQgBACgGABQgFABgCgCQgRAHgCAAQgDADgNADIgMACQgEABgKAEQgIADgEAAQAAACgOAAIgQgCQAAABgJADIgMACQgPAAgMAFQAAAFgLACQgMABAAABIgXAAQgQAAgFAFIgDACIgDADIgJADIgHACQgCADgcAEQgcAFAAACIgFAAIgFAAgAxuEwQAAgCgHgCQgFgCgEAAQAAAGAQAAgAzoD+IgCADIAOALIAKACIALACQAEAHAcAKQAbAKAAgGQgOAAAAgHQgQgCAAgCIgUgKQgCAAgEgIQgEgHgGAAQAAgDgKgBIgKgBIAAAAIgGACgAmhD9QgJAEgBADQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAIADAAQAAACAsgFIA0gGQAAgDAWgEIAcgFQABgDANAAIARAAQAFAAARgGQANgEAIACQAAgCATgDIAWgEQAAgFALACQAMACAAgEIAKAAQAGAAADgEIAJgDQAFgGAQACQAQABACgFQgIAAAHgEQAGgEAEAAIANgBIAEACIAFABIASgEQAAgCgFABIgHABQgDgGAcgHQAXgHAKAAQAAgBALgCQALgBABgCIAHgCIAHAAIADADIAFABQAAgBAAgBQgBgBABAAQAAgBAAAAQABAAABAAQgCgFAEgBIAJgCIAKAGQAKAGADgBIgHgDIgDgKIAGgFQADgBAFACQACABAMgFQALgFAAAEQADABAEgCQAEgCAAgCQAOAAADgFQAAgJAJAAQACgEAKAAIANAAQAFgBADgEQADgEADAAIAVAAIAEgJQADgDAEABIAGADQgBgJAGABIALADQADAAAEgDQAEgEADAAQACgCAJgFQALgFABACQAAgHAUgCQAUgCAAgCQAIAAAFgBIAFgDIAGgDQACgDALgDQAMgDAAAGQAEABAOgEQAGgEABgFQgEAAAEgHIAFgIQAEgCAAgJIANgHQAJgFAGAAQABACAKACIAMACQAAAEAMgGQALgFACgEQgHAAgCgMQAFAAAMgPQASgEAAgCQAMgCAOgGIAWgKQAFgFARgHQAOgGADgHQAGgCANgOQALgMAHAAQACgDAFgDQAFgEACgDQACgCAHgGQAHgFAAgEQACAAAFgIQAFgHAAgCQAEAAAJgXQAKgXgCgFQgCAAAAgMQABgMgEgCIADAAQgBAAgDgHIgHgRIgSgBQAAACgPgEQgPgDAAADQgmAHAAgBQgLABAAgCIgIABQgFABgDgDIgHABIgJABQAAgBAAAAQAAAAgBAAQgBAAAAAAQgBAAgBABIgGABQAAAEgMABQgLABgFgBIgPgBIgDAFQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIgOABQgCAHgNgEIgUgGQgBACgIABQgFABAAAHQgYAAgEABQAAADgUABQgUABAAACIgZABQgLAAgDADIgBABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgQABQAAABgGACIgIABQAAgBgSADQgTACAAACIgMADQgIACgFAAIgJAIQAAAEgJgHQgDAAgBADIgCAFQgBADgEABIgGABQAAAEgMAAQgBACgEABQgEABgDADQgDADgGAAQAAgEgGABIgKACQAAAFgWgCQAAAGgJADQgLADgCACQgCAAgEADIgHAEQgEACgCgBQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgDAAgCgCQgEgCgCAAIgIADIgIACQgDgCgEACIgHADIgEAEQgEAEAAACQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABIgBAEIgEAFIgCAAQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgDABgCgCQgDgCgCABQgFAJgVACIgUAMQgKAEgEgDIAAgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAQAAgBgKAHQAAAHgEABIgIgCQgBgBgHADQgHADgBACQgFAAgDADQgDADABAEIgMACQgNADgEAFQgEAAgBAFIAAAGIgRAJQgEAGgIAAIgMgCQACAMgGACIgMAHQgMAIAAgFQgGgEgBADIAAAEQAAADgKAIQgLAGgEABQAAACgGAEIgKADQAAgGgFAEQgHAFACAAQAAAFgHAIQgGAHgFAEQgCAFgFADIgKAEQgJADgDgEIgIAHQgFAFAGAAIgCAHIgGAJQgFAGgCAAIgKAJQgHAHgCAEQgGAAgCADIgEAJQgEABgEAFIgGAHQACAEgZAYQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIAPgBIAqgFQAAAFARgHIAFAAIADgCQAAAAABAAQABgBAAAAQAAAAABAAQAAAAAAABIAEACQABgFAKgDIAJgEQAGAAAVgEQASgDAEAIQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAgBABAAQACgEACAAQAAgBAFABIAHAAQAAgBAGAAIAJgBQAAABAAAAQAAABABAAQAAAAABAAQABAAABAAQAAgKAqAAQAAgEAKgBIAOgBQAAgHAZgBQAZgCAAADQADgBAEgEQAEgDACAAQAAgCAHACIAIACQAAAHAVgMQAAgCAHgDIAJgCQAFAHAHgBIARgDIAOgBQAHgBAAgGQgEADgEAAQAAgEADgCQAEgCABgCIAOgCIAGgCQAAgFALAAIAPAAQAHAHAGgGQAJgKAEgBQAMAAAAgCQAFAAADAFQACAFgHAAQAAAEAHACQAGADAAgFQgEAAgBgDQAAgEAEAAQAAgCAKAAIAGgEQAFgCAAgDQAHAAAEgDQABgCAEABQAEABACgBQAEgHALAAQACABAHgDIAIgEQAVgLAAAFQALAAgDgBQgIgEgBgCQgHgCAGgCIAJgBIAFAGQACACAEABQAMAAAAgCIAYgLQAFAAAJgEQALgEAFAAQAAgEAMgEQAKgDAFAAQABgCAFgCQAFgCACgCQAQgEACAAQAEABADgDQAFgFADgBIAJgFQAHgDACAEQACADgLANQgEAAgHAGQgIAFgEAAQAAAFgNAGQgOAGgCAEQgCAEgKACQgIABgCAEQgEAAgHAFIgJAHQgcALAAgBIgTAPIgMAEIgLAEQgZAGgGAIQgGgBgGAEQgGADgEAAQAAABgMABQgLABAAAGIgQADQgLACgEAEQgMAGgHABQAAACgJADIgKAEIgEAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgKADQgEAGgJABIABADIgGACIgHACIgJAAQgFgBgEABIgKAGQgKAFAAgBQgIAAgPAFQgPAFgJAAQAAABgWAEQgWAEAAADQgdALAAgEQgEAAgIAFQgHAFgEAAIgQAFQgRAEgBABIgZAFIgkAJQgaAAgCAEIgIACIgIACQAAgDgUAHIgNAEQgIADgHAAQgKADgFAAIgTAAQgFAFgMAAQgNgCgFABQAAABgIACIgLADIgBgBIgIACgAz3D2QAEgHgIgCQAAgBgEgEIgFgFQgDAAgIgFQgHgEgEAAQgBgDgHgGQgHgGgDAAQAAgCgLgIQgLgIgEAAQACAFAGAIQAGAHAFADQANAKgCAAQADAFAGAAQAWATAAgCQACABAFgCQAAAHALAAgApzCuIAGAEQgEABgCADQgDAEADADQAFADgDADIgEAEQATgEAAgBQADgBAFABIAHACIAEgBIADgDIADgBIAKgCQgFgZACAAIgCgJQgCgGABgDIACgOQABgIABgEQADAAgBgIQgBgIgGgBIgMASQAAAFgGAJQgGAJABAEQgGADgCACIgEAJQgCAAgCAEIgDAFQAAAEgIgGQgBABAGAEgAnqBaQgEAAgDAIQgEAKgDABQgDAVgBAAIAAACQgDAAgDAUQgDAUACADQADgBAFgIIADgIQADgHACAAIAFgLQAEgIACAAIADgHQAEgFAAgDQACAAAEgJIAFgLIAIgGQAHgGAAgCQAEAAABgDIABgIQACAAACgDQABgEADAAQAIgJABgEQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIACgFQAIgFAHgLQAEAAAGgJQAFgJAGAAQAegLgOAAQAAgGAFgCIAJgDQAAgGAIgEQAIgEAAgFQAFgBADgEQAEgFADgBQACgDAMgGQALgFAAgEQAKgGAGAAQAAgEAIgFQAIgEAAgDIAGgEIAHgEIAHgFQADAAAIgHQAIgGABABIALgGQAIgFACgDQAHgFABgGQAFAAAGgBQAGgCAJgGQAAAHAMgIIAPgKQACAAAGgEIAHgGQABgBAIgDIAIgDQAhgKAAgDQAFAAAJgEQAIgDAGAAQABgEAFACQAHABACgIIAGgCQACAAAHgEQACgCAOgEQANgDAAgCIAJgDQAGgDAAgDQAQgCAAgBIAJgCQAHgCAAgBQAFAAAKgEQALgFAGgBQAAgBAIgDIALgCQA2gRAEAAQAAgBAOgDIAQgEQATABAAgGQAFAAALgDQAKgDAGAAIAfgIQAAgCAMgBIAOgBQAAgCAMgCQAMgBABgCQAEAAAGgCQAHgDAEAAIAMABQAHgBADgDQAXgCAKgDQAAgEAygEQADgFAeAAQASABARgEQAAgFA4gBIA+gBQAAgCAGABQABAAABAAQABAAAAgBQABAAAAgBQAAAAAAgBIADAAIgBgCQgEAAgEgIQgFgIgDAAQAAgDgHgHQgHgGAAgEQAHgCAJADQALADAAAIQAEABAFAEQAFAEACAEQADACAAAFIADABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAEADQAEgBAEABQAGABAMgBIAUAAIAmACQAhABAAABQAIABAHgBQAAgCAUACIAZADQArACAAACIAzAEQArAFAAAGQAKAAAUAFQAVAEAKAAQAAACAPADQAPACAAACQAHABAKAEQAJADAHABQADABAHADQAGADADAAQAAADAJAAQAKABABACIAcAJQAEAAAIAEQAJAEACADQAOAHAAgDIAEABIACACQAEAAALAGQALAGAAABQAFAAAIAGQAIAFAEAAQAAABAHAFQAHAEACAAQAAABAIADQAIAEABACQADADAKAFQAIAFADAEQAHAAgHgJQgGgKgFAAIgEgEQgEgDAAgCQgIAAgHgKQgEAAgKgJQgLgKAAgDIgLgBQgHgCAAgEIgDgCIgGgBQgIgIgCgBIgOgHQgGgEgHAAQgEgFgKgDQgEgBgBgCQgCgDgCgBQAAgCgSAAQAAgGgLgCIgPgCQgHAAgHgDQgIgEAAgEQgIAAgNgJQgNgKgHAAQAAgBgKgCIgKgBQgZgHAAgCIgPgDQgIgDgEAAQAAgEgdgGQgZgEgKAAQAAgCgOAAQgPgBAAgEIgXgDQAAgDgbgCIgbgDQgZgDgMAAQAAgBgMgBQgMgBgBgBIgbgBQAAADgogCQgBgCgOAAQgNgBAAACQgDABgGgBIgIgBQgRACgIgBIgKADQAAABgKAAIgMgBQAAADgVACQgVABgFgBIgwAEIg5AEQgFAAgYAEQgZAEAAACIgXACIgUADQAAAHgyACQAAADgkAGQgCADgJAAQgJAAgDAEQgFgBgGACIgJABQAAACgOABQgNABAAADIgeAJQgSAFgLAAIgdAKQgeAJgCgBQAAAEgNACQgOACgBAEIgOAEQgIACgFABQAAABgHADIgIACQAAABgKAEIgPADQgCAEgLADQgLADgCAEQgEAAgGADQgHAEgDAAQgVAFgFAHQgFAAgIAGQgJAGgFAAQgDADgHAEQgHAEgEAAQgCADgPAIQgEAAgJAHQgIAHgHgCQgBAEgJAAQgBAEgIADQgNAFgHAGIgPAJIgPAJIgJAIQgEAFgFAAQABgCgKAHQAAAGgYAPQgLAMgKAEQAAABgEADIgGAEQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAABgFAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQgDAEgMAHIgDAEIgEAEQAAADgEAEQgDAEgDAAIgFAHIgHAFQAAACgJAIQgDADgEACQgFABgDADQAAADgEACQAAADgDACIgGAEQgCACAAAEQAAAFgCACIgFADQgDAAgCADQgCAFgBAAQgBACgEAGQgEAFgCABQAAAGgJAGQgKAGAAAGQABAAgFARIABAIQgBAFgDABIgBABIAAAAIgBABgAxpmXQgDABgCACIgCAFQgHAAgCADQgCAAgGADQgFADgCACIgHADIgGADQgGAHgTAGQgCAEgKACQgKABgBADIgHAGQgGAFAAABQgOAAgBAHIgSAOQgEAAgPAKQgJAGgGAHQgCADgFADQgFADgCADQAAAHgIAEQgKAEgBAFQgCABgDAGQgCAEgDABQgBACgGAFQgFAEAAADIgJAJIgIALIgDACQACACAlgbQAmgdAHgBIAHgFQAEgDADAAQAAgBAEgCIADgEQgDgBAAgEIAMgBQAIgCACgCIADgCQAAgBABAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgCAGgDQAFgDACAAQACgDALgFQAJgEACgDQADAAAFgFIAHgHQAMgEABgBQADAAAHgEQAJgEADgBQACgCAHAAQAEABABgFQABgJANAAIAHgIQACgDAFABQAFABABgDQACAAAHgEQAHgFACgBQAAgCARgHQAQgHADABIgBgEQAGgBAHgEQAHgEAFgBIALgFQAHgEACgDQADAAAFgCIAHgDQACgCAFAAIAIABQACgFADgCQAGgHAPgDIAYgDQACgDAIgDQAIgDAEAAQAAgDAIACQACABAEgCIAGgEIAIgEQAEgCADAAQAEgGAOgEIAWgEQAGgBALgDQAOgEAAgDIAHgCIAFgDIAJABQAFgBAAgFQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAABgBIACgDIgGgDIgvAMIgCgBQAAACgLABQgKACAAABQgHAAgLAGQgLAGgGABIAAgDQgFAAgKADQgJADgFAAQgEgBgCADIgFAEQgEAEgCAAIgHgDIgIAEQgIADgBAEIADABQgBADgFAAQgEABACgEQgDAAgHADQgHADgEAAIgFACQgGADgBACIgDAFQgDABgDgBQgCAGgOAFQAAABgFABQgFAAAAABIgLACQgEABgCAHIgDABQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgKAAAAgCQgCAAgDACQgEADgCABIgOAHQgNAIACABIgNAGIgNgCIgDABgAlSlJQgFgDAKgGIALgHQAIgDAAgBQABgBABAAQAAAAABAAQABAAAAAAQAAABABABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQACACgOAJQgJAGgFAAIgEgBg");
	this.shape_1.setTransform(7.7928,27.7457,0.4948,0.4948);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABwDnIAAkXQAAgygageQgbgeguAAQgfAAgdAPQgdAPgkAjIAAFEIhjAAIAAnEIBjAAIAAA8IADAAQAdghAogSQAngSAqAAQBLAAAvAtQAxAxAABZIAAEWg");
	this.shape_2.setTransform(117.997,94.1892,0.4949,0.4949);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjCCoQhLhEAAhnQAAhiBNhCQBNhDBxgBQB2AABNBCQBNBBAABlQAABqhMBCQhMBDh4AAQh1AAhLhEgAh4hvQgvAqAABCQAABGAuAsQAtArBIABQBPgBAugqQAugrAAhIQAAhBgwgrQgxgrhKAAQhGAAguArg");
	this.shape_3.setTransform(90.4194,94.4243,0.4949,0.4949);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiqEwQhCgnAAg8QABgyAegeQAfgfBBgOQgygbAAgeQAAgWAWgRQAWgRAjgIIAAgCQg3gVgdgkQgbgjAAgyQAAhIA8gqQA7gqBkAAIDRAAIAABFIhoAAQAeAbAMAWQALAVAAAdQAAAbgPAeQgNAcgTARQgiAghdAPQgoAGgOAGQgXAJAAARQAAASAnAOQAiAMBQAOQBNAOAlAjQAhAfgBAuQAABEg/AmQg/AmhvAAQhmAAhBgmgAhtCYQggATAAAeQAAAiAkASQAkASBEAAQBBAAAlgRQAlgSAAgfQgBgmg7gUQgsgOg9AAQgyAAggATgAhIjvQgdAYAAAhQABAlAbAXQAcAXAtAAQApAAAcgYQAbgYAAglQAAgggdgYQgdgYgnAAQgpAAgeAZg");
	this.shape_4.setTransform(64.4501,100.1526,0.4949,0.4949);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABoAAQBmAAA5A+QA8BAAAB7IliAAQAYCHCQAAQBVAABbg2IAABXQguAcgsAMQgxAOg9AAQhxgBhEhJgAhPiAQgjAdgKA2ID9AAQgDg0gfgeQgggeg0AAQg4AAgiAdg");
	this.shape_5.setTransform(39.7057,94.4243,0.4949,0.4949);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ai3DnIAAnEIBkAAIAABoIACAAQBHhxBKAAQA6AAA/A1Ig1BNQgXgTgbgNQgagMgSAAQgzAAgjAoQgjApAAA6IAADsg");
	this.shape_6.setTransform(19.9101,94.1892,0.4949,0.4949);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Aj1DJQhahSAAh3QAAh3BchTQBfhVCUAAQCWAABfBVQBbBSAAB4QAAB3haBSQhfBXiYAAQiVAAhfhXgAitiYQhGA8AABcQAABcBGA9QBFA9BoAAQBpAABFg9QBFg8AAhdQAAhchFg8QhFg9hpAAQhoAAhFA9g");
	this.shape_7.setTransform(-9.6965,91.7272,0.4949,0.4949);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABnAAQBnAAA5A+QA8BAAAB7IljAAQAMBCArAjQAqAiBIAAQBUAABdg2IAABXQgwAcgrAMQgwAOg/AAQhvgBhFhJgAhQiAQgjAdgKA2ID+AAQgDg0gfgeQgggeg0AAQg4AAgjAdg");
	this.shape_8.setTransform(-41.7282,94.4243,0.4949,0.4949);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ai4DnIAAnEIBkAAIAABoIADAAQBHhxBKAAQA7AAA9A1Ig1BNQgWgTgbgNQgagMgSAAQgyAAgkAoQgkApAAA6IAADsg");
	this.shape_9.setTransform(-61.1773,94.1892,0.4949,0.4949);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ABFDgQgTgLgHgYQhAAuhHABQg2AAgkgiQgiggAAguQABg7A3gkQAfgUBVgbIBYgcIAAgYQAAgpgWgUQgWgTguAAQhZAAhHBLIAAhiQA7g+BtAAQBQABAxAjQA1AoAABKIAADoQAAAXATAAQARAAAkgYIAAA2QgjAVgTAHQgUAIgWAAQghAAgSgMgAhCAtQgxAbAAAkQABAcAUASQAVASAeAAQAsAAArgmIAAiDQhOAXggATg");
	this.shape_10.setTransform(-84.536,94.4243,0.4949,0.4949);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AjIDAQhRhQAAhnQAAiABhhUQBhhUCUAAQBcAAB7AuIAABXQg6gfg0gOQgzgOg3AAQhqAAhHA9QhHA+AABbQAABeBGA8QBGA7BwAAQBsAABug/IAABXQgzAYgwAMQg6AOhFAAQihAAhfhgg");
	this.shape_11.setTransform(-112.7818,91.9993,0.4949,0.4949);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CO_v_white, new cjs.Rectangle(-126.7,-7.3,264.2,124.39999999999999), null);


(lib.BUTTON = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAqIAlgqIglgpIAaAAIAmApIgmAqgAg2AqIAmgqIgmgpIAbAAIAlApIglAqg");
	this.shape.setTransform(30.575,6.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUA4QgMgFgIgIQgIgHgFgMQgEgLAAgNQAAgLAEgLQAFgMAHgHQAIgIALgGQALgEAMAAQANAAAKAEQALAFAHAJQAIAHAEANQAEALAAANIAAAGIhUAAQACALAIAIQAIAIAOAAIAIgBIAIgCIAIgDIAHgGIANAUQgJAIgMAEQgNAEgNAAQgMAAgLgEgAgKghQgFACgEAEIgFAIIgCAJIA3AAIgCgJIgFgIQgDgDgFgCQgGgDgHAAQgGAAgFACg");
	this.shape_1.setTransform(15.125,6.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AggA6IAAhwIAeAAIAAAPQAFgHAKgGQAJgFALgBIAAAeIgIgBIgIABIgIADIgHAEQgDACgBADIAABKg");
	this.shape_2.setTransform(5.475,6.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaA6QgHgDgGgEQgFgFgEgHQgEgHAAgKQAAgKAEgHQAEgGAFgEQAGgFAHgCQAHgCAHAAQALAAAJADQAKAEAFAHIAAgPQAAgJgHgGQgHgEgKgBQgTAAgPAOIgLgUQALgJANgFQANgEAMAAQAKAAAJACQAJACAGAGQAIAFAEAHQAEAJAAAMIAABJIgeAAIAAgMQgGAHgJAEQgJAEgLAAQgHAAgHgCgAgQAKQgFAEgBAJQABAIAFAEQAHAEAJABQAGgBAGgCQAHgCAEgFIAAgPQgEgEgHgDQgGgCgGAAQgJAAgHAEg");
	this.shape_3.setTransform(-5.45,6.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgQA4QgLgFgIgIQgIgIgEgLQgFgLAAgNQAAgMAFgLQAEgLAIgIQAIgIALgFQAMgEAMAAQARAAALAGQALAGAGAJIgUASQgIgMgQAAQgMAAgJAJQgJAJAAAOQAAAPAJAJQAJAJAMAAQAIAAAGgDQAGgDAEgGIAUASQgGAIgLAGQgLAHgRAAQgMAAgMgEg");
	this.shape_4.setTransform(-16.625,6.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgKBCQgIgIAAgPIAAg7IgTAAIAAgaIATAAIAAgfIAdAAIAAAfIAXAAIAAAaIgXAAIAAAzQAAAFADAEQACADAFAAIAGgBIAFgCIAGAXQgDADgGACQgHACgJAAQgPAAgIgIg");
	this.shape_5.setTransform(-31.375,4.775);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgUA4QgMgFgIgIQgIgHgFgMQgEgLAAgNQAAgLAEgLQAFgMAHgHQAIgIALgGQALgEAMAAQANAAAKAEQALAFAHAJQAIAHAEANQAEALAAANIAAAGIhUAAQACALAIAIQAIAIAOAAIAIgBIAIgCIAIgDIAHgGIANAUQgJAIgMAEQgNAEgNAAQgMAAgLgEgAgKghQgFACgEAEIgFAIIgCAJIA3AAIgCgJIgFgIQgDgDgFgCQgGgDgHAAQgGAAgFACg");
	this.shape_6.setTransform(-41.225,6.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgXBMQgPgGgLgKQgMgLgHgPQgGgPgBgTQABgSAGgPQAHgPAMgLQALgKAPgGQAPgGAQAAQANAAAKADQAKADAIAFQAIAFAGAGIALAOIgcAPQgFgIgKgHQgJgGgOAAQgJAAgJAEQgKAEgGAHQgGAHgEAJQgEAKAAAKQAAALAEAKQAEAJAGAHQAGAHAKAEQAJAEAJAAQALAAAJgEQAJgEAFgEIAAgTIgpAAIAAgdIBLAAIAAA8QgNAOgQAIQgRAIgWAAQgQAAgPgGg");
	this.shape_7.setTransform(-55.8,4.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// bkgd
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#00A7B5").s().p("Aq0C4IAAluITwAAIB6CtIh6DBg");
	this.shape_8.setTransform(-10.4,5.9758,1,1.0587);

	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(1));

	// shad
	this.instance = new lib.Buttonshad();
	this.instance.setTransform(-80,-14,0.6438,0.6815);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BUTTON, new cjs.Rectangle(-96.8,-14,166.2,59.3), null);


(lib.BKGD = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF8300").s().p("A96WbMAAAgs1MA71AAAMAAAAs1g");
	this.shape.setTransform(0.0067,125.0449,0.7833,0.8714);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGD, new cjs.Rectangle(-150,0,300,250.1), null);


(lib.HEAD2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD2type();
	this.instance.setTransform(0,38,1,1,0,0,0,0,36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-139,2,278,50.8), null);


(lib.HEAD1d = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1dtype();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1d, new cjs.Rectangle(-135,-4,278,42.1), null);


(lib.HEAD1c = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1ctype();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1c, new cjs.Rectangle(-135,-4,278,42.1), null);


(lib.HEAD1b = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1btype();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1b, new cjs.Rectangle(-135,-4,278,42.1), null);


(lib.HEAD1a = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1atype();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1a, new cjs.Rectangle(-135,-4,278,42.1), null);


// stage content:
(lib.CO_KidsProcedures_728x90 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,432];
	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_432 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(432).call(this.frame_432).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,2,0,3).p("Eg4ygG8MBxlAAAIAAN5MhxlAAAg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(433));

	// HS logo
	this.instance = new lib.HS_logowhite();
	this.instance.setTransform(533.25,45.8,0.3378,0.3376,0,0,0,0.8,71.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(433));

	// CO logo
	this.instance_1 = new lib.CO_v_white();
	this.instance_1.setTransform(641.55,46.35,0.3786,0.3785,0,0,0,0.2,55.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(433));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EghFAHCIAAuDMBZ6AAAIAAODg");
	mask.setTransform(363.696,44.9987);

	// CTA
	this.instance_2 = new lib.BUTTON();
	this.instance_2.setTransform(94.75,73.05,0.76,0.76,0,0,0,-10.4,3.9);
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(413).to({_off:false},0).to({x:204.25},19).wait(1));

	// HEAD1a
	this.instance_3 = new lib.HEAD1a();
	this.instance_3.setTransform(302,44.15,1,1,0,0,0,4,13.8);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({y:40.15,alpha:1},7).wait(65).to({y:36.15,alpha:0},7).to({_off:true},1).wait(353));

	// HEAD1b
	this.instance_4 = new lib.HEAD1b();
	this.instance_4.setTransform(302,44.35,1,1,0,0,0,4,13.8);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(80).to({_off:false},0).to({y:40.35,alpha:1},7).wait(65).to({y:36.35,alpha:0},7).to({_off:true},1).wait(273));

	// HEAD1c
	this.instance_5 = new lib.HEAD1c();
	this.instance_5.setTransform(302,44.35,1,1,0,0,0,4,13.8);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(160).to({_off:false},0).to({y:40.35,alpha:1},7).wait(65).to({y:36.35,alpha:0},7).to({_off:true},1).wait(193));

	// HEAD1d
	this.instance_6 = new lib.HEAD1d();
	this.instance_6.setTransform(302,43.35,1,1,0,0,0,4,13.8);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(240).to({_off:false},0).to({y:39.35,alpha:1},7).wait(65).to({y:35.35,alpha:0},7).to({_off:true},1).wait(113));

	// HEAD2
	this.instance_7 = new lib.HEAD2();
	this.instance_7.setTransform(301.1,48.25,1,1,0,0,0,0,27.4);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(320).to({_off:false},0).to({y:44.25},14).wait(72).to({y:30.4},9).wait(18));

	// BKGD-orange
	this.instance_8 = new lib.BKGD();
	this.instance_8.setTransform(728.4,45,1.9189,0.3599,0,0,0,150.4,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(433));

	// PIC
	this.instance_9 = new lib.kp_img_728x90();

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(433));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(363.5,44.5,365,46);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 728,
	height: 90,
	fps: 36,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/CO_KidsProcedures_728x90_atlas_P_1.png", id:"CO_KidsProcedures_728x90_atlas_P_1"},
		{src:"images/CO_KidsProcedures_728x90_atlas_NP_1.jpg", id:"CO_KidsProcedures_728x90_atlas_NP_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;