(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"CO_Safety_160x600_atlas_P_1", frames: [[0,0,232,87]]},
		{name:"CO_Safety_160x600_atlas_NP_1", frames: [[0,0,320,1200],[0,1202,160,600],[162,1202,160,600]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Buttonshad = function() {
	this.initialize(ss["CO_Safety_160x600_atlas_P_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.MhSubstance_160x600 = function() {
	this.initialize(ss["CO_Safety_160x600_atlas_NP_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.safety_img1_160x600 = function() {
	this.initialize(ss["CO_Safety_160x600_atlas_NP_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.safety_img2_160x600 = function() {
	this.initialize(ss["CO_Safety_160x600_atlas_NP_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.HS_logowhite = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ap9EXIAHnRINagKIgCh7IGDgCIAZKDgAFdgfQgVAOgIAYQgGAUAAAZQAAAaAGATQAJAZAVAOQAVAOAgAAQAyAAAeggQADgDgEgCIgZgYQgCgDgEADQgSARgZAAQgfAAgHgZIgDgKQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIBxAAQAEAAAAgEQAAglgGgUQgIgYgVgOQgVgOgfABQgeAAgVANgAgnAvQgVAQAAAdQAAAdASAPQARAOAaAAQAjAAAQgVIABAAIAAANQAAADAEAAIArAAQADAAAAgDIAAh4QAAgjgSgPQgUgRgtABQgqAAgaASQgDACACADIARAeQACADADgDQAQgKAZAAQAWAAAIAEQAIAHAAANIAAAHQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIghAAQgkAAgUAOgAnMBXIgZAdQgCACACADQAiAdAzAAQAoAAAWgSQAVgRABgeQAAgyg/gGIgUgCQgPgCgGgEQgFgDAAgHQAAgOAYgBQAbAAAXAOQAEADACgDIAVgaQADgDgDgDQgegWguAAQgkgBgVARQgUAQAAAaQAAAzA9AHIAVABQAQACAGAEQAFAEAAAHQAAASgdAAQgfAAgagVIgDgBIgDABgACfgkIAACyQAAADAEAAIAuAAQAEAAAAgDIAAhjQAAgnAdgCQAMAAAPAJQADABACgCIAWgmQACgEgDgCQgNgLgUABQgjgBgOAYIAAAAIAAgPQAAgFgEAAIguAAQgEAAAAAFgAieAiIAABsQAAADAEAAIAuAAQAEAAAAgDIAAh2QAAgegRgTQgRgUgeABQghAAgPAUIgBAAIAAhZQAAgDgEAAIguAAQgEAAAAADIAAD/QAAADAEAAIAuAAQAEAAAAgDIAAhsQAAgPAIgKQAIgJAOAAQAdAAAAAig");
	this.shape.setTransform(25.025,83.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAaAAQABABABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_1.setTransform(27.15,92.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeATQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBQAAgGACgIQAHgTAXgBQAZABAGATQACAGAAAIQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_2.setTransform(65.075,85.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AqIk4IUcAvIAII0I03AOgAhWAjQgVAQAAAeQgBAdAUAPQAQAOAbAAQAkAAAPgVIAAANQAAADAEAAIArAAQAEAAAAgDIAAh5QAAgjgSgPQgUgRgsAAQgrAAgcATQgCACACADIARAfQACACADgBQARgMAZAAQAWAAAIAGQAHAGAAAMIAAAHQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIghAAQgjAAgVAOgAkagrQgVAOgIAZQgHATAAAZQAAAXAHAWQAIAaAWAOQAVAOAgAAQAzAAAdggQADgDgDgCIgagYQgCgDgDADQgSAQgZAAQgfAAgIgYQgCgDgBgIQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIBxAAQAFAAAAgEQAAgmgGgTQgJgZgUgOQgWgOgfAAQgeAAgVAOgADcgxIAAAhQAAAEAFAAIALAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAABUQAAAhAOAPQAOAPAgAAIAUAAQAEAAABgEIAAgnQgBgDgEAAIgJAAQgJAAgDgEQgFgFAAgKIAAhSQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAYAAQAEAAABgEIAAghQgBgDgEAAIgYAAQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAgyQAAgEgDAAIguAAQgFAAAAAEIAAAyQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgLAAQgFAAAAADgABth9IAADKQAAAfANAPQAOAOAfAAIAVAAQADAAAAgEIAAgnQAAgDgDAAIgIAAQgRAAAAgSIAAjGQAAgEgEAAIgvAAQgDAAAAAEgAHggBQAIAIAAAQIAABsQAAADADAAIAvAAQAEAAAAgDIAAh3QAAgegRgTQgQgUgfAAQghAAgQAWIAAAAIAAhaQAAgEgEAAIguAAQgFAAAAAEIAAEAQAAADAFAAIAuAAQAEAAAAgDIAAhsQAAgQAIgIQAIgKAOAAQAOAAAHAKgAmpgBQAHAIAAAQIAABsQAAADAFAAIAuAAQAEAAAAgDIAAh3QAAgegRgTQgRgUgfAAQghAAgPAWIAAhaQAAgEgEAAIgvAAQgDAAAAAEIAAEAQAAADADAAIAvAAQAEAAAAgDIAAhsQAAgQAIgIQAHgKAOAAQAOAAAIAKg");
	this.shape_3.setTransform(-21.95,31.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAbAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_4.setTransform(-24.5,39.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeASQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAgGADgIQAHgUAXAAQAYAAAIAUQACAIAAAGQAAABgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-45.05,31.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AJdAwIAcgBQABAJANAAQAPABAAgNIAAgIQgIAFgMAAQgRAAgLgMQgKgLAAgSQAAgSAKgLQALgMARAAQANAAAIAHIAAgFIAaAAIAABRQAAARgLALQgLAKgTAAQgmAAgFgggAJ4AAQAAASAPAAQAHgBAEgEQAEgEAAgIIAAgCQAAgHgEgFQgFgEgGAAQgPAAAAARgALLAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgALbAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAILAeQgLgLAAgTQAAgSALgLQAMgMASAAQASAAAKAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgKAHQgLAHgOAAQgTAAgMgLgAI0gIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgAFOAZQgRgQAAgaQAAgaARgRQAQgQAbAAQAbAAARAQQARARAAAaQAAAagRAQQgRAQgbAAQgbAAgQgQgAFjgpQgIAJAAAPQAAAPAIAJQAIAIAOAAQAOAAAIgIQAJgJAAgPQAAgPgJgJQgIgIgOgBQgOABgIAIgACHAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgACXAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAAJAeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgPAAQgTAAgLgLgAAygIQgBgMgLAAQgKAAgBAMIAXAAIAAAAgAiVASQAAgWAigCIAJAAIAAgEQAAgIgGAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAh6AQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAlOAfQgNgKAAgTIAegBQAAAGAFAEQAFAFAHAAQANgBAAgIQAAgHgTgFQgTgFgIgGQgLgHAAgQQAAgQAKgJQALgMAUAAQAUAAAMALQAMAJABASIgeABQAAgNgOAAQgMAAAAAKQAAAEAEACQADADAMADQATAEAIAHQALAJAAANQAAASgMAKQgMAIgTAAQgVAAgNgKgAoUANIAAgdIgOAAIAAgXIAOAAIABgZIAbAAIAAAZIARAAIAAAXIgRAAIAAAWQAAALALAAIAGgBIAAAYIgNABQggAAAAgcgAqjASQAAgWAigCIAKAAIAAgEQAAgIgHAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAqIAQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAr0AeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgOAAQgTAAgMgLgArLgIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgANWAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAhOIAaAAIAAAFQAGgHAOAAQAOAAAIAIQAJAJAAAPIAAAwgAHGAnIAAhOIAbAAIAAAGQAHgHAOAAIAAAbQgJAAgGAFQgFAEAAAGIAAAlgADlAnIAAg3IgOAAIAAgXIAOAAIAAgFQAAgQAKgKQAKgJAQAAIAJAAIAAAZIgGgBQgFAAgDADQgDADAAAEIAAAGIARAAIAAAXIgRAAIAAA3gAg7AnIAAhOIAbAAIAAAGQAGgHAPAAIAAAbQgKAAgFAFQgFAEAAAGIAAAlgAjAAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAGgGAMAAQAOAAAIAIQAJAJAAAPIAAAwgAmnAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAHgGALAAQAOAAAIAIQAJAJAAAPIAAAwgApJAnIAAh1IAcAAIAAB1gAstAnIAAgsIgmAAIAAAsIgeAAIAAhwIAeAAIAAAqIAmAAIAAgqIAeAAIAABwg");
	this.shape_6.setTransform(0.175,134.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HS_logowhite, new cjs.Rectangle(-88.7,0,177.5,143), null);


(lib.HEAD3type = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANQgFgFAAgIQAAgHAFgFQAFgEAHAAQAIAAAFAEQAFAFAAAHQAAAIgFAFQgFAEgIABQgHgBgFgEg");
	this.shape.setTransform(-9.975,67.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAUAvIgTgzIgTAzIgXAAIgahHIgDgEIgDgBIgFAAIAAgRIAzAAIAAARIgFAAQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAABABIADAJIAFAOIAFAOIAFgOIAFgOIADgJQAAgBABAAQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAQgBgBAAAAQgBAAAAAAQgBAAAAAAIgEAAIAAgRIAuAAIAAARIgEAAQgBAAAAAAQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABIAEAJIAFAOIAGAOIAFgOIAFgOIADgJQABgDgBgCQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgFAAIAAgRIAmAAIAAARIgFAAIgDABIgDAEIgZBHg");
	this.shape_1.setTransform(-20.175,64.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgaArQgLgGgGgLQgHgLAAgPQAAgNAHgMQAGgKAMgHQALgGAOAAQAQAAALAGQALAHAGAKQAGAMABANQgBAPgGALQgGALgMAGQgLAGgPAAQgPAAgLgGgAgOgYQgEAHAAARIAAABQAAAQAEAIQAFAGAJAAQAKAAAFgGQAEgIAAgQIAAgBQAAgRgEgHQgFgGgKAAIAAAAQgJAAgFAGg");
	this.shape_2.setTransform(-33.475,64.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAGAwIAAgRIAFAAIADgBQABgBAAgEIAAgjQAAgJgDgEQgDgEgHAAQgHAAgEAGQgFAGAAAOIAAAaQAAAEABABIADABIAFAAIAAARIgyAAIAAgRIAHAAIACgBIABgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAIgHAAIAAgRIASAAIANgBIAKgBIAAARQAEgJAIgEQAHgFALAAQAPAAAHAJQAIAJAAASIAAAkQAAAEABABIADABIAGAAIAAARg");
	this.shape_3.setTransform(-44.575,64.075);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgYArQgLgHgGgKQgGgMAAgOQAAgNAGgMQAHgKALgHQAKgGAOAAQAXABAMANQAMAMAAAXIAAAFIg/AAQABAMAFAGQAHAGAKAAQAJABAGgFQAFgEADgHIAQAJQgDAIgFAFQgGAGgJADQgIADgMAAQgRAAgLgGgAARgHQAAgOgDgEQgFgGgIAAQgGAAgFAGQgFAFAAANIAgAAIAAAAg");
	this.shape_4.setTransform(-60.05,64.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYBAIAAgQIAGAAIADgBQABgCAAgEIAAhPIgBgFQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAgBgBAAIgHAAIAAgQIATAAIANgBIAJgBIAABoQAAAEABACIADABIAGAAIAAAQg");
	this.shape_5.setTransform(-68.025,62.45);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgGA7QgIgGgEgLIgGAVIgVAAIAAgFIAAgKIAAgRIAAhGIAAgFQgBgBAAAAQAAAAgBAAQAAgBAAAAQgBAAAAAAIgIAAIAAgQIAUAAIANgBIAJgBIAAAzQAEgJAIgFQAHgFAMAAQALAAAKAHQAJAGAEAKQAFAKAAAPQAAAPgFALQgFALgJAGQgJAGgNAAQgNAAgIgGgAgIgGQgFAGgBAPIAAADQABAOAFAHQAFAHAHAAQAJAAAGgHQAEgHAAgOIAAgDQAAgPgEgGQgGgHgJABIgBAAQgGAAgFAGg");
	this.shape_6.setTransform(-76.75,62.575);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgrAqQgHgHAAgKQABgNAHgHQAJgFAOgFQANgDAPgCIAAgGQABgIgEgDQgFgFgIAAIgFABIgEABIABAEIABAEQAAAHgEAEQgFAEgHAAQgIAAgFgEQgEgEAAgIQAAgIAFgGQAGgFAKgDQALgDAOAAQAVAAALAHQAKAIAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAAAAAIAHAAIAAAQIgiAAIgFgHIgCgIQgDAGgFADQgDAEgHADQgGACgHAAQgOAAgIgHgAgLAHQgJAEAAAJQAAAEADAEQADACAFAAQAJAAAFgFQAEgGAAgKIAAgIQgMACgIAEg");
	this.shape_7.setTransform(-87.7,64.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgYBAIAAgQIAGAAIADgBQABgCAAgEIAAhPIgBgFQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAgBgBAAIgHAAIAAgQIATAAIANgBIAJgBIAABoQAAAEABACIADABIAGAAIAAAQg");
	this.shape_8.setTransform(-96.025,62.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgZBCIAAgQIAHAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAgtIgBgGQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgGAAIAAgRIATAAIAMgBIAKgCIAABIQAAABAAABQAAAAAAABQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAHAAIAAAQgAgMglQgFgEAAgIQAAgHAFgEQAFgGAHAAQAIAAAFAGQAEAEABAHQgBAIgEAEQgFAEgIABQgHgBgFgEg");
	this.shape_9.setTransform(-101.725,62.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgrAqQgHgHAAgKQABgNAHgHQAJgFAOgFQANgDAPgCIAAgGQABgIgEgDQgFgFgIAAIgFABIgEABIABAEIABAEQAAAHgEAEQgFAEgHAAQgIAAgFgEQgEgEAAgIQAAgIAFgGQAHgFAJgDQALgDAOAAQAVAAALAHQAKAIAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAIAGAAIAAAQIgiAAIgFgHIgCgIQgDAGgFADQgDAEgHADQgGACgIAAQgNAAgIgHgAgLAHQgJAEAAAJQAAAEADAEQADACAGAAQAIAAAEgFQAGgGgBgKIAAgIQgMACgIAEg");
	this.shape_10.setTransform(-109.85,64.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgKAvIgghHQgBgDgBgBIgEgBIgFAAIAAgRIA1AAIAAARIgHAAQAAAAgBAAQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABABABQAAAAAAABIAEALIAGANIAFAQIAHgRIAHgOIADgJQAAAAABgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAAAIgIAAIAAgRIAsAAIAAARIgHAAIgDABQgCABgCADIgfBHg");
	this.shape_11.setTransform(-120.75,64.275);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgrAqQgHgHAAgKQABgNAHgHQAJgFAOgFQANgDAQgCIAAgGQAAgIgFgDQgDgFgJAAIgFABIgEABIABAEIABAEQAAAHgEAEQgFAEgHAAQgIAAgFgEQgEgEAAgIQAAgIAFgGQAHgFAKgDQAKgDAOAAQAVAAALAHQAKAIAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAIAGAAIAAAQIgiAAIgFgHIgCgIQgDAGgFADQgDAEgGADQgHACgIAAQgNAAgIgHgAgMAHQgIAEAAAJQAAAEADAEQADACAGAAQAIAAAEgFQAGgGAAgKIAAgIQgNACgJAEg");
	this.shape_12.setTransform(-131.55,64.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgWAuQgKgBgHgDIAAgZIAWAAIAAAPIAGABIAJABQAGAAAEgCQAEgEAAgEQAAgHgFgCIgOgEQgIgBgHgDQgIgDgFgEQgEgHgBgKQABgOAKgIQALgJATAAQAMABAJACIAPAEIAAAYIgVAAIAAgNIgGgCIgHgBQgGAAgEADQgEADAAAEQAAAFADABQACACAFABIAJADIAQAEQAHADAFAFQAFAGAAAKQAAAPgLAJQgLAIgUAAQgMAAgJgDg");
	this.shape_13.setTransform(-18.325,40.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADACAGAAIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_14.setTransform(-26.125,38.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAGAwIAAgRIAFAAIADgBQABgBAAgEIAAgjQAAgJgDgEQgDgEgHAAQgHAAgEAGQgFAGAAAOIAAAaQAAAEABABIADABIAFAAIAAARIgyAAIAAgRIAHAAIACgBIABgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAIgHAAIAAgRIASAAIANgBIAKgBIAAARQAEgJAIgEQAHgFALAAQAPAAAHAJQAIAJAAASIAAAkQAAAEABABIADABIAGAAIAAARg");
	this.shape_15.setTransform(-34.925,39.975);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgYArQgLgGgGgLQgGgLAAgPQAAgOAGgLQAHgLALgGQALgGAOAAQAWAAANANQALANAAAXIAAAFIg/AAQAAAMAGAGQAHAHAKgBQAJABAFgFQAGgEADgHIAQAJQgDAHgFAGQgGAFgJAEQgIADgMAAQgQAAgMgGgAARgIQAAgNgEgFQgEgFgHAAQgIAAgEAFQgFAGAAAMIAgAAIAAAAg");
	this.shape_16.setTransform(-45.9,40.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAjAwIAAgRIAFAAIACgBQABgBAAgEIAAghQAAgKgDgEQgDgEgHAAQgHAAgEAGQgDAFAAAMIAAAcQAAAEABABIACABIAGAAIAAARIgwAAIAAgRIAFAAIACgBQABgBAAgEIAAgiQAAgJgDgEQgDgEgHAAQgHAAgEAGQgDAFAAAMIAAAcQAAAEABABIACABIAGAAIAAARIgzAAIAAgRIAHAAIADgBIAAgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgHAAIAAgRIATAAIANgBIAJgBIAAARQAFgIAHgFQAHgFAKAAQAMAAAFAFQAHAFADALQAEgKAHgGQAIgFAMAAQAPAAAIAJQAIAJAAATIAAAjIAAAFIADABIAHAAIAAARg");
	this.shape_17.setTransform(-59.575,39.975);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADACAGAAIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_18.setTransform(-71.725,38.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAGAwIAAgRIAFAAIADgBQABgBAAgEIAAgjQAAgJgDgEQgDgEgHAAQgHAAgEAGQgFAGAAAOIAAAaQAAAEABABIADABIAFAAIAAARIgyAAIAAgRIAHAAIACgBIABgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAIgHAAIAAgRIASAAIANgBIAKgBIAAARQAEgJAIgEQAHgFALAAQAPAAAHAJQAIAJAAASIAAAkQAAAEABABIADABIAGAAIAAARg");
	this.shape_19.setTransform(-80.525,39.975);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgZBCIAAgQIAHAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAgtIgBgGQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgGAAIAAgRIATAAIAMgBIAKgBIAABHQAAABAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAHAAIAAAQgAgMglQgFgFAAgHQAAgHAFgEQAFgFAHgBQAIABAFAFQAEAEABAHQgBAHgEAFQgFAEgIABQgHgBgFgEg");
	this.shape_20.setTransform(-89.275,38.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgaArQgLgGgGgLQgHgLAAgPQAAgOAHgLQAGgLAMgGQALgGAOAAQAQAAALAGQALAGAGALQAGALABAOQgBAPgGALQgGALgMAGQgLAGgPAAQgPAAgLgGgAgOgYQgEAIAAAQIAAABQAAAQAEAIQAFAGAJABQAKgBAFgGQAEgIAAgQIAAgBQAAgQgEgIQgFgGgKAAIAAAAQgJAAgFAGg");
	this.shape_21.setTransform(-97.525,40.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("Ag3BAIAAgRIAHAAIADAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAhQQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAgRIATAAIANgBIAJgBIAAATQAFgJAHgGQAHgFAMAAQAMAAAJAGQAIAHAGAKQAEALAAAPQAAAOgFALQgFALgJAGQgJAGgNAAQgLAAgGgFQgIgEgDgJIAAAaIABAFIADAAIAHAAIAAARgAgIgkQgFAGAAAPIAAACQAAAOAFAHQAFAHAIgBQAIABAFgHQAFgHABgOIAAgCQgBgPgFgGQgFgHgIAAQgIAAgFAHg");
	this.shape_22.setTransform(-108.85,41.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("Ag3BAIAAgRIAHAAIADAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAhQQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAgRIATAAIANgBIAJgBIAAATQAFgJAHgGQAHgFAMAAQAMAAAJAGQAIAHAGAKQAEALAAAPQAAAOgFALQgFALgJAGQgJAGgNAAQgLAAgGgFQgIgEgDgJIAAAaIABAFIADAAIAHAAIAAARgAgIgkQgFAGAAAPIAAACQAAAOAFAHQAFAHAIgBQAIABAFgHQAFgHABgOIAAgCQgBgPgFgGQgFgHgIAAQgIAAgFAHg");
	this.shape_23.setTransform(-120.55,41.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgrAqQgHgGAAgLQABgNAHgGQAJgGAOgFQANgDAQgCIAAgGQAAgIgFgDQgDgEgJgBIgFABIgEABIABAEIABAFQAAAGgEAEQgFAEgHAAQgIAAgFgEQgEgEAAgIQAAgIAFgGQAHgFAKgDQAKgDAOAAQAVAAALAHQAKAIAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAIAGAAIAAAQIgiAAIgFgHIgCgHQgDAEgFAFQgDAEgGACQgHACgIAAQgNAAgIgHgAgMAHQgIAEAAAIQAAAGADACQADADAGAAQAIAAAEgFQAGgHAAgJIAAgIQgNACgJAEg");
	this.shape_24.setTransform(-131.55,40.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAGAwIAAgRIAFAAIADgBQABgBAAgEIAAgjQAAgJgDgEQgDgEgHAAQgHAAgEAGQgFAGAAAOIAAAaQAAAEABABIADABIAFAAIAAARIgyAAIAAgRIAHAAIACgBIABgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAIgHAAIAAgRIASAAIANgBIAKgBIAAARQAEgJAIgEQAHgFALAAQAPAAAHAJQAIAJAAASIAAAkQAAAEABABIADABIAGAAIAAARg");
	this.shape_25.setTransform(-14.425,15.875);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgaArQgLgGgGgLQgHgLAAgPQAAgNAHgMQAGgKAMgGQALgHAOAAQAQAAALAHQALAGAGAKQAGAMABANQgBAPgGALQgGALgMAGQgLAGgPAAQgPAAgLgGgAgOgXQgEAGAAAQIAAACQAAARAEAGQAFAIAJAAQAKAAAFgIQAEgGAAgRIAAgCQAAgQgEgGQgFgIgKABIAAAAQgJAAgFAHg");
	this.shape_26.setTransform(-25.675,16);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgWAuQgKgCgHgCIAAgZIAWAAIAAAPIAGABIAJABQAGAAAEgCQAEgDAAgFQAAgGgFgDIgOgEQgIgBgHgDQgIgDgFgFQgEgFgBgLQABgOAKgIQALgJATAAQAMAAAJACIAPAGIAAAXIgVAAIAAgNIgGgCIgHAAQgGAAgEACQgEADAAAFQAAADADACQACACAFACIAJACIAQAEQAHADAFAFQAFAFAAALQAAAPgLAJQgLAIgUAAQgMAAgJgDg");
	this.shape_27.setTransform(-35.425,16);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgsAwIAAgRIAHAAIACgBQABgBAAgEIAAguIAAgFQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAgRIATAAIAOgBIAJgBIAAAUQACgLAHgFQAFgFAKAAQAKAAAGAHQAHAHAAAMQAAAKgFAGQgGAFgJAAQgGAAgEgDQgEgEgBgGQAAgEADgDQACgEAEgCIgDgBIgCAAQgJAAgEAHQgDAHAAANIAAAZQAAAEABABIABABIAIAAIAAARg");
	this.shape_28.setTransform(-44.4,15.875);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgYArQgLgHgGgLQgGgLAAgOQAAgNAGgMQAGgKALgGQAMgHAOAAQAXAAAMANQALAOAAAWIAAAFIg/AAQAAAMAHAGQAFAHALAAQAJAAAFgFQAGgEADgHIAQAJQgDAHgGAGQgFAFgJAEQgJADgMAAQgPAAgMgGgAASgIQAAgMgFgGQgEgFgHAAQgIAAgEAFQgFAGAAAMIAhAAIAAAAg");
	this.shape_29.setTransform(-54.25,16);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("Ag3BAIAAgRIAHAAIADgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgBAAgBIAAhPQAAgBgBgBQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAgRIATAAIANgBIAJgBIAAATQAFgJAHgGQAHgFAMAAQAMAAAJAHQAIAFAGALQAEALAAAPQAAAOgFALQgFALgJAGQgJAGgNAAQgLAAgGgFQgIgEgDgJIAAAaIAAAEIAEABIAHAAIAAARgAgIgkQgFAGAAAOIAAADQAAAOAFAHQAFAHAHAAQAKAAAEgHQAFgHABgOIAAgDQgBgOgFgGQgEgHgKAAQgHAAgFAHg");
	this.shape_30.setTransform(-65.3,17.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgZAKIAAgTIAzAAIAAATg");
	this.shape_31.setTransform(-73.95,16);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAGAwIAAgRIAFAAIADgBQABgBAAgEIAAgjQAAgJgDgEQgDgEgHAAQgHAAgEAGQgFAGAAAOIAAAaQAAAEABABIADABIAFAAIAAARIgyAAIAAgRIAHAAIACgBIABgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAIgHAAIAAgRIASAAIANgBIAKgBIAAARQAEgJAIgEQAHgFALAAQAPAAAHAJQAIAJAAASIAAAkQAAAEABABIADABIAGAAIAAARg");
	this.shape_32.setTransform(-82.625,15.875);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgZBCIAAgQIAHAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAgtIgBgGQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgGAAIAAgRIATAAIAMgBIAKgBIAABHQAAABAAABQAAAAAAABQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAHAAIAAAQgAgMglQgFgEAAgIQAAgHAFgFQAFgEAHAAQAIAAAFAEQAEAFABAHQgBAIgEAEQgFAFgIAAQgHAAgFgFg");
	this.shape_33.setTransform(-91.375,14);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgYArQgMgHgFgLQgGgLAAgOQAAgNAGgMQAHgKALgGQALgHAOAAQAWAAANANQALAOAAAWIAAAFIg/AAQAAAMAHAGQAFAHALAAQAJAAAFgFQAGgEADgHIAQAJQgDAHgFAGQgGAFgJAEQgJADgMAAQgPAAgMgGgAASgIQgBgMgEgGQgEgFgHAAQgIAAgEAFQgEAGgBAMIAhAAIAAAAg");
	this.shape_34.setTransform(-103.85,16);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgcBBIAAgRIAHAAIADgBQAAAAAAgFIAAg0IgLAAIAAgQIALAAIAAgFQAAgMADgHQAEgIAHgCQAGgEAMAAIAKACIAGACIAAAQIgDgBIgDAAIgIABQgDACgBAEQgBAEAAAIIAQAAIAAAQIgPAAIAAA0QAAAFABAAIADABIAIAAIAAARg");
	this.shape_35.setTransform(-112,14.15);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgqAqQgIgGAAgMQAAgMAJgGQAIgHANgDQAOgEAQgDIAAgFQAAgIgFgEQgEgDgHAAIgGAAIgEABIACAEIAAAFQAAAGgFAEQgEAEgHAAQgIAAgEgEQgFgEAAgIQAAgJAGgFQAFgGALgDQAKgCANAAQAXAAAKAIQAKAHAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAIAGAAIAAAQIgiAAIgFgGIgCgIQgDAEgEAFQgEAEgGACQgHACgIAAQgNAAgHgHgAgMAHQgIAEAAAIQAAAGADACQADAEAGAAQAIgBAEgGQAFgFABgLIAAgHQgNACgJAEg");
	this.shape_36.setTransform(-120.5,16);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgbA/QgMgDgJgEIAAgfIAZAAIAAATQAEACAGABIAMABQAIAAAFgEQAFgEABgHQAAgGgEgDQgDgEgGgCIgPgEQgMgDgJgEQgIgFgFgGQgFgHAAgMQAAgTAOgLQANgLAYgBQANAAALADQAKACAJAEIAAAfIgZAAIAAgTIgIgBIgJgBQgKAAgFAEQgGAEAAAHQAAAGADADQADADAGACIAPAEQALACAJAFQAJAEAGAGQAFAHABANQAAAMgGAKQgGAJgMAGQgLAFgRAAQgNAAgMgDg");
	this.shape_37.setTransform(-131.425,14.325);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD3type, new cjs.Rectangle(-139,0,150,76.3), null);


(lib.HEAD2type = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANQgFgFAAgIQAAgHAFgEQAFgGAHAAQAIAAAFAGQAFAEAAAHQAAAIgFAFQgFAEgIABQgHgBgFgEg");
	this.shape.setTransform(7.575,43.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag3BAIAAgRIAHAAIACAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAhQQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAAAgBAAIgIAAIAAgRIATAAIAOgBIAKgBIAAATQADgJAIgGQAHgFALAAQANAAAJAGQAJAHAEAKQAFALABAPQgBAOgFALQgFALgJAGQgJAGgNAAQgLAAgHgFQgGgEgEgJIAAAaIAAAFIADAAIAHAAIAAARgAgIgkQgFAGAAAPIAAACQAAAOAFAHQAFAHAHgBQAJABAGgHQAEgHAAgOIAAgCQAAgPgEgGQgGgHgJAAQgHAAgFAHg");
	this.shape_1.setTransform(-0.45,41.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgmAnQgHgJAAgSIAAglQAAAAAAgBQAAgBAAAAQgBgBAAAAQAAgBAAAAIgDgBIgHAAIAAgRIAqAAIAAA7QAAAIAEAEQADAEAGAAQAHAAAEgGQAEgGAAgMIAAgdQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBgBAAIgCgBIgIAAIAAgRIArAAIAABFIAAAFQABAAAAABQAAAAABAAQAAAAAAAAQABAAAAAAIAIAAIAAARIgUAAIgNAAIgKACIAAgQQgEAIgIAEQgGAEgLAAIgBABQgOAAgIgJg");
	this.shape_2.setTransform(-11.775,40.2513);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAFBAIAAgQIAFAAIACgCIgBgDIgLgUIgNANIAAAFIABAGIADABIAFAAIAAAQIgyAAIAAgQIAHAAIACgBQABgBAAgFIAAhPQAAgEgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAAAAAAAIgIAAIAAgRIAUAAIANgBIAJgBIAABQIAZgXQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAgBAAIgJAAIAAgRIA0AAIAAARIgIAAIgEABIgEADIgQAMIAYAmIADAEIAEABIAEAAIAAAQg");
	this.shape_3.setTransform(-23,38.35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AghAkQgOgMAAgYQAAgWAOgNQAOgMAXgBQAVAAALAJQALAIABAPQAAAJgGAHQgFAEgJABQgIgBgEgEQgEgDAAgGQgBgHAEgDQAEgFAFgBQgCgDgEgBQgEgCgGAAQgKAAgHAHQgFAHAAAPIAAACQgBAQAGAHQAFAHALAAQAIAAAHgEQAFgEADgIIARAJQgFALgKAIQgKAHgSAAQgXAAgOgNg");
	this.shape_4.setTransform(-33.4,40.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYArQgMgGgFgLQgGgLAAgPQAAgOAGgLQAGgLALgGQAMgGANAAQAYAAAMANQALANAAAXIAAAFIg/AAQAAAMAHAGQAFAHALgBQAJABAFgFQAHgEACgHIAQAJQgDAHgGAGQgFAFgJAEQgJADgMAAQgQAAgLgGgAASgIQAAgNgFgFQgDgFgJAAQgHAAgEAFQgEAGgBAMIAhAAIAAAAg");
	this.shape_5.setTransform(-43.35,40.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAGBAIAAgQIAGAAIADgBIAAgGIAAgkQABgHgEgEQgDgFgHABQgGgBgFAHQgEAFAAANIAAAbIAAAGIAEABIAFAAIAAAQIgzAAIAAgQIAHAAIADgBQABgBAAgFIAAhPQAAgEgBgBQgBAAAAgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAgRIATAAIANgBIAKgBIAAAxQAFgIAHgEQAHgFALAAQAOAAAIAJQAHAJAAARIAAAlQAAAFABABIADABIAGAAIAAAQg");
	this.shape_6.setTransform(-54.05,38.35);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AghAkQgNgMAAgYQAAgWANgNQAOgMAXgBQAVAAALAJQALAIAAAPQAAAJgFAHQgFAEgJABQgIgBgEgEQgEgDgBgGQABgHADgDQADgFAHgBQgDgDgEgBQgEgCgGAAQgLAAgFAHQgHAHAAAPIAAACQABAQAFAHQAGAHAKAAQAJAAAFgEQAGgEADgIIAQAJQgDALgLAIQgKAHgSAAQgXAAgOgNg");
	this.shape_7.setTransform(-64.5,40.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgrAqQgHgGAAgLQABgNAHgGQAJgGAOgFQANgDAQgCIAAgGQAAgIgFgDQgDgEgJgBIgFABIgEABIABAEIABAFQAAAGgEAEQgFAEgHAAQgIAAgFgEQgEgEAAgIQAAgIAFgGQAHgFAKgDQAKgDAOAAQAVAAALAHQAKAIAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAIAGAAIAAAQIgiAAIgFgHIgCgHQgDAEgFAFQgDAEgGACQgHACgIAAQgNAAgIgHgAgMAHQgIAEAAAIQAAAGADACQADADAGAAQAIAAAEgFQAGgHAAgJIAAgIQgNACgJAEg");
	this.shape_8.setTransform(-78.9,40.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADACAGAAIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_9.setTransform(-91.875,38.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgYArQgMgGgFgLQgGgLAAgPQAAgOAGgLQAHgLAKgGQALgGAOAAQAXAAAMANQAMANAAAXIAAAFIg/AAQABAMAFAGQAHAHAKgBQAJABAGgFQAGgEACgHIAQAJQgDAHgGAGQgFAFgJAEQgIADgNAAQgPAAgMgGgAARgIQAAgNgDgFQgFgFgIAAQgGAAgFAFQgEAGgBAMIAgAAIAAAAg");
	this.shape_10.setTransform(-99.85,40.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgjBHQgLgCgGgEQgEgEAAgHQAAgGAFgFQAHgEALgCQgKgCgEgFQgFgGAAgHQAAgHAFgFQADgFAJgCQgHgEgDgGQgEgHABgIQAAgKAFgIQAGgHAKgEQALgEAOAAQAHAAAHACQAHABAGADQACgIAEgFQAFgEAHgBQAGABAEADQAEADABAGQgBAGgDADQgDADgFAAQgDABgDgCQgCgBgCgEIgCADIgCACQAFAEABAFQADAFAAAHQAAAKgGAHQgFAIgLACQgKAEgNAAIgLAAIgKgCIgEABQAAAAgBABQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAABQAAABAAAAQAAABABAAQAAABABAAQADABAGABIANAAIAOgBIANAAQARAAAGAIQAIAHAAAMQAAAQgPAKQgOAIgbAAQgTAAgMgCgAgeAtQgDADAAAEQABAFAGACQAHABAQAAQAQAAAIgCQAIgDAAgGQAAgFgDgCQgEgCgIAAIgjAAQgGACgDADgAgPgpQgDAEAAAIIAAAEQAAAIADAEQAEAEAIAAQAFAAAEgEQAEgEAAgJIAAgDQAAgJgDgDQgEgFgGAAQgIABgEAEg");
	this.shape_11.setTransform(-110.1,41.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgaArQgLgGgGgLQgHgLAAgPQAAgOAHgLQAGgLAMgGQALgGAOAAQAQAAALAGQALAGAGALQAGALABAOQgBAPgGALQgGALgMAGQgLAGgPAAQgPAAgLgGgAgOgYQgEAIAAAQIAAABQAAAQAEAIQAFAGAJABQAKgBAFgGQAEgIAAgQIAAgBQAAgQgEgIQgFgGgKAAIAAAAQgJAAgFAGg");
	this.shape_12.setTransform(-125.325,40.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADACAGAAIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_13.setTransform(-133.925,38.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgYArQgLgHgGgLQgGgLAAgOQAAgNAGgMQAGgKALgGQAMgHAOAAQAXAAAMANQALAOAAAWIAAAFIg/AAQAAAMAHAGQAFAHALAAQAJAAAFgFQAGgEADgHIAQAJQgDAHgGAGQgFAFgJAEQgJADgMAAQgPAAgMgGgAASgIQAAgMgFgGQgEgFgHAAQgIAAgEAFQgFAGAAAMIAhAAIAAAAg");
	this.shape_14.setTransform(-7.9,16);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAjAwIAAgRIAFAAIACgBQABgBAAgEIAAghQAAgKgDgEQgDgEgHAAQgHAAgEAGQgDAFAAAMIAAAcQAAAEABABIACABIAGAAIAAARIgwAAIAAgRIAFAAIACgBQABgBAAgEIAAgiQAAgJgDgEQgDgEgHAAQgHAAgEAGQgDAFAAAMIAAAcQAAAEABABIACABIAGAAIAAARIgzAAIAAgRIAHAAIADgBIAAgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgHAAIAAgRIATAAIANgBIAJgBIAAARQAFgIAHgFQAHgFAKAAQAMAAAFAFQAHAFADALQAEgKAHgGQAIgFAMAAQAPAAAIAJQAIAJAAATIAAAjIAAAFIADABIAHAAIAAARg");
	this.shape_15.setTransform(-21.375,15.875);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgZBCIAAgQIAHAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAgtIgBgGQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgGAAIAAgRIATAAIAMgBIAKgBIAABHQAAABAAABQAAAAAAABQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAHAAIAAAQgAgMglQgFgEAAgIQAAgHAFgFQAFgEAHAAQAIAAAFAEQAEAFABAHQgBAIgEAEQgFAFgIAAQgHAAgFgFg");
	this.shape_16.setTransform(-32.775,14);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADADAGAAIAEgBIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_17.setTransform(-38.875,14.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADADAGAAIAEgBIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_18.setTransform(-49.475,14.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgqAqQgIgGAAgMQAAgMAJgGQAIgHANgDQAOgEAQgDIAAgFQAAgIgFgEQgEgDgHAAIgGAAIgEABIACAEIAAAFQAAAGgFAEQgEAEgHAAQgIAAgEgEQgFgEAAgIQAAgJAGgFQAFgGALgDQAKgCANAAQAXAAAKAIQAKAHAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAAAAAIAHAAIAAAQIgiAAIgEgGIgDgIQgDAEgEAFQgEAEgGACQgHACgIAAQgNAAgHgHgAgMAHQgIAEAAAIQAAAGADACQADAEAFAAQAJgBAEgGQAFgFABgLIAAgHQgNACgJAEg");
	this.shape_19.setTransform(-57.6,16);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgYArQgLgHgGgLQgGgLAAgOQAAgNAGgMQAHgKALgGQALgHAOAAQAWAAANANQALAOAAAWIAAAFIg/AAQAAAMAGAGQAHAHAKAAQAJAAAFgFQAGgEADgHIAQAJQgDAHgFAGQgGAFgJAEQgIADgMAAQgQAAgMgGgAARgIQAAgMgEgGQgEgFgHAAQgIAAgEAFQgFAGAAAMIAgAAIAAAAg");
	this.shape_20.setTransform(-67.95,16);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgsAwIAAgRIAHAAIACgBQABgBAAgEIAAguIAAgFQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAgRIATAAIAOgBIAJgBIAAAUQACgLAHgFQAGgFAIAAQAMAAAFAHQAHAHAAAMQAAAKgGAGQgFAFgJAAQgGAAgEgDQgEgEgBgGQABgEACgDQACgEAEgCIgCgBIgEAAQgHAAgFAHQgDAHAAANIAAAZQAAAEABABIABABIAIAAIAAARg");
	this.shape_21.setTransform(-77.45,15.875);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgjBHQgLgCgGgEQgEgEAAgGQAAgHAFgFQAHgEALgCQgKgDgEgEQgFgFAAgIQAAgHAFgFQAEgFAIgCQgGgEgEgGQgEgGAAgJQABgKAFgHQAHgHAKgFQAKgEAOAAQAHAAAHACQAHABAGAEQACgJAEgFQAFgFAIAAQAGAAAEAEQADAEAAAFQAAAGgDADQgCAEgGgBQgEAAgCgBQgCgBgCgDIgCACIgCABQAEAFACAFQADAGAAAGQAAAKgFAHQgHAIgKACQgKAEgNAAIgLgBIgKgBIgEABQAAAAgBABQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAABQAAABAAAAQAAABABAAQAAABABAAQADABAGAAIANAAIAPAAIAMAAQAQAAAIAIQAHAHAAAMQAAARgPAJQgOAIgcAAQgSAAgMgCgAgeAtQgCADgBAEQAAAEAHACQAHACAQAAQAQAAAIgDQAIgDAAgGQAAgEgDgCQgDgCgKAAIgjAAQgFACgDADgAgPgpQgDAEAAAIIAAAEQAAAIADAEQAEAEAHAAQAHAAADgEQAEgEAAgIIAAgEQAAgJgDgDQgEgEgHgBQgHAAgEAFg");
	this.shape_22.setTransform(-87.35,17.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgrAqQgHgGAAgMQABgMAHgGQAJgHAOgDQANgEAPgDIAAgFQABgIgEgEQgFgDgIAAIgFAAIgEABIABAEIABAFQAAAGgFAEQgEAEgHAAQgIAAgFgEQgEgEAAgIQAAgJAFgFQAGgGAKgDQALgCAOAAQAWAAAKAIQAKAHAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAAAAAIAHAAIAAAQIgiAAIgEgGIgDgIQgCAEgGAFQgDAEgHACQgGACgHAAQgOAAgIgHgAgLAHQgJAEAAAIQAAAGADACQADAEAFAAQAJgBAFgGQAEgFAAgLIAAgHQgMACgIAEg");
	this.shape_23.setTransform(-102.45,16);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgWAuQgKgCgHgCIAAgZIAWAAIAAAPIAGABIAJABQAGAAAEgCQAEgDAAgFQAAgGgFgDIgOgEQgIgBgHgDQgIgDgFgFQgEgFgBgLQABgOAKgIQALgJATAAQAMAAAJACIAPAGIAAAXIgVAAIAAgNIgGgCIgHAAQgGAAgEACQgEADAAAFQAAADADACQACACAFACIAJACIAQAEQAHADAFAFQAFAFAAALQAAAPgLAJQgLAIgUAAQgMAAgJgDg");
	this.shape_24.setTransform(-116.375,16);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgDAbIgEgMIgEgPIgCgNIAAgNIAbAAIAAANQAAAGgCAHIgEAPIgEAMg");
	this.shape_25.setTransform(-122.55,10.75);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADADAGAAIAEgBIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_26.setTransform(-127.725,14.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgbA/IAAgRIAIAAQAAAAAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAgBAAgEIAAhQIAAgEIgDgBIgIAAIAAgRIA3AAIAAARIgIAAIgCABIgBAEIAABQQAAAEABABQAAAAAAABQAAAAABAAQAAAAABAAQAAAAAAAAIAIAAIAAARg");
	this.shape_27.setTransform(-133.8,14.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2type, new cjs.Rectangle(-139,0,155.4,52.2), null);


(lib.HEAD1atype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANQgFgFAAgIQAAgHAFgFQAFgEAHAAQAIAAAFAEQAFAFAAAHQAAAIgFAFQgFAEgIABQgHgBgFgEg");
	this.shape.setTransform(-29.125,67.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgvA6QgHgFAAgLQAAgIAEgFQAFgEAIAAQAGAAAEADQAEADABAFQABAFgDAGQAFgBAEgFQAEgEADgJIAAgBIghhEIgCgFIgDgBIgGAAIAAgQIA0AAIAAAQIgFAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAABAAAAIAAAEIAQAmIAPglQABgDgBgCQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgGAAIAAgQIAqAAIAAAQIgGAAIgEABIgDAFIgcBDQgFANgFAIQgFAJgHAEQgHAEgLAAQgNAAgIgGg");
	this.shape_1.setTransform(-36.925,66.025);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAGBAIAAgQIAGAAIADgBIAAgGIAAgjQABgJgEgDQgDgFgHABQgGAAgFAGQgEAFAAAOIAAAaIABAGIADABIAFAAIAAAQIgzAAIAAgQIAHAAIADgBQAAgCAAgEIAAhPQAAgEAAgBQgBAAAAgBQAAAAAAAAQgBAAAAAAQgBgBAAAAIgHAAIAAgQIATAAIANgBIAKgBIAAAyQAEgJAIgFQAHgDALAAQAOgBAIAKQAHAIAAARIAAAlQAAAEABACIADABIAGAAIAAAQg");
	this.shape_2.setTransform(-48.1,62.45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgPIAGgBQAGgBADgDQAEgCABgHIACgPIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADADAGgBIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_3.setTransform(-57.275,63);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgYBAIAAgQIAGAAIADgBQABgCAAgEIAAhPIgBgFQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAgBgBAAIgHAAIAAgQIATAAIANgBIAJgBIAABoQAAAEABACIADABIAGAAIAAAQg");
	this.shape_4.setTransform(-63.225,62.45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgrAqQgHgHAAgKQAAgNAJgHQAIgFANgFQAOgDAPgCIAAgGQABgIgEgDQgEgFgJAAIgFABIgEABIACAEIAAAEQAAAHgFAEQgEAEgHAAQgIAAgFgEQgEgEAAgIQAAgIAGgGQAGgFAJgDQALgDANAAQAWAAALAHQAKAIAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAAAAAIAHAAIAAAQIgiAAIgEgHIgDgIQgCAGgFADQgEAEgHADQgGACgHAAQgOAAgIgHgAgLAHQgJAEAAAJQAAAEADAEQADACAFAAQAJAAAFgFQAEgGAAgKIAAgIQgMACgIAEg");
	this.shape_5.setTransform(-71.3,64.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgYArQgMgHgFgKQgGgMAAgOQAAgNAGgMQAHgKAKgHQALgGAOAAQAXABAMANQAMAMAAAXIAAAFIg/AAQABAMAFAGQAHAGAKAAQAJABAGgFQAGgEACgHIAQAJQgDAIgGAFQgFAGgJADQgIADgNAAQgPAAgMgGgAARgHQAAgOgDgEQgFgGgIAAQgGAAgFAGQgEAFgBANIAgAAIAAAAg");
	this.shape_6.setTransform(-81.85,64.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAGBAIAAgQIAGAAIADgBIAAgGIAAgjQABgJgEgDQgDgFgHABQgGAAgFAGQgEAFAAAOIAAAaIAAAGIAEABIAFAAIAAAQIgzAAIAAgQIAHAAIADgBQABgCAAgEIAAhPQAAgEgBgBQgBAAAAgBQAAAAAAAAQgBAAAAAAQgBgBAAAAIgHAAIAAgQIATAAIANgBIAKgBIAAAyQAFgJAHgFQAHgDALAAQAOgBAIAKQAHAIAAARIAAAlQAAAEABACIADABIAGAAIAAAQg");
	this.shape_7.setTransform(-92.75,62.45);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgjA7QgKgGgFgLQgFgLAAgPQAAgOAGgKQAFgLAJgGQAJgHAMAAQAMAAAGAFQAHAEAEAIIAAgYIgBgFQAAgBAAAAQgBAAAAAAQAAgBgBAAQAAAAgBAAIgHAAIAAgQIATAAIAOgBIAJgBIAABoQAAAEABABIADABIAGAAIAAARIgmAAIAAgGIgBgLQgEAJgHAFQgHAFgMAAQgNAAgJgGgAgRgGQgFAGAAAPIAAADQAAAOAFAHQAFAHAJAAQAIAAAFgHQAFgHAAgOIAAgDQAAgPgFgGQgFgHgIABIgBAAQgIAAgFAGg");
	this.shape_8.setTransform(-108.825,62.575);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAGAwIAAgRIAFAAIADgBQABgBAAgEIAAgjQAAgJgDgEQgDgEgHAAQgHAAgEAGQgFAGAAAOIAAAaQAAAEABABIADABIAFAAIAAARIgyAAIAAgRIAHAAIACgBIABgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAIgHAAIAAgRIASAAIANgBIAKgBIAAARQAEgJAIgEQAHgFALAAQAPAAAHAJQAIAJAAASIAAAkQAAAEABABIADABIAGAAIAAARg");
	this.shape_9.setTransform(-120.425,64.075);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgrAqQgHgHAAgKQABgNAHgHQAJgFAOgFQANgDAQgCIAAgGQAAgIgFgDQgDgFgJAAIgFABIgEABIABAEIABAEQAAAHgEAEQgFAEgHAAQgIAAgFgEQgEgEAAgIQAAgIAFgGQAHgFAKgDQAKgDAOAAQAVAAALAHQAKAIAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAIAGAAIAAAQIgiAAIgFgHIgCgIQgDAGgFADQgDAEgGADQgHACgIAAQgNAAgIgHgAgMAHQgIAEAAAJQAAAEADAEQADACAGAAQAIAAAEgFQAGgGAAgKIAAgIQgNACgJAEg");
	this.shape_10.setTransform(-131.55,64.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgYArQgLgGgGgLQgGgLAAgPQAAgOAGgLQAHgLALgGQAKgGAPAAQAXAAALANQAMANAAAXIAAAFIg/AAQABAMAFAGQAHAHAKgBQAJABAGgFQAFgEADgHIAQAJQgDAHgFAGQgGAFgJAEQgIADgMAAQgQAAgMgGgAARgIQAAgNgDgFQgEgFgIAAQgIAAgEAFQgFAGAAAMIAgAAIAAAAg");
	this.shape_11.setTransform(3.05,40.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcBBIAAgQIAHAAIADgBQABgBAAgFIAAg0IgNAAIAAgRIANAAIAAgEQAAgMACgHQAEgIAHgCQAGgEALAAIALABIAGADIAAAQIgCgBIgEgBIgIACQgDACgBAEQgBAEAAAHIARAAIAAARIgQAAIAAA0QAAAFABABIADABIAIAAIAAAQg");
	this.shape_12.setTransform(-5.1,38.25);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgqAqQgIgGAAgLQAAgNAJgGQAIgGANgFQAOgDAPgCIAAgGQABgIgFgDQgEgEgHgBIgGABIgEABIACAEIAAAFQAAAGgFAEQgEAEgHAAQgIAAgEgEQgFgEAAgIQAAgIAGgGQAGgFAJgDQALgDANAAQAXAAAKAHQAKAIAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAAAAAIAHAAIAAAQIgiAAIgEgHIgDgHQgCAEgFAFQgEAEgHACQgGACgHAAQgOAAgHgHgAgMAHQgIAEAAAIQAAAGADACQADADAFAAQAJAAAFgFQAEgHAAgJIAAgIQgMACgJAEg");
	this.shape_13.setTransform(-13.6,40.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgWAuQgKgBgHgDIAAgZIAWAAIAAAPIAGABIAJABQAGAAAEgCQAEgEAAgEQAAgHgFgCIgOgEQgIgBgHgDQgIgDgFgEQgEgHgBgKQABgOAKgIQALgJATAAQAMABAJACIAPAEIAAAYIgVAAIAAgNIgGgCIgHgBQgGAAgEADQgEADAAAEQAAAFADABQACACAFABIAJADIAQAEQAHADAFAFQAFAGAAAKQAAAPgLAJQgLAIgUAAQgMAAgJgDg");
	this.shape_14.setTransform(-23.425,40.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgYArQgMgGgFgLQgGgLAAgPQAAgOAGgLQAGgLALgGQAMgGANAAQAYAAALANQAMANAAAXIAAAFIg/AAQAAAMAHAGQAFAHALgBQAJABAFgFQAHgEACgHIAQAJQgDAHgGAGQgFAFgJAEQgJADgMAAQgPAAgMgGgAASgIQAAgNgFgFQgDgFgJAAQgGAAgFAFQgEAGgBAMIAhAAIAAAAg");
	this.shape_15.setTransform(-37.4,40.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgGA7QgIgGgEgLIgGAVIgVAAIAAgFIAAgKIAAgRIAAhGIAAgFQgBgBAAAAQAAAAgBAAQAAgBAAAAQgBAAAAAAIgIAAIAAgQIAUAAIANgBIAJgBIAAAzQAEgJAIgFQAHgFAMAAQALAAAKAHQAJAGAEAKQAFAKAAAPQAAAPgFALQgFALgJAGQgJAGgNAAQgNAAgIgGgAgIgGQgFAGgBAPIAAADQABAOAFAHQAFAHAHAAQAJAAAGgHQAEgHAAgOIAAgDQAAgPgEgGQgGgHgJABIgBAAQgGAAgFAGg");
	this.shape_16.setTransform(-48.4,38.475);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgaArQgLgGgGgLQgHgLAAgPQAAgOAHgLQAGgLAMgGQALgGAOAAQAQAAALAGQALAGAGALQAGALABAOQgBAPgGALQgGALgMAGQgLAGgPAAQgPAAgLgGgAgOgYQgEAIAAAQIAAABQAAAQAEAIQAFAGAJABQAKgBAFgGQAEgIAAgQIAAgBQAAgQgEgIQgFgGgKAAIAAAAQgJAAgFAGg");
	this.shape_17.setTransform(-63.975,40.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADACAGAAIAEAAIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_18.setTransform(-72.775,38.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgvA6QgHgFAAgLQAAgIAEgFQAFgEAIAAQAGAAAEADQAEADABAFQABAFgDAGQAFgBAEgFQAEgEADgJIAAgBIghhEIgCgFIgDgBIgGAAIAAgQIA0AAIAAAQIgFAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAABAAAAIAAAEIAQAmIAPglQABgDgBgCQAAgBgBAAQAAAAAAAAQgBgBgBAAQAAAAgBAAIgGAAIAAgQIAqAAIAAAQIgGAAIgEABIgDAFIgcBDQgFANgFAIQgFAJgHAEQgHAEgLAAQgNAAgIgGg");
	this.shape_19.setTransform(-85.875,41.925);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgYBAIAAgQIAGAAIADgBQABgBAAgFIAAhPIgBgFQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAAAgBAAIgHAAIAAgRIATAAIANgBIAJgBIAABoQAAAFABABIADABIAGAAIAAAQg");
	this.shape_20.setTransform(-94.125,38.35);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgZBCIAAgQIAHAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAgtIgBgGQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgGAAIAAgRIATAAIAMgBIAKgBIAABHQAAABAAABQAAAAAAABQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAHAAIAAAQgAgMglQgFgFAAgHQAAgHAFgEQAFgFAHgBQAIABAFAFQAEAEABAHQgBAHgEAFQgFAEgIABQgHgBgFgEg");
	this.shape_21.setTransform(-99.825,38.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAjAwIAAgRIAFAAIACgBQABgBAAgEIAAghQAAgKgDgEQgDgEgHAAQgHAAgEAGQgDAFAAAMIAAAcQAAAEABABIACABIAGAAIAAARIgwAAIAAgRIAFAAIACgBQABgBAAgEIAAgiQAAgJgDgEQgDgEgHAAQgHAAgEAGQgDAFAAAMIAAAcQAAAEABABIACABIAGAAIAAARIgzAAIAAgRIAHAAIADgBIAAgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgHAAIAAgRIATAAIANgBIAJgBIAAARQAFgIAHgFQAHgFAKAAQAMAAAFAFQAHAFADALQAEgKAHgGQAIgFAMAAQAPAAAIAJQAIAJAAATIAAAjIAAAFIADABIAHAAIAAARg");
	this.shape_22.setTransform(-111.275,39.975);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgrAqQgHgGAAgLQABgNAHgGQAJgGAOgFQANgDAQgCIAAgGQAAgIgFgDQgDgEgJgBIgFABIgEABIABAEIABAFQAAAGgEAEQgFAEgHAAQgIAAgFgEQgEgEAAgIQAAgIAFgGQAHgFAKgDQAKgDAOAAQAVAAALAHQAKAIAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAIAGAAIAAAQIgiAAIgFgHIgCgHQgDAEgFAFQgDAEgGACQgHACgIAAQgNAAgIgHgAgMAHQgIAEAAAIQAAAGADACQADADAGAAQAIAAAEgFQAGgHAAgJIAAgIQgNACgJAEg");
	this.shape_23.setTransform(-125.25,40.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgdBBIAAgQIAIAAIACgBQABgBAAgFIAAg0IgMAAIAAgRIAMAAIAAgEQAAgMAEgHQADgIAHgCQAGgEAMAAIAKABIAHADIAAAQIgEgBIgDgBIgIACQgDACgBAEQgBAEABAHIAPAAIAAARIgPAAIAAA0QAAAFABABIACABIAJAAIAAAQg");
	this.shape_24.setTransform(-133.75,38.25);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgsAwIAAgRIAHAAIACgBQABgBAAgEIAAguIAAgFQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAgRIATAAIAOgBIAJgBIAAAUQACgLAHgFQAFgFAKAAQAKAAAGAHQAHAHAAAMQAAAKgFAGQgGAFgJAAQgGAAgEgDQgEgEgBgGQAAgEADgDQACgEAEgCIgDgBIgCAAQgJAAgEAHQgDAHAAANIAAAZQAAAEABABIABABIAIAAIAAARg");
	this.shape_25.setTransform(-10.2,15.875);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgmAnQgHgJAAgSIAAglQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBAAAAIgDgBIgHAAIAAgRIAqAAIAAA7QAAAIAEAEQADAEAGAAQAHAAAEgGQAEgGAAgMIAAgdQAAAAAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAIgCgBIgIAAIAAgRIArAAIAABFIAAAFQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAAAIAIAAIAAARIgUAAIgNAAIgKACIAAgQQgEAIgIAEQgGAEgLAAIgBABQgOAAgIgJg");
	this.shape_26.setTransform(-20.725,16.1513);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgaArQgLgGgGgLQgHgLAAgPQAAgNAHgMQAGgKAMgGQALgHAOAAQAQAAALAHQALAGAGAKQAGAMABANQgBAPgGALQgGALgMAGQgLAGgPAAQgPAAgLgGgAgOgXQgEAGAAAQIAAACQAAARAEAGQAFAIAJAAQAKAAAFgIQAEgGAAgRIAAgCQAAgQgEgGQgFgIgKABIAAAAQgJAAgFAHg");
	this.shape_27.setTransform(-31.825,16);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgvA6QgHgFAAgLQAAgIAEgFQAFgEAIAAQAGAAAEADQAEADABAFQABAFgDAGQAFgBAEgFQAEgEADgJIAAgBIghhEIgCgFIgDgBIgGAAIAAgQIA0AAIAAAQIgFAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAIAQAmIAPglQABgDgBgCQAAgBgBAAQAAAAAAAAQgBgBgBAAQAAAAgBAAIgGAAIAAgQIAqAAIAAAQIgGAAIgEABIgDAFIgcBDQgFANgFAIQgFAJgHAEQgHAEgLAAQgNAAgIgGg");
	this.shape_28.setTransform(-42.725,17.825);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgLA2QgHgHAAgRIAAguIgMAAIAAgQIAGAAQAGgBADgDQAEgDABgFIACgQIAUAAIAAAbIARAAIAAARIgRAAIAAAuQAAAHACADQADADAGAAIAEgBIAEgBIAAARIgIACIgKABQgQAAgIgHg");
	this.shape_29.setTransform(-56.025,14.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAGAwIAAgRIAFAAIADgBQABgBAAgEIAAgjQAAgJgDgEQgDgEgHAAQgHAAgEAGQgFAGAAAOIAAAaQAAAEABABIADABIAFAAIAAARIgyAAIAAgRIAHAAIACgBIABgFIAAguQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAIgHAAIAAgRIASAAIANgBIAKgBIAAARQAEgJAIgEQAHgFALAAQAPAAAHAJQAIAJAAASIAAAkQAAAEABABIADABIAGAAIAAARg");
	this.shape_30.setTransform(-64.825,15.875);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgqAqQgIgGAAgMQAAgMAJgGQAIgHANgDQAOgEAQgDIAAgFQAAgIgFgEQgEgDgHAAIgGAAIgEABIACAEIAAAFQAAAGgFAEQgEAEgHAAQgIAAgEgEQgFgEAAgIQAAgJAGgFQAFgGALgDQAKgCANAAQAXAAAKAIQAKAHAAARIAAAoIABAEQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAIAGAAIAAAQIgiAAIgFgGIgCgIQgDAEgEAFQgEAEgGACQgHACgIAAQgNAAgHgHgAgMAHQgIAEAAAIQAAAGADACQADAEAGAAQAIgBAEgGQAFgFABgLIAAgHQgNACgJAEg");
	this.shape_31.setTransform(-75.95,16);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAUAvIgTgzIgTAzIgXAAIgahHIgDgEIgDgBIgFAAIAAgRIAzAAIAAARIgFAAQgBAAAAAAQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAABABIADAJIAFAOIAFAOIAFgOIAFgOIADgJQABgBAAAAQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAQgBgBAAAAQgBAAAAAAQgBAAAAAAIgEAAIAAgRIAuAAIAAARIgEAAQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABIAEAJIAFAOIAGAOIAFgOIAFgOIADgJQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgFAAIAAgRIAmAAIAAARIgFAAIgDABIgDAEIgZBHg");
	this.shape_32.setTransform(-89.325,16.075);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgmAnQgHgJAAgSIAAglQAAAAAAgBQAAgBAAAAQgBgBAAAAQAAgBAAAAIgDgBIgHAAIAAgRIAqAAIAAA7QAAAIAEAEQADAEAGAAQAHAAAEgGQAEgGAAgMIAAgdQAAAAAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAIgCgBIgIAAIAAgRIArAAIAABFIAAAFQABAAAAABQAAAAABAAQAAAAAAAAQABAAAAAAIAIAAIAAARIgUAAIgNAAIgKACIAAgQQgEAIgIAEQgGAEgLAAIgBABQgOAAgIgJg");
	this.shape_33.setTransform(-107.525,16.1513);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgaArQgLgGgGgLQgHgLAAgPQAAgNAHgMQAGgKAMgGQALgHAOAAQAQAAALAHQALAGAGAKQAGAMABANQgBAPgGALQgGALgMAGQgLAGgPAAQgPAAgLgGgAgOgXQgEAGAAAQIAAACQAAARAEAGQAFAIAJAAQAKAAAFgIQAEgGAAgRIAAgCQAAgQgEgGQgFgIgKABIAAAAQgJAAgFAHg");
	this.shape_34.setTransform(-118.625,16);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgcA/IAAgRIAJAAQAAAAABAAQAAAAABAAQAAAAAAAAQABgBAAAAQABgBAAgEIAAgeIghgyIgEgEQAAAAgBgBQAAAAgBAAQAAAAgBAAQgBAAAAAAIgGAAIAAgRIA8AAIAAARIgHAAQgBAAAAAAQgBAAAAAAQgBAAAAABQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAABABABIARAeIATggQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgKAAIAAgRIAzAAIAAARIgIAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBABAAAAIgEAEIgfAxIAAAfQAAAEABABQAAAAAAABQAAAAABAAQAAAAABAAQAAAAABAAIAJAAIAAARg");
	this.shape_35.setTransform(-130.425,14.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1atype, new cjs.Rectangle(-139,0,151,100.4), null);


(lib.CO_v_white = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgyA1QgXgVAAggQAAgeAWgVQAVgWAeAAQAfAAAWAXQAVAVgBAdQAAAfgVAVQgVAVgfABQgdgBgVgUgAgvgvQgTAUAAAbQAAAcATAUQAUATAbAAQAcAAATgTQATgTABgdQAAgbgTgTQgUgUgcAAQgbAAgUATgAASAuQgCgDgCgKIgCgPQgCgIgFgEQgEgCgJAAIgGAAIAAAqIgRAAIAAhcIAfAAQAPAAAFACQAPAFAAARQAAAQgTAGQAGABADAEQADAEABAJQAEAVADAHgAgOgIIAOAAQATAAAAgNQAAgIgHgDQgDgBgMAAIgLAAg");
	this.shape.setTransform(133.8251,86.6356,0.4949,0.4949);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACmLBQgKgEgNACQgPADgIAAQAAgDgKgCIgOgBQgRABgHgCQAAgDgSACQgjgBAAgBIgUgCIgTgBQgLgCgHAAQAAgBgQABQgRABAAgDIgOgEQgJgDAAAHQgDAAgFgDQgEgDgDAAQAAAFgJgBIgNgDQgNgCgLACQgRACgYgKIgJgEQgEgCgEABQgCAAgIgEQgIgFAAgBIgMABIgMABQgIACgFgBQgDAAgDgEQgEgFgDAAIAAAEQgEAAgEgCQgGgDAAgEQgCAGgBAAQAAgDgIgDQgIgCgFAAIgBABQgBAAAAAAQAAgBAAABQgBAAAAAAQAAAAAAAAQgDABgFgEQgEgDgEABQgEABAAgDIgIgGQgHgFAAAEQgCABgMgFQgNgGAAgCIgTgJQgBABAAAAQgBABAAAAQAAABAAAAQAAAAABAAIgEABIAAAAIgEAAIAEAAQABADgQgGQgCgDgFAAQAAgGgDgCIAAAGIgFgDQgGgDAAADIgIgIIgOgCQAAgCgNgGQgNgGAAgCQgKgEgDgKQgBgDgJgBIgOgCQgTgKgBABQgEgCgCABIABgDQgCAAgQgKQgLgIgDgIIgLgDQgCgCgBgDQgBgBgFAAIgDgHIgCgHQgEgBgCACQgCACgCAAQgBgLgTAAQgPAAAAgBIgNgBIgMgBQgSAFgHgCQAAgBgYgBQgaAAgDgBQAAACgJgCIgNgDQgLAFgDgEQgNgEgCABQAAABgGAAIgHgBIgJgCQgDgCgFAAIgOABQAAABgOgEQgGAAgFgHQgCgBgNABIgMAAQgEABgcgDQgcgDAAgBIgJgDQgGgCgDAAIgXgDQgDgEgbgGQgagHAAgBQgCAAgEgCQgDgDgDABQgOACAAgEQgJgEgPAAQAAgFgKgBQgNgBgBgBQgLgFgFgDQgHgGgQgDIgYgEQgDgDgDABIgHACIgGgDIgHgCQAAgEgJgBQgJgBgCgFIAJgCQgBgEgMgEQgMgFAAACIgSgJQgFAAgIgGIgLgHIgMgEIgNgBIAVAVQAAADAHAGQAHAGABAEQADACAGAHQAGAGAEABQAKADAEAHQADAAAHADIAKAFIAHAEQAHAEAAACQAFAAAHADQAGADAEAAIAEACQABAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAFABAGAGQACAFAWAEQAVAEAAADIAYAKQADAAAGADQAFAEAEAAQACgBATAGIATAFQADAAAIAEQAGAEAEgBQAEgBAJAEQAKAEADAAQAAgBARAEIAVAFQAEAAAJACIANAEQAAABAOACIAQABQAAAFBNAGQADADAjADQAiAEAAABQBPAIAAgBQADgBAkAEQAiAEAAgBQAIgBAAABQgGAAgMAGQgOAGgFABIgMgCQgLgCAAADIgGABQgDABgDgBQAAAGgUABQgTABAAgDQgQACAAgCIgGACQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgLgBQgDgBgDgGQgDAAgCADQgBABgGAAIgNgBQgXgCgDgCIgFgFIgJABIgMgEQgKgDAAADQgGAAgKgCQgCgGgEABIgJAFQgFADgFgCQAAgCgLgCQgKgCgEABQAAACgWgEIgbgFQAAgCgOgBQgPgBgBgEQgHAAgLgDQgMgDgGgBQgCgCgNgBQgNgBAAgCQgGAAgJgCIgOgEIgNgEQgNgEAAgBIgNgCQgKgCAAgBQgFAAgGgCIgLgFIgDgBIgCgBQgLAAAQALQACACAGACQAGACADADIAKADQAAABAFABIAHABQAAACASADQAAADAaAEQAZAFABAHIgKACQAAgDgXgDQgZgDgCgDIgagHQgVgHAAgDIgZgIQgUgIAAgBQgIgCgKgEQgNgGgFgGIgIgFQgJgEAAABQgCAAgHgFQgIgFAAgCQgKAAgPgHQgRgJgCgJQgPgKgGAAIgIgIQgFgFgDgCIgGgIIgJgFQgGgCAAgDQgGgEgHgIQgHgJgDgGQgDgBgEgHQgFgHAAgCQgDAAgDgJQgDgKgEAAQAAgEgDgGQgEgFAAgFQgBAAgFgTIgGgYIgHgkQgHgjAFAAIgFgVQgBAAgBgLIgBgNQgDAAAAgNQgBgOgCAAIgJhUIAAggQAAgcACAAIgCgjQgBggAEAAIgCgxQgCgsAFgDQAAgEAKgaQALgZgBgEQAIAAAHgOQAHgPAGgCQACgBADgFQACgGADgCQAAgFAGgGQAHgGAHgBIgDgEQAAAAAAgBQAAAAAAgBQAAAAABgBQABAAABAAIAEgCQAAAAAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAHgHIAKgHIAFAAIAEgCQALgIgHAAQgCgGAFgEQAFgFAFAAIAIgDIAIgCQAKgFAKgJIAQgRQAGgGADgBIAFgDIACgEQACAAAOgLQAAgCANgFQANgGAAgEQAEAAAJgGQAJgHABgDIAOgJQAHgEAIAAQAAgBAGgDIAFgCIAJABQAGACABgDIAXgEQAOgEAAgJQADgBACgEIADgEQABgCAEgDQAEgCABgDIgBAAQAAgFAHACIAJACIARgCIAIgFIAKgEIAJgFQAHgEACAAIAEgCQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBQAFAAAFgCQAHgCAAgDQgHAAAHgHQAHgGAEgBIANgHQAFAAAGgDQAAgDAHgCQAGgCAAgEQAGAAAAADQADAAAEgCIAHgCIAKACQAGABACgDIAOgGQAJgGAEAAQAAgBALgEQAKgDAEAAQAAgCAHAAQAHAAAAgBQAJAAACgCQACgBAAgHIAFgDIAEgEIAJACIgBAFIAEgCIADgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAfAAAHgDQAEgBAGACIAKACQALgGgFAAQgCgJASgGQATgGAAAFQAMgIAZAAQACgDAJAAQAJABACgEIAXgEQAUgEAAgBIABABIAVgFQAWgFADAAQAVAAAAgEIAIgCQAHgBAAgBIAggHIAvgHQAOAAAggFQAggGAQAAQAAgFBQAAQAAABAGACQAHACAAACQgIAFgXgCIgQABIgRABQgJAAgRADQgSADgJAAQAAgChXATQAAAFArgFIAxgGIAugGIAbgDQARgCAJACQAUgDABAKQASAAAAABIAHABQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAABIgIAAQAAADg1ACQAAABgRADIgUACIgTAAQgSAAAAADIgwAHIgSACIgUACQAAADgMACIgQACQgIgBgPAEQgQAFgHAAIgMACQgMACAAACQgEAAgGAEQgHAEgDAAIgJAAIgJgBQAAADgQACQgPADgBADQgCAKgMADQgOABgIACQAAADgTAHQgHAKgHAEQACAIAiABQAfABAHgEQADgCAagEQAXgDAAgCIAMgCIAMgDQAAgBAGABIAHABQARgEAJAAQAAgBAcgDIAcgFQAfgDAAgBIAVgCIAWgCQAAgCAmgCQAngDAFABIApgDQAkgDAAACQAMgCAYACIAcgBQASgBALACQAAADAJACQAJACAAgCIAQABQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQADgBAKACQALADAAACQgEACgWABIgVAAIgmABQgCADgWAFQgVAFAAACIgQgBQgPgBAAACIgWAAQAAAFgZABIgegBQAAADglABQglACgBAIQARADAXgDIAngGQAAACAkgCQAjgBAAABQAFAAALgDQAEAAAEACQAFADAEAAIAQgBQAJABgEAGQgFAIghACIghACQhWAFAAADIgTACQgTACAAgCQgGgBgJADQgLADgDAAIgRACQgCACgGAAIgKgBQgGABgJAGQgIAGgGABQAAAFgdAEQAAABgHACQgIADAAABIgTADIgKACQgLACgBACQgRAAgMAMQgGABgKAFQgKAGgGABQAAgBgNAFIgPAFQAAgCgFABQgEAAgCACIAEABQgBADgMACIAAgEIgOAFQAKAIgUAEQgWAEAAACIgTAGQgNAFgGABQAAgCgvAQIgRAGQgRAGgCADQgTAAgDAEQgFAAgHAFQgGAEgFgBQgGAAgFAFQgGAGgFAAQgCgDgFACIgIAEIgKAFQgFACgFABQgBABgLADIgNACQAAAFgJACIgOADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABgBAAQgCADgEAAQgEAAgCADQgDAEgDACIgDADQgBABgEAAQgBgCgGgBQgFgCAAAEQgFAAgBAFQgDAHgCABQAAADgJAAQgOAJgCAAQAAACgMACQgLADAAAEIgMAGQgIAFAAADQgFABgFAEQgGAEgEABIgGADQgEACgCAAQgRAJgCAAQgEAEgFAAIgQAMQAAADgIAFQgIAEAAADQgGAEgOACQgBAEgEACQgFACgBABQgFAAgEAIQgEAHgDABQgEABgIAHQgIAFgDAAQAAAFgHAEQgIADgBAFQgSALgLANQgEAAgGAGIgIAKQgGAIgFADQgBADgFACQgFACAAAEQgCAAgHAJQgGAIgDAAIABADQgFAAgFAHIgHAKIgIAIIgHAJQgDAHgLANQgJALgBAJQADAAAGgHQAIgJACgBQAGgKAEAAQAAgDAHgFQAGgFABgCQgCAAAKgJIALgJQAGAAAEgJQAEgJADAAIAGgGQAGgFACAAQACgEAHgEIALgHQAAgCAEgFIAHgFIAVgPQADgHAUgGQABgDAJgEQAIgEAAgCQgBgEAGgCIAIgDIAWgOQAEAAAFgFQAGgEADAAIAhgUQAGgCARgIQATgJAAgDQAHgBACgDQAEAAABgDQACgDACAAQAHgCABgCIAIgEQAFgDAAgBIAGgDIAFgDQAAADAMgFQALgFACgDIAHgCQAFgCAAgBQAHgBAOgJQANgIAIAAQADgEAJgCQAIgCADgDQAEAAAGgEQAFgEAEAAQAFgFAIAAIAIgIIAHAAIAGgBIASgHQAAgBAGgCIAHgBQADgEAKgBIALgCQABgCAHgDQAIgEAAgCIAQgDQAAgCALgDQAJgCAEAAQAAgGANgBQANgBACgCIApgMQAhgJAAgFQAEAAASgFQARgGAAgBQAFAAAJgCQAKgCAAgEQAygGAAgEQALAAAQgFQATgHAHgBQAAgBAYgFIAbgFQAAgBAdgGIAhgHQAIgCANgBQAAgBAFgBIAHgBIATgEQAMgDAHABQAAAIgWAFIgeAFQgQAEAAACQgDAAgHAFQgHAFgFgBQAAAAgBgBQAAAAAAAAQAAAAgBAAQgBAAAAAAQAAACgZAIIgHAFQgEADgEAAQgDAEgGABIgMABIgbAJQgQAFgMACIgEADQgEADAAACQgEAAAFAEQAFADAAgEIAMgBQAKgBAAgCQAfAAgQAFIgHAEIgGAGQgCABgHgCQgEgBgCAGQgJgBgIAEQgKAEgIAAQgFAAgHAEQgGAEgEAAQAAAEAGAAIAGgCIAHgCQAAANgmACQgBADgGABQgDACgEgBQgEAAgDABQgBACgPAFQgFAGgSAAQgLABgBAGQgEgBgFACQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgEgCgBABQAAABgFAEIgIAEQgOAFAAACQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIABACIgGACQgEACgCgBQgBAGgKABIgOgBQAHAFgHADQgFACgGAAQAAgBgIAEIgIAEQgDAGgPAAQAAgDgGACIgEADQgBgDgEAFIgEAIIgGgCQgBAAgBAAQgBAAgBAAQAAAAgBABQAAAAAAABQgFACgIAAQgEAAgMACQgNADAAADQgDAAgEAEQgFAEgDAAIgbAKQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgDADQgEAAgDACQgDACgCAAQAAADgEABQgEACgDAAQgFgBgDAEQgEAFgDAAIgHAEIgFADQAAAGgKACIgOABQAAABgFADIgHADQgDABgHAIQgFAHgGgBQgHgCgJAJQgRAEgBADIgFACQgCABAAAEIgJgBQABABAAAAQABAAgBABQAAAAAAAAQgBABgBAAIgEAAQgBAAgBAAQAAAAAAABQgBAAAAABQAAABABABQAAAGgKAAQgCgCgGADIgJAEQgRAHgIAKQgJABgIAEIgPAJQAAAEgMAGQgMAHgCAFIgJAEQgGACAAAEIgMAFIgGACQgDABgCADIgCADIgEACQgJAHAAACQgDAAgCADQgDAEgCAAQgHABgFAEIgNAPQgHAIgJADQAAAGgOAJQgOAKAAAHQgEACAOALQAPANgBADQgFAAgGAKQgFAKgBAGQgDAAAPANQAPAMAAgEQAGAAAIAHQAIAHABAGQAAAEAKACQAKACACACIAMAJQAGAAALAGQALAFAGAAQAAAHArAAQAMAMAIAAQAAABAIAAQAJABABABIALAAQAGABAFADIAOAJQANAGAFgCIAKgCIALgCQAEADACAAQgCAEADACQACABANgBQAMAAACAEIATABIAIABIAJABQAAgCAPADIASADQADgEAGAAIALAAQABACAHAAQAHAAADADIAEAKQAEAIADgBIACAAIABgCIABgNQABgFAFAAIAKAAIAPACIARAAQAAgCAKADIAMAEQAAgFAKgCQAKgBAAAGIAugFIgBgCQADgCgDgPQgEgPABAAIgEgNQgFgMABAAQABgCgBgFQgBgFgCAAIgBgUQgBgFACgMQABgOACAAIAAgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBABAAQAFAAAAgZQACAAACgIIADgJQAAgFADgGQADgHABgFIAIgfIAIgQQAFgKAAgGQAEgCACgGQADgIADgCQAHgGgBgHQAMgMgBAAIAEgGQADgCACgEQgCgFAEgBQAAgCAFgGQAGgFAAgDQACgBAFgGQAFgHACAAQAAgDAFgDIAIgGQACAAAEgEQADgEAAgCQANgGAPgPIAFgCQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIgRANQgFACgFAIQgFAHgBAFQAGgBADgDIAGgIQAPgGAAgBQAIgCANgKQALgJAKAAIAIgBQADAAADgDQABgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQAAgDAEgBQAAgDAJgHQAIgHAFgCQADgBAFgEIAIABQACgCAFAAQABAAABAAQABgBAAAAQABAAAAgBQAAAAAAgBIAIgGQAHgGAAADQAGACAAgLQAGgBAFgEQACgCAJgCQAAgDACgDQADgDACAAQAAgCAMgGIANgHIACgFQABgCAEgBIAGgCIAGgFIAFgBIAFgCQAEgEAHgDQAIgDADgDQAFgEADACIAEADQADAHgOAHIgSAIQAAACgSAJIgMAJQgIAFgCAFQgEABgIAGQgIAGgGABQAAAIgLACIgMAJQgGAFgCAFQgIACgHAIQgCAAgDADQgDACgEAAQgGABgCAHQgIAEgCAJQgEACgEAFIgIAIIgPAMQgKAHAAAHQgNAGACANIgDAEIgCAGQgFACgBAJQgCAAgEAFIgFAFQgJAKAAgEQgDABgBAHQAAAGgIAAQAAABgEAEIgFAEIgBALIgGAJQgEAGgBAEIgMAKIgEAMIgGAEQgBACABAFQgBAAgEAHIgDAJQgDABgFAIIgHAHQAAATgIADQgGACABAJIAAANQgEAAgBAZQgBAZABAAQABgJAIgNQAKgOABgHQADAAAFgIQAEgGAAgDIALgUQACgBAFgIQAEgHAEAAQAEgPALgCQgCgKAMgGIANgPQABgEAJgIQAIgHAAgFQAFgCAGgIQAFgJAFgCQAAgDALgJQAJgIAFgDQAAgDALgHQAKgGAAgCQAGgEANgNIAPgNQAEAAADgFQADgFAEAAQACgEAHgGQAHgFAEgBQABgDAFgEQAHgEABgCQAIAAALgMQAMgMAGAAIAKgHQAIgFAAgCQADgBABgDQAAAAAAgBQABAAAAAAQABgBABAAQAAAAABAAQAIAAgCgGIAGAAQAAgCARgIQAQgJAEgBQAAgEATgKQARgJAGAAQADgGAJgFQAIgEAHgCQAAgBAJgEQAJgEACAAQACgCAUgJQATgIAAgBIAEgEQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAQABAAABAAIAGgBQAAgCAIgDIAIgCQADgDAIAEQACgJAFAAQAGgGAIAAQAAgCAHgCIAKgDQAFgHAZgGQABgCAGgBQAFgCACgCIAGgCIAHgCQAAgCAGgBQAGgBAAgBIAEADIAdgQQAAgBAMgDQALgCAAgCQAXgGAAgCIAJAAQAHAAADgEQADAAAPgJQABAAABAGQAAgIAVgEIAMgEQAJgDABAAQAQAKgEgHIgCgDQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAugJQACgEAXgEQAWgEAAgBIAIgDQAEgCADAAQAAgDARgBQATgCABgCQADAAADgDQADgDADAAQAAgCALAAQAngIADABQAAgCAvgIQAHABANgDIAVgGQAYgFAGAAQA9gJAGAAQAJgBAVgEQATgEAMAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAKAFQAIADAAgGIAUgCQA+gHAAACQADABAZgFIAigBQAfAAAAgCIBjgBQAAgCAoADQAsAEAEAAIAKAAQADAEAEgCIAIgCQACAHgDgBQgBAAgBAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgFAEgNAAQAAAAAAgBQAAAAgBAAQgBAAAAAAQgBAAgBAAIgFACQgEAAgDgCQgDgCgCAAQgNAHAAgEQgQACgIgCQAAgCgMABQgMACAAABQgLAAgKABQgCAFgGgCIgKgDQAAADgLAAQgKgHgCACIgDADIgFABQgDADgGABQgDAAAAAHQgMAAgCAIQgCAIAMAAQACADAKABQAKABADACQAAgFAHADIAKADQAAgEANACQAIABgDACIgFADQgCACgJAAQgIAAgEgCQAAABgHABQgGABgBAFQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgCADQgKAAgIACQgKADgHAAIgqADQgCAEgLAAIgRAAIgtACQAAABgfAEQggADgFgBQAAAGgzgBQAAABgIADIgJACQgYAAAAADQgFgBgOADIgiACQAAABgVAEIgYADQAAgDgKAHQgLAGAAACIAhAAIAbgEIATACQADAAAFgCQAEgCAFAAIAOgDQANgCAAACQAFABAHgFIAOABQAAAFALgHQAKgBARgDQAAgCAJAAQAGgBAFABQAGACAGgBQAGgCAFACQAAgDARgDQARgEAAAFQArAFAAgDIAJABQAGABAAADQgNAHgDgBQgFgBgKABQgLABAAADQAkgDBBACQANAAAaAEQAYADANAAQAlAAA5AKQArAFAAAFQAFAAAXAFQAZAFAAADIAIAAQAEAAABgEQAJgDAFAAQAFAAAFACQAAABAIACQAIACAAACQATAAAZAOQAPASgBAAQAAAGASAAIgLgKQgIgHAJAAQAGAAAJAFQAJAFAFAAQAqAWAEAAQAAABAPAEQAOADAAADQADAAAHAEQAIADADAAQAAABAoAOIAZAOQASALAAAHQAEAEAFACQAAACAJAIQAKAIAAADQAHAMACAAQAAADAEAGQAEAGAAAEQABAAACAHIACAJQAEAAAFATQAFATADAAIAJAUQAFAMAAAKQACAAAFAbQACAAAGAXIANAyIAHAaQAHAXgDAAQACAGADApQABADgCAFIgCAIQgCAAAAAGIAAAJQgCAAgDAIIgDAJQgDABgFAPIgFAPQgBADgDAAIgDAAIgBAGQgBAAAAAAQgBABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgIAAIAAAEQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgEACgBAGQgCAAgDAGQgDADgCgFQgHABgFAFQgEAAgCAIQgCAIgCABQAAAHgGADQgGADgGgCQABANgJgDQgMgEgCAEIAAAMQgCABgDADIgCADIgEACQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAGQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQgJgCAAABIgKAEQgEAAgCADQgCAAAAAFQgBAFACAAQgBAKgNABQAAgDgIgBIgLgCIgGADQgGACAAADQAAADgMACQgEABgKAFQgKAFAAADQgCAAgNAHQgNAHAAACQgFACgDAHQgCAFgHgCQAAACgDAEQABAAACAEQACADAAACQgGACgLgDQgLgDgFABIABAKQAAAGgFAAQgCgDgEACQgBABAAAAQAAABAAABQgBAAABABQAAAAABAAQADACABADQgEACgFAAIgJAAQgCAAgHgFQgHgEgFAFIgDAGQgBACgEABIgHAEIgFADQgBAFgJAAIgPgBQAAAHgJADQgLADgCADIgDADQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAgBgBQgCgDgDAAQgEgBAAAEQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAIAAAGIgMABQgDAAgGAFQgEADgDgHQgDgBgDAFQgDAEAAAEQgFAAgFADQgFADAAAEIgGgBIgHABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAADQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgEAAIgPADQgFAGgHACIgPACQAAAAgBAAQAAABAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAADABAGQAAAEgNgEIgHAFQgHAEAAADIgJgBQgEABgCAGIgJADQgHABgCgEQgGADgHAFIgMAIQAAAGgRgDQgSgDAAAIIgFgCQgBgBgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBAAgDAFQgDAEgCgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgGAHQgDAFgFgBIgEAAIgFACQAAAAgBABQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgFAFIgJAEQgHADABABIAYAAQAOgBAIgDQADgBAcgFQAYgFAAgDQADgBAFAGQAEAGAEgCIARgFQACgFAZgDQAAgBALgDIALgEIALgCQAJgBgBgDQARgHABAHIAPgGQAKgDAHABQgSALgFABIgpAUQABgGgKACQgIABgEAEIAEADQgEAAgUAIQgUAIAAACIgJABQgIACAAADQgFABgFgBIgJgDQgBAKgHgBQgMgBgCABQAAABgIABQgJAAABAEQgRAJgKABQgWADAAACIgIABQgGgBAAgBQgDgBgEABIgHACQgWAMAAgIQgDAAgEACQgFABgBADQgDgBgIADIgGADQAAABgVAEQgGAAgFAEQgGAEAKABQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIADABQAAgDARAAQAQgBAAgCQAIAAAWgHIAdgEIAkgGIAVgEQATgEAAABQAIAAAMgEIASgHQgBgBAOgFIAQgEIAVgIQAPgHAEAFIgUAKIgRAHQgGABgLAGQgMAFgEABQABADgKACIgNACQgKAGgLACQAAgCgMAIQgCAFgDgFIgDgDQgEABgFADQgFAEgDAAIgKADQgJABAAADQgFAAgGACQgGACgGAAQAAAJgLgMQgCAGgBAAQgDgFgJACIgLADQgFAGgBADQgFAAgEgDQgFgDgEgBQAAAFgGAEIgLAEQgXALgNgLQgMAEgDAAQAAAHgPAAQAAACgMADQgLADgEgBQAAgEgIAAIgMAAQgCAHgBAAIgHgBQAAACgVgBQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAADgJAAQAAgGgEAIIgDAEIgIAEQAAgEgHABIgIACQgCABgQAAQgOAAgBADIgYAAQgFAAgHgDIgMgDQgHAHgIAAIgRgDQAAABgKADQgKACAAABIgPACQgMACgEgEQAAgBgNAAIgRgBQAAAFgHgBIgKgCQAAADgPABIgFAAQgKAAAAgDgACUKCQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAdgDQAZgCABAEQABAAAAAAQABAAAAgBQAAAAABgBQAAAAABgBQACgDADAAIAEAAIADgBQAEgBAGABQAHAAADgBIAOgFQAJgCAHAEQABgGAEADIAFAFQADAAAFgFQADgGAEABIAHACQADAAAFgDQACgBAFAAIAHgCQAFgBABABIABAFQAEAAAEgGIAJgDIASgFIALgBQAHgBAEgDQALgFADAAQgFgBgPAEIgTAGIgfADQgPACgVgBIgWAEQgSACgBgEQgNACgBABQgKADgJgCQgKgDgNACIg1ADQgFABgCgFIgKADQgBgDgFgBQgIgBgCgCQgLAEgEgBQgMgDgagBIgagBQgFAAgJgCIgOgBIgMAAIgKgCIgBACQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgDgCgCABQgBgDgFgBIgHAAQgKgDgYgBIgOgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABIgDABQgLABgIgDIgFgDQgCgCgDABIgNAAQAAgCgFAAIgHAAQgDgBgEAAIgIAAQgEAAgDgCIgGgEIgPgDQgJgBgEgEQgFgEgBAAQgCACgEAAIgKgCQgGgBgEABQgBgEgMgDQgIgCgGAAQgDABgDgDQgCgCgDABQgDAAgGgBIgKgEQACABgSgIQgQgHAEgBQgCgBgHAAQgGABgDgCQgIgEADgCIgQgFQgDgBgPADQgRADgOgBIApAdQARgBALAEIANAFQAIgBAMAGIAMAFQAKAEAAACIAHgCQADgBACADIAGAHQACgBAIgBQAJgBABADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIASAGQADACAFAAIAIABIASAFQAEACAFABIAJABQAQAEAjAEQA8ALA6AFIAbACQARABALACIAhABQADgBALACIAQABIAMgBQAIgBAEACQABAAAAAAQAAAAABAAQAAAAABgBQABAAAAAAIABgBQABAAAAAAQAAABABAAQAAAAAAAAQAAABABAAgAGCH/IgCgHQAAgDAHAAQABABAHgBQAHgBABgCIAPADQALACAAgEQAGgHAHAFIAMAHQAGAAAAgDQgBgEADgCIAHgCQACAAACAEQAIgIAQgBQAJAAAQABQAAgBAFgCIAGgDIARAAQAAgCAPAAQACAGAEAAQAAgGAIgBQAHgCAAACIAJgCIAJgCQAAAAABgBQAAAAABAAQAAgBABAAQABAAABAAQADAAACgDQALgFAIADQACAAATgEIAGACQAAAAABAAQAAgBABAAQAAAAAAgBQABgBAAgBQAAgBAAgBQABgBAAAAQAAAAABAAQABgBAAABQAFACABgBQAAgCAPgDIARgDQABgCAOgFQANgFAEAAQADABAEgEQAEgDADAAQAAgDAQAAQAGABALgHQAGAAALgFQALgGAGAAQACgDANgEQANgFAFAAQABgCAMgEQALgDAAgBIAVgIQADAAAEgCQAEgDAEAAIAKgEIAHgDQAEgCAEgBQABgDAGgBQAGgCACgCQAEAAAIgDQAJgEACgCQAEAAAHgEQAHgEADgEQAFAAAJgFQAIgFAGAAIAYgMQAAgBAVgIQAWgJACgDQAFAAAJgFQAIgGAGAAQAFAAAGgGQAHgHADAAQAEAAAGgGQAHgGADAAQAHAAAKgIQAEgCAHgHQAAgBAGgCQAGgCAAgCQgHAAAGgCQAFgCADAAQAAgEAJgBQAHgBADABQAAgDADgEQADgFAAgFIAQAAQAAgEAEgCIAIgFIANgIQAAgFAMgGQALgGAAgCQAMgCADgDQAGgEADgJQAFgBAQgbQAMgGAGgKIACgEQABgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAQADAAAFgJQAFgKAFAAQADgFAAgJQAFgDgBgEQABAAACgMQACgNACAAQAAgBgCgFIgEgGQAAAHgLAAIgFAGQgEAGACAAQAAADgHAGQgIAFAAACIgFAGIgGAIQgDAAgFAFIgIAFIgFADQgFADABAEIgJADIgHADIADAAIgBAEQADAAgMAKQgDADgIAAQgHABgCACQAFAAgFAHQgFAGgEAAQgJAMgOADQgEAIgOAFIgCACQgBAAgBAAQAAABgBAAQAAABAAAAQAAABAAAAIgKABQgCABAAAHQgbAFAAAGQgPALAAABIgJADQgGACgEAAQAAADgFACQgEACgEAAQgEgGgEAHQgEAHgCABQAAACgKAGIgMAGQgEABgIAGQgJAGAAAEQAAACgMAEIgQACQAAAEgJACQgJABABAEQAAABgaAFQAAAHgOAGQgLAFgKABQAAgFgOAHIgOAGQgDAAgJAEQgIAEAAABQgEAAgHADQgHADgEAAQAAACgJAEQgIADgCgBIgBADIgBADQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgDABgCgCQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAFIgDAAIgCgBQAAADgFABQgGABAAABQgEACgCgBQgDAAgDACQgDADgMAAIgIAGQAAABgKADIgNADQgNAGgDAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAAAABIgYAKQgYAGgGAEQAAADgXAAIgHAEQgEABgBAFQgFACgEgBIAAAFIgPAAQAAAGgGABQgHACAAgCQgDAAgLAFQgJAEgFgBQAAgBgGACIgHACQgDADgIAAIgMgBQgCAEgLAAIgbAJQAAABgFACIgJADQgFADgKAAQgDgDgDACIgFAEIgKgDQAAAHgNABIgTABIgIABQgFACgBADIgMgBQgcALgDgBIgUACQgSADAAACIgPADIgOACIgHACQgFACAAABQgIAAgQACQgVAEgDAEQACgCATAAQAAAEAZAAQADgEALABIAQACQAAgEANACIAOABQACAAADADQADACADAAIAAAAgAn2HeQgCAEgDAAIANAKQAJAGAEAAIADgDQABAAAAgBQAAgBAAAAQgBgBAAAAQgBgBgBAAQgBgDgGgFIgKgFIgDgCIgCACgAAUGwQACAEACAAIAIACQAFABACgEIADgBQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAgBAHgBQAHgCAAgBQAigBAAgFIAGABQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAFgBANADIAJgDQAGgDADAEQACADAFgBQAFAAACgDQACgCAFACIAIACIgEgEIADgGIAKgCQAGAHAAgFIASABQAFgCAHgHQACgBAKABQAJABADgDQAEgEAHAAIALABQACgFALABIAOABQAAgDAHABIAJADQAAABAKgHQAKgBAOACQAAgIAPgBQAAgBAVgEQAVgFADABQABADAMAAQAMAAACgEIACgFQAEgEADAFQACABAEAAIAGAAQAAgIABgCQACgBAIABQABAEAHgDIALgDQAEgBAKAEIAIgEQAAgFANgDIARgCQAHgDAEgGQADgCAHABIALABIgBgFQAEAAABgCQACgDADgBQADgBADABIAHACQAAgCAPgCIASgBIgCgEIADgBQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAJgBAHgEQAJgHAFgCQAXAAADgFQANAAABgCQAGAAgDgGIAKgBIAEgGQABgBAAgBQABgBAAAAQABAAAAAAQAAAAAAAAQADABADgCQADgCADABQAAACAHAAQAHAAAAgCQAHAAAEgDIAJgIQAHgBAEAAQACgEAEABQAGACACAAQAAgBASgGIAUgIQgDgDABgCQACgCAFAAQADADAFgCIAIgDQAAgBAHgBQAHgBAAgDIAGACQAIgFgEAAQgBgDAPgEQAQgEAAgCQAHAAAHgDIAOgIQABgCAIABQAHABAAgEIADgDQABgCAFAAQAEAAAHgDQAAgBAKgDQAKgCADABQgBgFAFgDQAGgEACgDQAPABAAgDIAHABQAEAAABgEIAKgIQAAgDAIgEQAHgFAEAAIALAAQAAABATgLQAAgDAHgFIAIgFQAGAAAIgHQAIgIAFAAQAAADASgNQAIgGAKAAQAUgNAAgCIAWgPQALAAAMgIQADgHAEAAQADgDAJgDQAJgEACgDQAFAAADgGQADgHADAAIAKgHQABgDAEgEIAHgGIAGgCQAFgBABgCQAAgFANgGQAMgHgBgDQAVgZADgBIAHgPQAFgKgHgDQAAgCgHgEQgIgDgBgDQAAgDgEgCIgHgFQgMgLgGgDIgQgHQgNgHAAgDQgGAAgJgFQgKgGgEgBQAAgBgJgFIgKgHQgEgBgIgFQgHgFgEAAQAAgBgSgEQgUgHgDgDIgQgIIgKABQgHABgEgBIgFgCIgHgBQgRgLgDAAQAAABgSgHIgJgDQgDgEgGgCIgKgBQgtgKgGgBQgGgHgWADQgSACgDgEQgDgEgHAAQAAgBgOACQgPACAAgDIgTgBQAAgEgGgBQgHgHgIAEIgNAFQgHAAgKgEIgRgGQAAAFgXgBQgWgBAAgJQABgEgFgBQgEgBgFABQgCADgIgCQgBgBgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAADgJgBQADAHAAAEQAHAAACAeQACAcgCAIQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABABQAAAAAAAAQgBABAAAAIgBAUQgBATgEAAQgBADADADIgIAQIgGANQgFAIAAAGIgGAPQgFAOgHAAIABAFQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIAAAEQgCAAgCAGQgBAGgDAAIAAAEQAAABgBAAQAAAAAAABQAAAAgBABQgBAAAAABIgFAEIgBAHQgDAAgBAFQgBAAgGAIQgHAJgFABQgBADgIADQgIACABAFIgCAFIgCADQAAACgEAEIgGAFQAEAKgSACQgBAGgHAEQgIAGgCADQgFAIgTAJQgCABgDAEIgFAFQgJAAgRAOQgUARgFACIgNAFQgJAEAAAEIgLAHQgGAFgGABQAAgBgFAFQgFAEABAAIgKAFIgKAGQAAABgLADQgMADAAAEQgJAAgRANQgSAMgMAAIgKADQgIAEgBABIgJAHQgFAFgFAAQgeAKgEAAQAAACgJAGQgJAFAAgEQgEAAgHADQgHAEgDADIgLACQgFABgEAFQgFAAgKAGQgJAGgEAAQgDAFgVAAQgCADgDACQgEABgBACIgGABQgEABgCgCIgGgDQgHgBgGADIgKAIQgBAFgNAEQgDAAgIAFQgHAEgEAAQgsANgHAAQAAADgZAHQgaAIgDADQgTACghANQgHADgOAAQAAAGgPAAQAAACgVAGQABgGgiAKQgEAAgGACIgKAEQAAgBgMAEIgPAFQgIAGgMACIgWAFIAFAAIABABIARACQAOACABgDQAcAAASAEQAsgBAAAFQAFABAvgHQAHgDAHAEIANAHQAAgCAQgCIAUgCIAQgBQAEABACADgAqtGZQgHgMAAgBIAHAFIAGAEQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIADgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgGAAIgCgBIgBAAIAAgBQgDgDgDgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgDgBQgjAFAAgEIgJgBIgIgCQAAgEgOACIgQADQgGAJATADQAWADAAABIAVABQARAAAAACIASAAIAAAAgAopGGQgDABAAAFIADAEIAEAFIAHgBQALAAgJgLQgFgEgEAAgAmTFsIAIAOIAFAFIAOACQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAIAOgCQAJgCAEABIBCgLQAAgCAVgDIAYgEQBOgSAHAAQAAgBAXgGQAXgFAEAAQAAgDAWgEQAWgDACgEQAHAAAKgEQALgDAGgBQAGAAALgEIAQgFQACgDAdgHQAagGgBgHQAYgBAAgDQAJgBARgHQAAgBAJgCQAJgCAAgBQADAAADgCQABgBAAAAQABgBAAAAQABAAAAgBQAAAAAAgBIAGgBIAFABQAAgDAQgFQAOgEAFAAQACgDAJgDQAKgCAAgDQAEAAAIgDQAJgDACgDQAGAAALgEQAJgEAFgEQAGgFAPgDQABgCANgEQANgEAAgCIANgGIAOgHIAPgFQAKgEADgEQACAAAJgFQAIgEAAgBQAEAAAIgEQAIgFADgDQAKAAAOgKQAOgKAIgBQACgEAUgJQATgKgBgCQAAgBANgHQAOgHAAgBIAHgGQADgDAFgBQAKACAEgGIAEgIQAEgIAFAAQAAgBAFgEQAGgDAAgCQAFgBAIgHQAIgHAFgBQADAAACgFQACgFADgBIAIgFIALgKQAEgCAFgHQAFgHAEgCQAAgFAOgMIAOgRQACgEAFgIQAGgIACAAQABgGAFgHIAGgMQACAAACgFIACgGIACgHQACgGgBgDQgFAAgJAOQgKAQgEACQAAAGgMAJIgLAKQgGAHgEACQAAAFgHAFIgKAKQgBACgIAFQgHAEAAAEQgDABgDAEQgDAEgFABIgEAFQgEADgCAAIgHADIgIADQAAACgEADQgFAEgBADIgKAGQgHAGgBACQgDAAgJAGQgJAGgCADQgKADgQANQgPAMgMACQgFAGgMAEQgLAEgIAAIgOAOQgFAAgHAGQgHAFgDAAQgCAEgIABQgHABgDADIgHADIgGADQgCAAgEAEIgFADQgCAEgJAAQgJABgDAEQgEACgDAAQgCAEgIABIgNABIgJABQgGAAgDABQgDABgDAHQgDAGgEABQgEAEgFgCQgHgCgDABQAAAEgFACQAAAEgVAJIgbALQgDAAgFADQgFADgDAAQAAACgNACQgEAEgIADQgHACgGAAQAAACgNADQgNADAAADIgNACQgKACgCADQgGAAgCABQgDABgFAFQgHAAgGACIgNADIgWAHQgBACgKACQgKACAAACIgbAHQgFAAgIADQgIADgFAAQgCACgOAEQgNADAAABQgDAAgFADQgFADgDAAQgBACgGABQgFABgCgCQgRAHgCAAQgDADgNADIgMACQgEABgKAEQgIADgEAAQAAACgOAAIgQgCQAAABgJADIgMACQgPAAgMAFQAAAFgLACQgMABAAABIgXAAQgQAAgFAFIgDACIgDADIgJADIgHACQgCADgcAEQgcAFAAACIgFAAIgFAAgAxuEwQAAgCgHgCQgFgCgEAAQAAAGAQAAgAzoD+IgCADIAOALIAKACIALACQAEAHAcAKQAbAKAAgGQgOAAAAgHQgQgCAAgCIgUgKQgCAAgEgIQgEgHgGAAQAAgDgKgBIgKgBIAAAAIgGACgAmhD9QgJAEgBADQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAIADAAQAAACAsgFIA0gGQAAgDAWgEIAcgFQABgDANAAIARAAQAFAAARgGQANgEAIACQAAgCATgDIAWgEQAAgFALACQAMACAAgEIAKAAQAGAAADgEIAJgDQAFgGAQACQAQABACgFQgIAAAHgEQAGgEAEAAIANgBIAEACIAFABIASgEQAAgCgFABIgHABQgDgGAcgHQAXgHAKAAQAAgBALgCQALgBABgCIAHgCIAHAAIADADIAFABQAAgBAAgBQgBgBABAAQAAgBAAAAQABAAABAAQgCgFAEgBIAJgCIAKAGQAKAGADgBIgHgDIgDgKIAGgFQADgBAFACQACABAMgFQALgFAAAEQADABAEgCQAEgCAAgCQAOAAADgFQAAgJAJAAQACgEAKAAIANAAQAFgBADgEQADgEADAAIAVAAIAEgJQADgDAEABIAGADQgBgJAGABIALADQADAAAEgDQAEgEADAAQACgCAJgFQALgFABACQAAgHAUgCQAUgCAAgCQAIAAAFgBIAFgDIAGgDQACgDALgDQAMgDAAAGQAEABAOgEQAGgEABgFQgEAAAEgHIAFgIQAEgCAAgJIANgHQAJgFAGAAQABACAKACIAMACQAAAEAMgGQALgFACgEQgHAAgCgMQAFAAAMgPQASgEAAgCQAMgCAOgGIAWgKQAFgFARgHQAOgGADgHQAGgCANgOQALgMAHAAQACgDAFgDQAFgEACgDQACgCAHgGQAHgFAAgEQACAAAFgIQAFgHAAgCQAEAAAJgXQAKgXgCgFQgCAAAAgMQABgMgEgCIADAAQgBAAgDgHIgHgRIgSgBQAAACgPgEQgPgDAAADQgmAHAAgBQgLABAAgCIgIABQgFABgDgDIgHABIgJABQAAgBAAAAQAAAAgBAAQgBAAAAAAQgBAAgBABIgGABQAAAEgMABQgLABgFgBIgPgBIgDAFQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIgOABQgCAHgNgEIgUgGQgBACgIABQgFABAAAHQgYAAgEABQAAADgUABQgUABAAACIgZABQgLAAgDADIgBABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgQABQAAABgGACIgIABQAAgBgSADQgTACAAACIgMADQgIACgFAAIgJAIQAAAEgJgHQgDAAgBADIgCAFQgBADgEABIgGABQAAAEgMAAQgBACgEABQgEABgDADQgDADgGAAQAAgEgGABIgKACQAAAFgWgCQAAAGgJADQgLADgCACQgCAAgEADIgHAEQgEACgCgBQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgDAAgCgCQgEgCgCAAIgIADIgIACQgDgCgEACIgHADIgEAEQgEAEAAACQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABIgBAEIgEAFIgCAAQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgDABgCgCQgDgCgCABQgFAJgVACIgUAMQgKAEgEgDIAAgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAQAAgBgKAHQAAAHgEABIgIgCQgBgBgHADQgHADgBACQgFAAgDADQgDADABAEIgMACQgNADgEAFQgEAAgBAFIAAAGIgRAJQgEAGgIAAIgMgCQACAMgGACIgMAHQgMAIAAgFQgGgEgBADIAAAEQAAADgKAIQgLAGgEABQAAACgGAEIgKADQAAgGgFAEQgHAFACAAQAAAFgHAIQgGAHgFAEQgCAFgFADIgKAEQgJADgDgEIgIAHQgFAFAGAAIgCAHIgGAJQgFAGgCAAIgKAJQgHAHgCAEQgGAAgCADIgEAJQgEABgEAFIgGAHQACAEgZAYQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIAPgBIAqgFQAAAFARgHIAFAAIADgCQAAAAABAAQABgBAAAAQAAAAABAAQAAAAAAABIAEACQABgFAKgDIAJgEQAGAAAVgEQASgDAEAIQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAgBABAAQACgEACAAQAAgBAFABIAHAAQAAgBAGAAIAJgBQAAABAAAAQAAABABAAQAAAAABAAQABAAABAAQAAgKAqAAQAAgEAKgBIAOgBQAAgHAZgBQAZgCAAADQADgBAEgEQAEgDACAAQAAgCAHACIAIACQAAAHAVgMQAAgCAHgDIAJgCQAFAHAHgBIARgDIAOgBQAHgBAAgGQgEADgEAAQAAgEADgCQAEgCABgCIAOgCIAGgCQAAgFALAAIAPAAQAHAHAGgGQAJgKAEgBQAMAAAAgCQAFAAADAFQACAFgHAAQAAAEAHACQAGADAAgFQgEAAgBgDQAAgEAEAAQAAgCAKAAIAGgEQAFgCAAgDQAHAAAEgDQABgCAEABQAEABACgBQAEgHALAAQACABAHgDIAIgEQAVgLAAAFQALAAgDgBQgIgEgBgCQgHgCAGgCIAJgBIAFAGQACACAEABQAMAAAAgCIAYgLQAFAAAJgEQALgEAFAAQAAgEAMgEQAKgDAFAAQABgCAFgCQAFgCACgCQAQgEACAAQAEABADgDQAFgFADgBIAJgFQAHgDACAEQACADgLANQgEAAgHAGQgIAFgEAAQAAAFgNAGQgOAGgCAEQgCAEgKACQgIABgCAEQgEAAgHAFIgJAHQgcALAAgBIgTAPIgMAEIgLAEQgZAGgGAIQgGgBgGAEQgGADgEAAQAAABgMABQgLABAAAGIgQADQgLACgEAEQgMAGgHABQAAACgJADIgKAEIgEAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgKADQgEAGgJABIABADIgGACIgHACIgJAAQgFgBgEABIgKAGQgKAFAAgBQgIAAgPAFQgPAFgJAAQAAABgWAEQgWAEAAADQgdALAAgEQgEAAgIAFQgHAFgEAAIgQAFQgRAEgBABIgZAFIgkAJQgaAAgCAEIgIACIgIACQAAgDgUAHIgNAEQgIADgHAAQgKADgFAAIgTAAQgFAFgMAAQgNgCgFABQAAABgIACIgLADIgBgBIgIACgAz3D2QAEgHgIgCQAAgBgEgEIgFgFQgDAAgIgFQgHgEgEAAQgBgDgHgGQgHgGgDAAQAAgCgLgIQgLgIgEAAQACAFAGAIQAGAHAFADQANAKgCAAQADAFAGAAQAWATAAgCQACABAFgCQAAAHALAAgApzCuIAGAEQgEABgCADQgDAEADADQAFADgDADIgEAEQATgEAAgBQADgBAFABIAHACIAEgBIADgDIADgBIAKgCQgFgZACAAIgCgJQgCgGABgDIACgOQABgIABgEQADAAgBgIQgBgIgGgBIgMASQAAAFgGAJQgGAJABAEQgGADgCACIgEAJQgCAAgCAEIgDAFQAAAEgIgGQgBABAGAEgAnqBaQgEAAgDAIQgEAKgDABQgDAVgBAAIAAACQgDAAgDAUQgDAUACADQADgBAFgIIADgIQADgHACAAIAFgLQAEgIACAAIADgHQAEgFAAgDQACAAAEgJIAFgLIAIgGQAHgGAAgCQAEAAABgDIABgIQACAAACgDQABgEADAAQAIgJABgEQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIACgFQAIgFAHgLQAEAAAGgJQAFgJAGAAQAegLgOAAQAAgGAFgCIAJgDQAAgGAIgEQAIgEAAgFQAFgBADgEQAEgFADgBQACgDAMgGQALgFAAgEQAKgGAGAAQAAgEAIgFQAIgEAAgDIAGgEIAHgEIAHgFQADAAAIgHQAIgGABABIALgGQAIgFACgDQAHgFABgGQAFAAAGgBQAGgCAJgGQAAAHAMgIIAPgKQACAAAGgEIAHgGQABgBAIgDIAIgDQAhgKAAgDQAFAAAJgEQAIgDAGAAQABgEAFACQAHABACgIIAGgCQACAAAHgEQACgCAOgEQANgDAAgCIAJgDQAGgDAAgDQAQgCAAgBIAJgCQAHgCAAgBQAFAAAKgEQALgFAGgBQAAgBAIgDIALgCQA2gRAEAAQAAgBAOgDIAQgEQATABAAgGQAFAAALgDQAKgDAGAAIAfgIQAAgCAMgBIAOgBQAAgCAMgCQAMgBABgCQAEAAAGgCQAHgDAEAAIAMABQAHgBADgDQAXgCAKgDQAAgEAygEQADgFAeAAQASABARgEQAAgFA4gBIA+gBQAAgCAGABQABAAABAAQABAAAAgBQABAAAAgBQAAAAAAgBIADAAIgBgCQgEAAgEgIQgFgIgDAAQAAgDgHgHQgHgGAAgEQAHgCAJADQALADAAAIQAEABAFAEQAFAEACAEQADACAAAFIADABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAEADQAEgBAEABQAGABAMgBIAUAAIAmACQAhABAAABQAIABAHgBQAAgCAUACIAZADQArACAAACIAzAEQArAFAAAGQAKAAAUAFQAVAEAKAAQAAACAPADQAPACAAACQAHABAKAEQAJADAHABQADABAHADQAGADADAAQAAADAJAAQAKABABACIAcAJQAEAAAIAEQAJAEACADQAOAHAAgDIAEABIACACQAEAAALAGQALAGAAABQAFAAAIAGQAIAFAEAAQAAABAHAFQAHAEACAAQAAABAIADQAIAEABACQADADAKAFQAIAFADAEQAHAAgHgJQgGgKgFAAIgEgEQgEgDAAgCQgIAAgHgKQgEAAgKgJQgLgKAAgDIgLgBQgHgCAAgEIgDgCIgGgBQgIgIgCgBIgOgHQgGgEgHAAQgEgFgKgDQgEgBgBgCQgCgDgCgBQAAgCgSAAQAAgGgLgCIgPgCQgHAAgHgDQgIgEAAgEQgIAAgNgJQgNgKgHAAQAAgBgKgCIgKgBQgZgHAAgCIgPgDQgIgDgEAAQAAgEgdgGQgZgEgKAAQAAgCgOAAQgPgBAAgEIgXgDQAAgDgbgCIgbgDQgZgDgMAAQAAgBgMgBQgMgBgBgBIgbgBQAAADgogCQgBgCgOAAQgNgBAAACQgDABgGgBIgIgBQgRACgIgBIgKADQAAABgKAAIgMgBQAAADgVACQgVABgFgBIgwAEIg5AEQgFAAgYAEQgZAEAAACIgXACIgUADQAAAHgyACQAAADgkAGQgCADgJAAQgJAAgDAEQgFgBgGACIgJABQAAACgOABQgNABAAADIgeAJQgSAFgLAAIgdAKQgeAJgCgBQAAAEgNACQgOACgBAEIgOAEQgIACgFABQAAABgHADIgIACQAAABgKAEIgPADQgCAEgLADQgLADgCAEQgEAAgGADQgHAEgDAAQgVAFgFAHQgFAAgIAGQgJAGgFAAQgDADgHAEQgHAEgEAAQgCADgPAIQgEAAgJAHQgIAHgHgCQgBAEgJAAQgBAEgIADQgNAFgHAGIgPAJIgPAJIgJAIQgEAFgFAAQABgCgKAHQAAAGgYAPQgLAMgKAEQAAABgEADIgGAEQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAABgFAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQgDAEgMAHIgDAEIgEAEQAAADgEAEQgDAEgDAAIgFAHIgHAFQAAACgJAIQgDADgEACQgFABgDADQAAADgEACQAAADgDACIgGAEQgCACAAAEQAAAFgCACIgFADQgDAAgCADQgCAFgBAAQgBACgEAGQgEAFgCABQAAAGgJAGQgKAGAAAGQABAAgFARIABAIQgBAFgDABIgBABIAAAAIgBABgAxpmXQgDABgCACIgCAFQgHAAgCADQgCAAgGADQgFADgCACIgHADIgGADQgGAHgTAGQgCAEgKACQgKABgBADIgHAGQgGAFAAABQgOAAgBAHIgSAOQgEAAgPAKQgJAGgGAHQgCADgFADQgFADgCADQAAAHgIAEQgKAEgBAFQgCABgDAGQgCAEgDABQgBACgGAFQgFAEAAADIgJAJIgIALIgDACQACACAlgbQAmgdAHgBIAHgFQAEgDADAAQAAgBAEgCIADgEQgDgBAAgEIAMgBQAIgCACgCIADgCQAAgBABAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgCAGgDQAFgDACAAQACgDALgFQAJgEACgDQADAAAFgFIAHgHQAMgEABgBQADAAAHgEQAJgEADgBQACgCAHAAQAEABABgFQABgJANAAIAHgIQACgDAFABQAFABABgDQACAAAHgEQAHgFACgBQAAgCARgHQAQgHADABIgBgEQAGgBAHgEQAHgEAFgBIALgFQAHgEACgDQADAAAFgCIAHgDQACgCAFAAIAIABQACgFADgCQAGgHAPgDIAYgDQACgDAIgDQAIgDAEAAQAAgDAIACQACABAEgCIAGgEIAIgEQAEgCADAAQAEgGAOgEIAWgEQAGgBALgDQAOgEAAgDIAHgCIAFgDIAJABQAFgBAAgFQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAABgBIACgDIgGgDIgvAMIgCgBQAAACgLABQgKACAAABQgHAAgLAGQgLAGgGABIAAgDQgFAAgKADQgJADgFAAQgEgBgCADIgFAEQgEAEgCAAIgHgDIgIAEQgIADgBAEIADABQgBADgFAAQgEABACgEQgDAAgHADQgHADgEAAIgFACQgGADgBACIgDAFQgDABgDgBQgCAGgOAFQAAABgFABQgFAAAAABIgLACQgEABgCAHIgDABQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgKAAAAgCQgCAAgDACQgEADgCABIgOAHQgNAIACABIgNAGIgNgCIgDABgAlSlJQgFgDAKgGIALgHQAIgDAAgBQABgBABAAQAAAAABAAQABAAAAAAQAAABABABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQACACgOAJQgJAGgFAAIgEgBg");
	this.shape_1.setTransform(7.7928,27.7457,0.4948,0.4948);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABwDnIAAkXQAAgygageQgbgeguAAQgfAAgdAPQgdAPgkAjIAAFEIhjAAIAAnEIBjAAIAAA8IADAAQAdghAogSQAngSAqAAQBLAAAvAtQAxAxAABZIAAEWg");
	this.shape_2.setTransform(117.997,94.1892,0.4949,0.4949);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjCCoQhLhEAAhnQAAhiBNhCQBNhDBxgBQB2AABNBCQBNBBAABlQAABqhMBCQhMBDh4AAQh1AAhLhEgAh4hvQgvAqAABCQAABGAuAsQAtArBIABQBPgBAugqQAugrAAhIQAAhBgwgrQgxgrhKAAQhGAAguArg");
	this.shape_3.setTransform(90.4194,94.4243,0.4949,0.4949);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiqEwQhCgnAAg8QABgyAegeQAfgfBBgOQgygbAAgeQAAgWAWgRQAWgRAjgIIAAgCQg3gVgdgkQgbgjAAgyQAAhIA8gqQA7gqBkAAIDRAAIAABFIhoAAQAeAbAMAWQALAVAAAdQAAAbgPAeQgNAcgTARQgiAghdAPQgoAGgOAGQgXAJAAARQAAASAnAOQAiAMBQAOQBNAOAlAjQAhAfgBAuQAABEg/AmQg/AmhvAAQhmAAhBgmgAhtCYQggATAAAeQAAAiAkASQAkASBEAAQBBAAAlgRQAlgSAAgfQgBgmg7gUQgsgOg9AAQgyAAggATgAhIjvQgdAYAAAhQABAlAbAXQAcAXAtAAQApAAAcgYQAbgYAAglQAAgggdgYQgdgYgnAAQgpAAgeAZg");
	this.shape_4.setTransform(64.4501,100.1526,0.4949,0.4949);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABoAAQBmAAA5A+QA8BAAAB7IliAAQAYCHCQAAQBVAABbg2IAABXQguAcgsAMQgxAOg9AAQhxgBhEhJgAhPiAQgjAdgKA2ID9AAQgDg0gfgeQgggeg0AAQg4AAgiAdg");
	this.shape_5.setTransform(39.7057,94.4243,0.4949,0.4949);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ai3DnIAAnEIBkAAIAABoIACAAQBHhxBKAAQA6AAA/A1Ig1BNQgXgTgbgNQgagMgSAAQgzAAgjAoQgjApAAA6IAADsg");
	this.shape_6.setTransform(19.9101,94.1892,0.4949,0.4949);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Aj1DJQhahSAAh3QAAh3BchTQBfhVCUAAQCWAABfBVQBbBSAAB4QAAB3haBSQhfBXiYAAQiVAAhfhXgAitiYQhGA8AABcQAABcBGA9QBFA9BoAAQBpAABFg9QBFg8AAhdQAAhchFg8QhFg9hpAAQhoAAhFA9g");
	this.shape_7.setTransform(-9.6965,91.7272,0.4949,0.4949);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABnAAQBnAAA5A+QA8BAAAB7IljAAQAMBCArAjQAqAiBIAAQBUAABdg2IAABXQgwAcgrAMQgwAOg/AAQhvgBhFhJgAhQiAQgjAdgKA2ID+AAQgDg0gfgeQgggeg0AAQg4AAgjAdg");
	this.shape_8.setTransform(-41.7282,94.4243,0.4949,0.4949);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ai4DnIAAnEIBkAAIAABoIADAAQBHhxBKAAQA7AAA9A1Ig1BNQgWgTgbgNQgagMgSAAQgyAAgkAoQgkApAAA6IAADsg");
	this.shape_9.setTransform(-61.1773,94.1892,0.4949,0.4949);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ABFDgQgTgLgHgYQhAAuhHABQg2AAgkgiQgiggAAguQABg7A3gkQAfgUBVgbIBYgcIAAgYQAAgpgWgUQgWgTguAAQhZAAhHBLIAAhiQA7g+BtAAQBQABAxAjQA1AoAABKIAADoQAAAXATAAQARAAAkgYIAAA2QgjAVgTAHQgUAIgWAAQghAAgSgMgAhCAtQgxAbAAAkQABAcAUASQAVASAeAAQAsAAArgmIAAiDQhOAXggATg");
	this.shape_10.setTransform(-84.536,94.4243,0.4949,0.4949);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AjIDAQhRhQAAhnQAAiABhhUQBhhUCUAAQBcAAB7AuIAABXQg6gfg0gOQgzgOg3AAQhqAAhHA9QhHA+AABbQAABeBGA8QBGA7BwAAQBsAABug/IAABXQgzAYgwAMQg6AOhFAAQihAAhfhgg");
	this.shape_11.setTransform(-112.7818,91.9993,0.4949,0.4949);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CO_v_white, new cjs.Rectangle(-126.7,-7.3,264.2,124.39999999999999), null);


(lib.BUTTON = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAqIAlgqIglgpIAaAAIAmApIgmAqgAg2AqIAmgqIgmgpIAbAAIAlApIglAqg");
	this.shape.setTransform(67.675,4.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUA3QgMgDgIgIQgIgIgFgLQgEgLAAgOQAAgMAEgKQAFgLAHgJQAIgIALgFQALgEAMAAQANAAAKAEQALAFAHAIQAIAJAEAMQAEALAAANIAAAGIhUAAQACALAIAIQAIAIAOAAIAIgBIAIgCIAIgEIAHgEIANATQgJAIgMAEQgNAEgNAAQgMAAgLgFgAgKghQgFADgEADIgFAJIgCAIIA3AAIgCgIIgFgJQgDgDgFgDQgGgCgHAAQgGAAgFACg");
	this.shape_1.setTransform(52.175,4.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AggA6IAAhxIAeAAIAAAQQAFgHAKgGQAJgFALgBIAAAeIgIgBIgIABIgIADIgHAEQgDACgBADIAABKg");
	this.shape_2.setTransform(42.575,4.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaA6QgHgDgGgEQgGgFgDgHQgEgIAAgJQAAgKAEgHQADgGAGgFQAGgEAHgCQAHgCAHAAQALAAAIAEQALADAFAHIAAgQQAAgIgHgFQgHgGgKAAQgTAAgPAOIgLgUQALgKANgEQAMgEANAAQAKAAAJACQAJACAGAGQAIAEAEAIQAEAJAAAMIAABJIgeAAIAAgMQgGAHgKAEQgIAEgLAAQgHAAgHgCgAgQAKQgFAEAAAJQAAAIAFAEQAHAFAJAAQAGAAAHgDQAGgCAEgGIAAgNQgEgFgGgDQgHgDgGABQgJgBgHAFg");
	this.shape_3.setTransform(31.65,4.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgQA3QgLgEgIgIQgIgIgEgLQgFgLAAgNQAAgMAFgMQAEgKAIgIQAIgJALgEQAMgEAMAAQARAAALAGQALAHAGAIIgUASQgIgNgQAAQgMABgJAIQgJAKAAAOQAAAPAJAJQAJAJAMAAQAIAAAGgDQAGgEAEgFIAUASQgGAIgLAGQgLAHgRAAQgMAAgMgFg");
	this.shape_4.setTransform(20.425,4.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgKBCQgIgIAAgPIAAg7IgTAAIAAgaIATAAIAAgfIAdAAIAAAfIAXAAIAAAaIgXAAIAAAzQAAAFADAEQACADAFAAIAGgBIAFgCIAGAXQgDADgGACQgHACgJAAQgPAAgIgIg");
	this.shape_5.setTransform(5.725,2.775);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgUA3QgMgDgIgIQgIgIgFgLQgEgLAAgOQAAgMAEgKQAFgLAHgJQAIgIALgFQALgEAMAAQANAAAKAEQALAFAHAIQAIAJAEAMQAEALAAANIAAAGIhUAAQACALAIAIQAIAIAOAAIAIgBIAIgCIAIgEIAHgEIANATQgJAIgMAEQgNAEgNAAQgMAAgLgFgAgKghQgFADgEADIgFAJIgCAIIA3AAIgCgIIgFgJQgDgDgFgDQgGgCgHAAQgGAAgFACg");
	this.shape_6.setTransform(-4.175,4.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgXBMQgQgGgKgKQgMgLgHgPQgGgPAAgTQAAgSAGgPQAHgPAMgLQAKgKAQgGQAQgGAPAAQANAAAKADQAKADAIAFQAIAFAGAGIAKAOIgbAPQgGgIgJgHQgKgGgNAAQgJAAgJAEQgJAEgHAHQgHAHgDAJQgEAKAAAKQAAALAEAKQADAJAHAHQAHAHAJAEQAJAEAJAAQALAAAJgEQAJgEAFgEIAAgTIgqAAIAAgdIBMAAIAAA8QgMAOgSAIQgQAIgWAAQgQAAgPgGg");
	this.shape_7.setTransform(-18.75,2.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// bkgd
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#00A7B5").s().p("AxYC4IAAluMAg4AAAIB6CtIh6DBg");
	this.shape_8.setTransform(-3.65,3.85);

	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(1));

	// shad copy
	this.instance = new lib.Buttonshad();
	this.instance.setTransform(-21.65,-15,0.6438,0.6438,0,0,180);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shad
	this.instance_1 = new lib.Buttonshad();
	this.instance_1.setTransform(-30,-15,0.6438,0.6438);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BUTTON, new cjs.Rectangle(-171,-15,300,56), null);


(lib.BKGDblue = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#256BA2").s().p("A3ZKVIAA0pMAuzAAAIAAUpg");
	this.shape.setTransform(0,66.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGDblue, new cjs.Rectangle(-149.7,0,299.5,132.2), null);


(lib.BKGD = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF8300").s().p("A96WbMAAAgs1MA71AAAMAAAAs1g");
	this.shape.setTransform(0.0067,125.0449,0.7833,0.8714);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGD, new cjs.Rectangle(-150,0,300,250.1), null);


(lib.HEAD3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD3type();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD3, new cjs.Rectangle(-139,0,150,76.3), null);


(lib.HEAD2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD2type();
	this.instance.setTransform(0,26,1,1,0,0,0,0,36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-139,-10,155.4,52.2), null);


(lib.HEAD1a = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1atype();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1a, new cjs.Rectangle(-139,0,151,100.4), null);


// stage content:
(lib.CO_Safety_160x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,324];
	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_324 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(324).call(this.frame_324).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,2,0,3).p("EgMaguyIY1AAMAAABdlI41AAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(325));

	// HS logo
	this.instance = new lib.HS_logowhite();
	this.instance.setTransform(80.2,557.75,0.31,0.31,0,0,0,0.7,71.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(325));

	// CO logo
	this.instance_1 = new lib.CO_v_white();
	this.instance_1.setTransform(79.2,500.2,0.35,0.35,0,0,0,0.1,55.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(325));

	// CTA
	this.instance_2 = new lib.BUTTON();
	this.instance_2.setTransform(-27.3,446.95,0.76,0.76,0,0,0,-10.4,3.9);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(309).to({_off:false},0).to({x:52.7},15,cjs.Ease.quadOut).wait(1));

	// HEAD1a
	this.instance_3 = new lib.HEAD1a();
	this.instance_3.setTransform(143.5,335.65,1,1,0,0,0,0,24);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({alpha:1},9).wait(101).to({alpha:0},10).to({_off:true},1).wait(204));

	// HEAD2
	this.instance_4 = new lib.HEAD2();
	this.instance_4.setTransform(143.6,369.4,1,1,0,0,0,0,36);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(151).to({_off:false},0).to({alpha:1},8).wait(94).to({alpha:0},10).to({_off:true},1).wait(61));

	// HEAD3
	this.instance_5 = new lib.HEAD3();
	this.instance_5.setTransform(143.5,336.15,1,1,0,0,0,0,24);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(276).to({_off:false},0).to({alpha:1},9).wait(40));

	// BKGD-orange
	this.instance_6 = new lib.BKGD();
	this.instance_6.setTransform(79.7,575.2,0.5317,0.7337,0,0,0,0,217);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(325));

	// BKGD-blue
	this.instance_7 = new lib.BKGDblue();
	this.instance_7.setTransform(80,352.1,0.5342,1,0,0,0,0,66.1);
	this.instance_7.alpha = 0.6992;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(139).to({alpha:0.8008},0).wait(186));

	// PIC
	this.instance_8 = new lib.safety_img1_160x600();

	this.instance_9 = new lib.MhSubstance_160x600();
	this.instance_9.setTransform(0,0,0.5,0.5);

	this.instance_10 = new lib.safety_img2_160x600();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_9},{t:this.instance_8}]}).to({state:[{t:this.instance_10}]},139).wait(186));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-69.3,299.5,229.8,301);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 160,
	height: 600,
	fps: 36,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/CO_Safety_160x600_atlas_P_1.png", id:"CO_Safety_160x600_atlas_P_1"},
		{src:"images/CO_Safety_160x600_atlas_NP_1.jpg", id:"CO_Safety_160x600_atlas_NP_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;