(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"CO_SchoolisBack_300x600_atlas_P_1", frames: [[0,0,232,87]]},
		{name:"CO_SchoolisBack_300x600_atlas_NP_1", frames: [[0,0,600,1200]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Buttonshad = function() {
	this.initialize(ss["CO_SchoolisBack_300x600_atlas_P_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.MhSubstance_300x600 = function() {
	this.initialize(ss["CO_SchoolisBack_300x600_atlas_NP_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.HS_logowhite = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ap9EXIAHnRINagKIgCh7IGDgCIAZKDgAFdgfQgVAOgIAYQgGAUAAAZQAAAaAGATQAJAZAVAOQAVAOAgAAQAyAAAeggQADgDgEgCIgZgYQgCgDgEADQgSARgZAAQgfAAgHgZIgDgKQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIBxAAQAEAAAAgEQAAglgGgUQgIgYgVgOQgVgOgfABQgeAAgVANgAgnAvQgVAQAAAdQAAAdASAPQARAOAaAAQAjAAAQgVIABAAIAAANQAAADAEAAIArAAQADAAAAgDIAAh4QAAgjgSgPQgUgRgtABQgqAAgaASQgDACACADIARAeQACADADgDQAQgKAZAAQAWAAAIAEQAIAHAAANIAAAHQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIghAAQgkAAgUAOgAnMBXIgZAdQgCACACADQAiAdAzAAQAoAAAWgSQAVgRABgeQAAgyg/gGIgUgCQgPgCgGgEQgFgDAAgHQAAgOAYgBQAbAAAXAOQAEADACgDIAVgaQADgDgDgDQgegWguAAQgkgBgVARQgUAQAAAaQAAAzA9AHIAVABQAQACAGAEQAFAEAAAHQAAASgdAAQgfAAgagVIgDgBIgDABgACfgkIAACyQAAADAEAAIAuAAQAEAAAAgDIAAhjQAAgnAdgCQAMAAAPAJQADABACgCIAWgmQACgEgDgCQgNgLgUABQgjgBgOAYIAAAAIAAgPQAAgFgEAAIguAAQgEAAAAAFgAieAiIAABsQAAADAEAAIAuAAQAEAAAAgDIAAh2QAAgegRgTQgRgUgeABQghAAgPAUIgBAAIAAhZQAAgDgEAAIguAAQgEAAAAADIAAD/QAAADAEAAIAuAAQAEAAAAgDIAAhsQAAgPAIgKQAIgJAOAAQAdAAAAAig");
	this.shape.setTransform(25.025,83.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAaAAQABABABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_1.setTransform(27.15,92.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeATQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBQAAgGACgIQAHgTAXgBQAZABAGATQACAGAAAIQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_2.setTransform(65.075,85.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AqIk4IUcAvIAII0I03AOgAhWAjQgVAQAAAeQgBAdAUAPQAQAOAbAAQAkAAAPgVIAAANQAAADAEAAIArAAQAEAAAAgDIAAh5QAAgjgSgPQgUgRgsAAQgrAAgcATQgCACACADIARAfQACACADgBQARgMAZAAQAWAAAIAGQAHAGAAAMIAAAHQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIghAAQgjAAgVAOgAkagrQgVAOgIAZQgHATAAAZQAAAXAHAWQAIAaAWAOQAVAOAgAAQAzAAAdggQADgDgDgCIgagYQgCgDgDADQgSAQgZAAQgfAAgIgYQgCgDgBgIQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIBxAAQAFAAAAgEQAAgmgGgTQgJgZgUgOQgWgOgfAAQgeAAgVAOgADcgxIAAAhQAAAEAFAAIALAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAABUQAAAhAOAPQAOAPAgAAIAUAAQAEAAABgEIAAgnQgBgDgEAAIgJAAQgJAAgDgEQgFgFAAgKIAAhSQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAYAAQAEAAABgEIAAghQgBgDgEAAIgYAAQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAgyQAAgEgDAAIguAAQgFAAAAAEIAAAyQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgLAAQgFAAAAADgABth9IAADKQAAAfANAPQAOAOAfAAIAVAAQADAAAAgEIAAgnQAAgDgDAAIgIAAQgRAAAAgSIAAjGQAAgEgEAAIgvAAQgDAAAAAEgAHggBQAIAIAAAQIAABsQAAADADAAIAvAAQAEAAAAgDIAAh3QAAgegRgTQgQgUgfAAQghAAgQAWIAAAAIAAhaQAAgEgEAAIguAAQgFAAAAAEIAAEAQAAADAFAAIAuAAQAEAAAAgDIAAhsQAAgQAIgIQAIgKAOAAQAOAAAHAKgAmpgBQAHAIAAAQIAABsQAAADAFAAIAuAAQAEAAAAgDIAAh3QAAgegRgTQgRgUgfAAQghAAgPAWIAAhaQAAgEgEAAIgvAAQgDAAAAAEIAAEAQAAADADAAIAvAAQAEAAAAgDIAAhsQAAgQAIgIQAHgKAOAAQAOAAAIAKg");
	this.shape_3.setTransform(-21.95,31.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAbAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_4.setTransform(-24.5,39.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeASQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAgGADgIQAHgUAXAAQAYAAAIAUQACAIAAAGQAAABgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-45.05,31.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AJdAwIAcgBQABAJANAAQAPABAAgNIAAgIQgIAFgMAAQgRAAgLgMQgKgLAAgSQAAgSAKgLQALgMARAAQANAAAIAHIAAgFIAaAAIAABRQAAARgLALQgLAKgTAAQgmAAgFgggAJ4AAQAAASAPAAQAHgBAEgEQAEgEAAgIIAAgCQAAgHgEgFQgFgEgGAAQgPAAAAARgALLAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgALbAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAILAeQgLgLAAgTQAAgSALgLQAMgMASAAQASAAAKAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgKAHQgLAHgOAAQgTAAgMgLgAI0gIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgAFOAZQgRgQAAgaQAAgaARgRQAQgQAbAAQAbAAARAQQARARAAAaQAAAagRAQQgRAQgbAAQgbAAgQgQgAFjgpQgIAJAAAPQAAAPAIAJQAIAIAOAAQAOAAAIgIQAJgJAAgPQAAgPgJgJQgIgIgOgBQgOABgIAIgACHAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgACXAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAAJAeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgPAAQgTAAgLgLgAAygIQgBgMgLAAQgKAAgBAMIAXAAIAAAAgAiVASQAAgWAigCIAJAAIAAgEQAAgIgGAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAh6AQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAlOAfQgNgKAAgTIAegBQAAAGAFAEQAFAFAHAAQANgBAAgIQAAgHgTgFQgTgFgIgGQgLgHAAgQQAAgQAKgJQALgMAUAAQAUAAAMALQAMAJABASIgeABQAAgNgOAAQgMAAAAAKQAAAEAEACQADADAMADQATAEAIAHQALAJAAANQAAASgMAKQgMAIgTAAQgVAAgNgKgAoUANIAAgdIgOAAIAAgXIAOAAIABgZIAbAAIAAAZIARAAIAAAXIgRAAIAAAWQAAALALAAIAGgBIAAAYIgNABQggAAAAgcgAqjASQAAgWAigCIAKAAIAAgEQAAgIgHAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAqIAQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAr0AeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgOAAQgTAAgMgLgArLgIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgANWAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAhOIAaAAIAAAFQAGgHAOAAQAOAAAIAIQAJAJAAAPIAAAwgAHGAnIAAhOIAbAAIAAAGQAHgHAOAAIAAAbQgJAAgGAFQgFAEAAAGIAAAlgADlAnIAAg3IgOAAIAAgXIAOAAIAAgFQAAgQAKgKQAKgJAQAAIAJAAIAAAZIgGgBQgFAAgDADQgDADAAAEIAAAGIARAAIAAAXIgRAAIAAA3gAg7AnIAAhOIAbAAIAAAGQAGgHAPAAIAAAbQgKAAgFAFQgFAEAAAGIAAAlgAjAAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAGgGAMAAQAOAAAIAIQAJAJAAAPIAAAwgAmnAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAHgGALAAQAOAAAIAIQAJAJAAAPIAAAwgApJAnIAAh1IAcAAIAAB1gAstAnIAAgsIgmAAIAAAsIgeAAIAAhwIAeAAIAAAqIAmAAIAAgqIAeAAIAABwg");
	this.shape_6.setTransform(0.175,134.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HS_logowhite, new cjs.Rectangle(-88.7,0,177.5,143), null);


(lib.HEAD3type = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgQAQQgGgGAAgKQAAgJAGgGQAHgGAJAAQAKAAAHAGQAFAGABAJQgBAKgFAGQgHAGgKAAQgJAAgHgGg");
	this.shape.setTransform(88.95,84.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgfA2QgOgIgHgOQgIgOAAgSQAAgSAIgOQAIgOAOgHQAOgIARAAQAeAAAPARQAPARAAAdIAAAFIhQAAQABAPAHAIQAHAIAOAAQALAAAHgFQAIgFADgKIAVAMQgFAKgHAGQgGAIgMADQgKAFgQAAQgVgBgOgHgAAWgKQAAgQgFgHQgFgHgKABQgKgBgFAHQgGAIAAAPIApAAIAAAAg");
	this.shape_1.setTransform(79.6,80.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgtBaQgOgDgGgFQgHgGAAgHQAAgIAIgGQAHgFAPgDQgMgEgGgFQgGgHAAgKQAAgJAFgGQAGgGAKgDQgIgFgEgHQgFgJAAgKQAAgNAIgKQAHgIANgFQANgGARAAQAKAAAJACQAJACAHAEQACgLAGgGQAGgGAKAAQAIAAAFAEQAFAFAAAHQAAAHgEAFQgEAEgHAAQgEAAgEgCQgDgCgCgEIgCADIgDADQAGAFADAGQADAHAAAJQgBANgHAIQgHAKgNADQgNAFgRAAIgNgBIgNgCIgFACQgBAAAAABQAAAAAAABQgBAAAAABQAAAAAAABQAAAEADACQAEABAHAAIASAAIASAAIAQAAQAUAAAJAJQAJAKAAAPQAAAVgSALQgRALgkAAQgYAAgPgCgAgmA5QgEAEAAAFQAAAFAJADQAJADAUgBQAUAAAKgDQAKgEAAgHQABgHgFgCQgEgDgLAAIgtAAQgGADgEAEgAgTg0QgEAFAAALIAAAEQAAAKAEAFQAFAFAJAAQAIAAAFgFQAEgFAAgKIAAgFQAAgLgEgEQgFgGgIAAIgBAAQgJAAgEAGg");
	this.shape_2.setTransform(66.425,82.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag2A1QgJgJAAgOQAAgPAKgIQALgJARgEQARgFAUgDIAAgGQAAgLgFgFQgFgEgKAAIgHAAIgGACQACACABACIAAAHQAAAIgFAFQgGAEgJABQgKAAgGgGQgGgFAAgJQABgMAHgGQAHgIANgCQANgEARAAQAcAAANAJQANAJAAAXIAAAyIABAGQAAAAAAABQABAAAAAAQABAAAAAAQABAAAAAAIAIAAIAAAWIgrAAIgFgJIgDgLQgDAHgGAFQgGAFgIADQgIADgJAAQgRgBgKgIgAgPAIQgKAFgBAMQABAGADAEQAEADAHAAQALAAAGgIQAGgHAAgNIAAgJQgQADgLAEg");
	this.shape_3.setTransform(52.525,80.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag3A8IAAgVIAIAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAQABgBAAgFIAAg7IgBgGQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAgBAAIgJAAIAAgVIAYAAIARgBIAMgCIAAAaQADgOAIgGQAIgGAMAAQANAAAIAIQAIAJAAAPQAAANgHAHQgHAHgLAAQgIAAgFgEQgFgFAAgHQAAgGADgEQACgEAFgDIgDgBIgEgBQgKAAgFAJQgEAKgBAQIAAAgQAAAFACABQAAAAAAAAQABABAAAAQAAAAAAAAQAAAAABAAIAJAAIAAAVg");
	this.shape_4.setTransform(39.825,80.425);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgfA2QgOgIgIgOQgHgOAAgSQAAgSAIgOQAIgOAOgHQAOgIARAAQAeAAAPARQAPARAAAdIAAAFIhQAAQABAPAHAIQAHAIAOAAQALAAAHgFQAIgFADgKIAVAMQgFAKgHAGQgGAIgMADQgKAFgQAAQgVgBgOgHgAAWgKQAAgQgFgHQgFgHgKABQgKgBgFAHQgGAIAAAPIApAAIAAAAg");
	this.shape_5.setTransform(27.4,80.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgOA7IgnhZQgCgFgCgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgHAAIAAgVIBDAAIAAAVIgIAAQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAAAABQgCACACAEIAFANIAIASIAHATIAJgVIAIgSIAEgLQABgEgBgCQgBgCgEAAIgJAAIAAgVIA3AAIAAAVIgIAAQgDAAgCABQgCACgCAEIgnBZg");
	this.shape_6.setTransform(14.075,80.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AghA2QgOgHgIgOQgIgPAAgSQAAgSAIgOQAIgOAPgHQAOgIATAAQATAAAOAIQAOAHAIAOQAIAOAAASQAAASgIAPQgIAOgOAHQgPAIgTAAQgTAAgOgIgAgRgeQgGAJAAAUIAAADQAAAUAGAIQAFAJAMAAQANAAAGgJQAFgIAAgUIAAgDQAAgUgFgJQgGgJgNABIAAgBQgMAAgFAJg");
	this.shape_7.setTransform(0.225,80.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgqAtQgRgQAAgdQAAgdARgQQARgPAegBQAaAAAPAKQAOALAAATQAAANgHAHQgGAGgMAAQgJAAgGgFQgFgEAAgIQAAgIAEgFQAEgGAIgBQgDgEgFgCQgFgCgIAAQgOAAgHAKQgIAIAAATIAAADQAAAUAHAIQAIAKANAAQALAAAHgFQAHgFAEgLIAVALQgFAPgNAKQgNAJgXAAQgegBgRgQg");
	this.shape_8.setTransform(-12.725,80.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgOBEQgJgJAAgVIAAg7IgPAAIAAgTIAIgBQAHgBAEgEQAFgDABgHIADgUIAaAAIAAAiIAVAAIAAAVIgWAAIAAA7QAAAJADADQAEADAHAAIAFAAIAFgBIAAAWIgKACIgNABIgCAAQgTAAgJgJg");
	this.shape_9.setTransform(-29.075,79.0513);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAHA8IAAgVIAHAAQABAAAAAAQAAAAABAAQAAAAABgBQAAAAABAAQABgBAAgFIAAgtQAAgLgFgFQgEgFgIAAQgJAAgGAIQgFAHAAARIAAAiQAAAFACABQAAAAAAAAQAAABABAAQAAAAABAAQAAAAAAAAIAHAAIAAAVIg/AAIAAgVIAIAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAgFIAAg7IgBgGQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgIAAIAAgVIAXAAIAQgBIANgCIAAAWQAFgLAKgGQAJgFAOAAQASAAAKALQAKALAAAXIAAAuQAAAFABABQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAIAAAVg");
	this.shape_10.setTransform(-40.2,80.425);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgeA2QgPgIgIgOQgGgOAAgSQgBgSAIgOQAIgOAOgHQAOgIASAAQAdAAAPARQAOARAAAdIAAAFIhPAAQABAPAHAIQAHAIAOAAQALAAAIgFQAGgFAEgKIAUAMQgEAKgGAGQgIAIgKADQgMAFgPAAQgUgBgOgHgAAWgKQAAgQgFgHQgFgHgKABQgJgBgGAHQgFAIgCAPIAqAAIAAAAg");
	this.shape_11.setTransform(-54.1,80.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAsA8IAAgVIAGAAQABAAAAAAQABAAAAAAQAAAAABgBQAAAAAAAAQACgBAAgFIAAgrQAAgMgEgFQgEgFgJAAQgJAAgFAHQgEAHAAAPIAAAkQAAAFABABQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIAIAAIAAAVIg+AAIAAgVIAHAAQAAAAABAAQAAAAABAAQAAAAAAgBQABAAAAAAQABgBAAgFIAAgsQAAgLgEgFQgEgFgIAAQgKAAgEAHQgFAHAAAPIAAAkQAAAFACABQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAIAHAAIAAAVIhAAAIAAgVIAIAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAQABgBAAgFIAAg7IgBgGQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgIAAIAAgVIAXAAIARgBIAMgCIAAAWQAFgKAJgGQAJgGAOAAQAOAAAHAGQAJAGADANQAFgMAJgHQAKgGAPAAQATAAAKALQAKALAAAYIAAAtQAAAFABABQABAAAAAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAIAAAVg");
	this.shape_12.setTransform(-71.375,80.425);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgOBEQgJgJAAgVIAAg7IgPAAIAAgTIAIgBQAHgBAEgEQAFgDABgHIADgUIAaAAIAAAiIAVAAIAAAVIgWAAIAAA7QAAAJADADQAEADAHAAIAFAAIAFgBIAAAWIgKACIgNABIgCAAQgTAAgJgJg");
	this.shape_13.setTransform(-86.725,79.0513);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ag2A1QgJgJAAgOQAAgPAKgIQALgJARgEQARgFAUgDIAAgGQAAgLgFgFQgFgEgKAAIgHAAIgGACQACACABACIAAAHQAAAIgFAFQgGAEgJABQgKAAgGgGQgGgFAAgJQABgMAHgGQAHgIANgCQANgEARAAQAcAAANAJQANAJAAAXIAAAyIABAGQAAAAAAABQABAAAAAAQABAAAAAAQABAAAAAAIAIAAIAAAWIgrAAIgFgJIgDgLQgDAHgGAFQgGAFgIADQgIADgJAAQgRgBgKgIgAgPAIQgKAFgBAMQABAGADAEQAEADAHAAQALAAAGgIQAGgHAAgNIAAgJQgQADgLAEg");
	this.shape_14.setTransform(-97.225,80.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgeA2QgPgIgIgOQgGgOgBgSQAAgSAIgOQAIgOAOgHQAOgIARAAQAeAAAPARQAPARAAAdIAAAFIhQAAQAAAPAIAIQAIAIANAAQAMAAAGgFQAIgFADgKIAVAMQgFAKgGAGQgIAIgKADQgMAFgPAAQgUgBgOgHgAAWgKQAAgQgFgHQgFgHgKABQgJgBgGAHQgFAIgBAPIApAAIAAAAg");
	this.shape_15.setTransform(-110.55,80.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag3A8IAAgVIAIAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAQABgBAAgFIAAg7IgBgGQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAgBAAIgJAAIAAgVIAYAAIARgBIAMgCIAAAaQADgOAIgGQAIgGAMAAQANAAAIAIQAIAJAAAPQAAANgHAHQgHAHgLAAQgIAAgFgEQgFgFAAgHQAAgGADgEQACgEAFgDIgDgBIgEgBQgKAAgFAJQgEAKgBAQIAAAgQAAAFACABQAAAAAAAAQABABAAAAQAAAAAAAAQAAAAABAAIAJAAIAAAVg");
	this.shape_16.setTransform(-122.825,80.425);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgOBEQgJgJAAgVIAAg7IgPAAIAAgTIAIgBQAHgBAEgEQAFgDABgHIADgUIAaAAIAAAiIAVAAIAAAVIgWAAIAAA7QAAAJADADQAEADAHAAIAFAAIAFgBIAAAWIgKACIgNABIgCAAQgTAAgJgJg");
	this.shape_17.setTransform(-133.125,79.0513);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgfA2QgOgIgHgOQgIgOAAgSQAAgSAIgOQAIgNAOgIQAOgIARAAQAeAAAPARQAPAQAAAeIAAAFIhQAAQABAPAHAIQAHAIAOAAQALAAAHgFQAIgGADgIIAVALQgFAJgHAIQgGAGgMAEQgKAFgQAAQgVAAgOgIgAAWgKQAAgQgFgHQgFgHgKAAQgKAAgFAHQgGAIAAAPIApAAIAAAAg");
	this.shape_18.setTransform(13.9,50.15);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgcA6IgVgFIAAggIAbAAIAAATIAIABIALABQAHAAAGgDQAFgDAAgHQAAgHgHgDQgHgDgLgCQgJgCgJgDQgKgEgGgHQgGgGgBgNQAAgTAOgKQAOgLAYAAQAPAAAMADQAMADAGAEIAAAdIgaAAIAAgRIgHgCIgJgBQgIABgFADQgFADAAAGQAAAFADACQAEADAFACIAMACQAKACAJAEQAKADAGAHQAGAHABANQgBATgOALQgOALgYAAQgPgBgMgDg");
	this.shape_19.setTransform(1.95,50.15);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgwAxQgJgKAAgXIAAgvIgBgGIgEgBIgJAAIAAgVIA1AAIAABKQAAALAFAFQAEAEAHAAQAKAAAFgHQAFgIAAgPIAAgkIgBgGIgDgBIgLAAIAAgVIA3AAIAABXIABAGQAAABAAAAQAAAAABAAQAAABABAAQAAAAABAAIAJAAIAAAVIgYAAIgRABIgMABIAAgUQgGALgJAFQgJAFgNAAQgTAAgKgLg");
	this.shape_20.setTransform(-10.9,50.325);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgeA2QgPgIgIgOQgGgOAAgSQgBgSAIgOQAIgNAOgIQAOgIASAAQAdAAAPARQAOAQAAAeIAAAFIhPAAQABAPAHAIQAHAIAOAAQALAAAIgFQAGgGAEgIIAUALQgEAJgGAIQgIAGgKAEQgMAFgPAAQgUAAgOgIgAAWgKQAAgQgFgHQgFgHgKAAQgJAAgGAHQgFAIgCAPIAqAAIAAAAg");
	this.shape_21.setTransform(-30.25,50.15);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgqAuQgRgRAAgdQAAgcARgQQARgRAeAAQAaAAAPAKQAOALAAATQAAAMgHAIQgGAGgMAAQgJAAgGgFQgFgFAAgIQAAgHAEgFQAEgFAIgCQgDgEgFgCQgFgCgIAAQgOAAgHAJQgIAJAAATIAAAEQAAASAHAKQAIAJANAAQALAAAHgFQAHgGAEgJIAVALQgFAOgNAKQgNAIgXABQgegBgRgPg");
	this.shape_22.setTransform(-42.875,50.15);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAHA8IAAgVIAHAAQABAAAAAAQAAAAABAAQAAAAABgBQAAAAABAAQABgBAAgFIAAgtQAAgLgFgFQgDgFgJAAQgJAAgGAIQgEAHgBARIAAAiQAAAFACABQAAAAAAAAQAAABABAAQAAAAABAAQAAAAAAAAIAIAAIAAAVIhAAAIAAgVIAIAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAgFIAAg7IgBgGQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgIAAIAAgVIAXAAIAQgBIANgCIAAAWQAFgLAKgGQAJgFAOAAQASAAAKALQAKALAAAXIAAAuQAAAFABABQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAIAAAVg");
	this.shape_23.setTransform(-56.5,49.975);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("Ag2A1QgJgJAAgOQAAgPAKgJQALgHARgFQARgFAUgDIAAgGQAAgLgFgEQgFgFgKAAIgHAAIgGABQACACABAEIAAAGQAAAIgFAFQgGAEgJABQgKAAgGgGQgGgEAAgLQABgKAHgIQAHgHANgDQANgDARAAQAcAAANAJQANAKAAAVIAAAzIABAGQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAIAAIAAAUIgrAAIgFgIIgDgLQgDAHgGAFQgGAFgIADQgIADgJAAQgRAAgKgJgAgPAJQgKAFgBAKQABAHADAEQAEADAHAAQALABAGgJQAGgHAAgNIAAgIQgQABgLAGg");
	this.shape_24.setTransform(-70.575,50.15);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgOBEQgJgJAAgVIAAg7IgPAAIAAgTIAIgBQAHgBAEgEQAFgDABgHIADgUIAaAAIAAAiIAVAAIAAAVIgWAAIAAA7QAAAJADADQAEADAHAAIAFAAIAFgBIAAAWIgKACIgNABIgCAAQgTAAgJgJg");
	this.shape_25.setTransform(-81.775,48.6013);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgdA6IgUgFIAAggIAbAAIAAATIAIABIAKABQAJAAAFgDQAFgDAAgHQAAgHgHgDQgHgDgKgCQgKgCgKgDQgJgEgGgHQgGgGgBgNQABgTAOgKQANgLAZAAQAOAAAMADQAMADAHAEIAAAdIgbAAIAAgRIgHgCIgJgBQgIABgFADQgFADAAAGQAAAFADACQADADAGACIAMACQAKACAJAEQAKADAGAHQAHAHgBANQAAATgNALQgPALgZAAQgPgBgMgDg");
	this.shape_26.setTransform(-91.15,50.15);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgIBLQgLgIgEgOIgGAaIgcAAIAAgFIAAgNIAAgWIAAhZIgBgGQAAgBAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgJAAIAAgVIAYAAIARgBIAMgCIAABCQAFgMAKgGQAJgGAOAAQAQAAALAIQALAHAGAOQAGANAAASQAAATgGAOQgHAOgLAIQgMAIgQAAQgRgBgKgHgAgKgHQgHAHAAATIAAAEQAAASAHAJQAGAIAKAAQALAAAHgIQAGgJAAgSIAAgEQAAgSgGgIQgHgJgLAAIgBAAQgJAAgGAJg");
	this.shape_27.setTransform(-104.225,48.075);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgwAxQgKgKAAgXIAAgvIgBgGIgDgBIgIAAIAAgVIA1AAIAABKQAAALADAFQAFAEAHAAQAJAAAGgHQAFgIAAgPIAAgkIgBgGIgEgBIgKAAIAAgVIA2AAIAABXIABAGQABABAAAAQAAAAABAAQAAABABAAQAAAAABAAIAKAAIAAAVIgZAAIgRABIgMABIAAgUQgFALgKAFQgJAFgNAAQgTAAgKgLg");
	this.shape_28.setTransform(-118.7,50.325);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgcA6IgVgFIAAggIAbAAIAAATIAIABIAKABQAIAAAGgDQAFgDAAgHQAAgHgHgDQgHgDgKgCQgLgCgIgDQgKgEgGgHQgGgGgBgNQABgTAOgKQANgLAYAAQAPAAAMADQAMADAGAEIAAAdIgaAAIAAgRIgHgCIgJgBQgIABgFADQgFADAAAGQAAAFADACQADADAGACIAMACQAKACAJAEQAKADAGAHQAHAHAAANQAAATgPALQgNALgZAAQgPgBgMgDg");
	this.shape_29.setTransform(-131.45,50.15);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgeA2QgPgIgIgOQgGgOAAgSQgBgSAIgNQAIgPAOgHQAOgIASAAQAdABAPAQQAOARAAAdIAAAFIhPAAQABAPAHAJQAHAHAOABQALgBAIgFQAGgGAEgJIAUANQgEAIgGAIQgIAGgKAFQgMAEgPAAQgUgBgOgHgAAWgKQAAgQgFgHQgFgHgKABQgJgBgGAIQgFAHgCAPIAqAAIAAAAg");
	this.shape_30.setTransform(28.7,19.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgeA2QgPgIgIgOQgGgOgBgSQAAgSAIgNQAIgPAOgHQAOgIARAAQAeABAPAQQAPARAAAdIAAAFIhQAAQABAPAHAJQAIAHANABQAMgBAGgFQAIgGADgJIAVANQgFAIgHAIQgGAGgMAFQgKAEgQAAQgVgBgNgHgAAWgKQAAgQgFgHQgFgHgKABQgKgBgFAIQgFAHgBAPIApAAIAAAAg");
	this.shape_31.setTransform(15.8,19.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("Ag3A8IAAgVIAIAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgBAAgFIAAg7IgBgGQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAgBAAIgJAAIAAgVIAYAAIARgBIAMgCIAAAaQADgOAIgGQAIgGAMAAQANAAAIAIQAIAJAAAPQAAANgHAHQgHAHgLAAQgIAAgFgEQgFgFAAgHQAAgGADgEQACgEAFgDIgDgBIgEgBQgKAAgFAJQgEAKgBAQIAAAgQAAAFACABQAAAAAAAAQABABAAAAQAAAAAAAAQAAAAABAAIAJAAIAAAVg");
	this.shape_32.setTransform(3.525,19.525);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgkBSIAAgVIAJAAQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABAAQABgCAAgEIAAhDIgQAAIAAgVIAQAAIAAgFQAAgQADgJQAFgJAJgEQAHgEAPAAQAHAAAGABIAJAEIAAAUIgEgBIgEAAQgHAAgEABQgEACgBAGQgBAEAAAKIAVAAIAAAVIgUAAIAABDQAAAEABACQABAAAAAAQABAAAAABQABAAAAAAQAAAAABAAIALAAIAAAVg");
	this.shape_33.setTransform(-6.3,17.35);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgcA7IgVgHIAAgeIAbAAIAAASIAIACIALAAQAHAAAGgCQAFgEAAgHQAAgHgHgDQgHgDgKgCQgLgCgIgEQgKgDgGgHQgGgGgBgNQAAgSAPgLQANgLAYAAQAPAAAMADQAMADAGAEIAAAeIgaAAIAAgSIgHgCIgJAAQgIgBgFAEQgFADAAAGQAAAFADADQADACAGABIAMAEQAKABAJAEQAKADAGAHQAGAHABANQgBATgOALQgNAKgZABQgPAAgMgDg");
	this.shape_34.setTransform(-21.55,19.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("Ag3A8IAAgVIAIAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgBAAgFIAAg7IgBgGQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAgBAAIgJAAIAAgVIAYAAIARgBIAMgCIAAAaQADgOAIgGQAIgGAMAAQANAAAIAIQAIAJAAAPQAAANgHAHQgHAHgLAAQgIAAgFgEQgFgFAAgHQAAgGADgEQACgEAFgDIgDgBIgEgBQgKAAgFAJQgEAKgBAQIAAAgQAAAFACABQAAAAAAAAQABABAAAAQAAAAAAAAQAAAAABAAIAJAAIAAAVg");
	this.shape_35.setTransform(-32.925,19.525);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgfA2QgOgIgHgOQgIgOABgSQAAgSAHgNQAIgPAOgHQAOgIASAAQAdABAPAQQAOARAAAdIAAAFIhPAAQAAAPAIAJQAHAHAOABQALgBAIgFQAGgGAEgJIAUANQgDAIgIAIQgHAGgLAFQgLAEgPAAQgVgBgOgHgAAWgKQAAgQgFgHQgFgHgKABQgJgBgGAIQgGAHgBAPIAqAAIAAAAg");
	this.shape_36.setTransform(-45.35,19.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgkBSIAAgVIAJAAQABAAAAAAQAAAAABAAQAAgBABAAQAAAAAAAAQACgCAAgEIAAhDIgPAAIAAgVIAPAAIAAgFQAAgQADgJQAFgJAIgEQAIgEAPAAQAIAAAFABIAIAEIAAAUIgDgBIgEAAQgHAAgEABQgDACgBAGQgCAEABAKIAUAAIAAAVIgTAAIAABDQAAAEAAACQABAAAAAAQABAAAAABQABAAAAAAQABAAAAAAIALAAIAAAVg");
	this.shape_37.setTransform(-55.65,17.35);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgkBSIAAgVIAJAAQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAAAQABgCAAgEIAAhDIgOAAIAAgVIAOAAIAAgFQAAgQAFgJQAEgJAIgEQAJgEAOAAQAHAAAGABIAIAEIAAAUIgDgBIgFAAQgGAAgEABQgEACAAAGQgCAEAAAKIAVAAIAAAVIgTAAIAABDQAAAEABACQAAAAAAAAQABAAAAABQABAAAAAAQABAAAAAAIAKAAIAAAVg");
	this.shape_38.setTransform(-63.6,17.35);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AghA2QgOgIgIgOQgIgNAAgTQAAgRAIgOQAIgPAPgHQAOgIATAAQATAAAOAIQAOAHAIAPQAIANAAASQAAATgIANQgIAOgOAIQgPAIgTAAQgTAAgOgIgAgRgeQgGAJAAAUIAAADQAAAUAGAJQAFAIAMABQANgBAGgIQAFgJAAgUIAAgDQAAgUgFgJQgGgJgNABIAAgBQgMAAgFAJg");
	this.shape_39.setTransform(-74.525,19.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AhFBQIAAgVIAKAAQABAAAAAAQABAAABgBQAAAAAAAAQABAAAAgBQACgCAAgEIAAhlQAAgEgCgCQAAgBgBAAQAAAAAAAAQgBgBgBAAQAAAAgBAAIgKAAIAAgVIBLAAQAgAAAQAMQAQAMAAAYQAAAZgPALQgQAMgiAAIgRAAIAAAiIABAGQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIAKAAIAAAVgAgMgDIAPAAQANAAAGgGQAGgHAAgOQAAgPgGgGQgGgGgNAAIgPAAg");
	this.shape_40.setTransform(-94.4,17.575);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAOBQIAAgVIAKAAQABAAAAAAQABAAAAgBQABAAAAAAQAAAAABgBIABgGIAAgqIg5AAIAAAqIABAGQAAABABAAQAAAAABAAQAAABABAAQABAAAAAAIAKAAIAAAVIhIAAIAAgVIAKAAQABAAABAAQAAAAABgBQAAAAABAAQAAAAAAgBQACgCAAgEIAAhlQAAgEgCgCQAAgBAAAAQgBAAAAAAQgBgBAAAAQgBAAgBAAIgKAAIAAgVIBIAAIAAAVIgKAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBAAAAABIgBAGIAAAoIA5AAIAAgoIgBgGQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgKAAIAAgVIBIAAIAAAVIgKAAQgBAAgBAAQAAAAgBABQAAAAgBAAQAAAAAAABIgBAGIAABlIABAGQAAABAAAAQABAAAAAAQABABAAAAQABAAABAAIAKAAIAAAVg");
	this.shape_41.setTransform(-110.675,17.575);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgsBJQgRgKgKgTQgKgTAAgZQAAgYAKgTQALgSASgKQATgLAYAAQAaAAASAKQASALAJASQAKATAAAYQAAAZgKATQgKATgTAKQgSAKgZAAQgZAAgTgKgAgbgsQgKAMAAAcIAAAKQAAAbAJANQAKAMASAAQATAAAKgMQAKgNAAgbIAAgKQAAgcgKgMQgJgNgUAAQgRAAgKANg");
	this.shape_42.setTransform(-128.3,17.575);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD3type, new cjs.Rectangle(-139,0,289.1,95.4), null);


(lib.HEAD2type = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgQAQQgGgGAAgKQAAgJAGgGQAHgGAJAAQAKAAAHAGQAFAGABAJQgBAKgFAGQgHAGgKAAQgJAAgHgGg");
	this.shape.setTransform(25.15,54.125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgtBLQgMgIgGgOQgGgOAAgTQAAgSAGgNQAHgOALgHQAMgIAPAAQAPAAAIAFQAJAFAFALIAAgfIgBgGQAAgBgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgJAAIAAgVIAYAAIARgBIAMgCIAACFQAAAFABABQABAAAAAAQAAABABAAQAAAAABAAQAAAAABAAIAHAAIAAAVIgvAAIgBgHIgBgOQgEAMgKAGQgJAHgPAAQgQAAgMgIgAgWgHQgGAIAAASIAAAEQAAASAGAJQAHAIALAAQAKAAAGgIQAGgJABgSIAAgEQgBgSgGgIQgGgJgKAAIgBAAQgLAAgGAJg");
	this.shape_1.setTransform(14.925,48.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeA2QgPgIgIgOQgGgOgBgSQAAgSAIgOQAIgNAOgIQAOgIARAAQAeAAAPARQAPAQAAAeIAAAFIhQAAQAAAPAIAIQAIAIANAAQAMAAAGgFQAIgGADgIIAVALQgFAJgGAIQgIAGgKAEQgMAFgPAAQgUAAgOgIgAAWgKQAAgQgFgHQgFgHgKAAQgJAAgGAHQgFAIgBAPIApAAIAAAAg");
	this.shape_2.setTransform(1.05,50.15);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfA2QgOgIgHgOQgIgOAAgSQABgSAHgOQAIgNAOgIQAOgIARAAQAeAAAPARQAPAQAAAeIAAAFIhQAAQAAAPAIAIQAIAIANAAQALAAAHgFQAHgGAEgIIAUALQgDAJgIAIQgGAGgMAEQgLAFgPAAQgVAAgOgIgAAWgKQAAgQgFgHQgFgHgKAAQgKAAgFAHQgGAIAAAPIApAAIAAAAg");
	this.shape_3.setTransform(-11.85,50.15);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAHA8IAAgVIAHAAQABAAAAAAQAAAAABAAQAAAAABgBQAAAAABAAQABgBAAgFIAAgtQAAgLgFgFQgDgFgJAAQgJAAgGAIQgEAHgBARIAAAiQAAAFACABQAAAAAAAAQAAABABAAQAAAAABAAQAAAAAAAAIAIAAIAAAVIhAAAIAAgVIAIAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAgFIAAg7IgBgGQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgIAAIAAgVIAXAAIAQgBIAMgCIAAAWQAHgLAJgGQAJgFAOAAQATAAAJALQAKALAAAXIAAAuQAAAFABABQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAIAAAVg");
	this.shape_4.setTransform(-25.55,49.975);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgwAxQgKgKAAgXIAAgvIgBgGIgDgBIgJAAIAAgVIA2AAIAABKQAAALADAFQAFAEAIAAQAIAAAGgHQAFgIAAgPIAAgkIgBgGIgEgBIgKAAIAAgVIA2AAIAABXIABAGQABABAAAAQAAAAABAAQAAABABAAQAAAAABAAIAKAAIAAAVIgZAAIgRABIgMABIAAgUQgFALgLAFQgIAFgNAAQgTAAgKgLg");
	this.shape_5.setTransform(-45.95,50.325);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AghA2QgOgHgIgPQgIgOAAgSQAAgSAIgOQAIgNAPgIQAOgIATAAQATAAAOAIQAOAIAIANQAIAOAAASQAAASgIAOQgIAPgOAHQgPAIgTAAQgTAAgOgIgAgRgeQgGAJAAAUIAAADQAAAUAGAIQAFAKAMgBQANABAGgKQAFgIAAgUIAAgDQAAgUgFgJQgGgJgNAAIAAAAQgMAAgFAJg");
	this.shape_6.setTransform(-60.025,50.15);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag7BKQgJgIAAgMQAAgLAFgGQAGgGAKAAQAIAAAFAEQAFAEABAHQABAGgEAIQAHgCAFgGQAFgGADgKIAAgBIgohXIgEgGQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAIgGAAIAAgVIBBAAIAAAVIgGAAQgBAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQgBADABADIAVAvIASgvQACgEgCgCQgBgCgEAAIgHAAIAAgVIA0AAIAAAVIgHAAIgFABIgEAGIgjBVQgGAQgHALQgGAKgJAGQgKAFgOAAQgQAAgJgHg");
	this.shape_7.setTransform(-73.825,52.425);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgfA2QgOgIgHgOQgIgOABgSQAAgSAHgOQAIgNAOgIQAOgIASAAQAdAAAPARQAOAQAAAeIAAAFIhPAAQAAAPAIAIQAHAIAOAAQALAAAIgFQAGgGAEgIIAUALQgEAJgGAIQgIAGgKAEQgLAFgQAAQgUAAgPgIgAAWgKQAAgQgFgHQgFgHgKAAQgKAAgFAHQgGAIgBAPIAqAAIAAAAg");
	this.shape_8.setTransform(-92.7,50.15);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag3A8IAAgVIAIAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAQABgBAAgFIAAg7IgBgGQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAgBAAIgJAAIAAgVIAYAAIARgBIAMgCIAAAaQADgOAIgGQAIgGAMAAQANAAAIAIQAIAJAAAPQAAANgHAHQgHAHgLAAQgIAAgFgEQgFgFAAgHQAAgGADgEQACgEAFgDIgDgBIgEgBQgKAAgFAJQgEAKgBAQIAAAgQAAAFACABQAAAAAAAAQABABAAAAQAAAAAAAAQAAAAABAAIAJAAIAAAVg");
	this.shape_9.setTransform(-104.975,49.975);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag2A1QgJgJAAgOQAAgPAKgJQALgHARgFQARgFAUgDIAAgGQAAgLgFgEQgFgFgKAAIgHAAIgGABQACACABAEIAAAGQAAAIgFAFQgGAEgJABQgKAAgGgGQgGgEAAgLQABgKAHgIQAHgHANgDQANgDARAAQAcAAANAJQANAKAAAVIAAAzIABAGQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAIAAIAAAUIgrAAIgFgIIgDgLQgDAHgGAFQgGAFgIADQgIADgJAAQgRAAgKgJgAgPAJQgKAFgBAKQABAHADAEQAEADAHAAQALABAGgJQAGgHAAgNIAAgIQgQABgLAGg");
	this.shape_10.setTransform(-117.575,50.15);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgqAuQgRgRAAgdQAAgcARgQQARgRAeAAQAaAAAPAKQAOALAAATQAAAMgHAIQgGAGgMAAQgJAAgGgFQgFgFAAgIQAAgHAEgFQAEgFAIgCQgDgEgFgCQgFgCgIAAQgOAAgHAJQgIAJAAATIAAAEQAAASAHAKQAIAJANAAQALAAAHgFQAHgGAEgJIAVALQgFAOgNAKQgNAIgXABQgegBgRgPg");
	this.shape_11.setTransform(-130.625,50.15);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgfA2QgOgIgHgOQgIgOAAgSQABgSAHgNQAIgPAOgHQAOgIASAAQAdABAPAQQAPARAAAdIAAAFIhQAAQAAAPAIAJQAIAHANABQALgBAHgFQAHgGAEgJIAUANQgDAIgIAIQgGAGgMAFQgLAEgPAAQgVgBgOgHgAAWgKQAAgQgFgHQgFgHgKABQgKgBgFAIQgGAHAAAPIApAAIAAAAg");
	this.shape_12.setTransform(54.3,19.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAIBRIAAgVIAHAAQAAAAAAAAQABAAAAAAQABgBAAAAQAAAAAAAAQACgCAAgEIAAguQAAgKgEgFQgEgFgJAAQgIAAgGAIQgFAHAAAQIAAAjQAAAEABACQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAAAIAHAAIAAAVIhAAAIAAgVIAIAAQABAAABAAQAAAAABAAQAAgBAAAAQABAAAAAAQABgCAAgEIAAhlIgBgHQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBgBgBAAIgJAAIAAgUIAZAAIARgBIAMgCIAAA+QAGgKAJgFQAJgGANABQATgBAKALQAKALAAAXIAAAvQAAAEABACQAAAAAAAAQABAAAAABQABAAAAAAQABAAAAAAIAJAAIAAAVg");
	this.shape_13.setTransform(40.55,17.45);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgOBEQgJgJAAgVIAAg7IgPAAIAAgTIAIgBQAHgBAEgEQAFgDABgHIADgUIAaAAIAAAiIAVAAIAAAVIgWAAIAAA7QAAAJADADQAEADAHAAIAFAAIAFgBIAAAWIgKACIgNABIgCAAQgTAAgJgJg");
	this.shape_14.setTransform(28.925,18.1513);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgOBEQgJgJAAgVIAAg7IgPAAIAAgTIAIgBQAHgBAEgEQAFgDABgHIADgUIAaAAIAAAiIAVAAIAAAVIgWAAIAAA7QAAAJADADQAEADAHAAIAFAAIAFgBIAAAWIgKACIgNABIgCAAQgTAAgJgJg");
	this.shape_15.setTransform(15.075,18.1513);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgeA2QgPgIgIgOQgGgOAAgSQgBgSAIgNQAIgPAOgHQAOgIARAAQAeABAPAQQAPARAAAdIAAAFIhQAAQABAPAHAJQAIAHANABQAMgBAGgFQAIgGADgJIAVANQgEAIgHAIQgIAGgKAFQgMAEgPAAQgUgBgOgHgAAWgKQAAgQgFgHQgFgHgKABQgJgBgGAIQgFAHgBAPIApAAIAAAAg");
	this.shape_16.setTransform(4.75,19.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgtBZQgOgCgGgGQgHgEAAgIQAAgIAIgGQAHgGAPgDQgMgCgGgHQgGgGAAgKQAAgIAFgHQAGgGAKgCQgIgGgEgIQgFgIAAgKQAAgNAIgJQAHgKANgFQANgFARAAQAKAAAJACQAJACAHAEQACgLAGgGQAGgGAKAAQAIAAAFAEQAFAFAAAHQAAAIgEAEQgEAEgHAAQgEAAgEgCQgDgCgCgDIgCACIgDACQAGAGADAGQADAHAAAIQgBANgHAKQgHAIgNAEQgNAFgRAAIgNgBIgNgCIgFACQgBAAAAABQAAAAAAABQgBAAAAABQAAAAAAABQAAAEADACQAEABAHABIASAAIASgBIAQAAQAUAAAJAKQAJAJAAAPQAAAVgSALQgRALgkAAQgYAAgPgDgAgmA4QgEAFAAAEQAAAHAJACQAJADAUAAQAUgBAKgEQAKgDAAgHQABgHgFgCQgEgCgLAAIgtAAQgGACgEADgAgTg1QgEAGAAALIAAAEQAAAKAEAFQAFAFAJAAQAIAAAFgFQAEgFAAgLIAAgEQAAgKgEgGQgFgFgIABIgBgBQgJAAgEAFg");
	this.shape_17.setTransform(-8.425,21.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AghA2QgOgIgIgOQgIgNAAgTQAAgRAIgOQAIgPAPgHQAOgIATAAQATAAAOAIQAOAHAIAPQAIANAAASQAAATgIANQgIAOgOAIQgPAIgTAAQgTAAgOgIgAgRgeQgGAJAAAUIAAADQAAAUAGAJQAFAIAMABQANgBAGgIQAFgJAAgUIAAgDQAAgUgFgJQgGgJgNABIAAgBQgMAAgFAJg");
	this.shape_18.setTransform(-28.175,19.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgOBEQgJgJAAgVIAAg7IgPAAIAAgTIAIgBQAHgBAEgEQAFgDABgHIADgUIAaAAIAAAiIAVAAIAAAVIgWAAIAAA7QAAAJADADQAEADAHAAIAFAAIAFgBIAAAWIgKACIgNABIgCAAQgTAAgJgJg");
	this.shape_19.setTransform(-39.275,18.1513);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgfA2QgOgIgHgOQgIgOABgSQAAgSAHgNQAIgPAOgHQAOgIASAAQAdABAPAQQAOARAAAdIAAAFIhPAAQAAAPAIAJQAHAHAOABQALgBAIgFQAGgGAEgJIAUANQgDAIgIAIQgHAGgLAFQgLAEgPAAQgVgBgOgHgAAWgKQAAgQgFgHQgFgHgKABQgJgBgGAIQgGAHgBAPIAqAAIAAAAg");
	this.shape_20.setTransform(-55.25,19.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAsA8IAAgVIAGAAQABAAAAAAQABAAAAAAQAAAAABgBQAAAAAAAAQACgBAAgFIAAgrQAAgMgEgFQgEgFgJAAQgJAAgFAHQgEAHAAAPIAAAkQAAAFABABQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIAIAAIAAAVIg+AAIAAgVIAHAAQAAAAABAAQAAAAABAAQAAAAAAgBQABAAAAAAQABgBAAgFIAAgsQAAgLgEgFQgEgFgIAAQgKAAgEAHQgFAHAAAPIAAAkQAAAFACABQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAIAHAAIAAAVIhAAAIAAgVIAIAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAQABgBAAgFIAAg7IgBgGQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgIAAIAAgVIAXAAIARgBIAMgCIAAAWQAFgKAJgGQAJgGAOAAQAOAAAHAGQAJAGADANQAFgMAJgHQAKgGAPAAQATAAAKALQAKALAAAYIAAAtQAAAFABABQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAIAAAVg");
	this.shape_21.setTransform(-72.525,19.525);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AggBUIAAgVIAJAAQABAAAAAAQABAAAAAAQABgBAAAAQAAAAAAAAIABgGIAAg5IgBgIQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAIgJAAIAAgVIAZAAIAPgBIAMgCIAABbIABAGQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAAAIAIAAIAAAVgAgPgvQgGgGgBgJQABgJAGgGQAGgGAJAAQALAAAFAGQAHAGgBAJQABAJgHAGQgFAGgLAAQgJAAgGgGg");
	this.shape_22.setTransform(-87.2,17.15);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgOBEQgJgJAAgVIAAg7IgPAAIAAgTIAIgBQAHgBAEgEQAFgDABgHIADgUIAaAAIAAAiIAVAAIAAAVIgWAAIAAA7QAAAJADADQAEADAHAAIAFAAIAFgBIAAAWIgKACIgNABIgCAAQgTAAgJgJg");
	this.shape_23.setTransform(-95.125,18.1513);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgdA7IgUgHIAAgeIAbAAIAAASIAIACIAKAAQAJAAAFgCQAFgEAAgHQAAgHgHgDQgHgDgLgCQgJgCgKgEQgJgDgGgHQgGgGAAgNQgBgSAOgLQAOgLAZAAQAOAAAMADQAMADAHAEIAAAeIgbAAIAAgSIgHgCIgJAAQgIgBgFAEQgFADAAAGQAAAFADADQADACAGABIAMAEQAKABAKAEQAJADAGAHQAHAHgBANQAAATgNALQgOAKgaABQgPAAgMgDg");
	this.shape_24.setTransform(-110.15,19.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgEAiIgFgPIgFgTIgDgQIAAgRIAjAAIAAARQAAAHgDAJIgFATIgFAPg");
	this.shape_25.setTransform(-118.225,13.025);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgOBEQgJgJAAgVIAAg7IgPAAIAAgTIAIgBQAHgBAEgEQAFgDABgHIADgUIAaAAIAAAiIAVAAIAAAVIgWAAIAAA7QAAAJADADQAEADAHAAIAFAAIAFgBIAAAWIgKACIgNABIgCAAQgTAAgJgJg");
	this.shape_26.setTransform(-125.025,18.1513);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgjBQIAAgVIAKAAQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAgBIABgGIAAhlIgBgGQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgKAAIAAgVIBHAAIAAAVIgKAAQgBAAAAAAQgBAAgBABQAAAAAAAAQgBAAAAABIgBAGIAABlIABAGQAAABABAAQAAAAAAAAQABABABAAQAAAAABAAIAKAAIAAAVg");
	this.shape_27.setTransform(-132.95,17.575);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2type, new cjs.Rectangle(-139,0,278,64.9), null);


(lib.HEAD1btype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPAQQgHgGAAgKQAAgJAHgGQAFgGAKAAQALAAAFAGQAHAGAAAJQAAAKgHAGQgFAGgLAAQgKAAgFgGg");
	this.shape.setTransform(67.6,84.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgOBEQgJgJAAgVIAAg7IgPAAIAAgTIAIgBQAHgBAEgEQAFgDABgHIADgUIAaAAIAAAiIAVAAIAAAVIgWAAIAAA7QAAAJADADQAEADAHAAIAFAAIAFgBIAAAWIgKACIgNABIgCAAQgTAAgJgJg");
	this.shape_1.setTransform(60.375,79.0513);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag3A8IAAgVIAIAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgBAAgFIAAg7IgBgGQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAgBAAIgJAAIAAgVIAYAAIARgBIAMgCIAAAaQADgOAIgGQAIgGAMAAQANAAAIAIQAIAJAAAPQAAANgHAHQgHAHgLAAQgIAAgFgEQgFgFAAgHQAAgGADgEQACgEAFgDIgDgBIgEgBQgKAAgFAJQgEAKgBAQIAAAgQAAAFACABQAAAAAAAAQABABAAAAQAAAAAAAAQAAAAABAAIAJAAIAAAVg");
	this.shape_2.setTransform(50.675,80.425);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AghA2QgOgHgIgOQgIgPAAgSQAAgSAIgOQAIgOAPgHQAOgIATAAQATAAAOAIQAOAHAIAOQAIAOAAASQAAASgIAPQgIAOgOAHQgPAIgTAAQgTAAgOgIgAgRgeQgGAJAAAUIAAADQAAAUAGAIQAFAJAMAAQANAAAGgJQAFgIAAgUIAAgDQAAgUgFgJQgGgJgNABIAAgBQgMAAgFAJg");
	this.shape_3.setTransform(37.875,80.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhGBRIAAgVIAJAAQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAAAIABgGIAAhkIgBgHQAAAAAAgBQgBAAAAAAQgBAAAAAAQgBAAAAAAIgJAAIAAgVIAYAAIARgCIAMgCIAAAZQAEgLAKgHQAJgHAPAAQAPAAAMAIQALAHAGAOQAGAOAAASQAAATgGAOQgHAOgLAHQgMAIgQAAQgOAAgIgHQgJgFgFgLIAAAhQAAAEABACQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAAAIAJAAIAAAVgAgLgvQgGAJAAASIAAAEQAAARAHAIQAGAJAKAAQALAAAGgJQAHgIAAgRIAAgEQAAgSgHgIQgGgJgLAAQgKAAgHAIg");
	this.shape_4.setTransform(23.575,82.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhGBRIAAgVIAJAAQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAAAIABgGIAAhkIgBgHQAAAAAAgBQgBAAAAAAQgBAAAAAAQgBAAAAAAIgJAAIAAgVIAYAAIARgCIAMgCIAAAZQAEgLAKgHQAJgHAPAAQAPAAAMAIQALAHAGAOQAGAOAAASQAAATgGAOQgHAOgLAHQgMAIgQAAQgOAAgIgHQgJgFgFgLIAAAhQAAAEABACQABAAAAAAQAAAAAAABQABAAAAAAQABAAAAAAIAJAAIAAAVgAgLgvQgGAJAAASIAAAEQAAARAHAIQAGAJAKAAQALAAAGgJQAHgIAAgRIAAgEQAAgSgHgIQgGgJgLAAQgKAAgHAIg");
	this.shape_5.setTransform(8.775,82.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgwAxQgKgKABgXIAAgvQAAgFgCgBIgDgBIgJAAIAAgVIA1AAIAABKQAAALAEAFQAFAEAIAAQAJAAAFgHQAFgIAAgPIAAgkQAAgFgBgBIgDgBIgLAAIAAgVIA2AAIAABXIACAGQAAABAAAAQAAAAABAAQAAABABAAQAAAAABAAIAKAAIAAAVIgZAAIgRABIgMABIAAgUQgGALgKAFQgIAFgNAAQgTAAgKgLg");
	this.shape_6.setTransform(-5.8,80.775);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgdA7IgUgGIAAggIAbAAIAAATIAIACIALABQAIAAAFgEQAFgDAAgHQAAgHgHgDQgHgDgLgCQgKgCgJgEQgJgDgGgGQgGgIAAgMQAAgSANgLQAOgKAZgBQAOABAMACQAMADAHADIAAAfIgbAAIAAgSIgHgCIgJgBQgIAAgFAEQgFADAAAGQAAAFADADQADACAGACIAMACQAKACAKAEQAJAEAGAGQAGAHAAANQABATgOALQgOAKgaABQgOgBgNgCg");
	this.shape_7.setTransform(-18.55,80.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag7BKQgJgIAAgMQAAgLAFgGQAGgGAKAAQAIAAAFAEQAFAEABAHQABAGgEAIQAHgCAFgGQAFgGADgKIAAgBIgohXIgEgGQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgGAAIAAgVIBBAAIAAAVIgGAAQgBAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQgBADABADIAVAvIASgvQACgEgCgCQgBgCgEAAIgHAAIAAgVIA0AAIAAAVIgHAAIgFABIgEAGIgjBVQgGAQgHALQgGAKgJAGQgKAFgOAAQgQAAgJgHg");
	this.shape_8.setTransform(-36.775,82.875);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag3A8IAAgVIAIAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAQABgBAAgFIAAg7IgBgGQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAgBAAIgJAAIAAgVIAYAAIARgBIAMgCIAAAaQADgOAIgGQAIgGAMAAQANAAAIAIQAIAJAAAPQAAANgHAHQgHAHgLAAQgIAAgFgEQgFgFAAgHQAAgGADgEQACgEAFgDIgDgBIgEgBQgKAAgFAJQgEAKgBAQIAAAgQAAAFACABQAAAAAAAAQABABAAAAQAAAAAAAAQAAAAABAAIAJAAIAAAVg");
	this.shape_9.setTransform(-49.375,80.425);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgfA2QgOgIgHgOQgIgOAAgSQABgSAHgOQAIgOAOgHQAOgIARAAQAeAAAPARQAPARAAAdIAAAFIhQAAQAAAPAIAIQAIAIANAAQALAAAHgFQAHgFAEgKIAUAMQgDAKgIAGQgGAIgMADQgLAFgPAAQgVgBgOgHgAAWgKQAAgQgFgHQgFgHgKABQgKgBgFAHQgGAIAAAPIApAAIAAAAg");
	this.shape_10.setTransform(-61.8,80.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgOA7IgnhZQgCgFgCgBQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAIgHAAIAAgVIBDAAIAAAVIgIAAQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAAAABQgCACACAEIAFANIAIASIAHATIAJgVIAIgSIAEgLQABgEgBgCQgBgCgEAAIgJAAIAAgVIA3AAIAAAVIgIAAQgDAAgCABQgCACgCAEIgnBZg");
	this.shape_11.setTransform(-75.125,80.675);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AghA2QgOgHgIgOQgIgPAAgSQAAgSAIgOQAIgOAPgHQAOgIATAAQATAAAOAIQAOAHAIAOQAIAOAAASQAAASgIAPQgIAOgOAHQgPAIgTAAQgTAAgOgIgAgRgeQgGAJAAAUIAAADQAAAUAGAIQAFAJAMAAQANAAAGgJQAFgIAAgUIAAgDQAAgUgFgJQgGgJgNABIAAgBQgMAAgFAJg");
	this.shape_12.setTransform(-88.975,80.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgqAtQgRgQAAgdQAAgdARgQQARgPAegBQAaAAAPAKQAOALAAATQAAANgHAHQgGAGgMAAQgJAAgGgFQgFgEAAgIQAAgIAEgFQAEgGAIgBQgDgEgFgCQgFgCgIAAQgOAAgHAKQgIAIAAATIAAADQAAAUAHAIQAIAKANAAQALAAAHgFQAHgFAEgLIAVALQgFAPgNAKQgNAJgXAAQgegBgRgQg");
	this.shape_13.setTransform(-101.925,80.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgfA2QgOgIgHgOQgIgOABgSQAAgSAHgOQAIgOAOgHQAOgIASAAQAdAAAPARQAOARAAAdIAAAFIhPAAQAAAPAIAIQAHAIAOAAQALAAAIgFQAGgFAEgKIAUAMQgEAKgGAGQgIAIgKADQgLAFgQAAQgUgBgPgHgAAWgKQAAgQgFgHQgFgHgKABQgKgBgFAHQgGAIgBAPIAqAAIAAAAg");
	this.shape_14.setTransform(-114.75,80.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAtBQQgKAAgGgGQgGgFgEgJQgDgJAAgMQgBgIgCgHQgCgGgEgDQgFgEgIAAIgNAAIAAAoQAAAEABACQAAAAABABQAAAAABAAQAAAAABABQAAAAABAAIAKAAIAAAVIhHAAIAAgVIAKAAQAAAAABAAQAAgBABAAQAAAAABAAQAAgBAAAAQACgCAAgEIAAhlQAAgEgCgCQAAAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAAAIgKAAIAAgVIBTAAQAdAAAPALQANAKAAAXQABAQgJAKQgJAJgRADQAQAEAGALQAIALABAQQABAIABADQADADAFAAIAFAAIAAAVgAgTgGIANAAQAPABAHgHQAGgGABgOQgBgOgGgGQgGgFgMAAIgRAAg");
	this.shape_15.setTransform(-129,78.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1btype, new cjs.Rectangle(-139,0,278,95.4), null);


(lib.HEAD1atype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPAQQgHgGAAgKQAAgJAHgGQAFgGAKAAQAKAAAHAGQAGAGAAAJQAAAKgGAGQgHAGgKAAQgKAAgFgGg");
	this.shape.setTransform(-21.85,54.125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgOBEQgJgJAAgVIAAg7IgPAAIAAgTIAIgBQAHgBAEgEQAFgDABgHIADgUIAaAAIAAAiIAVAAIAAAVIgWAAIAAA7QAAAJADADQAEADAHAAIAFAAIAFgBIAAAWIgKACIgNABIgCAAQgTAAgJgJg");
	this.shape_1.setTransform(-29.075,48.6013);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAHA8IAAgVIAHAAQABAAAAAAQAAAAABAAQAAAAABgBQAAAAABAAQABgBAAgFIAAgtQAAgLgFgFQgEgFgIAAQgJAAgGAIQgFAHAAARIAAAiQAAAFACABQAAAAAAAAQAAABABAAQAAAAABAAQAAAAAAAAIAHAAIAAAVIg/AAIAAgVIAIAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAgFIAAg7IgBgGQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgIAAIAAgVIAXAAIAQgBIANgCIAAAWQAFgLAKgGQAJgFAOAAQASAAAKALQAKALAAAXIAAAuQAAAFABABQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAIAAAVg");
	this.shape_2.setTransform(-40.2,49.975);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeA2QgPgIgIgOQgGgOAAgSQgBgSAIgOQAIgNAOgIQAOgIASAAQAdAAAPARQAOAQAAAeIAAAFIhPAAQABAPAHAIQAHAIAOAAQALAAAIgFQAGgGAEgIIAUALQgEAJgGAIQgIAGgKAEQgMAFgPAAQgUAAgOgIgAAWgKQAAgQgFgHQgFgHgKAAQgJAAgGAHQgFAIgCAPIAqAAIAAAAg");
	this.shape_3.setTransform(-54.1,50.15);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAsA8IAAgVIAGAAQABAAAAAAQABAAAAAAQAAAAABgBQAAAAAAAAQACgBAAgFIAAgrQAAgMgEgFQgEgFgJAAQgJAAgFAHQgEAHAAAPIAAAkQAAAFABABQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIAIAAIAAAVIg+AAIAAgVIAHAAQAAAAABAAQAAAAABAAQAAAAAAgBQABAAAAAAQABgBAAgFIAAgsQAAgLgEgFQgEgFgIAAQgKAAgEAHQgFAHAAAPIAAAkQAAAFACABQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAIAHAAIAAAVIhAAAIAAgVIAIAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAQABgBAAgFIAAg7IgBgGQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgIAAIAAgVIAXAAIARgBIAMgCIAAAWQAFgKAJgGQAJgGAOAAQAOAAAHAGQAJAGADANQAFgMAJgHQAKgGAPAAQATAAAKALQAKALAAAYIAAAtQAAAFABABQABAAAAAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAIAAAVg");
	this.shape_4.setTransform(-71.375,49.975);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgOBEQgJgJAAgVIAAg7IgPAAIAAgTIAIgBQAHgBAEgEQAFgDABgHIADgUIAaAAIAAAiIAVAAIAAAVIgWAAIAAA7QAAAJADADQAEADAHAAIAFAAIAFgBIAAAWIgKACIgNABIgCAAQgTAAgJgJg");
	this.shape_5.setTransform(-86.725,48.6013);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag2A1QgJgJAAgOQAAgPAKgJQALgHARgFQARgFAUgDIAAgGQAAgLgFgEQgFgFgKAAIgHAAIgGABQACACABAEIAAAGQAAAIgFAFQgGAEgJABQgKAAgGgGQgGgEAAgLQABgKAHgIQAHgHANgDQANgDARAAQAcAAANAJQANAKAAAVIAAAzIABAGQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAIAAIAAAUIgrAAIgFgIIgDgLQgDAHgGAFQgGAFgIADQgIADgJAAQgRAAgKgJgAgPAJQgKAFgBAKQABAHADAEQAEADAHAAQALABAGgJQAGgHAAgNIAAgIQgQABgLAGg");
	this.shape_6.setTransform(-97.225,50.15);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgeA2QgPgIgIgOQgGgOgBgSQAAgSAIgOQAIgNAOgIQAOgIARAAQAeAAAPARQAPAQAAAeIAAAFIhQAAQAAAPAIAIQAIAIANAAQAMAAAGgFQAIgGADgIIAVALQgFAJgGAIQgIAGgKAEQgMAFgPAAQgUAAgOgIgAAWgKQAAgQgFgHQgFgHgKAAQgJAAgGAHQgFAIgBAPIApAAIAAAAg");
	this.shape_7.setTransform(-110.55,50.15);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag3A8IAAgVIAIAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAQABgBAAgFIAAg7IgBgGQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAgBAAIgJAAIAAgVIAYAAIARgBIAMgCIAAAaQADgOAIgGQAIgGAMAAQANAAAIAIQAIAJAAAPQAAANgHAHQgHAHgLAAQgIAAgFgEQgFgFAAgHQAAgGADgEQACgEAFgDIgDgBIgEgBQgKAAgFAJQgEAKgBAQIAAAgQAAAFACABQAAAAAAAAQABABAAAAQAAAAAAAAQAAAAABAAIAJAAIAAAVg");
	this.shape_8.setTransform(-122.825,49.975);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgOBEQgJgJAAgVIAAg7IgPAAIAAgTIAIgBQAHgBAEgEQAFgDABgHIADgUIAaAAIAAAiIAVAAIAAAVIgWAAIAAA7QAAAJADADQAEADAHAAIAFAAIAFgBIAAAWIgKACIgNABIgCAAQgTAAgJgJg");
	this.shape_9.setTransform(-133.125,48.6013);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgeA2QgPgIgIgOQgGgOgBgSQAAgSAIgNQAIgPAOgHQAOgIARAAQAeABAPAQQAPARAAAdIAAAFIhQAAQAAAPAIAJQAIAHANABQAMgBAGgFQAIgGADgJIAVANQgFAIgGAIQgIAGgKAFQgMAEgPAAQgUgBgOgHgAAWgKQAAgQgFgHQgFgHgKABQgJgBgGAIQgFAHgBAPIApAAIAAAAg");
	this.shape_10.setTransform(16.8,19.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgdA7IgUgHIAAgeIAbAAIAAASIAIACIALAAQAIAAAFgCQAFgEAAgHQAAgHgHgDQgHgDgLgCQgKgCgJgEQgJgDgGgHQgGgGAAgNQAAgSANgLQAOgLAZAAQAOAAAMADQAMADAHAEIAAAeIgbAAIAAgSIgHgCIgJAAQgIgBgFAEQgFADAAAGQAAAFADADQADACAGABIAMAEQAKABAKAEQAJADAGAHQAGAHAAANQABATgOALQgOAKgaABQgOAAgNgDg");
	this.shape_11.setTransform(4.85,19.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgwAxQgKgKAAgXIAAgvIgBgGIgDgBIgIAAIAAgVIA1AAIAABKQAAALADAFQAFAEAHAAQAJAAAGgHQAFgIAAgPIAAgkIgBgGIgEgBIgKAAIAAgVIA2AAIAABXIABAGQABABAAAAQAAAAABAAQAAABABAAQAAAAABAAIAKAAIAAAVIgZAAIgRABIgMABIAAgUQgFALgKAFQgJAFgNAAQgTAAgKgLg");
	this.shape_12.setTransform(-8,19.875);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgfA2QgOgIgHgOQgIgOABgSQAAgSAHgNQAIgPAOgHQAOgIASAAQAdABAPAQQAOARAAAdIAAAFIhPAAQAAAPAIAJQAHAHAOABQALgBAIgFQAGgGAEgJIAUANQgDAIgIAIQgHAGgLAFQgLAEgPAAQgVgBgOgHgAAWgKQAAgQgFgHQgFgHgKABQgJgBgGAIQgGAHgBAPIAqAAIAAAAg");
	this.shape_13.setTransform(-27.35,19.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgqAtQgRgQAAgdQAAgcARgRQARgQAeAAQAaAAAPALQAOAKAAATQAAAMgHAIQgGAGgMAAQgJAAgGgFQgFgFAAgHQAAgIAEgFQAEgFAIgCQgDgEgFgCQgFgCgIAAQgOAAgHAKQgIAJAAASIAAADQAAAUAHAJQAIAJANAAQALAAAHgFQAHgGAEgKIAVAMQgFAOgNAJQgNAKgXAAQgeAAgRgRg");
	this.shape_14.setTransform(-39.975,19.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAHA8IAAgVIAHAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAABAAQAAgBAAgFIAAgtQAAgLgDgFQgFgFgIAAQgJAAgGAIQgFAHAAARIAAAiQAAAFABABQABAAAAAAQAAABABAAQAAAAABAAQAAAAAAAAIAHAAIAAAVIg/AAIAAgVIAIAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAgFIAAg7IgBgGQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgIAAIAAgVIAXAAIAQgBIANgCIAAAWQAFgLAKgGQAJgFAOAAQATAAAJALQAKALAAAXIAAAuQAAAFABABQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAIAAAVg");
	this.shape_15.setTransform(-53.6,19.525);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag2A1QgJgJAAgNQAAgQAKgJQALgIARgEQARgEAUgDIAAgHQAAgKgFgGQgFgEgKAAIgHAAIgGACQACABABAEIAAAFQAAAJgFAFQgGAFgJAAQgKAAgGgFQgGgGAAgKQABgKAHgIQAHgHANgCQANgEARAAQAcAAANAJQANAJAAAWIAAA0IABAFQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAIAAIAAAVIgrAAIgFgJIgDgKQgDAGgGAFQgGAFgIADQgIADgJAAQgRgBgKgIgAgPAIQgKAGgBAKQABAHADADQAEAFAHAAQALgBAGgHQAGgIAAgNIAAgIQgQACgLAEg");
	this.shape_16.setTransform(-67.675,19.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgOBEQgJgJAAgVIAAg7IgPAAIAAgTIAIgBQAHgBAEgEQAFgDABgHIADgUIAaAAIAAAiIAVAAIAAAVIgWAAIAAA7QAAAJADADQAEADAHAAIAFAAIAFgBIAAAWIgKACIgNABIgCAAQgTAAgJgJg");
	this.shape_17.setTransform(-78.875,18.1513);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgcA7IgVgHIAAgeIAbAAIAAASIAIACIAKAAQAIAAAGgCQAFgEAAgHQAAgHgHgDQgHgDgKgCQgLgCgIgEQgKgDgGgHQgGgGgBgNQABgSAOgLQANgLAYAAQAPAAAMADQAMADAGAEIAAAeIgaAAIAAgSIgHgCIgJAAQgIgBgFAEQgFADAAAGQAAAFADADQADACAGABIAMAEQAKABAJAEQAKADAGAHQAHAHAAANQAAATgPALQgNAKgZABQgPAAgMgDg");
	this.shape_18.setTransform(-88.25,19.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgIBLQgLgIgEgOIgGAaIgcAAIAAgFIAAgNIAAgWIAAhZIgBgGQAAgBAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgJAAIAAgVIAYAAIARgBIAMgCIAABCQAFgMAKgGQAJgGAOAAQAQAAALAIQALAHAGAOQAGANAAASQAAATgGAOQgHAOgLAIQgMAIgQAAQgRgBgKgHgAgKgHQgHAHAAATIAAAEQAAASAHAJQAGAIAKAAQALAAAHgIQAGgJAAgSIAAgEQAAgSgGgIQgHgJgLAAIgBAAQgJAAgGAJg");
	this.shape_19.setTransform(-101.325,17.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgwAxQgKgKAAgXIAAgvIgBgGIgDgBIgIAAIAAgVIA1AAIAABKQAAALADAFQAFAEAIAAQAIAAAGgHQAFgIAAgPIAAgkIgBgGIgEgBIgKAAIAAgVIA2AAIAABXIABAGQABABAAAAQAAAAABAAQAAABABAAQAAAAABAAIAKAAIAAAVIgZAAIgRABIgMABIAAgUQgFALgLAFQgIAFgNAAQgTAAgKgLg");
	this.shape_20.setTransform(-115.8,19.875);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgjBQQgPgEgLgGIAAgnIAgAAIAAAZQAFACAHABIAPABQALAAAGgFQAHgFAAgJQAAgHgEgEQgEgFgIgCIgTgGQgPgDgLgGQgLgFgGgIQgGgKAAgOQAAgZARgOQARgOAfAAQAQAAAOADQANADALAFIAAAnIggAAIAAgYIgKgCIgMAAQgMAAgHAEQgHAFAAAKQAAAHAEADQADAEAIADIATAFQAOADAMAFQALAFAHAJQAIAJAAAQQAAAQgIAMQgHAMgPAGQgOAHgVAAQgSAAgPgDg");
	this.shape_21.setTransform(-129.975,17.575);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1atype, new cjs.Rectangle(-139,0,278,95.4), null);


(lib.CO_v_white = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgyA1QgXgVAAggQAAgeAWgVQAVgWAeAAQAfAAAWAXQAVAVgBAdQAAAfgVAVQgVAVgfABQgdgBgVgUgAgvgvQgTAUAAAbQAAAcATAUQAUATAbAAQAcAAATgTQATgTABgdQAAgbgTgTQgUgUgcAAQgbAAgUATgAASAuQgCgDgCgKIgCgPQgCgIgFgEQgEgCgJAAIgGAAIAAAqIgRAAIAAhcIAfAAQAPAAAFACQAPAFAAARQAAAQgTAGQAGABADAEQADAEABAJQAEAVADAHgAgOgIIAOAAQATAAAAgNQAAgIgHgDQgDgBgMAAIgLAAg");
	this.shape.setTransform(133.8251,86.6356,0.4949,0.4949);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACmLBQgKgEgNACQgPADgIAAQAAgDgKgCIgOgBQgRABgHgCQAAgDgSACQgjgBAAgBIgUgCIgTgBQgLgCgHAAQAAgBgQABQgRABAAgDIgOgEQgJgDAAAHQgDAAgFgDQgEgDgDAAQAAAFgJgBIgNgDQgNgCgLACQgRACgYgKIgJgEQgEgCgEABQgCAAgIgEQgIgFAAgBIgMABIgMABQgIACgFgBQgDAAgDgEQgEgFgDAAIAAAEQgEAAgEgCQgGgDAAgEQgCAGgBAAQAAgDgIgDQgIgCgFAAIgBABQgBAAAAAAQAAgBAAABQgBAAAAAAQAAAAAAAAQgDABgFgEQgEgDgEABQgEABAAgDIgIgGQgHgFAAAEQgCABgMgFQgNgGAAgCIgTgJQgBABAAAAQgBABAAAAQAAABAAAAQAAAAABAAIgEABIAAAAIgEAAIAEAAQABADgQgGQgCgDgFAAQAAgGgDgCIAAAGIgFgDQgGgDAAADIgIgIIgOgCQAAgCgNgGQgNgGAAgCQgKgEgDgKQgBgDgJgBIgOgCQgTgKgBABQgEgCgCABIABgDQgCAAgQgKQgLgIgDgIIgLgDQgCgCgBgDQgBgBgFAAIgDgHIgCgHQgEgBgCACQgCACgCAAQgBgLgTAAQgPAAAAgBIgNgBIgMgBQgSAFgHgCQAAgBgYgBQgaAAgDgBQAAACgJgCIgNgDQgLAFgDgEQgNgEgCABQAAABgGAAIgHgBIgJgCQgDgCgFAAIgOABQAAABgOgEQgGAAgFgHQgCgBgNABIgMAAQgEABgcgDQgcgDAAgBIgJgDQgGgCgDAAIgXgDQgDgEgbgGQgagHAAgBQgCAAgEgCQgDgDgDABQgOACAAgEQgJgEgPAAQAAgFgKgBQgNgBgBgBQgLgFgFgDQgHgGgQgDIgYgEQgDgDgDABIgHACIgGgDIgHgCQAAgEgJgBQgJgBgCgFIAJgCQgBgEgMgEQgMgFAAACIgSgJQgFAAgIgGIgLgHIgMgEIgNgBIAVAVQAAADAHAGQAHAGABAEQADACAGAHQAGAGAEABQAKADAEAHQADAAAHADIAKAFIAHAEQAHAEAAACQAFAAAHADQAGADAEAAIAEACQABAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAFABAGAGQACAFAWAEQAVAEAAADIAYAKQADAAAGADQAFAEAEAAQACgBATAGIATAFQADAAAIAEQAGAEAEgBQAEgBAJAEQAKAEADAAQAAgBARAEIAVAFQAEAAAJACIANAEQAAABAOACIAQABQAAAFBNAGQADADAjADQAiAEAAABQBPAIAAgBQADgBAkAEQAiAEAAgBQAIgBAAABQgGAAgMAGQgOAGgFABIgMgCQgLgCAAADIgGABQgDABgDgBQAAAGgUABQgTABAAgDQgQACAAgCIgGACQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgLgBQgDgBgDgGQgDAAgCADQgBABgGAAIgNgBQgXgCgDgCIgFgFIgJABIgMgEQgKgDAAADQgGAAgKgCQgCgGgEABIgJAFQgFADgFgCQAAgCgLgCQgKgCgEABQAAACgWgEIgbgFQAAgCgOgBQgPgBgBgEQgHAAgLgDQgMgDgGgBQgCgCgNgBQgNgBAAgCQgGAAgJgCIgOgEIgNgEQgNgEAAgBIgNgCQgKgCAAgBQgFAAgGgCIgLgFIgDgBIgCgBQgLAAAQALQACACAGACQAGACADADIAKADQAAABAFABIAHABQAAACASADQAAADAaAEQAZAFABAHIgKACQAAgDgXgDQgZgDgCgDIgagHQgVgHAAgDIgZgIQgUgIAAgBQgIgCgKgEQgNgGgFgGIgIgFQgJgEAAABQgCAAgHgFQgIgFAAgCQgKAAgPgHQgRgJgCgJQgPgKgGAAIgIgIQgFgFgDgCIgGgIIgJgFQgGgCAAgDQgGgEgHgIQgHgJgDgGQgDgBgEgHQgFgHAAgCQgDAAgDgJQgDgKgEAAQAAgEgDgGQgEgFAAgFQgBAAgFgTIgGgYIgHgkQgHgjAFAAIgFgVQgBAAgBgLIgBgNQgDAAAAgNQgBgOgCAAIgJhUIAAggQAAgcACAAIgCgjQgBggAEAAIgCgxQgCgsAFgDQAAgEAKgaQALgZgBgEQAIAAAHgOQAHgPAGgCQACgBADgFQACgGADgCQAAgFAGgGQAHgGAHgBIgDgEQAAAAAAgBQAAAAAAgBQAAAAABgBQABAAABAAIAEgCQAAAAAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAHgHIAKgHIAFAAIAEgCQALgIgHAAQgCgGAFgEQAFgFAFAAIAIgDIAIgCQAKgFAKgJIAQgRQAGgGADgBIAFgDIACgEQACAAAOgLQAAgCANgFQANgGAAgEQAEAAAJgGQAJgHABgDIAOgJQAHgEAIAAQAAgBAGgDIAFgCIAJABQAGACABgDIAXgEQAOgEAAgJQADgBACgEIADgEQABgCAEgDQAEgCABgDIgBAAQAAgFAHACIAJACIARgCIAIgFIAKgEIAJgFQAHgEACAAIAEgCQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBQAFAAAFgCQAHgCAAgDQgHAAAHgHQAHgGAEgBIANgHQAFAAAGgDQAAgDAHgCQAGgCAAgEQAGAAAAADQADAAAEgCIAHgCIAKACQAGABACgDIAOgGQAJgGAEAAQAAgBALgEQAKgDAEAAQAAgCAHAAQAHAAAAgBQAJAAACgCQACgBAAgHIAFgDIAEgEIAJACIgBAFIAEgCIADgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAfAAAHgDQAEgBAGACIAKACQALgGgFAAQgCgJASgGQATgGAAAFQAMgIAZAAQACgDAJAAQAJABACgEIAXgEQAUgEAAgBIABABIAVgFQAWgFADAAQAVAAAAgEIAIgCQAHgBAAgBIAggHIAvgHQAOAAAggFQAggGAQAAQAAgFBQAAQAAABAGACQAHACAAACQgIAFgXgCIgQABIgRABQgJAAgRADQgSADgJAAQAAgChXATQAAAFArgFIAxgGIAugGIAbgDQARgCAJACQAUgDABAKQASAAAAABIAHABQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAABIgIAAQAAADg1ACQAAABgRADIgUACIgTAAQgSAAAAADIgwAHIgSACIgUACQAAADgMACIgQACQgIgBgPAEQgQAFgHAAIgMACQgMACAAACQgEAAgGAEQgHAEgDAAIgJAAIgJgBQAAADgQACQgPADgBADQgCAKgMADQgOABgIACQAAADgTAHQgHAKgHAEQACAIAiABQAfABAHgEQADgCAagEQAXgDAAgCIAMgCIAMgDQAAgBAGABIAHABQARgEAJAAQAAgBAcgDIAcgFQAfgDAAgBIAVgCIAWgCQAAgCAmgCQAngDAFABIApgDQAkgDAAACQAMgCAYACIAcgBQASgBALACQAAADAJACQAJACAAgCIAQABQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQADgBAKACQALADAAACQgEACgWABIgVAAIgmABQgCADgWAFQgVAFAAACIgQgBQgPgBAAACIgWAAQAAAFgZABIgegBQAAADglABQglACgBAIQARADAXgDIAngGQAAACAkgCQAjgBAAABQAFAAALgDQAEAAAEACQAFADAEAAIAQgBQAJABgEAGQgFAIghACIghACQhWAFAAADIgTACQgTACAAgCQgGgBgJADQgLADgDAAIgRACQgCACgGAAIgKgBQgGABgJAGQgIAGgGABQAAAFgdAEQAAABgHACQgIADAAABIgTADIgKACQgLACgBACQgRAAgMAMQgGABgKAFQgKAGgGABQAAgBgNAFIgPAFQAAgCgFABQgEAAgCACIAEABQgBADgMACIAAgEIgOAFQAKAIgUAEQgWAEAAACIgTAGQgNAFgGABQAAgCgvAQIgRAGQgRAGgCADQgTAAgDAEQgFAAgHAFQgGAEgFgBQgGAAgFAFQgGAGgFAAQgCgDgFACIgIAEIgKAFQgFACgFABQgBABgLADIgNACQAAAFgJACIgOADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABgBAAQgCADgEAAQgEAAgCADQgDAEgDACIgDADQgBABgEAAQgBgCgGgBQgFgCAAAEQgFAAgBAFQgDAHgCABQAAADgJAAQgOAJgCAAQAAACgMACQgLADAAAEIgMAGQgIAFAAADQgFABgFAEQgGAEgEABIgGADQgEACgCAAQgRAJgCAAQgEAEgFAAIgQAMQAAADgIAFQgIAEAAADQgGAEgOACQgBAEgEACQgFACgBABQgFAAgEAIQgEAHgDABQgEABgIAHQgIAFgDAAQAAAFgHAEQgIADgBAFQgSALgLANQgEAAgGAGIgIAKQgGAIgFADQgBADgFACQgFACAAAEQgCAAgHAJQgGAIgDAAIABADQgFAAgFAHIgHAKIgIAIIgHAJQgDAHgLANQgJALgBAJQADAAAGgHQAIgJACgBQAGgKAEAAQAAgDAHgFQAGgFABgCQgCAAAKgJIALgJQAGAAAEgJQAEgJADAAIAGgGQAGgFACAAQACgEAHgEIALgHQAAgCAEgFIAHgFIAVgPQADgHAUgGQABgDAJgEQAIgEAAgCQgBgEAGgCIAIgDIAWgOQAEAAAFgFQAGgEADAAIAhgUQAGgCARgIQATgJAAgDQAHgBACgDQAEAAABgDQACgDACAAQAHgCABgCIAIgEQAFgDAAgBIAGgDIAFgDQAAADAMgFQALgFACgDIAHgCQAFgCAAgBQAHgBAOgJQANgIAIAAQADgEAJgCQAIgCADgDQAEAAAGgEQAFgEAEAAQAFgFAIAAIAIgIIAHAAIAGgBIASgHQAAgBAGgCIAHgBQADgEAKgBIALgCQABgCAHgDQAIgEAAgCIAQgDQAAgCALgDQAJgCAEAAQAAgGANgBQANgBACgCIApgMQAhgJAAgFQAEAAASgFQARgGAAgBQAFAAAJgCQAKgCAAgEQAygGAAgEQALAAAQgFQATgHAHgBQAAgBAYgFIAbgFQAAgBAdgGIAhgHQAIgCANgBQAAgBAFgBIAHgBIATgEQAMgDAHABQAAAIgWAFIgeAFQgQAEAAACQgDAAgHAFQgHAFgFgBQAAAAgBgBQAAAAAAAAQAAAAgBAAQgBAAAAAAQAAACgZAIIgHAFQgEADgEAAQgDAEgGABIgMABIgbAJQgQAFgMACIgEADQgEADAAACQgEAAAFAEQAFADAAgEIAMgBQAKgBAAgCQAfAAgQAFIgHAEIgGAGQgCABgHgCQgEgBgCAGQgJgBgIAEQgKAEgIAAQgFAAgHAEQgGAEgEAAQAAAEAGAAIAGgCIAHgCQAAANgmACQgBADgGABQgDACgEgBQgEAAgDABQgBACgPAFQgFAGgSAAQgLABgBAGQgEgBgFACQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgEgCgBABQAAABgFAEIgIAEQgOAFAAACQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIABACIgGACQgEACgCgBQgBAGgKABIgOgBQAHAFgHADQgFACgGAAQAAgBgIAEIgIAEQgDAGgPAAQAAgDgGACIgEADQgBgDgEAFIgEAIIgGgCQgBAAgBAAQgBAAgBAAQAAAAgBABQAAAAAAABQgFACgIAAQgEAAgMACQgNADAAADQgDAAgEAEQgFAEgDAAIgbAKQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgDADQgEAAgDACQgDACgCAAQAAADgEABQgEACgDAAQgFgBgDAEQgEAFgDAAIgHAEIgFADQAAAGgKACIgOABQAAABgFADIgHADQgDABgHAIQgFAHgGgBQgHgCgJAJQgRAEgBADIgFACQgCABAAAEIgJgBQABABAAAAQABAAgBABQAAAAAAAAQgBABgBAAIgEAAQgBAAgBAAQAAAAAAABQgBAAAAABQAAABABABQAAAGgKAAQgCgCgGADIgJAEQgRAHgIAKQgJABgIAEIgPAJQAAAEgMAGQgMAHgCAFIgJAEQgGACAAAEIgMAFIgGACQgDABgCADIgCADIgEACQgJAHAAACQgDAAgCADQgDAEgCAAQgHABgFAEIgNAPQgHAIgJADQAAAGgOAJQgOAKAAAHQgEACAOALQAPANgBADQgFAAgGAKQgFAKgBAGQgDAAAPANQAPAMAAgEQAGAAAIAHQAIAHABAGQAAAEAKACQAKACACACIAMAJQAGAAALAGQALAFAGAAQAAAHArAAQAMAMAIAAQAAABAIAAQAJABABABIALAAQAGABAFADIAOAJQANAGAFgCIAKgCIALgCQAEADACAAQgCAEADACQACABANgBQAMAAACAEIATABIAIABIAJABQAAgCAPADIASADQADgEAGAAIALAAQABACAHAAQAHAAADADIAEAKQAEAIADgBIACAAIABgCIABgNQABgFAFAAIAKAAIAPACIARAAQAAgCAKADIAMAEQAAgFAKgCQAKgBAAAGIAugFIgBgCQADgCgDgPQgEgPABAAIgEgNQgFgMABAAQABgCgBgFQgBgFgCAAIgBgUQgBgFACgMQABgOACAAIAAgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBABAAQAFAAAAgZQACAAACgIIADgJQAAgFADgGQADgHABgFIAIgfIAIgQQAFgKAAgGQAEgCACgGQADgIADgCQAHgGgBgHQAMgMgBAAIAEgGQADgCACgEQgCgFAEgBQAAgCAFgGQAGgFAAgDQACgBAFgGQAFgHACAAQAAgDAFgDIAIgGQACAAAEgEQADgEAAgCQANgGAPgPIAFgCQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIgRANQgFACgFAIQgFAHgBAFQAGgBADgDIAGgIQAPgGAAgBQAIgCANgKQALgJAKAAIAIgBQADAAADgDQABgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQAAgDAEgBQAAgDAJgHQAIgHAFgCQADgBAFgEIAIABQACgCAFAAQABAAABAAQABgBAAAAQABAAAAgBQAAAAAAgBIAIgGQAHgGAAADQAGACAAgLQAGgBAFgEQACgCAJgCQAAgDACgDQADgDACAAQAAgCAMgGIANgHIACgFQABgCAEgBIAGgCIAGgFIAFgBIAFgCQAEgEAHgDQAIgDADgDQAFgEADACIAEADQADAHgOAHIgSAIQAAACgSAJIgMAJQgIAFgCAFQgEABgIAGQgIAGgGABQAAAIgLACIgMAJQgGAFgCAFQgIACgHAIQgCAAgDADQgDACgEAAQgGABgCAHQgIAEgCAJQgEACgEAFIgIAIIgPAMQgKAHAAAHQgNAGACANIgDAEIgCAGQgFACgBAJQgCAAgEAFIgFAFQgJAKAAgEQgDABgBAHQAAAGgIAAQAAABgEAEIgFAEIgBALIgGAJQgEAGgBAEIgMAKIgEAMIgGAEQgBACABAFQgBAAgEAHIgDAJQgDABgFAIIgHAHQAAATgIADQgGACABAJIAAANQgEAAgBAZQgBAZABAAQABgJAIgNQAKgOABgHQADAAAFgIQAEgGAAgDIALgUQACgBAFgIQAEgHAEAAQAEgPALgCQgCgKAMgGIANgPQABgEAJgIQAIgHAAgFQAFgCAGgIQAFgJAFgCQAAgDALgJQAJgIAFgDQAAgDALgHQAKgGAAgCQAGgEANgNIAPgNQAEAAADgFQADgFAEAAQACgEAHgGQAHgFAEgBQABgDAFgEQAHgEABgCQAIAAALgMQAMgMAGAAIAKgHQAIgFAAgCQADgBABgDQAAAAAAgBQABAAAAAAQABgBABAAQAAAAABAAQAIAAgCgGIAGAAQAAgCARgIQAQgJAEgBQAAgEATgKQARgJAGAAQADgGAJgFQAIgEAHgCQAAgBAJgEQAJgEACAAQACgCAUgJQATgIAAgBIAEgEQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAQABAAABAAIAGgBQAAgCAIgDIAIgCQADgDAIAEQACgJAFAAQAGgGAIAAQAAgCAHgCIAKgDQAFgHAZgGQABgCAGgBQAFgCACgCIAGgCIAHgCQAAgCAGgBQAGgBAAgBIAEADIAdgQQAAgBAMgDQALgCAAgCQAXgGAAgCIAJAAQAHAAADgEQADAAAPgJQABAAABAGQAAgIAVgEIAMgEQAJgDABAAQAQAKgEgHIgCgDQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAugJQACgEAXgEQAWgEAAgBIAIgDQAEgCADAAQAAgDARgBQATgCABgCQADAAADgDQADgDADAAQAAgCALAAQAngIADABQAAgCAvgIQAHABANgDIAVgGQAYgFAGAAQA9gJAGAAQAJgBAVgEQATgEAMAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAKAFQAIADAAgGIAUgCQA+gHAAACQADABAZgFIAigBQAfAAAAgCIBjgBQAAgCAoADQAsAEAEAAIAKAAQADAEAEgCIAIgCQACAHgDgBQgBAAgBAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgFAEgNAAQAAAAAAgBQAAAAgBAAQgBAAAAAAQgBAAgBAAIgFACQgEAAgDgCQgDgCgCAAQgNAHAAgEQgQACgIgCQAAgCgMABQgMACAAABQgLAAgKABQgCAFgGgCIgKgDQAAADgLAAQgKgHgCACIgDADIgFABQgDADgGABQgDAAAAAHQgMAAgCAIQgCAIAMAAQACADAKABQAKABADACQAAgFAHADIAKADQAAgEANACQAIABgDACIgFADQgCACgJAAQgIAAgEgCQAAABgHABQgGABgBAFQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgCADQgKAAgIACQgKADgHAAIgqADQgCAEgLAAIgRAAIgtACQAAABgfAEQggADgFgBQAAAGgzgBQAAABgIADIgJACQgYAAAAADQgFgBgOADIgiACQAAABgVAEIgYADQAAgDgKAHQgLAGAAACIAhAAIAbgEIATACQADAAAFgCQAEgCAFAAIAOgDQANgCAAACQAFABAHgFIAOABQAAAFALgHQAKgBARgDQAAgCAJAAQAGgBAFABQAGACAGgBQAGgCAFACQAAgDARgDQARgEAAAFQArAFAAgDIAJABQAGABAAADQgNAHgDgBQgFgBgKABQgLABAAADQAkgDBBACQANAAAaAEQAYADANAAQAlAAA5AKQArAFAAAFQAFAAAXAFQAZAFAAADIAIAAQAEAAABgEQAJgDAFAAQAFAAAFACQAAABAIACQAIACAAACQATAAAZAOQAPASgBAAQAAAGASAAIgLgKQgIgHAJAAQAGAAAJAFQAJAFAFAAQAqAWAEAAQAAABAPAEQAOADAAADQADAAAHAEQAIADADAAQAAABAoAOIAZAOQASALAAAHQAEAEAFACQAAACAJAIQAKAIAAADQAHAMACAAQAAADAEAGQAEAGAAAEQABAAACAHIACAJQAEAAAFATQAFATADAAIAJAUQAFAMAAAKQACAAAFAbQACAAAGAXIANAyIAHAaQAHAXgDAAQACAGADApQABADgCAFIgCAIQgCAAAAAGIAAAJQgCAAgDAIIgDAJQgDABgFAPIgFAPQgBADgDAAIgDAAIgBAGQgBAAAAAAQgBABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgIAAIAAAEQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgEACgBAGQgCAAgDAGQgDADgCgFQgHABgFAFQgEAAgCAIQgCAIgCABQAAAHgGADQgGADgGgCQABANgJgDQgMgEgCAEIAAAMQgCABgDADIgCADIgEACQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAGQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQgJgCAAABIgKAEQgEAAgCADQgCAAAAAFQgBAFACAAQgBAKgNABQAAgDgIgBIgLgCIgGADQgGACAAADQAAADgMACQgEABgKAFQgKAFAAADQgCAAgNAHQgNAHAAACQgFACgDAHQgCAFgHgCQAAACgDAEQABAAACAEQACADAAACQgGACgLgDQgLgDgFABIABAKQAAAGgFAAQgCgDgEACQgBABAAAAQAAABAAABQgBAAABABQAAAAABAAQADACABADQgEACgFAAIgJAAQgCAAgHgFQgHgEgFAFIgDAGQgBACgEABIgHAEIgFADQgBAFgJAAIgPgBQAAAHgJADQgLADgCADIgDADQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAgBgBQgCgDgDAAQgEgBAAAEQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAIAAAGIgMABQgDAAgGAFQgEADgDgHQgDgBgDAFQgDAEAAAEQgFAAgFADQgFADAAAEIgGgBIgHABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAADQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgEAAIgPADQgFAGgHACIgPACQAAAAgBAAQAAABAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAADABAGQAAAEgNgEIgHAFQgHAEAAADIgJgBQgEABgCAGIgJADQgHABgCgEQgGADgHAFIgMAIQAAAGgRgDQgSgDAAAIIgFgCQgBgBgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBAAgDAFQgDAEgCgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgGAHQgDAFgFgBIgEAAIgFACQAAAAgBABQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgFAFIgJAEQgHADABABIAYAAQAOgBAIgDQADgBAcgFQAYgFAAgDQADgBAFAGQAEAGAEgCIARgFQACgFAZgDQAAgBALgDIALgEIALgCQAJgBgBgDQARgHABAHIAPgGQAKgDAHABQgSALgFABIgpAUQABgGgKACQgIABgEAEIAEADQgEAAgUAIQgUAIAAACIgJABQgIACAAADQgFABgFgBIgJgDQgBAKgHgBQgMgBgCABQAAABgIABQgJAAABAEQgRAJgKABQgWADAAACIgIABQgGgBAAgBQgDgBgEABIgHACQgWAMAAgIQgDAAgEACQgFABgBADQgDgBgIADIgGADQAAABgVAEQgGAAgFAEQgGAEAKABQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIADABQAAgDARAAQAQgBAAgCQAIAAAWgHIAdgEIAkgGIAVgEQATgEAAABQAIAAAMgEIASgHQgBgBAOgFIAQgEIAVgIQAPgHAEAFIgUAKIgRAHQgGABgLAGQgMAFgEABQABADgKACIgNACQgKAGgLACQAAgCgMAIQgCAFgDgFIgDgDQgEABgFADQgFAEgDAAIgKADQgJABAAADQgFAAgGACQgGACgGAAQAAAJgLgMQgCAGgBAAQgDgFgJACIgLADQgFAGgBADQgFAAgEgDQgFgDgEgBQAAAFgGAEIgLAEQgXALgNgLQgMAEgDAAQAAAHgPAAQAAACgMADQgLADgEgBQAAgEgIAAIgMAAQgCAHgBAAIgHgBQAAACgVgBQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAADgJAAQAAgGgEAIIgDAEIgIAEQAAgEgHABIgIACQgCABgQAAQgOAAgBADIgYAAQgFAAgHgDIgMgDQgHAHgIAAIgRgDQAAABgKADQgKACAAABIgPACQgMACgEgEQAAgBgNAAIgRgBQAAAFgHgBIgKgCQAAADgPABIgFAAQgKAAAAgDgACUKCQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAdgDQAZgCABAEQABAAAAAAQABAAAAgBQAAAAABgBQAAAAABgBQACgDADAAIAEAAIADgBQAEgBAGABQAHAAADgBIAOgFQAJgCAHAEQABgGAEADIAFAFQADAAAFgFQADgGAEABIAHACQADAAAFgDQACgBAFAAIAHgCQAFgBABABIABAFQAEAAAEgGIAJgDIASgFIALgBQAHgBAEgDQALgFADAAQgFgBgPAEIgTAGIgfADQgPACgVgBIgWAEQgSACgBgEQgNACgBABQgKADgJgCQgKgDgNACIg1ADQgFABgCgFIgKADQgBgDgFgBQgIgBgCgCQgLAEgEgBQgMgDgagBIgagBQgFAAgJgCIgOgBIgMAAIgKgCIgBACQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgDgCgCABQgBgDgFgBIgHAAQgKgDgYgBIgOgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABIgDABQgLABgIgDIgFgDQgCgCgDABIgNAAQAAgCgFAAIgHAAQgDgBgEAAIgIAAQgEAAgDgCIgGgEIgPgDQgJgBgEgEQgFgEgBAAQgCACgEAAIgKgCQgGgBgEABQgBgEgMgDQgIgCgGAAQgDABgDgDQgCgCgDABQgDAAgGgBIgKgEQACABgSgIQgQgHAEgBQgCgBgHAAQgGABgDgCQgIgEADgCIgQgFQgDgBgPADQgRADgOgBIApAdQARgBALAEIANAFQAIgBAMAGIAMAFQAKAEAAACIAHgCQADgBACADIAGAHQACgBAIgBQAJgBABADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIASAGQADACAFAAIAIABIASAFQAEACAFABIAJABQAQAEAjAEQA8ALA6AFIAbACQARABALACIAhABQADgBALACIAQABIAMgBQAIgBAEACQABAAAAAAQAAAAABAAQAAAAABgBQABAAAAAAIABgBQABAAAAAAQAAABABAAQAAAAAAAAQAAABABAAgAGCH/IgCgHQAAgDAHAAQABABAHgBQAHgBABgCIAPADQALACAAgEQAGgHAHAFIAMAHQAGAAAAgDQgBgEADgCIAHgCQACAAACAEQAIgIAQgBQAJAAAQABQAAgBAFgCIAGgDIARAAQAAgCAPAAQACAGAEAAQAAgGAIgBQAHgCAAACIAJgCIAJgCQAAAAABgBQAAAAABAAQAAgBABAAQABAAABAAQADAAACgDQALgFAIADQACAAATgEIAGACQAAAAABAAQAAgBABAAQAAAAAAgBQABgBAAgBQAAgBAAgBQABgBAAAAQAAAAABAAQABgBAAABQAFACABgBQAAgCAPgDIARgDQABgCAOgFQANgFAEAAQADABAEgEQAEgDADAAQAAgDAQAAQAGABALgHQAGAAALgFQALgGAGAAQACgDANgEQANgFAFAAQABgCAMgEQALgDAAgBIAVgIQADAAAEgCQAEgDAEAAIAKgEIAHgDQAEgCAEgBQABgDAGgBQAGgCACgCQAEAAAIgDQAJgEACgCQAEAAAHgEQAHgEADgEQAFAAAJgFQAIgFAGAAIAYgMQAAgBAVgIQAWgJACgDQAFAAAJgFQAIgGAGAAQAFAAAGgGQAHgHADAAQAEAAAGgGQAHgGADAAQAHAAAKgIQAEgCAHgHQAAgBAGgCQAGgCAAgCQgHAAAGgCQAFgCADAAQAAgEAJgBQAHgBADABQAAgDADgEQADgFAAgFIAQAAQAAgEAEgCIAIgFIANgIQAAgFAMgGQALgGAAgCQAMgCADgDQAGgEADgJQAFgBAQgbQAMgGAGgKIACgEQABgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAQADAAAFgJQAFgKAFAAQADgFAAgJQAFgDgBgEQABAAACgMQACgNACAAQAAgBgCgFIgEgGQAAAHgLAAIgFAGQgEAGACAAQAAADgHAGQgIAFAAACIgFAGIgGAIQgDAAgFAFIgIAFIgFADQgFADABAEIgJADIgHADIADAAIgBAEQADAAgMAKQgDADgIAAQgHABgCACQAFAAgFAHQgFAGgEAAQgJAMgOADQgEAIgOAFIgCACQgBAAgBAAQAAABgBAAQAAABAAAAQAAABAAAAIgKABQgCABAAAHQgbAFAAAGQgPALAAABIgJADQgGACgEAAQAAADgFACQgEACgEAAQgEgGgEAHQgEAHgCABQAAACgKAGIgMAGQgEABgIAGQgJAGAAAEQAAACgMAEIgQACQAAAEgJACQgJABABAEQAAABgaAFQAAAHgOAGQgLAFgKABQAAgFgOAHIgOAGQgDAAgJAEQgIAEAAABQgEAAgHADQgHADgEAAQAAACgJAEQgIADgCgBIgBADIgBADQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgDABgCgCQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAFIgDAAIgCgBQAAADgFABQgGABAAABQgEACgCgBQgDAAgDACQgDADgMAAIgIAGQAAABgKADIgNADQgNAGgDAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAAAABIgYAKQgYAGgGAEQAAADgXAAIgHAEQgEABgBAFQgFACgEgBIAAAFIgPAAQAAAGgGABQgHACAAgCQgDAAgLAFQgJAEgFgBQAAgBgGACIgHACQgDADgIAAIgMgBQgCAEgLAAIgbAJQAAABgFACIgJADQgFADgKAAQgDgDgDACIgFAEIgKgDQAAAHgNABIgTABIgIABQgFACgBADIgMgBQgcALgDgBIgUACQgSADAAACIgPADIgOACIgHACQgFACAAABQgIAAgQACQgVAEgDAEQACgCATAAQAAAEAZAAQADgEALABIAQACQAAgEANACIAOABQACAAADADQADACADAAIAAAAgAn2HeQgCAEgDAAIANAKQAJAGAEAAIADgDQABAAAAgBQAAgBAAAAQgBgBAAAAQgBgBgBAAQgBgDgGgFIgKgFIgDgCIgCACgAAUGwQACAEACAAIAIACQAFABACgEIADgBQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAgBAHgBQAHgCAAgBQAigBAAgFIAGABQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAFgBANADIAJgDQAGgDADAEQACADAFgBQAFAAACgDQACgCAFACIAIACIgEgEIADgGIAKgCQAGAHAAgFIASABQAFgCAHgHQACgBAKABQAJABADgDQAEgEAHAAIALABQACgFALABIAOABQAAgDAHABIAJADQAAABAKgHQAKgBAOACQAAgIAPgBQAAgBAVgEQAVgFADABQABADAMAAQAMAAACgEIACgFQAEgEADAFQACABAEAAIAGAAQAAgIABgCQACgBAIABQABAEAHgDIALgDQAEgBAKAEIAIgEQAAgFANgDIARgCQAHgDAEgGQADgCAHABIALABIgBgFQAEAAABgCQACgDADgBQADgBADABIAHACQAAgCAPgCIASgBIgCgEIADgBQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAJgBAHgEQAJgHAFgCQAXAAADgFQANAAABgCQAGAAgDgGIAKgBIAEgGQABgBAAgBQABgBAAAAQABAAAAAAQAAAAAAAAQADABADgCQADgCADABQAAACAHAAQAHAAAAgCQAHAAAEgDIAJgIQAHgBAEAAQACgEAEABQAGACACAAQAAgBASgGIAUgIQgDgDABgCQACgCAFAAQADADAFgCIAIgDQAAgBAHgBQAHgBAAgDIAGACQAIgFgEAAQgBgDAPgEQAQgEAAgCQAHAAAHgDIAOgIQABgCAIABQAHABAAgEIADgDQABgCAFAAQAEAAAHgDQAAgBAKgDQAKgCADABQgBgFAFgDQAGgEACgDQAPABAAgDIAHABQAEAAABgEIAKgIQAAgDAIgEQAHgFAEAAIALAAQAAABATgLQAAgDAHgFIAIgFQAGAAAIgHQAIgIAFAAQAAADASgNQAIgGAKAAQAUgNAAgCIAWgPQALAAAMgIQADgHAEAAQADgDAJgDQAJgEACgDQAFAAADgGQADgHADAAIAKgHQABgDAEgEIAHgGIAGgCQAFgBABgCQAAgFANgGQAMgHgBgDQAVgZADgBIAHgPQAFgKgHgDQAAgCgHgEQgIgDgBgDQAAgDgEgCIgHgFQgMgLgGgDIgQgHQgNgHAAgDQgGAAgJgFQgKgGgEgBQAAgBgJgFIgKgHQgEgBgIgFQgHgFgEAAQAAgBgSgEQgUgHgDgDIgQgIIgKABQgHABgEgBIgFgCIgHgBQgRgLgDAAQAAABgSgHIgJgDQgDgEgGgCIgKgBQgtgKgGgBQgGgHgWADQgSACgDgEQgDgEgHAAQAAgBgOACQgPACAAgDIgTgBQAAgEgGgBQgHgHgIAEIgNAFQgHAAgKgEIgRgGQAAAFgXgBQgWgBAAgJQABgEgFgBQgEgBgFABQgCADgIgCQgBgBgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAADgJgBQADAHAAAEQAHAAACAeQACAcgCAIQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABABQAAAAAAAAQgBABAAAAIgBAUQgBATgEAAQgBADADADIgIAQIgGANQgFAIAAAGIgGAPQgFAOgHAAIABAFQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIAAAEQgCAAgCAGQgBAGgDAAIAAAEQAAABgBAAQAAAAAAABQAAAAgBABQgBAAAAABIgFAEIgBAHQgDAAgBAFQgBAAgGAIQgHAJgFABQgBADgIADQgIACABAFIgCAFIgCADQAAACgEAEIgGAFQAEAKgSACQgBAGgHAEQgIAGgCADQgFAIgTAJQgCABgDAEIgFAFQgJAAgRAOQgUARgFACIgNAFQgJAEAAAEIgLAHQgGAFgGABQAAgBgFAFQgFAEABAAIgKAFIgKAGQAAABgLADQgMADAAAEQgJAAgRANQgSAMgMAAIgKADQgIAEgBABIgJAHQgFAFgFAAQgeAKgEAAQAAACgJAGQgJAFAAgEQgEAAgHADQgHAEgDADIgLACQgFABgEAFQgFAAgKAGQgJAGgEAAQgDAFgVAAQgCADgDACQgEABgBACIgGABQgEABgCgCIgGgDQgHgBgGADIgKAIQgBAFgNAEQgDAAgIAFQgHAEgEAAQgsANgHAAQAAADgZAHQgaAIgDADQgTACghANQgHADgOAAQAAAGgPAAQAAACgVAGQABgGgiAKQgEAAgGACIgKAEQAAgBgMAEIgPAFQgIAGgMACIgWAFIAFAAIABABIARACQAOACABgDQAcAAASAEQAsgBAAAFQAFABAvgHQAHgDAHAEIANAHQAAgCAQgCIAUgCIAQgBQAEABACADgAqtGZQgHgMAAgBIAHAFIAGAEQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIADgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgGAAIgCgBIgBAAIAAgBQgDgDgDgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgDgBQgjAFAAgEIgJgBIgIgCQAAgEgOACIgQADQgGAJATADQAWADAAABIAVABQARAAAAACIASAAIAAAAgAopGGQgDABAAAFIADAEIAEAFIAHgBQALAAgJgLQgFgEgEAAgAmTFsIAIAOIAFAFIAOACQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAIAOgCQAJgCAEABIBCgLQAAgCAVgDIAYgEQBOgSAHAAQAAgBAXgGQAXgFAEAAQAAgDAWgEQAWgDACgEQAHAAAKgEQALgDAGgBQAGAAALgEIAQgFQACgDAdgHQAagGgBgHQAYgBAAgDQAJgBARgHQAAgBAJgCQAJgCAAgBQADAAADgCQABgBAAAAQABgBAAAAQABAAAAgBQAAAAAAgBIAGgBIAFABQAAgDAQgFQAOgEAFAAQACgDAJgDQAKgCAAgDQAEAAAIgDQAJgDACgDQAGAAALgEQAJgEAFgEQAGgFAPgDQABgCANgEQANgEAAgCIANgGIAOgHIAPgFQAKgEADgEQACAAAJgFQAIgEAAgBQAEAAAIgEQAIgFADgDQAKAAAOgKQAOgKAIgBQACgEAUgJQATgKgBgCQAAgBANgHQAOgHAAgBIAHgGQADgDAFgBQAKACAEgGIAEgIQAEgIAFAAQAAgBAFgEQAGgDAAgCQAFgBAIgHQAIgHAFgBQADAAACgFQACgFADgBIAIgFIALgKQAEgCAFgHQAFgHAEgCQAAgFAOgMIAOgRQACgEAFgIQAGgIACAAQABgGAFgHIAGgMQACAAACgFIACgGIACgHQACgGgBgDQgFAAgJAOQgKAQgEACQAAAGgMAJIgLAKQgGAHgEACQAAAFgHAFIgKAKQgBACgIAFQgHAEAAAEQgDABgDAEQgDAEgFABIgEAFQgEADgCAAIgHADIgIADQAAACgEADQgFAEgBADIgKAGQgHAGgBACQgDAAgJAGQgJAGgCADQgKADgQANQgPAMgMACQgFAGgMAEQgLAEgIAAIgOAOQgFAAgHAGQgHAFgDAAQgCAEgIABQgHABgDADIgHADIgGADQgCAAgEAEIgFADQgCAEgJAAQgJABgDAEQgEACgDAAQgCAEgIABIgNABIgJABQgGAAgDABQgDABgDAHQgDAGgEABQgEAEgFgCQgHgCgDABQAAAEgFACQAAAEgVAJIgbALQgDAAgFADQgFADgDAAQAAACgNACQgEAEgIADQgHACgGAAQAAACgNADQgNADAAADIgNACQgKACgCADQgGAAgCABQgDABgFAFQgHAAgGACIgNADIgWAHQgBACgKACQgKACAAACIgbAHQgFAAgIADQgIADgFAAQgCACgOAEQgNADAAABQgDAAgFADQgFADgDAAQgBACgGABQgFABgCgCQgRAHgCAAQgDADgNADIgMACQgEABgKAEQgIADgEAAQAAACgOAAIgQgCQAAABgJADIgMACQgPAAgMAFQAAAFgLACQgMABAAABIgXAAQgQAAgFAFIgDACIgDADIgJADIgHACQgCADgcAEQgcAFAAACIgFAAIgFAAgAxuEwQAAgCgHgCQgFgCgEAAQAAAGAQAAgAzoD+IgCADIAOALIAKACIALACQAEAHAcAKQAbAKAAgGQgOAAAAgHQgQgCAAgCIgUgKQgCAAgEgIQgEgHgGAAQAAgDgKgBIgKgBIAAAAIgGACgAmhD9QgJAEgBADQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAIADAAQAAACAsgFIA0gGQAAgDAWgEIAcgFQABgDANAAIARAAQAFAAARgGQANgEAIACQAAgCATgDIAWgEQAAgFALACQAMACAAgEIAKAAQAGAAADgEIAJgDQAFgGAQACQAQABACgFQgIAAAHgEQAGgEAEAAIANgBIAEACIAFABIASgEQAAgCgFABIgHABQgDgGAcgHQAXgHAKAAQAAgBALgCQALgBABgCIAHgCIAHAAIADADIAFABQAAgBAAgBQgBgBABAAQAAgBAAAAQABAAABAAQgCgFAEgBIAJgCIAKAGQAKAGADgBIgHgDIgDgKIAGgFQADgBAFACQACABAMgFQALgFAAAEQADABAEgCQAEgCAAgCQAOAAADgFQAAgJAJAAQACgEAKAAIANAAQAFgBADgEQADgEADAAIAVAAIAEgJQADgDAEABIAGADQgBgJAGABIALADQADAAAEgDQAEgEADAAQACgCAJgFQALgFABACQAAgHAUgCQAUgCAAgCQAIAAAFgBIAFgDIAGgDQACgDALgDQAMgDAAAGQAEABAOgEQAGgEABgFQgEAAAEgHIAFgIQAEgCAAgJIANgHQAJgFAGAAQABACAKACIAMACQAAAEAMgGQALgFACgEQgHAAgCgMQAFAAAMgPQASgEAAgCQAMgCAOgGIAWgKQAFgFARgHQAOgGADgHQAGgCANgOQALgMAHAAQACgDAFgDQAFgEACgDQACgCAHgGQAHgFAAgEQACAAAFgIQAFgHAAgCQAEAAAJgXQAKgXgCgFQgCAAAAgMQABgMgEgCIADAAQgBAAgDgHIgHgRIgSgBQAAACgPgEQgPgDAAADQgmAHAAgBQgLABAAgCIgIABQgFABgDgDIgHABIgJABQAAgBAAAAQAAAAgBAAQgBAAAAAAQgBAAgBABIgGABQAAAEgMABQgLABgFgBIgPgBIgDAFQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIgOABQgCAHgNgEIgUgGQgBACgIABQgFABAAAHQgYAAgEABQAAADgUABQgUABAAACIgZABQgLAAgDADIgBABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgQABQAAABgGACIgIABQAAgBgSADQgTACAAACIgMADQgIACgFAAIgJAIQAAAEgJgHQgDAAgBADIgCAFQgBADgEABIgGABQAAAEgMAAQgBACgEABQgEABgDADQgDADgGAAQAAgEgGABIgKACQAAAFgWgCQAAAGgJADQgLADgCACQgCAAgEADIgHAEQgEACgCgBQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgDAAgCgCQgEgCgCAAIgIADIgIACQgDgCgEACIgHADIgEAEQgEAEAAACQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABIgBAEIgEAFIgCAAQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgDABgCgCQgDgCgCABQgFAJgVACIgUAMQgKAEgEgDIAAgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAQAAgBgKAHQAAAHgEABIgIgCQgBgBgHADQgHADgBACQgFAAgDADQgDADABAEIgMACQgNADgEAFQgEAAgBAFIAAAGIgRAJQgEAGgIAAIgMgCQACAMgGACIgMAHQgMAIAAgFQgGgEgBADIAAAEQAAADgKAIQgLAGgEABQAAACgGAEIgKADQAAgGgFAEQgHAFACAAQAAAFgHAIQgGAHgFAEQgCAFgFADIgKAEQgJADgDgEIgIAHQgFAFAGAAIgCAHIgGAJQgFAGgCAAIgKAJQgHAHgCAEQgGAAgCADIgEAJQgEABgEAFIgGAHQACAEgZAYQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIAPgBIAqgFQAAAFARgHIAFAAIADgCQAAAAABAAQABgBAAAAQAAAAABAAQAAAAAAABIAEACQABgFAKgDIAJgEQAGAAAVgEQASgDAEAIQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAgBABAAQACgEACAAQAAgBAFABIAHAAQAAgBAGAAIAJgBQAAABAAAAQAAABABAAQAAAAABAAQABAAABAAQAAgKAqAAQAAgEAKgBIAOgBQAAgHAZgBQAZgCAAADQADgBAEgEQAEgDACAAQAAgCAHACIAIACQAAAHAVgMQAAgCAHgDIAJgCQAFAHAHgBIARgDIAOgBQAHgBAAgGQgEADgEAAQAAgEADgCQAEgCABgCIAOgCIAGgCQAAgFALAAIAPAAQAHAHAGgGQAJgKAEgBQAMAAAAgCQAFAAADAFQACAFgHAAQAAAEAHACQAGADAAgFQgEAAgBgDQAAgEAEAAQAAgCAKAAIAGgEQAFgCAAgDQAHAAAEgDQABgCAEABQAEABACgBQAEgHALAAQACABAHgDIAIgEQAVgLAAAFQALAAgDgBQgIgEgBgCQgHgCAGgCIAJgBIAFAGQACACAEABQAMAAAAgCIAYgLQAFAAAJgEQALgEAFAAQAAgEAMgEQAKgDAFAAQABgCAFgCQAFgCACgCQAQgEACAAQAEABADgDQAFgFADgBIAJgFQAHgDACAEQACADgLANQgEAAgHAGQgIAFgEAAQAAAFgNAGQgOAGgCAEQgCAEgKACQgIABgCAEQgEAAgHAFIgJAHQgcALAAgBIgTAPIgMAEIgLAEQgZAGgGAIQgGgBgGAEQgGADgEAAQAAABgMABQgLABAAAGIgQADQgLACgEAEQgMAGgHABQAAACgJADIgKAEIgEAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgKADQgEAGgJABIABADIgGACIgHACIgJAAQgFgBgEABIgKAGQgKAFAAgBQgIAAgPAFQgPAFgJAAQAAABgWAEQgWAEAAADQgdALAAgEQgEAAgIAFQgHAFgEAAIgQAFQgRAEgBABIgZAFIgkAJQgaAAgCAEIgIACIgIACQAAgDgUAHIgNAEQgIADgHAAQgKADgFAAIgTAAQgFAFgMAAQgNgCgFABQAAABgIACIgLADIgBgBIgIACgAz3D2QAEgHgIgCQAAgBgEgEIgFgFQgDAAgIgFQgHgEgEAAQgBgDgHgGQgHgGgDAAQAAgCgLgIQgLgIgEAAQACAFAGAIQAGAHAFADQANAKgCAAQADAFAGAAQAWATAAgCQACABAFgCQAAAHALAAgApzCuIAGAEQgEABgCADQgDAEADADQAFADgDADIgEAEQATgEAAgBQADgBAFABIAHACIAEgBIADgDIADgBIAKgCQgFgZACAAIgCgJQgCgGABgDIACgOQABgIABgEQADAAgBgIQgBgIgGgBIgMASQAAAFgGAJQgGAJABAEQgGADgCACIgEAJQgCAAgCAEIgDAFQAAAEgIgGQgBABAGAEgAnqBaQgEAAgDAIQgEAKgDABQgDAVgBAAIAAACQgDAAgDAUQgDAUACADQADgBAFgIIADgIQADgHACAAIAFgLQAEgIACAAIADgHQAEgFAAgDQACAAAEgJIAFgLIAIgGQAHgGAAgCQAEAAABgDIABgIQACAAACgDQABgEADAAQAIgJABgEQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIACgFQAIgFAHgLQAEAAAGgJQAFgJAGAAQAegLgOAAQAAgGAFgCIAJgDQAAgGAIgEQAIgEAAgFQAFgBADgEQAEgFADgBQACgDAMgGQALgFAAgEQAKgGAGAAQAAgEAIgFQAIgEAAgDIAGgEIAHgEIAHgFQADAAAIgHQAIgGABABIALgGQAIgFACgDQAHgFABgGQAFAAAGgBQAGgCAJgGQAAAHAMgIIAPgKQACAAAGgEIAHgGQABgBAIgDIAIgDQAhgKAAgDQAFAAAJgEQAIgDAGAAQABgEAFACQAHABACgIIAGgCQACAAAHgEQACgCAOgEQANgDAAgCIAJgDQAGgDAAgDQAQgCAAgBIAJgCQAHgCAAgBQAFAAAKgEQALgFAGgBQAAgBAIgDIALgCQA2gRAEAAQAAgBAOgDIAQgEQATABAAgGQAFAAALgDQAKgDAGAAIAfgIQAAgCAMgBIAOgBQAAgCAMgCQAMgBABgCQAEAAAGgCQAHgDAEAAIAMABQAHgBADgDQAXgCAKgDQAAgEAygEQADgFAeAAQASABARgEQAAgFA4gBIA+gBQAAgCAGABQABAAABAAQABAAAAgBQABAAAAgBQAAAAAAgBIADAAIgBgCQgEAAgEgIQgFgIgDAAQAAgDgHgHQgHgGAAgEQAHgCAJADQALADAAAIQAEABAFAEQAFAEACAEQADACAAAFIADABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAEADQAEgBAEABQAGABAMgBIAUAAIAmACQAhABAAABQAIABAHgBQAAgCAUACIAZADQArACAAACIAzAEQArAFAAAGQAKAAAUAFQAVAEAKAAQAAACAPADQAPACAAACQAHABAKAEQAJADAHABQADABAHADQAGADADAAQAAADAJAAQAKABABACIAcAJQAEAAAIAEQAJAEACADQAOAHAAgDIAEABIACACQAEAAALAGQALAGAAABQAFAAAIAGQAIAFAEAAQAAABAHAFQAHAEACAAQAAABAIADQAIAEABACQADADAKAFQAIAFADAEQAHAAgHgJQgGgKgFAAIgEgEQgEgDAAgCQgIAAgHgKQgEAAgKgJQgLgKAAgDIgLgBQgHgCAAgEIgDgCIgGgBQgIgIgCgBIgOgHQgGgEgHAAQgEgFgKgDQgEgBgBgCQgCgDgCgBQAAgCgSAAQAAgGgLgCIgPgCQgHAAgHgDQgIgEAAgEQgIAAgNgJQgNgKgHAAQAAgBgKgCIgKgBQgZgHAAgCIgPgDQgIgDgEAAQAAgEgdgGQgZgEgKAAQAAgCgOAAQgPgBAAgEIgXgDQAAgDgbgCIgbgDQgZgDgMAAQAAgBgMgBQgMgBgBgBIgbgBQAAADgogCQgBgCgOAAQgNgBAAACQgDABgGgBIgIgBQgRACgIgBIgKADQAAABgKAAIgMgBQAAADgVACQgVABgFgBIgwAEIg5AEQgFAAgYAEQgZAEAAACIgXACIgUADQAAAHgyACQAAADgkAGQgCADgJAAQgJAAgDAEQgFgBgGACIgJABQAAACgOABQgNABAAADIgeAJQgSAFgLAAIgdAKQgeAJgCgBQAAAEgNACQgOACgBAEIgOAEQgIACgFABQAAABgHADIgIACQAAABgKAEIgPADQgCAEgLADQgLADgCAEQgEAAgGADQgHAEgDAAQgVAFgFAHQgFAAgIAGQgJAGgFAAQgDADgHAEQgHAEgEAAQgCADgPAIQgEAAgJAHQgIAHgHgCQgBAEgJAAQgBAEgIADQgNAFgHAGIgPAJIgPAJIgJAIQgEAFgFAAQABgCgKAHQAAAGgYAPQgLAMgKAEQAAABgEADIgGAEQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAABgFAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQgDAEgMAHIgDAEIgEAEQAAADgEAEQgDAEgDAAIgFAHIgHAFQAAACgJAIQgDADgEACQgFABgDADQAAADgEACQAAADgDACIgGAEQgCACAAAEQAAAFgCACIgFADQgDAAgCADQgCAFgBAAQgBACgEAGQgEAFgCABQAAAGgJAGQgKAGAAAGQABAAgFARIABAIQgBAFgDABIgBABIAAAAIgBABgAxpmXQgDABgCACIgCAFQgHAAgCADQgCAAgGADQgFADgCACIgHADIgGADQgGAHgTAGQgCAEgKACQgKABgBADIgHAGQgGAFAAABQgOAAgBAHIgSAOQgEAAgPAKQgJAGgGAHQgCADgFADQgFADgCADQAAAHgIAEQgKAEgBAFQgCABgDAGQgCAEgDABQgBACgGAFQgFAEAAADIgJAJIgIALIgDACQACACAlgbQAmgdAHgBIAHgFQAEgDADAAQAAgBAEgCIADgEQgDgBAAgEIAMgBQAIgCACgCIADgCQAAgBABAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgCAGgDQAFgDACAAQACgDALgFQAJgEACgDQADAAAFgFIAHgHQAMgEABgBQADAAAHgEQAJgEADgBQACgCAHAAQAEABABgFQABgJANAAIAHgIQACgDAFABQAFABABgDQACAAAHgEQAHgFACgBQAAgCARgHQAQgHADABIgBgEQAGgBAHgEQAHgEAFgBIALgFQAHgEACgDQADAAAFgCIAHgDQACgCAFAAIAIABQACgFADgCQAGgHAPgDIAYgDQACgDAIgDQAIgDAEAAQAAgDAIACQACABAEgCIAGgEIAIgEQAEgCADAAQAEgGAOgEIAWgEQAGgBALgDQAOgEAAgDIAHgCIAFgDIAJABQAFgBAAgFQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAABgBIACgDIgGgDIgvAMIgCgBQAAACgLABQgKACAAABQgHAAgLAGQgLAGgGABIAAgDQgFAAgKADQgJADgFAAQgEgBgCADIgFAEQgEAEgCAAIgHgDIgIAEQgIADgBAEIADABQgBADgFAAQgEABACgEQgDAAgHADQgHADgEAAIgFACQgGADgBACIgDAFQgDABgDgBQgCAGgOAFQAAABgFABQgFAAAAABIgLACQgEABgCAHIgDABQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgKAAAAgCQgCAAgDACQgEADgCABIgOAHQgNAIACABIgNAGIgNgCIgDABgAlSlJQgFgDAKgGIALgHQAIgDAAgBQABgBABAAQAAAAABAAQABAAAAAAQAAABABABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQACACgOAJQgJAGgFAAIgEgBg");
	this.shape_1.setTransform(7.7928,27.7457,0.4948,0.4948);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABwDnIAAkXQAAgygageQgbgeguAAQgfAAgdAPQgdAPgkAjIAAFEIhjAAIAAnEIBjAAIAAA8IADAAQAdghAogSQAngSAqAAQBLAAAvAtQAxAxAABZIAAEWg");
	this.shape_2.setTransform(117.997,94.1892,0.4949,0.4949);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjCCoQhLhEAAhnQAAhiBNhCQBNhDBxgBQB2AABNBCQBNBBAABlQAABqhMBCQhMBDh4AAQh1AAhLhEgAh4hvQgvAqAABCQAABGAuAsQAtArBIABQBPgBAugqQAugrAAhIQAAhBgwgrQgxgrhKAAQhGAAguArg");
	this.shape_3.setTransform(90.4194,94.4243,0.4949,0.4949);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiqEwQhCgnAAg8QABgyAegeQAfgfBBgOQgygbAAgeQAAgWAWgRQAWgRAjgIIAAgCQg3gVgdgkQgbgjAAgyQAAhIA8gqQA7gqBkAAIDRAAIAABFIhoAAQAeAbAMAWQALAVAAAdQAAAbgPAeQgNAcgTARQgiAghdAPQgoAGgOAGQgXAJAAARQAAASAnAOQAiAMBQAOQBNAOAlAjQAhAfgBAuQAABEg/AmQg/AmhvAAQhmAAhBgmgAhtCYQggATAAAeQAAAiAkASQAkASBEAAQBBAAAlgRQAlgSAAgfQgBgmg7gUQgsgOg9AAQgyAAggATgAhIjvQgdAYAAAhQABAlAbAXQAcAXAtAAQApAAAcgYQAbgYAAglQAAgggdgYQgdgYgnAAQgpAAgeAZg");
	this.shape_4.setTransform(64.4501,100.1526,0.4949,0.4949);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABoAAQBmAAA5A+QA8BAAAB7IliAAQAYCHCQAAQBVAABbg2IAABXQguAcgsAMQgxAOg9AAQhxgBhEhJgAhPiAQgjAdgKA2ID9AAQgDg0gfgeQgggeg0AAQg4AAgiAdg");
	this.shape_5.setTransform(39.7057,94.4243,0.4949,0.4949);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ai3DnIAAnEIBkAAIAABoIACAAQBHhxBKAAQA6AAA/A1Ig1BNQgXgTgbgNQgagMgSAAQgzAAgjAoQgjApAAA6IAADsg");
	this.shape_6.setTransform(19.9101,94.1892,0.4949,0.4949);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Aj1DJQhahSAAh3QAAh3BchTQBfhVCUAAQCWAABfBVQBbBSAAB4QAAB3haBSQhfBXiYAAQiVAAhfhXgAitiYQhGA8AABcQAABcBGA9QBFA9BoAAQBpAABFg9QBFg8AAhdQAAhchFg8QhFg9hpAAQhoAAhFA9g");
	this.shape_7.setTransform(-9.6965,91.7272,0.4949,0.4949);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABnAAQBnAAA5A+QA8BAAAB7IljAAQAMBCArAjQAqAiBIAAQBUAABdg2IAABXQgwAcgrAMQgwAOg/AAQhvgBhFhJgAhQiAQgjAdgKA2ID+AAQgDg0gfgeQgggeg0AAQg4AAgjAdg");
	this.shape_8.setTransform(-41.7282,94.4243,0.4949,0.4949);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ai4DnIAAnEIBkAAIAABoIADAAQBHhxBKAAQA7AAA9A1Ig1BNQgWgTgbgNQgagMgSAAQgyAAgkAoQgkApAAA6IAADsg");
	this.shape_9.setTransform(-61.1773,94.1892,0.4949,0.4949);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ABFDgQgTgLgHgYQhAAuhHABQg2AAgkgiQgiggAAguQABg7A3gkQAfgUBVgbIBYgcIAAgYQAAgpgWgUQgWgTguAAQhZAAhHBLIAAhiQA7g+BtAAQBQABAxAjQA1AoAABKIAADoQAAAXATAAQARAAAkgYIAAA2QgjAVgTAHQgUAIgWAAQghAAgSgMgAhCAtQgxAbAAAkQABAcAUASQAVASAeAAQAsAAArgmIAAiDQhOAXggATg");
	this.shape_10.setTransform(-84.536,94.4243,0.4949,0.4949);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AjIDAQhRhQAAhnQAAiABhhUQBhhUCUAAQBcAAB7AuIAABXQg6gfg0gOQgzgOg3AAQhqAAhHA9QhHA+AABbQAABeBGA8QBGA7BwAAQBsAABug/IAABXQgzAYgwAMQg6AOhFAAQihAAhfhgg");
	this.shape_11.setTransform(-112.7818,91.9993,0.4949,0.4949);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CO_v_white, new cjs.Rectangle(-126.7,-7.3,264.2,124.39999999999999), null);


(lib.BUTTON = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAqIAlgqIglgpIAaAAIAmApIgmAqgAg2AqIAmgqIgmgpIAbAAIAlApIglAqg");
	this.shape.setTransform(34.925,8.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag5BQIAAicIAeAAIAAAOQAHgIAJgFQAJgEAJAAQALAAAKAEQAJAEAHAHQAGAIAEALQAEALAAAPQAAAOgEAKQgEALgGAIQgHAIgJAEQgKAEgLAAQgJAAgJgFQgJgEgHgJIAAA6gAgQgxQgHAEgEAFIAAAoQAEAFAHAEQAIAEAHAAQAMAAAIgJQAIgIAAgPQAAgPgIgKQgIgJgMAAQgHAAgIAEg");
	this.shape_1.setTransform(19.425,10.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgOBPIAAidIAdAAIAACdg");
	this.shape_2.setTransform(9.85,6.025);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgUA4QgMgFgIgIQgIgHgFgMQgEgKAAgOQAAgLAEgMQAFgLAHgHQAIgJALgFQALgEAMAAQANAAAKAEQALAFAHAJQAIAHAEAMQAEAMAAANIAAAHIhUAAQACAKAIAIQAIAIAOAAIAIgBIAIgCIAIgDIAHgGIANAUQgJAIgMAEQgNAEgNAAQgMAAgLgEgAgKghQgFADgEAEIgFAHIgCAJIA3AAIgCgJIgFgHQgDgEgFgCQgGgDgHAAQgGAAgFACg");
	this.shape_3.setTransform(1.025,8.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAXBPIAAhGQAAgLgFgEQgGgFgJAAQgIAAgHAFQgGAEgEAEIAABNIgfAAIAAidIAfAAIAAA6QAFgGAKgGQAKgFANAAQAUAAAIAJQAJAKAAARIAABQg");
	this.shape_4.setTransform(-11.8,6.025);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgaBMQgJgEgIgHQgGgIgEgLQgEgMAAgOQAAgOAEgKQAEgLAGgIQAHgHAKgFQAJgEAKAAQAKAAAJAFQAJAEAHAJIAAg6IAeAAIAACcIgeAAIAAgOQgHAIgJAFQgJAEgKAAQgKAAgJgEgAgSgDQgIAIAAAPQAAAIACAGQADAGADAEQAEAFAFACQAGACAFAAQAHAAAIgDQAHgEAEgGIAAgoQgEgFgHgDQgIgEgHAAQgMAAgIAJg");
	this.shape_5.setTransform(-30.65,6.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAXA6IAAhDQABgMgGgFQgGgFgKAAQgIAAgGAFQgHAEgEAFIAABLIgdAAIAAhwIAdAAIAAAOQAGgHAKgFQAJgGAPAAQASAAAKALQAIAJABARIAABPg");
	this.shape_6.setTransform(-43.35,8.05);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgOBRIAAhxIAdAAIAABxgAgMgyQgFgFAAgHQAAgIAFgFQAGgFAGAAQAIAAAEAFQAGAFAAAIQAAAHgGAFQgEAGgIAAQgGAAgGgGg");
	this.shape_7.setTransform(-52.55,5.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag3BPIAAidIBvAAIAAAeIhNAAIAAAhIBLAAIAAAdIhLAAIAABBg");
	this.shape_8.setTransform(-61.275,6.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// bkgd
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00A7B5").s().p("Aq0C4IAAluITwAAIB6CtIh6DBg");
	this.shape_9.setTransform(-10.4,3.85);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	// shad
	this.instance = new lib.Buttonshad();
	this.instance.setTransform(-80,-15,0.6438,0.6438);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BUTTON, new cjs.Rectangle(-96.8,-15,166.2,56), null);


(lib.BKGDblue = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#256BA2").s().p("A3ZKVIAA0pMAuzAAAIAAUpg");
	this.shape.setTransform(0,66.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGDblue, new cjs.Rectangle(-149.7,0,299.5,132.2), null);


(lib.BKGD = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF8300").s().p("A96WbMAAAgs1MA71AAAMAAAAs1g");
	this.shape.setTransform(0.0067,125.0449,0.7833,0.8714);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGD, new cjs.Rectangle(-150,0,300,250.1), null);


(lib.HEAD3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD3type();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD3, new cjs.Rectangle(-139,0,289.1,95.4), null);


(lib.HEAD2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD2type();
	this.instance.setTransform(0,50.95,1,1,0,0,0,0,36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-139,15,278,64.9), null);


(lib.HEAD1b = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1btype();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1b, new cjs.Rectangle(-139,0,278,95.4), null);


(lib.HEAD1a = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1atype();
	this.instance.setTransform(0,24,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1a, new cjs.Rectangle(-139,0,278,95.4), null);


// stage content:
(lib.CO_SchoolisBack_300x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,289];
	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_289 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(289).call(this.frame_289).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,2,0,3).p("EgXWguyMAutAAAMAAABdlMgutAAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(290));

	// HS logo
	this.instance = new lib.HS_logowhite();
	this.instance.setTransform(149.9,567.75,0.31,0.31,0,0,0,0.7,71.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(290));

	// CO logo
	this.instance_1 = new lib.CO_v_white();
	this.instance_1.setTransform(240.2,569.2,0.35,0.35,0,0,0,0.1,55.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(290));

	// CTA
	this.instance_2 = new lib.BUTTON();
	this.instance_2.setTransform(-27.3,566.95,0.76,0.76,0,0,0,-10.4,3.9);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(274).to({_off:false},0).to({x:52.7},15,cjs.Ease.quadOut).wait(1));

	// BKGD-orange
	this.instance_3 = new lib.BKGD();
	this.instance_3.setTransform(150,591.25,1,0.2639,0,0,0,0,217);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(290));

	// HEAD1a
	this.instance_4 = new lib.HEAD1a();
	this.instance_4.setTransform(145.5,446.65,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(119).to({alpha:0},8,cjs.Ease.quadInOut).to({_off:true},1).wait(162));

	// HEAD1b
	this.instance_5 = new lib.HEAD1b();
	this.instance_5.setTransform(145.5,446.65,1,1,0,0,0,0,24);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(43).to({_off:false},0).to({alpha:1},6).wait(70).to({alpha:0},8,cjs.Ease.quadInOut).to({_off:true},1).wait(162));

	// HEAD2
	this.instance_6 = new lib.HEAD2();
	this.instance_6.setTransform(145.5,458.65,1,1,0,0,0,0,36);
	this.instance_6.alpha = 0;
	this.instance_6.shadow = new cjs.Shadow("rgba(0,163,181,1)",0,0,0);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(133).to({_off:false},0).to({alpha:1},8).wait(60).to({alpha:0},8).to({_off:true},1).wait(80));

	// HEAD3
	this.instance_7 = new lib.HEAD3();
	this.instance_7.setTransform(145.5,446.65,1,1,0,0,0,0,24);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(210).to({_off:false},0).to({alpha:1},8).wait(72));

	// BKGD-blue
	this.instance_8 = new lib.BKGDblue();
	this.instance_8.setTransform(149.75,472.1,1,1,0,0,0,0,66.1);
	this.instance_8.alpha = 0.6992;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(290));

	// PIC
	this.instance_9 = new lib.MhSubstance_300x600();
	this.instance_9.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(290));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(57.1,299.5,243.4,301);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 300,
	height: 600,
	fps: 36,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/CO_SchoolisBack_300x600_atlas_P_1.png", id:"CO_SchoolisBack_300x600_atlas_P_1"},
		{src:"images/CO_SchoolisBack_300x600_atlas_NP_1.jpg", id:"CO_SchoolisBack_300x600_atlas_NP_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;