(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"CO_SchoolisBack_300x600_atlas_P_1", frames: [[0,0,232,87]]},
		{name:"CO_SchoolisBack_300x600_atlas_NP_1", frames: [[0,0,300,600]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Buttonshad = function() {
	this.initialize(ss["CO_SchoolisBack_300x600_atlas_P_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.sch_img_300x600 = function() {
	this.initialize(ss["CO_SchoolisBack_300x600_atlas_NP_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.HS_logowhite = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ap9EXIAHnRINagKIgCh7IGDgCIAZKDgAFdgfQgVAOgIAYQgGAUAAAZQAAAaAGATQAJAZAVAOQAVAOAgAAQAyAAAeggQADgDgEgCIgZgYQgCgDgEADQgSARgZAAQgfAAgHgZIgDgKQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIBxAAQAEAAAAgEQAAglgGgUQgIgYgVgOQgVgOgfABQgeAAgVANgAgnAvQgVAQAAAdQAAAdASAPQARAOAaAAQAjAAAQgVIABAAIAAANQAAADAEAAIArAAQADAAAAgDIAAh4QAAgjgSgPQgUgRgtABQgqAAgaASQgDACACADIARAeQACADADgDQAQgKAZAAQAWAAAIAEQAIAHAAANIAAAHQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIghAAQgkAAgUAOgAnMBXIgZAdQgCACACADQAiAdAzAAQAoAAAWgSQAVgRABgeQAAgyg/gGIgUgCQgPgCgGgEQgFgDAAgHQAAgOAYgBQAbAAAXAOQAEADACgDIAVgaQADgDgDgDQgegWguAAQgkgBgVARQgUAQAAAaQAAAzA9AHIAVABQAQACAGAEQAFAEAAAHQAAASgdAAQgfAAgagVIgDgBIgDABgACfgkIAACyQAAADAEAAIAuAAQAEAAAAgDIAAhjQAAgnAdgCQAMAAAPAJQADABACgCIAWgmQACgEgDgCQgNgLgUABQgjgBgOAYIAAAAIAAgPQAAgFgEAAIguAAQgEAAAAAFgAieAiIAABsQAAADAEAAIAuAAQAEAAAAgDIAAh2QAAgegRgTQgRgUgeABQghAAgPAUIgBAAIAAhZQAAgDgEAAIguAAQgEAAAAADIAAD/QAAADAEAAIAuAAQAEAAAAgDIAAhsQAAgPAIgKQAIgJAOAAQAdAAAAAig");
	this.shape.setTransform(25.025,83.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAaAAQABABABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_1.setTransform(27.15,92.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeATQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBQAAgGACgIQAHgTAXgBQAZABAGATQACAGAAAIQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_2.setTransform(65.075,85.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AqIk4IUcAvIAII0I03AOgAhWAjQgVAQAAAeQgBAdAUAPQAQAOAbAAQAkAAAPgVIAAANQAAADAEAAIArAAQAEAAAAgDIAAh5QAAgjgSgPQgUgRgsAAQgrAAgcATQgCACACADIARAfQACACADgBQARgMAZAAQAWAAAIAGQAHAGAAAMIAAAHQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIghAAQgjAAgVAOgAkagrQgVAOgIAZQgHATAAAZQAAAXAHAWQAIAaAWAOQAVAOAgAAQAzAAAdggQADgDgDgCIgagYQgCgDgDADQgSAQgZAAQgfAAgIgYQgCgDgBgIQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIBxAAQAFAAAAgEQAAgmgGgTQgJgZgUgOQgWgOgfAAQgeAAgVAOgADcgxIAAAhQAAAEAFAAIALAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAABUQAAAhAOAPQAOAPAgAAIAUAAQAEAAABgEIAAgnQgBgDgEAAIgJAAQgJAAgDgEQgFgFAAgKIAAhSQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAYAAQAEAAABgEIAAghQgBgDgEAAIgYAAQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAgyQAAgEgDAAIguAAQgFAAAAAEIAAAyQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgLAAQgFAAAAADgABth9IAADKQAAAfANAPQAOAOAfAAIAVAAQADAAAAgEIAAgnQAAgDgDAAIgIAAQgRAAAAgSIAAjGQAAgEgEAAIgvAAQgDAAAAAEgAHggBQAIAIAAAQIAABsQAAADADAAIAvAAQAEAAAAgDIAAh3QAAgegRgTQgQgUgfAAQghAAgQAWIAAAAIAAhaQAAgEgEAAIguAAQgFAAAAAEIAAEAQAAADAFAAIAuAAQAEAAAAgDIAAhsQAAgQAIgIQAIgKAOAAQAOAAAHAKgAmpgBQAHAIAAAQIAABsQAAADAFAAIAuAAQAEAAAAgDIAAh3QAAgegRgTQgRgUgfAAQghAAgPAWIAAhaQAAgEgEAAIgvAAQgDAAAAAEIAAEAQAAADADAAIAvAAQAEAAAAgDIAAhsQAAgQAIgIQAHgKAOAAQAOAAAIAKg");
	this.shape_3.setTransform(-21.95,31.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeABQAAgVAgAAIAbAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAANQAAAZgiAAQgbgBAAgTg");
	this.shape_4.setTransform(-24.5,39.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeASQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAgGADgIQAHgUAXAAQAYAAAIAUQACAIAAAGQAAABgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-45.05,31.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AJdAwIAcgBQABAJANAAQAPABAAgNIAAgIQgIAFgMAAQgRAAgLgMQgKgLAAgSQAAgSAKgLQALgMARAAQANAAAIAHIAAgFIAaAAIAABRQAAARgLALQgLAKgTAAQgmAAgFgggAJ4AAQAAASAPAAQAHgBAEgEQAEgEAAgIIAAgCQAAgHgEgFQgFgEgGAAQgPAAAAARgALLAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgALbAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAILAeQgLgLAAgTQAAgSALgLQAMgMASAAQASAAAKAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgKAHQgLAHgOAAQgTAAgMgLgAI0gIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgAFOAZQgRgQAAgaQAAgaARgRQAQgQAbAAQAbAAARAQQARARAAAaQAAAagRAQQgRAQgbAAQgbAAgQgQgAFjgpQgIAJAAAPQAAAPAIAJQAIAIAOAAQAOAAAIgIQAJgJAAgPQAAgPgJgJQgIgIgOgBQgOABgIAIgACHAdQgMgLAAgSQAAgSAMgLQAMgMATAAQATAAAMAMQAMALAAASQAAASgMALQgMAMgTAAQgTAAgMgMgACXAAQAAASAPAAQAPAAAAgSQAAgRgPAAQgPAAAAARgAAJAeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgPAAQgTAAgLgLgAAygIQgBgMgLAAQgKAAgBAMIAXAAIAAAAgAiVASQAAgWAigCIAJAAIAAgEQAAgIgGAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAh6AQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAlOAfQgNgKAAgTIAegBQAAAGAFAEQAFAFAHAAQANgBAAgIQAAgHgTgFQgTgFgIgGQgLgHAAgQQAAgQAKgJQALgMAUAAQAUAAAMALQAMAJABASIgeABQAAgNgOAAQgMAAAAAKQAAAEAEACQADADAMADQATAEAIAHQALAJAAANQAAASgMAKQgMAIgTAAQgVAAgNgKgAoUANIAAgdIgOAAIAAgXIAOAAIABgZIAbAAIAAAZIARAAIAAAXIgRAAIAAAWQAAALALAAIAGgBIAAAYIgNABQggAAAAgcgAqjASQAAgWAigCIAKAAIAAgEQAAgIgHAAQgHAAAAAHIgcgBQAAgLAJgJQAKgJAQAAQAiAAAAAhIAAAvIgaAAIAAgFQgHAHgMAAQgaAAAAgXgAqIAQQAAAFAHAAQAEAAACgCQADgDAAgDIAAgEIgHAAQgJABAAAGgAr0AeQgLgLAAgTQAAgSALgLQALgMATAAQARAAALAKQALALAAATIAAAIIgzAAQAAANAMAAQAIAAACgHIAcACQgCAMgLAHQgKAHgOAAQgTAAgMgLgArLgIQgBgMgKAAQgLAAgBAMIAXAAIAAAAgANWAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAhOIAaAAIAAAFQAGgHAOAAQAOAAAIAIQAJAJAAAPIAAAwgAHGAnIAAhOIAbAAIAAAGQAHgHAOAAIAAAbQgJAAgGAFQgFAEAAAGIAAAlgADlAnIAAg3IgOAAIAAgXIAOAAIAAgFQAAgQAKgKQAKgJAQAAIAJAAIAAAZIgGgBQgFAAgDADQgDADAAAEIAAAGIARAAIAAAXIgRAAIAAA3gAg7AnIAAhOIAbAAIAAAGQAGgHAPAAIAAAbQgKAAgFAFQgFAEAAAGIAAAlgAjAAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAGgGAMAAQAOAAAIAIQAJAJAAAPIAAAwgAmnAnIAAgpQAAgNgKAAQgLAAAAANIAAApIgcAAIAAh1IAcAAIAAArQAHgGALAAQAOAAAIAIQAJAJAAAPIAAAwgApJAnIAAh1IAcAAIAAB1gAstAnIAAgsIgmAAIAAAsIgeAAIAAhwIAeAAIAAAqIAmAAIAAgqIAeAAIAABwg");
	this.shape_6.setTransform(0.175,134.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HS_logowhite, new cjs.Rectangle(-88.7,0,177.5,143), null);


(lib.HEAD2type = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgRASQgIgHAAgLQAAgKAIgHQAGgHALAAQALAAAHAHQAIAHAAAKQAAALgIAHQgHAHgLAAQgLAAgGgHg");
	this.shape.setTransform(112,56.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAcBCIgbhIIgbBIIghAAIglhkQgCgFgCgCQAAAAgBAAQAAAAAAgBQgBAAgBAAQAAAAgBAAIgHAAIAAgXIBIAAIAAAXIgHAAQgEAAgBADQgBABABAFIAEAMIAIAVIAHATIAHgTIAIgVIAEgMQABgFgBgBQgCgDgDAAIgGAAIAAgXIBDAAIAAAXIgGAAQgEAAgCADQgBABACAFIAEAMIAIAVIAJAUIAHgUIAHgUIAEgNQABgFgCgCQAAAAAAgBQgBAAAAAAQgBgBgBAAQAAAAgBAAIgIAAIAAgXIA2AAIAAAXIgHAAQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAgBAAIgDAHIgjBkg");
	this.shape_1.setTransform(97.475,52.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AglA9QgQgJgJgQQgJgPAAgVQAAgUAJgQQAJgPARgJQAQgJAVAAQAVAAAQAJQAQAJAJAPQAJAQAAAUQAAAVgJAPQgJAQgQAJQgRAIgVABQgVgBgQgIgAgUgiQgGAKAAAXIAAADQAAAWAGAKQAHAKANAAQAOAAAHgKQAHgKgBgWIAAgDQABgXgHgKQgHgKgOAAQgNAAgHAKg");
	this.shape_2.setTransform(78.525,52.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAIBEIAAgYIAIAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAAAQACgCAAgFIAAgzQAAgNgFgFQgEgGgKABQgKgBgGAJQgGAJAAASIAAAnQAAAFABACQABAAAAAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAIAAAYIhIAAIAAgYIAJAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgJAAIAAgYIAaAAIATgBQAIgBAFgBIAAAYQAHgNALgGQAKgGAPAAQAVAAALANQALAMAAAaIAAA0QAAAFACACQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_3.setTransform(62.775,51.975);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgQBNQgLgLABgXIAAhDIgQAAIAAgVIAIgBQAIgBAFgEQAEgEACgIIACgXIAeAAIAAAnIAYAAIAAAXIgZAAIAABDQAAAKAEAEQAEADAIAAIAHAAIAEgCIAAAZIgLADIgPABQgWAAgLgKg");
	this.shape_4.setTransform(43.2,50.425);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgkBfIAAgYIAKAAQAAAAABAAQABAAAAAAQABgBAAAAQAAgBABAAIABgGIAAhBQAAgGgBgCQgCgDgDABIgJAAIAAgYIAbAAIASgBIANgCIAABmQAAAEACACQAAAAAAABQABAAAAABQABAAAAAAQABAAAAAAIAKAAIAAAYgAgRg1QgHgHAAgKQAAgKAHgGQAGgIALABQALgBAHAIQAHAGAAAKQAAAKgHAHQgHAHgLAAQgLAAgGgHg");
	this.shape_5.setTransform(34.725,49.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AghBCQgNgDgJgEIAAgjIAeAAIAAAVIAJACIAMABQAJAAAGgEQAFgEABgHQgBgIgHgEQgIgDgLgCQgMgCgLgFQgKgEgHgHQgGgIgBgOQAAgVAPgMQAQgMAbAAQARAAAOAEQANADAHAEIAAAiIgdAAIAAgUIgIgCIgLgBQgJAAgFAEQgGAEAAAGQAAAGAEADQADADAHABIANADQAMACAKAFQAKAEAIAHQAGAIABAPQgBAVgPAMQgPAMgdABQgRgBgOgDg");
	this.shape_6.setTransform(24.45,52.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgkBfIAAgYIAKAAQAAAAABAAQABAAAAAAQABgBAAAAQAAgBABAAIABgGIAAhBQAAgGgBgCQgCgDgDABIgJAAIAAgYIAbAAIASgBIANgCIAABmQAAAEACACQAAAAAAABQABAAAAABQABAAAAAAQABAAAAAAIAKAAIAAAYgAgRg1QgHgHAAgKQAAgKAHgGQAGgIALABQALgBAHAIQAHAGAAAKQAAAKgHAHQgHAHgLAAQgLAAgGgHg");
	this.shape_7.setTransform(14.125,49.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgPBCIgthkQgCgFgCgCQAAAAgBAAQAAAAAAgBQgBAAgBAAQAAAAgBAAIgIAAIAAgXIBMAAIAAAXIgKAAQgDAAgCADQgBABABAFIAGAPIAJAUIAIAWIAKgYIAJgUIAFgNQABgDgBgDQgCgDgEAAIgKAAIAAgXIA9AAIAAAXIgIAAQgDAAgDABQgCADgCAEIgsBkg");
	this.shape_8.setTransform(2.325,52.25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgzBUQgNgIgHgRQgHgPAAgVQAAgVAHgOQAHgQANgJQANgJASAAQAQAAAJAHQALAFAFAMIAAgjIgBgHQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgLAAIAAgZIAcAAIATAAIANgCIAACWQAAAEACACQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAJAAIAAAXIg1AAIgBgJIgBgOQgFAMgLAIQgKAGgSABQgSAAgNgJgAgZgJQgHAKAAAUIAAAEQAAAVAHAKQAIAKAMAAQALAAAHgKQAIgKAAgVIAAgEQAAgUgIgKQgHgJgLAAIgBAAQgMAAgHAJg");
	this.shape_9.setTransform(-20.125,49.85);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgjBbIAAgXIAKAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBAAAAQABgCAAgEIAAhzIgBgHQAAAAAAAAQgBgBAAAAQgBAAAAAAQgBAAAAAAIgKAAIAAgZIAbAAIASAAIANgCIAACWQAAAEABACQABAAAAABQABAAAAAAQABAAAAAAQAAABABAAIAJAAIAAAXg");
	this.shape_10.setTransform(-32.65,49.65);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgkBfIAAgYIAKAAQAAAAABAAQAAAAABAAQABgBAAAAQAAgBABAAIABgGIAAhBQAAgGgBgCQgCgDgDABIgJAAIAAgYIAbAAIASgBQAIgBAFgBIAABmQAAAEACACQAAAAAAABQABAAAAABQABAAAAAAQABAAAAAAIAKAAIAAAYgAgRg1QgHgHAAgKQAAgKAHgGQAGgIALABQALgBAHAIQAHAGAAAKQAAAKgHAHQgHAHgLAAQgLAAgGgHg");
	this.shape_11.setTransform(-40.725,49.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAJBbIAAgXIAHAAQABAAABgBQAAAAABAAQAAAAAAAAQABgBAAAAQABgCAAgEIAAg0QAAgMgEgGQgEgFgKAAQgKAAgHAJQgFAIgBASIAAAoQAAAEACACQAAAAABABQAAAAAAAAQABAAAAAAQABABABAAIAIAAIAAAXIhIAAIAAgXIAJAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQACgCAAgEIAAhzIgBgHQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAIgKAAIAAgZIAbAAIATAAIANgCIAABGQAHgMAKgFQALgHAPAAQAVAAALANQALAMAAAZIAAA2QAAAEABACQAAAAABABQAAAAABAAQAAAAABAAQAAABABAAIAKAAIAAAXg");
	this.shape_12.setTransform(-53,49.65);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgvAzQgTgSAAghQAAggATgSQATgTAiAAQAdAAAQAMQAQAMAAAVQAAAOgHAIQgHAIgNAAQgLAAgGgGQgGgFAAgJQAAgJAEgGQAFgFAJgCQgDgFgGgCQgGgCgJAAQgPAAgJAKQgIALAAAVIAAAEQAAAVAIAKQAIALAPAAQAMAAAIgGQAIgGAFgLIAXAMQgGAQgOALQgPAKgZABQgigBgTgSg");
	this.shape_13.setTransform(-68.125,52.175);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgjAOIAAgbIBHAAIAAAbg");
	this.shape_14.setTransform(-79.475,52.15);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgjBbIAAgXIAJAAQABAAABgBQAAAAABAAQAAAAABAAQAAgBAAAAQACgCAAgEIAAhzIgCgHQAAAAAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAIgJAAIAAgZIAbAAIARAAIAOgCIAACWQAAAEACACQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAIAAIAAAXg");
	this.shape_15.setTransform(-87.8,49.65);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgjBbIAAgXIAJAAQABAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQAAgCAAgEIAAhzIAAgHQgBAAAAAAQAAgBgBAAQAAAAgBAAQgBAAgBAAIgKAAIAAgZIAbAAIASAAIAOgCIAACWQAAAEABACQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAIAAIAAAXg");
	this.shape_16.setTransform(-95.95,49.65);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgjA8QgQgIgIgQQgIgQAAgUQAAgUAJgQQAIgPAQgJQAQgJAUAAQAhAAAQATQARATAAAhIAAAGIhZAAQAAARAJAJQAIAJAPAAQAOAAAHgGQAIgGAEgKIAXANQgEAKgJAIQgHAIgNAFQgMAEgRABQgXgBgRgJgAAZgMQAAgSgFgHQgHgIgKAAQgLAAgHAIQgGAIgBARIAvAAIAAAAg");
	this.shape_17.setTransform(-107.2,52.175);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAcBCIgbhIIgbBIIghAAIglhkQgCgFgCgCQAAAAgBAAQAAAAAAgBQgBAAgBAAQAAAAgBAAIgHAAIAAgXIBIAAIAAAXIgHAAQgEAAgBADQgBABABAFIAEAMIAIAVIAHATIAHgTIAIgVIAEgMQABgFgBgBQgCgDgDAAIgGAAIAAgXIBDAAIAAAXIgGAAQgEAAgCADQgBABACAFIAEAMIAIAVIAJAUIAHgUIAHgUIAEgNQABgFgCgCQAAAAAAgBQgBAAAAAAQgBgBgBAAQAAAAgBAAIgIAAIAAgXIA2AAIAAAXIgHAAQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAgBAAIgDAHIgjBkg");
	this.shape_18.setTransform(-125.725,52.25);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag8A7QgLgJAAgQQAAgRAMgKQAMgJATgFQAUgFAWgEIAAgHQAAgMgGgFQgGgFgLAAIgIAAIgGABQACADAAADIABAHQAAAJgGAGQgHAFgKAAQgLAAgHgFQgGgGAAgLQAAgNAIgHQAIgIAPgEQAOgEAUAAQAgAAAOALQAPAKAAAZIAAA5IABAGQAAABAAAAQABABAAAAQABAAAAAAQABAAAAAAIAJAAIAAAYIgwAAIgGgKQgCgFgCgHQgDAIgHAFQgGAGgJADQgJADgLABQgTgBgKgKgAgRAKQgLAFgBAMQAAAIAFAEQAEAEAHAAQANAAAHgIQAHgJAAgPIAAgJQgTACgMAGg");
	this.shape_19.setTransform(-6.625,21.9239);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgjA8QgQgIgIgQQgIgQAAgUQAAgUAIgQQAJgPAQgJQAQgJAUAAQAhAAARATQAQATAAAhIAAAGIhaAAQABARAIAJQAJAJAPAAQANAAAIgGQAIgGAEgKIAXANQgEAKgJAIQgIAIgLAFQgNAEgRABQgYgBgQgJgAAZgMQgBgSgFgHQgFgIgMAAQgLAAgGAIQgGAIgBARIAvAAIAAAAg");
	this.shape_20.setTransform(-27.95,21.925);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgjBbIAAgXIAJAAQABAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQABgBAAgFIAAhyIgBgIQgBAAAAAAQAAgBgBAAQAAAAgBAAQgBAAgBAAIgKAAIAAgZIAbAAIASAAIAOgCIAACWQAAAFABABQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAIAAIAAAXg");
	this.shape_21.setTransform(-39.35,19.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("Ag2A3QgLgMAAgaIAAg0QAAgFgBgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAAAAAIgKAAIAAgYIA7AAIAABUQAAAMAFAFQAEAGAJgBQALAAAFgIQAHgIgBgRIAAgpQAAgFgBgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgMAAIAAgYIA+AAIAABiIABAHQAAABABAAQAAAAAAABQABAAAAAAQABAAAAAAIAMAAIAAAYIgcAAIgUABIgNACIAAgXQgGAMgLAGQgKAGgPAAQgVAAgLgNg");
	this.shape_22.setTransform(-51.55,22.125);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgzBUQgNgJgHgPQgHgQAAgVQAAgVAHgOQAHgQANgJQANgJASAAQAQAAAJAHQALAFAFAMIAAgiIgBgIQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgLAAIAAgZIAcAAIATAAIANgCIAACWQAAAFACABQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAJAAIAAAXIg1AAIgBgJIgBgOQgFAMgLAIQgKAGgSABQgSAAgNgJgAgZgJQgHAKAAAUIAAAEQAAAVAHAKQAIAKAMAAQALAAAHgKQAIgKAAgVIAAgEQAAgUgIgKQgHgKgLABIgBAAQgMAAgHAJg");
	this.shape_23.setTransform(-67.925,19.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgjA8QgQgIgIgQQgIgQAAgUQAAgUAJgQQAIgPAQgJQAQgJAUAAQAhAAARATQAQATAAAhIAAAGIhZAAQAAARAJAJQAIAJAPAAQAOAAAHgGQAIgGAEgKIAXANQgEAKgJAIQgHAIgNAFQgMAEgRABQgYgBgQgJgAAZgMQAAgSgGgHQgFgIgMAAQgKAAgHAIQgGAIgBARIAvAAIAAAAg");
	this.shape_24.setTransform(-83.55,21.925);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAIBbIAAgXIAIAAQABAAABgBQAAAAABAAQAAAAAAAAQABgBAAAAQABgBABgFIAAg0QgBgLgEgGQgEgGgKAAQgLAAgFAJQgHAHAAATIAAAoQABAFABABQAAAAABABQAAAAAAAAQABAAAAAAQABABABAAIAIAAIAAAXIhIAAIAAgXIAJAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQACgBAAgFIAAhyIgBgIQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgKAAIAAgZIAbAAIATAAIANgCIAABGQAHgMAKgFQAKgHAQAAQAVAAALANQALAMAAAZIAAA2QAAAFABABQAAAAABABQAAAAABAAQAAAAABAAQAAABABAAIAJAAIAAAXg");
	this.shape_25.setTransform(-99,19.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgvAzQgTgSAAghQAAggATgSQATgTAiAAQAdAAAQAMQAQAMAAAVQAAAOgHAIQgHAIgNAAQgLAAgGgGQgGgFAAgJQAAgJAEgGQAFgFAJgCQgDgFgGgCQgGgCgJAAQgPAAgJAKQgIALAAAVIAAAEQAAAVAIAKQAIALAPAAQAMAAAIgGQAIgGAFgLIAXAMQgGAQgOALQgPAKgZABQgigBgTgSg");
	this.shape_26.setTransform(-114.125,21.925);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgnBZQgRgDgNgIIAAgrIAkAAIAAAcIAPADIAQABQALABAIgGQAIgFABgLQgBgIgEgFQgEgEgKgDIgWgGQgRgEgMgHQgMgGgHgJQgGgLgBgQQABgcASgQQAUgQAiAAQATAAAOAEQAPADANAGIAAAsIgkAAIAAgbIgLgCIgNgBQgOAAgIAGQgHAFgBALQAAAHAFAEQAEAFAIADIAVAFQAQAEANAGQANAGAIAJQAJALAAARQAAATgJANQgIAOgRAGQgQAIgXAAQgUAAgRgEg");
	this.shape_27.setTransform(-129.1,19.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2type, new cjs.Rectangle(-139,0,278,68.5), null);


(lib.HEAD1btype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSASQgHgHAAgLQAAgKAHgHQAHgHALAAQALAAAHAHQAIAHAAAKQAAALgIAHQgHAHgLAAQgLAAgHgHg");
	this.shape.setTransform(-9.4,56.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhCBTQgLgIAAgPQAAgLAGgHQAHgHALAAQAJAAAFAFQAGAEABAHQABAIgEAJQAIgCAGgHQAFgHAEgMIAAgBIguhiIgEgGQAAgBgBAAQAAAAgBAAQAAgBgBAAQgBAAAAAAIgIAAIAAgXIBKAAIAAAXIgHAAQgEAAgBADQgBADABADIAYA2IAVg1QACgFgCgCQgCgDgEAAIgIAAIAAgXIA7AAIAAAXIgJAAQgDAAgCACIgEAGIgoBgQgHASgHAMQgHAMgLAGQgKAGgQAAQgSAAgKgIg");
	this.shape_1.setTransform(-20.525,54.725);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgzBUQgNgIgHgRQgHgPAAgVQAAgVAHgOQAHgQANgJQANgJASAAQAQAAAJAHQALAFAFAMIAAgjIgBgHQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAIgLAAIAAgZIAcAAIATAAIANgCIAACWQAAAEACACQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAJAAIAAAXIg1AAIgBgJIgBgOQgFAMgLAIQgKAGgSABQgSAAgNgJgAgZgJQgHAKAAAUIAAAEQAAAVAHAKQAIAKAMAAQALAAAHgKQAIgKAAgVIAAgEQAAgUgIgKQgHgJgLAAIgBAAQgMAAgHAJg");
	this.shape_2.setTransform(-36.375,49.85);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag8A7QgLgJAAgQQAAgRAMgKQAMgJATgFQAUgFAWgEIAAgHQAAgMgGgFQgGgFgLAAIgIAAIgGABQACADAAADIABAHQAAAJgGAGQgHAFgKAAQgLAAgHgFQgGgGAAgLQAAgNAIgHQAIgIAPgEQAOgEAUAAQAgAAAOALQAPAKAAAZIAAA5IABAGQAAABAAAAQABABAAAAQABAAAAAAQABAAAAAAIAJAAIAAAYIgwAAIgGgKQgCgFgCgHQgDAIgHAFQgGAGgJADQgJADgLABQgTgBgKgKgAgRAKQgLAFgBAMQAAAIAFAEQAEAEAHAAQANAAAHgIQAHgJAAgPIAAgJQgTACgMAGg");
	this.shape_3.setTransform(-52.175,52.1739);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgjA8QgQgIgIgQQgIgQAAgUQAAgUAJgQQAIgPAQgJQAQgJAUAAQAhAAAQATQARATAAAhIAAAGIhZAAQAAARAJAJQAIAJAPAAQAOAAAHgGQAIgGAEgKIAXANQgEAKgJAIQgHAIgNAFQgMAEgRABQgXgBgRgJgAAZgMQAAgSgFgHQgHgIgKAAQgLAAgHAIQgGAIgBARIAvAAIAAAAg");
	this.shape_4.setTransform(-67.15,52.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag+BEIAAgYIAJAAQABAAAAAAQABAAABAAQAAAAAAgBQABAAAAAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgKAAIAAgYIAbAAIATgBIAOgCIAAAdQADgQAJgHQAJgHANAAQAPAAAJAKQAJAKAAAQQAAAPgIAIQgHAIgNAAQgJAAgGgFQgFgFgBgJQAAgFAEgFQADgFAFgDIgDgCIgFAAQgLAAgGAKQgFAKAAATIAAAkQAAAFABACQABAAAAAAQAAABABAAQAAAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_5.setTransform(-80.975,51.975);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgjA8QgQgIgIgQQgIgQAAgUQAAgUAIgQQAJgPAQgJQAQgJAUAAQAhAAARATQAQATAAAhIAAAGIhaAAQABARAIAJQAJAJAPAAQANAAAIgGQAIgGAEgKIAXANQgEAKgJAIQgIAIgLAFQgNAEgRABQgYgBgQgJgAAZgMQgBgSgFgHQgFgIgMAAQgLAAgGAIQgGAIgBARIAvAAIAAAAg");
	this.shape_6.setTransform(-101.3,52.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag+BEIAAgYIAJAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgKAAIAAgYIAbAAIATgBQAJgBAFgBIAAAdQADgQAJgHQAJgHANAAQAPAAAJAKQAJAKAAAQQAAAPgIAIQgHAIgNAAQgJAAgGgFQgFgFgBgJQAAgFAEgFQADgFAFgDIgDgCIgFAAQgLAAgGAKQgFAKAAATIAAAkQAAAFABACQABAAAAAAQABABAAAAQAAAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_7.setTransform(-115.125,51.975);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag8A7QgLgJAAgQQAAgRAMgKQAMgJATgFQAUgFAWgEIAAgHQAAgMgGgFQgGgFgLAAIgIAAIgGABQACADAAADIABAHQAAAJgGAGQgHAFgKAAQgLAAgHgFQgGgGAAgLQAAgNAIgHQAIgIAPgEQAOgEAUAAQAgAAAOALQAPAKAAAZIAAA5IABAGQAAABAAAAQABABAAAAQABAAAAAAQABAAAAAAIAJAAIAAAYIgwAAIgGgKQgCgFgCgHQgDAIgHAFQgGAGgJADQgJADgLABQgTgBgKgKgAgRAKQgLAFgBAMQAAAIAFAEQAEAEAHAAQANAAAHgIQAHgJAAgPIAAgJQgTACgMAGg");
	this.shape_8.setTransform(-129.275,52.1739);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AggBCQgOgDgKgEIAAgjIAfAAIAAAVIAJACIAMABQAKAAAFgEQAFgEABgHQgBgIgHgEQgIgDgMgCQgLgCgKgFQgLgEgHgHQgGgIgBgOQAAgVAQgMQAPgMAbAAQARAAAOAEQANADAHAEIAAAiIgdAAIAAgUIgIgCIgLgBQgJAAgGAEQgFAEAAAGQAAAGAEADQADADAHABIANADQAMACAKAFQAKAEAIAHQAGAIABAPQAAAVgQAMQgPAMgdABQgQgBgOgDg");
	this.shape_9.setTransform(115.9,21.925);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgzBUQgNgJgHgPQgHgQAAgVQAAgVAHgOQAHgQANgJQANgJASAAQAQAAAJAHQALAFAFAMIAAgiIgBgIQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAIgLAAIAAgZIAcAAIATAAIANgCIAACWQAAAFACABQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAJAAIAAAXIg1AAIgBgJIgBgOQgFAMgLAIQgKAGgSABQgSAAgNgJgAgZgJQgHAKAAAUIAAAEQAAAVAHAKQAIAKAMAAQALAAAHgKQAIgKAAgVIAAgEQAAgUgIgKQgHgKgLABIgBAAQgMAAgHAJg");
	this.shape_10.setTransform(101.425,19.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgkBfIAAgYIAKAAQAAAAABAAQABAAAAgBQABAAAAAAQAAgBABAAIABgGIAAhAQAAgHgBgCQgCgCgDAAIgJAAIAAgYIAbAAIASgBQAIgBAFgBIAABmQAAAEACACQAAAAAAABQABAAAAAAQABABAAAAQABAAAAAAIAKAAIAAAYgAgRg1QgHgGAAgLQAAgKAHgHQAGgGALAAQALAAAHAGQAHAHAAAKQAAALgHAGQgHAGgLABQgLgBgGgGg");
	this.shape_11.setTransform(88.975,19.05);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAHBbIAAgXIAHAAQABgBABAAQAAAAAAAAQABgBAAAAQAAAAAAgBIgBgEIgQgcIgTASIAAAJQABAFABABQAAAAABABQAAAAAAAAQABAAAAAAQABABABAAIAIAAIAAAXIhIAAIAAgXIAJAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQACgBAAgFIAAhyIgBgIQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgKAAIAAgZIAbAAIATAAIANgCIAAByIAkghQABgBAAAAQAAgBAAAAQABgBAAAAQAAgBgBgBQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAgBAAIgMAAIAAgXIBJAAIAAAXIgKAAQgEAAgDABIgFAEIgWASIAiA3QACADACABIAEACIAGAAIAAAXg");
	this.shape_12.setTransform(76.85,19.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag+BEIAAgYIAJAAQABAAAAAAQABAAABAAQAAAAAAgBQABAAAAAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgKAAIAAgYIAbAAIATgBIAOgCIAAAdQADgQAJgHQAJgHANAAQAPAAAJAKQAJAKAAAQQAAAPgIAIQgHAIgNAAQgJAAgGgFQgFgFgBgJQAAgFAEgFQADgFAFgDIgDgCIgFAAQgLAAgGAKQgFAKAAATIAAAkQAAAFABACQABAAAAAAQAAABABAAQAAAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_13.setTransform(55.825,21.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ag2A3QgLgMAAgaIAAg0QAAgFgBgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgKAAIAAgYIA8AAIAABUQAAAMAEAFQAFAGAKgBQAJAAAHgIQAFgIAAgRIAAgpQABgFgCgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgMAAIAAgYIA+AAIAABiIABAHQAAABABAAQAAAAAAABQABAAAAAAQABAAABAAIALAAIAAAYIgcAAIgTABIgOACIAAgXQgGAMgLAGQgKAGgPAAQgVAAgLgNg");
	this.shape_14.setTransform(40.9,22.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AglA9QgQgJgJgQQgJgPAAgVQAAgUAJgQQAJgPARgJQAQgJAVAAQAVAAAQAJQAQAJAJAPQAJAQAAAUQAAAVgJAPQgJAQgQAJQgRAIgVABQgVgBgQgIgAgUgiQgGAKAAAXIAAADQAAAWAGAKQAHAKANAAQAOAAAHgKQAHgKgBgWIAAgDQABgXgHgKQgHgKgOAAQgNAAgHAKg");
	this.shape_15.setTransform(25.075,21.925);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhCBTQgLgIAAgPQAAgLAGgHQAHgHALAAQAJAAAFAFQAGAEABAHQABAIgEAJQAIgCAGgHQAFgHAEgMIAAgBIguhiIgEgGQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgIAAIAAgXIBKAAIAAAXIgHAAQgEAAgBADQgBADABADIAYA2IAVg1QACgFgCgCQgCgDgEAAIgIAAIAAgXIA7AAIAAAXIgJAAQgDAAgCACIgEAGIgoBgQgHASgHAMQgHAMgLAGQgKAGgQAAQgSAAgKgIg");
	this.shape_16.setTransform(9.575,24.475);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgjA8QgQgIgIgQQgIgQAAgUQAAgUAIgQQAKgPAPgJQAQgJAUAAQAhAAARATQAQATAAAhIAAAGIhZAAQAAARAJAJQAIAJAPAAQAOAAAHgGQAIgGAEgKIAXANQgEAKgJAIQgHAIgMAFQgNAEgRABQgYgBgQgJgAAZgMQAAgSgGgHQgFgIgMAAQgLAAgGAIQgGAIgBARIAvAAIAAAAg");
	this.shape_17.setTransform(-11.65,21.925);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag+BEIAAgYIAJAAQABAAAAAAQABAAABAAQAAAAAAgBQABAAAAAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgKAAIAAgYIAbAAIATgBQAJgBAFgBIAAAdQADgQAJgHQAJgHANAAQAPAAAJAKQAJAKAAAQQAAAPgIAIQgHAIgNAAQgJAAgGgFQgFgFgBgJQAAgFAEgFQADgFAFgDIgDgCIgFAAQgLAAgGAKQgFAKAAATIAAAkQAAAFABACQABAAAAAAQAAABABAAQAAAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_18.setTransform(-25.475,21.725);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag2A3QgLgMAAgaIAAg0QAAgFgBgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAAAAAIgKAAIAAgYIA7AAIAABUQAAAMAFAFQAEAGAJgBQALAAAFgIQAHgIAAgRIAAgpQgBgFgBgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgMAAIAAgYIA+AAIAABiIABAHQAAABABAAQAAAAAAABQABAAAAAAQABAAAAAAIAMAAIAAAYIgdAAIgTABIgMACIAAgXQgHAMgLAGQgKAGgPAAQgVAAgLgNg");
	this.shape_19.setTransform(-40.4,22.125);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AghBCQgNgDgJgEIAAgjIAeAAIAAAVIAJACIAMABQAJAAAGgEQAFgEABgHQgBgIgHgEQgIgDgLgCQgMgCgLgFQgKgEgHgHQgGgIgBgOQAAgVAPgMQAQgMAbAAQARAAAOAEQANADAHAEIAAAiIgdAAIAAgUIgIgCIgLgBQgJAAgFAEQgGAEAAAGQAAAGAEADQADADAHABIANADQAMACAKAFQAKAEAIAHQAGAIABAPQgBAVgPAMQgPAMgdABQgRgBgOgDg");
	this.shape_20.setTransform(-54.75,21.925);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgiA8QgRgIgIgQQgIgQAAgUQAAgUAIgQQAKgPAPgJQAQgJAUAAQAhAAAQATQARATAAAhIAAAGIhaAAQABARAIAJQAJAJAPAAQANAAAIgGQAIgGAEgKIAXANQgFAKgHAIQgJAIgMAFQgMAEgRABQgXgBgQgJgAAZgMQgBgSgEgHQgHgIgKAAQgLAAgHAIQgGAIgBARIAvAAIAAAAg");
	this.shape_21.setTransform(-74.6,21.925);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAHBbIAAgXIAHAAQABgBABAAQAAAAABAAQAAgBAAAAQAAAAABgBIgCgEIgQgcIgTASIAAAJQAAAFACABQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIAJAAIAAAXIhIAAIAAgXIAJAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQACgBAAgFIAAhyIgBgIQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAIgKAAIAAgZIAbAAIATAAIANgCIAAByIAkghQAAgBABAAQAAgBAAAAQABgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBAAQgBgBAAAAQgBAAgBAAIgMAAIAAgXIBJAAIAAAXIgKAAQgEAAgDABIgFAEIgWASIAiA3QACADACABIAEACIAGAAIAAAXg");
	this.shape_22.setTransform(-89.9,19.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("Ag8A7QgLgJAAgQQAAgRAMgKQAMgJATgFQAUgFAWgEIAAgHQAAgMgGgFQgGgFgLAAIgIAAIgGABQACADAAADIABAHQAAAJgGAGQgHAFgKAAQgLAAgHgFQgGgGAAgLQAAgNAIgHQAIgIAPgEQAOgEAUAAQAgAAAOALQAPAKAAAZIAAA5IABAGQAAABAAAAQABABAAAAQABAAAAAAQABAAAAAAIAJAAIAAAYIgwAAIgGgKQgCgFgCgHQgDAIgHAFQgGAGgJADQgJADgLABQgTgBgKgKgAgRAKQgLAFgBAMQAAAIAFAEQAEAEAHAAQANAAAHgIQAHgJAAgPIAAgJQgTACgMAGg");
	this.shape_23.setTransform(-105.425,21.9239);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAjBaIAAgYIALAAQABAAABAAQAAAAABAAQAAgBABAAQAAAAABgBQABgCAAgFIAAhyIgxCTIgbAAIgsiRIAABwIABAHQAAABABAAQAAAAABABQAAAAABAAQABAAAAAAIANAAIAAAYIhBAAIAAgYIAOAAQAAAAABAAQABAAAAAAQABgBAAAAQABAAAAgBQABgCAAgFIAAhxQAAgFgBgCQAAgBgBAAQAAAAgBAAQAAgBgBAAQgBAAAAAAIgOAAIAAgYIBVAAIAeBmIAihmIBSAAIAAAYIgMAAQgBAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBABQgBACAAAFIAABxQAAAFABACQABABAAAAQABAAAAABQABAAAAAAQABAAABAAIAMAAIAAAYg");
	this.shape_24.setTransform(-125.05,19.525);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1btype, new cjs.Rectangle(-139,0,278,68.5), null);


(lib.HEAD1atype = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSASQgGgHgBgLQABgKAGgHQAHgHALAAQAMAAAGAHQAIAHAAAKQAAALgIAHQgGAHgMAAQgLAAgHgHg");
	this.shape.setTransform(-44.85,56.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAHBbIAAgXIAHAAQABgBABAAQAAAAABAAQAAgBAAAAQAAAAABgBIgCgEIgQgcIgTASIAAAJQAAAEACACQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIAJAAIAAAXIhIAAIAAgXIAJAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQACgCAAgEIAAhzIgBgHQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAIgKAAIAAgZIAbAAIATAAIANgCIAAByIAkghQAAAAABgBQAAgBAAAAQABgBAAAAQAAgBAAAAQgBgBAAgBQAAAAgBAAQgBgBAAAAQgBAAgBAAIgMAAIAAgXIBJAAIAAAXIgKAAQgEAAgDABIgFAEIgWASIAiA2QACAEACABIAEACIAGAAIAAAXg");
	this.shape_1.setTransform(-56.15,49.65);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgvAzQgTgSAAghQAAggATgSQATgTAiAAQAdAAAQAMQAQAMAAAVQAAAOgHAIQgHAIgNAAQgLAAgGgGQgGgFAAgJQAAgJAEgGQAFgFAJgCQgDgFgGgCQgGgCgJAAQgPAAgJAKQgIALAAAVIAAAEQAAAVAIAKQAIALAPAAQAMAAAIgGQAIgGAFgLIAXAMQgGAQgOALQgPAKgZABQgigBgTgSg");
	this.shape_2.setTransform(-71.175,52.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag8A7QgLgJAAgQQAAgRAMgKQAMgJATgFQAUgFAWgEIAAgHQAAgMgGgFQgGgFgLAAIgIAAIgGABQACADAAADIABAHQAAAJgGAGQgHAFgKAAQgLAAgHgFQgGgGAAgLQAAgNAIgHQAIgIAPgEQAOgEAUAAQAgAAAOALQAPAKAAAZIAAA5IABAGQAAABAAAAQABABAAAAQABAAAAAAQABAAAAAAIAJAAIAAAYIgwAAIgGgKQgCgFgCgHQgDAIgHAFQgGAGgJADQgJADgLABQgTgBgKgKgAgRAKQgLAFgBAMQAAAIAFAEQAEAEAHAAQANAAAHgIQAHgJAAgPIAAgJQgTACgMAGg");
	this.shape_3.setTransform(-85.775,52.1739);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgJBUQgNgJgEgPIgHAdIggAAIAAgGIABgOIAAgZIAAhlIgBgHQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAIgKAAIAAgZIAbAAIATAAIANgCIAABJQAGgMALgIQAKgHAQAAQASAAANAJQAMAIAHARQAHAOAAAVQAAAVgHAPQgIARgMAIQgOAJgSAAQgTAAgLgJgAgMgJQgIAJAAAVIAAAEQAAAVAIAKQAHAKALAAQANAAAHgKQAIgKgBgVIAAgEQABgUgIgKQgHgJgNAAIgBAAQgKAAgHAJg");
	this.shape_4.setTransform(-101.95,49.85);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AggBCQgOgDgKgEIAAgjIAfAAIAAAVIAJACIAMABQAKAAAFgEQAFgEABgHQgBgIgHgEQgIgDgMgCQgLgCgKgFQgLgEgHgHQgGgIgBgOQAAgVAQgMQAPgMAbAAQARAAAOAEQANADAHAEIAAAiIgdAAIAAgUIgIgCIgLgBQgJAAgGAEQgFAEAAAGQAAAGAEADQADADAHABIANADQAMACAKAFQAKAEAIAHQAGAIABAPQAAAVgQAMQgPAMgdABQgQgBgOgDg");
	this.shape_5.setTransform(-122.6,52.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgkBfIAAgYIAKAAQAAAAABAAQABAAAAAAQAAgBABAAQAAgBABAAIABgGIAAhBQAAgGgBgCQgCgDgDABIgJAAIAAgYIAbAAIASgBIANgCIAABmQAAAEACACQAAAAAAABQABAAAAABQABAAAAAAQABAAAAAAIAKAAIAAAYgAgRg1QgHgHAAgKQAAgKAHgGQAGgIALABQALgBAHAIQAHAGAAAKQAAAKgHAHQgHAHgLAAQgLAAgGgHg");
	this.shape_6.setTransform(-132.925,49.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgjBbIAAgXIAJAAQABAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQABgBAAgFIAAhyIgBgIQgBAAAAAAQAAgBgBAAQAAAAgBAAQgBAAgBAAIgKAAIAAgZIAbAAIASAAIAOgCIAACWQAAAFABABQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAIAAIAAAXg");
	this.shape_7.setTransform(69.55,19.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AglA9QgQgJgJgQQgJgPAAgVQAAgUAJgQQAJgPARgJQAQgJAVAAQAVAAAQAJQAQAJAJAPQAJAQAAAUQAAAVgJAPQgJAQgQAJQgRAIgVABQgVgBgQgIgAgUgiQgGAKAAAXIAAADQAAAWAGAKQAHAKANAAQAOAAAHgKQAHgKgBgWIAAgDQABgXgHgKQgHgKgOAAQgNAAgHAKg");
	this.shape_8.setTransform(57.875,21.925);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AglA9QgQgJgJgQQgJgPAAgVQAAgUAJgQQAJgPARgJQAQgJAVAAQAVAAAQAJQAQAJAJAPQAJAQAAAUQAAAVgJAPQgJAQgQAJQgRAIgVABQgVgBgQgIgAgUgiQgGAKAAAXIAAADQAAAWAGAKQAHAKANAAQAOAAAHgKQAHgKgBgWIAAgDQABgXgHgKQgHgKgOAAQgNAAgHAKg");
	this.shape_9.setTransform(42.575,21.925);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAJBbIAAgXIAIAAQAAAAABgBQAAAAABAAQAAAAAAAAQABgBAAAAQACgBgBgFIAAg0QAAgLgEgGQgFgGgJAAQgKAAgHAJQgFAHgBATIAAAoQAAAFACABQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIAJAAIAAAXIhIAAIAAgXIAJAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQACgBAAgFIAAhyIgBgIQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAIgKAAIAAgZIAbAAIATAAIANgCIAABGQAHgMAKgFQALgHAPAAQAVAAALANQALAMAAAZIAAA2QAAAFABABQAAAAABABQAAAAABAAQAAAAABAAQAAABABAAIAKAAIAAAXg");
	this.shape_10.setTransform(26.75,19.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgvAzQgTgSAAghQAAggATgSQATgTAiAAQAdAAAQAMQAQAMAAAVQAAAOgHAIQgHAIgNAAQgLAAgGgGQgGgFAAgJQAAgJAEgGQAFgFAJgCQgDgFgGgCQgGgCgJAAQgPAAgJAKQgIALAAAVIAAAEQAAAVAIAKQAIALAPAAQAMAAAIgGQAIgGAFgLIAXAMQgGAQgOALQgPAKgZABQgigBgTgSg");
	this.shape_11.setTransform(11.625,21.925);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AghBCQgOgDgIgEIAAgjIAeAAIAAAVIAJACIAMABQAJAAAGgEQAFgEABgHQgBgIgHgEQgIgDgLgCQgMgCgLgFQgKgEgHgHQgHgIAAgOQAAgVAPgMQAQgMAbAAQARAAAOAEQANADAIAEIAAAiIgeAAIAAgUIgIgCIgLgBQgJAAgFAEQgGAEAAAGQAAAGAEADQADADAHABIANADQALACALAFQAKAEAIAHQAGAIABAPQgBAVgPAMQgQAMgcABQgRgBgOgDg");
	this.shape_12.setTransform(-1.75,21.925);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAIBEIAAgYIAIAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAAAQACgCAAgFIAAgzQAAgNgFgFQgEgGgKABQgKgBgGAJQgGAJAAASIAAAnQAAAFABACQABAAAAAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAIAAAYIhIAAIAAgYIAJAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgJAAIAAgYIAaAAIATgBQAIgBAFgBIAAAYQAHgNALgGQAKgGAPAAQAVAAALANQALAMAAAaIAAA0QAAAFACACQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_13.setTransform(-22.475,21.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AglA9QgQgJgJgQQgJgPAAgVQAAgUAJgQQAJgPARgJQAQgJAVAAQAVAAAQAJQAQAJAJAPQAJAQAAAUQAAAVgJAPQgJAQgQAJQgRAIgVABQgVgBgQgIgAgUgiQgGAKAAAXIAAADQAAAWAGAKQAHAKANAAQAOAAAHgKQAHgKgBgWIAAgDQABgXgHgKQgHgKgOAAQgNAAgHAKg");
	this.shape_14.setTransform(-38.525,21.925);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AghBCQgOgDgIgEIAAgjIAeAAIAAAVIAJACIAMABQAKAAAFgEQAFgEABgHQAAgIgIgEQgIgDgLgCQgMgCgLgFQgKgEgHgHQgHgIAAgOQAAgVAPgMQAQgMAbAAQARAAANAEQAOADAIAEIAAAiIgfAAIAAgUIgIgCIgKgBQgJAAgFAEQgGAEAAAGQAAAGADADQAEADAGABIAOADQALACALAFQALAEAGAHQAIAIAAAPQAAAVgQAMQgQAMgcABQgQgBgPgDg");
	this.shape_15.setTransform(-52.35,21.925);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag+BEIAAgYIAJAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgKAAIAAgYIAbAAIATgBQAJgBAFgBIAAAdQADgQAJgHQAJgHANAAQAPAAAJAKQAJAKAAAQQAAAPgIAIQgHAIgNAAQgJAAgGgFQgFgFgBgJQAAgFAEgFQADgFAFgDIgDgCIgFAAQgLAAgGAKQgFAKAAATIAAAkQAAAFABACQABAAAAAAQABABAAAAQAAAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_16.setTransform(-65.175,21.725);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgjA8QgQgIgIgQQgIgQAAgUQAAgUAIgQQAKgPAPgJQAQgJAUAAQAhAAARATQAQATAAAhIAAAGIhZAAQAAARAJAJQAIAJAPAAQAOAAAHgGQAIgGAEgKIAXANQgEAKgJAIQgHAIgMAFQgNAEgRABQgYgBgQgJgAAZgMQAAgSgGgHQgFgIgMAAQgLAAgGAIQgGAIgBARIAvAAIAAAAg");
	this.shape_17.setTransform(-79.15,21.925);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhOBbIAAgYIAJAAQABAAAAAAQABAAAAAAQABAAAAAAQAAgBABAAQABgCAAgFIAAhwQAAgGgBgBQAAgBAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAIgKAAIAAgYIAbAAIATgBIANgCIAAAcQAGgOALgIQAKgHARAAQARAAANAJQAMAIAHAQQAHAQAAAUQAAAVgHAPQgHAQgOAIQgNAJgRAAQgQAAgKgHQgKgGgFgNIAAAlQAAAFABACQAAAAABABQAAAAABAAQAAAAABAAQAAAAABAAIAKAAIAAAYgAAaALQAHgJAAgUIAAgFQAAgUgHgJQgHgKgMAAQgMAAgHAKQgHAJAAAUIAAAFQAAAUAHAJQAHAJAMAAQAMAAAHgJg");
	this.shape_18.setTransform(-94.875,24.05);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgjAOIAAgbIBHAAIAAAbg");
	this.shape_19.setTransform(-107.225,21.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAIBEIAAgYIAIAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAAAQACgCAAgFIAAgzQAAgNgFgFQgEgGgKABQgKgBgGAJQgGAJAAASIAAAnQAAAFABACQABAAAAAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAIAAAYIhIAAIAAgYIAJAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAQABgCAAgFIAAhCQAAgGgBgBQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgJAAIAAgYIAaAAIATgBIANgCIAAAYQAHgNALgGQAKgGAPAAQAVAAALANQALAMAAAaIAAA0QAAAFACACQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIAKAAIAAAYg");
	this.shape_20.setTransform(-119.525,21.725);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgoBaIAAgYIAMAAQADAAABgCIABgHIAAhxIgBgHQgBgCgDAAIgMAAIAAgYIBQAAIAAAYIgLAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBAAAAABQgCACAAAFIAABxQAAAFACACQAAABABAAQAAAAABABQAAAAABAAQABAAAAAAIALAAIAAAYg");
	this.shape_21.setTransform(-132.45,19.525);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1atype, new cjs.Rectangle(-139,0,278,68.5), null);


(lib.CO_v_white = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgyA1QgXgVAAggQAAgeAWgVQAVgWAeAAQAfAAAWAXQAVAVgBAdQAAAfgVAVQgVAVgfABQgdgBgVgUgAgvgvQgTAUAAAbQAAAcATAUQAUATAbAAQAcAAATgTQATgTABgdQAAgbgTgTQgUgUgcAAQgbAAgUATgAASAuQgCgDgCgKIgCgPQgCgIgFgEQgEgCgJAAIgGAAIAAAqIgRAAIAAhcIAfAAQAPAAAFACQAPAFAAARQAAAQgTAGQAGABADAEQADAEABAJQAEAVADAHgAgOgIIAOAAQATAAAAgNQAAgIgHgDQgDgBgMAAIgLAAg");
	this.shape.setTransform(133.8251,86.6356,0.4949,0.4949);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACmLBQgKgEgNACQgPADgIAAQAAgDgKgCIgOgBQgRABgHgCQAAgDgSACQgjgBAAgBIgUgCIgTgBQgLgCgHAAQAAgBgQABQgRABAAgDIgOgEQgJgDAAAHQgDAAgFgDQgEgDgDAAQAAAFgJgBIgNgDQgNgCgLACQgRACgYgKIgJgEQgEgCgEABQgCAAgIgEQgIgFAAgBIgMABIgMABQgIACgFgBQgDAAgDgEQgEgFgDAAIAAAEQgEAAgEgCQgGgDAAgEQgCAGgBAAQAAgDgIgDQgIgCgFAAIgBABQgBAAAAAAQAAgBAAABQgBAAAAAAQAAAAAAAAQgDABgFgEQgEgDgEABQgEABAAgDIgIgGQgHgFAAAEQgCABgMgFQgNgGAAgCIgTgJQgBABAAAAQgBABAAAAQAAABAAAAQAAAAABAAIgEABIAAAAIgEAAIAEAAQABADgQgGQgCgDgFAAQAAgGgDgCIAAAGIgFgDQgGgDAAADIgIgIIgOgCQAAgCgNgGQgNgGAAgCQgKgEgDgKQgBgDgJgBIgOgCQgTgKgBABQgEgCgCABIABgDQgCAAgQgKQgLgIgDgIIgLgDQgCgCgBgDQgBgBgFAAIgDgHIgCgHQgEgBgCACQgCACgCAAQgBgLgTAAQgPAAAAgBIgNgBIgMgBQgSAFgHgCQAAgBgYgBQgaAAgDgBQAAACgJgCIgNgDQgLAFgDgEQgNgEgCABQAAABgGAAIgHgBIgJgCQgDgCgFAAIgOABQAAABgOgEQgGAAgFgHQgCgBgNABIgMAAQgEABgcgDQgcgDAAgBIgJgDQgGgCgDAAIgXgDQgDgEgbgGQgagHAAgBQgCAAgEgCQgDgDgDABQgOACAAgEQgJgEgPAAQAAgFgKgBQgNgBgBgBQgLgFgFgDQgHgGgQgDIgYgEQgDgDgDABIgHACIgGgDIgHgCQAAgEgJgBQgJgBgCgFIAJgCQgBgEgMgEQgMgFAAACIgSgJQgFAAgIgGIgLgHIgMgEIgNgBIAVAVQAAADAHAGQAHAGABAEQADACAGAHQAGAGAEABQAKADAEAHQADAAAHADIAKAFIAHAEQAHAEAAACQAFAAAHADQAGADAEAAIAEACQABAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAFABAGAGQACAFAWAEQAVAEAAADIAYAKQADAAAGADQAFAEAEAAQACgBATAGIATAFQADAAAIAEQAGAEAEgBQAEgBAJAEQAKAEADAAQAAgBARAEIAVAFQAEAAAJACIANAEQAAABAOACIAQABQAAAFBNAGQADADAjADQAiAEAAABQBPAIAAgBQADgBAkAEQAiAEAAgBQAIgBAAABQgGAAgMAGQgOAGgFABIgMgCQgLgCAAADIgGABQgDABgDgBQAAAGgUABQgTABAAgDQgQACAAgCIgGACQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgLgBQgDgBgDgGQgDAAgCADQgBABgGAAIgNgBQgXgCgDgCIgFgFIgJABIgMgEQgKgDAAADQgGAAgKgCQgCgGgEABIgJAFQgFADgFgCQAAgCgLgCQgKgCgEABQAAACgWgEIgbgFQAAgCgOgBQgPgBgBgEQgHAAgLgDQgMgDgGgBQgCgCgNgBQgNgBAAgCQgGAAgJgCIgOgEIgNgEQgNgEAAgBIgNgCQgKgCAAgBQgFAAgGgCIgLgFIgDgBIgCgBQgLAAAQALQACACAGACQAGACADADIAKADQAAABAFABIAHABQAAACASADQAAADAaAEQAZAFABAHIgKACQAAgDgXgDQgZgDgCgDIgagHQgVgHAAgDIgZgIQgUgIAAgBQgIgCgKgEQgNgGgFgGIgIgFQgJgEAAABQgCAAgHgFQgIgFAAgCQgKAAgPgHQgRgJgCgJQgPgKgGAAIgIgIQgFgFgDgCIgGgIIgJgFQgGgCAAgDQgGgEgHgIQgHgJgDgGQgDgBgEgHQgFgHAAgCQgDAAgDgJQgDgKgEAAQAAgEgDgGQgEgFAAgFQgBAAgFgTIgGgYIgHgkQgHgjAFAAIgFgVQgBAAgBgLIgBgNQgDAAAAgNQgBgOgCAAIgJhUIAAggQAAgcACAAIgCgjQgBggAEAAIgCgxQgCgsAFgDQAAgEAKgaQALgZgBgEQAIAAAHgOQAHgPAGgCQACgBADgFQACgGADgCQAAgFAGgGQAHgGAHgBIgDgEQAAAAAAgBQAAAAAAgBQAAAAABgBQABAAABAAIAEgCQAAAAAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAHgHIAKgHIAFAAIAEgCQALgIgHAAQgCgGAFgEQAFgFAFAAIAIgDIAIgCQAKgFAKgJIAQgRQAGgGADgBIAFgDIACgEQACAAAOgLQAAgCANgFQANgGAAgEQAEAAAJgGQAJgHABgDIAOgJQAHgEAIAAQAAgBAGgDIAFgCIAJABQAGACABgDIAXgEQAOgEAAgJQADgBACgEIADgEQABgCAEgDQAEgCABgDIgBAAQAAgFAHACIAJACIARgCIAIgFIAKgEIAJgFQAHgEACAAIAEgCQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBQAFAAAFgCQAHgCAAgDQgHAAAHgHQAHgGAEgBIANgHQAFAAAGgDQAAgDAHgCQAGgCAAgEQAGAAAAADQADAAAEgCIAHgCIAKACQAGABACgDIAOgGQAJgGAEAAQAAgBALgEQAKgDAEAAQAAgCAHAAQAHAAAAgBQAJAAACgCQACgBAAgHIAFgDIAEgEIAJACIgBAFIAEgCIADgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAfAAAHgDQAEgBAGACIAKACQALgGgFAAQgCgJASgGQATgGAAAFQAMgIAZAAQACgDAJAAQAJABACgEIAXgEQAUgEAAgBIABABIAVgFQAWgFADAAQAVAAAAgEIAIgCQAHgBAAgBIAggHIAvgHQAOAAAggFQAggGAQAAQAAgFBQAAQAAABAGACQAHACAAACQgIAFgXgCIgQABIgRABQgJAAgRADQgSADgJAAQAAgChXATQAAAFArgFIAxgGIAugGIAbgDQARgCAJACQAUgDABAKQASAAAAABIAHABQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAABIgIAAQAAADg1ACQAAABgRADIgUACIgTAAQgSAAAAADIgwAHIgSACIgUACQAAADgMACIgQACQgIgBgPAEQgQAFgHAAIgMACQgMACAAACQgEAAgGAEQgHAEgDAAIgJAAIgJgBQAAADgQACQgPADgBADQgCAKgMADQgOABgIACQAAADgTAHQgHAKgHAEQACAIAiABQAfABAHgEQADgCAagEQAXgDAAgCIAMgCIAMgDQAAgBAGABIAHABQARgEAJAAQAAgBAcgDIAcgFQAfgDAAgBIAVgCIAWgCQAAgCAmgCQAngDAFABIApgDQAkgDAAACQAMgCAYACIAcgBQASgBALACQAAADAJACQAJACAAgCIAQABQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQADgBAKACQALADAAACQgEACgWABIgVAAIgmABQgCADgWAFQgVAFAAACIgQgBQgPgBAAACIgWAAQAAAFgZABIgegBQAAADglABQglACgBAIQARADAXgDIAngGQAAACAkgCQAjgBAAABQAFAAALgDQAEAAAEACQAFADAEAAIAQgBQAJABgEAGQgFAIghACIghACQhWAFAAADIgTACQgTACAAgCQgGgBgJADQgLADgDAAIgRACQgCACgGAAIgKgBQgGABgJAGQgIAGgGABQAAAFgdAEQAAABgHACQgIADAAABIgTADIgKACQgLACgBACQgRAAgMAMQgGABgKAFQgKAGgGABQAAgBgNAFIgPAFQAAgCgFABQgEAAgCACIAEABQgBADgMACIAAgEIgOAFQAKAIgUAEQgWAEAAACIgTAGQgNAFgGABQAAgCgvAQIgRAGQgRAGgCADQgTAAgDAEQgFAAgHAFQgGAEgFgBQgGAAgFAFQgGAGgFAAQgCgDgFACIgIAEIgKAFQgFACgFABQgBABgLADIgNACQAAAFgJACIgOADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABgBAAQgCADgEAAQgEAAgCADQgDAEgDACIgDADQgBABgEAAQgBgCgGgBQgFgCAAAEQgFAAgBAFQgDAHgCABQAAADgJAAQgOAJgCAAQAAACgMACQgLADAAAEIgMAGQgIAFAAADQgFABgFAEQgGAEgEABIgGADQgEACgCAAQgRAJgCAAQgEAEgFAAIgQAMQAAADgIAFQgIAEAAADQgGAEgOACQgBAEgEACQgFACgBABQgFAAgEAIQgEAHgDABQgEABgIAHQgIAFgDAAQAAAFgHAEQgIADgBAFQgSALgLANQgEAAgGAGIgIAKQgGAIgFADQgBADgFACQgFACAAAEQgCAAgHAJQgGAIgDAAIABADQgFAAgFAHIgHAKIgIAIIgHAJQgDAHgLANQgJALgBAJQADAAAGgHQAIgJACgBQAGgKAEAAQAAgDAHgFQAGgFABgCQgCAAAKgJIALgJQAGAAAEgJQAEgJADAAIAGgGQAGgFACAAQACgEAHgEIALgHQAAgCAEgFIAHgFIAVgPQADgHAUgGQABgDAJgEQAIgEAAgCQgBgEAGgCIAIgDIAWgOQAEAAAFgFQAGgEADAAIAhgUQAGgCARgIQATgJAAgDQAHgBACgDQAEAAABgDQACgDACAAQAHgCABgCIAIgEQAFgDAAgBIAGgDIAFgDQAAADAMgFQALgFACgDIAHgCQAFgCAAgBQAHgBAOgJQANgIAIAAQADgEAJgCQAIgCADgDQAEAAAGgEQAFgEAEAAQAFgFAIAAIAIgIIAHAAIAGgBIASgHQAAgBAGgCIAHgBQADgEAKgBIALgCQABgCAHgDQAIgEAAgCIAQgDQAAgCALgDQAJgCAEAAQAAgGANgBQANgBACgCIApgMQAhgJAAgFQAEAAASgFQARgGAAgBQAFAAAJgCQAKgCAAgEQAygGAAgEQALAAAQgFQATgHAHgBQAAgBAYgFIAbgFQAAgBAdgGIAhgHQAIgCANgBQAAgBAFgBIAHgBIATgEQAMgDAHABQAAAIgWAFIgeAFQgQAEAAACQgDAAgHAFQgHAFgFgBQAAAAgBgBQAAAAAAAAQAAAAgBAAQgBAAAAAAQAAACgZAIIgHAFQgEADgEAAQgDAEgGABIgMABIgbAJQgQAFgMACIgEADQgEADAAACQgEAAAFAEQAFADAAgEIAMgBQAKgBAAgCQAfAAgQAFIgHAEIgGAGQgCABgHgCQgEgBgCAGQgJgBgIAEQgKAEgIAAQgFAAgHAEQgGAEgEAAQAAAEAGAAIAGgCIAHgCQAAANgmACQgBADgGABQgDACgEgBQgEAAgDABQgBACgPAFQgFAGgSAAQgLABgBAGQgEgBgFACQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgEgCgBABQAAABgFAEIgIAEQgOAFAAACQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIABACIgGACQgEACgCgBQgBAGgKABIgOgBQAHAFgHADQgFACgGAAQAAgBgIAEIgIAEQgDAGgPAAQAAgDgGACIgEADQgBgDgEAFIgEAIIgGgCQgBAAgBAAQgBAAgBAAQAAAAgBABQAAAAAAABQgFACgIAAQgEAAgMACQgNADAAADQgDAAgEAEQgFAEgDAAIgbAKQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgDADQgEAAgDACQgDACgCAAQAAADgEABQgEACgDAAQgFgBgDAEQgEAFgDAAIgHAEIgFADQAAAGgKACIgOABQAAABgFADIgHADQgDABgHAIQgFAHgGgBQgHgCgJAJQgRAEgBADIgFACQgCABAAAEIgJgBQABABAAAAQABAAgBABQAAAAAAAAQgBABgBAAIgEAAQgBAAgBAAQAAAAAAABQgBAAAAABQAAABABABQAAAGgKAAQgCgCgGADIgJAEQgRAHgIAKQgJABgIAEIgPAJQAAAEgMAGQgMAHgCAFIgJAEQgGACAAAEIgMAFIgGACQgDABgCADIgCADIgEACQgJAHAAACQgDAAgCADQgDAEgCAAQgHABgFAEIgNAPQgHAIgJADQAAAGgOAJQgOAKAAAHQgEACAOALQAPANgBADQgFAAgGAKQgFAKgBAGQgDAAAPANQAPAMAAgEQAGAAAIAHQAIAHABAGQAAAEAKACQAKACACACIAMAJQAGAAALAGQALAFAGAAQAAAHArAAQAMAMAIAAQAAABAIAAQAJABABABIALAAQAGABAFADIAOAJQANAGAFgCIAKgCIALgCQAEADACAAQgCAEADACQACABANgBQAMAAACAEIATABIAIABIAJABQAAgCAPADIASADQADgEAGAAIALAAQABACAHAAQAHAAADADIAEAKQAEAIADgBIACAAIABgCIABgNQABgFAFAAIAKAAIAPACIARAAQAAgCAKADIAMAEQAAgFAKgCQAKgBAAAGIAugFIgBgCQADgCgDgPQgEgPABAAIgEgNQgFgMABAAQABgCgBgFQgBgFgCAAIgBgUQgBgFACgMQABgOACAAIAAgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBABAAQAFAAAAgZQACAAACgIIADgJQAAgFADgGQADgHABgFIAIgfIAIgQQAFgKAAgGQAEgCACgGQADgIADgCQAHgGgBgHQAMgMgBAAIAEgGQADgCACgEQgCgFAEgBQAAgCAFgGQAGgFAAgDQACgBAFgGQAFgHACAAQAAgDAFgDIAIgGQACAAAEgEQADgEAAgCQANgGAPgPIAFgCQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIgRANQgFACgFAIQgFAHgBAFQAGgBADgDIAGgIQAPgGAAgBQAIgCANgKQALgJAKAAIAIgBQADAAADgDQABgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQAAgDAEgBQAAgDAJgHQAIgHAFgCQADgBAFgEIAIABQACgCAFAAQABAAABAAQABgBAAAAQABAAAAgBQAAAAAAgBIAIgGQAHgGAAADQAGACAAgLQAGgBAFgEQACgCAJgCQAAgDACgDQADgDACAAQAAgCAMgGIANgHIACgFQABgCAEgBIAGgCIAGgFIAFgBIAFgCQAEgEAHgDQAIgDADgDQAFgEADACIAEADQADAHgOAHIgSAIQAAACgSAJIgMAJQgIAFgCAFQgEABgIAGQgIAGgGABQAAAIgLACIgMAJQgGAFgCAFQgIACgHAIQgCAAgDADQgDACgEAAQgGABgCAHQgIAEgCAJQgEACgEAFIgIAIIgPAMQgKAHAAAHQgNAGACANIgDAEIgCAGQgFACgBAJQgCAAgEAFIgFAFQgJAKAAgEQgDABgBAHQAAAGgIAAQAAABgEAEIgFAEIgBALIgGAJQgEAGgBAEIgMAKIgEAMIgGAEQgBACABAFQgBAAgEAHIgDAJQgDABgFAIIgHAHQAAATgIADQgGACABAJIAAANQgEAAgBAZQgBAZABAAQABgJAIgNQAKgOABgHQADAAAFgIQAEgGAAgDIALgUQACgBAFgIQAEgHAEAAQAEgPALgCQgCgKAMgGIANgPQABgEAJgIQAIgHAAgFQAFgCAGgIQAFgJAFgCQAAgDALgJQAJgIAFgDQAAgDALgHQAKgGAAgCQAGgEANgNIAPgNQAEAAADgFQADgFAEAAQACgEAHgGQAHgFAEgBQABgDAFgEQAHgEABgCQAIAAALgMQAMgMAGAAIAKgHQAIgFAAgCQADgBABgDQAAAAAAgBQABAAAAAAQABgBABAAQAAAAABAAQAIAAgCgGIAGAAQAAgCARgIQAQgJAEgBQAAgEATgKQARgJAGAAQADgGAJgFQAIgEAHgCQAAgBAJgEQAJgEACAAQACgCAUgJQATgIAAgBIAEgEQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAQABAAABAAIAGgBQAAgCAIgDIAIgCQADgDAIAEQACgJAFAAQAGgGAIAAQAAgCAHgCIAKgDQAFgHAZgGQABgCAGgBQAFgCACgCIAGgCIAHgCQAAgCAGgBQAGgBAAgBIAEADIAdgQQAAgBAMgDQALgCAAgCQAXgGAAgCIAJAAQAHAAADgEQADAAAPgJQABAAABAGQAAgIAVgEIAMgEQAJgDABAAQAQAKgEgHIgCgDQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAugJQACgEAXgEQAWgEAAgBIAIgDQAEgCADAAQAAgDARgBQATgCABgCQADAAADgDQADgDADAAQAAgCALAAQAngIADABQAAgCAvgIQAHABANgDIAVgGQAYgFAGAAQA9gJAGAAQAJgBAVgEQATgEAMAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAKAFQAIADAAgGIAUgCQA+gHAAACQADABAZgFIAigBQAfAAAAgCIBjgBQAAgCAoADQAsAEAEAAIAKAAQADAEAEgCIAIgCQACAHgDgBQgBAAgBAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgFAEgNAAQAAAAAAgBQAAAAgBAAQgBAAAAAAQgBAAgBAAIgFACQgEAAgDgCQgDgCgCAAQgNAHAAgEQgQACgIgCQAAgCgMABQgMACAAABQgLAAgKABQgCAFgGgCIgKgDQAAADgLAAQgKgHgCACIgDADIgFABQgDADgGABQgDAAAAAHQgMAAgCAIQgCAIAMAAQACADAKABQAKABADACQAAgFAHADIAKADQAAgEANACQAIABgDACIgFADQgCACgJAAQgIAAgEgCQAAABgHABQgGABgBAFQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgCADQgKAAgIACQgKADgHAAIgqADQgCAEgLAAIgRAAIgtACQAAABgfAEQggADgFgBQAAAGgzgBQAAABgIADIgJACQgYAAAAADQgFgBgOADIgiACQAAABgVAEIgYADQAAgDgKAHQgLAGAAACIAhAAIAbgEIATACQADAAAFgCQAEgCAFAAIAOgDQANgCAAACQAFABAHgFIAOABQAAAFALgHQAKgBARgDQAAgCAJAAQAGgBAFABQAGACAGgBQAGgCAFACQAAgDARgDQARgEAAAFQArAFAAgDIAJABQAGABAAADQgNAHgDgBQgFgBgKABQgLABAAADQAkgDBBACQANAAAaAEQAYADANAAQAlAAA5AKQArAFAAAFQAFAAAXAFQAZAFAAADIAIAAQAEAAABgEQAJgDAFAAQAFAAAFACQAAABAIACQAIACAAACQATAAAZAOQAPASgBAAQAAAGASAAIgLgKQgIgHAJAAQAGAAAJAFQAJAFAFAAQAqAWAEAAQAAABAPAEQAOADAAADQADAAAHAEQAIADADAAQAAABAoAOIAZAOQASALAAAHQAEAEAFACQAAACAJAIQAKAIAAADQAHAMACAAQAAADAEAGQAEAGAAAEQABAAACAHIACAJQAEAAAFATQAFATADAAIAJAUQAFAMAAAKQACAAAFAbQACAAAGAXIANAyIAHAaQAHAXgDAAQACAGADApQABADgCAFIgCAIQgCAAAAAGIAAAJQgCAAgDAIIgDAJQgDABgFAPIgFAPQgBADgDAAIgDAAIgBAGQgBAAAAAAQgBABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgIAAIAAAEQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgEACgBAGQgCAAgDAGQgDADgCgFQgHABgFAFQgEAAgCAIQgCAIgCABQAAAHgGADQgGADgGgCQABANgJgDQgMgEgCAEIAAAMQgCABgDADIgCADIgEACQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAGQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQgJgCAAABIgKAEQgEAAgCADQgCAAAAAFQgBAFACAAQgBAKgNABQAAgDgIgBIgLgCIgGADQgGACAAADQAAADgMACQgEABgKAFQgKAFAAADQgCAAgNAHQgNAHAAACQgFACgDAHQgCAFgHgCQAAACgDAEQABAAACAEQACADAAACQgGACgLgDQgLgDgFABIABAKQAAAGgFAAQgCgDgEACQgBABAAAAQAAABAAABQgBAAABABQAAAAABAAQADACABADQgEACgFAAIgJAAQgCAAgHgFQgHgEgFAFIgDAGQgBACgEABIgHAEIgFADQgBAFgJAAIgPgBQAAAHgJADQgLADgCADIgDADQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAgBgBQgCgDgDAAQgEgBAAAEQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAIAAAGIgMABQgDAAgGAFQgEADgDgHQgDgBgDAFQgDAEAAAEQgFAAgFADQgFADAAAEIgGgBIgHABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAADQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgEAAIgPADQgFAGgHACIgPACQAAAAgBAAQAAABAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAADABAGQAAAEgNgEIgHAFQgHAEAAADIgJgBQgEABgCAGIgJADQgHABgCgEQgGADgHAFIgMAIQAAAGgRgDQgSgDAAAIIgFgCQgBgBgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBAAgDAFQgDAEgCgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgGAHQgDAFgFgBIgEAAIgFACQAAAAgBABQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgFAFIgJAEQgHADABABIAYAAQAOgBAIgDQADgBAcgFQAYgFAAgDQADgBAFAGQAEAGAEgCIARgFQACgFAZgDQAAgBALgDIALgEIALgCQAJgBgBgDQARgHABAHIAPgGQAKgDAHABQgSALgFABIgpAUQABgGgKACQgIABgEAEIAEADQgEAAgUAIQgUAIAAACIgJABQgIACAAADQgFABgFgBIgJgDQgBAKgHgBQgMgBgCABQAAABgIABQgJAAABAEQgRAJgKABQgWADAAACIgIABQgGgBAAgBQgDgBgEABIgHACQgWAMAAgIQgDAAgEACQgFABgBADQgDgBgIADIgGADQAAABgVAEQgGAAgFAEQgGAEAKABQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIADABQAAgDARAAQAQgBAAgCQAIAAAWgHIAdgEIAkgGIAVgEQATgEAAABQAIAAAMgEIASgHQgBgBAOgFIAQgEIAVgIQAPgHAEAFIgUAKIgRAHQgGABgLAGQgMAFgEABQABADgKACIgNACQgKAGgLACQAAgCgMAIQgCAFgDgFIgDgDQgEABgFADQgFAEgDAAIgKADQgJABAAADQgFAAgGACQgGACgGAAQAAAJgLgMQgCAGgBAAQgDgFgJACIgLADQgFAGgBADQgFAAgEgDQgFgDgEgBQAAAFgGAEIgLAEQgXALgNgLQgMAEgDAAQAAAHgPAAQAAACgMADQgLADgEgBQAAgEgIAAIgMAAQgCAHgBAAIgHgBQAAACgVgBQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAADgJAAQAAgGgEAIIgDAEIgIAEQAAgEgHABIgIACQgCABgQAAQgOAAgBADIgYAAQgFAAgHgDIgMgDQgHAHgIAAIgRgDQAAABgKADQgKACAAABIgPACQgMACgEgEQAAgBgNAAIgRgBQAAAFgHgBIgKgCQAAADgPABIgFAAQgKAAAAgDgACUKCQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAdgDQAZgCABAEQABAAAAAAQABAAAAgBQAAAAABgBQAAAAABgBQACgDADAAIAEAAIADgBQAEgBAGABQAHAAADgBIAOgFQAJgCAHAEQABgGAEADIAFAFQADAAAFgFQADgGAEABIAHACQADAAAFgDQACgBAFAAIAHgCQAFgBABABIABAFQAEAAAEgGIAJgDIASgFIALgBQAHgBAEgDQALgFADAAQgFgBgPAEIgTAGIgfADQgPACgVgBIgWAEQgSACgBgEQgNACgBABQgKADgJgCQgKgDgNACIg1ADQgFABgCgFIgKADQgBgDgFgBQgIgBgCgCQgLAEgEgBQgMgDgagBIgagBQgFAAgJgCIgOgBIgMAAIgKgCIgBACQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgDgCgCABQgBgDgFgBIgHAAQgKgDgYgBIgOgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABIgDABQgLABgIgDIgFgDQgCgCgDABIgNAAQAAgCgFAAIgHAAQgDgBgEAAIgIAAQgEAAgDgCIgGgEIgPgDQgJgBgEgEQgFgEgBAAQgCACgEAAIgKgCQgGgBgEABQgBgEgMgDQgIgCgGAAQgDABgDgDQgCgCgDABQgDAAgGgBIgKgEQACABgSgIQgQgHAEgBQgCgBgHAAQgGABgDgCQgIgEADgCIgQgFQgDgBgPADQgRADgOgBIApAdQARgBALAEIANAFQAIgBAMAGIAMAFQAKAEAAACIAHgCQADgBACADIAGAHQACgBAIgBQAJgBABADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIASAGQADACAFAAIAIABIASAFQAEACAFABIAJABQAQAEAjAEQA8ALA6AFIAbACQARABALACIAhABQADgBALACIAQABIAMgBQAIgBAEACQABAAAAAAQAAAAABAAQAAAAABgBQABAAAAAAIABgBQABAAAAAAQAAABABAAQAAAAAAAAQAAABABAAgAGCH/IgCgHQAAgDAHAAQABABAHgBQAHgBABgCIAPADQALACAAgEQAGgHAHAFIAMAHQAGAAAAgDQgBgEADgCIAHgCQACAAACAEQAIgIAQgBQAJAAAQABQAAgBAFgCIAGgDIARAAQAAgCAPAAQACAGAEAAQAAgGAIgBQAHgCAAACIAJgCIAJgCQAAAAABgBQAAAAABAAQAAgBABAAQABAAABAAQADAAACgDQALgFAIADQACAAATgEIAGACQAAAAABAAQAAgBABAAQAAAAAAgBQABgBAAgBQAAgBAAgBQABgBAAAAQAAAAABAAQABgBAAABQAFACABgBQAAgCAPgDIARgDQABgCAOgFQANgFAEAAQADABAEgEQAEgDADAAQAAgDAQAAQAGABALgHQAGAAALgFQALgGAGAAQACgDANgEQANgFAFAAQABgCAMgEQALgDAAgBIAVgIQADAAAEgCQAEgDAEAAIAKgEIAHgDQAEgCAEgBQABgDAGgBQAGgCACgCQAEAAAIgDQAJgEACgCQAEAAAHgEQAHgEADgEQAFAAAJgFQAIgFAGAAIAYgMQAAgBAVgIQAWgJACgDQAFAAAJgFQAIgGAGAAQAFAAAGgGQAHgHADAAQAEAAAGgGQAHgGADAAQAHAAAKgIQAEgCAHgHQAAgBAGgCQAGgCAAgCQgHAAAGgCQAFgCADAAQAAgEAJgBQAHgBADABQAAgDADgEQADgFAAgFIAQAAQAAgEAEgCIAIgFIANgIQAAgFAMgGQALgGAAgCQAMgCADgDQAGgEADgJQAFgBAQgbQAMgGAGgKIACgEQABgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAQADAAAFgJQAFgKAFAAQADgFAAgJQAFgDgBgEQABAAACgMQACgNACAAQAAgBgCgFIgEgGQAAAHgLAAIgFAGQgEAGACAAQAAADgHAGQgIAFAAACIgFAGIgGAIQgDAAgFAFIgIAFIgFADQgFADABAEIgJADIgHADIADAAIgBAEQADAAgMAKQgDADgIAAQgHABgCACQAFAAgFAHQgFAGgEAAQgJAMgOADQgEAIgOAFIgCACQgBAAgBAAQAAABgBAAQAAABAAAAQAAABAAAAIgKABQgCABAAAHQgbAFAAAGQgPALAAABIgJADQgGACgEAAQAAADgFACQgEACgEAAQgEgGgEAHQgEAHgCABQAAACgKAGIgMAGQgEABgIAGQgJAGAAAEQAAACgMAEIgQACQAAAEgJACQgJABABAEQAAABgaAFQAAAHgOAGQgLAFgKABQAAgFgOAHIgOAGQgDAAgJAEQgIAEAAABQgEAAgHADQgHADgEAAQAAACgJAEQgIADgCgBIgBADIgBADQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgDABgCgCQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAFIgDAAIgCgBQAAADgFABQgGABAAABQgEACgCgBQgDAAgDACQgDADgMAAIgIAGQAAABgKADIgNADQgNAGgDAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAAAABIgYAKQgYAGgGAEQAAADgXAAIgHAEQgEABgBAFQgFACgEgBIAAAFIgPAAQAAAGgGABQgHACAAgCQgDAAgLAFQgJAEgFgBQAAgBgGACIgHACQgDADgIAAIgMgBQgCAEgLAAIgbAJQAAABgFACIgJADQgFADgKAAQgDgDgDACIgFAEIgKgDQAAAHgNABIgTABIgIABQgFACgBADIgMgBQgcALgDgBIgUACQgSADAAACIgPADIgOACIgHACQgFACAAABQgIAAgQACQgVAEgDAEQACgCATAAQAAAEAZAAQADgEALABIAQACQAAgEANACIAOABQACAAADADQADACADAAIAAAAgAn2HeQgCAEgDAAIANAKQAJAGAEAAIADgDQABAAAAgBQAAgBAAAAQgBgBAAAAQgBgBgBAAQgBgDgGgFIgKgFIgDgCIgCACgAAUGwQACAEACAAIAIACQAFABACgEIADgBQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAgBAHgBQAHgCAAgBQAigBAAgFIAGABQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAFgBANADIAJgDQAGgDADAEQACADAFgBQAFAAACgDQACgCAFACIAIACIgEgEIADgGIAKgCQAGAHAAgFIASABQAFgCAHgHQACgBAKABQAJABADgDQAEgEAHAAIALABQACgFALABIAOABQAAgDAHABIAJADQAAABAKgHQAKgBAOACQAAgIAPgBQAAgBAVgEQAVgFADABQABADAMAAQAMAAACgEIACgFQAEgEADAFQACABAEAAIAGAAQAAgIABgCQACgBAIABQABAEAHgDIALgDQAEgBAKAEIAIgEQAAgFANgDIARgCQAHgDAEgGQADgCAHABIALABIgBgFQAEAAABgCQACgDADgBQADgBADABIAHACQAAgCAPgCIASgBIgCgEIADgBQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAJgBAHgEQAJgHAFgCQAXAAADgFQANAAABgCQAGAAgDgGIAKgBIAEgGQABgBAAgBQABgBAAAAQABAAAAAAQAAAAAAAAQADABADgCQADgCADABQAAACAHAAQAHAAAAgCQAHAAAEgDIAJgIQAHgBAEAAQACgEAEABQAGACACAAQAAgBASgGIAUgIQgDgDABgCQACgCAFAAQADADAFgCIAIgDQAAgBAHgBQAHgBAAgDIAGACQAIgFgEAAQgBgDAPgEQAQgEAAgCQAHAAAHgDIAOgIQABgCAIABQAHABAAgEIADgDQABgCAFAAQAEAAAHgDQAAgBAKgDQAKgCADABQgBgFAFgDQAGgEACgDQAPABAAgDIAHABQAEAAABgEIAKgIQAAgDAIgEQAHgFAEAAIALAAQAAABATgLQAAgDAHgFIAIgFQAGAAAIgHQAIgIAFAAQAAADASgNQAIgGAKAAQAUgNAAgCIAWgPQALAAAMgIQADgHAEAAQADgDAJgDQAJgEACgDQAFAAADgGQADgHADAAIAKgHQABgDAEgEIAHgGIAGgCQAFgBABgCQAAgFANgGQAMgHgBgDQAVgZADgBIAHgPQAFgKgHgDQAAgCgHgEQgIgDgBgDQAAgDgEgCIgHgFQgMgLgGgDIgQgHQgNgHAAgDQgGAAgJgFQgKgGgEgBQAAgBgJgFIgKgHQgEgBgIgFQgHgFgEAAQAAgBgSgEQgUgHgDgDIgQgIIgKABQgHABgEgBIgFgCIgHgBQgRgLgDAAQAAABgSgHIgJgDQgDgEgGgCIgKgBQgtgKgGgBQgGgHgWADQgSACgDgEQgDgEgHAAQAAgBgOACQgPACAAgDIgTgBQAAgEgGgBQgHgHgIAEIgNAFQgHAAgKgEIgRgGQAAAFgXgBQgWgBAAgJQABgEgFgBQgEgBgFABQgCADgIgCQgBgBgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAADgJgBQADAHAAAEQAHAAACAeQACAcgCAIQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABABQAAAAAAAAQgBABAAAAIgBAUQgBATgEAAQgBADADADIgIAQIgGANQgFAIAAAGIgGAPQgFAOgHAAIABAFQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIAAAEQgCAAgCAGQgBAGgDAAIAAAEQAAABgBAAQAAAAAAABQAAAAgBABQgBAAAAABIgFAEIgBAHQgDAAgBAFQgBAAgGAIQgHAJgFABQgBADgIADQgIACABAFIgCAFIgCADQAAACgEAEIgGAFQAEAKgSACQgBAGgHAEQgIAGgCADQgFAIgTAJQgCABgDAEIgFAFQgJAAgRAOQgUARgFACIgNAFQgJAEAAAEIgLAHQgGAFgGABQAAgBgFAFQgFAEABAAIgKAFIgKAGQAAABgLADQgMADAAAEQgJAAgRANQgSAMgMAAIgKADQgIAEgBABIgJAHQgFAFgFAAQgeAKgEAAQAAACgJAGQgJAFAAgEQgEAAgHADQgHAEgDADIgLACQgFABgEAFQgFAAgKAGQgJAGgEAAQgDAFgVAAQgCADgDACQgEABgBACIgGABQgEABgCgCIgGgDQgHgBgGADIgKAIQgBAFgNAEQgDAAgIAFQgHAEgEAAQgsANgHAAQAAADgZAHQgaAIgDADQgTACghANQgHADgOAAQAAAGgPAAQAAACgVAGQABgGgiAKQgEAAgGACIgKAEQAAgBgMAEIgPAFQgIAGgMACIgWAFIAFAAIABABIARACQAOACABgDQAcAAASAEQAsgBAAAFQAFABAvgHQAHgDAHAEIANAHQAAgCAQgCIAUgCIAQgBQAEABACADgAqtGZQgHgMAAgBIAHAFIAGAEQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIADgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgGAAIgCgBIgBAAIAAgBQgDgDgDgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgDgBQgjAFAAgEIgJgBIgIgCQAAgEgOACIgQADQgGAJATADQAWADAAABIAVABQARAAAAACIASAAIAAAAgAopGGQgDABAAAFIADAEIAEAFIAHgBQALAAgJgLQgFgEgEAAgAmTFsIAIAOIAFAFIAOACQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAIAOgCQAJgCAEABIBCgLQAAgCAVgDIAYgEQBOgSAHAAQAAgBAXgGQAXgFAEAAQAAgDAWgEQAWgDACgEQAHAAAKgEQALgDAGgBQAGAAALgEIAQgFQACgDAdgHQAagGgBgHQAYgBAAgDQAJgBARgHQAAgBAJgCQAJgCAAgBQADAAADgCQABgBAAAAQABgBAAAAQABAAAAgBQAAAAAAgBIAGgBIAFABQAAgDAQgFQAOgEAFAAQACgDAJgDQAKgCAAgDQAEAAAIgDQAJgDACgDQAGAAALgEQAJgEAFgEQAGgFAPgDQABgCANgEQANgEAAgCIANgGIAOgHIAPgFQAKgEADgEQACAAAJgFQAIgEAAgBQAEAAAIgEQAIgFADgDQAKAAAOgKQAOgKAIgBQACgEAUgJQATgKgBgCQAAgBANgHQAOgHAAgBIAHgGQADgDAFgBQAKACAEgGIAEgIQAEgIAFAAQAAgBAFgEQAGgDAAgCQAFgBAIgHQAIgHAFgBQADAAACgFQACgFADgBIAIgFIALgKQAEgCAFgHQAFgHAEgCQAAgFAOgMIAOgRQACgEAFgIQAGgIACAAQABgGAFgHIAGgMQACAAACgFIACgGIACgHQACgGgBgDQgFAAgJAOQgKAQgEACQAAAGgMAJIgLAKQgGAHgEACQAAAFgHAFIgKAKQgBACgIAFQgHAEAAAEQgDABgDAEQgDAEgFABIgEAFQgEADgCAAIgHADIgIADQAAACgEADQgFAEgBADIgKAGQgHAGgBACQgDAAgJAGQgJAGgCADQgKADgQANQgPAMgMACQgFAGgMAEQgLAEgIAAIgOAOQgFAAgHAGQgHAFgDAAQgCAEgIABQgHABgDADIgHADIgGADQgCAAgEAEIgFADQgCAEgJAAQgJABgDAEQgEACgDAAQgCAEgIABIgNABIgJABQgGAAgDABQgDABgDAHQgDAGgEABQgEAEgFgCQgHgCgDABQAAAEgFACQAAAEgVAJIgbALQgDAAgFADQgFADgDAAQAAACgNACQgEAEgIADQgHACgGAAQAAACgNADQgNADAAADIgNACQgKACgCADQgGAAgCABQgDABgFAFQgHAAgGACIgNADIgWAHQgBACgKACQgKACAAACIgbAHQgFAAgIADQgIADgFAAQgCACgOAEQgNADAAABQgDAAgFADQgFADgDAAQgBACgGABQgFABgCgCQgRAHgCAAQgDADgNADIgMACQgEABgKAEQgIADgEAAQAAACgOAAIgQgCQAAABgJADIgMACQgPAAgMAFQAAAFgLACQgMABAAABIgXAAQgQAAgFAFIgDACIgDADIgJADIgHACQgCADgcAEQgcAFAAACIgFAAIgFAAgAxuEwQAAgCgHgCQgFgCgEAAQAAAGAQAAgAzoD+IgCADIAOALIAKACIALACQAEAHAcAKQAbAKAAgGQgOAAAAgHQgQgCAAgCIgUgKQgCAAgEgIQgEgHgGAAQAAgDgKgBIgKgBIAAAAIgGACgAmhD9QgJAEgBADQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAIADAAQAAACAsgFIA0gGQAAgDAWgEIAcgFQABgDANAAIARAAQAFAAARgGQANgEAIACQAAgCATgDIAWgEQAAgFALACQAMACAAgEIAKAAQAGAAADgEIAJgDQAFgGAQACQAQABACgFQgIAAAHgEQAGgEAEAAIANgBIAEACIAFABIASgEQAAgCgFABIgHABQgDgGAcgHQAXgHAKAAQAAgBALgCQALgBABgCIAHgCIAHAAIADADIAFABQAAgBAAgBQgBgBABAAQAAgBAAAAQABAAABAAQgCgFAEgBIAJgCIAKAGQAKAGADgBIgHgDIgDgKIAGgFQADgBAFACQACABAMgFQALgFAAAEQADABAEgCQAEgCAAgCQAOAAADgFQAAgJAJAAQACgEAKAAIANAAQAFgBADgEQADgEADAAIAVAAIAEgJQADgDAEABIAGADQgBgJAGABIALADQADAAAEgDQAEgEADAAQACgCAJgFQALgFABACQAAgHAUgCQAUgCAAgCQAIAAAFgBIAFgDIAGgDQACgDALgDQAMgDAAAGQAEABAOgEQAGgEABgFQgEAAAEgHIAFgIQAEgCAAgJIANgHQAJgFAGAAQABACAKACIAMACQAAAEAMgGQALgFACgEQgHAAgCgMQAFAAAMgPQASgEAAgCQAMgCAOgGIAWgKQAFgFARgHQAOgGADgHQAGgCANgOQALgMAHAAQACgDAFgDQAFgEACgDQACgCAHgGQAHgFAAgEQACAAAFgIQAFgHAAgCQAEAAAJgXQAKgXgCgFQgCAAAAgMQABgMgEgCIADAAQgBAAgDgHIgHgRIgSgBQAAACgPgEQgPgDAAADQgmAHAAgBQgLABAAgCIgIABQgFABgDgDIgHABIgJABQAAgBAAAAQAAAAgBAAQgBAAAAAAQgBAAgBABIgGABQAAAEgMABQgLABgFgBIgPgBIgDAFQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIgOABQgCAHgNgEIgUgGQgBACgIABQgFABAAAHQgYAAgEABQAAADgUABQgUABAAACIgZABQgLAAgDADIgBABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgQABQAAABgGACIgIABQAAgBgSADQgTACAAACIgMADQgIACgFAAIgJAIQAAAEgJgHQgDAAgBADIgCAFQgBADgEABIgGABQAAAEgMAAQgBACgEABQgEABgDADQgDADgGAAQAAgEgGABIgKACQAAAFgWgCQAAAGgJADQgLADgCACQgCAAgEADIgHAEQgEACgCgBQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgDAAgCgCQgEgCgCAAIgIADIgIACQgDgCgEACIgHADIgEAEQgEAEAAACQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABIgBAEIgEAFIgCAAQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgDABgCgCQgDgCgCABQgFAJgVACIgUAMQgKAEgEgDIAAgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAQAAgBgKAHQAAAHgEABIgIgCQgBgBgHADQgHADgBACQgFAAgDADQgDADABAEIgMACQgNADgEAFQgEAAgBAFIAAAGIgRAJQgEAGgIAAIgMgCQACAMgGACIgMAHQgMAIAAgFQgGgEgBADIAAAEQAAADgKAIQgLAGgEABQAAACgGAEIgKADQAAgGgFAEQgHAFACAAQAAAFgHAIQgGAHgFAEQgCAFgFADIgKAEQgJADgDgEIgIAHQgFAFAGAAIgCAHIgGAJQgFAGgCAAIgKAJQgHAHgCAEQgGAAgCADIgEAJQgEABgEAFIgGAHQACAEgZAYQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIAPgBIAqgFQAAAFARgHIAFAAIADgCQAAAAABAAQABgBAAAAQAAAAABAAQAAAAAAABIAEACQABgFAKgDIAJgEQAGAAAVgEQASgDAEAIQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAgBABAAQACgEACAAQAAgBAFABIAHAAQAAgBAGAAIAJgBQAAABAAAAQAAABABAAQAAAAABAAQABAAABAAQAAgKAqAAQAAgEAKgBIAOgBQAAgHAZgBQAZgCAAADQADgBAEgEQAEgDACAAQAAgCAHACIAIACQAAAHAVgMQAAgCAHgDIAJgCQAFAHAHgBIARgDIAOgBQAHgBAAgGQgEADgEAAQAAgEADgCQAEgCABgCIAOgCIAGgCQAAgFALAAIAPAAQAHAHAGgGQAJgKAEgBQAMAAAAgCQAFAAADAFQACAFgHAAQAAAEAHACQAGADAAgFQgEAAgBgDQAAgEAEAAQAAgCAKAAIAGgEQAFgCAAgDQAHAAAEgDQABgCAEABQAEABACgBQAEgHALAAQACABAHgDIAIgEQAVgLAAAFQALAAgDgBQgIgEgBgCQgHgCAGgCIAJgBIAFAGQACACAEABQAMAAAAgCIAYgLQAFAAAJgEQALgEAFAAQAAgEAMgEQAKgDAFAAQABgCAFgCQAFgCACgCQAQgEACAAQAEABADgDQAFgFADgBIAJgFQAHgDACAEQACADgLANQgEAAgHAGQgIAFgEAAQAAAFgNAGQgOAGgCAEQgCAEgKACQgIABgCAEQgEAAgHAFIgJAHQgcALAAgBIgTAPIgMAEIgLAEQgZAGgGAIQgGgBgGAEQgGADgEAAQAAABgMABQgLABAAAGIgQADQgLACgEAEQgMAGgHABQAAACgJADIgKAEIgEAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgKADQgEAGgJABIABADIgGACIgHACIgJAAQgFgBgEABIgKAGQgKAFAAgBQgIAAgPAFQgPAFgJAAQAAABgWAEQgWAEAAADQgdALAAgEQgEAAgIAFQgHAFgEAAIgQAFQgRAEgBABIgZAFIgkAJQgaAAgCAEIgIACIgIACQAAgDgUAHIgNAEQgIADgHAAQgKADgFAAIgTAAQgFAFgMAAQgNgCgFABQAAABgIACIgLADIgBgBIgIACgAz3D2QAEgHgIgCQAAgBgEgEIgFgFQgDAAgIgFQgHgEgEAAQgBgDgHgGQgHgGgDAAQAAgCgLgIQgLgIgEAAQACAFAGAIQAGAHAFADQANAKgCAAQADAFAGAAQAWATAAgCQACABAFgCQAAAHALAAgApzCuIAGAEQgEABgCADQgDAEADADQAFADgDADIgEAEQATgEAAgBQADgBAFABIAHACIAEgBIADgDIADgBIAKgCQgFgZACAAIgCgJQgCgGABgDIACgOQABgIABgEQADAAgBgIQgBgIgGgBIgMASQAAAFgGAJQgGAJABAEQgGADgCACIgEAJQgCAAgCAEIgDAFQAAAEgIgGQgBABAGAEgAnqBaQgEAAgDAIQgEAKgDABQgDAVgBAAIAAACQgDAAgDAUQgDAUACADQADgBAFgIIADgIQADgHACAAIAFgLQAEgIACAAIADgHQAEgFAAgDQACAAAEgJIAFgLIAIgGQAHgGAAgCQAEAAABgDIABgIQACAAACgDQABgEADAAQAIgJABgEQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIACgFQAIgFAHgLQAEAAAGgJQAFgJAGAAQAegLgOAAQAAgGAFgCIAJgDQAAgGAIgEQAIgEAAgFQAFgBADgEQAEgFADgBQACgDAMgGQALgFAAgEQAKgGAGAAQAAgEAIgFQAIgEAAgDIAGgEIAHgEIAHgFQADAAAIgHQAIgGABABIALgGQAIgFACgDQAHgFABgGQAFAAAGgBQAGgCAJgGQAAAHAMgIIAPgKQACAAAGgEIAHgGQABgBAIgDIAIgDQAhgKAAgDQAFAAAJgEQAIgDAGAAQABgEAFACQAHABACgIIAGgCQACAAAHgEQACgCAOgEQANgDAAgCIAJgDQAGgDAAgDQAQgCAAgBIAJgCQAHgCAAgBQAFAAAKgEQALgFAGgBQAAgBAIgDIALgCQA2gRAEAAQAAgBAOgDIAQgEQATABAAgGQAFAAALgDQAKgDAGAAIAfgIQAAgCAMgBIAOgBQAAgCAMgCQAMgBABgCQAEAAAGgCQAHgDAEAAIAMABQAHgBADgDQAXgCAKgDQAAgEAygEQADgFAeAAQASABARgEQAAgFA4gBIA+gBQAAgCAGABQABAAABAAQABAAAAgBQABAAAAgBQAAAAAAgBIADAAIgBgCQgEAAgEgIQgFgIgDAAQAAgDgHgHQgHgGAAgEQAHgCAJADQALADAAAIQAEABAFAEQAFAEACAEQADACAAAFIADABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAEADQAEgBAEABQAGABAMgBIAUAAIAmACQAhABAAABQAIABAHgBQAAgCAUACIAZADQArACAAACIAzAEQArAFAAAGQAKAAAUAFQAVAEAKAAQAAACAPADQAPACAAACQAHABAKAEQAJADAHABQADABAHADQAGADADAAQAAADAJAAQAKABABACIAcAJQAEAAAIAEQAJAEACADQAOAHAAgDIAEABIACACQAEAAALAGQALAGAAABQAFAAAIAGQAIAFAEAAQAAABAHAFQAHAEACAAQAAABAIADQAIAEABACQADADAKAFQAIAFADAEQAHAAgHgJQgGgKgFAAIgEgEQgEgDAAgCQgIAAgHgKQgEAAgKgJQgLgKAAgDIgLgBQgHgCAAgEIgDgCIgGgBQgIgIgCgBIgOgHQgGgEgHAAQgEgFgKgDQgEgBgBgCQgCgDgCgBQAAgCgSAAQAAgGgLgCIgPgCQgHAAgHgDQgIgEAAgEQgIAAgNgJQgNgKgHAAQAAgBgKgCIgKgBQgZgHAAgCIgPgDQgIgDgEAAQAAgEgdgGQgZgEgKAAQAAgCgOAAQgPgBAAgEIgXgDQAAgDgbgCIgbgDQgZgDgMAAQAAgBgMgBQgMgBgBgBIgbgBQAAADgogCQgBgCgOAAQgNgBAAACQgDABgGgBIgIgBQgRACgIgBIgKADQAAABgKAAIgMgBQAAADgVACQgVABgFgBIgwAEIg5AEQgFAAgYAEQgZAEAAACIgXACIgUADQAAAHgyACQAAADgkAGQgCADgJAAQgJAAgDAEQgFgBgGACIgJABQAAACgOABQgNABAAADIgeAJQgSAFgLAAIgdAKQgeAJgCgBQAAAEgNACQgOACgBAEIgOAEQgIACgFABQAAABgHADIgIACQAAABgKAEIgPADQgCAEgLADQgLADgCAEQgEAAgGADQgHAEgDAAQgVAFgFAHQgFAAgIAGQgJAGgFAAQgDADgHAEQgHAEgEAAQgCADgPAIQgEAAgJAHQgIAHgHgCQgBAEgJAAQgBAEgIADQgNAFgHAGIgPAJIgPAJIgJAIQgEAFgFAAQABgCgKAHQAAAGgYAPQgLAMgKAEQAAABgEADIgGAEQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAABgFAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQgDAEgMAHIgDAEIgEAEQAAADgEAEQgDAEgDAAIgFAHIgHAFQAAACgJAIQgDADgEACQgFABgDADQAAADgEACQAAADgDACIgGAEQgCACAAAEQAAAFgCACIgFADQgDAAgCADQgCAFgBAAQgBACgEAGQgEAFgCABQAAAGgJAGQgKAGAAAGQABAAgFARIABAIQgBAFgDABIgBABIAAAAIgBABgAxpmXQgDABgCACIgCAFQgHAAgCADQgCAAgGADQgFADgCACIgHADIgGADQgGAHgTAGQgCAEgKACQgKABgBADIgHAGQgGAFAAABQgOAAgBAHIgSAOQgEAAgPAKQgJAGgGAHQgCADgFADQgFADgCADQAAAHgIAEQgKAEgBAFQgCABgDAGQgCAEgDABQgBACgGAFQgFAEAAADIgJAJIgIALIgDACQACACAlgbQAmgdAHgBIAHgFQAEgDADAAQAAgBAEgCIADgEQgDgBAAgEIAMgBQAIgCACgCIADgCQAAgBABAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgCAGgDQAFgDACAAQACgDALgFQAJgEACgDQADAAAFgFIAHgHQAMgEABgBQADAAAHgEQAJgEADgBQACgCAHAAQAEABABgFQABgJANAAIAHgIQACgDAFABQAFABABgDQACAAAHgEQAHgFACgBQAAgCARgHQAQgHADABIgBgEQAGgBAHgEQAHgEAFgBIALgFQAHgEACgDQADAAAFgCIAHgDQACgCAFAAIAIABQACgFADgCQAGgHAPgDIAYgDQACgDAIgDQAIgDAEAAQAAgDAIACQACABAEgCIAGgEIAIgEQAEgCADAAQAEgGAOgEIAWgEQAGgBALgDQAOgEAAgDIAHgCIAFgDIAJABQAFgBAAgFQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAABgBIACgDIgGgDIgvAMIgCgBQAAACgLABQgKACAAABQgHAAgLAGQgLAGgGABIAAgDQgFAAgKADQgJADgFAAQgEgBgCADIgFAEQgEAEgCAAIgHgDIgIAEQgIADgBAEIADABQgBADgFAAQgEABACgEQgDAAgHADQgHADgEAAIgFACQgGADgBACIgDAFQgDABgDgBQgCAGgOAFQAAABgFABQgFAAAAABIgLACQgEABgCAHIgDABQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgKAAAAgCQgCAAgDACQgEADgCABIgOAHQgNAIACABIgNAGIgNgCIgDABgAlSlJQgFgDAKgGIALgHQAIgDAAgBQABgBABAAQAAAAABAAQABAAAAAAQAAABABABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQACACgOAJQgJAGgFAAIgEgBg");
	this.shape_1.setTransform(7.7928,27.7457,0.4948,0.4948);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABwDnIAAkXQAAgygageQgbgeguAAQgfAAgdAPQgdAPgkAjIAAFEIhjAAIAAnEIBjAAIAAA8IADAAQAdghAogSQAngSAqAAQBLAAAvAtQAxAxAABZIAAEWg");
	this.shape_2.setTransform(117.997,94.1892,0.4949,0.4949);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjCCoQhLhEAAhnQAAhiBNhCQBNhDBxgBQB2AABNBCQBNBBAABlQAABqhMBCQhMBDh4AAQh1AAhLhEgAh4hvQgvAqAABCQAABGAuAsQAtArBIABQBPgBAugqQAugrAAhIQAAhBgwgrQgxgrhKAAQhGAAguArg");
	this.shape_3.setTransform(90.4194,94.4243,0.4949,0.4949);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiqEwQhCgnAAg8QABgyAegeQAfgfBBgOQgygbAAgeQAAgWAWgRQAWgRAjgIIAAgCQg3gVgdgkQgbgjAAgyQAAhIA8gqQA7gqBkAAIDRAAIAABFIhoAAQAeAbAMAWQALAVAAAdQAAAbgPAeQgNAcgTARQgiAghdAPQgoAGgOAGQgXAJAAARQAAASAnAOQAiAMBQAOQBNAOAlAjQAhAfgBAuQAABEg/AmQg/AmhvAAQhmAAhBgmgAhtCYQggATAAAeQAAAiAkASQAkASBEAAQBBAAAlgRQAlgSAAgfQgBgmg7gUQgsgOg9AAQgyAAggATgAhIjvQgdAYAAAhQABAlAbAXQAcAXAtAAQApAAAcgYQAbgYAAglQAAgggdgYQgdgYgnAAQgpAAgeAZg");
	this.shape_4.setTransform(64.4501,100.1526,0.4949,0.4949);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABoAAQBmAAA5A+QA8BAAAB7IliAAQAYCHCQAAQBVAABbg2IAABXQguAcgsAMQgxAOg9AAQhxgBhEhJgAhPiAQgjAdgKA2ID9AAQgDg0gfgeQgggeg0AAQg4AAgiAdg");
	this.shape_5.setTransform(39.7057,94.4243,0.4949,0.4949);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ai3DnIAAnEIBkAAIAABoIACAAQBHhxBKAAQA6AAA/A1Ig1BNQgXgTgbgNQgagMgSAAQgzAAgjAoQgjApAAA6IAADsg");
	this.shape_6.setTransform(19.9101,94.1892,0.4949,0.4949);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Aj1DJQhahSAAh3QAAh3BchTQBfhVCUAAQCWAABfBVQBbBSAAB4QAAB3haBSQhfBXiYAAQiVAAhfhXgAitiYQhGA8AABcQAABcBGA9QBFA9BoAAQBpAABFg9QBFg8AAhdQAAhchFg8QhFg9hpAAQhoAAhFA9g");
	this.shape_7.setTransform(-9.6965,91.7272,0.4949,0.4949);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABnAAQBnAAA5A+QA8BAAAB7IljAAQAMBCArAjQAqAiBIAAQBUAABdg2IAABXQgwAcgrAMQgwAOg/AAQhvgBhFhJgAhQiAQgjAdgKA2ID+AAQgDg0gfgeQgggeg0AAQg4AAgjAdg");
	this.shape_8.setTransform(-41.7282,94.4243,0.4949,0.4949);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ai4DnIAAnEIBkAAIAABoIADAAQBHhxBKAAQA7AAA9A1Ig1BNQgWgTgbgNQgagMgSAAQgyAAgkAoQgkApAAA6IAADsg");
	this.shape_9.setTransform(-61.1773,94.1892,0.4949,0.4949);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ABFDgQgTgLgHgYQhAAuhHABQg2AAgkgiQgiggAAguQABg7A3gkQAfgUBVgbIBYgcIAAgYQAAgpgWgUQgWgTguAAQhZAAhHBLIAAhiQA7g+BtAAQBQABAxAjQA1AoAABKIAADoQAAAXATAAQARAAAkgYIAAA2QgjAVgTAHQgUAIgWAAQghAAgSgMgAhCAtQgxAbAAAkQABAcAUASQAVASAeAAQAsAAArgmIAAiDQhOAXggATg");
	this.shape_10.setTransform(-84.536,94.4243,0.4949,0.4949);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AjIDAQhRhQAAhnQAAiABhhUQBhhUCUAAQBcAAB7AuIAABXQg6gfg0gOQgzgOg3AAQhqAAhHA9QhHA+AABbQAABeBGA8QBGA7BwAAQBsAABug/IAABXQgzAYgwAMQg6AOhFAAQihAAhfhgg");
	this.shape_11.setTransform(-112.7818,91.9993,0.4949,0.4949);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CO_v_white, new cjs.Rectangle(-126.7,-7.3,264.2,124.39999999999999), null);


(lib.BUTTON = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAqIAlgqIglgpIAaAAIAmApIgmAqgAg2AqIAmgqIgmgpIAbAAIAlApIglAqg");
	this.shape.setTransform(30.575,6.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUA4QgMgFgIgIQgIgHgFgMQgEgLAAgNQAAgLAEgLQAFgMAHgHQAIgIALgGQALgEAMAAQANAAAKAEQALAFAHAJQAIAHAEANQAEALAAANIAAAGIhUAAQACALAIAIQAIAIAOAAIAIgBIAIgCIAIgDIAHgGIANAUQgJAIgMAEQgNAEgNAAQgMAAgLgEgAgKghQgFACgEAEIgFAIIgCAJIA3AAIgCgJIgFgIQgDgDgFgCQgGgDgHAAQgGAAgFACg");
	this.shape_1.setTransform(15.125,6.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AggA6IAAhwIAeAAIAAAPQAFgHAKgGQAJgFALgBIAAAeIgIgBIgIABIgIADIgHAEQgDACgBADIAABKg");
	this.shape_2.setTransform(5.475,6.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaA6QgHgDgGgEQgFgFgEgHQgEgHAAgKQAAgKAEgHQAEgGAFgEQAGgFAHgCQAHgCAHAAQALAAAJADQAKAEAFAHIAAgPQAAgJgHgGQgHgEgKgBQgTAAgPAOIgLgUQALgJANgFQANgEAMAAQAKAAAJACQAJACAGAGQAIAFAEAHQAEAJAAAMIAABJIgeAAIAAgMQgGAHgJAEQgJAEgLAAQgHAAgHgCgAgQAKQgFAEgBAJQABAIAFAEQAHAEAJABQAGgBAGgCQAHgCAEgFIAAgPQgEgEgHgDQgGgCgGAAQgJAAgHAEg");
	this.shape_3.setTransform(-5.45,6.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgQA4QgLgFgIgIQgIgIgEgLQgFgLAAgNQAAgMAFgLQAEgLAIgIQAIgIALgFQAMgEAMAAQARAAALAGQALAGAGAJIgUASQgIgMgQAAQgMAAgJAJQgJAJAAAOQAAAPAJAJQAJAJAMAAQAIAAAGgDQAGgDAEgGIAUASQgGAIgLAGQgLAHgRAAQgMAAgMgEg");
	this.shape_4.setTransform(-16.625,6.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgKBCQgIgIAAgPIAAg7IgTAAIAAgaIATAAIAAgfIAdAAIAAAfIAXAAIAAAaIgXAAIAAAzQAAAFADAEQACADAFAAIAGgBIAFgCIAGAXQgDADgGACQgHACgJAAQgPAAgIgIg");
	this.shape_5.setTransform(-31.375,4.775);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgUA4QgMgFgIgIQgIgHgFgMQgEgLAAgNQAAgLAEgLQAFgMAHgHQAIgIALgGQALgEAMAAQANAAAKAEQALAFAHAJQAIAHAEANQAEALAAANIAAAGIhUAAQACALAIAIQAIAIAOAAIAIgBIAIgCIAIgDIAHgGIANAUQgJAIgMAEQgNAEgNAAQgMAAgLgEgAgKghQgFACgEAEIgFAIIgCAJIA3AAIgCgJIgFgIQgDgDgFgCQgGgDgHAAQgGAAgFACg");
	this.shape_6.setTransform(-41.225,6.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgXBMQgPgGgLgKQgMgLgHgPQgGgPgBgTQABgSAGgPQAHgPAMgLQALgKAPgGQAPgGAQAAQANAAAKADQAKADAIAFQAIAFAGAGIALAOIgcAPQgFgIgKgHQgJgGgOAAQgJAAgJAEQgKAEgGAHQgGAHgEAJQgEAKAAAKQAAALAEAKQAEAJAGAHQAGAHAKAEQAJAEAJAAQALAAAJgEQAJgEAFgEIAAgTIgpAAIAAgdIBLAAIAAA8QgNAOgQAIQgRAIgWAAQgQAAgPgGg");
	this.shape_7.setTransform(-55.8,4.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// bkgd
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#00A7B5").s().p("Aq0C4IAAluITwAAIB6CtIh6DBg");
	this.shape_8.setTransform(-10.4,5.9758,1,1.0587);

	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(1));

	// shad
	this.instance = new lib.Buttonshad();
	this.instance.setTransform(-80,-14,0.6438,0.6815);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BUTTON, new cjs.Rectangle(-96.8,-14,166.2,59.3), null);


(lib.BKGDblue = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#256BA2").s().p("A3ZKVIAA0pMAuzAAAIAAUpg");
	this.shape.setTransform(0,66.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGDblue, new cjs.Rectangle(-149.7,0,299.5,132.2), null);


(lib.BKGD = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF8300").s().p("A96WbMAAAgs1MA71AAAMAAAAs1g");
	this.shape.setTransform(0.0067,125.0449,0.7833,0.8714);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BKGD, new cjs.Rectangle(-150,0,300,250.1), null);


(lib.HEAD2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD2type();
	this.instance.setTransform(6,50,1,1,0,0,0,0,36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-133,14,278,68.5), null);


(lib.HEAD1b = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1btype();
	this.instance.setTransform(0,25,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1b, new cjs.Rectangle(-139,1,278,68.5), null);


(lib.HEAD1a = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD1atype();
	this.instance.setTransform(0,23,1,1,0,0,0,0,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1a, new cjs.Rectangle(-139,-1,278,68.5), null);


// stage content:
(lib.CO_SchoolisBack_300x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,338];
	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_338 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(338).call(this.frame_338).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,2,0,3).p("EgXWguyMAutAAAMAAABdlMgutAAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(339));

	// HS logo
	this.instance = new lib.HS_logowhite();
	this.instance.setTransform(149.9,557.9,0.3322,0.332,0,0,0,1.2,72);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(339));

	// CO logo
	this.instance_1 = new lib.CO_v_white();
	this.instance_1.setTransform(240.05,558.45,0.35,0.35,0,0,0,0.1,55.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(339));

	// CTA
	this.instance_2 = new lib.BUTTON();
	this.instance_2.setTransform(-27.3,556.95,0.76,0.76,0,0,0,-10.4,3.9);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(323).to({_off:false},0).to({x:52.7},15,cjs.Ease.quadOut).wait(1));

	// BKGD-orange
	this.instance_3 = new lib.BKGD();
	this.instance_3.setTransform(150,600,1,0.34,0,0,0,0,250);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(339));

	// HEAD1a
	this.instance_4 = new lib.HEAD1a();
	this.instance_4.setTransform(146,450.55,1,1,0,0,0,0,24);
	this.instance_4.alpha = 0.6992;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(4).to({_off:false},0).to({alpha:1},8).wait(87).to({alpha:0},7).to({_off:true},1).wait(232));

	// HEAD1b
	this.instance_5 = new lib.HEAD1b();
	this.instance_5.setTransform(146.1,448.55,1,1,0,0,0,0,24);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(113).to({_off:false},0).to({alpha:1},7).wait(123).to({alpha:0},8).to({_off:true},1).wait(87));

	// HEAD2
	this.instance_6 = new lib.HEAD2();
	this.instance_6.setTransform(140.1,447.8,1,1,0,0,0,0,36);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(261).to({_off:false},0).to({alpha:1},8).wait(70));

	// BKGD-blue
	this.instance_7 = new lib.BKGDblue();
	this.instance_7.setTransform(149.75,475,1,1,0,0,0,0,69);
	this.instance_7.alpha = 0.6992;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(339));

	// Layer_2
	this.instance_8 = new lib.sch_img_300x600();
	this.instance_8.setTransform(1,1);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(339));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(57.1,299.5,243.9,301.5);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 300,
	height: 600,
	fps: 36,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/CO_SchoolisBack_300x600_atlas_P_1.png", id:"CO_SchoolisBack_300x600_atlas_P_1"},
		{src:"images/CO_SchoolisBack_300x600_atlas_NP_1.jpg", id:"CO_SchoolisBack_300x600_atlas_NP_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;